### ISSUE TITLE
Could not find libsndfile

### ISSUE THREAD

**Issue by arunpatala** [facebookresearch/wav2letter#1]
When running cd wav2letter && luarocks make rocks/wav2letter-scm-1.rockspec && cd .. I get the following error:
CMake Error at cmake/FindSndFile.cmake:60 (message):
  Could not find libsndfile

Is anybody else facing similar issue. I am running  ubuntu 16.04.

**Comment by chbrian** [comment]
I had this issue. Installing libsndfile-dev can fix it.

> apt-get install libsndfile-dev

**Comment by byuns9334** [comment]
@chbrian  thank you so much bro!!! you saved me
