### ISSUE TITLE
Flac Issue in create.lua

### ISSUE THREAD

**Issue by DenisPeskov** [facebookresearch/wav2letter#10]
**Background/Use Case**
At the moment, I'm simply interested in using it for pre-trained decoding.  (I'd ideally extract the lattice/confidences as well if possible with your flags).

System: Mac El Capitan, CPU

**Assumptions Made in Installation:**
Skipped MKL install since not training
Boost installed through brew install
Skipped MPI installs since not planning on training again
Skipped CUDNN and CUNN installs since CPU (test.lau currently requires this, but I commented those relevant parts out).  

I'm currently stuck at **Training wav2letter models**

luajit issue with flac data
I throughly followed the installation instructions per the README.   To ultimately run the decoder, I need a librispeech-proc/letters.lst file, which I assume is generated by:

luajit ~/wav2letter/data/librispeech/create.lua...

However, downloading and unpacking everything as required, this command claims that my .flac files are in an "unimplemented format".  

**As far as I understood, downloading all of the LibriSpeech data is needed to decode, since you need to create letters.lst.
Perhaps you could upload a letters.lst file for LibriSpeech, and then none of this will be necessary?**

Thank you!

**Comment by saisrinivas047** [comment]
@DenisPeskov 

I have the same problem. Can you tell me how did you get the librispeech-proc folder ??
PS-I am running pretrained model on single CPU

**Comment by DenisPeskov** [comment]
Thanks for that list. Numeric values have to be added as well I believe (0-9).

I have the proper libraries and the flac files are not seen; I'll comment in the other thread where you posted about create-sz though.
