### ISSUE TITLE
Build error: wav2letter Unknown CMake command "find_dependency"

### ISSUE THREAD

**Issue by Bancherd-DeLong** [facebookresearch/wav2letter#100]
Hi:
I am using ubuntu 16.04 gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11),  While building wav2letter, got the following error.

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GTest: /usr/lib/libgtest.a  
-- GTest found (library: /usr/lib/libgtest.a include: /usr/include)
-- ArrayFire found (include: /opt/arrayfire/include, library: ArrayFire::afcuda)
-- Found Glog: /usr/local/include  
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- GLOG found
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- OpenMP found
flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_intel_thread: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- MKL found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found FFTW: /usr/local/include  
-- FFTW found
CMake Error at src/feature/CMakeLists.txt:24 (find_dependency):
  Unknown CMake command "find_dependency".
Call Stack (most recent call first):
  src/feature/CMakeLists.txt:31 (findAndCheckSndFileDependency)

-- Configuring incomplete, errors occurred!
Any suggestions?  Thank you.

P.S 4/7 tests failed during "make test" (flashlight)

**Comment by Bancherd-DeLong** [comment]
Sorry, I am away from my machine.  I will get back to the machine asap.  Thank you for looking into this.

**Comment by jacobkahn** [comment]
Fixed in 4609b03019509a0b18c2b17b65833a5a68781934. Thanks for reporting.
