### ISSUE TITLE
lack of  GTest

### ISSUE THREAD

**Issue by zhengqun** [facebookresearch/wav2letter#110]
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- GTest not found
CMake Error at src/tests/CMakeLists.txt:10 (message):
  GTest required to build tests

**Comment by jacobkahn** [comment]
For now, you need to build/install [GTest and GMock](https://github.com/google/googletest) yourself when building wav2letter++ (this may change in the future). You can use your system's package manager or build directly from source/Github.
