### ISSUE TITLE
cpu_version  flashlight.h cant found

### ISSUE THREAD

**Issue by ccnankai** [facebookresearch/wav2letter#112]
When I compile the cpu version, comment  the flashlight code in cmakelists   ,
error appears  when executing the make command. 
How can I change it? 

![1](https://user-images.githubusercontent.com/33537489/50588220-0ca08e00-0ebc-11e9-88cc-65e058ce0c65.jpg)

**Comment by jacobkahn** [comment]
@ccnankai — have you completed the `install` step for flashlight (`sudo make install`)? What is the exact CMake command you're running for wav2letter++?

**Comment by ccnankai** [comment]
@jacobkahn   thank you for your kindly  answer.
the Optional Dependencies section  in the  Building Instructions describes: cpu version use optional OPENMP, not flashlight .so i did not install flashlight.
I understand it wrong .

**Comment by jacobkahn** [comment]
@ccnankai — if you want to use the CPU backend for training, you'll need to build/install flashlight with `FLASHLIGHT_BACKEND=CPU`. The compiler will only attempt to link OpenMP if you build wav2letter++ with `CRITERION_BACKEND=CPU`, which you need to do if you're using the flashlight CPU backend/don't have CUDA on your machine.

**Comment by ccnankai** [comment]
@jacobkahn 
I am a newbie, thank you for your detailed instructions.

**Comment by ccnankai** [comment]
Hi @jacobkahn 

Thank you for your help, I built the wav2letter  in the  docker environment  provided by dockerfile in flashlight ,  compiled successfully.
![aaa](https://user-images.githubusercontent.com/33537489/50684387-4efad400-1050-11e9-9b41-2bca54c99173.jpg)


I also want to ask you a question that has nothing to do with wav2letter. The code I wrote before is relatively short, and C++ is used less, so I debug it directly with IDE. If I run C++ code on the server, how to debug is easier, Is there any tool  for  debugging on linux ?

**Comment by jacobkahn** [comment]
@ccnankai — in general, C++ is best-debugged with C-style debugging techniques such as [GDB](https://www.gnu.org/software/gdb/) ([cuda-gdb](https://docs.nvidia.com/cuda/cuda-gdb/index.html) can also be useful for debugging CUDA). Some editors/IDEs also have facilities for debugging C++ and can be used with remote environments, such a [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/quickstart-debug-with-cplusplus?view=vs-2017) or Atom.
