### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by 943274923** [facebookresearch/wav2letter#114]
`13%]` Building CXX object CMakeFiles/Test.dir/src/feature/SpeechUtils.cpp.o
[ 13%] Building CXX object CMakeFiles/Test.dir/src/feature/TriFilterbank.cpp.o
[ 13%] Building CXX object CMakeFiles/Test.dir/src/feature/Windowing.cpp.o
[ 13%] Building CXX object CMakeFiles/Test.dir/src/decoder/Decoder.cpp.o
[ 13%] Building CXX object CMakeFiles/Test.dir/src/decoder/Trie.cpp.o
[ 13%] Building CXX object CMakeFiles/Test.dir/src/decoder/KenLM.cpp.o
[ 13%] Building CXX object CMakeFiles/Test.dir/src/module/W2lModule.cpp.o
[ 13%] Building CXX object ### _**CMakeFiles/Test.dir/src/runtime/Logger.cpp.o**_
[ 14%] Building CXX object CMakeFiles/Test.dir/src/runtime/Serial.cpp.o
[ 14%] Building CXX object CMakeFiles/Test.dir/src/runtime/SpeechStatMeter.cpp.o
[ 14%] Building CXX object CMakeFiles/Test.dir/src/runtime/Distributed.cpp.o
[ 14%] Linking CXX executable Test
[ 14%] Built target Test
Scanning dependencies of target Train
[ 14%] Building CXX object CMakeFiles/Train.dir/Train.cpp.o
[ 14%] Building CXX object CMakeFiles/Train.dir/src/common/Defines.cpp.o
[ 14%] Building CXX object CMakeFiles/Train.dir/src/common/Dictionary.cpp.o
[ 14%] Building CXX object CMakeFiles/Train.dir/src/common/Transforms.cpp.o
[ 14%] Building CXX object CMakeFiles/Train.dir/src/common/Utils.cpp.o
[ 15%] Building CXX object CMakeFiles/Train.dir/src/criterion/ConnectionistTemporalCriterion.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
CMakeFiles/Train.dir/build.make:182: recipe for target 'CMakeFiles/Train.dir/src/criterion/ConnectionistTemporalCriterion.cpp.o' failed
make[2]: *** [CMakeFiles/Train.dir/src/criterion/ConnectionistTemporalCriterion.cpp.o] Error 4
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/Train.dir/all' failed
make[1]: *** [CMakeFiles/Train.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jacobkahn** [comment]
This type of error is generally due to an OOM error with CMake, or some other internal system error. I'd start by trying to run `make `with fewer threads. Feel free to reopen if you have evidence this is an issue with wav2letter++.

**Comment by 943274923** [comment]
> This type of error is generally due to an OOM error with CMake, or some other internal system error. I'd start by trying to run `make `with fewer threads. Feel free to reopen if you have evidence this is an issue with wav2letter++.

think you very much,   i try to run make -j 8 ,it failed

[ 25%] Linking CXX executable DctTest
[ 25%] Building CXX object src/tests/CMakeFiles/DitherTest.dir/__/runtime/Distributed.cpp.o
[ 25%] Building CXX object src/tests/CMakeFiles/CeplifterTest.dir/__/runtime/Distributed.cpp.o
[ 25%] Building CXX object src/tests/CMakeFiles/W2lCommonTest.dir/__/data/Featurize.cpp.o
[ 25%] Building CXX object src/tests/CMakeFiles/W2lModuleTest.dir/__/runtime/Distributed.cpp.o
[ 26%] Linking CXX executable SpeechUtilsTest
[ 26%] Building CXX object CMakeFiles/Train.dir/src/runtime/SpeechStatMeter.cpp.o
[ 26%] Building CXX object CMakeFiles/Test.dir/src/runtime/Distributed.cpp.o
[ 27%] Linking CXX executable DitherTest
[ 27%] Linking CXX executable CeplifterTest
[ 27%] Linking CXX executable W2lModuleTest
[ 30%] Built target DctTest
[ 30%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/feature/test/SoundTest.cpp.o
[ 30%] Building CXX object CMakeFiles/Train.dir/src/runtime/Distributed.cpp.o
[ 30%] Building CXX object src/tests/CMakeFiles/W2lCommonTest.dir/__/module/W2lModule.cpp.o
[ 32%] Built target SpeechUtilsTest
[ 32%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/attention/test/WindowTest.cpp.o
CMakeFiles/W2lModuleTest.dir/__/feature/Ceplifter.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/W2lModuleTest.dir/build.make:1142: recipe for target 'src/tests/W2lModuleTest' failed
make[2]: *** [src/tests/W2lModuleTest] Error 1
CMakeFiles/Makefile2:425: recipe for target 'src/tests/CMakeFiles/W2lModuleTest.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/W2lModuleTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 32%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/common/Defines.cpp.o
[ 32%] Linking CXX executable Test
[ 34%] Built target DitherTest
[ 35%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/common/Dictionary.cpp.o
[ 38%] Built target CeplifterTest
[ 39%] Building CXX object src/tests/CMakeFiles/W2lCommonTest.dir/__/runtime/Logger.cpp.o
[ 39%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/common/Defines.cpp.o
[ 39%] Linking CXX executable Train
[ 39%] Building CXX object src/tests/CMakeFiles/W2lCommonTest.dir/__/runtime/Serial.cpp.o
[ 39%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/common/Transforms.cpp.o
[ 39%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/common/Utils.cpp.o
CMakeFiles/Train.dir/src/feature/SpeechUtils.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
CMakeFiles/Train.dir/build.make:1139: recipe for target 'Train' failed
make[2]: *** [Train] Error 1
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/Train.dir/all' failed
make[1]: *** [CMakeFiles/Train.dir/all] Error 2
[ 39%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/ConnectionistTemporalCriterion.cpp.o
[ 40%] Built target Test
[ 40%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/common/Dictionary.cpp.o
[ 40%] Building CXX object src/tests/CMakeFiles/W2lCommonTest.dir/__/runtime/SpeechStatMeter.cpp.o
[ 40%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/common/Transforms.cpp.o
[ 40%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/common/Utils.cpp.o
[ 40%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/CriterionUtils.cpp.o
[ 40%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/ForceAlignmentCriterion.cpp.o
[ 40%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/FullConnectionCriterion.cpp.o
[ 41%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/ConnectionistTemporalCriterion.cpp.o
[ 41%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/CriterionUtils.cpp.o
[ 41%] Building CXX object src/tests/CMakeFiles/W2lCommonTest.dir/__/runtime/Distributed.cpp.o
[ 41%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/ForceAlignmentCriterion.cpp.o
[ 41%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/Seq2SeqCriterion.cpp.o
[ 41%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/backend/cuda/ConnectionistTemporalCriterion.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/attention/ContentAttention.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/FullConnectionCriterion.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/Seq2SeqCriterion.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/backend/cuda/ConnectionistTemporalCriterion.cpp.o
[ 42%] Linking CXX executable W2lCommonTest
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/attention/ContentAttention.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/attention/MedianWindow.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/attention/SoftWindow.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/attention/MedianWindow.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/attention/SoftWindow.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/criterion/attention/StepWindow.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/data/W2lDataset.cpp.o
[ 42%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/data/W2lNumberedFilesDataset.cpp.o
[ 43%] Built target W2lCommonTest
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/data/NumberedFilesLoader.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/criterion/attention/StepWindow.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/data/W2lDataset.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/data/Featurize.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/module/W2lModule.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/runtime/Logger.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/runtime/Serial.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/data/W2lNumberedFilesDataset.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/runtime/SpeechStatMeter.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/SoundTest.dir/__/runtime/Distributed.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/data/NumberedFilesLoader.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/data/Featurize.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/module/W2lModule.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/runtime/Logger.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/runtime/Serial.cpp.o
[ 43%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/runtime/SpeechStatMeter.cpp.o
[ 44%] Building CXX object src/tests/CMakeFiles/WindowTest.dir/__/runtime/Distributed.cpp.o
[ 44%] Linking CXX executable SoundTest
CMakeFiles/SoundTest.dir/__/data/Utils.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/SoundTest.dir/build.make:1142: recipe for target 'src/tests/SoundTest' failed
make[2]: *** [src/tests/SoundTest] Error 1
CMakeFiles/Makefile2:501: recipe for target 'src/tests/CMakeFiles/SoundTest.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/SoundTest.dir/all] Error 2
[ 44%] Linking CXX executable WindowTest
[ 46%] Built target WindowTest
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jacobkahn** [comment]
Responded in https://github.com/facebookresearch/wav2letter/issues/118

**Comment by shoegazerstella** [comment]
I am having the same issue.
I am building the Dockerfile so I don't have a wav2letter/build dir to clear.
