### ISSUE TITLE
Build failed on Ubuntu 16.04 [KenLM Problem]

### ISSUE THREAD

**Issue by misbullah** [facebookresearch/wav2letter#117]
Hi, I compile the toolkit use cmake by typing the following command.

cmake .. -DArrayFire_DIR=/home/asus/toolkit/arrayfire/share/ArrayFire/cmake -DINTEL_MKL_DIR=/opt/intel/mkl -DKENLM_LIB=/home/asus/toolkit/kenlm/build/lib -DKENLM_UTIL_LIB=/home/asus/toolkit/kenlm/util -DKENLM_INC=/home/asus/toolkit/kenlm/lm -DCMAKE_BUILD_TYPE=Release

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GTest: /usr/local/lib/libgtest.a  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- GTest found (library: /usr/local/lib/libgtest.a include: /usr/local/include)
-- ArrayFire found (include: /home/asus/toolkit/arrayfire/include, library: ArrayFire::afcuda)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GLOG found
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- OpenMP found
flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_intel_thread: /opt/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /opt/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- MKL found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found FFTW: /usr/local/include  
-- FFTW found
-- Found Ogg: /usr/lib/x86_64-linux-gnu/libogg.so (found version "1.3.2") 
-- Required SndFile dependency Ogg found.
-- Found Vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so (found version "1.3.5") 
-- Required SndFile dependency Vorbis found.
-- Found VorbisEnc: /usr/lib/x86_64-linux-gnu/libvorbisenc.so (found version "1.3.5") 
-- Required SndFile dependency VorbisEnc found.
-- Found FLAC: /usr/lib/x86_64-linux-gnu/libFLAC.so (found version "1.3.1") 
-- Required SndFile dependency FLAC found.
-- Looking for KenLM
-- Using kenlm library found in /home/asus/toolkit/kenlm/build/lib
-- Using kenlm utils library found in /home/asus/toolkit/kenlm/build/lib
-- kenlm lm/model.hh found in /home/asus/toolkit/kenlm/lm
-- Found kenlm: /home/asus/toolkit  
-- Found kenlm (include: /home/asus/toolkit, library: /home/asus/toolkit/kenlm/build/lib;/home/asus/toolkit/kenlm/util)
-- kenlm found
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.1.0") 
-- LZMA found (library: /usr/lib/x86_64-linux-gnu/liblzma.so include: /usr/include)
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- BZip2 found (library: /usr/lib/x86_64-linux-gnu/libbz2.so include: /usr/include)
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Z found (library: /usr/lib/x86_64-linux-gnu/libz.so include: /usr/include)
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- Adding warpctc:
-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "6.5") 
-- warpctc: cuda found TRUE
-- warpctc: using CUDA 9.0 or above
-- warpctc: Building shared library with GPU support
-- Configuring done
WARNING: Target "Decoder" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Decoder" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Test" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Test" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Train" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Train" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "wav2letter++" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "wav2letter++" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DctTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DctTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "CeplifterTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "CeplifterTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DitherTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DitherTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SpeechUtilsTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SpeechUtilsTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "W2lModuleTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "W2lModuleTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "W2lCommonTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "W2lCommonTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SoundTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SoundTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "WindowTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "WindowTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DerivativesTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DerivativesTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TriFilterbankTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TriFilterbankTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DecoderTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DecoderTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "CriterionTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "CriterionTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "RuntimeTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "RuntimeTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Seq2SeqTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "Seq2SeqTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DataTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "DataTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "AttentionTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "AttentionTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "MfccTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "MfccTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "PreEmphasisTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "PreEmphasisTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "WindowingTest" requests linking to directory "/home/asus/toolkit/kenlm/build/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "WindowingTest" requests linking to directory "/home/asus/toolkit/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/asus/toolkit/wav2letter/build

When I make wav2letter++, I got the following error:

asus@asus-M51AC:~/toolkit/wav2letter/build$ make wav2letter++
[  0%] Built target warpctc
Scanning dependencies of target wav2letter++
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Defines.cpp.o
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Dictionary.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Transforms.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Utils.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/ConnectionistTemporalCriterion.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/CriterionUtils.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/ForceAlignmentCriterion.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/FullConnectionCriterion.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cuda/ConnectionistTemporalCriterion.cpp.o
[ 20%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/ContentAttention.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/MedianWindow.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/SoftWindow.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/StepWindow.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/Utils.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lDataset.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lNumberedFilesDataset.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/NumberedFilesLoader.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/Featurize.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Ceplifter.cpp.o
[ 40%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Dct.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Derivatives.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Dither.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Mfcc.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Mfsc.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/PowerSpectrum.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/PreEmphasis.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Sound.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/SpeechUtils.cpp.o
[ 60%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/TriFilterbank.cpp.o
[ 80%] Building CXX object CMakeFiles/wav2letter++.dir/src/feature/Windowing.cpp.o
[ 80%] Building CXX object CMakeFiles/wav2letter++.dir/src/decoder/Decoder.cpp.o
In file included from /home/asus/toolkit/wav2letter/src/decoder/Decoder.hpp:11:0,
                 from /home/asus/toolkit/wav2letter/src/decoder/Decoder.cpp:17:
/home/asus/toolkit/wav2letter/src/decoder/LM.hpp:11:23: fatal error: lm/model.hh: No such file or directory
compilation terminated.
CMakeFiles/wav2letter++.dir/build.make:806: recipe for target 'CMakeFiles/wav2letter++.dir/src/decoder/Decoder.cpp.o' failed
make[3]: *** [CMakeFiles/wav2letter++.dir/src/decoder/Decoder.cpp.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
CMakeFiles/Makefile2:193: recipe for target 'CMakeFiles/wav2letter++.dir/rule' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/rule] Error 2
Makefile:212: recipe for target 'wav2letter++' failed
make: *** [wav2letter++] Error 2

But, the lm/model.hh found when I run cmake from above command.

Any suggestion?

**Comment by misbullah** [comment]
I solved the problem.

Thanks.

**Comment by smolendawid** [comment]
@misbullah how did you solve the problem?

**Comment by misbullah** [comment]
@smolendawid I just set path of KenLM as following:

export KENLM_ROOT_DIR=<path of KenLM>

Thanks
