### ISSUE TITLE
How to understand network structure [network.arch]

### ISSUE THREAD

**Issue by misbullah** [facebookresearch/wav2letter#119]
Hi,

How to modify network.arch for different configuration?

I checked in C++ code, there has several network structure that can be used for model training.
[wav2letter++/src/module/W2lModule.cpp]

Thanks.

**Comment by jacobkahn** [comment]
@misbullah — I'd take a look at the [docs for archfiles](https://github.com/facebookresearch/wav2letter/blob/master/docs/arch.md). They detail layers you can specify (which will be pulled in from flashlight). `W2lModule` is a simple wrapper around a [flashlight `Sequential`](https://fl.readthedocs.io/en/latest/modules.html#classfl_1_1_sequential).
