### ISSUE TITLE
results of the tutorial

### ISSUE THREAD

**Issue by zdgithub** [facebookresearch/wav2letter#122]
I executed the scripts step by step according to [the tutorial of librispeech-clean](https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean),
but I got the result whose format was not  the same to yours, 
```
|T|: as a sample of the press comments against the brutality of the missourians i quote a paragraph from the quincy argus march sixteenth eighteen thirty nine 
|P|: e as a sample of the press comments gains of the brutality of the miseries i had a paragraph from the quincy argus march sixteenth eighteen thirty nine 
[sample: 1094, WER: 19.2308%, LER: 10.4575%, slice WER: 18.8305%, slice LER: 9.25109%, progress: 99.6914%]
|T|: the vicious character of sin is brought out by the words who gave himself for our sins 
|P|: the vicious character of sin is brought out by the words who gave himself for our sins 
[sample: 866, WER: 0%, LER: 0%, slice WER: 18.7843%, slice LER: 9.22947%, progress: 100%]

```
I don't know the meanings of the slice WER , slice LER and progress. Do you have any instructions?

**Comment by tiru1930** [comment]
@zdgithub  , Though it is not answer to above issue, i just want to know if you can provide any installation script or proper procedure on linux env

**Comment by zdgithub** [comment]
I followed [the building instructions](https://github.com/facebookresearch/wav2letter/blob/master/docs/installation.md), installing all the dependencies and setting their environment variables one by one according to their readme documents.
All build/install instructions of these dependencies can be found.

**Comment by vineelpratap** [comment]
@zdgithub - 
```
|T|: as a sample of the press comments against the brutality of the missourians i quote a paragraph from the quincy argus march sixteenth eighteen thirty nine 
|P|: e as a sample of the press comments gains of the brutality of the miseries i had a paragraph from the quincy argus march sixteenth eighteen thirty nine 
[sample: 1094, WER: 19.2308%, LER: 10.4575%, slice WER: 18.8305%, slice LER: 9.25109%, progress: 99.6914%]
```

In the above example,
|T| - True transcription
|P| - predicted transcription.
WER - Word Error Rate for current sample
slice-WER - Overall Word Error Rate in the current thread. (Note that for decoding we divide the work using a ThreadPool)
