### ISSUE TITLE
 flag 'flagfile' was defined more than once 

### ISSUE THREAD

**Issue by 943274923** [facebookresearch/wav2letter#125]
when i use ./Train train --flagsfile /data/a/wav2letter/tutorials/1-librispeech_clean/train.cfg

ERROR: flag 'flagfile' was defined more than once (in files '/data/a/wav2letter/gflags/src/gflags.cc' and '/data/a/gflags/src/gflags.cc').

**Comment by vineelpratap** [comment]
It looks like you have two installations of 'gflags' in the system - `/data/a/wav2letter/gflags/` and `/data/a/gflags/`. Can you make sure there is only one  while linking and building with CMake.

**Comment by zhengqun** [comment]
i have the same error

**Comment by zhengqun** [comment]
root@84cc24bc8f20:~/wav2letter/build# ./Train train --flagsfile train.cfg
ERROR: flag 'flagfile' was defined more than once (in files '/home/zquse/gflags/src/gflags.cc' and '/tmp/gflags/src/gflags.cc').
I have the same error ,i have delete /home/zquse......,but still error

**Comment by zhengqun** [comment]
@943274923 @vineelpratap

**Comment by zhengqun** [comment]
I have rm  -rf gflags , and  build it again ,but still have this error.  another version?  I use 2.2.0

**Comment by 943274923** [comment]
> I have rm -rf gflags , and build it again ,but still have this error. another version? I use 2.2.0
You can try  2.1.X

**Comment by zhengqun** [comment]
@943274923 still have this error .how do you deal it?
