### ISSUE TITLE
CMake cannot find package configuration file for "SndFile"

### ISSUE THREAD

**Issue by ai-zahran** [facebookresearch/wav2letter#126]
## Description
CMake cannot find the configuration file for SndFile.

Command used:
```bash
$ cmake $WAV2LETTER_SRC_DIR -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CUDA
```

Output:
```
CMake Error at src/feature/CMakeLists.txt:36 (find_package):
  By not providing "FindSndFile.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SndFile", but
  CMake did not find one.

  Could not find a package configuration file provided by "SndFile" with any
  of the following names:

    SndFileConfig.cmake
    sndfile-config.cmake

  Add the installation prefix of "SndFile" to CMAKE_PREFIX_PATH or set
  "SndFile_DIR" to a directory containing one of the above files.  If
  "SndFile" provides a separate development package or SDK, be sure it has
  been installed.
```

When filename **cmake/FindSNDFILE.cmake** is changed to **cmake/FindSndFile.cmake**, CMake finds SndFile correctly.

```
-- Found SNDFILE: /usr/local/include  
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.so include: /usr/local/include
```

## System details
- OS: Ubuntu 16.04
- cmake version 3.5.1
- libsndfile was installed using autotools
- libsndfile library location: /usr/local/lib
- libsndfile include directory location: /usr/local/include

**Comment by jacobkahn** [comment]
@ai-zahran — none of the generated paths present in `FindSNDFILE.cmake` are actually used in the build anymore, so one should remove the file (I'll send a fix removing it shortly). If you've installed libsndfile properly via CMake, then the target should be found by the build automatically.
