### ISSUE TITLE
decode information

### ISSUE THREAD

**Issue by 943274923** [facebookresearch/wav2letter#129]
1.how to get the  decoding information like:
`[Decode data/test-clean (2620 samples) in 199.436s (actual decoding time 0.177s/sample) -- WER: 18.9687, LER: 8.71737]`
i use ./Decode  
```
|T|: the vicious character of sin is brought out by the words who gave himself for our sins
|P|: the vicious character of sin has brought out by the words who gave himself for sins
[sample: 866, WER: 11.7647%, LER: 6.97674%, slice WER: 21.4409%, slice LER: 10.6423%, progress: 100%]
```
2.And  why it so slow when i use `mpirun -n 8 ./Decoder --flagsfile /data//librispeech_clean/decode.cfg` 
How to improve the decoding speed

**Comment by jacobkahn** [comment]
@943274923:
1. The line you mentioned is printed after decoding completes, and is logged to stderr. If you're not seeing it, try running with gflags' `--logtostderr=1` flag.

2. Decoding currently runs on the CPU, and is pretty dependent on the number of cores you have. I wouldn't recommend running it with `mpirun`, as there's no distributed decoding capabilities at this time. You can, however, tweak the number of threads the decoder uses with the [`nthread_decoder` flag](https://github.com/facebookresearch/wav2letter/blob/efdc4ebfedcf9e275a426ee4f62c581f666959ba/Decode.cpp#L403). This is generally best set to a value close to the number of cores you have.
