### ISSUE TITLE
Current pre-trained model?

### ISSUE THREAD

**Issue by nh2** [facebookresearch/wav2letter#130]
The current version seems to no longer link the pre-trained model mentioned in #29 #88.

Is there a new/current pre-trained model available?

**Comment by vineelpratap** [comment]
Hi, 
 Currently it is not available. We plan to open-source within few weeks.

**Comment by nh2** [comment]
Thanks, eagerly looking forward to it!

When it's done, could you post here, so that subscribers will notice?

**Comment by zdgithub** [comment]
As there isn't a pre-trained model,
how many epochs do I need to achieve the result on librispeech dataset in paper?

**Comment by pastorenick** [comment]
Hey guys, is there a reason why pre-trained models are not accessible anymore anywhere?

> Hi,
> Currently it is not available. We plan to open-source within few weeks.

This was posted on the 10th of January, BTW.

**Comment by Venryx** [comment]
Any update?

If a pre-trained model was close to being available all the way back in January, surely some progress has been made on that front by this point?

**Comment by tlikhomanenko** [comment]
@Venryx 

Right now, please, check them here https://github.com/facebookresearch/wav2letter/tree/master/models

**Comment by gemfield** [comment]
@tlikhomanenko this link is broken too, any update?
