### ISSUE TITLE
How to recognize live voice from microphone

### ISSUE THREAD

**Issue by auvilink** [facebookresearch/wav2letter#132]
Hi, there,

Should I finish training the acoustic model, how to use wav2letter to recognize live voice continuously from microphone? 

Any examples would be highly appreciated.

Thanks.

**Comment by vineelpratap** [comment]
As mentioned in #120, open sourcing streaming recognition is in our future plans but we can't guarantee any timelines as of now.

**Comment by ariefsaferman** [comment]
Hei, can we use it now? using wav2letter model to recognize live voice continously from mic?
