### ISSUE TITLE
Out of memory on trying to train on librispeech

### ISSUE THREAD

**Issue by kfmn** [facebookresearch/wav2letter#133]
Hi, I have a trouble running Train to train model on librispeech data.
I have prepared data successfully.
But when I am running training I obtain the following error (at the very beginning, just after loading tokens):
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function void* cuda::MemoryManager::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:191
CUDA Error (2): out of memory

I use Ubuntu 16.04, CUDA Toolkit 9.2, GPU driver 410.79 and a single GPU Tesla K80 with 11441K memory. ArrayFire was installed from binary got at https://arrayfire.com/download/ 
Initially I used the network.arch from the recipe config dir, then I tried to delete several layers but this did not help.

**Comment by vineelpratap** [comment]
Hi, 
 It might be because the model is too big to train on the GPU. Can you try a smaller architecture architecture. (For example - https://github.com/facebookresearch/wav2letter/blob/master/tutorials/1-librispeech_clean/network.arch )

You can find details about defining the architecture [here](https://github.com/facebookresearch/wav2letter/blob/master/docs/arch.md).

**Comment by kfmn** [comment]
Thanks for your answer.
It seems the reason was the incorrectly formed tokens.txt. After re-generating it training started successfully.

**Comment by sanjaykasturia** [comment]
> Thanks for your answer.
> It seems the reason was the incorrectly formed tokens.txt. After re-generating it training started successfully.

I am seeing the same error but tokens.txt appears ok. It is a small file with a character per line. I am attaching the tokens.txt that I have. Can you share the regenerated tokens.txt if it is different?
[tokens.txt](https://github.com/facebookresearch/wav2letter/files/3010949/tokens.txt)
