### ISSUE TITLE
How can i test single audio file with the trained model on tutorial data set?

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/wav2letter#135]

**Comment by jacobkahn** [comment]
@tiru1930 — what does the dataset look like? The simplest way is to put that audio file in a directory on its own, and set your data directory to point there.

If you can't do that, I'd have a look at [`NumberedFilesLoader`](https://github.com/facebookresearch/wav2letter/blob/master/src/data/NumberedFilesLoader.h); you can get a single file via `get` and hack `NumberedDatasetLoader` to only look at that file.

**Comment by tiru1930** [comment]
@jacobkahn , I was able to test singel audio file which is .flac and 16kHz file ,  Below i have posted  the files
epbot@ai-tiru-new-exp:~/w2l/data/single-clean/flack$ ls -rlt
total 120
-rw-rw-r-- 1 epbot epbot      0 Jan 10 07:47 000000001.tkn
-rw-rw-r-- 1 epbot epbot      0 Jan 10 07:48 000000001.wrd
-rw-rw-r-- 1 epbot epbot 119728 Jan 10 12:20 000000001.flac
epbot@ai-tiru-new-exp:~/w2l/data/single-clean/flack$ pwd
Here .tkn and .wrd are just empty files , which are used not break the decoder execution

Now i am trying to write HTTP interface for this decoder where i need load all the models when i start my decoder HTTP server  , so that when new audio file is uploaded to HTTP server , text conversion time will get reduced.

Can you tell which files i need look so that i can load the model before i start decoder HTTP server.

**Comment by jacobkahn** [comment]
@tiru1930 — I'm not exactly sure what you're asking, but in order to run the decoder, you'll need a language model file (if you want to use one) in addition to network emissions. You can try starting the decoder minimally regardless; it should tell you what you're missing. [Check here](https://git.io/fhnQQ) for more details on those flags.

**Comment by GabrielLin** [comment]
@tiru1930  I understand what you mean. That is also what I want. Have you found your solution?
