### ISSUE TITLE
could not found libri-speech folder

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#14]
Hi in the running decoder section there is a librispeech-proc folder but i could not find any folder in my system. Can anyone please help.

PS: I am trying to run pre-trained model on cpu

**Comment by srk97** [comment]
Decoder works only with GPU. Although the authors said that they're working on converting their GPU models to CPU.

**Comment by VitaliyLi** [comment]
The folder is created with dataset preprocessing scripts. Please check out README file.
