### ISSUE TITLE
flags which are used for paper (wav2letter++)

### ISSUE THREAD

**Issue by hsh2438** [facebookresearch/wav2letter#140]
I have performed following tutorial.

But, error rate is too high, LER is higher than 10% and WER as well.

I want to test same performance in wav2letter++ paper.

Would you please provide flags?

**Comment by jacobkahn** [comment]
@hsh2438 — to which model are you referring: the fully-convolutional model (~100 million params), or the RNN model (~30 million params)? The WER reported in the paper is also after decoding. We didn't report raw WER numbers for the encoder.

**Comment by hsh2438** [comment]
I want to know both of cases, covolutional model and RNN model. Would you please share network file together? Thank you so much for your effort.

**Comment by jacobkahn** [comment]
@hsh2438 — here are the architecture files we used for each of the configurations.
[convrnn_10lyr_30mil.txt](https://github.com/facebookresearch/wav2letter/files/2756627/convrnn_10lyr_30mil.txt)
[conv_20lyr_100mil.txt](https://github.com/facebookresearch/wav2letter/files/2756628/conv_20lyr_100mil.txt)

**Comment by beknazar** [comment]
> @hsh2438 — here are the architecture files we used for each of the configurations.
> [convrnn_10lyr_30mil.txt](https://github.com/facebookresearch/wav2letter/files/2756627/convrnn_10lyr_30mil.txt)
> [conv_20lyr_100mil.txt](https://github.com/facebookresearch/wav2letter/files/2756628/conv_20lyr_100mil.txt)
@jacobkahn — in the arch files, does **H** mean seq2seq model? Can I use these architecture files while training/decoding/encoding stages? While training, I got parsing error

**Comment by vineelpratap** [comment]
It stands for `Tanh`. Can you replace `H` with `T`. (We changed it before releasing the code)
