### ISSUE TITLE
No output for 1hr (training)

### ISSUE THREAD

**Issue by realdoug** [facebookresearch/wav2letter#141]
```/root/wav2letter/build/Train train --flagsfile train.cfg```

I'm running the provided Dockerfile on a single NVIDIA Tesla P4 GPU & thus far the command has hung with no output for about 1hr.  Is this to be expected?  Happy to just let it run, but I'd rather find out sooner than later if I have an error.

How long should i reasonably expect before epoch 1 starts?

**Comment by zdgithub** [comment]
Yeah, and you can find the logs in your flagsfile --rundir directory
```
> ls [your rundir]/librispeech_clean_trainlogs
# 001_config  001_log  001_model_librispeech#dev-clean.bin  001_model_last.bin  001_perf
```

**Comment by jacobkahn** [comment]
@realdoug — can you try using `--logtostderr=1`? I'd check the logs as well. If you're seeing the beginning of the first epoch but not much more, I'd try changing `reportiters` or setting it a low value so you can see progress after some number of iterations.

**Comment by realdoug** [comment]
Thanks!  The ```reportiters``` flag creates output to the log file that can be monitored for progress.  Looks like its working fine.

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/51366236-70af8d00-1b1f-11e9-8007-7c08b6120b5f.png)

I have the same question
