### ISSUE TITLE
decoder failed

### ISSUE THREAD

**Issue by zhengqun** [facebookresearch/wav2letter#144]
![image](https://user-images.githubusercontent.com/34435100/51082026-38800700-1739-11e9-8d0d-14706b2919fe.png)

**Comment by zhengqun** [comment]
could you please tell me how can i do ?

**Comment by zhengqun** [comment]
cuda 9.2  cudnn7.4

**Comment by jacobkahn** [comment]
@zhengqun — looks like you're missing some dependencies for `libsndfile` — specifically, `ogg` and `vorbis` audio encoding libraries. Make sure you have all of the [dependencies listed here](https://github.com/erikd/libsndfile#hacking).

**Comment by jacobkahn** [comment]
@zhengqun — your installation of `libogg` and `libvorbis` must be incorrect. Can you tell me the output of `nm -D /usr/lib64/libvorbis.so | grep -i vorbis_synthesis_headerin` and `nm -D /usr/lib64/libogg.so | grep -i ogg_stream_init`? You may need to change the paths to each of those libraries depending on where the libraries are located. Which OS are you on?
