### ISSUE TITLE
bug: docker build error `'checkIndexBounds' was not declared in this scope`

### ISSUE THREAD

**Issue by AvielNiego** [facebookresearch/wav2letter#145]
I've tried running `docker build -f Dockerfile-CUDA .`
and got this error:
```
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/Utils.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lDataset.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lNumberedFilesDataset.cpp.o
/root/wav2letter/src/data/W2lDataset.cpp: In member function 'virtual std::vector<af::array> w2l::W2lDataset::get(int64_t) const':
/root/wav2letter/src/data/W2lDataset.cpp:42:23: error: 'checkIndexBounds' was not declared in this scope
   checkIndexBounds(idx);
                       ^
CMakeFiles/wav2letter++.dir/build.make:422: recipe for target 'CMakeFiles/wav2letter++.dir/src/data/W2lDataset.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/data/W2lDataset.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c export MKLROOT=/opt/intel/mkl && export KENLM_ROOT_DIR=/root/kenlm &&     cd /root/wav2letter && mkdir -p build &&     cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CUDA &&     make -j8' returned a non-zero code: 2

```

when i checked out to commit `fd2b33c31204836929caaa53578e1f99f9bb5901` everything worked fine

**Comment by jacobkahn** [comment]
@AvielNiego — this was a breaking API addition from flashlight - can you try recloning, building, and installing flashlight before building wav2letter++ again?

**Comment by tlikhomanenko** [comment]
@AvielNiego I will update the image for flashlight for the latest master state (the wav2letter Dockerfile is based on it). After that, you could build the image for wav2letter.

**Comment by beknazar** [comment]
> @AvielNiego I will update the image for flashlight for the latest master state (the wav2letter Dockerfile is based on it). After that, you could build the image for wav2letter.

Cool, we will wait for the updates.

**Comment by tlikhomanenko** [comment]
@AvielNiego @beknazar I have updated `Dockerfile-CUDA` in a way that it uses latest github version of `flashlight` during build. You can try to build image now.
