### ISSUE TITLE
Doubt of the training process in V100

### ISSUE THREAD

**Issue by drkingman** [facebookresearch/wav2letter#149]
I have tried the tutorial on a single GTX1080 GPU, and got a good result. When I am implmenting 500hrs librispeech data on a tesla V100 GPU, the model training process seems that it has to take some time(around 5-10 mins) to enable the computing power (Volatile OF GPU), which was quite fast (in seconds) when tested on GTX 1080 (also on 500hrs data).

I'm now not sure whether it may have influence on the training time. The V100 GPU driver version is 410.48, while GTX 1080 is 396.37.

**Comment by jacobkahn** [comment]
@drkingman — not sure what could be causing this. We've trained many models (including those benchmarked for our paper) on Tesla V100s. Are you running exactly the same training procedure on both GPUs? How large is the difference, and which CUDA versions are you using on each?

**Comment by drkingman** [comment]
Both procedure are running the same docker and CUDA 9.2. and the tranning time of one iteration on GTX1080 is around 22mins while it is around 24-26 mins on Tesla V100s.

**Comment by drkingman** [comment]
Actually I have tried the muti-gpu training process on 2 Tesla V100s this weekend, and the issue I mentioned did not happen, it was quite fast to fully enable the computing power.
