### ISSUE TITLE
train my own datasets

### ISSUE THREAD

**Issue by zhengqun** [facebookresearch/wav2letter#151]
hello ,  can i use  this poject to train chinese datasets ?

**Comment by zhengqun** [comment]
hello ,i want to know how can i process my chinese dataset? if i need to use /tutorials/1-librispeech_clean/prepare_data.py ? @wbgxx333 

![image](https://user-images.githubusercontent.com/34435100/51575396-ea16f900-1eec-11e9-8abc-95c1ae82de04.png)

**Comment by AlleyEli** [comment]
an you cat your wav.trn file?

**Comment by AlleyEli** [comment]
Can you cat your wav.trn file?

**Comment by zhengqun** [comment]
@AlleyEli  
![image](https://user-images.githubusercontent.com/34435100/51575767-6d851a00-1eee-11e9-90eb-6cafb7009d97.png)

**Comment by zhengqun** [comment]
I am a master of ucas .

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/51580624-19833100-1f00-11e9-8616-2b4145d31c6b.png)
encoding='utf-8'

**Comment by zhengqun** [comment]
@wbgxx333 thank you , i  want to try it use chinese datasets , i am a master  student

**Comment by zhengqun** [comment]
@AlleyEli  
![image](https://user-images.githubusercontent.com/34435100/51581523-61f01e00-1f03-11e9-8071-b573c16e6561.png)
 encoding error: .wav.trn is hard to tran

**Comment by AlleyEli** [comment]
please use python3 and
Is the trn encoding of your file 'utf-8' ?

```
16     with open(txt_file, "r", encoding="utf-8") as trnfile:
17         line = trnfile.readline()
18         print(line)

```

**Comment by AlleyEli** [comment]
Do you use python3 ?
> python3 xxx.py

**Comment by zhengqun** [comment]
@AlleyEli  yes python3 . i have meet the same error

**Comment by AlleyEli** [comment]
加微信[ LC_LUCKY666 ]直接聊吧!

**Comment by zhengqun** [comment]
![image](https://user-images.githubusercontent.com/34435100/51582008-3cfcaa80-1f05-11e9-8eb8-7ffbc8394872.png)

open it in windows 7

**Comment by aaronlyt** [comment]
how about the evaluation result

**Comment by kingdeewang** [comment]
can i ask how do you prepare the train.list?

**Comment by tlikhomanenko** [comment]
@kingdeewang,
please at first have a look here https://github.com/facebookresearch/wav2letter/wiki/Data-Preparation with all information about data preparation.

**Comment by bjl21012** [comment]
> @wbgxx333 thank you , i want to try it use chinese datasets , i am a master student
你训练的怎么样了？ 能用么
