### ISSUE TITLE
cmake for install wav2letter 

### ISSUE THREAD

**Issue by horsetmotiv** [facebookresearch/wav2letter#152]
please ask : 
Looking for cblas_sgemm
-- Looking for cblas_sgemm - found 
-- MKL library found
-- MKL found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found FFTW: /usr/include
-- FFTW found
-- Found Ogg: /usr/lib/x86_64-linux-gnu/libogg.so (found version "1.3.2")
-- Required SndFile dependency Ogg found.
-- Found Vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so (found version "1.3.5")
-- Required SndFile dependency Vorbis found.
-- Found VorbisEnc: /usr/lib/x86_64-linux-gnu/libvorbisenc.so (found version "1.3.5")
-- Required SndFile dependency VorbisEnc found.
-- Found FLAC: /usr/lib/x86_64-linux-gnu/libFLAC.so (found version "1.3.1")
-- Required SndFile dependency FLAC found.
-- Found SNDFILE: /usr/local/include
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.a include: /usr/local/include
-- libsndfile found.
-- Looking for KenLM
-- Using kenlm library found in /home/chen/software/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/chen/software/kenlm/build/lib/libkenlm.a
CMake Error at cmake/Findkenlm.cmake:73 (message):
  kenlm lm/model.hh not found; please set CMAKE_INCLUDE_PATH or KENLM_INC
Call Stack (most recent call first):
  src/decoder/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/chen/software/wav2letter/build/CMakeFiles/CMakeOutput.log".
See also "/home/chen/software/wav2letter/build/CMakeFiles/CMakeError.log".
chen@chen-VirtualBox:~/software/wav2letter/build$ make
make: *** 没有指明目标并且找不到 makefile。 停止。

I use the cmd at "cmake .. -DCMAKE_BUILD_TYPE=Release -DArrayFire_DIR=/home/chen/software/arrayfire/share/ArrayFire/cmake"

**Comment by wbgxx333** [comment]
you can export the kenlm path

**Comment by jacobkahn** [comment]
@horsetmotiv — `export KENLM_ROOT_DIR=[dir where you build kenlm]` will allow CMake to find it.

**Comment by horsetmotiv** [comment]
thank you very much
