### ISSUE TITLE
segmentation fault (core dump) 

### ISSUE THREAD

**Issue by zhengqun** [facebookresearch/wav2letter#153]
![image](https://user-images.githubusercontent.com/34435100/51303890-a85ffb80-1a71-11e9-88e1-f7e4e7bce557.png)

how can i do ?rebuild arrayfire ,flashlight,and wav2letter?

**Comment by wbgxx333** [comment]
--flagfile=/*/*/train.cfg

**Comment by jacobkahn** [comment]
@zhengqun — this is an issue with ArrayFire not detecting your GPU devices before wav2letter even initializes. Are you running the wav2letter CUDA Docker image? You'll notice that ArrayFire tests will also fail if you run them. I'd take a look at support for [ArrayFire](https://github.com/arrayfire/arrayfire) or for [NVIDIA Docker](https://github.com/NVIDIA/nvidia-docker).

**Comment by megharangaswamy** [comment]
@jacobkahn 

Hi,

I was able to train and now I want to run the test and Decode sections. I was able to run Test binary and create Emission set " **wav2letter#tutorials#output#data#test-clean#.bin** " .

I am trying to run Decoder now b yusing Emission set. Here is my command and the output I am getting. 

```
megha@megha-ERAZER-X4709-D-C519:/media/home/megha/5_wav2letter/WAV_2_LETTER/wav2letter/build$ /media/home/megha/5_wav2letter/WAV_2_LETTER/wav2letter/build/Decoder \
> -tokens wav2letter/tutorials/output/data/tokens.txt \
> -lexicon wav2letter/tutorials/output/lm/lexicon.txt \
> -emission_dir /media/home/megha/5_wav2letter/WAV_2_LETTER/librispeech_clean_trainlogs/my_emmision_dir/ wav2letter#tutorials#output#data#test-clean#.bin\
> -lm /media/home/megha/5_wav2letter/WAV_2_LETTER/wav2letter/tutorials/output/lm/3-gram.arpa \
> -datadir /media/home/megha/5_wav2letter/WAV_2_LETTER/ \
> -test wav2letter/tutorials/output/data/test-clean/ \
> -sclite /media/home/megha/5_wav2letter/WAV_2_LETTER/librispeech_clean_trainlogs/  \
> -lmweight 4 \
> -wordscore 2.2 \
> -maxload 50 \
> -beamsize 2500 \
> -beamscore 100 \
> -silweight -1 \
> -nthread_decoder 8 \
> -smearing max \
> -show \
> -showletters
*** Aborted at 1548241771 (unix time) try "date -d @1548241771" if you are using GNU date ***
PC: @           0x418023 main
*** SIGSEGV (@0x0) received by PID 22554 (TID 0x7f83f78b1800) from PID 0; stack trace: ***
    @     0x7f8377f574b0 (unknown)
    @           0x418023 main
    @     0x7f8377f42830 __libc_start_main
    @           0x459d49 _start
Segmentation fault


```

How to slove the Segmentation fault error ?

Thanks :)

**Comment by vineelpratap** [comment]
This is fixed recently in https://github.com/facebookresearch/wav2letter/commit/9edbbe877606a500ca398d8eeef46b69a52a0e8a .  Can you use the latest version of wav2letter++ and try again.

**Comment by vineelpratap** [comment]
The issue was with saving the emission set. So, emission set needs to be created again.

**Comment by megharangaswamy** [comment]
> The issue was with saving the emission set. So, emission set needs to be created again.

I created the emission set after I took the latest code and built all 3 binaries. Should I do the creation of emission set again?

**Comment by vineelpratap** [comment]
The issue with saving is fixed in https://github.com/facebookresearch/wav2letter/commit/9edbbe877606a500ca398d8eeef46b69a52a0e8a and https://github.com/facebookresearch/wav2letter/commit/d06c9ed0787e5161c49d1f3c1d23a032fdce83c2 .  Please make sure you have pulled in these changes.

Otherwise, can you post the backtrace output from gdb. I'll try to debug later today.
