### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by horsetmotiv** [facebookresearch/wav2letter#156]
Hello, 
trying to build wav2letter on Ubuntu, when I execute :

make  -j4

I get the error :
........
ogg_vorbis.c:(.text+0x16cd)：对‘vorbis_analysis_wrote’未定义的引用
ogg_vorbis.c:(.text+0x16e9)：对‘vorbis_analysis’未定义的引用
ogg_vorbis.c:(.text+0x16fb)：对‘vorbis_bitrate_addblock’未定义的引用
ogg_vorbis.c:(.text+0x171e)：对‘ogg_stream_packetin’未定义的引用
ogg_vorbis.c:(.text+0x1741)：对‘ogg_stream_pageout’未定义的引用
ogg_vorbis.c:(.text+0x17af)：对‘ogg_page_eos’未定义的引用
ogg_vorbis.c:(.text+0x17f1)：对‘vorbis_bitrate_flushpacket’未定义的引用
ogg_vorbis.c:(.text+0x1817)：对‘vorbis_analysis_blockout’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_write_s’中：
ogg_vorbis.c:(.text+0x18a0)：对‘vorbis_analysis_buffer’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_write_i’中：
ogg_vorbis.c:(.text+0x19b0)：对‘vorbis_analysis_buffer’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_write_f’中：
ogg_vorbis.c:(.text+0x1ac6)：对‘vorbis_analysis_buffer’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_write_d’中：
ogg_vorbis.c:(.text+0x1bc6)：对‘vorbis_analysis_buffer’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_end’中：
ogg_vorbis.c:(.text+0x1e62)：对‘vorbis_comment_clear’未定义的引用
ogg_vorbis.c:(.text+0x1e74)：对‘vorbis_info_clear’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘free_stream_set’中：
ogg_vorbis.c:(.text+0x1ef4)：对‘ogg_stream_clear’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘find_stream_processor’中：
ogg_vorbis.c:(.text+0x1f9b)：对‘ogg_page_serialno’未定义的引用
ogg_vorbis.c:(.text+0x2029)：对‘ogg_page_eos’未定义的引用
ogg_vorbis.c:(.text+0x214d)：对‘ogg_stream_init’未定义的引用
ogg_vorbis.c:(.text+0x2164)：对‘ogg_stream_pagein’未定义的引用
ogg_vorbis.c:(.text+0x217b)：对‘ogg_stream_packetout’未定义的引用
ogg_vorbis.c:(.text+0x21d3)：对‘vorbis_comment_init’未定义的引用
ogg_vorbis.c:(.text+0x21e5)：对‘vorbis_info_init’未定义的引用
ogg_vorbis.c:(.text+0x21fc)：对‘ogg_stream_packetout’未定义的引用
ogg_vorbis.c:(.text+0x220f)：对‘ogg_stream_clear’未定义的引用
ogg_vorbis.c:(.text+0x2224)：对‘ogg_stream_init’未定义的引用
ogg_vorbis.c:(.text+0x2230)：对‘ogg_page_eos’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_length_get_next_page’中：
ogg_vorbis.c:(.text+0x228b)：对‘ogg_sync_buffer’未定义的引用
ogg_vorbis.c:(.text+0x22c6)：对‘ogg_sync_wrote’未定义的引用
ogg_vorbis.c:(.text+0x22e2)：对‘ogg_sync_wrote’未定义的引用
ogg_vorbis.c:(.text+0x22f5)：对‘ogg_sync_pageout’未定义的引用
/usr/local/lib/libsndfile.a(ogg_vorbis.c.o)：在函数‘vorbis_length_aux’中：
ogg_vorbis.c:(.text+0x235c)：对‘ogg_sync_init’未定义的引用
ogg_vorbis.c:(.text+0x2409)：对‘ogg_stream_pagein’未定义的引用
ogg_vorbis.c:(.text+0x2464)：对‘vorbis_synthesis_headerin’未定义的引用
ogg_vorbis.c:(.text+0x24a1)：对‘ogg_stream_packetout’未定义的引用
ogg_vorbis.c:(.text+0x24ba)：对‘ogg_page_granulepos’未定义的引用
ogg_vorbis.c:(.text+0x2542)：对‘ogg_sync_clear’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/Decoder.dir/build.make:1132: recipe for target 'Decoder' failed
make[2]: *** [Decoder] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/Decoder.dir/all' failed
make[1]: *** [CMakeFiles/Decoder.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jacobkahn** [comment]
https://github.com/facebookresearch/wav2letter/issues/136
