### ISSUE TITLE
Pretrained librispeech model link

### ISSUE THREAD

**Issue by DamienLaineLinagora** [facebookresearch/wav2letter#159]
Greetings,

Where can i find the pretrained model based on librispeech data ?
https://facebook.ai/developers/tools/wav2letter page points to an anchor on https://github.com/facebookresearch/wav2letter#pre-trained-models where i'm stuck, unable to locate the download link.

Would you help us on this ?

**Comment by jacobkahn** [comment]
@DamienLaineLinagora — that link is old/broken (we're working on updating it), but we haven't yet released pre-trained models. We plan on releasing them in the next few weeks.
