### ISSUE TITLE
No rule to make target '/root/usr/lib/libkenlm.a', needed by 'libbeamer.so'. 

### ISSUE THREAD

**Issue by testphys** [facebookresearch/wav2letter#16]
I am new to lua and I run into an error I have not found any information on.

`luarocks make rocks/beamer-scm-1.rockspec
-- Using kenlm library /root/usr/lib/libkenlm.a
-- Using kenlm include path /kenlm
-- Found Torch7 in /root/usr
-- Configuring done
-- Generating done
-- Build files have been written to: /home/abetz/github/wav2letter/beamer/build.luarocks
make[2]: *** No rule to make target '/root/usr/lib/libkenlm.a', needed by 'libbeamer.so'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/beamer.dir/all' failed
make[1]: *** [CMakeFiles/beamer.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.`

**Comment by VitaliyLi** [comment]
Hi,

It seems a problem with KenLM toolkit.
Have you followed the exact steps described in README for installing [KenLM](https://github.com/facebookresearch/wav2letter#kenlm-language-model-toolkit)?

**Comment by testphys** [comment]
Indeed, I copied the library into the wrong directory. Thanks a lot.

**Comment by byuns9334** [comment]
@VitaliyLi @testphys  hi, i got the same error here, it seems like I downloaded KENLM into wrong path. Could you explain in detail about how to fix this? I don't know much about path stuffs :(
