### ISSUE TITLE
Cannot build Gloo backend without Gloo

### ISSUE THREAD

**Issue by GreatJiweix** [facebookresearch/wav2letter#163]
Dear author, I always report an error when installing flashlight. I have already installed gloo. How can I solve this problem? Thank you

-- Gloo not found
CMake Error at flashlight/distributed/CMakeLists.txt:32 (message):
  Cannot build Gloo backend without Gloo
Call Stack (most recent call first):
  CMakeLists.txt:230 (include)

**Comment by jacobkahn** [comment]
Duplicate with https://github.com/facebookresearch/flashlight/issues/26 - closing.
