### ISSUE TITLE
'Killed' when decoding 

### ISSUE THREAD

**Issue by wuzhonglijz** [facebookresearch/wav2letter#171]
Thanks for your toolkit. I have trained the model with tutorial sample dataset successfully.
According to the doc, next step is decoding.
But whatever i use `./Decoder --flagfile ./decode.cfg` 
or  `./Decoder \ -tokens xxx \ lexicon xxx \.....`
It can not be decode.
![image](https://user-images.githubusercontent.com/32999273/51651319-66313f80-1fc6-11e9-9769-558c5ed77101.png)
  

### I used hyperpara as follows:

./Decoder \
-tokens data/tokens.txt \
-lexicon /home/w2l/lm/lexicon.txt \
-am /root/wav2letter/trained_model/librispeech_clean_trainlogs/001_model_data#dev-clean.bin \
-lm /home/w2l/lm/3-gram.arpa \
-datadir /home/w2l/ \
-test data/test-clean/ \
-sclite /root/wav2letter/build/decode_log \
-lmweight 4 \
-wordscore 2.2 \
-maxload 50 \
-beamsize 2500 \
-beamscore 100 \
-silweight -1 \
-nthread_decoder 8 \
-smearing max \
-show \
-showletters
  
---

--datadir=/home/w2l/
--lexicon=/home/w2l/lm/lexicon.txt
--lm=/home/w2l/lm/3-gram.arpa
--am=/root/wav2letter/trained_model/librispeech_clean_trainlogs/001_model_data#dev-clean.bin
--test=data/test-clean
--lmweight=2.5
--wordscore=1
--beamsize=1000
--beamscore=25
--silweight=-0.5
--nthread=1
--nthread_decoder=8
--smearing=max
--show

**Comment by jacobkahn** [comment]
@wuzhonglijz — if no one else on your machine killed your process, then your kernel killed the process (likely due to memory usage/resource starvation). If you're on Linux, `/var/log/kern.log` sometimes contains more details on why the OS killed the process. Decreasing the number of threads on the decoder should alleviate memory pressure a bit.

**Comment by xtluo-ai** [comment]
@jacobkahn I run into the same problem when training using only 100 utterances, even after I decreased the number of threads to 1 and the number of layers of `conv_glu`. 

---
```
# train.cfg
# Training config for Librispeech using Gated ConvNets
--runname=test_conv_glu
--rundir=/prj/test_conv_glu
--tokensdir=/prj/
--archdir=/prj/test_conv_glu
--train=/prj/test_conv_glu/train.lst
--valid=/prj/test_conv_glu/valid.lst
--lexicon=/prj/phonemes_lexicon.txt
--arch=network.arch
--tokens=phonemes_tokens.txt
--criterion=asg
--lr=0.6
--lrcrit=0.006
--linseg=1
--momentum=0.8
--maxgradnorm=0.2
--replabel=2
--surround=|
--onorm=target
--sqnorm=true
--mfsc=true
--nthread=1
--batchsize=1
--transdiag=4
```
```
# network
V -1 1 NFEAT 0
WN 3 C NFEAT 400 13 1 170
GLU 2
DO 0.2
WN 3 C 200 440 14 1 0
GLU 2
DO 0.28051034614
WN 3 C 321 706 19 1 0
GLU 2
WN 3 C 565 1242 25 1 0
GLU 2
DO 0.551806308143
WN 3 C 826 1816 29 1 0
GLU 2
DO 0.590432749713
RO 2 0 3 1
WN 0 L 908 1816
GLU 0
DO 0.590432749713
WN 0 L 908 NLABEL
```

To me, the possible cause of this is that the number of tokens is too large, say 1.8k. Any idea?

Thanks.
