### ISSUE TITLE
redefinition of function Ignored Value

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/wav2letter#172]
While running "make" command to build wav2letter i ran this error.

[cat.txt](https://github.com/facebookresearch/wav2letter/files/2790432/cat.txt)

the error is saying that it is a redefinition of error
one in /usr/local/include/gtest/internal/gtest-internal.h:111:7
other in /usr/include/gmock/internal/gmock-generated-internal-utils.h:55:7

please help

**Comment by Stolaine** [comment]
i googled the problem and came to read something about "include guard" (https://en.wikipedia.org/wiki/Include_guard) but both the above mentioned files have that feature.

**Comment by jacobkahn** [comment]
@Stolaine — what OS are you on, and how did you install GTest/GMock?

**Comment by Stolaine** [comment]
> 
> 
> @Stolaine — what OS are you on, and how did you install GTest/GMock?

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

I installed gtest using this link (https://gist.github.com/Cartexius/4c437c084d6e388288201aadf9c8cdd5)

After installation of googletest there was a folder gmock inside it. so I didn't install gmock

**Comment by jacobkahn** [comment]
@Stolaine - it looks like you have versions of gmock/gtest headers installed - one in `/usr/local/include` and one in `/usr/include`. You'll need to remove both of those; CMake is finding both directories, and attempting to include both headers at once, which is causing the definition duplication.
