### ISSUE TITLE
thchs30_chinese_datasets test error

### ISSUE THREAD

**Issue by zhengqun** [facebookresearch/wav2letter#173]
![image](https://user-images.githubusercontent.com/34435100/51661582-444ab380-1fec-11e9-845e-efabfc823991.png)

**Comment by zhengqun** [comment]
decode  dev / train dataset no error

**Comment by jacobkahn** [comment]
@zhengqun — you're trying to run decoding through the `Test` binary - this is incorrect. `Test` is end-to-end/requires a trained acoustic model and input audio files. If you just want to decode using an lm/some lexicon, use the `Decode` binary.
