### ISSUE TITLE
issue with seq2seq

### ISSUE THREAD

**Issue by rohithkodali** [facebookresearch/wav2letter#178]
when i run make after all paths are set i get the following error related to seq2seq

[  2%] Performing update step for 'CUB'
[  2%] Built target warpctc
[  2%] No configure step for 'CUB'
[  2%] No build step for 'CUB'
[  2%] No install step for 'CUB'
[  2%] Completed 'CUB'
[  2%] Built target CUB
[  2%] Built target w2lCriterionCudaKernels
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cuda/ConnectionistTemporalClassificationCriterion.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/FullConnectionCriterion.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cuda/FullConnectionCriterion.cpp.o
In file included from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:0:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h: In member function ‘std::shared_ptr<fl::Embedding> w2l::Seq2SeqCriterion::embedding() const’:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:85:60: error: passing ‘const w2l::Seq2SeqCriterion’ as ‘this’ argument discards qualifiers [-fpermissive]
     return std::static_pointer_cast<fl::Embedding>(module(0));
                                                            ^
In file included from /usr/local/include/flashlight/nn/modules/Loss.h:20:0,
                 from /usr/local/include/flashlight/nn/modules/AdaptiveSoftMaxLoss.h:11,
                 from /usr/local/include/flashlight/nn/modules/modules.h:12,
                 from /usr/local/include/flashlight/nn/nn.h:22,
                 from /usr/local/include/flashlight/flashlight.h:16,
                 from /home/rohit/wav2letter/src/criterion/SequenceCriterion.h:11,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:12,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:
/usr/local/include/flashlight/nn/modules/Container.h:89:13: note:   in call to ‘fl::ModulePtr fl::Container::module(int)’
   ModulePtr module(int id);
             ^~~~~~
In file included from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:0:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h: In member function ‘std::shared_ptr<fl::RNN> w2l::Seq2SeqCriterion::decodeRNN() const’:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:89:54: error: passing ‘const w2l::Seq2SeqCriterion’ as ‘this’ argument discards qualifiers [-fpermissive]
     return std::static_pointer_cast<fl::RNN>(module(1));
                                                      ^
In file included from /usr/local/include/flashlight/nn/modules/Loss.h:20:0,
                 from /usr/local/include/flashlight/nn/modules/AdaptiveSoftMaxLoss.h:11,
                 from /usr/local/include/flashlight/nn/modules/modules.h:12,
                 from /usr/local/include/flashlight/nn/nn.h:22,
                 from /usr/local/include/flashlight/flashlight.h:16,
                 from /home/rohit/wav2letter/src/criterion/SequenceCriterion.h:11,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:12,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:
/usr/local/include/flashlight/nn/modules/Container.h:89:13: note:   in call to ‘fl::ModulePtr fl::Container::module(int)’
   ModulePtr module(int id);
             ^~~~~~
In file included from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:0:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h: In member function ‘std::shared_ptr<fl::Linear> w2l::Seq2SeqCriterion::linearOut() const’:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:93:57: error: passing ‘const w2l::Seq2SeqCriterion’ as ‘this’ argument discards qualifiers [-fpermissive]
     return std::static_pointer_cast<fl::Linear>(module(2));
                                                         ^
In file included from /usr/local/include/flashlight/nn/modules/Loss.h:20:0,
                 from /usr/local/include/flashlight/nn/modules/AdaptiveSoftMaxLoss.h:11,
                 from /usr/local/include/flashlight/nn/modules/modules.h:12,
                 from /usr/local/include/flashlight/nn/nn.h:22,
                 from /usr/local/include/flashlight/flashlight.h:16,
                 from /home/rohit/wav2letter/src/criterion/SequenceCriterion.h:11,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:12,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:
/usr/local/include/flashlight/nn/modules/Container.h:89:13: note:   in call to ‘fl::ModulePtr fl::Container::module(int)’
   ModulePtr module(int id);
             ^~~~~~
In file included from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:0:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h: In member function ‘std::shared_ptr<w2l::AttentionBase> w2l::Seq2SeqCriterion::attention() const’:
/home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:97:60: error: passing ‘const w2l::Seq2SeqCriterion’ as ‘this’ argument discards qualifiers [-fpermissive]
     return std::static_pointer_cast<AttentionBase>(module(3));
                                                            ^
In file included from /usr/local/include/flashlight/nn/modules/Loss.h:20:0,
                 from /usr/local/include/flashlight/nn/modules/AdaptiveSoftMaxLoss.h:11,
                 from /usr/local/include/flashlight/nn/modules/modules.h:12,
                 from /usr/local/include/flashlight/nn/nn.h:22,
                 from /usr/local/include/flashlight/flashlight.h:16,
                 from /home/rohit/wav2letter/src/criterion/SequenceCriterion.h:11,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.h:12,
                 from /home/rohit/wav2letter/src/criterion/Seq2SeqCriterion.cpp:9:
/usr/local/include/flashlight/nn/modules/Container.h:89:13: note:   in call to ‘fl::ModulePtr fl::Container::module(int)’
   ModulePtr module(int id);
             ^~~~~~
CMakeFiles/wav2letter++.dir/build.make:230: recipe for target 'CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

anyone else face the issue?

**Comment by jacobkahn** [comment]
@rohithkodali — I'll send a fix up shortly. What version of gcc/g++ of using?

**Comment by jacobkahn** [comment]
@rohithkodali — I just built with g++ 5.4.0 on Ubuntu 16.04, and didn't run into the issue. Can you pull from master and try again? There are a few updates Seq2seq criterion updates you might not have.

**Comment by jacobkahn** [comment]
@rohithkodali — after investigating a little further, this was a breaking API change with flashlight in https://github.com/facebookresearch/flashlight/commit/526ce3b78e1a4d86fb9f916dbc53b9fb39ba967f. If you reclone, rebuild, and reinstall flashlight, then rebuild wav2letter, everything should work.

**Comment by rohithkodali** [comment]
it worked with bove changes thanks @jacobkahn
