### ISSUE TITLE
docker for centos7

### ISSUE THREAD

**Issue by isaacleeai** [facebookresearch/wav2letter#180]
Will there be docker ( with CUDA backend ) for centos7 released soon?

**Comment by jacobkahn** [comment]
@isaacleeai — you should be able to run the existing Ubuntu Docker images on CentOS. If you're referring to a flashlight/w2l Docker image that is based on a CentOS image, this isn't a high priority for us; a few dependencies aren't up to date in `yum`, so everything is a bit more difficult to automate.

If you don't want to run the existing Docker image in CentOS, you should be able to get everything up and running yourself — we've consistently tested the build on CentOS 7.5. Feel free to follow up here if you're having trouble.
