### ISSUE TITLE
Unable to open dictionary file '[...]/data/tokens.txt'

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/wav2letter#182]
I installed wav2letter using docker file and when i was training the acoustic model i get the following error.
F0129 08:33:13.201216  2990 Utils.cpp:237] Unable to open dictionary file '[...]/data/tokens.txt'
*** Check failure stack trace: ***
    @     0x7efc3f3c25cd  google::LogMessage::Fail()
    @     0x7efc3f3c4433  google::LogMessage::SendToLog()
    @     0x7efc3f3c215b  google::LogMessage::Flush()
    @     0x7efc3f3c4e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x50ac66  w2l::createTokenDict()
    @           0x50ad49  w2l::createTokenDict()
    @           0x416d18  main
    @     0x7efc353a2830  __libc_start_main
    @           0x4563c9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by jacobkahn** [comment]
@Stolaine — the `[...]` at the beginning of the path is a placeholder - you need to fill in the actual path to your tokens file.

**Comment by Stolaine** [comment]
thanks @jacobkahn - it is working but I have another issue after this #187
