### ISSUE TITLE
loading AM file throw error while decoding

### ISSUE THREAD

**Issue by rohithkodali** [facebookresearch/wav2letter#183]
When i try to decode the "Decoder" throw error that the am file not exist, but the file exist in path

F0129 11:30:48.108448     1 Serial.h:52] File - './001_model_data#dev-clean.bin' does not exist.
*** Check failure stack trace: ***
    @     0x7f01946d35cd  google::LogMessage::Fail()
    @     0x7f01946d5433  google::LogMessage::SendToLog()
    @     0x7f01946d315b  google::LogMessage::Flush()
    @     0x7f01946d5e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x488d5a  w2l::W2lSerializer::load<>()
    @           0x417530  main
    @     0x7f013fd70830  __libc_start_main
    @           0x459b59  _start
    @              (nil)  (unknown)
*** Aborted at 1548761448 (unix time) try "date -d @1548761448" if you are using GNU date ***
PC: @     0x7f013fd87196 abort
*** SIGSEGV (@0x0) received by PID 1 (TID 0x7f019c4a9780) from PID 0; stack trace: ***
    @     0x7f01953f0390 (unknown)
    @     0x7f013fd87196 abort
    @     0x7f01946dc12c (unknown)
    @     0x7f01946d35cd google::LogMessage::Fail()
    @     0x7f01946d5433 google::LogMessage::SendToLog()
    @     0x7f01946d315b google::LogMessage::Flush()
    @     0x7f01946d5e1e google::LogMessageFatal::~LogMessageFatal()
    @           0x488d5a w2l::W2lSerializer::load<>()
    @           0x417530 main
    @     0x7f013fd70830 __libc_start_main
    @           0x459b59 _start
    @                0x0 (unknown)

**Comment by jacobkahn** [comment]
@rohithkodali — is `001_model_data#dev-clean.bin'` in the directory you're running `Decode` from? I'd update the am model path to be relative to `~` do you don't need to worry about where you're running your binary from.

**Comment by rohithkodali** [comment]
i have used docker for installation and the command i have used is this 

sudo docker run  -it wav2letter /root/wav2letter/build/Decoder --datadir=/home/rohit/LibriSpeech_Corpus/ --lexicon=/home/rohit/LibriSpeech_Corpus/lm/lexicon.txt --lm=/home/rohit/LibriSpeech_Corpus/lm/3-gram.arpa.bin --am=./001_model_data#dev-clean.bin --test=data/test-clean --tokensdir=/home/rohit/LibriSpeech_Corpus/ --tokens=data/tokens.txt --lmweight=2.5 --wordscore=1 --beamsize=1000 --beamscore=25 --silweight=-0.5 --nthread=1 --nthread_decoder=8 --smearing=max --show=true --batchsize=256


the AM exist in the path from where i'm running this command

**Comment by jacobkahn** [comment]
@rohithkodali — I'd still specify an absolute path/check the filename carefully, especially since you're using Docker, and it's hard to say what `.` will be relative to the binary when run.
