### ISSUE TITLE
Detail information to use external data for training

### ISSUE THREAD

**Issue by megharangaswamy** [facebookresearch/wav2letter#184]
Hi all,

I trained my model using Librispeech data set. Now I want to train it further to increase the accuracy. I have many personal audio files for English. Here are my questions.

1) If the audio file is with background music, will it affect training? Should I use them or not?
2) Should I have .wav or .flac file format for training as I saw in many places we used .flac file whereas in data preparation document .wav format is mentioned? 
3) can I find the scripts for preparing data for training? Currently, I have an audio file and respected transcripts. I need to write scripts to create all .tkn, .wrd, .id .
4) Is there any limit on the size or time for the audio files for training and inference? 

Thanks :)

**Comment by jacobkahn** [comment]
1. There's no simple answer here: having background music obviously introduces noise. While this can help the model generalize better in some cases, it may also have the opposite effect, and depends on a lot.
2. wav2letter can read wav, flac, and other audio formats (anything supported by libsndfile is usable) — you can use the `input` flag to specify the file format (`--input=wav` for wav files).
3. We have several scripts in `recipes` to prepare TIMIT/WSJ/Librispeech. I'd take a look at those for more on what format w2l expects.
4. There isn't a limit per se, but you'll obviously see performance degradations in dataset loading for audio files that are large. The frame size per-input is fixed, so AM training dynamics shouldn't change much regardless of file size.
