### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/wav2letter#187]
While i was training the acoustic model i am getting this error

I am using docker file to build wav2letter

```
*** Aborted at 1548926196 (unix time) try "date -d @1548926196" if you are using GNU date ***
PC: @     0x7f5616c7c6f9 mkldnn::impl::get_msec()
*** SIGILL (@0x7f5616c7c6f9) received by PID 2893 (TID 0x7f5619157bc0) from PID 382191353; stack trace: ***
    @     0x7f5610443390 (unknown)
    @     0x7f5616c7c6f9 mkldnn::impl::get_msec()
    @     0x7f5616cfa94f mkldnn::impl::cpu::gemm_convolution_fwd_t::pd_t::create_primitive()
    @           0x60817c fl::conv2d()
    @           0x5ea7d6 fl::Conv2D::forward()
    @           0x5f8b3f fl::UnaryModule::forward()
    @           0x5e97d2 fl::Sequential::forward()
    @           0x45a0db _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEERNS0_19FirstOrderOptimizerES9_biE4_clES2_S5_S7_S9_S9_bi.constprop.8772
    @           0x417cc2 main
    @     0x7f560de2a830 __libc_start_main
    @           0x4563c9 _start
    @                0x0 (unknown)
Illegal instruction (core dumped)
```

my train.cfg file is as follows

![screenshot 7](https://user-images.githubusercontent.com/35038791/52044304-dceeaf80-2567-11e9-8394-08f7b41a2396.png)

**Comment by jacobkahn** [comment]
@Stolaine — what is your host OS for the Docker image? Are you running things on an Intel CPU?

I'd try running tests from MKL-DNN separately to see if they pass — this doesn't appear to be a problem with wav2letter.

**Comment by Stolaine** [comment]
kernel name = Linux
kernel release = 4.15.0-44-generic
machine hardware name = x86_64
operating System = GNU/Linux

this is the details of my host os

how can I run MKL-DNN tests separately

**Comment by jacobkahn** [comment]
@Stolaine — I'd try the following:
1. Clone [MKL-DNN](https://github.com/intel/mkl-dnn/) on your machine (outside of Docker), built it, and run their tests.
2. If the above works, clone it inside Docker, build it, and see if tests pass there.

**Comment by Stolaine** [comment]
@jacobkahn The above error is not coming as for now. 
I set the LD_LIBRARY_PATH to /path/to/mkl-dnn/build/src/ by using below code
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/mkl-dnn/build/src`

but the training is running for quite a time and nothing is showing on the terminal. Is it normal to take long duration?? I am using CPU backend i.e. "docker" instead of "nvidia-docker"

**Comment by jacobkahn** [comment]
@Stolaine — training on the CPU is generally substantially slower than training on a GPU.

You can try some of the things in https://github.com/facebookresearch/wav2letter/issues/141 to see if anything is happening. Your CPU utilization should also be telling.

- CTC refers to [Connectionist Temporal Classification](ftp://ftp.idsia.ch/pub/juergen/icml2006.pdf), which is one of the loss functions we use for training the acoustic model.
- ASG refers to [Auto-SeGmentation](https://arxiv.org/pdf/1609.03193.pdf), a different loss we can use to train acoustic models. 

Very generally, the difference is that ASG features learnable parameters ('transitions' over the lattice), whereas CTC does not. ASG can thus be trained with gradient-based optimization methods, jointly. Further discussions [here](https://www.facebook.com/groups/717232008481207/permalink/938134059724333/) and [here](https://www.facebook.com/groups/717232008481207/permalink/938490883021984/) detail some of those differences.
