### ISSUE TITLE
Compilation error, need help!

### ISSUE THREAD

**Issue by qjchen1972** [facebookresearch/wav2letter#191]
I follow the installation instructions to install the necessary components. Then it is as follows:            Mkdir-p build & CD build           
CMake.. - DCMAKE_BUILD_TYPE = Release - DW2L_CRITERION_BACKEND = CPU 
Display the following information, I feel that there is no problem：

-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- OpenMP found
-- flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: /usr/local/lib/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- MKL found
-- FFTW found
-- Required SndFile dependency Ogg found.
-- Required SndFile dependency Vorbis found.
-- Required SndFile dependency VorbisEnc found.
-- Required SndFile dependency FLAC found.
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.so include: /usr/local/include
-- libsndfile found.
-- Looking for KenLM
-- Using kenlm library found in /root/facebook/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /root/facebook/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /root/facebook/kenlm/lm/model.hh
-- Found kenlm (include: /root/facebook/kenlm, library: /root/facebook/kenlm/build/lib/libkenlm.a;/root/facebook/kenlm/build/lib/libkenlm_util.a)
-- kenlm found
-- LZMA found (library: /usr/local/lib/liblzma.so include: /usr/local/include)
-- BZip2 found (library: /usr/local/lib/libbz2.a include: /usr/local/include)
-- Z found (library: /usr/local/lib/libz.so include: /usr/local/include)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/facebook/wav2letter/build

but I follow “ make -j4",  the mistake happened：

/root/facebook/wav2letter/src/common/Defines.h:21:21: error: 'cpp' is not a namespace-name
 namespace cpp = fl::cpp;                     
/root/facebook/wav2letter/src/common/Defines.h:21:24: error: expected namespace-name before ';' token  namespace cpp = fl::cpp;

**Comment by jacobkahn** [comment]
@qjchen1972 @BoneGoat - which OS/compiler are you using? I’ll send a fix shortly.

**Comment by jacobkahn** [comment]
@qjchen1972 @BoneGoat — what compilers are you using? I've been unable to reproduce an issue with gcc/g++ 6.3.0 and gcc/g++ 5.4.0, both on Ubuntu 16.04 and gcc/g++ 5.4.0 on CentOS 7.5.

**Comment by qjchen1972** [comment]
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

  @jacobkahn

**Comment by qjchen1972** [comment]
I reproduced the error and copied the displayed information. 

cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CPU
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)
-- Found Glog: /usr/local/include  
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- GLOG found
-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- OpenMP found
-- flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: /usr/local/lib/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- MKL found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found FFTW: /usr/local/include  
-- FFTW found
-- Found Ogg: /usr/local/lib/libogg.so (found version "1.3.0") 
-- Required SndFile dependency Ogg found.
-- Found Vorbis: /usr/local/lib/libvorbis.so (found version "1.3.3") 
-- Required SndFile dependency Vorbis found.
-- Found VorbisEnc: /usr/local/lib/libvorbisenc.so (found version "1.3.3") 
-- Required SndFile dependency VorbisEnc found.
-- Found FLAC: /usr/lib/x86_64-linux-gnu/libFLAC.so (found version "1.3.1") 
-- Required SndFile dependency FLAC found.
-- Found SNDFILE: /usr/local/include  
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.so include: /usr/local/include
-- libsndfile found.
-- Looking for KenLM
-- Using kenlm library found in /root/facebook/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /root/facebook/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /root/facebook/kenlm/lm/model.hh
-- Found kenlm: /root/facebook/kenlm  
-- Found kenlm (include: /root/facebook/kenlm, library: /root/facebook/kenlm/build/lib/libkenlm.a;/root/facebook/kenlm/build/lib/libkenlm_util.a)
-- kenlm found
-- Looking for lzma_auto_decoder in /usr/local/lib/liblzma.so
-- Looking for lzma_auto_decoder in /usr/local/lib/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/local/lib/liblzma.so
-- Looking for lzma_easy_encoder in /usr/local/lib/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/local/lib/liblzma.so
-- Looking for lzma_lzma_preset in /usr/local/lib/liblzma.so - found
-- Found LibLZMA: /usr/local/include (found version "5.2.2") 
-- LZMA found (library: /usr/local/lib/liblzma.so include: /usr/local/include)
-- Found BZip2: /usr/local/lib/libbz2.a (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- BZip2 found (library: /usr/local/lib/libbz2.a include: /usr/local/include)
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.11") 
-- Z found (library: /usr/local/lib/libz.so include: /usr/local/include)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/facebook/wav2letter/build
----------------------------

 **then   make -j4**

Scanning dependencies of target gtest
Scanning dependencies of target wav2letter++
[  0%] Creating directories for 'gtest'
[  0%] Performing download step (git clone) for 'gtest'
Cloning into 'gtest'...
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Defines.cpp.o
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Dictionary.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Transforms.cpp.o
In file included from /root/facebook/wav2letter/src/common/Transforms.h:19:0,
                 from /root/facebook/wav2letter/src/common/Transforms.cpp:9:
/root/facebook/wav2letter/src/common/Defines.h:21:21: error: 'cpp' is not a namespace-name
 namespace cpp = fl::cpp;
                     ^
/root/facebook/wav2letter/src/common/Defines.h:21:24: error: expected namespace-name before ';' token
 namespace cpp = fl::cpp;
                        ^
In file included from /root/facebook/wav2letter/src/common/Defines.cpp:9:0:
/root/facebook/wav2letter/src/common/Defines.h:21:21: error: 'cpp' is not a namespace-name
 namespace cpp = fl::cpp;
                     ^
/root/facebook/wav2letter/src/common/Defines.h:21:24: error: expected namespace-name before ';' token
 namespace cpp = fl::cpp;
                        ^
In file included from /root/facebook/wav2letter/src/common/Utils.h:18:0,
                 from /root/facebook/wav2letter/src/common/Dictionary.cpp:14:
/root/facebook/wav2letter/src/common/Defines.h:21:21: error: 'cpp' is not a namespace-name
 namespace cpp = fl::cpp;
                     ^
/root/facebook/wav2letter/src/common/Defines.h:21:24: error: expected namespace-name before ';' token
 namespace cpp = fl::cpp;
                        ^
In file included from /root/facebook/wav2letter/src/common/Dictionary.cpp:14:0:
/root/facebook/wav2letter/src/common/Utils.h:102:16: error: 'cpp' does not name a type
     typename = cpp::enable_if_t<std::is_same<
                ^
/root/facebook/wav2letter/src/common/Utils.h:102:19: error: expected '>' before '::' token
     typename = cpp::enable_if_t<std::is_same<
                   ^
Note: checking out '2fe3bd994b3189899d93f1d5a881e725e046fdc2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2fe3bd9... Merge pull request #1433 from dsacre/fix-clang-warnings
[  1%] No patch step for 'gtest'
[  1%] Performing update step for 'gtest'
[  1%] Performing configure step for 'gtest'
loading initial cache file /root/facebook/wav2letter/build/src/tests/googletest/tmp/gtest-cache-Release.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /root/anaconda2/bin/python (found version "2.7.15") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/facebook/wav2letter/build/src/tests/googletest/src/gtest
[  1%] Performing build step for 'gtest'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Scanning dependencies of target gtest
[ 12%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
CMakeFiles/wav2letter++.dir/build.make:88: recipe for target 'CMakeFiles/wav2letter++.dir/src/common/Transforms.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/common/Transforms.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/wav2letter++.dir/build.make:75: recipe for target 'CMakeFiles/wav2letter++.dir/src/common/Dictionary.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/common/Dictionary.cpp.o] Error 1
CMakeFiles/wav2letter++.dir/build.make:62: recipe for target 'CMakeFiles/wav2letter++.dir/src/common/Defines.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/common/Defines.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Linking CXX static library libgtest.a
[ 25%] Built target gtest
Scanning dependencies of target gmock
[ 37%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 50%] Linking CXX static library libgmock.a
[ 50%] Built target gmock
Scanning dependencies of target gmock_main
[ 62%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 75%] Linking CXX static library libgmock_main.a
[ 75%] Built target gmock_main
Scanning dependencies of target gtest_main
[ 87%] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[  1%] No install step for 'gtest'
[  2%] Completed 'gtest'
[  2%] Built target gtest
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jacobkahn** [comment]
@qjchen1972 @BoneGoat — can you try pulling, rebuilding, and reinstalling flashlight? https://github.com/facebookresearch/flashlight/commit/e709134edca062b2da6415f0c17c57f0d08dd467 adds the missing namespace in question along with the backports themselves.

**Comment by BoneGoat** [comment]
I can confirm that the build works after rebuilding flashlight. Using the supplied Docker image. Thanks! @jacobkahn
