### ISSUE TITLE
Inference an wav2letter

### ISSUE THREAD

**Issue by AGrosserHH** [facebookresearch/wav2letter#194]
Hi,

I have trained the example dataset and now I would like to use the acoustic model on own wav file to produce as output the mentioned words. Is there any description how I can do this? Do I just need to copy the wav file into the folder for decoding and then start the decoding process?

Cheers,
Andi

**Comment by jacobkahn** [comment]
@AGrosserHH — if you want to do decoding, use the `Decode` binary and [see the documentation](https://github.com/facebookresearch/wav2letter/blob/master/docs/decoder.md) accordingly. If you want to do inference with the acoustic model, use the `Test` binary, which works similarly to the `Train` binary; it accepts an AM, a tokens file, and input audio, and generates emissions.

We don't yet have an online decoder that allows for encoding and decoding with one pipeline, but we'll be open sourcing that pretty soon.

**Comment by jacobkahn** [comment]
@AGrosserHH — the online decoder is available as of https://github.com/facebookresearch/wav2letter/commit/eda528dd38a509e35cb96ddca492095ec88da1cc.
