### ISSUE TITLE
exception in compute_ctc_loss

### ISSUE THREAD

**Issue by eturner303** [facebookresearch/wav2letter#195]
Greetings!  I'm attempting to train on a custom dataset.  

When I train on a 20 hour slice of data I see no issues.  If I increase the train to 40 hours of data, this occurs near the end of the first epoch:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: compute_ctc_loss, stat = unknown error
*** Aborted at 1549484188 (unix time) try "date -d @1549484188" if you are using GNU date ***
PC: @     0x7f8e3779c428 gsignal
*** SIGABRT (@0x7aed) received by PID 31469 (TID 0x7f8eb4e6f7c0) from PID 31469; stack trace: ***
    @     0x7f8eadaea390 (unknown)
    @     0x7f8e3779c428 gsignal
    @     0x7f8e3779e02a abort
    @     0x7f8e37ecfb39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f8e37ece1fb __cxxabiv1::__terminate()
    @     0x7f8e37ece234 std::terminate()
    @     0x7f8e37ece416 __cxa_throw
    @           0x546dab w2l::(anonymous namespace)::throw_on_error()
    @           0x547b51 w2l::ConnectionistTemporalClassificationCriterion::forward()
    @           0x469c1c _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE4_clES2_S5_S7_S9_S9_ddbi.constprop.9454
    @           0x419567 main
    @     0x7f8e37787830 __libc_start_main
    @           0x4657d9 _start
    @                0x0 (unknown)

Is there any way to get more verbose logging from the Train tool so I can track down the sample/samples which seem to be causing this error?  Or any thoughts as to what might be going on?

Thanks for any help.

**Comment by eturner303** [comment]
Some additional information:

I modified the wav2letter code to enable me to see which sample was causing the crash.

The offending file was 16.5 seconds long, 528,030 bytes.  

Removing all files >400,000 bytes solved my issue.  Is there a hard-coded max file limit or max number of seconds for training samples?  If so, what is that value?

Thanks

**Comment by jacobkahn** [comment]
@eturner303 — which criterion backend did you build wav2letter with (CPU or GPU) and how much GPU memory do you have available? It's possible this is a spurious issue where data loading/featurization consumes too much memory, causing CTC to fail because of a lack of memory.

**Comment by eturner303** [comment]
I am using the GPU criterion, and training on K80 GPUs (12GB ram per GPU) -- batch size is 4

**Comment by jacobkahn** [comment]
I'm a bit surprised it still OOMs with 12 GB per GPU, but truncating your audio is probably the best solution for now (it shouldn't make a difference in training).
