### ISSUE TITLE
Share Low Dropout configuration arch

### ISSUE THREAD

**Issue by smolendawid** [facebookresearch/wav2letter#20]
I'd like to ask if it is possible to share Low Dropout configuration arch in the same way as High Dropout (librispeech-glu-highdropout file), so that entire paper could be reproduced?

**Comment by VitaliyLi** [comment]
Hi,

We have uploaded the [low-dropout model](https://s3.amazonaws.com/wav2letter/models/librispeech-glu-lowdropout.bin) from the paper:

`https://s3.amazonaws.com/wav2letter/models/librispeech-glu-lowdropout.bin`
