### ISSUE TITLE
Dockerfile-CPU doesn't seem to work

### ISSUE THREAD

**Issue by pzelasko** [facebookresearch/wav2letter#200]
It's aborting with the following error:

```
Step 5/5 : RUN export MKLROOT=/opt/intel/mkl && export KENLM_ROOT_DIR=/root/kenlm &&     cd /root/wav2letter && mkdir -p build &&     cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CPU &&     make -j8
 ---> Running in 01b94b898ed4

CMake Error: The source directory "/root/wav2letter" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
The command '/bin/sh -c export MKLROOT=/opt/intel/mkl && export KENLM_ROOT_DIR=/root/kenlm &&     cd /root/wav2letter && mkdir -p build &&     cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CPU &&     make -j8' returned a non-zero code: 1
```

EDIT: the same happens in Dockerfile-CUDA

**Comment by tlikhomanenko** [comment]
Hi @pzelasko,

I cannot reproduce your error. For me the build is going fine. Could you try rebuild full image using `docker build --no-cache`? And be sure that when you are running command `docker build ...` you are in the `wav2letter` folder (in `Dockerfile` we copy all files in `./` to the image, so all files in folder `wav2letter` will be copied into docker image if you are in this folder)

**Comment by pzelasko** [comment]
Thanks for the feedback! I'll re-try according to your suggestions early next week and let you know how it went.

**Comment by pzelasko** [comment]
Thanks, it helped! I was previously doing `cat Dockerfile-CPU | sudo docker build -`, now it works when I did `sudo docker build -f Dockerfile-CPU --no-cache .`.
