### ISSUE TITLE
Training using russian dataset

### ISSUE THREAD

**Issue by RVlasov** [facebookresearch/wav2letter#202]
Hi. I'm preparing russian dataset for wav2letter. Maybe someone have an experience in that  area?
Things that i've noticed now:
• 1 marked file shoud contain audio (20-30 sec.) and 1 sentense
• 1 epoch shoud be less than 30 min. of audio
• For successful training ~ 100 houres of marked audio and text is adequate array?
• Audio shoud contain "clear" speech (without accent), text also shoud consist of a literature language.
• Any otehrs aspects?

Really appreciate the help

**Comment by jacobkahn** [comment]
@RVlasov — we haven't yet trained models in Russian for wav2letter; I'd recommend posting in the [wav2letter users group](https://www.facebook.com/groups/717232008481207/). We're trying to keep Github issues high-signal, so I'm going to close the issue for now, but feel free to continue a discussion here as well.

**Comment by RVlasov** [comment]
Okay, i understand you. I've already asked the question in that group - no
answer too. But thanks for your help.

пн, 18 февр. 2019 г. в 20:34, Jacob Kahn <notifications@github.com>:
