### ISSUE TITLE
Decoding with custom language model

### ISSUE THREAD

**Issue by victoriapoghosyan** [facebookresearch/wav2letter#203]
I've run ./Decoder  --flagsfile ../tutorials/1-librispeech_clean/decode.cfg
When using language model created by kenlm decoded sentences are empty  and WER is 100%
--Output--
|T|: the vicious character of sin is brought out by the words who gave himself for our sins 
|P|: 
[sample: 866, WER: 100%, LER: 100%, slice WER: 100%, slice LER: 100%, progress: 100%]
what can I do?
Also I've tried to use 3-gram model created by kaldi,but same occured

**Comment by xuqiantong** [comment]
Can you first make sure you language model is constructed with valid words (e.g. words with lower-case letters as in the target |T|)?

**Comment by victoriapoghosyan** [comment]
Thanks a lot. It works for me
