### ISSUE TITLE
Viable for Macbook?

### ISSUE THREAD

**Issue by DenisPeskov** [facebookresearch/wav2letter#21]
In retrospect this would have been better to ask beforehand.

How much RAM do you need to transcribe with a pre-trained model?  I imagine most of the CPU-only folks are trying to do this.

After setting up everything, I ended getting this on the decoding part, with 4 GB of free RAM.
**PANIC: unprotected error in call to Lua API (not enough memory)**

Bringing down the beam-size to 25 from (25,000) still was too cumbersome.  Any other hyper parameters that would reduce the memory?

Has anybody successfully got this working on an MacOS?  I debugged lots of small snags, but ultimately couldn't get it working (flac files not being seen- comment on closed issue about Flac, lua runs out of space).  Might make sense to only install this on a Linux with GPU for the time being.

**Comment by VitaliyLi** [comment]
How many threads are you running with the decoder (-nthread flag)? You might want to decrease that one instead of beam size.
