### ISSUE TITLE
WER is low for phone calls

### ISSUE THREAD

**Issue by AIGyan** [facebookresearch/wav2letter#211]
WER is high for phone calls audio recording. Any suggestion on lowering the WER will be helpful.

**Comment by jacobkahn** [comment]
There's no quick-fix here, but a few motivating questions:
- WER is "high" with respect to what - what's your baseline and what's the relative difference in WER?
- Is there a significant variance in audio quality (volume, audible background noise) across the utterances? Can you better normalize or filter samples?
- How large is your receptive field/how deep is your model?
- How many MFCC coefficients are you using (the `mfcccoeffs` flag)?

For questions about specific use cases, posting in the [wav2letter users group](https://www.facebook.com/groups/717232008481207/) may be helpful.
