### ISSUE TITLE
DECODING ERROR!! PLEASE SAVE ME

### ISSUE THREAD

**Issue by lvyilan23** [facebookresearch/wav2letter#212]
*** Error in `/home/lyu/workspace/wav2letter/build/Decoder': corrupted size vs. prev_size: 0x00007fd7bbf09e8f ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fdacaa9d7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82aec)[0x7fdacaaa8aec]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fdacaaaa184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7fdacb5bee78]
/home/lyu/workspace/wav2letter/build/Decoder[0x5262fb]
/home/lyu/workspace/wav2letter/build/Decoder[0x52b697]
/home/lyu/workspace/wav2letter/build/Decoder[0x45c533]
/home/lyu/workspace/wav2letter/build/Decoder[0x45e644]
/home/lyu/workspace/wav2letter/build/Decoder[0x462d29]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xea99)[0x7fdb4460fa99]
/home/lyu/workspace/wav2letter/build/Decoder[0x45ac41]
/home/lyu/workspace/wav2letter/build/Decoder[0x46781b]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7fdacb5e9c80]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fdb446086ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fdacab2d41d]
======= Memory map: ========
00400000-0074c000 r-xp 00000000 08:01 22158828                           /home/lyu/workspace/wav2letter/build/Decoder
0094c000-0094f000 r--p 0034c000 08:01 22158828                           /home/lyu/workspace/wav2letter/build/Decoder
0094f000-00952000 rw-p 0034f000 08:01 22158828                           /home/lyu/workspace/wav2letter/build/Decoder
00952000-0095b000 rw-p 00000000 00:00 0 
01371000-5e48d000 rw-p 00000000 00:00 0                                  [heap]
200000000-200200000 rw-s 00000000 00:06 544                              /dev/nvidiactl
200200000-200400000 ---p 00000000 00:00 0 
200400000-200404000 rw-s 00000000 00:06 544                              /dev/nvidiactl
200404000-200600000 ---p 00000000 00:00 0 
200600000-200a00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
200a00000-201600000 ---p 00000000 00:00 0 
201600000-201800000 rw-s 00000000 00:06 544                              /dev/nvidiactl
201800000-201804000 rw-s 00000000 00:06 544                              /dev/nvidiactl
201804000-201a00000 ---p 00000000 00:00 0 
201a00000-201e00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
201e00000-201e04000 rw-s 00000000 00:06 544                              /dev/nvidiactl
201e04000-202000000 ---p 00000000 00:00 0 
202000000-202400000 rw-s 00000000 00:06 544                              /dev/nvidiactl
202400000-202404000 rw-s 00000000 00:06 544                              /dev/nvidiactl
202404000-202600000 ---p 00000000 00:00 0 
202600000-202a00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
202a00000-202a04000 rw-s 00000000 00:06 544                              /dev/nvidiactl
202a04000-202c00000 ---p 00000000 00:00 0 
202c00000-203000000 rw-s 00000000 00:06 544                              /dev/nvidiactl
203000000-203004000 rw-s 00000000 00:06 544                              /dev/nvidiactl
203004000-203200000 ---p 00000000 00:00 0 
203200000-203600000 rw-s 00000000 00:06 544                              /dev/nvidiactl
203600000-203604000 rw-s 00000000 00:06 544                              /dev/nvidiactl
203604000-203800000 ---p 00000000 00:00 0 
203800000-203c00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
203c00000-203c04000 rw-s 00000000 00:06 544                              /dev/nvidiactl
203c04000-203e00000 ---p 00000000 00:00 0 
203e00000-204200000 rw-s 00000000 00:06 544                              /dev/nvidiactl
204200000-204204000 rw-s 00000000 00:06 544                              /dev/nvidiactl
204204000-204400000 ---p 00000000 00:00 0 
204400000-204800000 rw-s 00000000 00:06 544                              /dev/nvidiactl
204800000-204804000 rw-s 00000000 00:06 544                              /dev/nvidiactl
204804000-204a00000 ---p 00000000 00:00 0 
204a00000-204e00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
204e00000-204e04000 rw-s 00000000 00:06 544                              /dev/nvidiactl
204e04000-205000000 ---p 00000000 00:00 0 
205000000-205400000 rw-s 00000000 00:06 544                              /dev/nvidiactl
205400000-205404000 rw-s 00000000 00:06 544                              /dev/nvidiactl
205404000-205600000 ---p 00000000 00:00 0 
205600000-205a00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
205a00000-205a04000 rw-s 00000000 00:06 544                              /dev/nvidiactl
205a04000-205c00000 ---p 00000000 00:00 0 
205c00000-206000000 rw-s 00000000 00:06 544                              /dev/nvidiactl
206000000-206004000 rw-s 00000000 00:06 544                              /dev/nvidiactl
206004000-206200000 ---p 00000000 00:00 0 
206200000-206600000 rw-s 00000000 00:06 544                              /dev/nvidiactl
206600000-206604000 rw-s 00000000 00:06 544                              /dev/nvidiactl
206604000-206800000 ---p 00000000 00:00 0 
206800000-206c00000 rw-s 00000000 00:06 544                              /dev/nvidiactl
206c00000-206c04000 rw-s 00000000 00:06 544                              /dev/nvidiactl
206c04000-206e00000 ---p 00000000 00:00 0 
206e00000-207200000 rw-s 00000000 00:06 544                              /dev/nvidiactl
207200000-207400000 ---p 00000000 00:00 0 
207400000-207600000 rw-s 00000000 00:06 544                              /dev/nvidiactl
207600000-300200000 ---p 00000000 00:00 0 
10000000000-10204000000 ---p 00000000 00:00 0 
7fd540000000-7fd5ac1e4000 rw-p 00000000 00:00 0 
7fd600000000-7fd66c1e4000 rw-p 00000000 00:00 0 
7fd680000000-7fd6ec1e4000 rw-p 00000000 00:00 0 
7fd700000000-7fd76c1e4000 rw-p 00000000 00:00 0 
7fd770000000-7fd770021000 rw-p 00000000 00:00 0 
7fd770021000-7fd774000000 ---p 00000000 00:00 0 
7fd778000000-7fd778828000 rw-p 00000000 00:00 0 
7fd778828000-7fd77c000000 ---p 00000000 00:00 0 
7fd77c000000-7fd77c512000 rw-p 00000000 00:00 0 
7fd77c512000-7fd780000000 ---p 00000000 00:00 0 
7fd780000000-7fd7835ff000 rw-p 00000000 00:00 0 
7fd7835ff000-7fd784000000 ---p 00000000 00:00 0 
7fd784000000-7fd7848c8000 rw-p 00000000 00:00 0 
7fd7848c8000-7fd788000000 ---p 00000000 00:00 0 
7fd788000000-7fd78b41f000 rw-p 00000000 00:00 0 
7fd78b41f000-7fd78c000000 ---p 00000000 00:00 0 
7fd78c000000-7fd78fffe000 rw-p 00000000 00:00 0 
7fd78fffe000-7fd790000000 ---p 00000000 00:00 0 
7fd790000000-7fd793483000 rw-p 00000000 00:00 0 
7fd793483000-7fd794000000 ---p 00000000 00:00 0 
7fd794000000-7fd797ffd000 rw-p 00000000 00:00 0 
7fd797ffd000-7fd798000000 ---p 00000000 00:00 0 
7fd798000000-7fd79bff4000 rw-p 00000000 00:00 0 
7fd79bff4000-7fd79c000000 ---p 00000000 00:00 0 
7fd79c000000-7fd79f7c3000 rw-p 00000000 00:00 0 
7fd79f7c3000-7fd7a0000000 ---p 00000000 00:00 0 
7fd7a0000000-7fd7a3ffa000 rw-p 00000000 00:00 0 
7fd7a3ffa000-7fd7a4000000 ---p 00000000 00:00 0 
7fd7a4000000-7fd7a7f34000 rw-p 00000000 00:00 0 
7fd7a7f34000-7fd7a8000000 ---p 00000000 00:00 0 
7fd7a8000000-7fd7abfe6000 rw-p 00000000 00:00 0 
7fd7abfe6000-7fd7ac000000 ---p 00000000 00:00 0 
7fd7ac000000-7fd7afffb000 rw-p 00000000 00:00 0 
7fd7afffb000-7fd7b0000000 ---p 00000000 00:00 0 
7fd7b0000000-7fd7b3ffa000 rw-p 00000000 00:00 0 
7fd7b3ffa000-7fd7b4000000 ---p 00000000 00:00 0 
7fd7b4000000-7fd7b7fff000 rw-p 00000000 00:00 0 
7fd7b7fff000-7fd7b8000000 ---p 00000000 00:00 0 
7fd7b8000000-7fd7bbff3000 rw-p 00000000 00:00 0 
7fd7bbff3000-7fd7bc000000 ---p 00000000 00:00 0 
7fd7bc000000-7fd7bffff000 rw-p 00000000 00:00 0 
7fd7bffff000-7fd7c0000000 ---p 00000000 00:00 0 
7fd7c0000000-7fd82c1e4000 rw-p 00000000 00:00 0 
7fd830000000-7fd834000000 rw-p 00000000 00:00 0 
7fd834000000-7fd838000000 rw-p 00000000 00:00 0 
7fd838000000-7fd83c000000 rw-p 00000000 00:00 0 
7fd83c000000-7fd840000000 rw-p 00000000 00:00 0 
7fd840000000-7fd8ac1e4000 rw-p 00000000 00:00 0 
7fd8b0000000-7fd8b4000000 rw-p 00000000 00:00 0 
7fd8b4000000-7fd8b8000000 rw-p 00000000 00:00 0 
7fd8b8000000-7fd8bc000000 rw-p 00000000 00:00 0 
7fd8bc000000-7fd8c0000000 rw-p 00000000 00:00 0 
7fd8c0000000-7fd8c4000000 rw-p 00000000 00:00 0 
7fd8c4000000-7fd8c8000000 rw-p 00000000 00:00 0 
7fd8c8000000-7fd8cc000000 rw-p 00000000 00:00 0 
7fd8cc000000-7fd8cffef000 rw-p 00000000 00:00 0 
7fd8cffef000-7fd8d0000000 ---p 00000000 00:00 0 
7fd8d0000000-7fd8d4000000 rw-p 00000000 00:00 0 
7fd8d4000000-7fd8d8000000 rw-p 00000000 00:00 0 
7fd8d8000000-7fd8dc000000 rw-p 00000000 00:00 0 
7fd8dc000000-7fd8e0000000 rw-p 00000000 00:00 0 
7fd8e0000000-7fd8e4000000 rw-p 00000000 00:00 0 
7fd8e4000000-7fd8e8000000 rw-p 00000000 00:00 0 
7fd8e8000000-7fd8ec000000 rw-p 00000000 00:00 0 
7fd8ec000000-7fd8f0000000 rw-p 00000000 00:00 0 
7fd8f0000000-7fd8f4000000 rw-p 00000000 00:00 0 
7fd8f4000000-7fd8f8000000 rw-p 00000000 00:00 0 
7fd8f8000000-7fd8fc000000 rw-p 00000000 00:00 0 
7fd8fc000000-7fd900000000 rw-p 00000000 00:00 0 
7fd900000000-7fd96c1e4000 rw-p 00000000 00:00 0 
7fd970000000-7fd974000000 rw-p 00000000 00:00 0 
7fd974000000-7fd978000000 rw-p 00000000 00:00 0 
7fd978000000-7fd97c000000 rw-p 00000000 00:00 0 
7fd97c000000-7fd980000000 rw-p 00000000 00:00 0 
7fd980000000-7fd9ec1e4000 rw-p 00000000 00:00 0 
7fd9f0000000-7fd9f4000000 rw-p 00000000 00:00 0 
7fd9f4000000-7fd9f8000000 rw-p 00000000 00:00 0 
7fd9f8000000-7fd9fc000000 rw-p 00000000 00:00 0 
7fd9fc000000-7fda00000000 rw-p 00000000 00:00 0 
7fda00000000-7fda04000000 rw-p 00000000 00:00 0 
7fda04000000-7fda08000000 rw-p 00000000 00:00 0 
7fda08000000-7fda0c000000 rw-p 00000000 00:00 0 
7fda10000000-7fda14000000 rw-p 00000000 00:00 0 
7fda18000000-7fda1c000000 rw-p 00000000 00:00 0 
7fda1c000000-7fda20000000 rw-p 00000000 00:00 0 
7fda20000000-7fda22000000 ---p 00000000 00:00 0 
7fda24000000-7fda28000000 rw-p 00000000 00:00 0 
7fda28000000-7fda2c000000 rw-p 00000000 00:00 0 
7fda2c000000-7fda32000000 ---p 00000000 00:00 0 
7fda34000000-7fda44000000 ---p 00000000 00:00 0 
7fda44000000-7fda44021000 rw-p 00000000 00:00 0 
7fda44021000-7fda48000000 ---p 00000000 00:00 0 
7fda48000000-7fda4c000000 rw-p 00000000 00:00 0 
7fda4c000000-7fda4c021000 rw-p 00000000 00:00 0 
7fda4c021000-7fda50000000 ---p 00000000 00:00 0 
7fda52000000-7fda54000000 ---p 00000000 00:00 0 
7fda54000000-7fda54021000 rw-p 00000000 00:00 0 
7fda54021000-7fda58000000 ---p 00000000 00:00 0 
7fda58c00000-7fda58f6f000 rw-p 00000000 00:00 0 
7fda59000000-7fda5936f000 rw-p 00000000 00:00 0 
7fda59400000-7fda5976f000 rw-p 00000000 00:00 0 
7fda59800000-7fda59b6f000 rw-p 00000000 00:00 0 
7fda59c00000-7fda59f6f000 rw-p 00000000 00:00 0 
7fda5a000000-7fda5c000000 ---p 00000000 00:00 0 
7fda5c000000-7fda5c021000 rw-p 00000000 00:00 0 
7fda5c021000-7fda60000000 ---p 00000000 00:00 0 
7fda60400000-7fda6076f000 rw-p 00000000 00:00 0 
7fda60800000-7fda60b6f000 rw-p 00000000 00:00 0 
7fda60c00000-7fda60f6f000 rw-p 00000000 00:00 0 
7fda60ffe000-7fda60fff000 ---p 00000000 00:00 0 
7fda60fff000-7fda617ff000 rw-p 00000000 00:00 0 
7fda617ff000-7fda61800000 ---p 00000000 00:00 0 
7fda61800000-7fda62000000 rw-p 00000000 00:00 0 
7fda62000000-7fda64000000 ---p 00000000 00:00 0 
7fda64000000-7fda64021000 rw-p 00000000 00:00 0 
7fda64021000-7fda68000000 ---p 00000000 00:00 0 
7fda684b8000-7fda684b9000 ---p 00000000 00:00 0 
7fda684b9000-7fda68cb9000 rw-p 00000000 00:00 0 
7fda68cb9000-7fda68cba000 ---p 00000000 00:00 0 
7fda68cba000-7fda694ba000 rw-p 00000000 00:00 0 
7fda694ba000-7fda69f1b000 r-xp 00000000 08:01 56763051                   /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.93
7fda69f1b000-7fda6a11a000 ---p 00a61000 08:01 56763051                   /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.93
7fda6a11a000-7fda6a24b000 rw-p 00a60000 08:01 56763051                   /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.93
7fda6a24b000-7fda6a254000 rw-p 00000000 00:00 0 
7fda6a254000-7fda6a255000 ---p 00000000 00:00 0 
7fda6a255000-7fda6aa55000 rw-p 00000000 00:00 0 
7fda6aa55000-7fda6aa56000 ---p 00000000 00:00 0 
7fda6aa56000-7fda6b256000 rw-p 00000000 00:00 0 
7fda6b256000-7fda6bde7000 r-xp 00000000 08:01 56624784                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_vml_avx2.so
7fda6bde7000-7fda6bfe7000 ---p 00b91000 08:01 56624784                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_vml_avx2.so
7fda6bfe7000-7fda6bfea000 r--p 00b91000 08:01 56624784                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_vml_avx2.so
7fda6bfea000-7fda6bfff000 rw-p 00b94000 08:01 56624784                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_vml_avx2.so
7fda6bfff000-7fda6c000000 rw-p 00000000 00:00 0 
7fda6c000000-7fda6c021000 rw-p 00000000 00:00 0 
7fda6c021000-7fda70000000 ---p 00000000 00:00 0 
7fda704be000-7fda73de6000 r-xp 00000000 08:01 56624771                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_avx2.so
7fda73de6000-7fda73fe5000 ---p 03928000 08:01 56624771                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_avx2.so
7fda73fe5000-7fda73fec000 r--p 03927000 08:01 56624771                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_avx2.so
7fda73fec000-7fda73ffb000 rw-p 0392e000 08:01 56624771                   /opt/intel/compilers_and_libraries_2019.2.187/linux/mkl/lib/intel64_lin/libmkl_avx2.so
7fda73ffb000-7fda74000000 rw-p 00000000 00:00 0 
7fda74000000-7fda74021000 rw-p 00000000 00:00 0 
7fda74021000-7fda78000000 ---p 00000000 00:00 0 
7fda7822a000-7fda7822b000 ---p 00000000 00:00 0 
7fda7822b000-7fda78a2b000 rw-p 00000000 00:00 0 
7fda78a2b000-7fda78a2c000 ---p 00000000 00:00 0 
7fda78a2c000-7fda7922c000 rw-p 00000000 00:00 0 
7fda7922c000-7fda7922d000 ---p 00000000 00:00 0 
7fda7922d000-7fda79a2d000 rw-p 00000000 00:00 0 
7fda79a2d000-7fda79a2e000 ---p 00000000 00:00 0 
7fda79a2e000-7fda7c117000 rw-p 00000000 00:00 0 
7fda7c7fd000-7fda7c7fe000 ---p 00000000 00:00 0 
7fda7c7fe000-7fda7cffe000 rw-p 00000000 00:00 0 
7fda7cffe000-7fda7cfff000 ---p 00000000 00:00 0 
7fda7cfff000-7fda7d7ff000 rw-p 00000000 00:00 0 
7fda7d7ff000-7fda7d800000 ---p 00000000 00:00 0 
7fda7d800000-7fda7e000000 rw-p 00000000 00:00 0 
7fda7e000000-7fda88000000 ---p 00000000 00:00 0 
7fda88000000-7fda88021000 rw-p 00000000 00:00 0 
7fda88021000-7fda8c000000 ---p 00000000 00:00 0 
7fda8c000000-7fda8c021000 rw-p 00000000 00:00 0 
7fda8c021000-7fda90000000 ---p 00000000 00:00 0 
7fda90000000-7fda90001000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90001000-7fda90002000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90002000-7fda90003000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90003000-7fda90004000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90004000-7fda90005000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90005000-7fda90006000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90006000-7fda90007000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90007000-7fda90008000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90008000-7fda90009000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90009000-7fda9000a000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda9000a000-7fda9000b000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda9000b000-7fda9000c000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda9000c000-7fda9000d000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda9000d000-7fda9000e000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda9000e000-7fda9000f000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda9000f000-7fda90010000 rw-s 00000000 00:06 547                        /dev/nvidia0
7fda90010000-7fdaa0000000 ---p 00000000 00:00 0 
7fdaa02c8000-7fdaa05fd000 r-xp 00000000 08:01 58217908                   /usr/local/cuda-9.2/lib64/libnvrtc-builtins.so.9.2.148
7fdaa05fd000-7fdaa07fc000 ---p 00335000 08:01 58217908                   /usr/local/cuda-9.2/lib64/libnvrtc-builtins.so.9.2.148
7fdaa07fc000-7fdaa07fd000 rw-p 00334000 08:01 58217908                   /usr/local/cuda-9.2/lib64/libnvrtc-builtins.so.9.2.148
7fdaa07fd000-7fdaa07fe000 ---p 00000000 00:00 0 
7fdaa07fe000-7fdaa0ffe000 rw-p 00000000 00:00 0 
7fdaa0ffe000-7fdaa0fff000 ---p 00000000 00:00 0 
7fdaa0fff000-7fdaa17ff000 rw-p 00000000 00:00 0 
7fdaa17ff000-7fdaa1800000 ---p 00000000 00:00 0 
7fdaa1800000-7fdaa2000000 rw-p 00000000 00:00 0 
7fdaa2000000-7fdaa2200000 ---p 00000000 00:00 0 
7fdaa2200000-7fdaa2400000 rw-s 00000000 00:05 14751714                   /dev/zero (deleted)
7fdaa2400000-7fdaa2600000 rw-s 00000000 00:06 544                        /dev/nvidiactl
7fdaa2600000-7fdaa2800000 rw-s 00000000 00:05 14751715                   /dev/zero (deleted)
7fdaa2800000-7fdaa2a00000 rw-s 00000000 00:06 544                        /dev/nvidiactl
7fdaa2a00000-7fdaa2c00000 ---p 00000000 00:00 0 
7fdaa2c00000-7fdaa2ed6000 rw-s 00000000 00:06 544                        /dev/nvidiactl
7fdaa2ed6000-7fdaa3000000 ---p 00000000 00:00 0 
7fdaa3000000-7fdaa3200000 rw-s 00000000 00:05 14751717                   /dev/zero (deleted)
7fdaa3200000-7fdaa3400000 ---p 00000000 00:00 0 
7fdaa3400000-7fdaa3600000 rw-s 00000000 00:05 14751718                   /dev/zero (deleted)
7fdaa3600000-7fdaa4000000 ---p 00000000 00:00 0 
7fdaa418f000-7fdaa42ba000 rw-p 00000000 00:00 0 
7fdaa42ba000-7fdaa42bb000 ---p 00000000 00:00 0 
7fdaa42bb000-7fdaa4abb000 rw-p 00000000 00:00 0 
7fdaa4abb000-7fdaa4abc000 ---p 00000000 00:00 0 
7fdaa4abc000-7fdaa52bc000 rw-p 00000000 00:00 0 
7fdaa52bc000-7fdaab2bc000 ---p 00000000 00:00 0 
7fdaab2bc000-7fdaab2c5000 r-xp 00000000 08:01 56762196                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7fdaab2c5000-7fdaab4c4000 ---p 00009000 08:01 56762196                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7fdaab4c4000-7fdaab4c5000 r--p 00008000 08:01 56762196                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7fdaab4c5000-7fdaab4c6000 rw-p 00009000 08:01 56762196                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7fdaab4c6000-7fdaab4ea000 r-xp 00000000 08:01 56103619                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fdaab4ea000-7fdaab6e9000 ---p 00024000 08:01 56103619                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fdaab6e9000-7fdaab6ea000 r--p 00023000 08:01 56103619                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fdaab6ea000-7fdaab6eb000 rw-p 00024000 08:01 56103619                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7fdaab6eb000-7fdaab6f0000 r-xp 00000000 08:01 56762172                   /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fdaab6f0000-7fdaab8ef000 ---p 00005000 08:01 56762172                   /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fdaab8ef000-7fdaab8f0000 r--p 00004000 08:01 56762172                   /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fdaab8f0000-7fdaab8f1000 rw-p 00005000 08:01 56762172                   /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7fdaab8f1000-7fdaab8f3000 r-xp 00000000 08:01 56762161                   /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fdaab8f3000-7fdaabaf3000 ---p 00002000 08:01 56762161                   /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fdaabaf3000-7fdaabaf4000 r--p 00002000 08:01 56762161                   /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fdaabaf4000-7fdaabaf5000 rw-p 00003000 08:01 56762161                   /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7fdaabaf5000-7fdaabafe000 r-xp 00000000 08:01 56762957                   /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fdaabafe000-7fdaabcfd000 ---p 00009000 08:01 56762957                   /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fdaabcfd000-7fdaabcfe000 r--p 00008000 08:01 56762957                   /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fdaabcfe000-7fdaabcff000 rw-p 00009000 08:01 56762957                   /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fdaabcff000-7fdaabd09000 r-xp 00000000 08:01 56763084                   /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fdaabd09000-7fdaabf08000 ---p 0000a000 08:01 56763084                   /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fdaabf08000-7fdaabf09000 r--p 00009000 08:01 56763084                   /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fdaabf09000-7fdaabf0a000 rw-p 0000a000 08:01 56763084                   /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fdaabf0a000-7fdaabf13000 r-xp 00000000 08:01 56764094                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fdaabf13000-7fdaac112000 ---p 00009000 08:01 56764094                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fdaac112000-7fdaac113000 r--p 00008000 08:01 56764094                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fdaac113000-7fdaac114000 rw-p 00009000 08:01 56764094                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7fdaac114000-7fdaac116000 r-xp 00000000 08:01 56762186                   /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7fdaac116000-7fdaac315000 ---p 00002000 08:01 56762186                   /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7fdaac315000-7fdaac316000 r--p 00001000 08:01 56762186                   /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7fdaac316000-7fdaac317000 rw-p 00002000 08:01 56762186                   /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7fdaac317000-7fdaac321000 r-xp 00000000 08:01 56762194                   /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7fdaac321000-7fdaac520000 ---p 0000a000 08:01 56762194                   /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7fdaac520000-7fdaac521000 r--p 00009000 08:01 56762194                   /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7fdaac521000-7fdaac522000 rw-p 0000a000 08:01 56762194                   /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7fdaac522000-7fdaac55f000 r-xp 00000000 08:01 56762567                   /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7fdaac55f000-7fdaac75e000 ---p 0003d000 08:01 56762567                   /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0*** Aborted at 1550731903 (unix time) try "date -d @1550731903" if you are using GNU date ***
PC: @     0x7fdacaa5b428 gsignal
*** SIGABRT (@0x3e80000709b) received by PID 28827 (TID 0x7fda78a2a700) from PID 28827; stack trace: ***
    @     0x7fdb44612390 (unknown)
    @     0x7fdacaa5b428 gsignal
    @     0x7fdacaa5d02a abort
    @     0x7fdacaa9d7ea (unknown)
    @     0x7fdacaaa8aec (unknown)
    @     0x7fdacaaaa184 __libc_malloc
    @     0x7fdacb5bee78 operator new()
    @           0x5262fb w2l::Decoder::storeAllFinalHypothesis()
    @           0x52b697 w2l::Decoder::decode()
    @           0x45c533 _ZZ4mainENKUliiiE2_clEiii
    @           0x45e644 _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_ESt12_Bind_simpleIFSt17reference_wrapperISt5_BindIFZ4mainEUliiiE2_iiiEEEvEEvEEE9_M_invokeERKSt9_Any_data
    @           0x462d29 std::__future_base::_State_baseV2::_M_do_set()
    @     0x7fdb4460fa99 __pthread_once_slow
    @           0x45ac41 _ZNSt13__future_base11_Task_stateISt5_BindIFZ4mainEUliiiE2_iiiEESaIiEFvvEE6_M_runEv
    @           0x46781b _ZNSt6thread5_ImplISt12_Bind_simpleIFZN2fl10ThreadPoolC4EmRKSt8functionIFvmEEEUlvE_vEEE6_M_runEv
    @     0x7fdacb5e9c80 (unknown)
    @     0x7fdb446086ba start_thread
    @     0x7fdacab2d41d clone
已放弃 (核心已转储)

**Comment by lvyilan23** [comment]
I use the LibriSpeech in tutorials, and training succeeded, decoding failed.

**Comment by xuqiantong** [comment]
Can you pull the master again? If it still fails, please send the commands here.

**Comment by lvyilan23** [comment]
> Can you pull the master again? If it still fails, please send the commands here.

okerrrr thank you！！

**Comment by xuqiantong** [comment]
Assuming problem solved. Closing.
