### ISSUE TITLE
RNN based models and the view module

### ISSUE THREAD

**Issue by akhiari** [facebookresearch/wav2letter#214]
Hello,
First, Thank you very much for your work, and your efforts open sourcing this tool and making flexible enough for many usages.

I am trying to train an LSTM based network but am running into the following trouble:
1- I want to reshape the input data into 3 dimensional tensor in order to feed it to an RNN. The view module seems to only allow 4 dimensional sizes when using the .arch configuration. V d1 d2 d3 d4.
2- if not possible, it there an example on how to pass data to an RNN, using an alternative approach ? so far am always having this error: terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid # of parameters or wrong input shape for RNN
3- in Keras or other frameworks, a Distributed layer is used with LSTM before applying a dense layer. is there a way to do this with wav2letter ?, if not is there an alternative?
4- Correct me if am wrong, but even if one is trying to implement a deep speech like architecture, the data should be transformed into 3d data before passing to RNNs. in this sense the RNN layers are useless in their current form with the .arch file.

**Comment by jacobkahn** [comment]
If I understand your question correctly:
1. You can use a 3-dimensional tensor - you just need to set the dimension of the tensor along the correct irrelevant axis equal to 1. AM data in wav2letter is usually manipulated in a WHCN format (equivalent to row-major NCHW in column-major ArrayFire). Typically, this means that the second axis (`H`) will be 1 for most input data.
2. ArrayFire `af::array`s always have order 4, but may have lower dimension if, as I mentioned, the size along one axis is 1. I would carefully check the shape of your input against what the code expects.
3. If the RNN [architecture specification](https://github.com/facebookresearch/wav2letter/blob/master/docs/arch.md) won't serve your purposes as is, you'll need to make custom modifications. I would check [W2lModule](https://github.com/facebookresearch/wav2letter/blob/master/src/module/W2lModule.cpp) for more on this.
4. See my answer to 1/2 above.
