### ISSUE TITLE
Train FFTW MKL Problem

### ISSUE THREAD

**Issue by mcspa** [facebookresearch/wav2letter#215]
On Ubuntu 18.04 with CUDA 10.0, Nvidia drivers 410 and all other prerequisites built, I was able to compile wav2letter without errors. 
'make test' gave Segmentation faults in Modules _'DataTest'_ and _'MfccTest'_.
Starting _'Train'_ for the librispeech tutorial ended shortly after the call with:

```
*** Aborted at 1550787957 (unix time) try "date -d @1550787957" if you are using GNU date ***
PC: @     0x7f8acc256c17 mkl_dft_bless_node_omp
*** SIGSEGV (@0x0) received by PID 22774 (TID 0x7f8ace7f77c0) from PID 0; stack trace: ***
    @     0x7f8acdd0c890 (unknown)
    @     0x7f8acc256c17 mkl_dft_bless_node_omp
    @     0x7f8acd3719d7 DftiCreateDescriptor_d_1d
    @     0x7f8acd378170 fftw_plan_guru64_dft_r2c
    @     0x7f8acd376e6b fftw_plan_dft_r2c
    @     0x7f8acd376eab fftw_plan_dft_r2c_1d
    @     0x55e15766d73a speech::PowerSpectrum<>::PowerSpectrum()
    @     0x55e15766a507 speech::Mfsc<>::Mfsc()
    @     0x55e1576628ee w2l::featurize()
    @     0x55e157651176 w2l::W2lDataset::getFeatureData()
    @     0x55e1576529b6 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x55e157652f18 w2l::W2lDataset::get()
    @     0x55e15753bc9f _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE4_clES2_S5_S7_S9_S9_ddbi
    @     0x55e15750075c main
    @     0x7f8a4b2a5b97 __libc_start_main
    @     0x55e1575386ba _start
Segmentation fault (core dumped)
```

The problem seems to be in fetaure extraction.
I have downloaded MKL _'l_mkl_2019.1.144.tgz'_ from the Intel Website and  used the installer script and previously installed _'apt-get install libfftw3-dev'_.

Does anyone know how to solve this problem? Thanks.

**Comment by mcspa** [comment]
I solved it by calling _'apt-get install intel-mkl-64bit-2018.4-057'_ instead of installing the newest MKL version from the Intel website.

**Comment by jacobkahn** [comment]
This is good to know that there's some incompatibility — thanks for reporting @mcspa.
