### ISSUE TITLE
Issue in installing the toolkit

### ISSUE THREAD

**Issue by sanakhamekhem** [facebookresearch/wav2letter#219]
Hi, 
I have an issue when installing the toolkit. 
Thank you for your help.

[  6%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Serial.cpp.o
In file included from /home/ahmed/wav2letter/src/runtime/Serial.cpp:9:0:
/home/ahmed/wav2letter/src/runtime/Serial.h: In static member function ‘static void w2l::W2lSerializer::save(const string&, const Args& ...)’:
/home/ahmed/wav2letter/src/runtime/Serial.h:24:26: error: ‘chrono_literals’ is not a namespace-name
     using namespace std::chrono_literals;
                          ^
/home/ahmed/wav2letter/src/runtime/Serial.h:24:41: error: expected namespace-name before ‘;’ token
     using namespace std::chrono_literals;
                                         ^
/home/ahmed/wav2letter/src/runtime/Serial.h:39:29: error: unable to find numeric literal operator ‘operator""s’
     retryWithBackoff(write, 1s, 2.0, 6); // max wait 31s
                             ^
/home/ahmed/wav2letter/src/runtime/Serial.h: In static member function ‘static void w2l::W2lSerializer::load(const string&, Args& ...)’:
/home/ahmed/wav2letter/src/runtime/Serial.h:44:26: error: ‘chrono_literals’ is not a namespace-name
     using namespace std::chrono_literals;
                          ^
/home/ahmed/wav2letter/src/runtime/Serial.h:44:41: error: expected namespace-name before ‘;’ token
     using namespace std::chrono_literals;
                                         ^
/home/ahmed/wav2letter/src/runtime/Serial.h:60:28: error: unable to find numeric literal operator ‘operator""s’
     retryWithBackoff(read, 1s, 2.0, 6); // max wait 31s
                            ^
[  6%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/SpeechStatMeter.cpp.o
CMakeFiles/wav2letter++.dir/build.make:1022 : la recette pour la cible « CMakeFiles/wav2letter++.dir/src/runtime/Serial.cpp.o » a échouée
make[2]: *** [CMakeFiles/wav2letter++.dir/src/runtime/Serial.cpp.o] Erreur 1
make[2]: *** Attente des tâches non terminées....

**Comment by AdrienDuff** [comment]
Hi,
Same here. The last commit (c791ec67e88014dc5132d9865619f92657beb79a) seems to cause this issue. I tried to checkout just before this one and it works.

**Comment by realdoug** [comment]
The issue appears to be that ```std::chrono_literals``` support begins at c++14, not c++11: https://en.cppreference.com/w/cpp/symbol_index/chrono_literals

**Comment by jacobkahn** [comment]
Thanks for flagging. We're aware of the issue and are reverting the change that added it.

**Comment by sanakhamekhem** [comment]
Thanks Adrien and Jacob for your fast and helpfull responses.

**Comment by jacobkahn** [comment]
Fixed in 8916e18c501b8d8a0ede8d4e7c7cee7161842c7d.
