### ISSUE TITLE
ai-group.speechdata reference?

### ISSUE THREAD

**Issue by DenisPeskov** [facebookresearch/wav2letter#22]
While running the following:

~/Documents/librispeech-glu-highdropout-cpu.bin -progress -show -test ~Documents/librispeech-proc/dev-clean/84/121123 -save

It looks for a random file path and then crashes:
/Users/dpeskov/usr/bin/luajit: ./wav2letter/runtime/data.lua:146: bad argument #1 to 'lines' (**/data/local/packages/ai-group.speechdata/latest/speech/letters.lst**: No such file or directory)

I didn't find this path anywhere in runtime/data.lau, and even creating that exact file path did not resolve the issue.

Disclaimer: I did not run create/ create.sz scripts due to Flac issues, but I don't think should affect this.

**Comment by VitaliyLi** [comment]
Hi,

You need to run create scripts, those produce letters.lst. Please refer to [the earlier issue](https://github.com/facebookresearch/wav2letter/issues/10) you created asking for contents of letters.lst. What do you mean by "even creating that exact file path"? Did you just create an empty file?
