### ISSUE TITLE
SoX cannot process .flac files

### ISSUE THREAD

**Issue by sanakhamekhem** [facebookresearch/wav2letter#221]
Hi all, 
I have the following error when running preparedata.py. I will be wonderfull if you can provide me the suitable version of sox. 

  0%|          | 0/2703 [00:00<?, ?it/s]This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.

**Comment by cyx1233528** [comment]
Hi sanakhamekhem,
Have you solved the problem? How? Thanks! I have the same errors as you.
