### ISSUE TITLE
Cmake Error while building wav2letter

### ISSUE THREAD

**Issue by manu51188** [facebookresearch/wav2letter#227]
Hi Facebook team,

I am getting the following error:

-- flashlight found (include:  lib: flashlight::flashlight )
CMake Error at CMakeLists.txt:66 (message):
  flashlight must be build in distributed mode for wav2letter++

I have built Flashlight with the following command:
cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU -DFL_BUILD_DISTRIBUTED = ON

and building wav2letter with following command.
cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CPU

Please help me in resolving the above issue ?

**Comment by manu51188** [comment]
Hi Team,

I have resolved the above error and move ahead with building wav2letter source code. I deleted the flashlight build directory and used CMAKE_INSTALL_PREFIX while building Flashlight again and it works for me.

Now, I am not able to build the wav2letter source code checked out on today.

Following is the error which I am getting with make -j4:
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Defines.cpp.o
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Dictionary.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Transforms.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Utils.cpp.o
In file included from /home/mohit/wav2letter/src/common/Utils.cpp:9:0:
/home/mohit/wav2letter/src/common/Utils.h:62:33: error: ‘fl’ does not name a type
 std::vector<T> afToVector(const fl::Variable& var) {
                                 ^
/home/mohit/wav2letter/src/common/Utils.h:62:45: error: expected unqualified-id before ‘&’ token
 std::vector<T> afToVector(const fl::Variable& var) {
                                             ^
/home/mohit/wav2letter/src/common/Utils.h:62:45: error: expected ‘)’ before ‘&’ token
/home/mohit/wav2letter/src/common/Utils.h:62:47: error: expected initializer before ‘var’
 std::vector<T> afToVector(const fl::Variable& var) {
                                               ^
/home/mohit/wav2letter/src/common/Utils.h:72:1: error: ‘fl’ does not name a type
 fl::cpp::result_of_t<Fn(Args...)> retryWithBackoff(
 ^
/home/mohit/wav2letter/src/common/Utils.h:81:16: error: ‘fl’ does not name a type
     typename = fl::cpp::enable_if_t<std::is_same<
                ^
/home/mohit/wav2letter/src/common/Utils.h:81:18: error: expected ‘>’ before ‘::’ token
     typename = fl::cpp::enable_if_t<std::is_same<
                  ^
/home/mohit/wav2letter/src/common/Utils.h:91:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                        ^
/home/mohit/wav2letter/src/common/Utils.h:91:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                                  ^
/home/mohit/wav2letter/src/common/Utils.h:91:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                        ^
/home/mohit/wav2letter/src/common/Utils.h:91:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                                  ^
/home/mohit/wav2letter/src/common/Utils.h:91:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                        ^
/home/mohit/wav2letter/src/common/Utils.h:91:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                                  ^
/home/mohit/wav2letter/src/common/Utils.h:91:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                        ^
/home/mohit/wav2letter/src/common/Utils.h:91:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                                  ^
/home/mohit/wav2letter/src/common/Utils.h:91:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                        ^
/home/mohit/wav2letter/src/common/Utils.h:91:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                                  ^
/home/mohit/wav2letter/src/common/Utils.h:91:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                        ^
/home/mohit/wav2letter/src/common/Utils.h:91:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
                                                  ^
/home/mohit/wav2letter/src/common/Utils.h:105:7: error: ‘emissions’ is not a type
       emissions,
       ^
/home/mohit/wav2letter/src/common/Utils.h:106:7: error: ‘wordTargets’ is not a type
       wordTargets,
       ^
/home/mohit/wav2letter/src/common/Utils.h:107:7: error: ‘letterTargets’ is not a type
       letterTargets,
       ^
/home/mohit/wav2letter/src/common/Utils.h:108:7: error: ‘sampleIds’ is not a type
       sampleIds,
       ^
/home/mohit/wav2letter/src/common/Utils.h:109:7: error: ‘transition’ is not a type
       transition,
       ^
/home/mohit/wav2letter/src/common/Utils.h:110:7: error: ‘emissionT’ is not a type
       emissionT,
       ^
/home/mohit/wav2letter/src/common/Utils.h:111:7: error: ‘emissionN’ is not a type
       emissionN,
       ^
/home/mohit/wav2letter/src/common/Utils.h:112:7: error: ‘gflags’ is not a type
       gflags)
       ^
/home/mohit/wav2letter/src/common/Utils.h:112:13: error: ISO C++ forbids declaration of ‘FL_SAVE_LOAD’ with no type [-fpermissive]
       gflags)
             ^
/home/mohit/wav2letter/src/common/Utils.h:112:13: error: expected ‘;’ at end of member declaration
In file included from /home/mohit/wav2letter/src/common/Utils.h:117:0,
                 from /home/mohit/wav2letter/src/common/Utils.cpp:9:
/home/mohit/wav2letter/src/common/Utils-inl.h:60:1: error: ‘fl’ does not name a type
 fl::cpp::result_of_t<Fn(Args...)> retryWithBackoff(
 ^
/home/mohit/wav2letter/src/common/Utils.cpp: In function ‘std::__cxx11::string w2l::join(const string&, const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/mohit/wav2letter/src/common/Utils.cpp:33:44: error: no matching function for call to ‘join(const string&, std::vector<std::__cxx11::basic_string<char> >::const_iterator, std::vector<std::__cxx11::basic_string<char> >::const_iterator)’
   return join(delim, vec.begin(), vec.end());
                                            ^
In file included from /home/mohit/wav2letter/src/common/Utils.h:117:0,
                 from /home/mohit/wav2letter/src/common/Utils.cpp:9:
/home/mohit/wav2letter/src/common/Utils-inl.h:38:13: note: candidate: template<class FwdIt, class> std::__cxx11::string w2l::join(const string&, FwdIt, FwdIt)
 std::string join(const std::string& delim, FwdIt begin, FwdIt end) {
             ^
/home/mohit/wav2letter/src/common/Utils-inl.h:38:13: note:   template argument deduction/substitution failed:
/home/mohit/wav2letter/src/common/Utils.cpp:30:13: note: candidate: std::__cxx11::string w2l::join(const string&, const std::vector<std::__cxx11::basic_string<char> >&)
 std::string join(
             ^
/home/mohit/wav2letter/src/common/Utils.cpp:30:13: note:   candidate expects 2 arguments, 3 provided
/home/mohit/wav2letter/src/common/Utils.cpp: At global scope:
/home/mohit/wav2letter/src/common/Utils.cpp:36:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                        ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                                  ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                        ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                                  ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                        ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                                  ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                        ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                                  ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                        ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                                  ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:29: error: redefinition of ‘int64_t w2l::numTotalParams’
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                             ^
In file included from /home/mohit/wav2letter/src/common/Utils.cpp:9:0:
/home/mohit/wav2letter/src/common/Utils.h:91:9: note: ‘int64_t w2l::numTotalParams’ previously defined here
 int64_t numTotalParams(std::shared_ptr<fl::Module> module);
         ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:40: error: ‘fl’ was not declared in this scope
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                        ^
/home/mohit/wav2letter/src/common/Utils.cpp:36:50: error: template argument 1 is invalid
 int64_t numTotalParams(std::shared_ptr<fl::Module> module) {
                                                  ^
/home/mohit/wav2letter/src/common/Utils.cpp:44:1: error: expected ‘}’ at end of input
 } // namespace w2l
 ^
CMakeFiles/wav2letter++.dir/build.make:134: recipe for target 'CMakeFiles/wav2letter++.dir/src/common/Utils.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/common/Utils.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

I am enclosing my cmake results as well which is obtained using following command:
cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CPU

-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.a)
-- GLOG found
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.a)
-- GFLAGS found
-- OpenMP found
-- flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /home/mohit/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /home/mohit/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /home/mohit/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: /usr/local/lib/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- MKL found
-- FFTW found
-- Required SndFile dependency Ogg found.
-- Required SndFile dependency Vorbis found.
-- Required SndFile dependency VorbisEnc found.
-- Required SndFile dependency FLAC found.
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.a include: /usr/local/include
-- libsndfile found.
-- Looking for KenLM
-- Using kenlm library found in /home/mohit/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/mohit/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /home/mohit/kenlm/lm/model.hh
-- Found kenlm (include: /home/mohit/kenlm, library: /home/mohit/kenlm/build/lib/libkenlm.a;/home/mohit/kenlm/build/lib/libkenlm_util.a)
-- kenlm found
-- LZMA found (library: /usr/lib/x86_64-linux-gnu/liblzma.so include: /usr/include)
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- BZip2 not found
-- Z found (library: /usr/lib/x86_64-linux-gnu/libz.so include: /usr/include)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mohit/wav2letter/build

I am compiling the above on Ubuntu 16.04 with cmake version : 3.5.1 and g++ version 5.4.0

Please help me in resolving the above error.

**Comment by jacobkahn** [comment]
@manu51188 — what OS/compiler version are you running? Are you sure you only have one version of flashlight on your system?

It looks like flashlight isn't installed properly/isn't being linked with wav2letter. Did you `make install` flashlight after running the build? I would remove your installation of flashlight and rebuild, then rebuild wav2letter.

**Comment by manu51188** [comment]
Hi,

@jacobkahn : Thanks very much for your answer. I am working on Ubuntu 16.04 with cmake version 
3.5.1.

Yes, I am sure that flashlight is installed in my system and I did ran "make install" after make. 

I can try uninstalling the Flashlight project and build it again. Is "make uninstall" works to uninstall the Flashlight project ?

Thanks,
Mohit

**Comment by manu51188** [comment]
I didn't find the option of make uninstall in Flashlight project. 

Also, I did saw that libFlashlight.a library is installed in /usr/local/lib and include files are present in /usr/local/include.

**Comment by jacobkahn** [comment]
@manu51188 — there isn't an option to uninstall flashlight: you'll have to remove the following files/directories yourself if you want to remove it from your system:
- `/usr/local/lib/libflashlight*`
- `/usr/local/include/flashlight`
- `/usr/local/share/flashlight`

If you're using `CMAKE_INSTALL_PREFIX` when installing flashlight, make sure you pass `CMAKE_LIBRARY_PATH` and `CMAKE_INCLUDE_PATH` to your wav2letter build so the library and headers are properly found.

**Comment by manu51188** [comment]
Hi Jacob,

Thanks very much for your response.

Yes, I was using CMAK_INSTALL_PREFIX while installing flashlight otherwise it was not able to recognise that Flashlight was build in distributed mode. So, I have now included CMAKE_LIBRARY_PATH and CMAKE_INCLUDE_PATH which has helped the wav2letter project 
to know the path of Flashlight.

While building the wav2letter project, following error is encountered.

Scanning dependencies of target wav2letter++
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Defines.cpp.o
[  0%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Dictionary.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Transforms.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Utils.cpp.o

[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/common/Utils-base.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/CriterionUtils.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/ForceAlignmentCriterion.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/Seq2SeqCriterion.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/FullConnectionCriterion.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cpu/FullConnectionCriterion.cpp.o
[  1%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cpu/ViterbiPath.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/ContentAttention.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/MedianWindow.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/SoftWindow.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/attention/StepWindow.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/decoder/Decoder.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/decoder/Trie.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/decoder/KenLM.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/module/W2lModule.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Data.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Logger.cpp.o
[  2%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Serial.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/SpeechStatMeter.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Distributed.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Optimizer.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/Utils.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lDataset.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lListFilesDataset.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/W2lNumberedFilesDataset.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/NumberedFilesLoader.cpp.o
[  3%] Building CXX object CMakeFiles/wav2letter++.dir/src/data/Featurize.cpp.o
In file included from /home/mohit/wav2letter/src/feature/Mfsc.h:13:0,
                 from /home/mohit/wav2letter/src/feature/Mfcc.h:15,
                 from /home/mohit/wav2letter/src/data/Featurize.cpp:20:
/home/mohit/wav2letter/src/feature/PowerSpectrum.h:57:3: error: ‘fftw_plan’ does not name a type
   fftw_plan fftPlan_;
   ^
CMakeFiles/wav2letter++.dir/build.make:830: recipe for target 'CMakeFiles/wav2letter++.dir/src/data/Featurize.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/data/Featurize.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

Can you please look at it and let me know what is required to resolve this error ?

Also, can you please update the procedure in Flashlight to document to include library and include path while building Flashlight so that new users like me will not face such problem.

Regards

**Comment by jacobkahn** [comment]
@manu51188 — CMake install path and library/includes prefixes are standard features of CMake and are [documented accordingly](https://cmake.org/cmake/help/v3.5/variable/CMAKE_INSTALL_PREFIX.html).

From your logs, it looks like the [fftw](http://www.fftw.org/) headers weren't found — `fftw_plan` is [specified here](http://www.fftw.org/fftw3_doc/Using-Plans.html). Make sure you have the library and headers installed, and try again.

**Comment by manu51188** [comment]
Hi Jacob,

I am able to resolve the error with your support in FFTW after make and installing the FFTW again.  I have build the wav2letter now and using it for my further research.

Thanks very much for your support and help. I am closing the ticket now. 

One last query : Can you please tell me the time in which we can able to build both Flashlight and wav2letter on Windows ? Any timelines on plan?
