### ISSUE TITLE
Workload being too high while GPUs is idle

### ISSUE THREAD

**Issue by keshawnhsieh** [facebookresearch/wav2letter#228]
I want to do some training with full LibriSpeech dataset using recipe located in wav2letter/recipes/librispeech/config/conv_glu/train.cfg. The platform I used is equipped with 8 * V100 GPUs, 64 CPU cores and 400GB memory. 
I start training process by running like this
```
mpirun -n 8 --allow-run-as-root ./build/Train train --flagsfile /root/wav2letter/recipes/librispeech/config/conv_glu/train.cfg --enable_distributed true
```
However, after waiting for a long time, I noticed that the total number of thread is 713 but the usage of CPU is very low, which means all CPUs are occupied but not used. And all GPUs are idle at the same time.
```
Mon Mar  4 16:48:12 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:05.0 Off |                    0 |
| N/A   36C    P0    49W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:06.0 Off |                    0 |
| N/A   38C    P0    48W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:07.0 Off |                    0 |
| N/A   38C    P0    49W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   36C    P0    51W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:09.0 Off |                    0 |
| N/A   36C    P0    49W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:0A.0 Off |                    0 |
| N/A   38C    P0    47W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:0B.0 Off |                    0 |
| N/A   40C    P0    51W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:0C.0 Off |                    0 |
| N/A   39C    P0    49W / 160W |   4568MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
Is there anything wrong in config file ?
```
--datadir=/root/w2l
--tokensdir=/root/w2l/
--rundir=/result
--runname=librispeech_traininglogs
--archdir=/root/wav2letter/recipes/librispeech/config/conv_glu/
--train=data/train-clean-100,data/train-clean-360,data/train-other-500
--valid=data/dev-clean,data/dev-other
--arch=network.arch
--tokens=tokens.txt
--criterion=asg
--lr=0.6
--lrcrit=0.006
--linseg=1
--momentum=0.8
--maxgradnorm=0.2
--replabel=2
--surround=|
--onorm=target
--sqnorm=true
--mfsc=true
--nthread=6
--batchsize=4
--transdiag=4
```

**Comment by jacobkahn** [comment]
@keshawnhsieh — nothing looks immediately wrong with your config. How many CPU cores per GPU are you using? Are you certain that the total number of threads attributed to your train binary is 713? (I have 6,000 threads running on my machine right now in total; many fewer than that are wav2letter threads)

There should be that many threads spawned from wav2letter at any point based on what you've specified as `nthread`. Can you check that ArrayFire and flashlight tests pass to make sure something isn't spinning there?

**Comment by keshawnhsieh** [comment]
@jacobkahn I not quite sure how many CPU cores per GPU uses. Is it physically configured or set up in scripts like passing `nthread=6`. As I was running it in Docker container and there was no other program running except the  command `htop` that I ran to check CPU usage. I was sure the most of threads are created by wav2letter.

I was wondering why the number of thread is not 48 since I had config `nthread` to 6 and I got 8 GPUs in total. I will check the ArrayFire and flashlight test pass as you said. 

BTW, After waiting for about 1 hour, it finally started training progress. But it really takes too long, isn't it ?

**Comment by jacobkahn** [comment]
@keshawnhsieh — `nthread` controls the number of threads used in dataset loading and isn't related to the number of threads/cores per GPU.

> I was wondering why the number of thread is not 48

If you're starting a wav2letter train binary with `mpirun`, then the total number of threads will be the number of MPI processes by the number of dataset threads, since `nthreads` dataset threads are spawned for each MPI process. You should start as many MPI processes as there are GPUs available from your node.

Training on librispeech can take a long time, especially if you're using all of the train datasets. An hour per epoch doesn't sound too unreasonable to me on 8 GPUs. If you want to monitor intermediary process at a more granular level, you can use the `reportiters` flag — see https://github.com/facebookresearch/wav2letter/issues/141.

**Comment by zcth428** [comment]
I encountered the same problem，in same config file，when i am running on  timit dataset GPU working full load but on other big dataset CPU working full load and GPU is idle , so confusing； i have tested flashlight and all have passed !
