### ISSUE TITLE
ArrayFire Error during training

### ISSUE THREAD

**Issue by bsridatta** [facebookresearch/wav2letter#229]
Unable to resolve this issue with ArrayFire. Any directions would be very helpful

compilation tools, release 9.2, V9.2.148

Error:  build/Train train --flagsfile train.cfg 
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function std::vector<char> cuda::compileToPTX(const char*, std::__cxx11::string)
In file src/backend/cuda/jit.cpp:298
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION

In function T af::anyTrue(const af::array&) [with T = bool]
In file src/api/cpp/reduce.cpp:154
*** Aborted at 1551999312 (unix time) try "date -d @1551999312" if you are using GNU date ***
PC: @     0x7fdd99daf428 gsignal
*** SIGABRT (@0x809) received by PID 2057 (TID 0x7fddf64d2780) from PID 2057; stack trace: ***
    @     0x7fddef41a390 (unknown)
    @     0x7fdd99daf428 gsignal
    @     0x7fdd99db102a abort
    @     0x7fdd9a6f284d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fdd9a6f06b6 (unknown)
    @     0x7fdd9a6f0701 std::terminate()
    @     0x7fdd9a6f0919 __cxa_throw
    @     0x7fdd9af966be af::anyTrue<>()
    @           0x4697b7 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE4_clES2_S5_S7_S9_S9_ddbi.constprop.9454
    @           0x419487 main
    @     0x7fdd99d9a830 __libc_start_main
    @           0x4656f9 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by jacobkahn** [comment]
@bsridatta — this sounds like an issue with your GPU driver; it may not be new enough (https://github.com/facebookresearch/flashlight/issues/37 may be relevant). Can you:
1. Check if flashlight tests pass?
2. If so, check if ArrayFire tests pass? If you've installed ArrayFire with the prebuilt libraries, can you check that your CUDA and NVIDIA driver meet the requirements?
3. If not, can you build ArrayFire from source and see if tests pass with that build?

**Comment by bsridatta** [comment]
Following comments from other posts, I have built ArrayFire from source and it didn't work. But I'll test flashlight tests and see if it fixes it.  Thanks for the reply!

**Comment by jacobkahn** [comment]
@bsridatta make sure ArrayFire tests pass as well after you build from source.
