### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by hjg10029** [facebookresearch/wav2letter#232]
I am a newbie. I found no online decoder in the dockerfile-GPU. When is the dockerfile updated?

**Comment by tlikhomanenko** [comment]
Hi @hjg10029,

Will update it tomorrow. Thanks for reminder!

**Comment by tlikhomanenko** [comment]
Hi @hjg10029,

I have updated docker images with the current latest versions for CPU and CUDA backends. Welcome to use them!

**Comment by hjg10029** [comment]
Thank you very much.As a newcomer to ASR ,I still have a question. What commands do I need to enter for online decoding?
