### ISSUE TITLE
Segfault when training

### ISSUE THREAD

**Issue by CamJN** [facebookresearch/wav2letter#233]
I run `./Train train --flagsfile ../tutorials/1-librispeech_clean/train.cfg` and get the following error:
```
*** Aborted at 1552402833 (unix time) try "date -d @1552402833" if you are using GNU date ***
PC: @     0x7fae5b97ec17 mkl_dft_bless_node_omp
*** SIGSEGV (@0x0) received by PID 11748 (TID 0x7faed59b37c0) from PID 0; stack trace: ***
    @     0x7faebaae4890 (unknown)
    @     0x7fae5b97ec17 mkl_dft_bless_node_omp
    @     0x7fae5ca999d7 DftiCreateDescriptor_d_1d
    @     0x7fae5caa0170 fftw_plan_guru64_dft_r2c
    @     0x7fae5ca9ee6b fftw_plan_dft_r2c
    @     0x7fae5ca9eeab fftw_plan_dft_r2c_1d
    @     0x55f4def103da speech::PowerSpectrum<>::PowerSpectrum()
    @     0x55f4def0d1a7 speech::Mfsc<>::Mfsc()
    @     0x55f4def0569e w2l::featurize()
    @     0x55f4deeede76 w2l::W2lDataset::getFeatureData()
    @     0x55f4deeef6b6 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x55f4deeefc18 w2l::W2lDataset::get()
    @     0x55f4dedb653f _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi
    @     0x55f4ded77af9 main
    @     0x7fae55c53b97 __libc_start_main
    @     0x55f4dedb2e2a _start
Segmentation fault (core dumped)
```

CUDA backend, all deps installed.

**Comment by jacobkahn** [comment]
See https://github.com/facebookresearch/wav2letter/issues/208. Confirm that ArrayFire and flashlight tests pass. If not, post an issue in those respective places; feel free to follow up here if everything passes.

**Comment by CamJN** [comment]
When I built wav2letter, I used cuda 9.2 libs, and the build went fine. But I get `./Train: error while loading shared libraries: libnvrtc.so.10.0: cannot open shared object file: No such file or directory` when trying to run it. Then I installed CUDA 10.0, and ran Train, to get the issue described above. I ran the flashlight tests and they all passed, then because they aren't included in the normal installer for arrayfire I rebuilt arrayfire from source (with only cuda 9.2 in the LD_LIBRARY_PATH and PATH env vars, but cuda 10 was installed per above) and ran the arrayfire tests and got a segfault in the test_threading_cuda test, then tried to rebuild arrayfire with cuda 10.0 but cuda 10 doesn't include libcublas_device, which we found in step one is required for wav2letter.


So how am I supposed to get this working when I both need and cannot use cuda 10?

**Comment by jacobkahn** [comment]
@CamJN — you can use flashlight and wav2letter with ArrayFire >= 3.6.1 — we're still using ArrayFire 3.6.1. I'd try [checking it out](https://github.com/arrayfire/arrayfire/releases/tag/v3.6.1) (`git checkout b443e14`), building from source, then rebuilding flashlight and wav2letter. The CUDA 10 requirement should not exist in ArrayFIre 3.6.1.
