### ISSUE TITLE
std::bad_alloc when Decoding

### ISSUE THREAD

**Issue by apldev3** [facebookresearch/wav2letter#234]
Hey guys just wanted to ask for some advice on this issue that I've hit a bit of a wall on.

I've been trying to perform Decoding with a model that I got to successfully train on the VoxForge Spanish dataset and using a KenLM language model trained on 100% of the OPUS MultiUN monolingual untokenized Spanish plaintext file (that being said there is a lot of preprocessing involved before actually throwing it over to KenLM).

At any rate, when attempting to do some decoding using this combination, I get a bad::alloc, a la

> F0312 15:26:01.203004 55325 Decode.cpp:402] Exception in thread 2
std::bad_alloc
*** Check failure stack trace: ***
F0312 15:26:01.213933 55327 Decode.cpp:402] Exception in thread 4
std::bad_alloc
*** Check failure stack trace: ***
    @     0x7ff76607f5cd  google::LogMessage::Fail()
    @     0x7ff76607f5cd  google::LogMessage::Fail()
F0312 15:26:01.213933 55327 Decode.cpp:402] Exception in thread 4
std::bad_allocF0312 15:26:01.806497 55330 Decode.cpp:402] Exception in thread 7
std::bad_alloc
*** Check failure stack trace: ***
    @     0x7ff766081433  google::LogMessage::SendToLog()
    @     0x7ff766081433  google::LogMessage::SendToLog()
    @     0x7ff76607f5cd  google::LogMessage::Fail()
    @     0x7ff76607f15b  google::LogMessage::Flush()
    @     0x7ff76607f15b  google::LogMessage::Flush()
    @     0x7ff766081433  google::LogMessage::SendToLog()
    @     0x7ff766081e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff766081e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x45ca2c  _ZZ4mainENKUliiiE2_clEiii
    @           0x45ca2c  _ZZ4mainENKUliiiE2_clEiii
    @           0x45e584  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_ESt12_Bind_simpleIFSt17reference_wrapperISt5_BindIFZ4mainEUliiiE2_iiiEEEvEEvEEE9_M_invokeERKSt9_Any_data
    @           0x45e584  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_ESt12_Bind_simpleIFSt17reference_wrapperISt5_BindIFZ4mainEUliiiE2_iiiEEEvEEvEEE9_M_invokeERKSt9_Any_data
    @           0x462c69  std::__future_base::_State_baseV2::_M_do_set()
    @           0x462c69  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7ff76607f15b  google::LogMessage::Flush()
    @     0x7ff766d90a99  __pthread_once_slow
    @     0x7ff766d90a99  __pthread_once_slow
    @           0x45ab81  _ZNSt13__future_base11_Task_stateISt5_BindIFZ4mainEUliiiE2_iiiEESaIiEFvvEE6_M_runEv
    @           0x45ab81  _ZNSt13__future_base11_Task_stateISt5_BindIFZ4mainEUliiiE2_iiiEESaIiEFvvEE6_M_runEv
    @           0x46775b  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN2fl10ThreadPoolC4EmRKSt8functionIFvmEEEUlvE_vEEE6_M_runEv
    @           0x46775b  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN2fl10ThreadPoolC4EmRKSt8functionIFvmEEEUlvE_vEEE6_M_runEv
    @     0x7ff766081e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x45ca2c  _ZZ4mainENKUliiiE2_clEiii
    @           0x45e584  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_ESt12_Bind_simpleIFSt17reference_wrapperISt5_BindIFZ4mainEUliiiE2_iiiEEEvEEvEEE9_M_invokeERKSt9_Any_data
    @           0x462c69  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7ff6edd02c80  (unknown)
    @     0x7ff6edd02c80  (unknown)
    @     0x7ff766d90a99  __pthread_once_slow
    @           0x45ab81  _ZNSt13__future_base11_Task_stateISt5_BindIFZ4mainEUliiiE2_iiiEESaIiEFvvEE6_M_runEv
    @           0x46775b  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN2fl10ThreadPoolC4EmRKSt8functionIFvmEEEUlvE_vEEE6_M_runEv
    @     0x7ff766d896ba  start_thread
    @     0x7ff766d896ba  start_thread
    @     0x7ff6edd02c80  (unknown)
    @     0x7ff6ed24641d  clone
    @     0x7ff6ed24641d  clone
F0312 15:26:01.213933 55327 Decode.cpp:402] Exception in thread 4
std::bad_allocF0312 15:26:01.806497 55330 Decode.cpp:402] Exception in thread 7
std::bad_allocF0312 15:26:02.209452 55324 Decode.cpp:402] Exception in thread 1
std::bad_alloc
*** Check failure stack trace: ***
    @     0x7ff766d896ba  start_thread
    @              (nil)  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

The claimed offending line of code (Decoder.cpp:402) looks to start a timer in flashlight, but that seems odd that that would break the camel's back here.

> --datadir=/shared/install/wav2letter/w2l/voxforge75
--tokens=tokens.txt
--lexicon=/shared/install/wav2letter/w2l/lm/lexicon.txt
--lm=/shared/install/wav2letter/w2l/lm/MultiUN100.blm
--am=/shared/install/wav2letter/w2l/train/VoxForge_75/001_model_validation.bin
--test=test
--sclite=/shared/install/wav2letter/w2l/decode
--lmweight=2.5
--wordscore=1
--beamsize=1000
--beamscore=25
--silweight=-0.5
--nthread=4
--nthread_decoder=8
--smearing=max
--show
--showletters

Here's my current `decode.cfg`. Would you all have any suggestions as to how to avoid the bad_alloc?

**Comment by xuqiantong** [comment]
Can you try to pull the master again? Right now the language model will loaded only once and shared among all the threads. This will relieve the memory usage. 
If this doesn't work for you, please share all your stderr output here.

**Comment by apldev3** [comment]
Looks to be that I initially downloaded the project on February 20, so if any change occurred between now and then, it seems to be a good candidate. Will try to pull and let you know how it goes in a little while.

**Comment by apldev3** [comment]
Apologies for the delay, am just now finally getting back to this after a couple days. After the pull, I managed to get to a new error that once resolved let me actually do a complete decoding, so we're all good here!

Cheers! :tada: :tada:
