### ISSUE TITLE
Input flag

### ISSUE THREAD

**Issue by sanakhamekhem** [facebookresearch/wav2letter#236]
I would like to ask about the input flag. Is there other extension than .flac or .wav?
Can the toolkit process images (tiff...) ?
Thank you in advance.

**Comment by jacobkahn** [comment]
@sanakhamekhem — wav2letter is built as a framework for automatic recognition. I'd recommend you take a look at [flashlight](https://github.com/facebookresearch/flashlight) (the C++ ML library that powers w2l) if you're looking for something more generic that can handle images.

To answer your first question, wav2letter can support audio formats supported by [libsndfile](https://github.com/erikd/libsndfile) (more information [here](http://www.mega-nerd.com/libsndfile/)). You can use the `input` flag to specify the format of files you're looking to parse (e.g. `--input=wav` will look for `.wav` files).

**Comment by sanakhamekhem** [comment]
Thank you for your response.
