### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#24]
HI 
when I am running the below command
'luajit /wav2letter/test.lua /experiments/hello_librispeech/001_model_dev-clean.bin -progress -show -test dev-clean -save'

I am getting the following error 'CUDA driver version is insufficient for CUDA runtime version'. can someone help me solve this.

Ps- i am trying to run the pretrained model in gcloud gpu instance

**Comment by saisrinivas047** [comment]
@VitaliyLi

**Comment by VitaliyLi** [comment]
What CUDA version are you using? You need CUDA 8.0.

**Comment by saisrinivas047** [comment]
this is what I get after running nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by VitaliyLi** [comment]
Not sure what exactly is wrong. [This](https://stackoverflow.com/questions/41409842/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-vers) solution might work.

**Comment by saisrinivas047** [comment]
sure will try that, thanks for the fast reply.

**Comment by saisrinivas047** [comment]
@VitaliyLi Can you please briefly tell the process to run the pre-trained model in cpu. Does running the model in cpu require Cuda. ?

**Comment by saisrinivas047** [comment]
how much time does running a pretrained model takes approximately. for me it is showing around 6days to complete

**Comment by VitaliyLi** [comment]
For training - on 4 GPUs 1 epoch takes 1 day. If you are running 1 GPU only, 6 days is reasonable. You can make epochs shorter with flag -itersz.

**Comment by saisrinivas047** [comment]
there is no need for training for pretrained model right. so for running the pre-trained model also will ir take same time to complete ?

**Comment by saisrinivas047** [comment]
when I am trying to transcribe speech using "luajit ~/wav2letter/test.lua ~/librispeech-glu-highdropout-cpu.bin -progress -show -test dev-clean -save -datadir ~/librispeech-proc/ -dictdir ~/librispeech-proc/ -gfsai"  command  it is showling 

[Sentence WER: 000.00%, dataset WER: 003.70%]
 [.................... 2/2703 ..................]  ETA: 6D13h | Step: 3m29s 

will it really take 6
days to complete ?

**Comment by VitaliyLi** [comment]
6 days indeed is too long for 3k sequences. Do you use Intel MKL?

**Comment by srinivas047** [comment]
I did a mistake actually, I want to use pretrained model to transcribe few audio files but instead I am transcribing librispeech data. Can you tell me the audio format to transcribe single audio file because I see that the librispeech audio is splitted into different parts should I also split my audio file. Can you specify the steps for data preparation to transcribe sample audio files
