### ISSUE TITLE
Token File content

### ISSUE THREAD

**Issue by sanakhamekhem** [facebookresearch/wav2letter#240]
Hi, I would to ask about the token list if it support other tokens variant such as:
|
aaA
aaE
....

**Comment by jacobkahn** [comment]
@sanakhamekhem — yes, you can use other things (like phonemes, word-pieces, etc). In general, the tokens file determines what categories the AM/network will produce a probability distribution over as output.

**Comment by sanakhamekhem** [comment]
Thank you Sir.
