### ISSUE TITLE
Single GPU Recipe for LibriSpeech

### ISSUE THREAD

**Issue by ahmadab** [facebookresearch/wav2letter#244]
It seems that the published recipe for LibriSpeech was built using 8 GPU (according to a response on a related thread)

Are there any plans to publish one for a single GPU? Or is there any guidance on which flags need to change from the 8-GPU recipe? Is it just lRate?

**Comment by jacobkahn** [comment]
@ahmadab — the only change in run configuration when you run on one GPU versus 8 would be the `--enable_distributed` flag (which you should remove for the one GPU case), and any arguments passed to `mpirun`, which you shouldn't be using anyways if you're only on one GPU. The recipe should work as is.
