### ISSUE TITLE
Failed to run the Train 

### ISSUE THREAD

**Issue by CHSTR** [facebookresearch/wav2letter#245]
when run the next command line: Train train --flagsfile ~/wav2letter/tutorials/1-librispeech_clean/train.cfg in my nvidia-docker, show this error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open dictionary file: [...]/data/tokens.txt
*** Aborted at 1553196749 (unix time) try "date -d @1553196749" if you are using GNU date ***
PC: @     0x7fd836166428 gsignal
*** SIGABRT (@0xb80) received by PID 2944 (TID 0x7fd895e06780) from PID 2944; stack trace: ***
    @     0x7fd879f04390 (unknown)
    @     0x7fd836166428 gsignal
    @     0x7fd83616802a abort
    @     0x7fd836aa984d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fd836aa76b6 (unknown)
    @     0x7fd836aa7701 std::terminate()
    @     0x7fd836aa7919 __cxa_throw
    @           0x5351e3 w2l::createTokenDict()
    @           0x5354a1 w2l::createTokenDict()
    @           0x4184b8 main
    @     0x7fd836151830 __libc_start_main
    @           0x465619 _start
    @                0x0 (unknown)
Aborted (core dumped)

What will I do wrong?
I followed these instructions: [https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean#e2e-speech-recognition-on-librispeech-clean-dataset](url)
Thanks.

**Comment by jacobkahn** [comment]
@CHSTR — you need to change `[...]` in your flagsfile for your `tokensdir` to point to the directory containing your `tokens.txt` file.
