### ISSUE TITLE
wav2letter++ install on Ubuntu 16.04

### ISSUE THREAD

**Issue by sanjaykasturia** [facebookresearch/wav2letter#246]
I installed flashlight succesfully (all tests passed) in /home/sanjay/flashlight

In installing wav2letter++,  cmake errors out at find_package(flashlight REQUIRED)

The error message is:
 _CMake Error at CMakeLists.txt:62 (find_package):
  By not providing "Findflashlight.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "flashlight", but CMake did not find one.

  Could not find a package configuration file provided by "flashlight" with
  any of the following names:

    flashlightConfig.cmake
    flashlight-config.cmake

  Add the installation prefix of "flashlight" to CMAKE_PREFIX_PATH or set
  "flashlight_DIR" to a directory containing one of the above files.  If
  "flashlight" provides a separate development package or SDK, be sure it has
  been installed._

In my case, the flashlightConfig.cmake file which is mentioned above is in
/home/sanjay/flashlight/build/cmake/install

So following the suggestion in the error message, I tried to resolve the problem with:
export flashlight_DIR=/home/sanjay/flashlight/build/cmake/install

With this, I get past the: 
find_package(flashlight REQUIRED)

but get an error:
flashlight must be build in distributed mode for wav2letter++

This is indicating that find_package(flashlight) is not finding/setting the right paths.
1. Should I install flashlight in a different location?
2. Is there a Findflashlight.cmake that can be added to the cmake directory to resolve this?
3. In addition to the export flashlight_DIR=/home/sanjay/flashlight/build/cmake/install are there other settings that can fix this?

https://github.com/facebookresearch/wav2letter/issues/227 seemed to start with the same issue but claimed to resolve it by: "I deleted the flashlight build directory and used CMAKE_INSTALL_PREFIX while building Flashlight again" but I don't know exactly what was done here.

**Comment by sanjaykasturia** [comment]
problem resolved by using a cmake directive with a relative path instead of exporting path to flashlightConfig.cmake as follows:
cmake .. -Dflashlight_DIR=../flashlight -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CUDA

In this case, the flashlight directory was ../ relative to the wav2letter directory

**Comment by sanjaykasturia** [comment]
I thought my build was successful as it completed without errors and all the tests passed but the build directory does not have a "Decode" executable. It does have Train, Test & Decoder. 

Here's the cmake and make & output:
cmake .. -Dflashlight_DIR=../flashlight -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CUDA

make -j8 # (or any number of threads)
build completed with no errors.
cd /wav2letter/build && make test
Running tests...
Test project /home/sanjay/wav2letter/build
      Start  1: W2lCommonTest
 1/19 Test  #1: W2lCommonTest ....................   Passed    3.95 sec
      Start  2: CriterionTest
 2/19 Test  #2: CriterionTest ....................   Passed    9.07 sec
      Start  3: Seq2SeqTest
 3/19 Test  #3: Seq2SeqTest ......................   Passed    6.86 sec
      Start  4: AttentionTest
 4/19 Test  #4: AttentionTest ....................   Passed    1.97 sec
      Start  5: WindowTest
 5/19 Test  #5: WindowTest .......................   Passed    2.18 sec
      Start  6: DataTest
 6/19 Test  #6: DataTest .........................   Passed    1.38 sec
      Start  7: DecoderTest
 7/19 Test  #7: DecoderTest ......................   Passed    0.99 sec
      Start  8: CeplifterTest
 8/19 Test  #8: CeplifterTest ....................   Passed    0.08 sec
      Start  9: DctTest
 9/19 Test  #9: DctTest ..........................   Passed    0.12 sec
      Start 10: DerivativesTest
10/19 Test #10: DerivativesTest ..................   Passed    0.08 sec
      Start 11: DitherTest
11/19 Test #11: DitherTest .......................   Passed    8.10 sec
      Start 12: MfccTest
12/19 Test #12: MfccTest .........................   Passed    0.19 sec
      Start 13: PreEmphasisTest
13/19 Test #13: PreEmphasisTest ..................   Passed    0.07 sec
      Start 14: SoundTest
14/19 Test #14: SoundTest ........................   Passed    0.11 sec
      Start 15: SpeechUtilsTest
15/19 Test #15: SpeechUtilsTest ..................   Passed    1.40 sec
      Start 16: TriFilterbankTest
16/19 Test #16: TriFilterbankTest ................   Passed    0.11 sec
      Start 17: WindowingTest
17/19 Test #17: WindowingTest ....................   Passed    0.08 sec
      Start 18: W2lModuleTest
18/19 Test #18: W2lModuleTest ....................   Passed    2.90 sec
      Start 19: RuntimeTest
19/19 Test #19: RuntimeTest ......................   Passed    2.39 sec

100% tests passed, 0 tests failed out of 19

Total Test time (real) =  42.03 sec

**Comment by jacobkahn** [comment]
@sanjaykasturia - that's a error in the docs. We'll fix that. Thanks for flagging.

**Comment by ishita1995** [comment]
Hi, 
I am facing the same , but unfortunately above mentioned solution does not work in my case.
neither relative nor absolute paths seems to work.
Is there some other solution to this problem ?

**Comment by jacobkahn** [comment]
@ishita1995 — can you confirm that `flashlightConfig.cmake` is found in the absolute path you're passing to `flashlight_DIR`?

**Comment by ishita1995** [comment]
Hi, 
Yes I gave both absolute and relative path to flashlight_DIR

**Comment by jacobkahn** [comment]
@ishita1995 — confirm that you're using CMake 3.5.1 and above, and that the for the directory you're using in `-Dflashlight_DIR=$FLASHLIGHT_CMAKE_DIR`, `$FLASHLIGHT_CMAKE_DIR/flashlightConfig.cmake` exists.

**Comment by rangakamesh** [comment]
Hello,

I am being notified of the same issue. I can confirm that i have flashlightConfig.make in my flashlight directory. can you please help ? 

![Screenshot from 2020-03-21 21-42-09](https://user-images.githubusercontent.com/37494279/77240512-e2b8b180-6bbc-11ea-9a03-8af6af912d7d.png)

**Comment by rangakamesh** [comment]
hi, 

cleaning and rebuilding my flashlight solved the issue. sorry for prompting a closed ticket.

**Comment by manojmsrit** [comment]
Facing above issue when I am trying to build wav2letter in Docker. Please help me regarding this.

Steps I followed:

sudo docker run --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cpu-latest
sudo docker exec -it w2l bash
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_LIBRARY_PATH
cd /root/flashlight && git pull
cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU
make -j8 && make install
export KENLM_ROOT_DIR=/root/kenlm
cd /root/wav2letter
git pull (Did not work due to authentication issue, i tried adding ssh key but also did not work )
rm -rf build/*
cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=OFF -DW2L_BUILD_INFERENCE=ON
Then I encountered below issue. Please help me regarding the same. Thank you.

root@287c7bdde47f:~/wav2letter/build# cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=OFF -DW2L_BUILD_INFERENCE=ON
-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- OpenMP found
-- flashlight found (include:  lib: flashlight::flashlight )
CMake Error at CMakeLists.txt:103 (message):
  flashlight must be build in distributed mode for wav2letter++


-- Configuring incomplete, errors occurred!
See also "/root/wav2letter/build/CMakeFiles/CMakeOutput.log".

**Comment by tlikhomanenko** [comment]
do I understand right that you didn't do pull from github and just rebuild inside docker?

**Comment by wahyubram82** [comment]
> hi,
> 
> cleaning and rebuilding my flashlight solved the issue. sorry for prompting a closed ticket.

what the rebuild comand that you use? what command that make it build to wav2letter?

**Comment by tlikhomanenko** [comment]
In docker for rebuild you need pull and then run the same commands as we have in the Dockerfile.

**Comment by manojmsrit** [comment]
Yes, But git pull command is giving authentication issues. It is not able to pull the latest code. That is the problem

**Comment by tlikhomanenko** [comment]
you can just remove the folder, do git clone and repeat commands from the docker files on the flashlight and wav2letter.
