### ISSUE TITLE
Running train on librispeech

### ISSUE THREAD

**Issue by sanjaykasturia** [facebookresearch/wav2letter#248]
This identical to issue #133 but I can't reopen it so posting as a new issue.
running train on librispeech/train-clean-100 results in an ArrayFire Exception (Device out of memory:101).
I'm running this on ubuntu 16.04 LTS
Machine info:
Processor:	Intel Core i7-7800X CPU@3.50GHzx12
Graphics:	GeForce RTX 2070/PCIeSSE2
OS type:	64-bit
Disk:		2.2TB

Cuda details:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

CUDNN version
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 2

I build with CUDA backend. All flashlight tests passed on installation.

I am posting two sets of error reports. The first is with the default train.cfg
The second is with batchsize changed from 4 to 1. The place the memory exception occurs is different but it is still a memory exception in AF.

---------------with default train.cfg settings-----------------------------
~/wav2letter/recipes/librispeech$ $HOME/wav2letter/build/Train train --flagsfile config/conv_glu/train.cfg
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function void* cuda::MemoryManager::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:191
CUDA Error (2): out of memory

In function void af::initDataArray(void**, const T*, af::source, dim_t, dim_t, dim_t, dim_t) [with T = double; af_array = void*; af::source = af_source; dim_t = long long int]
In file src/api/cpp/array.cpp:141
*** Aborted at 1553706234 (unix time) try "date -d @1553706234" if you are using GNU date ***
PC: @     0x7f811b610428 gsignal
*** SIGABRT (@0x3ea00001d19) received by PID 7449 (TID 0x7f819eb55a80) from PID 7449; stack trace: ***
    @     0x7f819e06e390 (unknown)
    @     0x7f811b610428 gsignal
    @     0x7f811b61202a abort
    @     0x7f811c17584d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f811c1736b6 (unknown)
    @     0x7f811c173701 std::terminate()
    @     0x7f811c173919 __cxa_throw
    @     0x7f812492782f af::initDataArray<>()
    @     0x7f812492c479 af::array::array<>()
    @           0x552d8a w2l::FullConnectionCriterion::forward()
    @           0x47aef6 w2l::AutoSegmentationCriterion::forward()
    @           0x47cc35 w2l::LinearSegmentationCriterion::forward()
    @           0x469bec _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.9786
    @           0x419b70 main
    @     0x7f811b5fb830 __libc_start_main
    @           0x4658b9 _start
    @                0x0 (unknown)
Aborted (core dumped)

---------------------with batchsize reduced to 1------------------------------------------
$HOME/wav2letter/build/Train train --flagsfile config/conv_glu/train.cfg
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function void* cuda::MemoryManager::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:191
CUDA Error (2): out of memory

In function af::array af::sum(const af::array&, int)
In file src/api/cpp/reduce.cpp:21
*** Aborted at 1553709199 (unix time) try "date -d @1553709199" if you are using GNU date ***
PC: @     0x7fe7bead4428 gsignal
*** SIGABRT (@0x3ea000021d7) received by PID 8663 (TID 0x7fe842019a80) from PID 8663; stack trace: ***
    @     0x7fe841532390 (unknown)
    @     0x7fe7bead4428 gsignal
    @     0x7fe7bead602a abort
    @     0x7fe7bf63984d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fe7bf6376b6 (unknown)
    @     0x7fe7bf637701 std::terminate()
    @     0x7fe7bf637919 __cxa_throw
    @     0x7fe7c7e97712 af::sum()
    @           0x666003 fl::sumAs()
    @           0x666238 _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_6tileAsES7_RKN2af4dim4EEUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @           0x658884 fl::Variable::backward()
    @           0x658e03 fl::Variable::backward()
    @           0x469e57 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.9786
    @           0x419b70 main
    @     0x7fe7beabf830 __libc_start_main
    @           0x4658b9 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by sanjaykasturia** [comment]
Switching to the simpler network shown in the librispeech tutorial, I was able to get train to run without seeing the memory error but would still like to know how to fix the memory error.

**Comment by jacobkahn** [comment]
@sanjaykasturia - the model and dataset are probably too large to fit on your GPU. You'd need to get more GPU memory or, as you've done, use a smaller model.

**Comment by sanjaykasturia** [comment]
Thanks Jacob. Can you specify how much memory is needed on the GPU to run this model, or, which GPU model/memory configuration it ran successfully?

**Comment by jacobkahn** [comment]
@sanjaykasturia — I'm not sure exactly how much memory is required to run the model, but we've successfully run it on NVIDIA P100 SMX2 nodes with 16 GB of onboard memory. Hope this helps. Depending on how many GPUs you have, Librispeech itself may not fit in memory: I know that with two Tesla M40s with ~12 GB of memory, the dataset doesn't fit. Increasing the number of GPUs can facilitate splitting up the dataset more evenly.

**Comment by sanjaykasturia** [comment]
Thanks Jacob!
