### ISSUE TITLE
Pre-trained model in CPU

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#25]
Can you please briefly tell the process to run the pre-trained model in cpu. Does running the model in cpu require Cuda. ?

**Comment by salehgundogdu** [comment]
It can't require cuda. 
I am also having some problems to run pre-trained-cpu model.

**Comment by saisrinivas047** [comment]
remove the require 'cunn' and 'cudnn' from test.lua then we don't require cuda. if you are successful in running the model can you tell the estimated time it showed to complete ?
