### ISSUE TITLE
Minor correction on tutorial (https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean)

### ISSUE THREAD

**Issue by sanjaykasturia** [facebookresearch/wav2letter#250]
Decoding instructions in tutorial say:
# Replace [...] with appropriate paths in decode.cfg before starting
> [...]/wav2letter/build/Decode --flagsfile [...]/wav2letter/tutorials/librispeech_clean/decode.cfg

But I think the decoder executable is "Decoder" and not "Decode" if built according to the instructions.

**Comment by jacobkahn** [comment]
Fixed in https://github.com/facebookresearch/wav2letter/commit/99fd97f0e7592c73e54eb568015255a8dc876a1c. Thanks for flagging.
