### ISSUE TITLE
How to set id file when no gender and speaker information

### ISSUE THREAD

**Issue by GabrielLin** [facebookresearch/wav2letter#254]
I have a lot of speech with transcription but no gender and speaker. How should I set the .id file. Thanks.

**Comment by lunixbochs** [comment]
I think you can just not put those lines in the id file and it's fine.

**Comment by siddharthasahu** [comment]
In the tutorial, they save `file_id`: https://github.com/facebookresearch/wav2letter/blob/master/tutorials/1-librispeech_clean/prepare_data.py#L66

**Comment by vineelpratap** [comment]
Currently, we do not use ` .id ` file. There is no need to create those files at all.
