### ISSUE TITLE
What are the other parameters in the W2 layer?

### ISSUE THREAD

**Issue by sanjaykasturia** [facebookresearch/wav2letter#258]
Per the documentation on in arch.md [https://github.com/facebookresearch/wav2letter/blob/master/docs/arch.md] the weight normalization layer WN has two parameters:
fl::WeightNorm WN [normDim] [Layer]
however the  sample network.arch file provided for librispeech has WN2 with many more parameters eg:
WN 3 C 565 1242 25 1 0

What are these other parameters? In this example, what value does "C" take and what are "565 1242 25 1 0"? If there is documentation elsewhere, can you point me to it?

I am trying to create a simpler network than the one provided in the recipe for librispeech by reducing the number of instance of:
WN
GLU
DO
but am triggering an ArrayFire error indicating that I am messing up one of the weight dimensions. This is quite possible 
Thanks!

**Comment by jacobkahn** [comment]
In `WN [normDim] [Layer]`, `[Layer]` refers to a full layer specification.
```
WN 3 C 565 1242 25 1 0
```
is effectively applying weight normalization to the layer described as `C 565 1242 25 1 0`. You can add any layer after `WN [normDim]` to add weight normalization to it.

**Comment by sanjaykasturia** [comment]
Thanks Jacob!
