### ISSUE TITLE
experiments folder not found

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#26]
luajit test.lua ~/experiments/hello_librispeech/001_model_dev-clean.bin -progress -show -test dev-clean -save
luajit: cannot open </home/saisrinivas_chetti/experiments/hello_librispeech/001_model_dev-clean.bin> in mode r  at /tmp/luarocks_torch-scm-1-5171/torch7/lib/TH/THDiskFile.c:673
stack traceback:
        [C]: at 0x7f09a425e450
        [C]: in function 'DiskFile'
        /torch/install/share/lua/5.1/wav2letter/runtime/serial.lua:54: in function 'loadmodel'
        test.lua:53: in main chunk
        [C]: at 0x00405d50

can someone help me resolve this error ?

**Comment by smolendawid** [comment]
Is the path correct? Try 001_model_last.bin

**Comment by saisrinivas047** [comment]
do you see the experiments folder in your model ?
