### ISSUE TITLE
Switch from CPU to GPU

### ISSUE THREAD

**Issue by sanakhamekhem** [facebookresearch/wav2letter#262]
Hi, 
I have trained my data for 2 epochs using CPU installation. Now, I would like to switch to GPU configuration. 
Is it possible to resume training from epoch 2 ?
I would like to change the batchsize and nthread number, is it possible also??? 

Thank you in advance.

**Comment by lunixbochs** [comment]
I think you can edit the flagsfile and use `Train continue <model directory>`
