### ISSUE TITLE
Pytorch version in future?

### ISSUE THREAD

**Issue by snakers4** [facebookresearch/wav2letter#263]
Hi,

Many thanks for your amazing library.
I saw old questions (early 2018) about PyTorch.
No plans to build a PyTorch version?
If so, are you accepting contributions?

PyTorch boasts CTC loss in 1.0 now =)

**Comment by jacobkahn** [comment]
@snakers4 — no promises, but there are plans/work in progress porting several components of wav2letter to a generic Python interface that might be compatible with PyTorch including ASG and the decoder. Expect more on this in the next few months.

**Comment by snakers4** [comment]
Thank you for your reply!
