### ISSUE TITLE
Streaming inference latency/framing

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#266]
I can see how to do a streaming decoder, but I'm trying to figure out how to optimize the emission loop when streaming. My first attempt have been split between: very poor quality emissions, dropped emissions, or a lot of latency.

I've reduced the problem to a realtime audio pipeline that executes this code in a loop on samples from a live mic:
```
struct W2lLoaderData data = {};
data.input = samples;

auto feat = featurize({data}, state.dicts);
auto result = af::array(feat.inputDims, feat.input.data());

auto rawEmission = state.network->forward({fl::input(result)}).front();

auto viterbiPath =
  afToVector<int>(state.criterion->viterbiPath(rawEmission.array()));
if (FLAGS_criterion == kCtcCriterion || FLAGS_criterion == kAsgCriterion) {
  uniq(viterbiPath);
}
remapLabels(viterbiPath, state.tokenDict); 
auto letters = tensor2letters(viterbiPath, state.tokenDict);
if (letters.size() > 0) {
  std::cout << tensor2letters(viterbiPath, state.tokenDict) << std::endl;
}
```

I get somewhat usable token output if I pipe in ~half second chunks (8000 samples) of audio. I don't understand the architecture well enough to:
(1) use smaller audio chunks and still get usable emissions
(2) generally reduce the latency of `network->forward()`
(3) handle and align the emissions from letters that appear at the edge of audio chunks
(4) accumulate emissions reasonably across multiple calls to forward / viterbiPath so e.g. `abc`, `bcd` from two iterations can pass `abcd` to the decoder

The first View layer of the sample architecture takes many consecutive frames of audio features, right? That's the `-1` parameter?

I know this is a large question scope, I'm mostly trying to communicate my understanding so you can fill in the gaps. Thanks in advance!

**Comment by lunixbochs** [comment]
I wrote a simple VAD and it gets better results, but still I'd love a way to run some of the network while the user is talking to reduce latency

**Comment by manu51188** [comment]
Hi @lunixbochs,

If I understand the above implementation correctly, the samples here mentioned in the above code "data.input = samples;" are the MFSC or MFCC values not the raw audio samples. right ?

What is the minimum length of audio that you have tried feeding in this streaming decoder to get reasonable token output ?

Regards,
Mohit

**Comment by lunixbochs** [comment]
Samples are raw samples at 16khz. My call to featurize is what generates MFSC features, which are passed to network->forward. The actual number of samples doesn’t seem to matter as much as long as I chunk them by voice activity.

**Comment by lunixbochs** [comment]
When not chunking by voice activity, I got poor results below 500ms. That is, I kept a ring buffer of 8k or 16k samples and continuously ran the network on it. That was much slower than doing a VAD.

**Comment by manu51188** [comment]
Hi @lunixbochs,

Thanks very much for providing the details. 

I am currently working on streaming decoder with live mic, normally what is the latency that did you observe when the samples of approximately 1s feed into the network ? 

I mean what is the approximate time taken to generate output token once samples are feed into the network.

**Comment by lunixbochs** [comment]
Around 650ms on my dual core 2015 macbook. I reduced the network size by around half and retrained and got ~250ms instead.

**Comment by manu51188** [comment]
Ok Thanks.

250 ms sounds pretty good. Is it possible to share me the network configuration (with reduced network size) file ?

Thanks very much for clearing the doubts.

Regards,
Mohit

**Comment by lunixbochs** [comment]
I just made all the WN Conv layers smaller by an arbitrary amount

**Comment by lunixbochs** [comment]
I'm closing this, the VAD in #327 is more than good enough on CPU.
