### ISSUE TITLE
Quantization

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#267]
This might be more of a flashlight question. I wanted to try quantizing my model, but after digging around in w2l and flashlight code/docs for a bit I didn't see weight datatypes declared on any of the layer classes. Are the conv layers float32? Where is that actually decided?

**Comment by jacobkahn** [comment]
@lunixbochs — types in wav2letter and flashlight come from ArrayFire. An `af::array` doesn't use generics in its public API, so types are [specified dynamically](https://github.com/facebookresearch/flashlight/blob/2ce82ff74447dffad99c496825310013cce8b5b9/tests/nn/SerializationTest.cpp#L85-L93).

By default, Conv layers are indeed fp32 ([weight initialization](https://github.com/facebookresearch/flashlight/blob/master/flashlight/nn/modules/Conv2D.cpp#L140) --> [`uniform`](https://github.com/facebookresearch/flashlight/blob/349e8cfa261a70dd30ab336c44c6985b45555141/flashlight/nn/Init.cpp#L98) --> [ArrayFire's initialization](https://github.com/facebookresearch/flashlight/blob/349e8cfa261a70dd30ab336c44c6985b45555141/flashlight/nn/Init.cpp#L56), which is [here/`af::dtype::f32`](https://github.com/arrayfire/arrayfire/blob/master/include/af/random.h#L184). Most Arrays in flashlight are fp32, although there may be places where values are switched between single and double precision in wav2letter for criterion, etc.

Regarding quantization, we don't yet support quantization in [flashlight](https://github.com/facebookresearch/flashlight), but this is definitely on our roadmap. While certainly not a blocker, ArrayFire is [in the process of implementing fp16](https://github.com/arrayfire/arrayfire/pull/2413). The first step would be to add this to `cudnn` calls ([API](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#tensor-ops-conv-functions-data-filter-formats)). MKL-DNN may have [recently removed this](https://github.com/intel/mkl-dnn/commit/06764c44505c848083ebb05e7bfdc50711fc3fb8) from their API, so I'm not sure what the story is there.

**Comment by lunixbochs** [comment]
Thanks for the info!

My plan is to try to quantize and unquantize the model manually to test it as a compression method and see how it affects accuracy first, then look into supporting it in the MKL backend (as I’m just doing this for CPU inference speed and download size).
