### ISSUE TITLE
Frames per chunck (Input length)

### ISSUE THREAD

**Issue by lucgeo** [facebookresearch/wav2letter#268]
Hi,

This is an architectural question. I'm looking to the conv_glu Librispeech recipe and I don't find  anywhere info about the number of frames per chunk (batch). What is the size of the input processed at a time?

Thank you!

**Comment by jacobkahn** [comment]
@lucgeo — 
https://github.com/facebookresearch/wav2letter/blob/517db5fca7ef4b07106f2b664ebcc056ef581bb1/src/feature/FeatureParams.h#L83-L101

has most of the defaults you're looking for.

**Comment by lucgeo** [comment]
Thank you, but what I'm looking for I think is the "Bin size along audio length axis" which is equal to 100. I found it [here]. Does it represent the number of frames processed at a time?

[here]: https://github.com/facebookresearch/wav2letter/blob/master/src/common/Defines.cpp

**Comment by jacobkahn** [comment]
@lucgeo — the `inputbinsize` flag is only relevant if the `output_spiral` flag is selected as the dataorder format (as is the case in the s2s TDS recipe). This sorts samples in increasing order of size, then alternates bucketing based on output size. For the Librispeech `conv_glu` recipe, we use the default `input` dataorder, which simply sorts inputs by size.
