### ISSUE TITLE
bad argument #1 to 'readShort' (the number of frames must be positive)

### ISSUE THREAD

**Issue by salehgundogdu** [facebookresearch/wav2letter#27]
### Issue 
I keep getting an error when attempting to run create.lua command. I have already commented the data that I am not using 'train-other-500'. 

Is there anything that I can do?

I am running :
`luajit ~/wav2letter/data/librispeech/create.lua ~/LibriSpeech/ ~/librispeech-proc`

Here is the error that I am getting:

> wav2letter/data/librispeech/create.lua:35: bad argument #1 to 'readShort' (the number of frames must be positive)
> stack traceback:
> 	[C]: in function 'readShort'
> 	/wav2letter/data/librispeech/create.lua:35: in function 'copytoflac'
> 	/wav2letter/data/librispeech/create.lua:95: in function 'createidx'
> 	/wav2letter/data/librispeech/create.lua:152: in main chunk
> 	[C]: at 0x00405e90

**Comment by saisrinivas047** [comment]
check if you are out of memory ?

**Comment by VitaliyLi** [comment]
Try to print out file name in copytoflac function in create.lua. You'll see on what file it is failing. That file might be corrupted.

**Comment by bolt163** [comment]
i  meet the same problem,  after delete the total  .tar.gz and re-download it and decompress the file again, the error  disappeared, very  oddly~....~
