### ISSUE TITLE
opaque errors

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#270]
It would be awesome if the errors here included the filename. I don't see another way to figure out which sound file in my dataset is bad.
https://github.com/facebookresearch/wav2letter/blob/ff3f2351e43720d356f16c00bb99e1a13b85ac2a/src/feature/Sound.cpp#L104-L110

(Also cool would be the ability to say "I know my dataset is flawed, please just skip files that have critical errors")

**Comment by xuqiantong** [comment]
Thanks for the suggestion @lunixbochs. We will improve it soon!
