### ISSUE TITLE
Add clang-format as a step to CONTRIBUTING.md

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#273]
https://github.com/facebookresearch/wav2letter/blob/master/CONTRIBUTING.md

As per the comments in https://github.com/facebookresearch/wav2letter/pull/271

**Comment by jacobkahn** [comment]
Added in https://github.com/facebookresearch/wav2letter/commit/07025afbccb110f7c1e0cdc18583f21231cc49b9. Thanks.
