### ISSUE TITLE
arrayfire dimension for input Feature.

### ISSUE THREAD

**Issue by gloryyingling** [facebookresearch/wav2letter#278]
I find this line.
 feat.inputDims = af::dim4(T, FLAGS_channels, 1, batchSz);
(line 76 of /src/data/Featureize.cpp)
And I think it should be
 feat.inputDims = af::dim4(T, 1, FLAGS_channels, batchSz);
What is wrong in my thought?

**Comment by lunixbochs** [comment]
Are you actually training/inferencing against 2-channel audio anyway?

**Comment by gloryyingling** [comment]
No actually I am using mono, and current code works fine, but I just want
the confirmation of yours.

**Comment by vineelpratap** [comment]
Hi,
 It doesn't matter in this case because we are loading a float vector to arrayfire array.  It is just a different way to view the same data. Note that this when you want to use raw audio. 
We modify `feat.inputDims` in L102 if one wants to compute mfcc/mfsc/powspectrum features.
