### ISSUE TITLE
label score output of the ConvNet acoustic model

### ISSUE THREAD

**Issue by zdgithub** [facebookresearch/wav2letter#279]
As the last layer of the ConvNet acoustic model is a linear layer in [1-librispeech_clean/network.arch](https://github.com/facebookresearch/wav2letter/blob/master/tutorials/1-librispeech_clean/network.arch), its label score outputs are neither probabilities in range 0 to 1 nor log-probabilities less than 0.
How are these label score outputs used directly by the CTC criterion?

**Comment by vineelpratap** [comment]
Hi, we use Auto Segmentation Criterion (not CTC) for the recipe. It doesn't require the output at each frame to be normalized since it performs global normalization. 
Ref: https://arxiv.org/abs/1609.03193

**Comment by zdgithub** [comment]
@vineelpratap Hi, but I have set `--criterion=ctc` in my `train.cfg` file before training

**Comment by zdgithub** [comment]
I also want to know whether the output 30 dimensions at each frame of the acoustic model are corresponding to the 30 graphemes one-to-one? That is, could I find which dimension is corresponding to the token alphabet `a` and which is to the token `silence` or `repetition`

**Comment by vineelpratap** [comment]
>  I have set --criterion=ctc in my train.cfg file before training

We do logsoftmax inside the ctc criterion itself. So, it should work fine.

> I also want to know whether the output 30 dimensions at each frame of the acoustic model are corresponding to the 30 graphemes one-to-one

If you are using `--ctc`, use replabel=0 (instead of 2) since CTC doesn't require this operation. Then the outside size will be the size of tokens passes through `--tokens` flag and a blank token which corresponds to the last index.

**Comment by zdgithub** [comment]
Thank you. @vineelpratap 
Do you mean that the output dimensions of the last linear layer of the ConvNet acoustic model are in the same order of the tokens?
For example, the output is a tensor in 29(tokens) x T(frames) x 1 x 1, can I say that the first row corresponds to scores of token `apostrophe` and the last row corresponds to scores of  token `blank`? Because the tokens are in order of `'`, `|`, `a`,`b`,...,`blank`, I want to know the output label score of some specific token.

**Comment by gloryyingling** [comment]
You are right, @zizhan
According to
https://github.com/facebookresearch/wav2letter/blob/master/recipes/librispeech/data/prepare_data.py
output tensor is 30( , | , ' ,  a , b , ... , z , 2 replabels) X T (Frame
length)

**Comment by gloryyingling** [comment]
And also If you are using CTC criterion, one more token(for blank - '#') is
added,
And you set eos flag in train flags, one more token(for eos - '$') is added

**Comment by zdgithub** [comment]
@gloryyingling ok, thank you all.
