### ISSUE TITLE
Time taken to transcribe using pretrained cpu model.

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#28]
how much time does it take to transcribe using the pretrained model. 
when I am trying to transcribe speech using "luajit ~/wav2letter/test.lua ~/librispeech-glu-highdropout-cpu.bin -progress -show -test dev-clean -save -datadir ~/librispeech-proc/ -dictdir ~/librispeech-proc/ -gfsai"  command  it is showling 

[Sentence WER: 000.00%, dataset WER: 003.70%]
 [.................... 2/2703 ..................]  ETA: 6D13h | Step: 3m29s 

will it really take 6 days to complete ?

**Comment by VitaliyLi** [comment]
Closing this as it is answered in another issue.
