### ISSUE TITLE
Test is broken

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#285]
880a6d9d37efcebe2975e08039b2b84e44307cc3 removed `kFileIdIdx` which is still referenced in Test.cpp

https://github.com/facebookresearch/wav2letter/blob/master/Test.cpp#L117

**Comment by vineelpratap** [comment]
Fixed in https://github.com/facebookresearch/wav2letter/commit/9561c66e0ecb9c04c6c1626a28e0c7e78b262eb3. Thanks for reporting.
