### ISSUE TITLE
SpecAugment

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#287]
I implemented the masking parts of [SpecAugment](https://ai.googleblog.com/2019/04/specaugment-new-data-augmentation.html), which broke CAPIO's leading LibriSpeech record by 0.7%.

My masks are far more conservative than the paper's. I currently only mask 7/40 frequency buckets instead of 27/80, and only 30ms of time instead of 700-1000ms. It's probably worth experimenting with these parameters.

I didn't implement the warping, because I wasn't sure how to achieve that easily with ArrayFire, and it seemed like the least important of the three augmentation strategies.

I'm still training my first model with it, but I'm already getting good results and I figured I'd post in case someone else wanted to play with it or integrate into W2L: https://github.com/talonvoice/wav2letter/tree/spec_augment

It would definitely be neat to get some kind of configurable data augmentation frontend for W2L.

**Comment by lunixbochs** [comment]
SpecAugment is in [talonvoice/wav2letter/master](https://github.com/talonvoice/wav2letter/commit/89c1f6e6075974261efbcb3f9aba77a971896591) now and I've actually been getting pretty good results with it.

Do you want a pull request for it? Is there a better place you'd want to put a data augmentation step?

I added [flags](https://github.com/talonvoice/wav2letter/commit/1347a3498ae221566f11eff3f243b1aef6d4bf69) e.g. specaug=true, specaug_F=13, specaug_T=3

**Comment by gloryyingling** [comment]
Hi.
Thank you for your sharing. Really great update.
And could you please explain more about your option.
The original paper indicates following options.
Policy        W        F       mF        T       p      mT
None         0         0        -         0       -       -
LB             80       27      1        100   1.0   1
LD             80      27       2        100   1.0   2
SM            40       15      2        70      0.2   2
SS             40       27      2        70      0.2   2
According to their policy should we use "specaug_F=27, specaug_T=100"?

**Comment by vineelpratap** [comment]
Hi @lunixbochs, thanks for mentioning about this. We are infact already planning on adding SpecAugment to wav2letter soon. Instead of providing as an option through `gflag`, we want to provide it a flashlight module so that is is easier for users to experiment with different options while [specifying network architecture](https://github.com/facebookresearch/wav2letter/blob/master/docs/arch.md).

Here is our initial implementation in case you want to take a look - https://gist.github.com/vineelpratap/6c120a30a51fb388b5adff6738191308.

**Comment by gloryyingling** [comment]
Pretty nice code. We are wait for your update repository.

**Comment by gloryyingling** [comment]
For the second policy "LibriSpeech double (LD) 80 27 2 100 1.0 2", Do you
think or test as follow with your augmentation class?
freqMaskF_=27
numFreqMask_=2
timeMaskT_=100
timeMaskP_=1.0
numTimeMask_=2
The feature vector in paper is same as ours?

**Comment by lunixbochs** [comment]
@gloryyingling it's parameterized in my branch, you can try their original parameters. I reduced the parameters by default to make it easier for my model to converge.

**Comment by gloryyingling** [comment]
Thank you for your consideration. So you mean F=13 and T=? And could you
please share your some experimental parameters and results?
I am trying with your parameters, and the model is getting better. Of
course I will try more for best policy.

**Comment by jacobkahn** [comment]
@gloryyingling @lunixbochs — fyi, we rolled SpecAugment into wav2letter in 04c3d80bf66fe749466cd427afbcc936fbdec5cd.

**Comment by lunixbochs** [comment]
I have mixed feelings about not being able to add/remove data augmentation strategies after I’ve started training

**Comment by jacobkahn** [comment]
@lunixbochs — if you're talking about `04c3d80bf66fe749466cd427afbcc936fbdec5cd`, `SpecAugment` will only be added if the `SAUG` layer is present in the architecture file. It won't be added by default.

**Comment by lunixbochs** [comment]
Yes, but the only way to mix in a dataset with specaugment enabled is to put it in the architecture when the model is created, and there's no way to change that later without writing code to cut the layer out (say, if I want to specialize a model on a user's voice but don't want the added difficulty of specaugment)

**Comment by jacobkahn** [comment]
@lunixbochs — hard to disagree with those points; not being able to change the architecture of a serialized model is a tricky constraint. That said, it's not particularly hard to write a script to:
1. Deserialize the model
2. Create a new `Sequential`
3. Populate said `Sequential` with layers containing parameters of the old model, minus a few data-augmentation layers
4. Serialize/save that new sequential with a slightly different architecture.

One of the reasons it's difficult to provide tooling to do this out of the box is that we still have to check the validity of the "new" network before serializing it, and those checks live inside the flashlight `Container` and `Module` logic, so we have to do both this and serialization jawns at runtime.

**Comment by gloryyingling** [comment]
Could you please update network.arch for specAugment?

**Comment by sanjaykasturia** [comment]
> @lunixbochs — if you're talking about `04c3d80bf66fe749466cd427afbcc936fbdec5cd`, `SpecAugment` will only be added if the `SAUG` layer is present in the architecture file. It won't be added by default.

where can I find documentation on the SAUG layer?

**Comment by vineelpratap** [comment]
@sanjaykasturia - yes, `tWarpW` is not supported yet. So the param `tWarpW ` is unused. We support frequency, time masking.
