### ISSUE TITLE
Issues in Pre-trained model for CPU

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#29]
Hi @VitaliyLi 

I am trying to use pre-trained model for cpu to transcribe the librispeech. I ave a few question regarding this. Hope you people will reply soon. 

1. For this does it require Cuda Installation ?
2. Do we need to run the decoder ? because for running this command "luajit ~/wav2letter/test.lua ~/experiments/hello_librispeech/001_model_dev-clean.bin -progress -show -test dev-clean -save"

we need experiments folder which is created after training but what is the point in training when we want to use pre-trained model.

3. How much time does it take to transcribe using the pretrained model.
when I am trying to transcribe speech using "luajit ~/wav2letter/test.lua ~/librispeech-glu-highdropout-cpu.bin -progress -show -test dev-clean -save -datadir ~/librispeech-proc/ -dictdir ~/librispeech-proc/ -gfsai" command it is showling

[Sentence WER: 000.00%, dataset WER: 003.70%]
[.................... 2/2703 ..................] ETA: 6D13h | Step: 3m29s

will it really take 6 days to complete ?

Thanks & Regards

**Comment by VitaliyLi** [comment]
Hi,

1. If you use a CPU model you don't need CUDA. CUDA is needed only for GPU.
2. You need to run the decoder if you want to use language model. I am not sure I understand your question regarding the experiments folder, can you elaborate?
3. It can't be 6 days, something must be wrong with your system. In my experience transcribing on CPU should take 1s per sequence, not 3 mins.

**Comment by saisrinivas047** [comment]
2. The fourth step in running the decoder is "luajit ~/wav2letter/test.lua ~/experiments/hello_librispeech/001_model_dev-clean.bin -progress -show -test dev-clean -save" which contains experiments folder "~/experiments/hello_librispeech/001_model_dev-clean.bin" which is created during the training Training(but I am using pre-trained model)
"mkdir experiments
luajit ~/wav2letter/train.lua --train -rundir ~/experiments -runname hello_librispeech -arch ~/wav2letter/arch"

3. I am running on google compute engine cpu instance. can you tell whether the problem is with my system or something went wrong during the requirements, installation, and decoding parts of this README. ?
