### ISSUE TITLE
Inference without .tkn .id .wrd files

### ISSUE THREAD

**Issue by TheMathMajor** [facebookresearch/wav2letter#291]
Is there to run a trained model on .flac/.wav files that do not have associated label files (.tkn .id .wrd) files for each audio clip?

**Comment by an918tw** [comment]
You can use `W2lListFilesDataset` to load data. This data loading takes in a list of files, and the format of the list is expected to be (columns should be space-separated) "*[utterance id] [audio file (full path)] [audio length] [word transcripts]*", where transcripts can be empty. Here's a recipe for preparing such data (with transcripts) for librispeech: https://github.com/facebookresearch/wav2letter/blob/master/recipes/librispeech/data/prepare_data.py

**Comment by lunixbochs** [comment]
You don't need .id at all, and .tkn .wrd can be blank.
