### ISSUE TITLE
Training on Multiple CPUs

### ISSUE THREAD

**Issue by TheMathMajor** [facebookresearch/wav2letter#293]
Is there a way to do parallel training across multiple nodes using the CPU backend rather than GPU?

**Comment by gloryyingling** [comment]
They said, it is possible with with Gloo.

**Comment by jacobkahn** [comment]
@TheMathMajor — correct, this is supported with the Gloo distributed backend, which will automatically be built and linked if the CPU backend is selected.

**Comment by abdelhamidfares** [comment]
@jacobkahn there are any tutorial how to train in distributed CPU in multi-machines.

**Comment by jacobkahn** [comment]
@abdelhamidfares — the [distributed training tutorial](https://fl.readthedocs.io/en/latest/distributed.html) applies to CPU training as well as GPU training.
