### ISSUE TITLE
Enable verbose logging

### ISSUE THREAD

**Issue by BoneGoat** [facebookresearch/wav2letter#294]
Is there any way to enable verbose logging?

I'm running a highly custom environment in Docker based on Ubuntu 18.04. It's available [here](https://github.com/BoneGoat/wav2letter/blob/master/Dockerfile-CUDA)

The problem I'm running into is silence. I ran training on 100hrs of audio for 24hrs and got no output whatsoever. This was on a I7 and a 2080Ti. There is no output in the console nor any logs. Meanwhile, the 2080Ti is loaded to 100% and mem is loaded to about 80%. I've set nthread to 4 and the CPU is loaded to about 300%+ so it seems accurate. Something is loaded into GPU memory but I can't see any disk activity.

So, I would like to get some feedback to what's happening. Anything really...

**Comment by tlikhomanenko** [comment]
Hi @BoneGoat,

I met this problem inside the docker container previously. Solution is published here https://github.com/facebookresearch/wav2letter/blob/master/docs/installation.md at the bottom:

`For logging during training/testing/decoding inside a container, use the --logtostderr=1 flag.`

**Comment by tlikhomanenko** [comment]
Feel free to reopen the issue if this doesn't help!

**Comment by BoneGoat** [comment]
@tlikhomanenko Thank you!
