### ISSUE TITLE
Failed:  6 - DataTest (OTHER_FAULT)

### ISSUE THREAD

**Issue by username1618** [facebookresearch/wav2letter#298]
Hi! Can you help me, please?
I have run a wav2letter by docker-container in Google VM (Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1032-gcp x86_64)). 

When I run tests inside a container, I have a `FAILED:6 - DataTest (OTHER_FAULT)`:

>> vainu_apmath@w2l:~$ docker run --runtime=nvidia -it --ipc=host --name w2l wav2letter/wav2letter:cuda-latest
>> root@918c08b257c0:~# cd /root/wav2letter/build && make test
Running tests...
Test project /root/wav2letter/build
      Start  1: W2lCommonTest
...
 6/19 Test  #6: DataTest .........................***Exception: Other  4.29 sec
 ...
95% tests passed, 1 tests failed out of 19
The following tests FAILED:
          6 - DataTest (OTHER_FAULT)
Errors while running CTest
Makefile:104: recipe for target 'test' failed
make: *** [test] Error 8

Also, I can't to Train "Librispeech-Clean Dataset"((

My config file is look a like this:
```
--datadir=/home/w2l/
--tokensdir=/home/w2l/
--rundir=/home/w2l/
--archdir=/root/wav2letter/tutorials/1-librispeech_clean/
--train=data/train-clean-100
--valid=data/dev-clean
--input=flac
--arch=network.arch
--tokens=data/tokens.txt
--criterion=ctc
--lr=0.1
--maxgradnorm=1.0
--replabel=2
--surround=|
--onorm=target
--sqnorm=true
--mfsc=true
--filterbanks=40
--nthread=4
--batchsize=4
--runname=librispeech_clean_trainlogs
--iter=100
```

All files are in owned places:

>> root@918c08b257c0:/home/w2l/data# ls
dev-clean  test-clean  tokens.txt  train-clean-100

>> root@918c08b257c0:~/wav2letter/tutorials/1-librispeech_clean# ls
README.md  acoustic_model.png  decode.cfg  network.arch  prepare_data.py  prepare_lm.py  train.cfg

>> root@918c08b257c0:~/wav2letter# ls
CMakeLists.txt      CONTRIBUTING.md  Dockerfile-CPU   LICENSE    Test.cpp   build  docs     src
CODE_OF_CONDUCT.md  Decode.cpp       Dockerfile-CUDA  README.md  Train.cpp  cmake  recipes  tutorials

But when I'm trying to Train dataset, I receive this:

>>  root@918c08b257c0:~/wav2letter/build# ~/wav2letter/build/Train train --flagsfile ~/wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not read file '~/wav2letter/tutorials/1-librispeech_clean/network.arch'
*** Aborted at 1558127820 (unix time) try "date -d @1558127820" if you are using GNU date ***
PC: @     0x7f902a97b428 gsignal
*** SIGABRT (@0xc08) received by PID 3080 (TID 0x7f908a61b780) from PID 3080; stack trace: ***
    @     0x7f906e719390 (unknown)
    @     0x7f902a97b428 gsignal
    @     0x7f902a97d02a abort
    @     0x7f902b2be84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f902b2bc6b6 (unknown)
    @     0x7f902b2bc701 std::terminate()
    @     0x7f902b2bc919 __cxa_throw
    @           0x5339ff w2l::getFileContent()
    @           0x56d0c1 w2l::createW2lSeqModule()
    @           0x418901 main
    @     0x7f902a966830 __libc_start_main
    @           0x465619 _start
    @                0x0 (unknown)
Aborted (core dumped)

Next I've edit `--archdir` from `"~/wav2letter/tutorials/1-librispeech_clean/"` to `"/root/wav2letter/..."`

When I've run:
>> root@918c08b257c0:~/wav2letter/tutorials/1-librispeech_clean# ~/wav2letter/build/Train train --flagsfile ~/wav2lett

NOTHING is happend for a long time!

I'm a beginer in Linux and I don't know how to solve this problem. Can someone help me, pleace?

**Comment by xuqiantong** [comment]
Usually `~/.../` is equivalent to `$HOME/...` but not `/root/...`. Can you double check if the path is correct? Also according to the log, it seems like you are trying to read from `/wav2letter/tutorials/1-librispeech_clean/network.arch`, which is an invalid path.

**Comment by tlikhomanenko** [comment]
@username1618 

To have logging available inside a docker container add flag `--logtostderr=1` while running training/test/decode commands, (see the issue https://github.com/facebookresearch/wav2letter/issues/294).

In a docker container you will be under root user, so seems that path ~/ or /root will be the same. To check this run in your wav2letter directory
```
echo $HOME
cd ~ && pwd
```
the first will show you home directory path, and the second will show the exact path of your home directory. Also you can run `pwd` inside wav2letter directory to see the full path.

Also could you run from wav2letter/build folder the command
```
./src/tests/DataTest
```
and post the log of it?

I would not recommend to use ~/ in paths, so put the full paths (sometimes I had troubles to use paths with ~ prefix).

**Comment by username1618** [comment]
Thanks!
I missed that I can check `--rundir` directory for logs. After adding the `--logtostderr=1` flag, I made sure that the training was started, and checking the `--rundir` directory showed that the intermediate model was saved in the last launch
