### ISSUE TITLE
bad argument #1 to 'lines' (/data/local/packages/ai-group.speechdata/latest/speech/letters.lst: No such file or directory)

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#30]
HI 
I am using pretrained model for cpu to transcribe a simple audio file but I am getting the following error. can someone help me to rectify it 

command : "luajit test.lua librispeech-glu-highdropout-cpu.bin -progress -show -test audio_6134_24_2812.8_2825.73.wav -save"

luajit: /torch/install/share/lua/5.1/wav2letter/runtime/data.lua:146: bad argument #1 to 'lines' (/data/local/packages/ai-group.speechdata/latest/speech/letters.lst: No such file or directory)
stack traceback:
	[C]: in function 'lines'
	/torch/install/share/lua/5.1/wav2letter/runtime/data.lua:146: in function 'newdict'
	test.lua:72: in main chunk
	[C]: at 0x00405d50

**Comment by Kranberry** [comment]
Hey saisrinivas047, can you tell me what you did to correct this error, since I see that you have closed this? I'm getting it now too
