### ISSUE TITLE
Benchmark parallel streaming decode

### ISSUE THREAD

**Issue by dambaquyen96** [facebookresearch/wav2letter#302]
I can see that the decoding process with LM on the emissons set can be done parallel on CPU. But I want to feed parallel the audio data through neural network to get the emissions result too.
Have anyone deployed wav2letter to ASR online streaming service? That it receives multiple audio input stream and outputs the result in realtime on 1 process only (Because the model took all GPU's memory, so I cannot just run the service multi time). 
And what is its benchmark? Like how many concurrent streams that one model can handle?
Btw, I'm using 1 GPU 2080TI & 16 core CPU.

**Comment by lunixbochs** [comment]
Which model are you using? The default librispeech recipe? I would be able to benchmark something like this for you in exchange for compensation.

**Comment by dambaquyen96** [comment]
I'm using the conv_glu model in librispeech recipe, but with Vietnamese dataset. Which model are you using? I'm very appreciated if we could have a discussion about this problem.

**Comment by lunixbochs** [comment]
I’ve been running experiments with a variety of English models. I have an English conv_glu model based on the librispeech recipe that would have the same performance characteristics as another language on the same network architecture.

**Comment by xtluo-ai** [comment]
> @lunixbochs Can you give me your benchmark with that model? And what is your benchmark architecture? I'm planning to implement the ASR online streaming service, and I'm glad to share my experiments about this if you need it.

@dambaquyen96 Hello, any progress? I'm planning on deploying my model for online streaming service too. Thanks.

**Comment by tlikhomanenko** [comment]
close due to inactivity.
