### ISSUE TITLE
CharLM decoding

### ISSUE THREAD

**Issue by ahmadab** [facebookresearch/wav2letter#303]
With the CharLM changes, is decoding now possible without a lexicon?
I got a crash when I tried this!

**Comment by xuqiantong** [comment]
Yes, we provide a lexicon-free decoder write now which can work with a token level LM. Can you share some information about your set up and error message?

**Comment by ahmadab** [comment]
Decoder -am <acoustic-model> -lm <arpa-bin-file> -beamsize 1000 -beamthreshold 25 -lmweight 1.1 -silweight -0.29 -smearing max -datadir . -test <tst-dir> -nthread_decoder 20 -show -maxload -1 -sclite decode/

The above crashes. Below is the stack trace. Running on Ubuntu 18.04.2 LTS

*** Aborted at 1558459034 (unix time) try "date -d @1558459034" if you are using GNU date ***
PC: @     0x559a241c9b10 (unknown)
*** SIGSEGV (@0x0) received by PID 17241 (TID 0x7f9f09931700) from PID 0; stack trace: ***
    @     0x7fa01c1ca890 (unknown)
    @     0x559a241c9b10 (unknown)
    @     0x559a241beeb9 w2l::LexiconDecoder::decodeBegin()
    @     0x559a240c64ae _ZZ4mainENKUliiiE2_clEiii
    @     0x559a240c8fa2 _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFZ4mainEUliiiE2_iiiEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x559a240d11e9 std::__future_base::_State_baseV2::_M_do_set()
    @     0x7fa01c1c7827 __pthread_once_slow
    @     0x559a240c5343 _ZNSt17_Function_handlerIFvvEZN2fl10ThreadPool7enqueueIRZ4mainEUliiiE2_JRiS6_S6_EEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOS9_DpOSA_EUlvE_E9_M_invokeERKSt9_Any_data
    @     0x559a240d13f0 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN2fl10ThreadPoolC4EmRKSt8functionIFvmEEEUlvE_EEEEE6_M_runEv
    @     0x7f9fff3db66f (unknown)
    @     0x7fa01c1bf6db start_thread
    @     0x7f9ffe86988f clone
Segmentation fault (core dumped)

**Comment by xuqiantong** [comment]
Try `-decodertype tkn`. Will update docs soon.

**Comment by ahmadab** [comment]
Works. Thank you!
