### ISSUE TITLE
Training error: Asynchronous allReduce not yet supported for Gloo backend

### ISSUE THREAD

**Issue by SYnchronYSe** [facebookresearch/wav2letter#309]
Hi
 I'm running the LibriSpeech tutorial. I got the following error while training the model:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Asynchronous allReduce not yet supported for Gloo backend
*** Aborted at 1558947808 (unix time) try "date -d @1558947808" if you are using GNU date ***
PC: @     0x7f4961524428 gsignal
*** SIGABRT (@0xa00) received by PID 2560 (TID 0x7f496c50ec00) from PID 2560; stack trace: ***
    @     0x7f4962604390 (unknown)
    @     0x7f4961524428 gsignal
    @     0x7f496152602a abort
    @     0x7f4961e6784d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f4961e656b6 (unknown)
    @     0x7f4961e65701 std::terminate()
    @     0x7f4961e65919 __cxa_throw
    @           0x647782 fl::syncDistributed()
    @           0x479f1a _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.11625
    @           0x419fac main
    @     0x7f496150f830 __libc_start_main
    @           0x475299 _start
Aborted (core dumped)
```

I was getting the same what() message on running the make test 'AllReduce' after compiling Flashlight on CPU backend. Refer to [this issue.](https://github.com/facebookresearch/flashlight/issues/47)
Any help please?

**Comment by jacobkahn** [comment]
@SYnchronYSe — there are a few ways you can proceed, but you'll need to change the arguments to [`ContiguousReducer`](https://fl.readthedocs.io/en/latest/dist.html#_CPPv4N2fl17CoalescingReducerE), which is [created here in Train.cpp](https://github.com/facebookresearch/wav2letter/blob/master/Train.cpp#L128-L129) to not use those features. Since both coalescing and asynchronous reductions aren't yet supported with Gloo, you'll need to flip those booleans to false. You can also use the `InlineReducer` with your training flow ([docs](https://fl.readthedocs.io/en/latest/dist.html#_CPPv4N2fl13InlineReducerE)).

**Comment by SYnchronYSe** [comment]
Thanks for your response.
I pulled the latest commit, set those two booleans to 'false' as suggested and compiled it. But now I'm getting a segmentation fault when trying to run training.
```
*** Aborted at 1559034228 (unix time) try "date -d @1559034228" if you are using GNU date ***
PC: @     0x7f9f43c41460 (unknown)
*** SIGSEGV (@0x726f) received by PID 4341 (TID 0x7f9f4eaf0c00) from PID 29295; stack trace: ***
    @     0x7f9f44be8390 (unknown)
    @     0x7f9f43c41460 (unknown)
    @           0x560b33 w2l::tknIdx2Ltr()
    @           0x56368d w2l::tknPrediction2Ltr()
    @           0x476f77 _ZZ4mainENKUlRKN2af5arrayES2_RN3w2l13DatasetMetersEE1_clES2_S2_S5_
    @           0x47a078 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.11627
    @           0x419ff3 main
    @     0x7f9f43af3830 __libc_start_main
    @           0x475349 _start
Segmentation fault (core dumped)

```

**Comment by SYnchronYSe** [comment]
My pc configuration is:

RAM 16GB
Processor Intel® Core™ i5-8500 CPU @ 3.00GHz × 6 
Graphics Intel® HD Graphics (Coffeelake 3x8 GT2)
OS Ubuntu 16.04LTS 64-bit
