### ISSUE TITLE
Endpoint detetion in Decoding

### ISSUE THREAD

**Issue by dambaquyen96** [facebookresearch/wav2letter#312]
When decode the long audio file, which containing many sentence, I want apply the endpoint detection to detect the end of each sentence. Previously, I've worked with Kaldi Toolkit and it's endpoint detection is very effective (https://github.com/kaldi-asr/kaldi/blob/master/src/online2/online-endpoint.cc).
So is there anyone working on this using wav2letter? I really want to discuss about this idea.

**Comment by abhinavkulkarni** [comment]
@dambaquyen96: The model can only recognize subword pieces from `tokens.txt`, so if period (`.`) is not part of token set, it cannot be recognized by the model. I assume they remove all the punctuation from the training data.

You'll have to incorporate punctuation recognition as part of decoding or restoring.

**Comment by tlikhomanenko** [comment]
Or you can add period into tokens set and have proper training data - this is the other way. As far as I know mostly people do post-processing with another model which returns you where you should put punctuation.
