### ISSUE TITLE
Trouble with libsndfile while following librispeech recipe

### ISSUE THREAD

**Issue by poneill** [facebookresearch/wav2letter#314]
Hi, I'm trying to follow the librispeech recipe while running w2l (in docker with the CUDA backend), and am getting `sndfile: unknown format or could not open file` errors, as in #241.  Following the advice in that thread, I tried rolling libsndfile back to 1.0.28 by editing the gitsha in the Dockerfile and recompiling the image.  This, in turn, fails with the message: `CMake Error: The source directory "/root/wav2letter" does not appear to contain CMakeLists.txt`, similar to #200.  That thread recommends rebuilding with `--no-cache`, which worked for OP  but not for me :)

Am I doing anything obviously wrong here? Would be grateful for any advice about how to get the librispeech recipe up and running.  Thanks in advance!

**Comment by tlikhomanenko** [comment]
Hi @poneill,

- Are you using the Dockerfile-CUDA from the repository? 
- In case of `sndfile` error did all test inside the container pass?

- Could you try to run these commands?
```
sudo docker image rm --force wav2letter/wav2letter:cuda-latest
sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-latest
sudo docker exec -it w2l bash
```
And then inside the container
```
cd /root/wav2letter/build && make test
```
And then, please, post if all test pass or not.

**Comment by poneill** [comment]
hi @tlikhomanenko, thanks for your help.  

Yes, I used the command:
```
docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-latest
```
from the repo's installation instructions.

After that I ran

```
cd /root/wav2letter/build && make test
```
and all of the tests passed.  

After removing and reinstalling the docker image, I now get the following errors:

```root@0299cb246285:/# cd /root/wav2letter/build && make test
Running tests...
Test project /root/wav2letter/build
      Start  1: W2lCommonTest
 1/19 Test  #1: W2lCommonTest ....................***Exception: SegFault  1.43 sec
      Start  2: CriterionTest
 2/19 Test  #2: CriterionTest ....................***Exception: SegFault  1.04 sec
      Start  3: Seq2SeqTest
 3/19 Test  #3: Seq2SeqTest ......................***Exception: SegFault  0.65 sec
      Start  4: AttentionTest
 4/19 Test  #4: AttentionTest ....................***Exception: SegFault  0.94 sec
      Start  5: WindowTest
 5/19 Test  #5: WindowTest .......................***Exception: SegFault  0.64 sec
      Start  6: DataTest
 6/19 Test  #6: DataTest .........................***Failed    0.66 sec
      Start  7: DecoderTest
 7/19 Test  #7: DecoderTest ......................   Passed    0.76 sec
      Start  8: CeplifterTest
 8/19 Test  #8: CeplifterTest ....................   Passed    0.02 sec
      Start  9: DctTest
 9/19 Test  #9: DctTest ..........................   Passed    0.06 sec
      Start 10: DerivativesTest
10/19 Test #10: DerivativesTest ..................   Passed    0.03 sec
      Start 11: DitherTest
11/19 Test #11: DitherTest .......................   Passed    8.03 sec
      Start 12: MfccTest
12/19 Test #12: MfccTest .........................   Passed    0.19 sec
      Start 13: PreEmphasisTest
13/19 Test #13: PreEmphasisTest ..................   Passed    0.03 sec
      Start 14: SoundTest
14/19 Test #14: SoundTest ........................   Passed    0.05 sec
      Start 15: SpeechUtilsTest
15/19 Test #15: SpeechUtilsTest ..................***Failed    0.76 sec
      Start 16: TriFilterbankTest
16/19 Test #16: TriFilterbankTest ................   Passed    0.03 sec
      Start 17: WindowingTest
17/19 Test #17: WindowingTest ....................   Passed    0.02 sec
      Start 18: W2lModuleTest
18/19 Test #18: W2lModuleTest ....................***Exception: SegFault  1.72 sec
      Start 19: RuntimeTest
19/19 Test #19: RuntimeTest ......................***Failed    8.53 sec

53% tests passed, 9 tests failed out of 19

Total Test time (real) =  25.59 sec

The following tests FAILED:
	  1 - W2lCommonTest (SEGFAULT)
	  2 - CriterionTest (SEGFAULT)
	  3 - Seq2SeqTest (SEGFAULT)
	  4 - AttentionTest (SEGFAULT)
	  5 - WindowTest (SEGFAULT)
	  6 - DataTest (Failed)
	 15 - SpeechUtilsTest (Failed)
	 18 - W2lModuleTest (SEGFAULT)
	 19 - RuntimeTest (Failed)
Errors while running CTest
Makefile:104: recipe for target 'test' failed
make: *** [test] Error 8
```

**Comment by tlikhomanenko** [comment]
Could you send the log of running for example this test separately?
```
cd /root/wav2letter/build && ./src/tests/W2lCommonTest
```

So, as I understood you have a problem with building the docker image on you machine using official Dockerfile from repository (with sndfile: unknown format or could not open file). 
- What docker version do you have (`sudo docker --version`), which operating system?
- Could you build the image like `sudo docker build -f ./Dockerfile-GPU -t test . > docker.log` and attach the `docker.log` which will be generated during building (want to see how the image build looks like)?

As the proxy solution you can use `wav2letter/wav2letter:cuda-latest` image and rebuild wav2letter if you make changes to the code (or install any other dependencies on the top of this image). For this purpose you can use a key `-v path/in/your/system:path/in/docker/where/mount` to mount folders from your system to the docker container (for example your own version of wav2letter which will be accessible inside the container).

**Comment by poneill** [comment]
Yes, to clarify: I originally had a working build in the sense that the test suite was passing.  Upon removal and reinstallation of the docker image, tests are no longer passing.  I've tried several permutations of removal and reinstallation, but still no luck since.

Output for

`cd /root/wav2letter/build && ./src/tests/W2lCommonTest`:

```
[==========] Running 18 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 18 tests from W2lCommonTest
[ RUN      ] W2lCommonTest.StringTrim
[       OK ] W2lCommonTest.StringTrim (0 ms)
[ RUN      ] W2lCommonTest.ReplaceAll
[       OK ] W2lCommonTest.ReplaceAll (0 ms)
[ RUN      ] W2lCommonTest.StringSplit
[       OK ] W2lCommonTest.StringSplit (0 ms)
[ RUN      ] W2lCommonTest.StringJoin
[       OK ] W2lCommonTest.StringJoin (0 ms)
[ RUN      ] W2lCommonTest.StringFormat
[       OK ] W2lCommonTest.StringFormat (0 ms)
[ RUN      ] W2lCommonTest.PathsConcat
[       OK ] W2lCommonTest.PathsConcat (0 ms)
[ RUN      ] W2lCommonTest.RetryWithBackoff
[       OK ] W2lCommonTest.RetryWithBackoff (752 ms)
[ RUN      ] W2lCommonTest.Replabel
[       OK ] W2lCommonTest.Replabel (0 ms)
[ RUN      ] W2lCommonTest.Dictionary
[       OK ] W2lCommonTest.Dictionary (0 ms)
[ RUN      ] W2lCommonTest.InvReplabel
[       OK ] W2lCommonTest.InvReplabel (0 ms)
[ RUN      ] W2lCommonTest.Uniq
[       OK ] W2lCommonTest.Uniq (0 ms)
[ RUN      ] W2lCommonTest.Normalize
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:160
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION


In function af::array af::stdev(const af::array&, dim_t)
In file src/api/cpp/stdev.cpp:55" thrown in the test body.
[  FAILED  ] W2lCommonTest.Normalize (472 ms)
[ RUN      ] W2lCommonTest.Transpose
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:160
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION


In function af::array af::transpose(const af::array&, bool)
In file src/api/cpp/transpose.cpp:18" thrown in the test body.
[  FAILED  ] W2lCommonTest.Transpose (1 ms)
[ RUN      ] W2lCommonTest.localNormalize
Segmentation fault (core dumped)
```

Docker version:
```
Docker version 18.09.6, build 481bc77
```

OS: Ubuntu 18.04


`docker build -f ./Dockerfile-GPU -t test . > docker.log` builds successfully, logs here:
https://gist.github.com/poneill/10e91ec08ab376052fb86b43d98d3869


Thanks again,
Pat.

**Comment by poneill** [comment]
Ah, so it appears that the test breakage was caused by pulling `cuda:latest`, which was updated recently.  If I pull `cuda-0b16293`, tests are passing again.

**Comment by tlikhomanenko** [comment]
The error in your test `NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION` seems to be related to driver issue (check https://github.com/facebookresearch/wav2letter/issues/229, and https://github.com/facebookresearch/wav2letter/issues/229). Did you update the driver while updating the docker?

I built my images with docker version `Docker version 18.06.1-ce, build e68fc7a`, you can try to install it. Could you test with this version, so there are maybe some problems with docker version to use `--runtime=nvidia` correctly?

Could you also send the log of:
```
cd /root/wav2letter/build && ./src/tests/DataTest
```
to check if there is a problem with `libsndfile` still.

**Comment by poneill** [comment]
Reverting to `cuda-0b16293` also fixes the libsndfile issue, apparently.  Thanks again for all the help!
