### ISSUE TITLE
documentation for emission.bin format

### ISSUE THREAD

**Issue by poneill** [facebookresearch/wav2letter#315]
Is there any documentation of how emission matrices are stored?  I'm interested in trying out the wav2letter decoder in the context of a broader pipeline, and would like to write a utility to convert my emission matrices to a form that wav2letter can handle.  Is there any documentation of how the W2lSerializer works?  Thanks in advance!

(Happy of course to PR it too, if this would be more generally useful.)

**Comment by xuqiantong** [comment]
You can find it from here. https://github.com/facebookresearch/wav2letter/blob/master/src/common/Utils.h#L95

**Comment by xuqiantong** [comment]
No following questions. closing.

**Comment by poneill** [comment]
Thanks!

**Comment by poneill** [comment]
Sorry, still a bit confused about how reading the emissions file is supposed to work.  I've been trying to play around with the example data given in the decoder test.  If I run the following command from the top-level directory:

`build/Decoder -emission_dir src/decoder/test/ -test emission --logtostderr    `

I get the following output:

```
I0604 20:51:26.256098   689 Decode.cpp:98] [Serialization] Loading file: src/decoder/test/emission.bin
E0604 20:51:26.256260   689 Serial.h:74] Error while loading: basic_string::_M_replace_aux
E0604 20:51:27.256419   689 Serial.h:74] Error while loading: basic_string::_M_replace_aux
```

Am I doing something wrong, or is this unexpected behavior?

Thanks again.

**Comment by xuqiantong** [comment]
Seems like a version mismatch between the Test.cpp you used to generate emission set and Decode.cpp. Can you make sure you are running them both on the same commit?

**Comment by poneill** [comment]
The `emission.bin` file is just the example given in `src/decoder/test`, using the docker image `cuda-0b16293`.   Should I expect to be able to load it, or am I working against intended usage?

(This is successfully read in the `DecoderTest` (i.e. that test passes), but inspecting the source, AFAICT, it looks like `emission.bin` is not loaded the same way as in `Decode`?  Specifically, `DecoderTest` doesn't use the `W2lSerializer` design used in `Decode`.)

**Comment by xuqiantong** [comment]
Oh, that is just a single emission file, not the emission set that is serializable in Decode.cpp. You need to generate the emission set with Test.cpp. Please refer to https://github.com/facebookresearch/wav2letter/blob/master/docs/decoder.md

**Comment by poneill** [comment]
Thanks for this.

I generated an emission set with `Test.cpp`.  In particular, I created a file `mytest.cfg`:

```
--am=w2l_data/librispeech_clean_trainlogs/001_model_last.bin
--emission_dir=w2l_data/mytestset_emissions
--test=mytestset
--maxload=1
--show
--logtostderr
```

and ran:
`/root/wav2letter/build/Test --flagsfile w2l_data/mytest.cfg > w2l_data/mytest_stdout.txt`
which generated a 21MB file `mytestset.bin`.  When I check the log, I see that the model is generating sensible predictions for each snippet in my test set.  

However, when I attempted to decode these emissions with the following config:

```
--emission_dir=w2l_data/mytestset_emissions
--test=mytestset
--lexicon=w2l_data/lm/lexicon.txt
--lm=w2l_data/lm/3-gram.arpa
--lmweight=2.5
--wordscore=1
--beamsize=1000
--beamscore=25
--silweight=-0.5
--nthread=1
--nthread_decoder=8
--smearing=max
--show
--sclite=w2l_data/decode_output
--logtostderr
```
and run:
`/root/wav2letter/build/Decoder --flagfile w2l_data/decode.cfg > w2l_data/decoder_stdout.txt `

It looks like the logs only show me predictions for the _first_ snippet in the dataset, but not any of the others.  

If I decode using the acoustic model rather than the emissions as in the following config:

```
File Edit Options Buffers Tools Conf Help                                                                                                                                                                                                                                                                                                                                                   
# /root/wav2letter/build/Decoder --flagfile w2l_data/decode_am.cfg > w2l_data/decod_am_stdout.txt                                                                                                                                                                                                                                                                                           
# decode using acoustic model                                                                                                                                                                                                                                                                                                                                                               
--am=w2l_data/librispeech_clean_trainlogs/001_model_last.bin
# input comes from here.                                                                                                                                                                                                                                                                                                                                                                    
--test=mytestset
# output goes here                                                                                                                                                                                                                                                                                                                                                                          
--sclite=w2l_data/decode_am_output
--lexicon=w2l_data/lm/lexicon.txt
--lm=w2l_data/lm/3-gram.arpa
--lmweight=2.5
--wordscore=1
--beamsize=1000
--beamscore=25
--silweight=-0.5
--nthread=1
--nthread_decoder=8
--smearing=max
--show
--logtostderr
--v=100
```

then I receive predictions for the entire test set as expected.

Is there anything else I should be aware of in order to generate batch predictions from emissions for an entire test set?  Thanks again!

**Comment by xuqiantong** [comment]
`maxload=1` you passed in to the test, will be serialized into the emission set as well. So, decoder, will only decode 1 sample. 

It means:
1) There is a bug in Test.cpp which doesn't respect `maxload` flag. 
2) To solve your only-1-sample-decoded issue, you may simply set `maxload=-1` before decoding.

**Comment by poneill** [comment]
Ah!  Thank you again!
