### ISSUE TITLE
Seq2Seq decoding

### ISSUE THREAD

**Issue by ahmadab** [facebookresearch/wav2letter#317]
Any update on the seq2seq model decoding?

**Comment by tlikhomanenko** [comment]
Hi @ahmadab,

Decoder for seq2seq models is added in the commit 0b8fbab8332f7e15392e2ea15fb66a8ba97198b1. The docs update how to use it is coming soon. 

But you can use it already. Additional flags are 
- `smoothingtemperature`, default 1.0, smoothening the probability distribution in seq2seq decoder
- `attentionthreshold`, default `std::numeric_limits<int>::infinity()`, hard attention limit
- `hardselection`, default 1.0, end-of-sentence threshold
- `softselection`, default `std::numeric_limits<double>::infinity()`, threshold to keep new candidate from being proposed.

Also you need to set flag `criterion=seq2seq`.
