### ISSUE TITLE
FFTW on RHEL

### ISSUE THREAD

**Issue by akshatdewan** [facebookresearch/wav2letter#32]
Hi all, 
I am working RHEL release 7.3 (Maipo). I tried installing FFTW3 (fftw-3.3.7) manually (from source) but the default install builds only libfftw3 libraries and libfftw3f and libfft3l are missing. FindFFTW file in wav2letter repos gives me the impression that the missing (fftw3) libraries are mandatory. Am I mistaken? Or is there a way to build the missing libraries? I tried the --enable-sme2 option for making fftw3 but that did not help either. 
Thanks

**Comment by bolt163** [comment]
try to install it by apt-get or yum install?  first i installed it by the source code ,it fails, there were kinds of errors eg can't finding the fftw or undefinde symbol fftw_xxx;
while using yum install,  the problem all  go die

**Comment by akshatdewan** [comment]
yum install did not work for me. I gave up and now am running a ubuntu docker image on RHEL.

**Comment by sungjae-cho** [comment]
@akshatdewan 
Hi, there. You always don't forget to update `apt-get` if you meet the error that says a missing library. 
```
sudo apt-get update
```

**Comment by andresy** [comment]
Closing as we do not support the lua version of wav2letter anymore - on RHEL I guess the right package for fftw is fftw-devel.
