### ISSUE TITLE
not sure what the training process is utilizing- CPU or GPU

### ISSUE THREAD

**Issue by SYnchronYSe** [facebookresearch/wav2letter#320]
Hi, I have compiled wav2letter with CUDA backend and I'm running the training on Librispeech.

My specs are:
RAM 16GB
Processor Intel® Core™ i5-8500 CPU @ 3.00GHz × 6
Graphics Nvidia GeForce GT710 2GB
Nvidia driver v418.67, Cuda v10.1
OS Ubuntu 16.04LTS 64-bit

All of my wav2letter tests passed, but for Flashlight, the AllReduce test had failed with the following message:

```
satishyadav@satishyadav-Dell:~/speech/flashlight/build/tests$ ./AllReduceTest 
Initialized NCCL 2.3.7 successfully!
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from Distributed
[ RUN      ] Distributed.AllReduce
[       OK ] Distributed.AllReduce (299 ms)
[ RUN      ] Distributed.InlineReducer
[       OK ] Distributed.InlineReducer (97 ms)
[ RUN      ] Distributed.AllReduceAsync
[       OK ] Distributed.AllReduceAsync (0 ms)
[ RUN      ] Distributed.AllReduceSetAsync
[       OK ] Distributed.AllReduceSetAsync (3 ms)
[ RUN      ] Distributed.CoalescingReducer
unknown file: Failure
C++ exception with description "ArrayFire Exception (Device out of memory:101):
In function void* cuda::MemoryManager::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:149
CUDA Error (2): out of memory


In function void af::array::eval() const
In file src/api/cpp/array.cpp:875" thrown in the test body.
[  FAILED  ] Distributed.CoalescingReducer (203 ms)
```
You can see my arrayfire errors [here](https://drive.google.com/file/d/1eV0KHN7BtTx-MyWBo_cupmzoydVpKChc/view?usp=sharing). It's an extension less file. Please open it with text reader.
4 of my arrayfire tests were failing, and I couldn't figure out the reason. So I decided to move on with these errors and see if they create a problem in future.

So I set the contiguous bool of the Coalescing Reducer to false as suggested in #309  

I was getting a segmentation fault for the complete data, so I separated 3000 datasets, and reduced the batchsize to 1.

For 3000 datasets, the training completed successfully for 5 epochs, it took 12 minutes for each epoch, when nthread=1.

Now I changed to nthread=4. This time the 1st epoch gave seg fault after 11 hours.

For the third time, I set nthread=1, batchsize=4. At the time of writing this, it's been 65 minutes and the epoch 1 is still running.

But for each process, my CPU and GPU utilization stays the same as you can see here:
![image](https://user-images.githubusercontent.com/30228260/58853464-05beb700-86b8-11e9-8e4b-61a7686b348f.png)
![image](https://user-images.githubusercontent.com/30228260/58853477-0f481f00-86b8-11e9-996c-af18c496139f.png)

1. What were the consequences of disabling contiguous reducer?
2. Even when the seg fault occurs, my GPU is not overloaded. It stays at around 1100/1993MB. Does that imply my training is running on CPU?
3. I have a single GPU and I'm not running on mpi. How would modifying nthread value affect the process then?
4. Can I somehow utilize all the CPU cores on CUDA backend in order to prevent this seg fault?
5. My swap space is not utilized at all. Is this normal?

**Comment by jacobkahn** [comment]
@SYnchronYSe — you can effectively ignore that test failure. It tests the `CoalescingReducer` with a particular cache/memory overload which fits on many, but not all GPUs (yours only has 2 GB of cache memory, so it's not fitting). The cache overload is quite fast/you might not be able to detect it unless you're watching memory usage with very high granularity. I'll update the test at some point to work on older GPU models with less memory.

That said, if you only have 1 GPU, you won't use any reducer at all (since you're not going to need distributed training). You can start your training runs without `--enable_distributed`, in which case no reducer will be used, since you don't need to synchronize gradients across GPUs. Your training will still run on GPU/will run normally.

**Comment by SYnchronYSe** [comment]
@jacobkahn my CPU usage is going 100%, whereas the GPU usage stays around 50%, as you can see in the screenshots. Would it be possible for you to figure out why this is happening? Since I have built it on CUDA backend, the training was supposed to utilise the GPU.
