### ISSUE TITLE
token language model

### ISSUE THREAD

**Issue by ahmadab** [facebookresearch/wav2letter#323]
Seq2seq only works with token decoders as mentioned in documentation and apparent in the code
How can the token language model be generated. Does KenLM support token LMs?

**Comment by xuqiantong** [comment]
Yes. 
Suppose you use letters as tokens when training AM, then token LM means the units in LM are also letters, rather than words. 
To prepare training data for it, map sentences like `i like cats` to `i | l i k e | c a t s`, where `|` should also be the delimiter you specified for AM training.

**Comment by ahmadab** [comment]
Perhaps I was not clear
A tokens file is generated for training. It contains 1000s of tokens for Librispeech for example
When I try to use an arpa kenlm LM while Decoding using a seq2seq AM in tkn mode, I get a 100% WER
I assumed that this is because the apra file describes a char level LM not a token one

**Comment by xuqiantong** [comment]
In principle, the tokens in token-LM should match with the tokens you used in AM training. You can simply check if the tokens in your token file match with the uni-grams in the arpa file.

**Comment by ahmadab** [comment]
Do you mean that the unigrams in the arpa file should *just* be the list of tokens?
Because currently the unigrams are the list of supported words not tokens!

**Comment by xuqiantong** [comment]
Yes, it should be the tokens.

**Comment by ahmadab** [comment]
I guess this means that the token LM Decoder works differently? Would it be possible to share an token LM arpa file for LibriSpeech for example?

**Comment by xuqiantong** [comment]
We are about to release models soon.

**Comment by TechnikEmpire** [comment]
@xuqiantong Is "soon" soon?

**Comment by jacobkahn** [comment]
@TechnikEmpire — we'll be open sourcing models for a few recent papers _this week_. I'll comment here once they're available.

**Comment by TechnikEmpire** [comment]
@jacobkahn that's great. Thanks for the update and for supporting those of us too lazy to train ourselves. :D
