### ISSUE TITLE
Is there any config files for the convolutional acoustic model described in the paper?

### ISSUE THREAD

**Issue by k1kyo** [facebookresearch/wav2letter#324]
I wanna train an convolutional acoustic model based on the paper[https://arxiv.org/abs/1812.06864](url). Is it the model described in Section 3.1 in paper[https://arxiv.org/abs/1806.07098](url)?

**Comment by lunixbochs** [comment]
wav2letter's acoustic models are already convolutional. The "fully convolutional" part of this paper is the fact the language model is also a convolutional neural network: https://arxiv.org/abs/1812.06864

As far as I can tell Facebook hasn't released any of their language model code yet.

**Comment by k1kyo** [comment]
> wav2letter's acoustic models are already convolutional. I believe the "fully convolutional" part of this paper is a reference to the fact the language model is also a convolutional neural network: https://arxiv.org/abs/1812.06864
> 
> As far as I can tell Facebook hasn't released any of their language model code yet.

I found that gcnn-14B is defined in [here](https://github.com/facebookresearch/wav2letter/issues/316#issuecomment-498365996)

**Comment by k1kyo** [comment]
I guess [this](https://github.com/facebookresearch/wav2letter/blob/7b82999a981dbfbb2a35a2d848987550df0556c6/recipes/librispeech/configs/conv_glu/network.arch) is the config of ConvAM for librispeech
