### ISSUE TITLE
should I define runPath when using continue mode?

### ISSUE THREAD

**Issue by k1kyo** [facebookresearch/wav2letter#329]
In Train.cpp line 63 the code define the runPath with argv[2], I can't find any description about how to use continue mode and how to specify the runPath [here](https://github.com/facebookresearch/wav2letter/blob/5f1c1bed699a54882535e99e3092229539fe2ae1/docs/train.md)

**Comment by vineelpratap** [comment]
Assuming you have specified `-rundir=<RUNDIR> -runname=<RUNNAME>` for the initial run, you can continue in continue mode with 

```
<TRAIN_BINARY> continue <RUNDIR>/<RUNNAME> 
```

Optionally, you can also specify gflags that you want to change from the earlier run. For example, one thing we usually do is reduce the learning rate for the next run using continue mode.

```
<TRAIN_BINARY> continue <RUNDIR>/<RUNNAME> --lr 0.1
```
