### ISSUE TITLE
how to generate lm-4g.bin for WSJ?

### ISSUE THREAD

**Issue by k1kyo** [facebookresearch/wav2letter#331]
I wanna use the decode configs in [decode.cfg](https://github.com/facebookresearch/wav2letter/blob/master/recipes/wsj/configs/conv_glu/decode.cfg#L4). In Line 4 it uses lm-4g.bin as LM. I wonder how to generate lm-4g.bin. In [prepare_lm.py](https://github.com/facebookresearch/wav2letter/blob/master/recipes/wsj/data/prepare_lm.py) I can't find the command to generate binary for LM and it seems that argument ` cmudict`  and ` wsjdict`  don't work.
By the way, my WSJ dataset has names like 11-3.1, no 11_3.1. I replace ` sep = "-" if ds == "wsj0" else "_"`   with ` seq = '-'`  in [L75](https://github.com/facebookresearch/wav2letter/blob/master/recipes/wsj/data/utils.py#L75) and replace all the string like ` 13_34.1`  with ` 13-34.1` in [prepare_data.py](https://github.com/facebookresearch/wav2letter/blob/master/recipes/wsj/data/prepare_data.py), the changes works for my WSJ dataset, is my dataset different from your dataset? (It's my first time to use WSJ dataset and I'm not familiar with it)

**Comment by vineelpratap** [comment]
`prepare_lm.py` generates LM training data - 
 https://github.com/facebookresearch/wav2letter/blob/master/recipes/wsj/data/prepare_lm.py#L54 

You can use KenLM to create the language model - https://github.com/kpu/kenlm#estimation

**Comment by k1kyo** [comment]
> `prepare_lm.py` generates LM training data -
> https://github.com/facebookresearch/wav2letter/blob/master/recipes/wsj/data/prepare_lm.py#L54
> 
> You can use KenLM to create the language model - https://github.com/kpu/kenlm#estimation

Thanks!
