### ISSUE TITLE
Cannot train seq2seq model

### ISSUE THREAD

**Issue by seymacengizz** [facebookresearch/wav2letter#337]
Hi,

I am getting an error when I am trying to train seq2seq model. Can you please help me how you solved this problem?

DATASET: librispeech-clean

ERROR:
terminate called after throwing an instance of 'std::runtime_error'
  what():  unhandled cuda error
*** Aborted at 1560944202 (unix time) try "date -d @1560944202" if you are using GNU date ***
PC: @     0x7fe47af20428 gsignal
*** SIGABRT (@0x3e800004be8) received by PID 19432 (TID 0x7fe4fd5bba80) from PID 19432; stack trace: ***
    @     0x7fe47af204b0 (unknown)
    @     0x7fe47af20428 gsignal
    @     0x7fe47af2202a abort
    @     0x7fe47b865b39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7fe47b8641fb __cxxabiv1::__terminate()
    @     0x7fe47b864234 std::terminate()
    @     0x7fe47b864416 __cxa_throw
    @           0x66b044 fl::detail::ncclCheck()
    @           0x66c69e fl::distributedInit()
    @           0x5c0066 w2l::initDistributed()
    @           0x418937 main
    @     0x7fe47af0b830 __libc_start_main
    @           0x478f79 _start
    @                0x0 (unknown)
Aborted

TRAIN CONFIG FILE:
--runname=ls-100_seq2seq_tds16
--rundir=../data/asr/w2l-ls/models/
--tokensdir=../data/asr/w2l-ls/seq2seq/
--archdir=../data/asr/w2l-ls/
--listdata=true
--train=../data/asr/w2l-ls/seq2seq/train-clean-100.lst
--valid=dev-clean:../data/asr/w2l-ls/seq2seq/dev-clean.lst
--lexicon=../data/asr/w2l-ls/seq2seq/librispeech-train+dev-unigram-10000-nbest10.dict
--arch=network_seq2seq_tds.arch
--tokens=librispeech-train-all-unigram-10000.vocab-filtered
--criterion=seq2seq
--lr=0.05
--lrcrit=0.05
--momentum=0.0
--stepsize=40
--gamma=0.5
--maxgradnorm=15
--mfsc=true
--dataorder=output_spiral
--inputbinsize=25
--filterbanks=80
--attention=keyvalue
--encoderdim=512
--attnWindow=softPretrain
--softwstd=4
--trainWithWindow=true
--pretrainWindow=3
--maxdecoderoutputlen=120
--usewordpiece=true
--wordseparator=_
--sampletarget=0.01
--target=ltr
--batchsize=4
--labelsmooth=0.05
--nthread=6
--memstepsize=4194304
--eostoken=true
--pcttraineval=1
--pctteacherforcing=99
--iter=200
--enable_distributed=true

When preparing data with prepare_seq2se2_dict.py, '_' character is assigned before the words. Could it not be because of this training? 

Some data in the 'librispeech-train-all-unigram-10000.vocab' file is as follows:
<unk>	0
<s>	0
</s>	0
▁the	-2.90205
▁and	-3.50317
▁of	-3.60996
▁to	-3.6869
▁a	-3.86236
s	-4.05527
▁in	-4.16581
▁i	-4.3758
▁he	-4.40509
▁was	-4.421
ed	-4.43408
▁that	-4.45709
▁it	-4.5481
▁his	-4.73492
ing	-4.75185

Some data in the 'librispeech-train-all-unigram-10000.vocab-filtered' file is as follows:
_the
_and
_of
_to
_a
s
_in
_i
_he
_was
ed
_that
_it
_his
ing

Some data in the 'librispeech-train+dev-unigram-10000-nbest10.dict' file is as follows:
a _a
a _ a
a'rony _a ' ro ny
a'rony _a ' r on y
a'rony _a ' ro n y
a'rony _a ' r o ny
a'rony _a ' r o n y
a'rony _ a ' ro ny
a'rony _ a ' r on y
a'rony _ a ' ro n y
a'rony _ a ' r o ny
a'rony _ a ' r o n y

What else could be the problem if the data was prepared correctly?

Thanks.

**Comment by gloryyingling** [comment]
according to your error log, it seems it not due to configuration, did you
built flashlight with distributed enabled?
You'd better to confirm you set up the distributed training environment
correctly.

**Comment by seymacengizz** [comment]
I can start training with ctc and asg without any problems. For this reason, I'm starting to wonder if there is a problem with the seq2seq model from data or configuration.

Well, Is there may be a hardware problem? Is the hardware may not sufficient for the seq2seq architecture? My graphic card is GeForce GTX 1060.

**Comment by gloryyingling** [comment]
I wonder how you could train ctc or asg model with GTX 1060. I tried to train with GTX 1060 on my local but I failed with Memory leak. Could you please share how much is your GPU's RAM?
And did you tried with nthread=1 for seq2seq model?
Maybe It could be helpful.
