### ISSUE TITLE
Trained model file size very small 

### ISSUE THREAD

**Issue by SYnchronYSe** [facebookresearch/wav2letter#339]
Hi
I trained the model in the librispeech tutorial with the clean-dataset of 7GB size. After training for about 19 epochs the size of my model ( librispeech_clean_trainlogs/001_model_data#dev-clean.bin ) is just 15.6MB. Is this normal?

If I remember correctly, the model trained by Talon was nearly 1GB. The difference was that he had trained the bigger neural network present in wav2letter/recipes

**Comment by lunixbochs** [comment]
The model size is just the size of the weights from your network.arch. The provided librispeech recipe produces a 1.6GB model. I've experimented with 800MB and 400MB models as well just by tweaking the layer sizes.

I assume you're using the network.arch from the tutorial [here](https://github.com/facebookresearch/wav2letter/blob/master/tutorials/1-librispeech_clean/network.arch), which is a completely different architecture and has very few small layers.

I don't think you want to actually use that architecture, as they claimed an 18% word error rate on librispeech-clean with it in the tutorial, while I've seen as low as 3.14% token error rate with my 400MB model and 2.54% with my 1.6GB model.

**Comment by tlikhomanenko** [comment]
Hi @SYnchronYSe,

just to confirm that @lunixbochs is correct and for the tutorial a very small model (with small number of parameters) is provided just to demonstrate the full pipeline and some meaningful results.
