### ISSUE TITLE
issue in data pre-processing

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#34]
Hi @VitaliyLi  
I am trying to transcribe sample audio files using pre-trained model. I have stored my audio files in dev-clean2 folder. When I am running this command" luajit data/librispeech/create.lua Audios audio-proc
| parsing SPEAKERS.TXT for gender...
| analyzing Audios/dev-clean2...
| writing audio-proc/dev-clean2...
luajit: data/librispeech/create.lua:31: bad argument #1 to 'writeShort' (dimension 2 size must be equal to the number of channels)
stack traceback:
	[C]: in function 'writeShort'
	data/librispeech/create.lua:31: in function 'copytoflac'
	data/librispeech/create.lua:95: in function 'createidx'
	data/librispeech/create.lua:150: in main chunk
	[C]: at 0x00405d50
"
I am getting this error can someone help me please

**Comment by vineelpratap** [comment]
Your audio seems to have 2 channels. The librispeech preprocessing scripts are designed for which expect the number of channels to be 1 - https://github.com/facebookresearch/wav2letter/blob/master/data/librispeech/create.lua#L28 .
