### ISSUE TITLE
Is there any problem with the latest decoder cfg(Decoder's wer worse than Test)? 

### ISSUE THREAD

**Issue by goodmajia** [facebookresearch/wav2letter#342]
I used the latest code for my exp.  On my test set, the "Test" binary get wer about 20, the "Decoder" binary with an good external LM and Lexicon gets wer about 30.  But when i use "Decoder" building about two month ago, the wer is 18, better than "Test". 

My decoder config as follows:
`--listdata=true

--lm=lm.arpa.bin
--lexicon=lexicon.txt
--am=mdl.bin
--test=test.lst

--sclite=result_dir

--lmweight=4.5
--wordscore=1
--beamsize=2500
--beamthreshold=25
--silweight=-0.4
--nthread_decoder=8
--smearing=max
--show=true
--logtostderr=1

`
is any problem with this cfg?

**Comment by tlikhomanenko** [comment]
Hi @goodmajia,

Decoding for latest updates should be pretty the same as old version. A little bit fluctuations are expected (< 0.2% in WER). 

Do you run with exactly the same decoder params as previously (lmweight, wordscore, beamthreshold, beamsize, silweight, lm model)? If no, could you run with exactly the same params?
Could you also send the head of your lexicon file?

**Comment by goodmajia** [comment]
hi @tlikhomanenko  I am sure that i run with the same params as I list above.
the head of lexicon as follows:
`aa      a a
aab     a a b
aac     a a c
aach    a a c h
aachen  a a c h e n
aachener        a a c h e n e r
aah     a a h
aal     a a l
aalborg a a l b o r g
aale    a a l e
aalener a a l e n e r
aalesund        a a l e s u n d
aaliyah a a l i y a h
aaliyah's       a a l i y a h ' s
aalto   a a l t o
aamer   a a m e r
aamir   a a m i r
aanya   a a n y a`

**Comment by goodmajia** [comment]
hi @tlikhomanenko , I find the problem, the format of the lexicon need to be changed. thanks!
