### ISSUE TITLE
test & decode and decode will get different WER

### ISSUE THREAD

**Issue by k1kyo** [facebookresearch/wav2letter#345]
I ran the test.cpp to get the emissionSet and then I ran the decode.cpp with `--emission_dir` not with `--am`, I got 5.46637 WER. 
I ran the decode.cpp with `--am` not with `--emission_dir` and I got 5.31802 WER.
it seems that decode with `--am` would get a lower WER than test & decode with `--emission_dir`. I think it should get the same WER in theory.

**Comment by xuqiantong** [comment]
Note that the emission set you specified by `--emission_dir` will include all the gflags you used in train and test. So, please double check that the two runs: 1) decode and 2) test & decode, use exactly the same flags. You may start checking from `--lexicon`.

Closing for now. If you are sure the flags are the same, please provide more details and reopen this issue.
