### ISSUE TITLE
Catastrophic forgetting techniques

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#346]
How much variance of datasets are you training your full models against? I assume you have a large corpus of internal data, not just librispeech.

I have around 4000 hours of various datasets at this point, and anytime I do a focused train on one dataset it clearly forgets features of the others. When I train on more datasets at once, it also fails to converge as fully on each dataset.

Have you experimented with catastrophic forgetting techniques like EWC in wav2letter to train and retrain on smaller datasets at a time? I'm curious if this is likely to let me converge more quickly and train more fully on each dataset.

I'm also planning on allowing users to retrain the acoustic model themselves, and I think something like EWC would allow it to learn about their voice without forgetting as much from the long duration training.

Any thoughts?

**Comment by tlikhomanenko** [comment]
Please check on our recent work https://arxiv.org/abs/2010.11745 + finetuning of our SOTA models (here people reported good numbers for their transfer learning tasks).
