### ISSUE TITLE
How to do inference on a new audio file using the trained acoustic model?

### ISSUE THREAD

**Issue by megharangaswamy** [facebookresearch/wav2letter#347]
Dear all,

I am trying to get a transcript of an audio file using the acoustic model I have trained. When decoding, I was supposed to give the data with a transcript file inside. But currently, I want to get transcripts of the audio file when are new. For this audio file, I do not have a transcript file. I want to create 1 using my trained acoustic model. How to get it? 

in the data preparation stage, the script expects a transcript file to create .id, .tkn, and .wrd file. But I do not have that. How to work with this?

Kindly help!!!

Thank you,
Megha Rangaswamy

**Comment by lunixbochs** [comment]
All of those files can be blank

**Comment by megharangaswamy** [comment]
@lunixbochs ,

do you mean inside my data folder, with the audio files I also need to keep (say) my_transcript.trans.txt file?
Like in just this file need to be there even if this file has no transcript in them? Because I tried doing like this, and this still does not work. When I run the prepare_data.py file, it is creating an output folder without any files inside the test_clean folder.


OR

Do you mean anything else? Kindly elaborate a little.

Thank you,
Megha Rangaswamy

**Comment by nestyme** [comment]
Hi @megharangaswamy 
Mb It can be done in smarter way, but possible solution is to put file which supposed to be transcripted into 000000000.wav and write whatever you want in .id, .wrd, .tkn and then run ./Decoder --flagsfile /path/to/config 
(don't forget to provide path to directory into config file)
