### ISSUE TITLE
Assertion Failed error/

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#35]
Hi 
When I am trying to run the "luajit data/librispeech/create.lua Audios audio-proc"

I am getting the following error,
| parsing SPEAKERS.TXT for gender...
| analyzing Audios/dev-clean2...
| writing audio-proc/dev-clean2...
luajit: data/librispeech/create.lua:91: assertion failed!
stack traceback:
	[C]: in function 'assert'
	data/librispeech/create.lua:91: in function 'createidx'
	data/librispeech/create.lua:150: in main chunk
	[C]: at 0x00405d50

Can anyone explain what this error means

**Comment by vineelpratap** [comment]
As mentioned in #34, the librispeech preprocessing scripts are supposed to work only for librispeech data 

https://github.com/facebookresearch/wav2letter/blob/master/data/librispeech/create.lua#L91

**Comment by saisrinivas047** [comment]
hi @vineelpratap
thanks for the reply. So if the preprocessing scripts are only for librispeech data does that mean that we cannot transcribe random sample audio files using the pre-trained model ? @VitaliyLi
