### ISSUE TITLE
Unknown index in dictionary

### ISSUE THREAD

**Issue by mtmd** [facebookresearch/wav2letter#353]
I built the program outside of a docker and followed the instructions [here](https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean) to train the provided toy example on Librispeech-Clean Dataset. For the first 23 epochs everything worked fine. On epoch 24, it suddenly crashed with the following error
`terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unknown index in dictionary '-1'
*** Aborted at 1563414724 (unix time) try "date -d @1563414724" if you are using GNU date ***
PC: @     0x7f3f81118e97 gsignal
*** SIGABRT (@0x3e8000003ea) received by PID 1002 (TID 0x7f3fb35d62c0) from PID 1002; stack trace: ***
    @     0x7f3f82688890 (unknown)
    @     0x7f3f81118e97 gsignal
    @     0x7f3f8111a801 abort
    @     0x7f3f81d3c957 (unknown)
    @     0x7f3f81d42ab6 (unknown)
    @     0x7f3f81d42af1 std::terminate()
    @     0x7f3f81d42d24 __cxa_throw
    @     0x5604c38bad84 _ZNK3w2l10Dictionary8getEntryB5cxx11Ei
    @     0x5604c38fde8a _ZN3w2l10tknIdx2LtrB5cxx11ERKSt6vectorIiSaIiEERKNS_10DictionaryE
    @     0x5604c38fe694 _ZN3w2l17tknPrediction2LtrB5cxx11ESt6vectorIiSaIiEERKNS_10DictionaryE
    @     0x5604c37d18c7 _ZZ4mainENKUlRKN2af5arrayES2_RN3w2l13DatasetMetersEE1_clES2_S2_S5_
    @     0x5604c37d44f5 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi
    @     0x5604c3780842 main
    @     0x7f3f810fbb97 __libc_start_main
    @     0x5604c37cf25a _start
Aborted (core dumped)
`
System information:
OS Name: Ubuntu
OS  Version: 18.04.2 LTS
NVIDIA driver version: 418.67
GPU: TITAN V
CPU: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz

**Comment by awni** [comment]
@vineelpratap Any ideas on this one?

**Comment by vineelpratap** [comment]
@mtmd - Given that it ran for > 20 epochs without any issue, I don't see a reason why it would fail. Is it possible to provide gdb backtrace info ?

Also, just making sure - are you using the latest version of wav2letter ?

**Comment by dhruv-karan** [comment]
@vineelpratap @mtmd plz reply help me on dhruvkaran243@gmail.com need u r help on speech2text.

**Comment by mtmd** [comment]
@vineelpratap, you are right. It was surprising to me too. I tried to reproduce the error to send you the gdb backtrack info, but it no longer happens on my machine. I am going to close this issue. In case it happens again, I'll reopen it with gdb back track log. Thank you all.
