### ISSUE TITLE
run time error during tutorials/1-librispeech_clean

### ISSUE THREAD

**Issue by YuBeomGon** [facebookresearch/wav2letter#354]
hello.
i use docker and nvidia docker.

after this cmd, 
wav2letter/build/Train train --flagsfile ./wav2letter/tutorials/1-librispeech_clean/train.cfg

following runtime error happened.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open dictionary file: [...]/data/tokens.txt
*** Aborted at 1563498445 (unix time) try "date -d @1563498445" if you are using GNU date ***
PC: @     0x7fb2cb301428 gsignal
*** SIGABRT (@0xe7a) received by PID 3706 (TID 0x7fb315174600) from PID 3706; stack trace: ***
    @     0x7fb2d2b81390 (unknown)
    @     0x7fb2cb301428 gsignal
    @     0x7fb2cb30302a abort
    @     0x7fb2cbc4484d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fb2cbc426b6 (unknown)
    @     0x7fb2cbc42701 std::terminate()
    @     0x7fb2cbc42919 __cxa_throw
    @           0x565613 w2l::createTokenDict()
    @           0x41919c main
    @     0x7fb2cb2ec830 __libc_start_main
    @           0x478d59 _start
    @                0x0 (unknown)

whats wrong?

**Comment by cogmeta** [comment]
**what(): Unable to open dictionary file: [...]/data/tokens.txt**

**Comment by awni** [comment]
You have to set the dictionary flag correctly in the flagsfile. Wherever you see `[...]` you should replace with the path to the actual file.

**Comment by dhruv-karan** [comment]
awni plz check your inbox i just mailed u and need some help this stuff

thank you
