### ISSUE TITLE
any trick for adjustment of --lr and --lrcrit

### ISSUE THREAD

**Issue by k1kyo** [facebookresearch/wav2letter#355]
The `lr` and `lrcrit` in the train.cfg of librispeech recipes are 0.6 and 0.006, respectively. If I set `--stepsize` and `--gamma`, `lr` and `lrcrit` would keeping reducing as the training progresses. Intuitively 0.006 is kind of  small learning rate for SGD but 0.6 is big for SGD. As the `lr` and `lrcrit` reduce, `lrcrit` would get a small value like 0.0001. In that case I guess `lrcrit` would make no difference for training criterion. Can you share your `lr` and `lrcrit` adjustment schemes when training.

**Comment by awni** [comment]
For that recipe we don't adjust them. In other recipes we reduce them by gamma=0.5 and stepsize=40 (see e.g. [tds recipe](https://github.com/facebookresearch/wav2letter/blob/master/recipes/librispeech/configs/seq2seq_tds/train.cfg))
