### ISSUE TITLE
Error building wav2letter  distributed mode

### ISSUE THREAD

**Issue by cogmeta** [facebookresearch/wav2letter#356]
Ubuntu 16.04
wav2letter - master branch

/home/ubuntu/w2v/wav2letter/Train.cpp: In lambda function:
/home/ubuntu/w2v/wav2letter/Train.cpp:455:46: error: could not convert ‘gradNorm’ from ‘const double’ to ‘std::shared_ptr<fl::Reducer>’
     fl::distributeModuleGrads(ntwrk, gradNorm);
                                              ^
/home/ubuntu/w2v/wav2letter/Train.cpp:456:45: error: could not convert ‘gradNorm’ from ‘const double’ to ‘std::shared_ptr<fl::Reducer>’
     fl::distributeModuleGrads(crit, gradNorm);

**Comment by awni** [comment]
It looks like you are using an old version of wav2letter?

https://github.com/facebookresearch/wav2letter/blob/master/Train.cpp#L442-L445

**Comment by cogmeta** [comment]
No, I am not. I am using master branch
#if BUILD_DISTRIBUTED
    fl::distributeModuleGrads(ntwrk, gradNorm);
    fl::distributeModuleGrads(crit, gradNorm);
#endif

grandNorm is defined as double 
 double gradNorm = 1.0 / (FLAGS_batchsize * worldSize);
while  signature for distributeModuleGrads is 


void distributeModuleGrads(
--
16 | std::shared_ptr<const Module> module,
17 | std::shared_ptr<Reducer> reducer)

**Comment by cogmeta** [comment]
Thanks. Fixed with latest master.
