### ISSUE TITLE
luajit: /torch/install/share/lua/5.1/wav2letter/runtime/data.lua:146: bad argument #1 to 'lines' (/data/local/packages/ai-group.speechdata/latest/speech/letters.lst: No such file or directory)

### ISSUE THREAD

**Issue by dharm033075** [facebookresearch/wav2letter#36]
HI @VitaliyLi 
I am getting the following while using pretarined model to transcribe the audio file.Can someone pls help me solve this

luajit test.lua librispeech-glu-highdropout-cpu.bin -progress -show -test dev-clean2 -save -datadir audio-proc/ -datadir audio-proc/ -gfsai
luajit: /torch/install/share/lua/5.1/wav2letter/runtime/data.lua:146: bad argument #1 to 'lines' (/data/local/packages/ai-group.speechdata/latest/speech/letters.lst: No such file or directory)
stack traceback:
[C]: in function 'lines'
/torch/install/share/lua/5.1/wav2letter/runtime/data.lua:146: in function 'newdict'
test.lua:72: in main chunk
[C]: at 0x00405d50

**Comment by VitaliyLi** [comment]
Hi, you need to run data preprocessing scripts to generate the letters.lst file.
