### ISSUE TITLE
 what():  loadSound: unknown format or could not open stream

### ISSUE THREAD

**Issue by cogmeta** [facebookresearch/wav2letter#360]
I followed the librispeech recipe and I get this

terminate called after throwing an instance of 'std::runtime_error'
  what():  loadSound: unknown format or could not open stream
*** Aborted at 1563884075 (unix time) try "date -d @1563884075" if you are using GNU date ***
PC: @     0x7faea54da428 gsignal
*** SIGABRT (@0x3e8000169a7) received by PID 92583 (TID 0x7faef8770640) from PID 92583; stack trace: ***
    @     0x7faef7cfd390 (unknown)
    @     0x7faea54da428 gsignal
    @     0x7faea54dc02a abort
    @     0x7faec26a10a5 __gnu_cxx::__verbose_terminate_handler()
    @     0x7faec2612436 __cxxabiv1::__terminate()
    @     0x7faec2612481 std::terminate()
    @     0x7faec260fee3 __cxa_throw
    @           0x5d2951 w2l::loadSound<>()
    @           0x5d2b10 w2l::loadSound<>()
    @           0x5c626a w2l::W2lListFilesDataset::getLoaderData()
    @           0x5bf564 w2l::W2lDataset::getFeatureData()
    @           0x5c0b19 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @           0x5c0e4e w2l::W2lDataset::get()
    @           0x4804a4 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.11256
    @           0x41b525 main
    @     0x7faea54c5830 __libc_start_main
    @           0x47bcb9 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by cogmeta** [comment]
# Training config for Librispeech using Gated ConvNets
# Replace `[...]` with appropriate paths
--runname=librispeech_conv_glu
--rundir=models
--tokensdir=./data/librispeech
--archdir=./config/seq2seq_tds
--listdata=true
--train=./data/librispeech/train-clean-100.lst,./data/librispeech/train-clean-360.lst,./data/librispeech/train-other-500.lst
--valid=dev-clean:./data/librispeech/dev-clean.lst,dev-other:./data/librispeech/dev-other.lst
--lexicon=./data/librispeech/librispeech-train+dev-unigram-10000-nbest10.dict
--arch=network.arch
--tokens=librispeech-train-all-unigram-10000.vocab-filtered
--lexicon=./data/librispeech/librispeech-train+dev-tokens.dict
--arch=network.arch
--tokens=tokens.txt
--criterion=asg
--lr=0.6
--lrcrit=0.006
--linseg=1
--momentum=0.8
--maxgradnorm=0.2
--replabel=2
--surround=|
--onorm=target
--sqnorm=true
--mfsc=true
--nthread=6
--batchsize=4
--transdiag=4

**Comment by cogmeta** [comment]
head -5 ./data/librispeech/train-clean-100.lst
train-clean-100-103-1240-0000 /home/ubuntu/data/wav2letter/recipes/librispeech/data/src/LibriSpeech/train-clean-100/103/1240/103-1240-0000.flac 14085.0 chapter one missus rachel lynde is surprised missus rachel lynde lived just where the avonlea main road dipped down into a little hollow fringed with alders and ladies eardrops and traversed by a brook
train-clean-100-103-1240-0001 /home/ubuntu/data/wav2letter/recipes/librispeech/data/src/LibriSpeech/train-clean-100/103/1240/103-1240-0001.flac 15945.0 that had its source away back in the woods of the old cuthbert place it was reputed to be an intricate headlong brook in its earlier course through those woods with dark secrets of pool and cascade but by the time it reached lynde's hollow it was a quiet well conducted little stream
train-clean-100-103-1240-0002 /home/ubuntu/data/wav2letter/recipes/librispeech/data/src/LibriSpeech/train-clean-100/103/1240/103-1240-0002.flac 13945.0 for not even a brook could run past missus rachel lynde's door without due regard for decency and decorum it probably was conscious that missus rachel was sitting at her window keeping a sharp eye on everything that passed from brooks and children up

**Comment by cogmeta** [comment]
ls -al "/home/ubuntu/data/wav2letter/recipes/librispeech/data/src/LibriSpeech/train-clean-100/103/1240/103-1240-0000.flac"
-r--r--r-- 1 ubuntu ubuntu 255398 Jul  8  2014 /home/ubuntu/data/wav2letter/recipes/librispeech/data/src/LibriSpeech/train-clean-100/103/1240/103-1240-0000.flac

**Comment by tlikhomanenko** [comment]
Hi @cogmeta,

Seems you have a trouble with libsnd. Could you provide details how you installed it? Could you try to run this in the docker container?

**Comment by nhha1602** [comment]
I got the same issue.
I installed libsnd by following instruction:

git clone git://github.com/erikd/libsndfile.git
./autogen.sh
./configure --enable-werror
make
make check
sudo make install

**Comment by cogmeta** [comment]
@nhha1602 Thanks. Will try it and report back.

**Comment by nhha1602** [comment]
I tried to re-build libsndfile with opus and it is OK.

**Comment by samehraban** [comment]
> I tried to re-build libsndfile with opus and it is OK.

How did you do that? I'm facing same problem and it seems libsndfiles is configured to read opus/flac by default.

**Comment by kksiddharth** [comment]
Did anyone find a solution to this problem.... I'm facing the same error when i try to train the acoustic model of the LibriSpeech clean tutorial, I tried out @nhha1602 suggestion to rebuild libsndfile with opus, https://github.com/xiph/opus, but to no avail as the error is still persisting, any help on this issue would be of great help, thanks

**Comment by kksiddharth** [comment]
Hey guys, I'm really sorry, but yea @nhha1602 was right, I just had to rebuild wav2letter after rebuilding libsndfile with opus, and the issue went away, one way, correct me if I'm wrong, i guess this can be detected is to make test after building wav2letter, all the cases were passing except SoundTest for me when i built libsndfile without opus, and after rebuilding with opus it passed. Thanks
