### ISSUE TITLE
what is a slice wer and slice ler?

### ISSUE THREAD

**Issue by YuBeomGon** [facebookresearch/wav2letter#364]
word error ratio and letter error ratio.
what is a slice?

and can I see the total average word ratio in total sample data??

|T|: even so i had just returned from an arduous journey exhausted and badly needing a rest
|P|: even so i had just returned from an arduous journey exhaust it and badly needing a rest
[sample: 2464, WER: 12.5%, LER: 3.48837%, slice WER: 14.8148%, slice LER: 6.43275%, progress: 0.609756%]
|T|: to this his answer was prompt oh thank god no and is the record yours
|P|: to this his answer was prompt to thank god now and is the reckon yours
[sample: 141, WER: 20%, LER: 8.69565%, slice WER: 23.5294%, slice LER: 9.30233%, progress: 0.609756%]
|T|: slow to world greetings quick with its o list when the angels speak
|P|: slow to world greetings quick with its oh list when the angel speak
[sample: 2607, WER: 15.3846%, LER: 2.98507%, slice WER: 21.2766%, slice LER: 7.53138%, progress: 0.914634%]
|T|: at the head of the <unk> were <unk> <unk> and button bright who had the parrot on his shoulder and they were supported by captain coralie and captain <unk> and rosalie the witch
|P|: at the head of the tanks were at basil and by a bright who had the pearl on his shoulder and they are supported by captain cole and cat intendant and rosily the witch
[sample: 2528, WER: 33.3333%, LER: 20.1087%, slice WER: 33.3333%, slice LER: 20.1087%, progress: 0.304878%]
|T|: there is no danger of the modern commentators on the timaeus falling into the absurdities of the neo platonists
|P|: there is no danger of the modern commentators one tones falling into absurdities of the neo platonists
[sample: 878, WER: 21.0526%, LER: 9.90991%, slice WER: 21.0526%, slice LER: 9.90991%, progress: 0.304878%]
|T|: control yourselves my dears replied the <unk> the worst punishment i know how to inflict on anyone this prisoner is about to suffer you'll see a very pretty patching my royal daughters
|P|: control yourselves my dears replied the bolero the worst punishment i know how to look on and on this prisoners of but to suffer you are of very pretty patching my roy with daughters
[sample: 2511, WER: 37.5%, LER: 15.9574%, slice WER: 37.5%, slice LER: 15.9574%, progress: 0.304878%]
|T|: only there are two sorts of cloud and fire
|P|: only there are two sorts of cloud and fire
[sample: 93, WER: 0%, LER: 0%, slice WER: 17.8571%, slice LER: 6.40569%, progress: 1.21951%]
|T|: therefore her majesty paid no attention to anyone and no one paid any attention to her
|P|: therefore her majesty paid no attention to any one and no one paid any attention to her
[sample: 2508, WER: 12.5%, LER: 1.16279%, slice WER: 13.9535%, slice LER: 4.66926%, progress: 0.914634%]

**Comment by xuqiantong** [comment]
`slice WER` is the average WER computed so far in a given decoding thread. If you pull the latest master, the thread info will show up in the summary line `[sample: ...]`. 
You will see the average WER of all samples after decoding finish.
