### ISSUE TITLE
prepare_seq2seq_dic.py error

### ISSUE THREAD

**Issue by YuBeomGon** [facebookresearch/wav2letter#365]
I did it below.
python3 prepare_seq2seq_dict.py --src Data/ --dst ./librispeech

but below error happened.
whats wrong? and Can I get a doc or guide for LibSpeech training?

trainer_interface.cc(507) LOG(INFO) Saving model: ./librispeech/librispeech-train-all-unigram-10000.model
trainer_interface.cc(531) LOG(INFO) Saving vocabs: ./librispeech/librispeech-train-all-unigram-10000.vocab
creating word piece list...
Traceback (most recent call last):
  File "prepare_seq2seq_dict.py", line 88, in <module>
    for line in f:
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 21: ordinal not in range(128)

**Comment by jacobkahn** [comment]
@YuBeomGon — my guess is that the script is using `str` and isn't expecting other ascii ordinals. Can you try using `codecs.open` from [`codecs`](https://docs.python.org/2/library/codecs.html) instead of `open` when opening the file?

**Comment by tlikhomanenko** [comment]
@YuBeomGon,

this is fixed in the 41dd8ee8cc69f46a567af922681c1a2dc6899540, have a look at https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/seq2seq_tds/librispeech how to prepare data and run training/decoding.
