### ISSUE TITLE
question about train config file

### ISSUE THREAD

**Issue by YuBeomGon** [facebookresearch/wav2letter#366]
what is this, and how can I change this??
--lexicon=[...]/librispeech-train+dev-tokens.dict

below error happend. 
this is no librispeech-train+dev-tokens.dict, how can I make this?
root@356173c7396f:~# wav2letter/build/Train train --flagsfile wav2letter/recipes/librispeech/configs/conv_glu/train.cfg
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Cannot open wav2letter/recipes/librispeech/data/Data/lm/librispeech-train+dev-tokens.dict

**Comment by k1kyo** [comment]
you should prepare your data using [prepare_data.py](https://github.com/facebookresearch/wav2letter/blob/master/recipes/librispeech/data/prepare_data.py) in librispeech recipes. In [Line 117](https://github.com/facebookresearch/wav2letter/blob/master/recipes/librispeech/data/prepare_data.py#L117) the dict is generated.

**Comment by tlikhomanenko** [comment]
Hi @YuBeomGon,

We have restructured a little bit data preparation and pre-trained model publishing. Now there is also more clear documentation on re-running recipes, please have a look here https://github.com/facebookresearch/wav2letter/tree/master/recipes in dirs `data` and `models`.

Feel free to reopen the issue if you still have problems to re-run training/decoding for recipes.
