### ISSUE TITLE
Kaldi data adaptation

### ISSUE THREAD

**Issue by benoriol** [facebookresearch/wav2letter#368]
Hello,
I was wondering which is the easiest way to adapt kaldi data to wav2letter. 
For example, I guess that wav2letter doesn't support something like Kaldi's "segments" file, right?
Do I have to manually split my dataset in segments and store them in numbered wav/flac/... files?
Do you/Does anyone have utility scripts for this kind of adaptation?

Thank you very much

Benet

**Comment by vineelpratap** [comment]
@benoriol - We are planning to change the data format used by wav2letter++ to a new format soon. This is closely related to `kaldi` data format.

Each dataset (test/valid/train) needs to be in a separate file with one sample per line.
A sample is specified using 4 columns separated by space (or tabs).
 - `sample_id` - unique id for the sample
 - `input_handle` - input audio file path.
 - `size` - a real number used for sorting the dataset (typically audio duration).
 - `transcription` - word transcription for this sample

The directories for the dataset is specified using `-datadir` and files are specified
with `-train`, `-valid` and `-test` corresponding to training, validation and test sets.

```
// Example input file format

[~/speech/data] head train.lst
train001 /tmp/000000000.flac 100.03  this is sparta
train002 /tmp/000000001.flac 360.57  coca cola
train003 /tmp/000000002.flac 123.53  hello world
train004 /tmp/000000003.flac 999.99  quick brown fox jumped
...
...
```

Currently, this is not the default option and you would need to specify `--listdata` flag to use it. You might also want to take a look at our Librispeech recipe which uses this format - https://github.com/facebookresearch/wav2letter/tree/master/recipes/librispeech/ . 

Hope it helps !

**Comment by benoriol** [comment]
This still doesn't solve the problem of having multiple transcribed utterances in the same audio file. Say my audio file is a whole conversation and my dataset is transcribed by segments. With this format, I will still have to split the audio files into smaller audio files corresponding to each transcribed utterances. This is avoided in kaldi using the segments file.

However, I think this format is very useful too. In my opinion, it is much more practical than naming in a specific way the files. 

Thanks a lot for the help!

**Comment by vineelpratap** [comment]
>  In my opinion, it is much more practical than naming in a specific way the files.

Yup, that's indeed one our goals - to be as generic as possible. Ideally, we want to support split segments usage as well. This will be done after we have updated the codebase with the new format and remove all dependencies with the older version. 

If you want to be unblocked for now, you can have a segments file mapping from `filename` to `segment_info` and read the entire file and later use the specific segment. Here is a code pointer - https://git.io/fj9Qh.

**Comment by jkkj1630** [comment]
> @benoriol - We are planning to change the data format used by wav2letter++ to a new format soon. This is closely related to `kaldi` data format.
> 
> Each dataset (test/valid/train) needs to be in a separate file with one sample per line.
> A sample is specified using 4 columns separated by space (or tabs).
> 
> * `sample_id` - unique id for the sample
> * `input_handle` - input audio file path.
> * `size` - a real number used for sorting the dataset (typically audio duration).
> * `transcription` - word transcription for this sample
> 
> The directories for the dataset is specified using `-datadir` and files are specified
> with `-train`, `-valid` and `-test` corresponding to training, validation and test sets.
> 
> ```
> // Example input file format
> 
> [~/speech/data] head train.lst
> train001 /tmp/000000000.flac 100.03  this is sparta
> train002 /tmp/000000001.flac 360.57  coca cola
> train003 /tmp/000000002.flac 123.53  hello world
> train004 /tmp/000000003.flac 999.99  quick brown fox jumped
> ...
> ...
> ```
> 
> Currently, this is not the default option and you would need to specify `--listdata` flag to use it. You might also want to take a look at our Librispeech recipe which uses this format - https://github.com/facebookresearch/wav2letter/tree/master/recipes/librispeech/ .
> 
> Hope it helps !

hello,the link are 404,i want know,the size is what?sound time of second?

**Comment by tlikhomanenko** [comment]
Hi @jkkj1630,

the new link is https://github.com/facebookresearch/wav2letter/tree/master/recipes/data/librispeech and the size of sound in milliseconds (see https://github.com/facebookresearch/wav2letter/blob/master/recipes/data/librispeech/utils.py#L43)
