### ISSUE TITLE
Read 0 blocks instead of 1 at /tmp/luarocks_torch-scm-1-1308/torch7/lib/TH/THDiskFile.c:352

### ISSUE THREAD

**Issue by pvn25** [facebookresearch/wav2letter#37]
I'm trying to run this command:

luajit test-one-file.lua ~/librispeech-glu-highdropout-cpu.bin my-audio-file.wav 

And, I'm getting this error message:

| best valid (test?) error was:	table: 0x406e7940
luajit: /home/vraj/usr/share/lua/5.1/torch/File.lua:259: read error: read 0 blocks instead of 1 at /tmp/luarocks_torch-scm-1-1308/torch7/lib/TH/THDiskFile.c:352
stack traceback:
	[C]: in function 'readInt'
	/home/vraj/usr/share/lua/5.1/torch/File.lua:259: in function 'readObject'
	test-one-file.lua:37: in main chunk
	[C]: at 0x00404ab0

I've also tried re-downloading the model.

**Comment by saisrinivas047** [comment]
hi did you solve this error. are you able to test single audio file. If you are able to do that can you share how you did that its kinda urgent for me

**Comment by VitaliyLi** [comment]
Hi @pvn25 ,

test-one-file.lua might be outdated and have some bugs, you should use only test.lua as specified in README file.

Thank you,
Vitaliy
