### ISSUE TITLE
ConvLM by fairseq

### ISSUE THREAD

**Issue by hiroaki-ogawa** [facebookresearch/wav2letter#372]
I trained character based convlm of WSJ using fairseq. So I  have convlm in format of [fairseq](https://github.com/pytorch/fairseq).
(lets say, checkpoints/checkpoint_best.pt)
I gave this lm to the decoder 
```
--lexicon ""
--lm checkpoints/checkpoint_best.pt
--lm_vocab path/to/dict.txt
--lmtype convlm
--lm_memory 5000
```
and got follwoing error
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unknown token in dictionary: <unk>
*** Aborted at 1565701299 (unix time) try "date -d @1565701299" if you are using GNU date ***
PC: @     0x7fc61031b428 gsignal
*** SIGABRT (@0xd5000002ab) received by PID 683 (TID 0x7fc65a18e600) from PID 683; stack trace: ***
    @     0x7fc617b9b390 (unknown)
    @     0x7fc61031b428 gsignal
    @     0x7fc61031d02a abort
    @     0x7fc610c5e84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fc610c5c6b6 (unknown)
    @     0x7fc610c5c701 std::terminate()
    @     0x7fc610c5c919 __cxa_throw
    @           0x50c22c w2l::Dictionary::getIndex()
    @           0x56397b w2l::ConvLM::ConvLM()
    @           0x487364 std::__shared_ptr<>::__shared_ptr<>()
    @           0x41a8b8 main
    @     0x7fc610306830 __libc_start_main
    @           0x4762d9 _start
    @                0x0 (unknown)
```
My dictionary made by fairseq just include letters and "madeupwords000"..."madeupwords005".
Do I have to convert the convlm for wav2letters?

**Comment by lunixbochs** [comment]
Does your tokens.txt include numbers?

**Comment by hiroaki-ogawa** [comment]
Thank you @lunixbochs .

No, my tokens.txt does not include numbers.
I realized that I didn't replace repetition with numbers in the AM training. 
I will re-train my am and check it!

**Comment by tlikhomanenko** [comment]
Hi @hiroaki-ogawa,

At first you need to convert fairseq checkpoint (which is python dict of tensors) to the format of wav2letter (like create a necessary network in w2l and then load matrices from checkpoint file).

The dictionary which is generated by fairseq you need to preprocess in the following way:
- remove the second column (like `cut -f1 dict.txt`) 
- add at the begging of the file 4 additional words (due to fairseq implementation) 
```
<fairseq_style>
<pad>
</s>
<unk>
``` 
Then you should use preprocess dict as an input parameter "lm_vocab" in the decoder.

You could have a look at the models we published here https://github.com/facebookresearch/wav2letter/blob/master/models/lexicon_free.md.

**Comment by tlikhomanenko** [comment]
About publishing code to convert fairseq model into wav2letter format refer to https://github.com/facebookresearch/wav2letter/issues/373

**Comment by tlikhomanenko** [comment]
> Thank you @lunixbochs .
> 
> No, my tokens.txt does not include numbers.
> I realized that I didn't replace repetition with numbers in the AM training.
> I will re-train my am and check it!

About token set. If you are training am with ASG you can have tokens set without numbers and then just use param rep_label. Then during training rep label will be processed automatically and your tokens set will be extended with numbers. In that case you should prepare your lm data for char lm training in the same format: preprocess the data to have numbers when you have repetitions of letters.

**Comment by hiroaki-ogawa** [comment]
Hi @tlikhomanenko ,

Thank you so much for your kind answers. They really hit the spot!!!

**Comment by loretoparisi** [comment]
@tlikhomanenko the link https://github.com/facebookresearch/wav2letter/blob/master/models/lexicon_free.md seems to be broken, models are somewhere else?

**Comment by tlikhomanenko** [comment]
@loretoparisi,

Thanks for pointing! Updated link is https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/lexicon_free/README.md. We have directory `recipes/models` where each paper has its own folder and models are published there.
