### ISSUE TITLE
speed perturbation mentioned in commit but missing

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#374]
https://github.com/facebookresearch/wav2letter/commit/a58e55ee91e43505218bfb0c5ed4d12589515a69

> - Implements speed perturbation which can be used as a data augmentation method in W2L.

**Comment by vineelpratap** [comment]
Hi, this is in our experimental folder and we haven't open sourced this yet. 

Just in case you are curious, we are using this library - http://www.mega-nerd.com/SRC/api_misc.html and the API `int src_simple (SRC_DATA *data, int converter_type, int channels) ;` to do the speed perturbation.
