### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by safarisadegh** [facebookresearch/wav2letter#378]
Hi, i have a dataset with mp3 files. unfortunately libsndfile does not support mp3. How i can train on my dataset using wav2letter?

**Comment by vineelpratap** [comment]
Hi,
You can convert the audio file to `flac` format using `sox` or `ffmpeg`. 
If that is not an option, you would have write a wrapper to load `mp3` files and get vector of float samples. Here is the code pointer where we load the audio file - https://git.io/fj9Qh
