### ISSUE TITLE
'decode' binary missing in Docker container

### ISSUE THREAD

**Issue by Eelis** [facebookresearch/wav2letter#383]
The [decoder documentation](https://github.com/facebookresearch/wav2letter/blob/master/docs/decoder.md) talks about a `decode` binary, but there is no such binary in the Docker container:

    ee@h:~ $ sudo docker run -it --rm wav2letter/wav2letter:cpu-latest
    root@38356b708da7:/# decode 
    bash: decode: command not found
    root@38356b708da7:/# find / -name decode
    root@38356b708da7:/# 

Any clues? :)

**Comment by tlikhomanenko** [comment]
The binary inside `build` folder of wav2letter (the same as without usage of docker image). The full path for the binary inside the docker image is `/root/wav2letter/build/Decoder`

**Comment by Eelis** [comment]
Sweet, thanks!
