### ISSUE TITLE
I got "Sample has NaN values" issue

### ISSUE THREAD

**Issue by nhha1602** [facebookresearch/wav2letter#386]
Hi all,

I tried to run as bellow cmd:
./Train train --flagsfile /home/wav2letter/wav2letter/tutorials/1-librispeech_clean/train.cfg
As the instruction of  this link: "https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean"

But i got "Sample has NaN values" and core dump.

wav2letter@wav2letter:~/wav2letter/build$ ./Train train --flagsfile /home/wav2letter/wav2letter/tutorials/1-librispeech_clean/train.cfg
F0827 23:37:31.375236 95819 Train.cpp:527] Sample has NaN values - train-clean-100-2843-152918-0013,train-clean-100-3807-4923-0021,train-clean-100-8123-275209-0029,train-clean-100-446-123502-0025
*** Check failure stack trace: ***
    @     0x7f822f2030cd  google::LogMessage::Fail()
    @     0x7f822f204f33  google::LogMessage::SendToLog()
    @     0x7f822f202c28  google::LogMessage::Flush()
    @     0x7f822f205999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55f28183b1a3  (unknown)
    @     0x55f2817cd893  (unknown)
    @     0x7f822e4e8b97  __libc_start_main
    @     0x55f28183647a  (unknown)
Aborted (core dumped)
wav2letter@wav2letter:~/wav2letter/build$

Could you, please help to show me how to solve it?

**Comment by nhha1602** [comment]
I tried to read train-clean-100.lst by pandas, and as below, there is no NaN value
================================================================
                               0  ...                                                  3
0  train-clean-100-103-1240-0000  ...  chapter one missus rachel lynde is surprised m...
1  train-clean-100-103-1240-0001  ...  that had its source away back in the woods of ...
2  train-clean-100-103-1240-0002  ...  for not even a brook could run past missus rac...
3  train-clean-100-103-1240-0003  ...  and that if she noticed anything odd or out of...
4  train-clean-100-103-1240-0004  ...  but missus rachel lynde was one of those capab...

[5 rows x 4 columns]
================================================================
(28222, 4)
================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28222 entries, 0 to 28221
Data columns (total 4 columns):
0    28222 non-null object
1    28222 non-null object
2    28222 non-null float64
3    28222 non-null object
dtypes: float64(1), object(3)
memory usage: 882.0+ KB
None

Out put of: df.isnull().sum()
================================================================
0    0
1    0
2    0
3    0
dtype: int64
================================================================

**Comment by zcy618** [comment]
hi I got the same error, could you help to tell me how did you resolve this issue please?
Thanks

**Comment by tlikhomanenko** [comment]
@zcy618,

seems here the problem could be with audio files itself. Could you check the audio files for which you have this error that they are not corrupted?

**Comment by tlikhomanenko** [comment]
close due to inactivity.
