### ISSUE TITLE
Lexicon-free LibriSpeech pretrained model link broken

### ISSUE THREAD

**Issue by nimz** [facebookresearch/wav2letter#387]
[The link to the pretrained model file (in recipes/models/lexicon_free/lexicon_free.md) appears to be broken.](https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/am/baseline_dev-clean+other.bin)

[In addition, the link to the lexicon for the TDS paper (in recipes/models/seq2seq_tds.md) is also broken.](https://dl.fbaipublicfiles.com/wav2letter/tds/librispeech/librispeech-train+dev-unigram-10000-nbest10.lexicon)

**Comment by rjcobain** [comment]
Replace the '+' with %2b
