### ISSUE TITLE
Why is beamsize such big

### ISSUE THREAD

**Issue by smolendawid** [facebookresearch/wav2letter#39]
I am looking for the motivation of why is beamsize such big. Isn't that making decoding too long, so that it cannot be used in production? What happens if beam size is much smaller?

**Comment by smolendawid** [comment]
In the paper, it is said that 
"The decoder runs over the clean and other sets in 3min56s and 30min5s, using only one
CPU thread – which (considering the decoder alone) corresponds to a .01 and 0.1 Real Time
Factor (RTF), respectively"
RTF was measured using the same beam size? (25000)

**Comment by VitaliyLi** [comment]
beamsize can be so big because beamscore is also implicitly limiting beam size. 25000 is really an upper limit (high watermark) because most candidates in the beam will be discarded.

**Comment by ColdEyeLampr** [comment]
Is the beamscore here identity to log probability? I noticed that beamscore is set to 40 by default. However, a simple calculation of exp(-40) gives a really small float, which makes me confused.

**Comment by VitaliyLi** [comment]
No, it is an un-normalized score.
