### ISSUE TITLE
How to use Pre-trained Model in Python binding？

### ISSUE THREAD

**Issue by wyh163** [facebookresearch/wav2letter#397]
I want to use python binding to do some research， but the README about that is too little.
And I'm sorry about that I don't understand how to import a Pre-trained Model in Python binding, can you tell me something about that? Thank you very much!

**Comment by tylercollins590** [comment]
I would love to see this as well.

**Comment by tylercollins590** [comment]
@wyh163 I've figured it out.. It was a pain and the instructions were not clear at all. Feel free to email me at tylercollins590@gmail.com and I will happily help you work through it

**Comment by maltium** [comment]
I'm having the same issue. Specifically how do you go from the features to the emissions. Surely the model.bin file has to be loaded somehow. Would be grateful if someone summarizes the solution.

**Comment by samehraban** [comment]
@tylercollins590 Can you please post the solution here so everybody could use the python binding for decode?

**Comment by tylercollins590** [comment]
I’ve compiled this into a working docker. I will try to upload this in the
next week or so.

**Comment by maltium** [comment]
> I’ve compiled this into a working docker. I will try to upload this in the next week or so.

@tylercollins590 do you have any progress to share on this? Thank you.

**Comment by daanzu** [comment]
It would be great to have an example for generating the emission matrix from features in Python.

**Comment by mathieulallier807** [comment]
Any news on this?

**Comment by tlikhomanenko** [comment]
@mathieulallier807 what are your needs? Could you specify what functionality are you searching?
