### ISSUE TITLE
There is no prepare_librispeech_official_lm.py

### ISSUE THREAD

**Issue by seymacengizz** [facebookresearch/wav2letter#398]
When I prepare data and language model, I am getting an error like there is no prepare_librispeech_official_lm.py. 

So I cannot create 4-gram.bin file for decoding in the prepare.py file.
 **# Generating decoder/***
    cmd = [
        "python3 {}/../../scripts/prepare_librispeech_official_lm.py",
        "--dst {}",
        "--kenlm {}",
]

How can I generate 4-gram.bin file?

**Comment by tlikhomanenko** [comment]
Hi @seymacengizz,

Thanks for pointing this! Will send the fix shortly.

**Comment by tlikhomanenko** [comment]
Fixed in the c19600fba4e55b98aa9ab82e5c375ac6545e49e6. Please pull and rerun `prepare.py` script.
