### ISSUE TITLE
test.lua > Running Pre-trained Model on CPU only

### ISSUE THREAD

**Issue by JesseVent** [facebookresearch/wav2letter#4]
### Issue Description
I keep getting an error when attempting to run test.lua via CPU while using the pre-trained model. I've attempted modifying the test script to suit my system and remove dependencies on GPU/CUDA.

Is there something additional I need to do to be able to avoid any CUDA dependencies at this point?

### System Specs
Model: iMac Late 2015 Retina 5K
CPU: 3.2 GHz Intel Core i5
RAM: 32 GB 1867 MHz DDR3
Software: Mac OS X 10.13.2 running Intel MKI
Fresh Torch install
AMD GPU with no CUDA/cuDNN support

### Fixes Attempted
I've changed all references to in wav2letter to torch.FloatTensor which should be the CPU equivalent, but still getting the error returned.

I did also comment out require cunn and cudnn dependencies and set gpu command to default of zero.
`cmd:option('-gpu', 0, 'gpu device')
`
### Code Output
    luajit ./test.lua ./librispeech-glu-highdropout.bin -progress -show -test dev-clean -save -datadir ./librispeech-proc/ -dictdir ./librispeech-proc/

```
| number of classes (network) = 30
| reloading model <./librispeech-glu-highdropout.bin>
luajit: ...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
	[C]: in function 'error'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/macbookpro/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/macbookpro/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	...rs/macbookpro/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...orch/install/share/lua/5.1/wav2letter/runtime/serial.lua:57: in function 'loadmodel'
	./test.lua:97: in main chunk
	[C]: at 0x010b5bbea0

```

**Comment by VitaliyLi** [comment]
Unfortunately, you cannot run GPU-trained models on CPU. We are working on converting the uploaded model to CPU-tensors and will soon upload it.

**Comment by soswow** [comment]
@VitaliyLi If this is the case, why not keep this issue open and close it when you upload CPU-trained model?
Also, it would be beneficial to add this info to the readme. I've spent all this time setting up everything with the goal to try this pre-trained model on my CPU and ... =(

**Comment by saisrinivas047** [comment]
@JesseVent @VitaliyLi @soswow can you please tell me how did you get the librispeech-proc folder ? I installed all the dependencies but di not find any librispeech-proc folder in my system.

PS- I am running pretained model in CPU

**Comment by soswow** [comment]
I don't have it either. So it's another question to maintainers.

**Comment by JesseVent** [comment]
@saisrinivas047 @soswow 
The librispeech-proc folder got created as the output directory when you run the script to preprocess the data files.

## Preprocessing ~/Librispeech files
```
wget http://www.openslr.org/resources/12/dev-clean.tar.gz
tar xfvz dev-clean.tar.gz
# repeat for train-clean-100, train-clean-360, train-other-500, dev-other, test-clean, test-other
luajit ~/wav2letter/data/librispeech/create.lua ~/LibriSpeech ~/librispeech-proc
luajit ~/wav2letter/data/utils/create-sz.lua librispeech-proc/train-clean-100 librispeech-proc/train-clean-360 librispeech-proc/train-other-500 librispeech-proc/dev-clean librispeech-proc/dev-other librispeech-proc/test-clean librispeech-proc/test-other
```

The `~/wav2letter/data/librispeech/create.lua` script requires having all the the files the instructions say to repeat for.. I only downloaded test-clean, test-other, dev-clean, dev-other and to get around the requirement for the other files I just made changes to `~/wav2letter/data/librispeech/create.lua` as per below.

## Commenting out files to ignore them for preprocessing
```
assert(#arg == 2, string.format('usage: %s <src dir> <dst dir>', arg[0]))
-- This is setting up your input folder for preprocessing to be ~/LibriSpeech
local src = arg[1]
-- This is creating your output folder for the preprocessed files to be ~/librispeech-proc
local dst = arg[2]

local subpaths = {
  -- **COMMENT THE FILES YOU DON'T HAVE OUT**
   --'train-clean-100', 'train-clean-360', 'train-other-500',
   'dev-clean', 'dev-other',
   'test-clean', 'test-other'
}

```

Hope that helps you with the folder

**Comment by soswow** [comment]
@JesseVent yeah. I've figured that out already. I wasn't prepared to download so much stuff, though. When I finish with all that and finally make it functional, I will create a list of things (maybe in a form of PR) that are missing from README. For instance, there are a bunch of dependencies that are not explicitly stated, but missing out on clean Ubuntu, for example. + other things.

**Comment by JesseVent** [comment]
Yeah I had a nightmare trying to get boost and KenLM working on MacOS. Cant even manage to get them working on Ubuntu though
