### ISSUE TITLE
Possible to get Timestamps?

### ISSUE THREAD

**Issue by tylercollins590** [facebookresearch/wav2letter#400]
Is it possible to get timestamps from the decoder of each word?

**Comment by tlikhomanenko** [comment]
Hi @tylercollins590, 

Could you provide more details what do what to get from decoder? Any example will be helpful.

**Comment by xuqiantong** [comment]
@tylercollins590, it is!
https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L450-L451
The raw token and word sequences return by decoder is aligned per frame, so we did some post-process before computing WER and LER. However you can parse them manually to get the begin and end time for each word. 

Note that the sequences are aligned to the output frames of the acoustic model. So, when computing actual timestamps, don't forget to consider:
1) The stride of your model in the time dimension.
2) MFSC/MFCC feature window.

**Comment by Jellyrick** [comment]
@xuqiantong 
how to  get word timestamp when use Test.cpp (Seq2SeqCriterion viterbiPath?)
thanks!

**Comment by webbp** [comment]
> https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L450-L451
Those line numbers are no longer relevant in the latest version of Decode.cpp. If I understand correctly, the relevant code you had linked to was:
```
        auto& rawWordPrediction = results[0].words;
        auto& rawTokenPrediction = results[0].tokens;

```
