### ISSUE TITLE
Please update docker image on DockerHub

### ISSUE THREAD

**Issue by Jevin754** [facebookresearch/wav2letter#402]
Hi, I am going to use the python bindings in my research. I try to build the dockerfile with W2L_BUILD_FOR_PYTHON=ON, but failed.
Could you please update the image with python bindings on DockerHub?
Thanks a lot!

**Comment by tlikhomanenko** [comment]
Hi @Jevin754,

The images with latest versions for CPU and CUDA backend are uploaded. Also the image with CUDA backend also has python bindings installed. 

Feel free to reopen if you will have any issue with them.
