### ISSUE TITLE
WebAssembly Support

### ISSUE THREAD

**Issue by pshah123** [facebookresearch/wav2letter#403]
I'm wondering if there are any plans to port wav2letter++ to WebAssembly?

I think this project would have very far-reaching effects if used at scale on the web -- i.e. enabling any web application to access quality speech recognition with ease.

**Comment by lunixbochs** [comment]
I wouldn't recommend porting wav2letter directly - including dependencies, I end up with over 100mb of binaries. You could hand-build an inference-only frontend by just reimplementing featurization and convolution, and the decoder can be extracted standalone.

**Comment by vineelpratap** [comment]
As mentioned above, it is not currently supported or we have plans to do this in our timeline.

However, we are actively working on providing API for real-time inference pipeline with minimal dependencies to easily plugin to any interface needed. Our goal is to have this ready in a few months.
