### ISSUE TITLE
Active Speech Recognition

### ISSUE THREAD

**Issue by Technerder** [facebookresearch/wav2letter#406]
Does this project provide an easy way to actively transcribe live microphone audio?

**Comment by vineelpratap** [comment]
Hi,
  Someone from our community have worked on this. Please take a look here - https://github.com/facebookresearch/wav2letter/issues/327

We are also actively working on providing API for real-time inference pipeline. We also release models trained on public datasets for the same. Our goal is to have this ready in a few months.

**Comment by jacobkahn** [comment]
See [inference framework docs](https://github.com/facebookresearch/wav2letter/wiki/Inference-Framework) for a place to start!
