### ISSUE TITLE
convert own audio files into wav2letter audio format 

### ISSUE THREAD

**Issue by saisrinivas047** [facebookresearch/wav2letter#41]
I am trying to use pre-trained model to transcribe my own audio files. but when I am doing that I am getting this error 
"inconsistent tensor size, expected tensor [24 x 24] and src [30 x 30] to have the same number of elements, but got 576 and 900 elements respectively at /tmp/luarocks_torch-scm-1-5171/torch7/lib/TH/generic/THTensorCopy.c:86"

did the facebook guys provided any info about how to convert our audio files into their format ?

ps: I am using .flac files

**Comment by ambigus9** [comment]
@saisrinivas047 Any progress? I'm trying to use a pre-trained model to transcribe my own audio files as same as you.
