### ISSUE TITLE
tutorial lr and lrcriterion

### ISSUE THREAD

**Issue by zdgithub** [facebookresearch/wav2letter#412]
Why the learning rate of tutorial/librispeech-clean dataset keeps unchanged and the lrcriterion is 0 ?

Could it get a relatively good result with fixed lr=0.1 and lrcriterion=0 after 25 epoch as the train.cfg ?

**Comment by an918tw** [comment]
The tutorial uses CTC criterion, and thus we can set lr only. The purpose of the tutorial is to guide users to run an experiment end-to-end, and the results wouldn't be state-of-the-art. Users can definitely play with different learning rate schedules to see how they affect the training. Can you share back if you're seeing different results by following the exact scripts in the tutorial?

 Can you share if you're getting

**Comment by zdgithub** [comment]
Thank you very much!
I'm trying using the config in the tutorial to train my own data on just one Tesla K40, so I'm sorry to say that I didn't reproduce the result of the tutorial. If I do that I'm glad to share it
