### ISSUE TITLE
DecoderTest failing after rebuilding KenLM with MAX_ORDER=20

### ISSUE THREAD

**Issue by nikhildes** [facebookresearch/wav2letter#413]
I am using the latest docker container version of wav2letter, and attempting to use the KenLM token decoder with the provided token LM (lm_librispeech_kenlm_char_15g_pruned.bin) 

However, it appears that the base container referenced in Dockerfile-CUDA has KenLM compiled with MAX_ORDER=6, not MAX_ORDER=20, so decoding fails. 

```terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  /root/kenlm/lm/model.cc:49 in void lm::ngram::detail::{anonymous}::CheckCounts(const std::vector<long unsigned int>&) threw FormatLoadException because `counts.size() > 6'.
This model has order 15 but KenLM was compiled to support up to 6.
```

While inside the container, I deleted kenlm folder and rebuilt kenlm from scratch with KENLM_MAX_ORDER=20. I then deleted /wav2letter/build, set `KENLM_ROOT_DIR` and rebuilt wav2letter.  

When I run `make test` all tests pass except DecoderTest, which throws a segfault

```
root@f197888e04fd:~/wav2letter/build# ./src/tests/DecoderTest 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DecoderTest
[ RUN      ] DecoderTest.run
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0926 20:58:56.980756 19326 DecoderTest.cpp:93] [Serialization] Loaded emissions [235 x 29]
I0926 20:58:57.042776 19326 DecoderTest.cpp:101] [Dictionary] Number of words: 26710
Loading the LM will be faster if you build a binary file.
Reading /root/wav2letter/src/decoder/test/lm.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
I0926 20:58:57.092444 19326 DecoderTest.cpp:106] [Decoder] LM constructed.
Segmentation fault (core dumped)
``` 

1. Is there a way to see log output from the DecoderTest binary? 
2. Am I missing some step to link kenlm to wav2letter? I am no longer getting the max order error I was getting previously. Instead I get this error: 

``` 
I0926 21:19:13.377246 19330 Decode.cpp:308] [Decoder] LM constructed.
*** Aborted at 1569532753 (unix time) try "date -d @1569532753" if you are using GNU date ***
PC: @     0x7f8378be0a4c opal_memory_ptmalloc2_int_malloc
*** SIGSEGV (@0x0) received by PID 19330 (TID 0x7f83db346600) from PID 0; stack trace: ***
    @     0x7f83d364c390 (unknown)
    @     0x7f8378be0a4c opal_memory_ptmalloc2_int_malloc
    @     0x7f8378be16bc opal_memory_ptmalloc2_malloc
    @     0x7f8391a16e78 operator new()
    @           0x51557e _ZNSt6vectorIiSaIiEE19_M_emplace_back_auxIJiEEEvDpOT_
    @           0x5188af w2l::packReplabels()
    @           0x518acb w2l::tkn2Idx()
    @           0x41b0c8 main
    @     0x7f83910c0830 __libc_start_main
    @           0x47b839 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

3. Could you please change the base container so that kenlm is compiled with KENLM_MAX_ORDER=20?

**Comment by tlikhomanenko** [comment]
Hi @nikhildes,

You can have a look to the https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/lexicon_free/Dockerfile to be sure you recompiled kenlm and wav2letter correctly with max order 20. Looking at your error it seems that you didn't run cmake with `-DKENLM_MAX_ORDER=20` for wav2letter.

Could you try to redo steps (for kenlm and wav2letter) as listed in the https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/lexicon_free/Dockerfile?

We are not planning to change base container to have `KENLM_MAX_ORDER=20` right now (need to test efficiency in case of usage 3-6 gram models for that compilation: there are memory allocations, etc. which defined by this variable during compilation).

**Comment by samehraban** [comment]
I'm facing same error while decoding:

```
*** Aborted at 1571852024 (unix time) try "date -d @1571852024" if you are using GNU date ***
PC: @     0x7f790ca0fa4c opal_memory_ptmalloc2_int_malloc
*** SIGSEGV (@0x0) received by PID 48241 (TID 0x7f79552a7600) from PID 0; stack trace: ***
    @     0x7f794d5bf390 (unknown)
    @     0x7f790ca0fa4c opal_memory_ptmalloc2_int_malloc
    @     0x7f790ca106bc opal_memory_ptmalloc2_malloc
    @     0x7f7926f8ce78 operator new()
    @           0x549168 w2l::KenLM::score()
    @           0x41b5ae main
    @     0x7f7926636830 __libc_start_main
    @           0x4834e9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

Any idea what did cause this error? (I'm not working on docker. )

**Comment by tlikhomanenko** [comment]
Hi @samehraban,

Seems you didn't compile kenlm and wav2letter correctly for higher orders. See my above comment what you could try. Also you could try to use directly `wav2letter/wav2letter:lexfree` docker image.

**Comment by tlikhomanenko** [comment]
@samehraban 

did you solve the issue? 

Closing for now. Feel free to reopen!
