### ISSUE TITLE
Decoding : same accoustic model works very well on one test data and way worse with other test data

### ISSUE THREAD

**Issue by shburra** [facebookresearch/wav2letter#415]
Hi all,

I trained a Spanish model with 25GB data (not sure if it is enough). I divided my data into 'train', 'dev' and 'test'. Trained the model on 'train' and 'dev' (for validation). Decoded on 'test'. The model performed very well on this test data
with below settings
--lmweight=2.50
--wordscore=1
--beamsize=480
--beamscore=25
--silweight=-0.170
--nthread=1
--nthread_decoder=8
--smearing=max
--show

[Decode wav2letter/tutorials/output_26/data/test-clean (113 samples) in 10.1193s (actual decoding time 0.609s/sample) -- **WER: 8.2906**, LER: 17.7358]

Just to make sure, I prepared new Spanish data and decoded using the same model and parameter settings
This time the performance was very low
[Decode wav2letter/tutorials/output_alugha/data/test-clean (56 samples) in 50.6901s (actual decoding time 6.95s/sample) -- **WER: 98.4704**, LER: 91.2452]

I am not sure if the model is overfitting as both the test sets are new to the model.
Can anyone give me a clue why this might have happened and what can be done?

Thanks in advance for your inputs and insights,
Haritha

**Comment by juanpablogd** [comment]
Hola!, me puedes enseñar a entrenar un modelo en español por favor, si quieres podemos trabajar conjuntamente, cordial saludo

**Comment by tlikhomanenko** [comment]
Either you have problem in the settings, so I would check first the test.cpp to see how AM performs itself without language model.
