### ISSUE TITLE
relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#420]
While running the make command, I am getting the following error: 

[ 86%] Building CXX object src/tests/CMakeFiles/DerivativesTest.dir/__/libraries/decoder/LexiconDecoder.cpp.o
[ 86%] Building CXX object src/tests/CMakeFiles/DctTest.dir/__/libraries/decoder/Seq2SeqDecoder.cpp.o
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/Serialize.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/Utils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/common/Dictionary.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/common/Utils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/common/WordUtils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/criterion/cpu/ForceAlignmentCriterion.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/criterion/cpu/FullConnectionCriterion.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/criterion/cpu/ViterbiPath.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/decoder/LexiconDecoder.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/decoder/LexiconFreeDecoder.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/decoder/Seq2SeqDecoder.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/decoder/TokenLMDecoder.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/decoder/Trie.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/decoder/WordLMDecoder.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/lm/KenLM.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l5KenLME' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/lm/ConvLM.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l6ConvLME' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/lm/ZeroLM.cpp.o: relocation R_X86_64_32S against symbol `_ZTVSt23_Sp_counted_ptr_inplaceIN3w2l11ZeroLMStateESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Ceplifter.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Dct.cpp.o: relocation R_X86_64_32S against `.rodata.cst8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Derivatives.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Dither.cpp.o: relocation R_X86_64_32S against `.rodata.cst4' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Mfcc.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l4MfccIfEE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Mfsc.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l4MfscIfEE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/PowerSpectrum.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/PreEmphasis.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/SpeechUtils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/TriFilterbank.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/libraries/feature/Windowing.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/common/Defines.cpp.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/common/FlashlightUtils.cpp.o: relocation R_X86_64_32 against symbol `vsnprintf@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/common/Utils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/backend/cuda/ConnectionistTemporalClassificationCriterion.cpp.o: relocation R_X86_64_32 against symbol `_ZN2af4spanE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/backend/cuda/CriterionUtils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/backend/cuda/ForceAlignmentCriterion.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/backend/cuda/FullConnectionCriterion.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l44ConnectionistTemporalClassificationCriterionE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/CriterionUtils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/ForceAlignmentCriterion.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l23ForceAlignmentCriterionE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/Seq2SeqCriterion.cpp.o: relocation R_X86_64_32S against symbol `_ZTVSt23_Sp_counted_ptr_inplaceIN3w2l23NeuralLocationAttentionESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/FullConnectionCriterion.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l23FullConnectionCriterionE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/attention/ContentAttention.cpp.o: relocation R_X86_64_32 against symbol `_ZN2af4spanE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/attention/LocationAttention.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l23SimpleLocationAttentionE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/attention/MedianWindow.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l12MedianWindowE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/attention/SoftPretrainWindow.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l18SoftPretrainWindowE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/attention/SoftWindow.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l10SoftWindowE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/criterion/attention/StepWindow.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l10StepWindowE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/Featurize.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/ListFileDataset.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l15ListFileDatasetE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/Utils.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/W2lDataset.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l10W2lDatasetE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/W2lBlobsDataset.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l15W2lBlobsDatasetE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/data/W2lListFilesDataset.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l19W2lListFilesDatasetE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/module/ConvLmModule.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/module/SpecAugment.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l11SpecAugmentE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/module/TDSBlock.cpp.o: relocation R_X86_64_32S against symbol `_ZTVN3w2l8TDSBlockE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/module/W2lModule.cpp.o: relocation R_X86_64_32S against symbol `_ZTVSt23_Sp_counted_ptr_inplaceIN2fl10SequentialESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/Data.cpp.o: relocation R_X86_64_32S against symbol `_ZTVSt23_Sp_counted_ptr_inplaceIN3w2l15W2lBlobsDatasetESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/Logger.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/Serial.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/SpeechStatMeter.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/Distributed.cpp.o: relocation R_X86_64_32 against symbol `vsnprintf@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/Optimizer.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/SerializeConvLM.dir/__/__/__/__/src/runtime/Helpers.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
recipes/models/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/build.make:1100: recipe for target 'recipes/models/utilities/convlm_serializer/SerializeConvLM' failed
make[2]: *** [recipes/models/utilities/convlm_serializer/SerializeConvLM] Error 1
CMakeFiles/Makefile2:1472: recipe for target 'recipes/models/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/all' failed
make[1]: *** [recipes/models/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 86%] Building CXX object src/tests/CMakeFiles/DerivativesTest.dir/__/libraries/decoder/LexiconFreeDecoder.cpp.o
[ 86%] Building CXX object src/tests/CMakeFiles/DerivativesTest.dir/__/libraries/decoder/Seq2SeqDecoder.cpp.o

**Comment by lunixbochs** [comment]
try adding `add_definitions(-fPIC)` to the topmost CMakeLists.txt

**Comment by jacobkahn** [comment]
@samin9796 — just curious - what's your platform where you're seeing this issue with `pthread` symbols?
