### ISSUE TITLE
Shuffled result during decoding

### ISSUE THREAD

**Issue by nestyme** [facebookresearch/wav2letter#421]
Hello! 
During decoding I am using *.lst file with filenames and I want to get result in the same order as lines in *.lst. But it shuffling in some random way. How deal with It?
Many thanks!

**Comment by vineelpratap** [comment]
Hi, 
 List file dataset orders the list by the third column - https://git.io/Je80L . If you want in the same order as tour list files dataset, you would have to do these two steps.

1. Create your list files dataset such that the third column is ordered, for example

train001 /tmp/000000000.flac **0**  this is sparta
train002 /tmp/000000001.flac **1**  coca cola
train003 /tmp/000000002.flac **2**  hello world
train004 /tmp/000000003.flac **3**  quick brown fox jumped

2. Remove `ds->shuffle(3)` in https://git.io/Je80G
