### ISSUE TITLE
Question about shuffling in Decode.cpp

### ISSUE THREAD

**Issue by nestyme** [facebookresearch/wav2letter#422]
I have a question about shuffling in Decoder.cpp after loading dataset. Could you please explain me the purpose of It? Thanks!
https://github.com/facebookresearch/wav2letter/blob/a66c213163d772a2a9444d041c39c6b03803468c/Decode.cpp#L153

**Comment by vineelpratap** [comment]
ListFileDataset orders the dataset by third column which is supposed to contain the size of the audio. This is done for efficient batching of sample for distributed training. 
But, for multi-threaded decoding, this will end up distributing the samples in such a way that the avg. size of sample won't be similar across threads - https://git.io/Je80R . 

We shuffle the dataset to avoid this bias.
