### ISSUE TITLE
Not able to access decoder directory in lexicon-free docker image

### ISSUE THREAD

**Issue by Harshitmalhotra12** [facebookresearch/wav2letter#427]
![Screenshot from 2019-10-16 12-53-01](https://user-images.githubusercontent.com/46706500/66897125-f52e2e00-f013-11e9-8458-25e55c9057fa.png)

**Comment by Harshitmalhotra12** [comment]
It is a green executable file in build folder of wav2letter instead of a directory for Decoder ,Train and Test.
what  can i do to get those directories ?

**Comment by tlikhomanenko** [comment]
Hi @Harshitmalhotra12,

I am not clear what folder you need. For me build dir looks correctly (`Decoder` is a binary to run beam-search decoding). If you need to get access to the folder `decoder/*` with files on lm and lexicons there are generated by the code of the recipe inside `recipes/models/lexicon_free/liobrispeech/decoder/*` and `recipes/models/lexicon_free/wsj/decoder/*` for each dataset.

**Comment by Harshitmalhotra12** [comment]
Thank you @tlikhomanenko  , i figured out that ,i made a dumb rookie error here.
Sorry for bothering you.
