### ISSUE TITLE
PSA: new models, mixed english/command recognition, desktop app

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#428]
This is a short update on the work I've been doing with wav2letter and Talon (for most of this year!)

I've updated my C API (referenced here https://github.com/facebookresearch/wav2letter/issues/326), in the [talonvoice/wav2letter/decoder](https://github.com/talonvoice/wav2letter/tree/decoder) branch.

It now supports command graph decoding with mixed English and commands via a DFA. Sorry, haven't spent time on docs for this, as my main goal is getting the Talon app release out. See the new header: [w2l.h](https://github.com/talonvoice/wav2letter/blob/decoder/w2l.h) and take a look at the decoder source if you'd like to know more.

I've trained dozens of new models, found/created more data to train on (>3k hours of audio), and run many experiments on model size and performance. I'm now focusing on the 77MB wsjarch model for the time/accuracy tradeoff, but honestly the accuracy feels pretty good when using it. I've uploaded several of my experimental models here: https://talonvoice.com/research/

I'm very excited about this part. My main project, [Talon](https://talonvoice.com), now has support in the Mac/Linux private betas for using wav2letter as a speech recognition engine for realtime desktop control and dictation. It works pretty well! I hope to release this soonish into the free public version of Talon once it's more polished.

Thanks so much to the Facebook research team for doing this work and open-sourcing it. I'm getting so much better acoustic model performance/accuracy with wav2letter than DeepSpeech and _every other_ free engine I've tried, and I've found it way easier to understand, train, and extend than Kaldi.

See my Talon update post on Patreon for some more information about the Talon integration, and please support me on Patreon if my published models or work is helpful or interesting to you: https://www.patreon.com/posts/october-update-30805594

**Comment by lunixbochs** [comment]
I made a little web demo too: https://web2letter-west-1.talonvoice.com/

**Comment by ORlGlN** [comment]
Hi there, really appreciate your works on wav2letter and Talon!
I have some questions regarding how to run offline inference using the model you provided, specifically this model (https://talonvoice.com/research/e127-specaug-cb5_89-cv12_63-lsc3_00-lso9_28-sc2_16-tal9_41-tat0_45-ted8_42-tts2_12.bin) together with this lm (https://talonvoice.com/research/enwiki-4gram-2019-04.tar.gz).
Would you mind to shed some light on the queries below:
- Is there any info missing such as the decoder options, model architecture, lexicons, features.bin?
- How to use this model to do inference offline?
- Which branch of your repo should i use for this particular model?

Thanks in advance.
