### ISSUE TITLE
kenlm library not found

### ISSUE THREAD

**Issue by Azatalion** [facebookresearch/wav2letter#429]
I built kenlm and set KENLM_ROOT_DIR to kenlm's directory.
But when I'm trying to build wav2letter, I get such output:

-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcuda)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- OpenMP found
-- flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- flashlight built with contrib features.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Includes found
-- Checking for [openblas]
-- Includes found
-- CBLAS Symbols FOUND
-- CBLAS library found
-- CBLAS found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libopenblas.so)
-- FFTW found
-- Looking for KenLM
CMake Error at cmake/Findkenlm.cmake:47 (message):
  kenlm library not found; please set CMAKE_LIBRARY_PATH or KENLM_LIB
Call Stack (most recent call first):
  src/libraries/lm/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!

This is CMakeErrog.Log:

Determining if the pthread_create exist failed with the following output:
Change Dir: /mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_609c0/fast"
/usr/bin/make -f CMakeFiles/cmTC_609c0.dir/build.make CMakeFiles/cmTC_609c0.dir/build
make[1]: Entering directory '/mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_609c0.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC    -o CMakeFiles/cmTC_609c0.dir/CheckSymbolExists.c.o   -c /mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_609c0
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_609c0.dir/link.txt --verbose=1
/usr/bin/cc -fPIC      CMakeFiles/cmTC_609c0.dir/CheckSymbolExists.c.o  -o cmTC_609c0 
CMakeFiles/cmTC_609c0.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_609c0.dir/build.make:97: recipe for target 'cmTC_609c0' failed
make[1]: *** [cmTC_609c0] Error 1
make[1]: Leaving directory '/mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_609c0/fast' failed
make: *** [cmTC_609c0/fast] Error 2

File /mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6bd88/fast"
/usr/bin/make -f CMakeFiles/cmTC_6bd88.dir/build.make CMakeFiles/cmTC_6bd88.dir/build
make[1]: Entering directory '/mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6bd88.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_6bd88.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_6bd88
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6bd88.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create     CMakeFiles/cmTC_6bd88.dir/CheckFunctionExists.c.o  -o cmTC_6bd88 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_6bd88.dir/build.make:97: recipe for target 'cmTC_6bd88' failed
make[1]: *** [cmTC_6bd88] Error 1
make[1]: Leaving directory '/mnt/data/repositories/src/wav2letter/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_6bd88/fast' failed
make: *** [cmTC_6bd88/fast] Error 2

**Comment by jacobkahn** [comment]
@Azatalion — this seems like an issue with CMake finding pthread. I'd also make sure you pass `-DKENLM_LIB=<path>` to CMake with the correct directory containing the KenLM libraries.

**Comment by tlikhomanenko** [comment]
@Azatalion 

did you solve the issue?

Closing for now, feel free to reopen!
