### ISSUE TITLE
WER much higher than TER

### ISSUE THREAD

**Issue by zdgithub** [facebookresearch/wav2letter#430]
I have tried to reproduce the conv_glu recipe just with librispeech train-clean-100 as the trainset. The loss converged after 30 epochs(Note that I have decayed lr in training) , I got the following result:
```
epoch:       30 | lr: 0.020000 | lrcriterion: 0.000200 | runtime: 01:05:03 | bch(ms): 1640.64 | smp(ms): 1.92 | fwd(ms): 428.45 | crit-fwd(ms): 14.09 | bwd(ms): 1162.79 | optim(ms): 28.02 | loss:    6.00383 | train-TER: 14.90 | train-WER: 40.44 | dev-clean-loss:    4.36503 | dev-clean-TER: 14.61 | dev-clean-WER: 38.93 | avg-isz: 1267 | avg-tsz: 213 | max-tsz: 376 | hrs:  100.51 | thrpt(sec/sec): 92.71
```
While the TER is below 15%, the WER is about 40% which is much higher than TER. 
I'm confused about the result becasue your paper shows that the difference between WER and TER won't be so big.

**Comment by lunixbochs** [comment]
You trained a network with much less data. The expected TER is in the 2.5% range if you train their 1.6GB model on the full 960 hours.

The WER you're seeing here during training isn't using a language model, the WER in the whitepaper is. You need to run the Decoder to get a language model based WER.

The WER can be much higher than the TER for multiple reasons.

In this example, there's one token (the word spacer) missing for around 9% token error rate, but as a result 50% of the words are wrong.
```
1: hello|world
2: helloworld
```

**Comment by zdgithub** [comment]
> You trained a network with much less data. The expected TER is in the 2.5% range if you train their 1.6GB model on the full 960 hours.
> 
> The WER you're seeing here during training isn't using a language model, the WER in the whitepaper is. You need to run the Decoder to get a language model based WER.
> 
> The WER can be much higher than the TER for multiple reasons.
> 
> In this rough example, there's one token (the word spacer) missing for around 9% token error rate, but as a result 100% of the words are wrong.
> 
> ```
> 1: hello|world
> 2: helloworld
> ```
> 
> Take a look at my trained models for an example of some of the TERs you should see: https://talonvoice.com/research/

Thank you very much.
