### ISSUE TITLE
Suggestion: Make a symlink called "wav2letter" to "src"

### ISSUE THREAD

**Issue by galv** [facebookresearch/wav2letter#434]
A problem with integrating wav2letter into other projects is that you have to write includes like this:

`#include "runtime/Serial.h"`

instead of `#include "wav2letter/runtime/Serial.h"`

This is a tricky problem, and kaldi has it too, but an easy workaround is to add a symlink named "wav2letter" in the top-level directory, which points to "src". Then you can change this:

```
target_include_directories(
  wav2letter++
  PUBLIC
  ${PROJECT_SOURCE_DIR}/src # all includes are based at src/
  ${FLASHLIGHT_INCLUDE_DIRS} # includes are <flashlight/...>
  )
```

https://github.com/facebookresearch/wav2letter/blob/a66c213163d772a2a9444d041c39c6b03803468c/CMakeLists.txt#L183

to this:

```
target_include_directories(
  wav2letter++
  PUBLIC
  ${PROJECT_SOURCE_DIR}/src # all includes are based at src/
  ${FLASHLIGHT_INCLUDE_DIRS} # includes are <flashlight/...>
  ${PROJECT_SOURCE_DIR} # for projects including wav2letter
  )
```

 That can be a little bit odd with windows, but there is no windows support for wav2letter anyway.

**Comment by jacobkahn** [comment]
@galv — we've moved the wav2letter codebase to [flashlight](https://github.com/facebookresearch/flashlight); now we're focused on making flashlight ASR components installable (they already are, with better include paths). Thanks for the suggestion.
