### ISSUE TITLE
Python bindings to use acoustic model?

### ISSUE THREAD

**Issue by samehraban** [facebookresearch/wav2letter#439]
Is there any way to use trained acoustic model with python? I didn't find anything in docs and there is only `WordLMDecode` in `decoder` package. So I suppose most of decoding stuff like using am to produce emissions or decoding without lexicons or with token lm is not yet have python bindings?

**Comment by jacobkahn** [comment]
@samehraban — we don't have plans to add Python bindings for flashlight, so training AMs in wav2letter through flashlight isn't going to be possible. There are Python bindings for the decoder, however, so you can train an AM in PyTorch and also decode in Python.
