### ISSUE TITLE
Links to pre-trained models are broken

### ISSUE THREAD

**Issue by chrisspen** [facebookresearch/wav2letter#446]
None of the wget commands to download the pretrained models work. They all return the error "The specified bucket does not exist".

**Comment by tlikhomanenko** [comment]
Hi @chrisspen,

Which models are you trying to download? If models inside `recipes/models` it works for me, for example
![Screen Shot 2019-11-21 at 2 34 28 PM](https://user-images.githubusercontent.com/7202615/69382526-535fc800-0cc8-11ea-89dd-cc08cf5e2d09.png)
