### ISSUE TITLE
How to train with wav2vec embeddings?

### ISSUE THREAD

**Issue by pkumarsatish** [facebookresearch/wav2letter#448]
To train wav2letter++ with wav2vec embedding, I generated hdf5 feature files using fairseq wav2vec_featurize.py script. The script says these hdf5 files are in wav2letter++ compatible format. However, I don't see any wav2letter++ support to load features from these files. I am not sure about implications of simply modifying Featurize.cpp to load data directly into inFeat variable (https://git.io/fjv28). 

Please let me know how can I train wav2letter++ with these embedding. Any help would be much appreciated.

**Comment by jacobkahn** [comment]
@pkumarsatish — we won't be supporting hdf5 formats in the near future, but others have built nice ways to load those embeddings: https://github.com/facebookresearch/wav2letter/issues/436#issuecomment-559038575, cc @maltium
