### ISSUE TITLE
Error: Out of Memory

### ISSUE THREAD

**Issue by pvn25** [facebookresearch/wav2letter#45]
I'm using the pre-trained "librispeech-glu-highdropout" model with GeForce GTX 960M GPU (2GB memory) and I'm getting this error:

| number of classes (network) = 30
| reloading model </home/vraj/librispeech-glu-highdropout.bin>
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6610/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
luajit: /home/vraj/usr/share/lua/5.1/nn/WeightNorm.lua:201: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-6610/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'new'
	/home/vraj/usr/share/lua/5.1/nn/WeightNorm.lua:201: in function 'read'
	/home/vraj/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/vraj/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/vraj/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/vraj/usr/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/home/vraj/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/vraj/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/vraj/usr/share/lua/5.1/wav2letter/runtime/serial.lua:57: in function 'loadmodel'
	/home/vraj/wav2letter/test.lua:104: in main chunk
	[C]: at 0x004057a0

Is there a way around this issue?

**Comment by VitaliyLi** [comment]
Are you running it on librispeech dataset, or your own audio file?

**Comment by pvn25** [comment]
I'm running on my own audio file (10 sec single audio file with 16000 sample rate).

**Comment by pvn25** [comment]
May I know how much GPU memory do I need to run the inference task?

**Comment by bolt163** [comment]
THCudaCheck FAIL file=/data1/usr/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
luajit: /data1/usr/torch/install/share/lua/5.1/nn/utils.lua:11: cuda runtime error (2) : out of memory at /data1/usr/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'resize'
	/data1/usr/torch/install/share/lua/5.1/nn/utils.lua:11: in function 'torch_Storage_type'
	/data1/usr/torch/install/share/lua/5.1/nn/utils.lua:57: in function 'recursiveType'
	...a1/usr/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'f'
	...ch/install/share/lua/5.1/wav2letter/runtime/netutils.lua:25: in function 'TemporalConvolution'
	...ch/install/share/lua/5.1/wav2letter/runtime/netutils.lua:209: in function 'create'
	/data1/wav2letter/train.lua:368: in main chunk
	[C]: at 0x004064f0

**Comment by VitaliyLi** [comment]
Hi @pvn25 ,

Sorry for the delay. How much memory you need depends on how long is the audio sequence you are transcribing. For librispeech sequences it's ~10 Gbs.

To workaround this issue you can try splitting your sequences into smaller chunks of 3-4 seconds each.

**Comment by tuanphan09** [comment]
@VitaliyLi I did as you said. I tried to split a long audio into smaller chunks, but the result was difference. More infor about the issue here #369
