### ISSUE TITLE
Using dockerfile to decode?

### ISSUE THREAD

**Issue by chrisspen** [facebookresearch/wav2letter#451]
Can the docker instructions listed [here](https://github.com/facebookresearch/wav2letter/blob/master/docs/installation.md) be used to decode a wav? I'm able to run the docker commands, but there's no further documentation on what to do with it. Is it only for running the tests or can it be used for decoding?

The command to run tests fails for me, with 2 failing. Namely the W2lModuleTest and Seq2SeqTest.

**Comment by tlikhomanenko** [comment]
Hi @chrisspen,

Docker instructions are listed to provide you correctly built environment in which you can run training and decoding binaries. 

You can follow any recipe here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models or use them as an example how to run decoding and training (inside a docker container the `wav2letter` folder will be in `~/wav2letter` and built binaries will be in `~/wav2letter/build/Decode.cpp` `~/wav2letter/build/Train.cpp` which you can use inside a docker container).

About the tests: please run these two tests separately and show me the log of them.

**Comment by chrisspen** [comment]
That page says to run `/wav2letter/build/Decode --flagsfile decode.cfg`, but the path `./wav2letter/build/Decode` does not exist. Was that supposed to be `./wav2letter/build/Decoder`? Even that command can't find the file `decode.cfg`.

Where is the test log? The console output doesn't list any details, other than a list of the test names that failed.

**Comment by chrisspen** [comment]
If I run `./wav2letter/build/Decoder --flagsfile wav2letter/tutorials/1-librispeech_clean/decode.cfg`, that fails with a core dump:

    root@f8dd6dde8b20:~# ./wav2letter/build/Decoder --flagsfile wav2letter/tutorials/1-librispeech_clean/decode.cfg
    E1201 17:42:08.482143   392 Serial.h:74] Error while loading: failed to open file for reading
    E1201 17:42:09.483325   392 Serial.h:74] Error while loading: failed to open file for reading
    E1201 17:42:11.483731   392 Serial.h:74] Error while loading: failed to open file for reading
    E1201 17:42:15.484139   392 Serial.h:74] Error while loading: failed to open file for reading
    E1201 17:42:23.484483   392 Serial.h:74] Error while loading: failed to open file for reading
    E1201 17:42:39.484802   392 Serial.h:74] Error while loading: failed to open file for reading
    terminate called after throwing an instance of 'std::runtime_error'
      what():  failed to open file for reading
    *** Aborted at 1575222159 (unix time) try "date -d @1575222159" if you are using GNU date ***
    PC: @     0x7f9674aff428 gsignal
    *** SIGABRT (@0x188) received by PID 392 (TID 0x7f967fec6bc0) from PID 392; stack trace: ***
        @     0x7f9675975390 (unknown)
        @     0x7f9674aff428 gsignal
        @     0x7f9674b0102a abort
        @     0x7f967544284d __gnu_cxx::__verbose_terminate_handler()
        @     0x7f96754406b6 (unknown)
        @     0x7f9675440701 std::terminate()
        @     0x7f9675440969 __cxa_rethrow
        @           0x48a508 w2l::retryWithBackoff<>()
        @           0x418100 main
        @     0x7f9674aea830 __libc_start_main
        @           0x47a749 _start
        @                0x0 (unknown)
    Aborted (core dumped)

**Comment by jacobkahn** [comment]
@chrisspen check the path to your serialized model. That's what's failing here.

**Comment by tlikhomanenko** [comment]
@chrisspen 

Inside docker container do `ls ~/wav2letter/build` and you should see `Decode` binary there. As flagsfile you should specify configuration file like you did for example `--flagsfile wav2letter/tutorials/1-librispeech_clean/decode.cfg`. 

To run with pre-trained model please have a look for example on the README.md https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/seq2seq_tds/librispeech and for instance for config https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/seq2seq_tds/librispeech/decode_ngram_clean.cfg you should fix the paths (`[...]`, `[DATA_DST]`, `[MODEL_DST]` with appropriate paths depending on where you downloaded model and lexicon) before running decoding command.

**Comment by tlikhomanenko** [comment]
@chrisspen 

Did you manage to run decoding inside docker?

Closing issue for now. Feel free to reopen!
