### ISSUE TITLE
Error while running ASG for my custom Dataset.

### ISSUE THREAD

**Issue by vaibhav0195** [facebookresearch/wav2letter#452]
Hi I built the python bindings for my computer and I was trying to use ASG criterion for my model.
It runs perfectly for some steps,but after the few steps its raising the error: 
```
RuntimeError: CUDA error: an illegal memory access was encountered
```

PS : this problem started when i used 
loss.backward(loss.data) ; where loss.data is the data produced by forward call of ASG criterion, instead of loss.backward(grad) ; where grad is the tensor containing only ones and has the shape equal to loss.data.

EDIT : the error occurs when i call the criterion forward method.

I am using CUDA 10.1 and pytorch 1.3
I have a nvidia RTX 2080Ti
Nvidia driver = 418
cudnn = 7.4.2
Any help is appreciated :)

**Comment by tlikhomanenko** [comment]
Hi @vaibhav0195,

did you solve the problem?

**Comment by vaibhav0195** [comment]
Hi @tlikhomanenko  yes I did. Ithere was some None value flowing around in my targets which caused the error.
