### ISSUE TITLE
How to incorporate laughter, noise, etc... in transcriptions?

### ISSUE THREAD

**Issue by mpierre0220** [facebookresearch/wav2letter#457]
The docs say that you can use L, N, etc in transcriptions to capture laughter, noise, etc...  However when I insert them Train complains that it does not recognize them, although I add them to the tokens file. Is there something else I should do?

**Comment by vineelpratap** [comment]
This is how we usually handle N, L tokens in the transcripts. 

Let's say you have some data with transcriptions like 
_the cat sat [noise] on mat_ 
_happy holidays [laughter]_

You need to have tokens file and lexicon file defined this way 
```
# tokens.txt 
|
a
b
c
..
..
z
N 
L
```

```
# lexicon.txt 
the t h e |
cat c a t |
happy h a p p y |
[noise] N |
[laughter] L |
```

**Comment by mpierre0220** [comment]
@
