### ISSUE TITLE
what():  loadSound: unknown format or could not open stream

### ISSUE THREAD

**Issue by kksiddharth** [facebookresearch/wav2letter#458]
Hi, I'm facing unknown format error when I try to train the acoustic model of the LibriSpeech Clean tutorial, the log when I run the following command :
**sudo wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train_test.cfg | tee train_log.log**
And the log is:
**_terminate called after throwing an instance of 'std::runtime_error'
  what():  loadSound: unknown format or could not open stream
*** Aborted at 1576348781 (unix time) try "date -d @1576348781" if you are using GNU date ***
PC: @     0x7f7065178e97 gsignal
*** SIGABRT (@0x38b3) received by PID 14515 (TID 0x7f708fa41600) from PID 14515; stack trace: ***
    @     0x7f70666e8890 (unknown)
    @     0x7f7065178e97 gsignal
    @     0x7f706517a801 abort
    @     0x7f7065d9c957 (unknown)
    @     0x7f7065da2ab6 (unknown)
    @     0x7f7065da2af1 std::terminate()
    @     0x7f7065da2d24 __cxa_throw
    @     0x55848e259977 w2l::loadSound<>()
    @     0x55848e25a11d w2l::loadSound<>()
    @     0x55848e26e9ed w2l::W2lListFilesDataset::getLoaderData()
    @     0x55848e25f827 w2l::W2lDataset::getFeatureData()
    @     0x55848e26098f w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x55848e26157e w2l::W2lDataset::get()
    @     0x55848e0cf1b4 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi
    @     0x55848e07534e main
    @     0x7f706515bb97 __libc_start_main
    @     0x55848e0c847a _start
Aborted_**

I have been struggling with this issue for days and any help on how to proceed with this will help me a ton.
Thanks

**Comment by maltium** [comment]
Probably it means that the file does not exist. I would add some logging to _loadSound(...)_ so that the file path is printed on the console. That should help you identify why the path is incorrect.

**Comment by kksiddharth** [comment]
Hey @maltium, thanks for your reply,
It wasnt a path issue, I was able to solve this issue by rebuilding libsndfiles with opus and rebuilding wav2letter again.

**Comment by omprakashsonie** [comment]
I also faced same issue but it is not getting resolved by rebuilding libsndfiles with opus and rebuilding wav2letter again. 

how do I access log to see which file is giving error?

terminate called after throwing an instance of 'std::runtime_error'
  what():  loadSound: unknown format or could not open stream
*** Aborted at 1594410591 (unix time) try "date -d @1594410591" if you are using GNU date ***
PC: @     0x7f88f57a2e97 gsignal
*** SIGABRT (@0xa120) received by PID 41248 (TID 0x7f893b072380) from PID 41248; stack trace: ***
    @     0x7f8939f4a890 (unknown)
    @     0x7f88f57a2e97 gsignal
    @     0x7f88f57a4801 abort
    @     0x7f88f6197957 (unknown)
    @     0x7f88f619dab6 (unknown)
    @     0x7f88f619daf1 std::terminate()
    @     0x7f88f619daaa std::rethrow_exception()
    @     0x562b1c112803 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x562b1c112a4e w2l::W2lDataset::get()
    @     0x562b1bf455f6 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl
    @     0x562b1bee05e8 main
    @     0x7f88f5785b97 __libc_start_main
    @     0x562b1bf4035a _start
*** Aborted at 1594410592 (unix time) try "date -d @1594410592" if you are using GNU date ***
PC: @     0x7ffec5b6ab6d ([vdso]+0xb6c)
*** SIGTERM (@0x7ffec5a44840) received by PID 41247 (TID 0x7f32e0abf380) from PID 18446744072730462272; stack trace: ***
    @     0x7f329b1eff20 (unknown)
    @     0x7ffec5b6ab6d ([vdso]+0xb6c)
    @     0x7f329b2e1ea6 __clock_gettime
    @     0x7f328126f37e (unknown)
    @     0x7f32813334f7 (unknown)
    @     0x7f32812574ac (unknown)
    @     0x7f3281257609 (unknown)
    @     0x7f328115716d (unknown)
    @     0x7f32812de739 cuStreamSynchronize
    @     0x7f32bd51de04 cudart::cudaApiStreamSynchronize()
    @     0x7f32bd55c13d cudaStreamSynchronize
    @     0x7f32bb453509 cuda::sync()
    @     0x7f32bbb80acf af_sync
    @     0x7f32bbe56af7 af::sync()
    @     0x56502224ef1f _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl

**Comment by tlikhomanenko** [comment]
which OS are you using? Make sure that install all system libs, like for Ubuntu 18.04 https://github.com/facebookresearch/wav2letter/blob/master/Dockerfile-CUDA-Base#L20
