### ISSUE TITLE
malloc(): memory corruption error when decoding

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#459]
There are 38470 words in the lexicon file. I am working on Bengali language.

Head of lexicon.txt:
বিদেশীর ব ি দ ে শ ী র |
কৃতিত্বের ক ৃ ত ি ত ্ ব ে র |
মুর্তিটাকে ম ু র ্ ত ি ট া ক ে |
ফেনী ফ ে ন ী |
তিরুবনন্তপুরম ত ি র ু ব ন ন ্ ত প ু র ম |
ভূতেদের ভ ূ ত ে দ ে র |
উঁচিয়ে উ ঁ চ ি য ় ে |
ডিকো ড ি ক ো |
নামসর্বস্ব ন া ম স র ্ ব স ্ ব |
ঘটনাগুনো ঘ ট ন া গ ু ন ো |

Error:
I1129 06:16:10.698246 20154 Decode.cpp:133] Number of classes (network): 179 I1129 06:16:10.771031 20154 Decode.cpp:140] Number of words: 38470 I1129 06:16:10.920435 20154 W2lListFilesDataset.cpp:141] 6594 files found. I1129 06:16:10.920583 20154 Utils.cpp:102] Filtered 0/6594 samples I1129 06:16:10.921502 20154 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 6594 I1129 06:16:10.922315 20154 Decode.cpp:154] [Serialization] Running forward pass ... I1129 06:20:31.829942 20154 Decode.cpp:201] [Dataset] Number of samples per thread: 1649 I1129 06:23:24.582834 20154 Decode.cpp:308] **[Decoder] LM constructed. malloc(): memory corruption** *** Aborted at 1575037404 (unix time) try "date -d @1575037404" if you are using GNU date *** PC: @ 0x7ff18601ee97 gsignal *** SIGABRT (@0x3eb00004eba) received by PID 20154 (TID 0x7ff1ad886380) from PID 20154; stack trace: *** @ 0x7ff1ac785890 (unknown) @ 0x7ff18601ee97 gsignal @ 0x7ff186020801 abort @ 0x7ff186069897 (unknown) @ 0x7ff18607090a (unknown) @ 0x7ff186074994 (unknown) @ 0x7ff1860772ed __libc_malloc @ 0x7ff186c49258 operator new() @ 0x55e61c2ecbe1 w2l::KenLM::score() @ 0x55e61c1cca1e main @ 0x7ff186001b97 __libc_start_main @ 0x55e61c21da0a _start Aborted (core dumped)

**Comment by tlikhomanenko** [comment]
Hi @samin9796,

What was the problem and how did you solve it? I see that now you reported another problem in separate issue.

**Comment by samin9796** [comment]
@tlikhomanenko  I cannot solve it.
