### ISSUE TITLE
Decoder: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#460]
This is the error I got when decoding:

I1216 06:36:41.125556 15401 Decode.cpp:133] Number of classes (network): 179
I1216 06:36:41.154817 15401 Decode.cpp:140] Number of words: 17514
I1216 06:36:41.171702 15401 Decode.cpp:201] [Dataset] Number of samples per thread: 6533
Loading the LM will be faster if you build a binary file.
Reading /data/ahnaf/speech/warp-ctc/pytorch_binding/audio/ctcdecode/deepspeech.pytorch_new/language_models/sust_3gram_lm.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
I1216 06:36:41.304169 15401 Decode.cpp:308] [Decoder] LM constructed.
Decoder: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
*** Aborted at 1576507001 (unix time) try "date -d @1576507001" if you are using GNU date ***
PC: @     0x7f25161aee97 gsignal
*** SIGABRT (@0x3eb00003c29) received by PID 15401 (TID 0x7f253da16380) from PID 15401; stack trace: ***
    @     0x7f253c915890 (unknown)
    @     0x7f25161aee97 gsignal
    @     0x7f25161b0801 abort
    @     0x7f2516204a73 (unknown)
    @     0x7f25162072ed __libc_malloc
    @     0x7f2516dd9258 operator new()
    @     0x55ec1240fbe1 w2l::KenLM::score()
    @     0x55ec122efa1e main
    @     0x7f2516191b97 __libc_start_main
    @     0x55ec12340a0a _start
Aborted (core dumped)

decode.cfg:
--lexicon=/data/ahnaf/wav2letter/dataset_prep/test_lexicon.txt
--lm=/data/ahnaf/speech/warp-ctc/pytorch_binding/audio/ctcdecode/deepspeech.pytorch_new/language_models/sust_3gram_lm.arpa
--emission_dir=/data/ahnaf/wav2letter/dataset_prep/
--datadir=/data/ahnaf/wav2letter/dataset_prep/
--tokensdir=/data/ahnaf/wav2letter/dataset_prep/
--tokens=tokens.txt
--test=test.lst
--sclite=/data/ahnaf/wav2letter/dataset_prep/sclite
--lmweight=0.5
--wordscore=1
--beamsize=8
--beamscore=8
--beamthreshold=5
--silweight=-0.5
--nthread_decoder=1
--smearing=max
--show=true
--showletters=true

I have 17514 words in the lexicon file for decoding and 180 tokens. I am working on Bengali language. The head of the lexicon file:

জানুয়ারি জ  া ন  ু য়  া র  ি |
ইনি ই ন  ি |
পাই প  া ই |
মায়ের ম  া য়  ে র |
বীজ ব  ী জ |
পাঠক প  া ঠ ক |
সংসার স  ং স  া র |
স্থলভাগে স  ্ থ ল ভ  া গ  ে |
ইন্ধন ই ন  ্ ধ ন |
সমবেত স ম ব  ে ত |
সমানেই স ম  া ন  ে ই |
ম্যাচেই ম  ্ য  া চ  ে ই |
জীবনের জ  ী ব ন  ে র |
বলছেন ব ল ছ  ে ন |
পক্ষের প ক  ্ ষ  ে র |
মানহানির ম  া ন হ  া ন  ি র |
রুবিন র  ু ব  ি ন |
প্রত্যাশাও প  ্ র ত  ্ য  া শ  া ও |
গতরাতের গ ত র  া ত  ে র |
সম্মানে স ম  ্ ম  া ন  ে |
৫টা ৫ ট  া |
জরুরী জ র  ু র  ী |
নতুনভাবে ন ত  ু ন ভ  া ব  ে |
বাড়তি ব  া ড  ় ত  ি |
ভিদাকে ভ  ি দ  া ক  ে |
ভঙ্গি ভ ঙ  ্ গ  ি |
এগিয়ে এ গ  ি য  ়  ে |
দোকাঙ্গুলি দ  ো ক  া ঙ  ্ গ  ু ল  ি |

I am using gtx 1080Ti 8 gpu and number of  cpu is 48 with a total of 252 gb of ram. I am stuck at this error for the last 20 days and haven't got any solution yet. Please have a look!

**Comment by tlikhomanenko** [comment]
@samin9796,

could you also provide head of your tokens file and head of the arpa file for language model?

**Comment by samin9796** [comment]
@tlikhomanenko 

Head of token file:
|
+
-
*
'
_
অ
আ
ই
ঈ
উ
ঊ
ঋ
এ
ঐ
ও
ঔ
ক
খ
গ
ঘ
ঙ
চ
ছ
জ
ঝ
ঞ
ট
=
.
ঃ
া
ো
ৌ
ী
ু
ূ


Head of arpa file:

\data\
ngram 1=30761
ngram 2=143825
ngram 3=189065

\1-grams:
-5.1502714	<unk>	0
0	<s>	-0.73582405
-1.2575002	</s>	0
-4.7778788	০৫	-0.20160179
-3.2981043	জাতীয়	-0.23002596
-4.9083824	সংগীত	-0.14285506
-3.7704697	জাতীয়	-0.14182217
-3.1692817	বাংলাদেশ	-0.19133516
-4.626536	রবীন্দনাথ	-0.32654053

**Comment by tlikhomanenko** [comment]
@samin9796, could you check that kenlm query binary works fine with your transcriptions data?

**Comment by samin9796** [comment]
@tlikhomanenko  I tried to decode with kenlm binary file also but failed. I used this language model for deepspeech2 toolkit and it works there. Is it related to installing w2l? Should I re-install w2l?

**Comment by abhaygargab** [comment]
Can you try cmake command for KENLM without -DCMAKE_BUILD_TYPE=Release

Refer https://github.com/facebookresearch/wav2letter/issues/596
