### ISSUE TITLE
Cannot build again: Seq2SeqCriterion.cpp error

### ISSUE THREAD

**Issue by alpoktem** [facebookresearch/wav2letter#464]
Hi,

I actually built wav2letter successfully and ran the Librispeech training tutorial. This build still runs without any problem.

I wanted to try out some other branches, but cannot build them. Even with the master branch I am having problems, even though I follow the same installation instructions.

I couldn't find anyone else having the same issue. So desperately looking what I'm missing. I am sure it's a trivial thing but I'd appreciate any guidance.  

I am on Ubuntu and building with GPU. 

Here's my unsuccessful build log: https://gist.github.com/alpoktem/2f398652b427ba01e39c9a809142aac0

Shortcut to error:
`/home/twbgmy/extSW/wav2letter-copy/src/criterion/Seq2SeqCriterion.cpp:582:68: error: ‘class fl::Variable’ has no member named ‘linear’
       Variable inStateHiddenBatched = concatenate(statesVector, 1).linear();`

**Comment by xuqiantong** [comment]
Hey, you need to pull the latest flashlight and rebuild it. We introduced `linear()` function to `fl::Variable` recently.
