### ISSUE TITLE
Train QuartzNet with wav2letter

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/wav2letter#465]
Hi, seen that recent article: 
https://devblogs.nvidia.com/develop-smaller-speech-recognition-models-with-nvidias-nemo-framework/
Apparently a QuartzNet model could do as good as a wav2letter model (even a little better) but with 10 time less params.
Question : Is it possible today to train a QuartzNet model with wav2letter ?
Kind
W.

**Comment by vineelpratap** [comment]
> Is it possible today to train a QuartzNet model with wav2letter
Yes, it should be possible. And, wav2letter framework has also support to train with CTC Loss. One would to have to define the specific architecture and write the recipe though.
 
For reference, here is the implementation of original TDS module that the paper mentions - https://git.io/Jedsv.

**Comment by trangtv57** [comment]
> > Is it possible today to train a QuartzNet model with wav2letter
> 
> Yes, it should be possible. And, wav2letter framework has also support to train with CTC Loss. One would to have to define the specific architecture and write the recipe though.
> 
> For reference, here is the implementation of original TDS module that the paper mentions - https://git.io/Jedsv.
Do you have file model.arch for quartz Net write for wav2letter or try to write it? @vineelpratap  
thanks
