### ISSUE TITLE
how to use residuals?

### ISSUE THREAD

**Issue by danFromTelAviv** [facebookresearch/wav2letter#467]
Hi, 
I want to add simple residuals to a sample architecture you have posted. The documentation is not clear enough I suppose. I want to use a linear transformation since the layers have different shapes so I used SKIPL. However, it looks like there is still an issue with the dimensions. 
Here is a simple example that fails:
* The architecture:
```
V -1 1 NFEAT 0
WN 3 C NFEAT 200 13 2 -1
GLU 2
RES 24 1 1
DO 0.25
WN 3 C 100 200 3 1 -1
GLU 2
DO 0.25
WN 3 C 100 200 4 1 -1
GLU 2
DO 0.25
WN 3 C 100 250 5 1 -1
GLU 2
DO 0.25
WN 3 C 125 250 6 1 -1
GLU 2
DO 0.25
WN 3 C 125 300 7 1 -1
GLU 2
DO 0.25
WN 3 C 150 350 8 1 -1
GLU 2
DO 0.25
WN 3 C 175 400 9 1 -1
GLU 2
DO 0.25
WN 3 C 200 450 10 1 -1
GLU 2
SKIPL 0 25 1 0.7071
DO 0.25
WN 3 C 225 500 11 1 -1
GLU 2
DO 0.25
WN 3 C 250 500 12 1 -1
GLU 2
DO 0.25
WN 3 C 250 500 13 1 -1
GLU 2
DO 0.25
WN 3 C 250 600 14 1 -1
GLU 2
DO 0.25
WN 3 C 300 600 15 1 -1
GLU 2
DO 0.25
WN 3 C 300 750 21 1 -1
GLU 2
DO 0.25
RO 2 0 3 1
WN 0 L 375 1000
GLU 0
DO 0.25
WN 0 L 500 NLABEL
```
* The Error:
```
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Invalid input size:203):
In function af::dim4 getOutDims(const af::dim4&, const af::dim4&, bool)
In file src/backend/common/ArrayInfo.cpp:130
Invalid dimension for argument 1
Expected: ldims == rdims
In function af::array af::operator+(const af::array&, const af::array&)
In file src/api/cpp/array.cpp:837
*** Aborted at 1577893305 (unix time) try "date -d @1577893305" if you are using GNU date ***
PC: @     0x7f19fc592428 gsignal
*** SIGABRT (@0x817) received by PID 2071 (TID 0x7f1a46803600) from PID 2071; stack trace: ***
    @     0x7f1a3eb09390 (unknown)
    @     0x7f19fc592428 gsignal
    @     0x7f19fc59402a abort
    @     0x7f19fced584d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f19fced36b6 (unknown)
    @     0x7f19fced3701 std::terminate()
    @     0x7f19fced3919 __cxa_throw
    @     0x7f1a18a4142f af::operator+()
    @           0x66423a fl::operator+()
    @           0x6ae9fa fl::Residual::forward()
    @           0x6aef9c fl::Residual::forward()
    @           0x68fd52 fl::Sequential::forward()
    @           0x4832df _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi.constprop.11419
    @           0x41b895 main
    @     0x7f19fc57d830 __libc_start_main
    @           0x47e5d9 _start
    @                0x0 (unknown)
Aborted (core dumped)
```

Thank you for your help  and for sharing this amazing library.

**Comment by tlikhomanenko** [comment]
Hi @danFromTelAviv,

When you declare the `SKIPL 0 25 1 0.7071` the next row should be the layer which will be applied to `x` before doing the summation (here the third arg is 1 so we need to define 1 layer), in you case `DO 0.25` will be used as this layer. 

For your case to apply the residual connection you need to change it to:
```
SKIPL 0 25 3 0.7071
RO 2 0 3 1 # reorder before applying Linear layer: input Tx1xCxB -> CxTxBx1
L 100 225 # apply linear layer
RO 1 3 0 2 # reorder back for conv operation
```
Here you need to reorder because Linear and Conv layer have different axis to transform.

**Comment by padentomasello** [comment]
Hi @danFromTelAviv, I wanted to provide some additional information to @tlikhomanenko response. 

1. As mentioned, the `SKIPL` doesn't by itself do any linear projection. Rather, it creates a projection using next M layers, (as defined by the third parameter) in the archfile. So for your file, we have
```
SKIPL 0 25 1 0.7071
DO 0.25
```
which "projects" the input using a dropout layer. In addition to the method above, you can also use
```
SKIPL 0 25 1 0.7071                                                                                                                                                                                                       
WN 3 C 100 225 1 1 -1
```
which takes the residual tensor (with 100 channels) and uses a pointwise (1x1) convolution to project each pixel to 225 channels, which matches our target tensor, without performing any reordering. (The network print out can be helpful for understanding this)

2. We also need to make sure the the time dimensions of output and residual tensors match. (Even though the architecture uses convolution with "SAME" padding, this isn't always the case when using even kernel sizes). To do so, ensure that all convolutions have odd kernel sizes, stride of 1, and "SAME" padding. 

With those to changes, here is a full network that you should be able to use:
```
V -1 1 NFEAT 0
WN 3 C NFEAT 200 13 1 -1
GLU 2
RES 23 1 1
DO 0.25
WN 3 C 100 200 3 1 -1
GLU 2
DO 0.25
WN 3 C 100 200 3 1 -1
GLU 2
DO 0.25
WN 3 C 100 250 5 1 -1
GLU 2
DO 0.25
WN 3 C 125 250 5 1 -1
GLU 2
DO 0.25
WN 3 C 125 300 7 1 -1
GLU 2
DO 0.25
WN 3 C 150 350 5 1 -1
GLU 2
DO 0.25
WN 3 C 175 400 9 1 -1
GLU 2
DO 0.25
WN 3 C 200 450 11 1 -1
#SKIP 0 25 0.707
SKIPL 0 24 1 0.7071
WN 3 C 100 450 1 1 -1
GLU 2
DO 0.25
WN 3 C 225 500 11 1 -1
GLU 2
DO 0.25
WN 3 C 250 500 12 1 -1
GLU 2
DO 0.25
WN 3 C 250 500 13 1 -1
GLU 2
DO 0.25
WN 3 C 250 600 14 1 -1
GLU 2
DO 0.25
WN 3 C 300 600 15 1 -1
GLU 2
DO 0.25
WN 3 C 300 750 21 1 -1
GLU 2
DO 0.25
RO 2 0 3 1
WN 0 L 375 1000
GLU 0
DO 0.25
WN 0 L 500 NLABEL
```
(Note, I also moved the GLU outside of the Residual block)

**Comment by danFromTelAviv** [comment]
@tlikhomanenko @padentomasello 
thank you very much for the incredibly well detailed answer. I will try it out.

**Comment by tlikhomanenko** [comment]
@danFromTelAviv 

Feel free to reopen issue if you still need any clarification.
