### ISSUE TITLE
No completed candidates in Seq2seq decoder

### ISSUE THREAD

**Issue by jmpc11** [facebookresearch/wav2letter#469]
I use seq2seq decoder for Spanish model, but the output transcriptions are not completed. The decoder is not able to recognize the words at the end of some sentences.

I do not know if it is related to:
- An unbalanced dataset in terms of sentence duration.
- The silence model. Some audio files containing only one word between long pauses does not obtain any output.

The same architecture works well using LibriSpeech for English models. I read the same issue but it had not been solved.

Thanks in advance.

**Comment by tlikhomanenko** [comment]
We have updated the seq2seq decoder with a bit different algorithm, so you can try to use it again, you need to tune eosscore which is responsible to control length prediction.
