### ISSUE TITLE
Can not install  it

### ISSUE THREAD

**Issue by Sundy1219** [facebookresearch/wav2letter#470]
I can not find installation instructions page.it always show 404.
how can solve it ? thanks

**Comment by tlikhomanenko** [comment]
Hi @Sundy1219,

aAll documentation is moved to the wiki page https://github.com/facebookresearch/wav2letter/wiki (see https://github.com/facebookresearch/wav2letter/wiki/Dependencies and https://github.com/facebookresearch/wav2letter/wiki/General-building-instructions, for docker - https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker)
