### ISSUE TITLE
It's too hard to install wav2letter 

### ISSUE THREAD

**Issue by Sundy1219** [facebookresearch/wav2letter#471]
I am trying to build wav2letter. but i found it is very hard to build dependency of wav2letter.  do you have easy  and detailed tutorials ? thanks

**Comment by davidbelle** [comment]
Have you tried using the docker image/s. I tried for ages to install all the dependencies too but using the docker image fixed all that. 

If you're using CUDA 10+, then use this docker image
`sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-10-latest
`
then

`sudo docker exec -it w2l`

The image contains all the dependancies you need but it's a little bit old. If you want to have the latest you'll have to do the following inside ~/flashlight

`git pull
export MKLROOT=/opt/intel/mkl
rm -rf build
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j4
make test
make install
`

Then go into ~/wav2letter directory and build the wav2letter as per the instructions.

**Comment by Sundy1219** [comment]
thanks for your reply. I'll try it.

**Comment by Franceshe** [comment]
> Have you tried using the docker image/s. I tried for ages to install all the dependencies too but using the docker image fixed all that.
> 
> If you're using CUDA 10+, then use this docker image
> `sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-10-latest `
> then
> 
> `sudo docker exec -it w2l`
> 
> The image contains all the dependancies you need but it's a little bit old. If you want to have the latest you'll have to do the following inside ~/flashlight
> 
> `git pull export MKLROOT=/opt/intel/mkl rm -rf build mkdir -p build cd build cmake .. -DCMAKE_BUILD_TYPE=Release make -j4 make test make install `
> 
> Then go into ~/wav2letter directory and build the wav2letter as per the instructions.

Does it also applies to Mac OX with only CPU for distributed training and without CUDA?




> I am trying to build wav2letter. but i found it is very hard to build dependency of wav2letter. do you have easy and detailed tutorials ? thanks

Agree, the installation process for dependency is too complex.
Hopefully the dev team could improve the process with followup update.

**Comment by davidbelle** [comment]
@Franceshe I haven't tried it, but I would assume using the Dockerfile-CPU file (found in the root directory) instead of the link I provided should work just as well. 

Also when you're re-building arrayfire, there's a special flag to send to _make_ to specify you're using CPU backend instead of CUDA. Currently the arrayfire website is down so can't tell you exactly what it is, you'll have to look it up when the website is backup.

**Comment by Franceshe** [comment]
> @Franceshe I haven't tried it, but I would assume using the Dockerfile-CPU file (found in the root directory) instead of the link I provided should work just as well.
> 
> Also when you're re-building arrayfire, there's a special flag to send to _make_ to specify you're using CPU backend instead of CUDA. Currently the arrayfire website is down so can't tell you exactly what it is, you'll have to look it up when the website is backup.

Hi, thanks for the reference. It looks like the facebook team updated the installation process with  docker [Building Running with Docker
](https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker)
and the build process is at ease.

**Comment by tlikhomanenko** [comment]
@davidbelle, thanks for pointing to the right place for people.

@Sundy1219, @Franceshe there are Dockerfiles for both CPU and GPU backend: we have Dockerfile-CUDA-Base and Dockerfile-CPU-Base where all dependencies are installed and then Dockerfile-CUDA and Dockerfile-CPU where flashlight and wav2letter installation is done.

So one can have possibilities for simple installation:
- use pre-built images, as @davidbelle pointed and docs to run it https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker (added also the link to all pre-built images there too). Inside container one can do git pull for flashilight and git clone for latest wav2letter and then repeat the steps from Dockerfile-CUDA or Dockerfile-CPU (depending on the backend) - added to the docs too.
- repeat steps in the Dockerfiles, this will work for Ubuntu 16.04
- built docker image by yourself with latest master.

> Does it also applies to Mac OX with only CPU for distributed training and without CUDA?
if you will use docker image on Mac OX the image will work, this is like virtual machine.

**Comment by tlikhomanenko** [comment]
Feel free to reopen if problem still persists!
