### ISSUE TITLE
blinding python Error

### ISSUE THREAD

**Issue by Sundy1219** [facebookresearch/wav2letter#473]
i try to install wav2letter blinding python. but i got an error. how can i solve it ? thanks .
![2020-01-14 18-19-53屏幕截图](https://user-images.githubusercontent.com/19542945/72335960-ce5ac300-36fa-11ea-9b88-5077bac971fb.png)

**Comment by tlikhomanenko** [comment]
Hi @Sundy1219, 

Latest commits should fix this error. Could you try again?

**Comment by tlikhomanenko** [comment]
@Sundy1219,

Feel free to reopen if error still persists!
