### ISSUE TITLE
Tests failing on docker run

### ISSUE THREAD

**Issue by wazcodez** [facebookresearch/wav2letter#474]
Hi, 

I've tried running docker (cpu-latest), but I'm getting error. I followed https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker

**Here are the steps:**

1. Getting docker image
`docker run --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cpu-latest`

2. Accessing container
`docker exec -it w2l bash`

3. Running Tests
`cd /root/wav2letter/build && make test`

**Here is the error that I'm getting:**

```
90% tests passed, 2 tests failed out of 21

Total Test time (real) =  15.82 sec

The following tests FAILED:
          4 - Seq2SeqTest (Failed)
         20 - W2lModuleTest (Failed)
Errors while running CTest
Makefile:72: recipe for target 'test' failed
make: *** [test] Error 8
```

Also, I tried following inference example per wiki:

For this, I followed: https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples

1. Example ASR
`make simple_streaming_asr_example`

**Here is the error that I'm getting:**

```
make: *** No rule to make target 'simple_streaming_asr_example'.  Stop.
```

I'm on windows. 

When I try to build the docker images locally - I'm running into issues with the following:

```
[  6%] Building CXX object tests/CMakeFiles/AllReduceTest.dir/__/flashlight/autograd/Functions.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make[2]: *** [tests/CMakeFiles/ContribModuleTest.dir/contrib/modules/ContribModuleTest.cpp.o] Error 4
tests/CMakeFiles/ContribModuleTest.dir/build.make:62: recipe for target 'tests/CMakeFiles/ContribModuleTest.dir/contrib/modules/ContribModuleTest.cpp.o' failed
make[1]: *** [tests/CMakeFiles/ContribModuleTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1122: recipe for target 'tests/CMakeFiles/ContribModuleTest.dir/all' failed
```

**Comment by Chreschtf** [comment]
Have the same thing. running on windows 10, when performing the 'make test'

**Comment by avidov** [comment]
Hi,

Sorry for the simple_streaming_asr_example failure. I am working on it now.
I’ll upload the fix today or tomorrow.

Thank you,
Gilad


On Jan 14, 2020, at 1:00 PM, wazcodez <notifications@github.com<mailto:notifications@github.com>> wrote:


simple_streaming_asr_example

**Comment by tlikhomanenko** [comment]
Hi @Chreschtf, @wazcodez,

These two tests should fail, because they use RNN and it is not implemented yet for CPU backend. You can simply run these tests separately and there will be printed like "Not implemented yet". No worries, you can safely use the image. Note that this built is old (not actual latest master), so to update the w2l inside container follow steps in the https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker.

We are planning to update the image as soon as we will fix some stuff in the streaming pipeline.

**Comment by wazcodez** [comment]
Hi @tlikhomanenko ,

Thanks for that - I followed the posting, but ran into some issues. I'm not sure about ramifications of these. 

I'm at, 
` cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=OFF -DW2L_BUILD_INFERENCE=ON && make -j4`

```
Scanning dependencies of target fbgemm_avx2
[ 21%] Building CXX object CMakeFiles/fbgemm_avx2.dir/src/FbgemmFP16UKernelsAvx2.cc.o
[ 22%] Building CXX object CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8Depthwise3DAvx2.cc.o
[  4%] Building CXX object CMakeFiles/wav2letter++.dir/src/criterion/backend/cpu/FullConnectionCriterion.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/wav2letter++.dir/build.make:878: recipe for target 'CMakeFiles/wav2letter++.dir/src/criterion/backend/cpu/FullConnectionCriterion.cpp.o' failed
make[2]: *** [CMakeFiles/wav2letter++.dir/src/criterion/backend/cpu/FullConnectionCriterion.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8Depthwise3x3Avx2.cc.o
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/wav2letter++.dir/all' failed
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2

... (more logs)

Scanning dependencies of target cpuinfo_internals
[ 86%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/init.c.o
[ 87%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/api.c.o
[ 88%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/init.c.o
[ 88%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/info.c.o
[ 89%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/vendor.c.o
[ 90%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/uarch.c.o
[ 91%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/name.c.o
[ 91%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/topology.c.o
[ 92%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/isa.c.o
[ 93%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/cache/init.c.o
[ 94%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/cache/descriptor.c.o
[ 94%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/cache/deterministic.c.o
[ 95%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/linux/init.c.o
[ 96%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/x86/linux/cpuinfo.c.o
[ 97%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/linux/smallfile.c.o
[ 97%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/linux/multiline.c.o
[ 98%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/linux/current.c.o
[ 99%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/linux/cpulist.c.o
[100%] Building C object cpuinfo/CMakeFiles/cpuinfo_internals.dir/src/linux/processors.c.o
[100%] Linking C static library libcpuinfo_internals.a
[100%] Built target cpuinfo_internals
[  4%] No install step for 'fbgemm'
[  4%] Completed 'fbgemm'
[  4%] Built target fbgemm
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by avidov** [comment]
Is the simple_streaming_asr_example working well now when following
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples ?

**Comment by tlikhomanenko** [comment]
@wazcodez,

Can you remove `wav2letter/build/*` and run then `cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=OFF && make -j4`? Does this gives you the same error?

**Comment by vigneshmj1997** [comment]
i am to getting a error while running test in docker image for inference
here the error i got
make: *** No rule to make target 'test'.  Stop.
root@24196b2f5aa7:~/wav2letter/build#

**Comment by ML6634** [comment]
@avidov 

Thank you for taking care of this!
So far, the other examples on the same link work for me. However, for 
Interactive Streaming ASR Example I have got the same error (which was copied and pasted at the bottom). I use Ubuntu Subsystem on Windows 10. So, any ideas? Thank you!

~/wav2letter/build$ make interactive_streaming_asr_example -j $(nproc)
make: *** No rule to make target 'interactive_streaming_asr_example'.  Stop.

**Comment by avidov** [comment]
Please ensure that you have the latest build (using: git pull). and run cmake again from the build directory.

**Comment by ML6634** [comment]
@avidov
Thank you for the helpful comment! Now it works nicely for me! The only minor change I did is that I put my username in the link of the input file right after "input=/home/". Probably it is because I use Ubuntu on Windows?
