### ISSUE TITLE
Release of online RNN-T baseline

### ISSUE THREAD

**Issue by swpd** [facebookresearch/wav2letter#475]
Hi, 

Thanks for your great work of the online speech recognition.
I'm also insterested in the RNN-T baseline mentioned in the paper and would like to compare it with TDS model on my own training data.
According to the [paper](https://research.fb.com/wp-content/uploads/2020/01/Scaling-up-online-speech-recognition-using-ConvNets.pdf?) Section 4.2, 

> All our experiments are run using wav2letter++ framework [2] with 64 GPUs for each experiment.

Can you please consider releasing the RNN-T baseline? (RNN-T train/decode recipes, RNN-T critcriterion, etc.)

Thanks!

**Comment by vineelpratap** [comment]
Hi,
 For LC-BLSTM + RNN-T baseline, we got the trained model from the authors of https://arxiv.org/abs/1911.01629 and used it to compute the experimental results.
