### ISSUE TITLE
Error in acoustic model file loading in inference

### ISSUE THREAD

**Issue by chintler** [facebookresearch/wav2letter#477]
Hi,

I set up wav2letter on Ubuntu 16.04 and I think I've got all the steps, except the last. I am referring [this link](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples) for the streaming inference, and my command is as follows:

cat ../../audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | inference/inference/examples/simple_streaming_asr_example  --input_files_base_path ../model

The model files have been downloaded with this command

    for f in acoustic_model.bin arch.txt decoder_options.json feature_extractor.bin language_model.bin lexicon.txt tokens.txt ; do wget http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model/${f} ; done

which is from the same link. My log is as follows

> Started features model file loading ... 
> Completed features model file loading elapsed time=81504 microseconds
> 
> Started acoustic model file loading ... 
> terminate called after throwing an instance of 'std::invalid_argument'
>   what():  TDSBlock::TDSBlock() is called with null conv.
> Aborted (core dumped)

As you can see, the features_model file at this location gets loaded correctly, while the acoustic_model does not. All the necessary files are present in the /model folder, so I don't think that is the issue. Can someone point me in the right direction?

**Comment by avidov** [comment]
Hi,

Sorry about that. I just uploaded a fix and an updated model.
Please obtain both.

To update the code:
> cd wav2letter
> git pull

To update the model:
Use the

for f in acoustic_model.bin arch.txt decoder_options.json feature_extractor.bin language_model.bin lexicon.txt tokens.txt ; do wget http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model/${f} ; done


command


On Jan 16, 2020, at 8:00 AM, chintler <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I set up wav2letter on Ubuntu 16.04 and I think I've got all the steps, except the last. I am referring this link<https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples> for the streaming inference, and my command is as follows:

cat ../../audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | inference/inference/examples/simple_streaming_asr_example --input_files_base_path ../model

The model files have been downloaded with this command

for f in acoustic_model.bin arch.txt decoder_options.json feature_extractor.bin language_model.bin lexicon.txt tokens.txt ; do wget http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model/${f} ; done


which is from the same link. My log is as follows

Started features model file loading ...
Completed features model file loading elapsed time=81504 microseconds

Started acoustic model file loading ...
terminate called after throwing an instance of 'std::invalid_argument'
what(): TDSBlock::TDSBlock() is called with null conv.
Aborted (core dumped)

As you can see, the features_model file at this location gets loaded correctly, while the acoustic_model does not. All the necessary files are present in the /model folder, so I don't think that is the issue. Can someone point me in the right direction?

**Comment by chintler** [comment]
Thanks for the quick fix! I updated the model, pulled the repo and it's up and running.
