### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#478]
Hi there I'm trying to follow the intro tutorial but I found that the installation guide and the preprocessing details are down , can u please reupload it or provide an alternative.

https://github.com/facebookresearch/wav2letter/blob/master/docs/installation.md - DOWN
https://github.com/facebookresearch/wav2letter/blob/master/docs/data_prep.md - DOWN

it will be nice to have the data preparation details please

**Comment by avidov** [comment]
Hi,

We are migrating the markdown to Wiki.
Please see:
https://github.com/facebookresearch/wav2letter/wiki
And
Data Preparation<https://github.com/facebookresearch/wav2letter/wiki/Data-Preparation>



On Jan 16, 2020, at 12:53 PM, Cristopher Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there I'm trying to follow the intro tutorial but I found that the installation guide and the preprocessing details are down , can u please reupload it or provide an alternative.

https://github.com/facebookresearch/wav2letter/blob/master/docs/installation.md - DOWN
https://github.com/facebookresearch/wav2letter/blob/master/docs/data_prep.md - DOWN

i will be nice to have the data preparation details please

**Comment by cri5Castro** [comment]
thanks

**Comment by avidov** [comment]
Thank you for fixing the doc!
