### ISSUE TITLE
Training Without lexicon 

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#479]
Hi there, do you have any tutorial about training without lexicon? since in some language are very difficult to build one

**Comment by avidov** [comment]
Sorry, training requires a lexicon.

**Comment by tlikhomanenko** [comment]
Hi @cri5Castro,

to prepare lexicon you have the options:
- if you want to train letter based acoustic models (for each frame we predict probability for each letter) then you simply prepare lexicon as "word w o r d" - this works for all languages (I guess). Example of how we are doing this https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/conv_glu/librispeech/prepare.py#L83
- you can have word-pieces, for this you can use sentencepiece toolkit which takes the text file (you can use your train transcriptions) and like constructing the optimal coding of words with word-pieces with learning these word-pieces at the same time https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/seq2seq_tds/librispeech/prepare.py#L84

One can train on phones so you should use some of words to phones toolkit, but I guess this is not an option for you.

**Comment by cri5Castro** [comment]
Thanks for the info, do you know if there is no actuall way to skip the lexicon building, like using some now tokenizer

**Comment by tlikhomanenko** [comment]
@cri5Castro,

you can use any bpe tokenizer you want. We are using google sentencepiece tool to build word-pieces and then apply this model to all words from the train transcription to get their spellings for training (or map just to letter sequence). We haven't automatic construction of lexicon inside w2l, you need to prepare it before (this is flexibility for people to do any preprocessing and define any tokens set for their experiments).

**Comment by cri5Castro** [comment]
thanks for the support :)

**Comment by tlikhomanenko** [comment]
@cri5Castro , Do you need any further help with lexicon?

**Comment by cri5Castro** [comment]
no,thanks great explanation up there
