### ISSUE TITLE
files found but then not

### ISSUE THREAD

**Issue by jdupl123** [facebookresearch/wav2letter#48]
when I try run test.lua to transcribe some flac files. It finds them but then says 0 files found after and dies. This issues seems to be related to threading. any ideas?

luajit ~/wav2letter/test.lua ~/models/libri/librispeech-glu-highdropout-cpu.bin -progress -show -test LibriSpeech/dev-clean -save -dictdir librispeech-proc -datadir .

LibriSpeech/dev-clean
| dataset </Users/jdp/Projects/pinch/ml/LibriSpeech/dev-clean>: 10000 files found
| dataset </Users/jdp/Projects/pinch/ml/LibriSpeech/dev-clean>: 0 files found
luajit: /Users/jdp/usr/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...dp/usr/share/lua/5.1/wav2letter/numberedfilesdataset.lua:71: no file found in </Users/jdp/Projects/pinch/ml/LibriSpeech/dev-clean/?????????.flacsz> nor in </Users/jdp/Projects/pinch/ml/LibriSpeech/dev-clean/00000/?????????.flacsz>
stack traceback:
        [C]: in function 'assert'
        ...dp/usr/share/lua/5.1/wav2letter/numberedfilesdataset.lua:71: in function '__init'
        /Users/jdp/usr/share/lua/5.1/torch/init.lua:91: in function </Users/jdp/usr/share/lua/5.1/torch/init.lua:87>
        [C]: in function 'closure'
        /Users/jdp/usr/share/lua/5.1/wav2letter/runtime/data.lua:319: in function 'mapconcat'
        /Users/jdp/usr/share/lua/5.1/wav2letter/runtime/data.lua:417: in function 'datasetwithfeatures'
        /Users/jdp/usr/share/lua/5.1/wav2letter/runtime/data.lua:476: in function 'closure'
        ...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:79: in function <...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:78>
        [C]: in function 'xpcall'
        /Users/jdp/usr/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        /Users/jdp/usr/share/lua/5.1/threads/queue.lua:65: in function </Users/jdp/usr/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        /Users/jdp/usr/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
        [C]: in function 'error'
        /Users/jdp/usr/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        /Users/jdp/usr/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        /Users/jdp/usr/share/lua/5.1/threads/threads.lua:142: in function 'specific'
        /Users/jdp/usr/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
        ...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:85: in function '__init'
        /Users/jdp/usr/share/lua/5.1/torch/init.lua:91: in function </Users/jdp/usr/share/lua/5.1/torch/init.lua:87>
        [C]: in function 'newiterator'
        /Users/jdp/wav2letter/test.lua:150: in main chunk
        [C]: at 0x010c2bf350

**Comment by vineelpratap** [comment]
Looks like you haven't done the the pre-processing steps correctly. `?????????.flacsz` should be created when you run `create-sz.lua` script
You can find the details here - https://github.com/facebookresearch/wav2letter#data-pre-processing
