### ISSUE TITLE
simple_streaming_asr_example: terminate called after throwing an instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by LifaSun** [facebookresearch/wav2letter#481]
I am trying to implement the Inference Framework, but it doesn't work. 
https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples

**Command:**
root@8eb0b4812c4a:~/wav2letter_master# ./build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path ./model --input_audio_file ./audio/Librispeech/116-288045-0022.flac

**Output:**
Started features model file loading ...
Completed features model file loading elapsed time=32441 microseconds

Started acoustic model file loading ...
**terminate called after throwing an instance of 'std::invalid_argument'
  what():  TDSBlock::TDSBlock() is called with null conv.
Aborted (core dumped)**

Is there anyone who can tell me how to figure it out? Thank you!

**Comment by sunilpro** [comment]
Pls try in latest master branch. Same issue: #477

**Comment by avidov** [comment]
Agree with sunilpro, pulling the latest version will fix this. Also I'll release today Docker image for inference.

**Comment by LifaSun** [comment]
Thanks @sunilpro and @avidov ! It works well now. 

To update the code:
 cd wav2letter
 git pull
To update the model:
Use the
for f in acoustic_model.bin arch.txt decoder_options.json feature_extractor.bin language_model.bin lexicon.txt tokens.txt ; do wget http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model/${f} ; done

Then, re-cmake in the directory /wav2letter/build.
