### ISSUE TITLE
is Normalization required?

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#488]
Hi there I wanted to know if we need to normalize the audio files (i.e: from -1 to 1) or we only need to convert them into a compatible format and adjust the sample rate?

**Comment by vineelpratap** [comment]
> need to normalize the audio files 
It is not a requirement. Usually, this shouldn't be a concern and the digitized data should be between [-1, 1]. Which format are your audio files stored ? 

> adjust the sample rate
There is no restriction on `samplerate`, but we expect all the `train`, `valid` and `test` sets to be the same which can be specified using `--samplerate` flag. If you don't specify anything, 16000 will be used as default.

**Comment by cri5Castro** [comment]
i'm working with wav files but  I'm not sure about if there are already normalized

**Comment by vineelpratap** [comment]
Okay. It shouldn’t be an issue.
