### ISSUE TITLE
Dealing with special characters

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#490]
hello, there

I wanted to know if i need to perfom some kind of processing to special chars like "ñ" or  "á,é,í,ó,ú"   I'll train a model for spanish specifically, do you recomend to delete this characters or is the library able to work with this ones

**Comment by vineelpratap** [comment]
wav2letter++ should work fine with unicode characters. We have already tested this many non english languages. 

Out of curiosity, which recipe are using for training your spanish model.

**Comment by cri5Castro** [comment]
I'm basing my preprocessing scrips on the libspeech recipe but I'm working with Mozilla common voice data

**Comment by vineelpratap** [comment]
Okay. Would recommend using [this](https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/seq2seq_tds ) recipe and adapting it for your use case for the start.
