### ISSUE TITLE
LM training

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#495]
Hi there I wanted to know if you have any recipe for lm training on fairseq, or  what is needed to prepare an used a pretrained model i.e fasttext pretrained models

**Comment by tlikhomanenko** [comment]
Hi @cri5Castro,

For the GCNN models from fairseq (and supporting decoding with them) please have a look here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019/lm and https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech. In the latest link also there are details in the README.md how to convert fairseq GCNN model to the w2l to use it during decoding. For other neural-based models we have no support of converting (you should create the same model with flashlight and then reload matrices if you are going to do this for your LMs).
