### ISSUE TITLE
reducing inference dependencies

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#496]
- inference depends on a cblas library for SpeechUtils
It looks like fbgemm can do a gemm on its own (it's even in the name), but wav2letter libraries won't build without another cblas library present, due to the SpeechUtils cblasGemm function

- inference depends on gflags, which isn't mentioned in the [wiki](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-and-build-wav2letter-inference)
```
git clone https://github.com/gflags/gflags.git
cd gflags
cmake .
make && make install
```

**Comment by avidov** [comment]
> * inference depends on a cblas library for SpeechUtils
>   It looks like fbgemm can do a gemm on its own (it's even in the name), but wav2letter libraries won't build without another cblas library present, due to the SpeechUtils cblasGemm function

This is a good point. Currently inference reuses libraries/feature/FeatureParams.h which uses cblas, but we should use whatever backend inference is set to use (currently only supports FBGEMM but soon will support others for mobile platforms). I marked it as desired enhancement for now.

> inference depends on gflags, which isn't mentioned in the [wiki](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-and-build-wav2letter-inference)

Inference examples using gflags. CMake searches for it and download it if not found, so the wiki does not ask to install manually.

**Comment by lunixbochs** [comment]
> CMake searches for it and download it if not found, so the wiki does not ask to install manually.

This doesn't seem to happen for me:
```
-- Could NOT find GFlags (missing: GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY) 
CMake Error at inference/CMakeLists.txt:43 (message):
  GFLAGS not found
```

When running from wav2letter/build on a Mac
```
KENLM_ROOT_DIR=~/build/kenlm/build cmake .. -DW2L_BUILD_LIBRARIES_ONLY=ON -DW2L_BUILD_INFERENCE=ON -DW2L_LIBRARIES_USE_CUDA=OFF
```

**Comment by lunixbochs** [comment]
as fbgemm is already a dependency, maybe it's simpler to just always use a function from that for featurization?
