### ISSUE TITLE
Change data/librispeech/create.lua

### ISSUE THREAD

**Issue by grahamimac** [facebookresearch/wav2letter#5]
Hi all,

Thanks for putting this out there. I'm still building, but ran into an issue.

This is a bit of a small change for a pull request, so I just created an issue and hope you'll update/test. I had issues with running the first "Data pre-processing" step, specifically:

```
luajit ~/wav2letter/data/librispeech/create.lua ~/LibriSpeech ~/librispeech-proc
```

When run, I get the following output:

```
| parsing SPEAKERS.TXT for gender...
| analyzing /LibriSpeech/train-clean-100...
luajit: /wav2letter/data/librispeech/create.lua:54: cannot open /LibriSpeech/train-clean-100: No such file or directory
stack traceback:
	[C]: in function 'dir'
	/wav2letter/data/librispeech/create.lua:54: in function 'fileapply'
	/wav2letter/data/librispeech/create.lua:72: in function 'createidx'
	/wav2letter/data/librispeech/create.lua:152: in main chunk
	[C]: at 0x00405430
```

When I edit line 149 of `create.lua` from:

```
   local src = string.format("%s/%s", src, subpath)
```

to

```
   local src = string.format("%s", src)
```

it seems to work fine. 

There aren't corresponding directories in LibriSpeech as there are in librispeech-proc, so the subpath didn't make sense to me. I'm not a lua expert, nor do I know this codebase well, so I'm not sure this is the right solution here. I would very much appreciate someone else checking it out.

**Comment by vineelpratap** [comment]
Looks like you haven't downloaded train-clean-100 data. 
As mentioned in https://github.com/facebookresearch/wav2letter#data-pre-processing, please repeat the following step for train-clean-100, train-clean-360, train-other-500, dev-other, test-clean, test-other
```
wget http://www.openslr.org/resources/12/dev-clean.tar.gz
tar xfvz dev-clean.tar.gz
```

**Comment by grahamimac** [comment]
Gotcha, that makes sense. Wasn't entirely clear to me at the time. So as I understand it:

```
wget http://www.openslr.org/resources/12/dev-clean.tar.gz
tar xfvz dev-clean.tar.gz
# repeat for train-clean-100, train-clean-360, train-other-500, dev-other, test-clean, test-other
```

essentially means to do something like this:

```
for f in dev-clean train-clean-100 train-clean-360 train-other-500 dev-other test-clean test-other; do
wget http://www.openslr.org/resources/12/${f}.tar.gz
tar xfvz ${f}.tar.gz
done
```

Is that right?

**Comment by vineelpratap** [comment]
Yes, that's correct.
