### ISSUE TITLE
simple_streaming_asr_example uses too much memory for large wav files.

### ISSUE THREAD

**Issue by zxl777** [facebookresearch/wav2letter#501]
The wav file is 17 minutes long.
It started to recognize properly and worked fine. But memory usage continues to grow until server memory is exhausted.

When the previous audio part is recognized, can the previously used memory be automatically released?

**Comment by vineelpratap** [comment]
This is certainly not expected. We will debug and get back to you.

**Comment by avidov** [comment]
Will you please share debugging data? including the audio file and errors that you see.

**Comment by zxl777** [comment]
download 2.wav:
https://transfer.sh/%28/PquKh/2.wav%29.zip

command line:
sudo docker run --rm -v ~/ai/:/root/host/ -it --ipc=host --name w2l -a stdin -a stdout -a stderr wav2letter/wav2letter:inference-latest sh -c "/root/wav2letter/builinference/inference/examples/simple_streaming_asr_example --input_files_base_path  /root/host/model --input_audio_file /root/host/2.wav"

top screenshot:
<img width="671" alt="屏幕快照 2020-01-29 下午2 17 35" src="https://user-images.githubusercontent.com/816448/73332584-26b8c580-42a2-11ea-9fb1-328224ebb1d1.png">

**Comment by avidov** [comment]
Was able to reproduce using your example.

**Comment by avidov** [comment]
We are debugging this as a memory leak, will update you once we release a fix.

**Comment by zxl777** [comment]
Thank you and look forward to updates.

**Comment by xuqiantong** [comment]
Should have been solved with commit 7a9696dc2f7518642a3f1908d6ed298901e108c0.

**Comment by zxl777** [comment]
Worked!
Completed converting audio input file=/root/host/2.wav to text... elapsed time=489 seconds
Memory occupancy is stable and there seems to be no memory leak.
Thank you.

**Comment by LilTinkk** [comment]
do not email me your contact me I don't know who you are I have already reported you to the authorities stop emailing meLaurie MeltonOn Feb 16, 2020 3:37 AM, Sky <notifications@github.com> wrote:Worked!
Completed converting audio input file=/root/host/2.wav to text... elapsed time=489 seconds
Memory occupancy is stable and there seems to be no memory leak.
Thank you.
