### ISSUE TITLE
Are there any plans to add punctuation ?

### ISSUE THREAD

**Issue by zxl777** [facebookresearch/wav2letter#502]
Is it possible to have periods to separate sentences, that would be great.

**Comment by tlikhomanenko** [comment]
@zxl777,

Could explain details/give an example what do you mean exactly?

**Comment by JanX2** [comment]
@tlikhomanenko, 
I guess @zxl777 means hallucinating punctuation similarly to how <https://www.speechmatics.com> does it: derive punctuation from the language model’s tree.

**Comment by zxl777** [comment]
I mean, add the following text with punctuation.

`as your click numbers go up your brand recognition increases and the more that grows the more confident people become in the integrity of your content and communications`

To

`As your click numbers go up, your brand recognition increases. And the more that grows, the more confident people become in the integrity of your content and communications.`

**Comment by tlikhomanenko** [comment]
@zxl777,

In this case you can train acoustic model having `.,!?` in the tokens set and the same for language model and then it will infer punctuation for you. The only thing for postprocessing is to capitalize words if they have `.?!` before.

Another option is to use some NLP tools.

**Comment by zxl777** [comment]
@tlikhomanenko  Thank you, I understand. 
I have found the right NLP tool to solve this problem.

**Comment by JanX2** [comment]
@zxl777 
Could you please tell us more about your solution?

**Comment by zxl777** [comment]
@JanX2 Search "natural language processing in python"

I have chose the https://spacy.io/
