### ISSUE TITLE
Will the transformer model trained on LibriSpeech only be released ?

### ISSUE THREAD

**Issue by lenassero** [facebookresearch/wav2letter#504]
Only the transformer model trained on LibriSpeech + LibriVox seems available. 
Will the one trained on LibriSpeech alone be released ? This is the one used in Section 3.4 of the paper to pseudo label utterances from LibriVox:

"We then generate pseudo-labels for this audio using the recipe described in [2]. To generate the pseudo-labels, we use an Transformer AM trained on LIBRISPEECH with CTC loss that achieves a 6.38%WER on dev-other when decoded with a 4-gramword LM – the same model as is listed in Table 2. We pseudo-label all audio using this AM and 4-gram decoding using a smaller beam size to increase decoding speed"

**Comment by tlikhomanenko** [comment]
Hi @lenassero 

Yep, it will be available in several days, working its release and ConvLM decoding configs!

**Comment by lenassero** [comment]
Nice, thanks @tlikhomanenko !

**Comment by tlikhomanenko** [comment]
Hi @lenassero,

Finally we release Transformer CTC (Librispeech only) model, also decoding parameters for GCNN LM also released here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019.

**Comment by lenassero** [comment]
Super, thanks @tlikhomanenko :)

**Comment by tuanphan09** [comment]
@tlikhomanenko Is it possible to reproduce SOTA result with transformer based for AM now? #519

**Comment by tlikhomanenko** [comment]
@tuanphan09, we didn't release warmup yet, but feel free to use  the code and comments from https://github.com/facebookresearch/wav2letter/issues/519. Recipe is correct and should be able to reproduce.

**Comment by webbp** [comment]
Is it your intention to release warmup? If so, is there an approximate ETA? Thanks!

**Comment by tlikhomanenko** [comment]
Yep, clearing a bit the code, but here are some latest commits for warmup db673a2dc67662d9d097decc1b8733e1755c51ba, 76c4e04942fd456ac4db632c9a7fa9b31bb432ce. 

We are planning to release all code during next week.
