### ISSUE TITLE
[PSA] wav2train - align arbitrary audio+transcripts into a wav2letter training corpus

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#509]
I'm releasing a new tool called [wav2train](https://github.com/talonvoice/wav2train) based on my experience building wav2letter training sets.

It uses DSAlign internally to align arbitrarily large audio files with a matching .txt transcript, directly into the wav2letter training data layout.

Basically, it takes an `input/` directory with any number of audio file + .txt pairs and generates an `output/` wav2letter corpus like:

```
input/name1.wav input/name1.txt
input/name2.mp3 input/name2.txt
input/name3.ogg input/name3.txt
input/name4.sph input/name4.txt
input/name5.flac input/name5.txt
->
output/clips/*.flac
output/clips.lst
output/train.lst
output/dev.lst
output/test.lst
```

Usage:
```
./wav2train input/ output/
./wsplit output/clips.lst
```

**Comment by cri5Castro** [comment]
is english only ready right? I mean i need to make some changes to use it in other languages?

**Comment by lunixbochs** [comment]
It uses DSAlign. If you want to use it on another language, you'll need to add DSAlign support for that, which I think just requires DeepSpeech models.

**Comment by lunixbochs** [comment]
Here's an example where I aligned an arbitrary book from librivox to the Project Gutenberg source text: https://talonvoice.com/dl/align-example.tar.gz

I just ran `./wav2train input/ output/` and it generated the output in this archive.

**Comment by lunixbochs** [comment]
I added a wav2letter transcription backend. I've also packaged my optimized static wav2letter CPU build and one of my compact models for _significantly_ faster transcription than DSAlign's included DeepSpeech model. Please note this is an older build of wav2letter (from the github.com/talonvoice/wav2letter decoder branch), so it doesn't support the newer transformer models or anything.

This should work out of the box on modern Mac/Linux:
```
wget https://talonvoice.com/research/w2l-align.tar.xz
tar -xf w2l-align.tar.xz
./wav2train -m w2l-align/ input/ output/
```

A test 906s file took ~45s to align on a dual core laptop with my wav2letter model. Only 10 seconds of that were transcription, the rest was building a language model and the Python code aligning the transcript.

**Comment by cri5Castro** [comment]
awesome thanks
