### ISSUE TITLE
Transcript not created during inference

### ISSUE THREAD

**Issue by mvarvani** [facebookresearch/wav2letter#510]
To whom it may concern,

I followed the "Simple Streaming ASR Example using Docker (super easy)" tutorial. At the end when it returns "Completed converting audio input from stdin to text ...", the transcript file is not created in the folder. No error was returned.

**Comment by avidov** [comment]
[simple_streaming_asr_example](
https://github.com/facebookresearch/wav2letter/blob/master/inference/inference/examples/SimpleStreamingASRExample.cpp)
Prints the transcription to stdout not to file. 

You can redirect that output to a file or use the [multithreaded_streaming_asr_example](https://github.com/facebookresearch/wav2letter/blob/master/inference/inference/examples/MultithreadedStreamingASRExample.cpp)
The tutorial teaches how to use [multithreaded_streaming_asr_example](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#multithreaded-streaming-asr-example) that you download and build on your machine, but it can be done using the docker file as well.

following your post I added a tutorial section for doing what you asked:
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#Multithreaded-streaming-ASR-example-using-Docker

Please let e know how it works for you.
