### ISSUE TITLE
Receptive field computation of seq2seq TDS

### ISSUE THREAD

**Issue by lenassero** [facebookresearch/wav2letter#512]
Hi, 

I have computed the receptive field for the TDS encoder described in "Sequence-to-Sequence Speech Recognition with Time-Depth Separable Convolutions" (model architecture [here](https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/seq2seq_tds/librispeech/network.arch)).

The paper shows a receptive field of 14.2 seconds in _Figure 2_.
However, I get 4.225 seconds (281 frames, where `receptive_field_ms = 25 * receptive_field_frames - 10 * (receptive_field_frames-1)`)

Here is how I did the computation:
```python
def get_context_size(num_layers, kernel_size, initial_context, stride):
    return initial_context + (kernel_size - 1) * (1  + (num_layers - 1) * stride)

def get_receptive_field_frames(kernel_size, kernel_size_subsampling=None):
    if kernel_size_subsampling is None:
        kernel_size_subsampling = kernel_size

    # Subsampling 1
    context_subsampling_1 = get_context_size(1, kernel_size_subsampling, 1, 1)

    # Group 1
    context_group_1_tds_1 = get_context_size(1, kernel_size, context_subsampling_1, 2)
    context_group_1_tds_2 = get_context_size(1, kernel_size, context_group_1_tds_1, 1)

    # Subsampling 2
    context_subsampling_2 = get_context_size(1, kernel_size_subsampling, context_group_1_tds_2, 1)

    # Group 2
    context_group_2_tds_1 = get_context_size(1, kernel_size, context_subsampling_2, 2)
    context_group_2_tds_rest = get_context_size(2, kernel_size, context_group_2_tds_1, 1)

    # Subsampling 3
    context_subsampling_3 = get_context_size(1, kernel_size_subsampling, context_group_2_tds_rest, 1)

    # Group 3
    context_group_3_tds_1 = get_context_size(1, kernel_size, context_subsampling_3, 2)
    context_group_3_tds_rest = get_context_size(5, kernel_size, context_group_3_tds_1, 1)
    return context_group_3_tds_rest

> get_receptive_field_frames(21)
```

I am probably missing something ...
Thanks!

**Comment by vineelpratap** [comment]
Here is a script that we generally use to compute the receptive field - https://gist.github.com/vineelpratap/45900ff43bedbf1264dc93b745c6506f

**Comment by lenassero** [comment]
Thanks @vineelpratap, I forgot to propagate the stride in my formula, I do finally get to the same result 👍
