### ISSUE TITLE
fine tune pretrained model

### ISSUE THREAD

**Issue by jianminsun** [facebookresearch/wav2letter#513]
I have some problem with fine tuning wav2letter's pretrained models. 

I download seq2seq_tds model baseline_dev-other.bin to a folder.
Running following command:
build/Train fork /w2l/am/baseline_dev-other.bin --flagsfile /root/wav2letter/recipes/models/seq2seq_tds/librispeech/train.cfg

and got error:
F0131 18:21:20.625896 11369 W2lListFilesDataset.cpp:105] Could not read file '/mnt/vol/gfsai-east/ai-group/users/annl/speech/datasets//w2l/LibriSpeech/lists/train-clean-100.lst'

my list file is at /w2l/LibriSpeech/lists/train-clean-100.lst. For some reason wav2letter add 
/mnt/vol/gfsai-east/ai-group/users/annl/speech/datasets/ to the file path. I wonder how to avoid this problem.

EDIT: add flagfile and it is working well to train and fork the models I trained locally
runname=seq2seq_tds_distributed
--rundir=/w2l
--tokensdir=/w2l/am
--archdir=/root/wav2letter/recipes/models/seq2seq_tds/librispeech
--train=/w2l/LibriSpeech/lists/train-clean-100.lst,/w2l/LibriSpeech/lists/train-clean-360.lst,/w2l/LibriSpeech/lists/train-other-500.lst
--valid=dev-clean:/w2l/LibriSpeech/lists/dev-clean.lst,dev-other:/w2l/LibriSpeech/lists/dev-other.lst
--lexicon=/w2l/am/librispeech-train+dev-unigram-10000-nbest10.lexicon
--arch=network.arch
--tokens=librispeech-train-all-unigram-10000.tokens
--criterion=seq2seq
--lr=0.05
--lrcrit=0.05
--momentum=0.0
--stepsize=40
--gamma=0.5
--maxgradnorm=15
--mfsc=true
--dataorder=output_spiral
--inputbinsize=25
--filterbanks=80
--attention=keyvalue
--encoderdim=512
--attnWindow=softPretrain
--softwstd=4
--trainWithWindow=true
--pretrainWindow=3
--maxdecoderoutputlen=120
--usewordpiece=true
--wordseparator=_
--sampletarget=0.01
--target=ltr
--batchsize=16
--labelsmooth=0.05
--nthread=6
--memstepsize=4194304
--eostoken=true
--pcttraineval=1
--pctteacherforcing=99
--iter=400
--enable_distributed=true

**Comment by lunixbochs** [comment]
Can you post your flagsfile contents?

**Comment by lunixbochs** [comment]
I think you need to set one of the flags like `datadir`

**Comment by jianminsun** [comment]
add --datadir=/ 
works for seq2seq_tds, thanks a lot. I am going to test sota models.
