### ISSUE TITLE
sota/2019 architecture maxpool

### ISSUE THREAD

**Issue by aask1357** [facebookresearch/wav2letter#514]
In the `am_transformer_s2s.arch` and `am_transformer_s2s_librivox.arch` file, maxpool layers are written as
```M 1 1 2 1```
which is 1x1 filter with x_stride=2 meaning it discards even numbered frames.

However, the paper (https://arxiv.org/abs/1911.08460) says `max-pooling over 2 frames`, and I think it should be
```M 2 1 2 1```
which is 2x1 filter with x_stride=2.

Is there any reason for using the above, not below?

**Comment by syhw** [comment]
Yes, this was a bug, we corrected it subsequently but the models we released have it, it makes no difference in WER (it just stupidly not efficient).
