### ISSUE TITLE
Any idea why my serialized models are much larger than yours?

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#515]
https://dl.fbaipublicfiles.com/wav2letter/sota/2019/am/am_transformer_s2s.arch
https://dl.fbaipublicfiles.com/wav2letter/sota/2019/librispeech/models/am/am_transformer_s2s_librispeech_dev_other.bin - 1.1GB

But if I train for 1 epoch I get a 2.1GB model. And ~4GB for the librivox transformer model instead of your 2GB. Is there some way to make Cereal output smaller models?

**Comment by yoks** [comment]
I found this issue if you use non SGD optimizer (momentum 0). If you use any other optimizer or specify momentum, model bloats 2 times in size.

**Comment by lunixbochs** [comment]
I’m using the same optimizer from their paper and config though

**Comment by vineelpratap** [comment]
Hi, it is because we store some state variables required for optimizers. Also, would recommend you to use rebase flaslight past this commit https://github.com/facebookresearch/flashlight/commit/857cf54f83dbc66f57a7465325edb884d490312f which fixes storing those variables as float instead of double.

**Comment by lunixbochs** [comment]
Thanks! Do the released models have the optimizer state stripped out, or just the double->float fix?

**Comment by vineelpratap** [comment]
Hi,
  I see that most of the models contain the optimizer state but you shouldn't rely on optimizer state in the released models. We don't give any guarantees about its existence.
