### ISSUE TITLE
Slow training - GPU usage is low

### ISSUE THREAD

**Issue by mailong25** [facebookresearch/wav2letter#516]
I train wav2letter on my own language with approximately 100K utterance ( ~10sec/utterance).
I using librespeech tutorial recipes with wav2vec feature instead of MFCC.
It took about 1h30m to complete an epoch. GPU usage equal to zero most of the time, sometimes it peaked at 25%. I'm using 1 Tesla V100 on Google cloud.
Here is my training log:

```
epoch:        1 | lr: 0.100000 | lrcriterion: 0.000000 | runtime: 01:34:59 | bch(ms): 557.78 | smp(ms): 538.41 | fwd(ms): 9.84 | crit-fwd(ms): 4.95 | bwd(ms): 6.97 | optim(ms): 1.56 | loss:    7.66140 | train-TER: 37.66 | train-WER: 69.15 | /home/sa47/source/stt/data16k/valid.lst-loss:    6.70531 | /home/sa47/source/stt/data16k/valid.lst-TER: 27.56 | /home/sa47/source/stt/data16k/valid.lst-WER: 52.55 | avg-isz: 333 | avg-tsz: 065 | max-tsz: 291 | hrs:   75.64 | thrpt(sec/sec): 47.78
------
epoch:        2 | lr: 0.100000 | lrcriterion: 0.000000 | runtime: 01:28:42 | bch(ms): 520.89 | smp(ms): 501.88 | fwd(ms): 9.63 | crit-fwd(ms): 4.91 | bwd(ms): 6.88 | optim(ms): 1.53 | loss:    4.63750 | train-TER: 23.57 | train-WER: 48.87 | /home/sa47/source/stt/data16k/valid.lst-loss:    6.03578 | /home/sa47/source/stt/data16k/valid.lst-TER: 24.87 | /home/sa47/source/stt/data16k/valid.lst-WER: 46.71 | avg-isz: 333 | avg-tsz: 065 | max-tsz: 291 | hrs:   75.64 | thrpt(sec/sec): 51.16
```

**Comment by lunixbochs** [comment]
Add a batchsize to the flags. I typically use at least 4 on a v100, and up to 32 or so depending on the model size. Also the tutorial recipes aren’t the best. Try the wsjarch recipe, or the librispeech conv_glu recipe.

**Comment by mailong25** [comment]
Hi @lunixbochs. Do you have any comments on the GPU usage of my case, I don't know why it equal to zero most of the time. Is there any problem with data loading?

![image](https://user-images.githubusercontent.com/12481660/73716910-eb5b4280-474a-11ea-93e3-a729844e6bfc.png)

**Comment by mailong25** [comment]
Another case when I train on a tiny dataset. The first epoch took 11m but other only around 1m30s?. GPU usage on the first epoch is pretty low (0% most of the time) while this number is about 50-60% on other epochs
.
epoch:        1 | lr: 0.100000 | lrcriterion: 0.000000 | runtime: 00:11:05 | bch(ms): 283.12 | smp(ms): 260.85 | fwd(ms): 9.67 | crit-fwd(ms): 5.18 | bwd(ms): 7.45 | optim(ms): 3.17 | loss:   18.32647 | train-TER: 73.09 | train-WER: 100.11 | /home/sa47/source/stt/data16k/valid.txt-loss:   16.77386 | /home/sa47/source/stt/data16k/valid.txt-TER: 68.39 | /home/sa47/source/stt/data16k/valid.txt-WER: 99.78 | avg-isz: 276 | avg-tsz: 070 | max-tsz: 291 | hrs:   14.42 | thrpt(sec/sec): 78.06
--- 
epoch:        2 | lr: 0.100000 | lrcriterion: 0.000000 | runtime: 00:01:12 | bch(ms): 30.83 | smp(ms): 11.27 | fwd(ms): 8.64 | crit-fwd(ms): 5.02 | bwd(ms): 6.32 | optim(ms): 2.70 | loss:   14.96199 | train-TER: 63.44 | train-WER: 95.27 | /home/sa47/source/stt/data16k/valid.txt-loss:   13.04202 | /home/sa47/source/stt/data16k/valid.txt-TER: 57.59 | /home/sa47/source/stt/data16k/valid.txt-WER: 90.75 | avg-isz: 276 | avg-tsz: 070 | max-tsz: 291 | hrs:   14.42 | thrpt(sec/sec): 716.76
--
epoch:        3 | lr: 0.100000 | lrcriterion: 0.000000 | runtime: 00:01:12 | bch(ms): 31.05 | smp(ms): 11.31 | fwd(ms): 8.65 | crit-fwd(ms): 5.08 | bwd(ms): 6.42 | optim(ms): 2.74 | loss:   12.13611 | train-TER: 52.99 | train-WER: 85.31 | /home/sa47/source/stt/data16k/valid.txt-loss:   10.80348 | /home/sa47/source/stt/data16k/valid.txt-TER: 47.46 | /home/sa47/source/stt/data16k/valid.txt-WER: 79.00 | avg-isz: 276 | avg-tsz: 070 | max-tsz: 291 | hrs:   14.42 | thrpt(sec/sec): 711.71

**Comment by lunixbochs** [comment]
You can't really use the gpu much on small architectures without a decent batch size, and you still hit other limitations. You should make your architecture larger and increase the batch size. 700 sec/sec is pretty good! You might be saturating your disk or something. Run atop or htop while training and see how overall system utilization is.

**Comment by mailong25** [comment]
Exactly disk saturation !

![image](https://user-images.githubusercontent.com/12481660/73721018-df28b280-4755-11ea-885a-ac987130de70.png)
.
![image](https://user-images.githubusercontent.com/12481660/73721192-4ba3b180-4756-11ea-9a8e-c6306dd36c90.png)

**Comment by tlikhomanenko** [comment]
Feel free to reopen if it is needed.

**Comment by mnpham0417** [comment]
@mailong25 can you share how you can use wav2vec features instead of MFCC for the tutorials? Thank you.
