### ISSUE TITLE
Broken lexicon link at streaming_convnets recipe

### ISSUE THREAD

**Issue by oplatek** [facebookresearch/wav2letter#517]
Hi!

This link is broken: https://dl.fbaipublicfiles.com/wav2letter/streaming_convnets/librispeech/librispeech-train+dev-unigram-10000-nbest10.lexicon

See https://github.com/facebookresearch/wav2letter/blame/master/recipes/models/streaming_convnets/librispeech/README.md#L101

**Comment by vineelpratap** [comment]
Hi,
 Could you try this link instead - https://dl.fbaipublicfiles.com/wav2letter/tds/librispeech/librispeech-train%2Bdev-unigram-10000-nbest10.lexicon 

I have also sent a PR for the same - https://github.com/facebookresearch/wav2letter/pull/531

**Comment by oplatek** [comment]
Thanks! The above link works for me
