### ISSUE TITLE
No output when training still running?

### ISSUE THREAD

**Issue by juunnn** [facebookresearch/wav2letter#522]
So I run training with 1000 epoch I check the log file frequently to know that the prosess still running. Atfer 64 epoch it stop giving anything in the log file, but when I check the process using htop the training process is still running. I am using docker that I pulled from this [link](https://hub.docker.com/r/wav2letter/wav2letter/tags) and using 8 GTX1080 GPUs, is there any configuration that I have done wrong?
Thank you in advance.

**Comment by tlikhomanenko** [comment]
Hi @juunnn,

could you provide all details on your configuration to understand what could be wrong and how can we reproduce it? Details which exact docker image you are using, how you start docker container, how did you run training command and with which config file. Also could you attach log of training and screenshot of nvidia-smi and memory usage. 

If you kill the job and run training in continue mode is it going ok?

**Comment by juunnn** [comment]
The continue command is doing fine, it just stops logging after 64 epoch so I have to continue the training command over and over again. And because of the logging stop, I cannot ensure that the training is still running so I check the htop it still doing some processes.
The training command I use is `mpirun -n 4 --allow-run-as-root /root/wav2letter/build/Train continue path/to/exp --flagsfile fork.cfg`

this is the fork.cfg file
```
# Training config for Librispeech using Time-Depth Separable Convolutions
# Replace `[...]`, `[MODEL_DST]`, `[DATA_DST]`, `[DATA_DST_librilight] with appropriate paths
--runname=exp1
--rundir=./models/streaming

--tokensdir=./data/batches/txt
--tokens=tokens

--archdir=./config/streaming
--arch=network.arch

--datadir=./data/batches/lists
--train=train
--valid=test
#--test=test.lst

--lexicon=./data/batches/txt/lexicon

--criterion=ctc
--lr=0.24
--lrcosine=true
--momentum=0.1
--maxgradnorm=0.5
--iter=1000

--nthread=6
--batchsize=6

--mfsc=true
--usewordpiece=true
--wordseparator=|
--filterbanks=80

--minisz=200
--mintsz=2
--maxisz=33000

--enable_distributed=true
--pcttraineval=1
--minloglevel=0

--alsologtostderr=true

--onorm=target
--sqnorm

--localnrmlleftctx=300
```

the command to use docker is provided here
`docker run --runtime=nvidia -itd --ipc=host --volume /data/jun/w2l/:/exp --volume /data/suara/:/dataset --name w2lbaru wav2letter/wav2letter:cuda-latest`

The nvidia-smi looks like this 
![image](https://user-images.githubusercontent.com/24216927/74116722-6ad39080-4be7-11ea-80b2-16819ca451f5.png)

The log from the logging dir looks like this
![image](https://user-images.githubusercontent.com/24216927/74117015-a589f880-4be8-11ea-8c83-59fedd85af9c.png)

Is there anything I can do?

**Comment by tlikhomanenko** [comment]
hi @juunnn,

Please add `--minloglevel=0 --logtostderr=1` to have error log too inside docker container. My guess is that some thread is crashed but the others are still hanging and job is not finished normally. So with these additional params you could monitor them. Also this could be helpful https://stackoverflow.com/questions/50273012/openmpi-doesnt-kill-other-rank-when-one-rank-crashes/50273172#50273172 in this case.

**Comment by juunnn** [comment]
![image](https://user-images.githubusercontent.com/24216927/74295850-c7b08180-4d74-11ea-90fe-16148f940e52.png)
I forgot to attach this. This error, that I think come from mpirun, occured when I try to continue the training. Is this the same error that trying to solve with the link you sent?
Thanks,

**Comment by tlikhomanenko** [comment]
The link I sent is different, but you could try to follow the suggestion of log too and do (details on this param see in https://www.open-mpi.org/faq/?category=debugging)
```
mpirun --mca orte_base_help_aggregate 0 ...
```

**Comment by juunnn** [comment]
Hi @tlikhomanenko , I tried both the `--mca orte_base_help_aggregate 0` and `-mca orte_abort_on_non_zero_status 1` to my option on running mpirun but the problem remains the same. Also the log when I use `--minloglevel=0 --logtostderr=1` is empty. Should I try to use another docker image?

**Comment by abramovi** [comment]
Having the same issue.

**Comment by tlikhomanenko** [comment]
@juunnn, @abramovi,

You can try to use latest images and test if the problem still exists. To monitor if the problem is really in crashing one of the threads - you can check if your latest snapshot is updated or not. As soon as you have no log output and (if you confirm) that snapshot is not updated then the problem is really in crashing one of the threads. 

Can you run on 2 and 8 gpus and test if this behaviour is reproduced for them too?

**Comment by abramovi** [comment]
@tlikhomanenko I am going to test with latest docker - but It fail for me with 8 and 4 gpu and the latest snapshot is not updated.
![image](https://user-images.githubusercontent.com/770839/77831686-b0213280-7141-11ea-8b72-8697023e0076.png)

going to try now with latest docker

**Comment by abramovi** [comment]
can reproduce it with latest docker .

**Comment by tlikhomanenko** [comment]
@abramovi 

could you send all steps how to reproduce the issue?

**Comment by tlikhomanenko** [comment]
close due to inactivity, please try our latest flashlight where we merged together fl and w2l codebases and improved a bunch of things.
