### ISSUE TITLE
Pipe or underscore in lexicon

### ISSUE THREAD

**Issue by BoneGoat** [facebookresearch/wav2letter#526]
Hi,

I've successfully trained models on my own dataset last year. Recently I made some additions to the dataset so I figured I would try to train a new model. This time I cannot make it learn anything except if I modify the lexicon. When I last trained models the lexicon was supposed to contain lines like this:
word w o r d |

To make the training work I had to remove the pipe character from the lexicon. When I did that the train WER started to go down. Unfortunately when I decode using the model it will stop early. When I feed it a 5 min audio it will output around three words. This was working fine last year and the entire audio was transcribed.

Now looking at the recipes I get confused about how to format the lexicon.

conv_glu (using pipe)
https://github.com/facebookresearch/wav2letter/blob/63326c174a83155661415f3e059faf52a4373d5c/recipes/models/conv_glu/librispeech/train.cfg#L19
consistent with the prepare script:
https://github.com/facebookresearch/wav2letter/blob/63326c174a83155661415f3e059faf52a4373d5c/recipes/models/conv_glu/librispeech/prepare.py#L83

lexicon_free (same as conv_clu)

seq2seq_tds does not specify the surround param but does specify the wordseparator param:
https://github.com/facebookresearch/wav2letter/blob/63326c174a83155661415f3e059faf52a4373d5c/recipes/models/seq2seq_tds/librispeech/train.cfg#L31

The wordseparator param is set to underscore which would match the prepare script which adds underscore to the lexicon instead of pipe:
https://github.com/facebookresearch/wav2letter/blob/63326c174a83155661415f3e059faf52a4373d5c/recipes/models/seq2seq_tds/librispeech/prepare.py#L117

The SOTA/2019 recipes also omits the surround param but sets the wordseparator param to underscore:
https://github.com/facebookresearch/wav2letter/blob/63326c174a83155661415f3e059faf52a4373d5c/recipes/models/sota/2019/librivox/train_am_tds_s2s.cfg#L35
and prepare:
https://github.com/facebookresearch/wav2letter/blob/63326c174a83155661415f3e059faf52a4373d5c/recipes/models/utilities/prepare_librispeech_wp_and_official_lexicon.py#L181

The wordseparator param is documented here:
https://github.com/facebookresearch/wav2letter/wiki/Beam-Search-Decoder#12-lexicon-free-beam-search-decoder-uselexiconfalse

But I'm confused if this is the same as surround param. Please explain how to properly format the lexicon.

**Comment by BoneGoat** [comment]
OK, so after running the prepare script for seq2seq_tds (downloading and processing about one billion GB of data) I can see that the format for both lexicon and tokens has changed. I'll just have to rewrite the scripts for my dataset.

**Comment by tlikhomanenko** [comment]
@BoneGoat,

One note: for recipes in their README we specified the version of w2l tag/commit with which they can be reproduced. So for example sota/2019 right now reproduced with current master, others could be not (for example we changed a bit logic of beam-search decoder recently).

So please use documentation as the latest update on parameters and their usage.

About your issue: if you are training letter based system still you should have lexicon as "word w o r d 
|" where you add `|` to separate the words. This lexicon is used to map exactly input transcription words to the sequence of tokens. So token file should contain `a-z` + `|`. Then you should set `--wordseparator=|` which is using to find word boundaries in generated tokens sequence to map then back to words and compute Viterbi WER.
