### ISSUE TITLE
Simple streaming ASR example using Docker fails

### ISSUE THREAD

**Issue by e-ndrus** [facebookresearch/wav2letter#527]
Trying to run the simple streaming ASR example with the provided Docker command on Ubuntu 18 throws the following error:

`sh: 1: /root/host/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav: not found
Started features model file loading ... 
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open feature file=/root/host/model/feature_extractor.bin for reading
Aborted (core dumped)`

Is there something what needs to be additionally installed for the provided Docker to work?

**Comment by e-ndrus** [comment]
Disregard this. Forgot to add audio files and the model.

**Comment by realbaker1967** [comment]
I do have the same problem. @e-ndrus could you please tell me how did you add audio files and the model?
