### ISSUE TITLE
Question: tensorboard compatibility

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#528]
hi there is there any way log the training process in tensorboard format?

**Comment by lunixbochs** [comment]
no, that's a cool idea though - tensorboard format is here https://github.com/tensorflow/tensorboard/issues/72#issuecomment-319839210

**Comment by vineelpratap** [comment]
Here is script that we generally use - https://gist.github.com/vineelpratap/4e7ee1c5b576a5d0d08bd1b1d868ad6f. However, it works with  only tf 1.14. Let us know if you are able to make it work with tf 2.0 .

**Comment by tlikhomanenko** [comment]
Feel free to reopen if it is needed.
