### ISSUE TITLE
Facing "attempt to index a nil value" during creating LibriSpeech training data

### ISSUE THREAD

**Issue by IrishCoffee** [facebookresearch/wav2letter#53]
I am creating the LibriSpeech training dataset. 

I have already downloaded the required dataset, such as "dev-clean".... When I executed the command "luajit data/librispeech/create.lua LibriSpeech/ librispeech-proc", I encountered an error as follows.

| parsing SPEAKERS.TXT for gender...
luajit: data/librispeech/create.lua:51: attempt to index a nil value
stack traceback:
        data/librispeech/create.lua:51: in main chunk
        [C]: at 0x00405d50

Is there any ideas about this error? Thanks.

**Comment by bolt163** [comment]
do you installed the  libsndfile's  dependency libraries e.g. flac?

**Comment by vineelpratap** [comment]
Looks like you haven't specified the input and output path for the command. Please see https://github.com/facebookresearch/wav2letter#data-pre-processing for reference.
