### ISSUE TITLE
How to compile beam_search decoder ?

### ISSUE THREAD

**Issue by Sundy1219** [facebookresearch/wav2letter#533]
Hi,I have a question:
Now, I just want to use your beam_search decoder. i can pass some parameters to it. How to compile beam_search decoder separately．can you give me some guides ？
thanks !!!!

**Comment by an918tw** [comment]
Check out the build options here https://github.com/facebookresearch/wav2letter/wiki/General-building-instructions. You can turn off the ones you don't need, e.g. recipes, tests, etc.

**Comment by tlikhomanenko** [comment]
Hi @Sundy1219,

you can also try to use docker image where everything is compiled already https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker

**Comment by Sundy1219** [comment]
Thanks for your reply. now i just want decoder module. and i need to intergrate it with other framework. g++ compiler is better. thanks

**Comment by xuqiantong** [comment]
@Sundy1219 @an918tw was correct, You just need to switch on `W2L_BUILD_LIBRARIES_ONLY` and a static library, including decoder module as well as LM, dictionary, etc., will be created.

**Comment by tlikhomanenko** [comment]
Feel free to reopen if it is needed.
