### ISSUE TITLE
Error seq2seq decoding

### ISSUE THREAD

**Issue by shessam** [facebookresearch/wav2letter#535]
if i run: /root/wav2letter/build/Decoder --flagsfile=/root/wav2letter/recipes/models/seq2seq_tds/librispeech/decode_convlm_clean.cfg --minloglevel=0 --logtostderr=1

I have this error:
I0213 22:21:25.079392 25647 Decode.cpp:75] [Network] Reading acoustic model from root/w2l/seq2seq_tds_distributed/001_model_dev-clean.bin
E0213 22:21:25.106351 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:26.106592 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:28.106880 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:32.107168 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:40.107458 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:56.107745 25647 Serial.h:74] Error while loading: failed to open file for reading
terminate called after throwing an instance of 'std::runtime_error'
what(): failed to open file for reading
*** Aborted at 1581632516 (unix time) try "date -d @1581632516" if you are using GNU date ***
PC: @ 0x7fc388390428 gsignal
*** SIGABRT (@0x642f) received by PID 25647 (TID 0x7fc3d5b74600) from PID 25647; stack trace: ***
@ 0x7fc3cde7f390 (unknown)
@ 0x7fc388390428 gsignal
@ 0x7fc38839202a abort
@ 0x7fc388cd384d __gnu_cxx::__verbose_terminate_handler()
@ 0x7fc388cd16b6 (unknown)
@ 0x7fc388cd1701 std::terminate()
@ 0x7fc388cd1969 __cxa_rethrow
@ 0x48c6ee ZN3w2l16retryWithBackoffIRFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt13unordered_mapIS6_S6_St4hashIS6_ESt8equal_toIS6_ESaISt4pairIS7_S6_EEERSt10shared_ptrIN2fl6ModuleEERSJ_INS_17SequenceCriterionEEEJS8_SI_SN_SQ_EEENSt9result_ofIFT_DpT0_EE4typeENSt6chrono8durationIdSt5ratioILl1ELl1EEEEdlOSU_DpOSV.constprop.6525
@ 0x4191be main
@ 0x7fc38837b830 __libc_start_main
@ 0x4899f9 _start
@ 0x0 (unknown)
Aborted (core dumped)

**Comment by shessam** [comment]
if i run: /root/wav2letter/build/Decoder --flagsfile=/root/wav2letter/recipes/models/seq2seq_tds/librispeech/decode_convlm_clean.cfg --minloglevel=0 --logtostderr=1

I have this error:
I0213 22:21:25.079392 25647 Decode.cpp:75] [Network] Reading acoustic model from root/w2l/seq2seq_tds_distributed/001_model_dev-clean.bin
E0213 22:21:25.106351 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:26.106592 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:28.106880 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:32.107168 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:40.107458 25647 Serial.h:74] Error while loading: failed to open file for reading
E0213 22:21:56.107745 25647 Serial.h:74] Error while loading: failed to open file for reading
terminate called after throwing an instance of 'std::runtime_error'
what(): failed to open file for reading
*** Aborted at 1581632516 (unix time) try "date -d @1581632516" if you are using GNU date ***
PC: @ 0x7fc388390428 gsignal
*** SIGABRT (@0x642f) received by PID 25647 (TID 0x7fc3d5b74600) from PID 25647; stack trace: ***
@ 0x7fc3cde7f390 (unknown)
@ 0x7fc388390428 gsignal
@ 0x7fc38839202a abort
@ 0x7fc388cd384d __gnu_cxx::__verbose_terminate_handler()
@ 0x7fc388cd16b6 (unknown)
@ 0x7fc388cd1701 std::terminate()
@ 0x7fc388cd1969 __cxa_rethrow
@ 0x48c6ee ZN3w2l16retryWithBackoffIRFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt13unordered_mapIS6_S6_St4hashIS6_ESt8equal_toIS6_ESaISt4pairIS7_S6_EEERSt10shared_ptrIN2fl6ModuleEERSJ_INS_17SequenceCriterionEEEJS8_SI_SN_SQ_EEENSt9result_ofIFT_DpT0_EE4typeENSt6chrono8durationIdSt5ratioILl1ELl1EEEEdlOSU_DpOSV.constprop.6525
@ 0x4191be main
@ 0x7fc38837b830 __libc_start_main
@ 0x4899f9 _start
@ 0x0 (unknown)
Aborted (core dumped)


flagsfile content (decode_convlm_clean.cfg):
--am=root/w2l/seq2seq_tds_distributed/001_model_dev-clean.bin
--tokensdir=root/w2l/am
--tokens=librispeech-train-all-unigram-10000.tokens
--lexicon=root/w2l/am/librispeech-train+dev-unigram-10000-nbest10.lexicon
--lm=root/w2l/decoder/lm_librispeech_convlm_14B.bin
--datadir=root/w2l/LibriSpeech/lists
--test=test-clean.lst
--sclite=[...]
--uselexicon=false
--decodertype=tkn
--lmweight=0.5
--wordscore=1.0
--beamsize=80
--beamthreshold=7
--hardselection=1.5
--softselection=10.0
--attentionthreshold=30
--nthread_decoder=2
--smearing=max
--show=true
--lmtype=convlm
--lm_memory=3000
--lm_vocab=root/w2l/decoder/lm_librispeech_convlm_14B.vocab

**Comment by tlikhomanenko** [comment]
Hi @shessam,

One thing to fix in the config (which is not related to the current issue, but will cause another error) is to fix `--sclite=[...]` to `--sclite=path/where/to save` or remove just this flag if you need only the final WER of decoding.

About your issue:
why do you have the path starting with `root/` and not with `/root`? Is this correct? Please try to put absolute paths for all files in the config. If you look at your error `Error while loading: failed to open file for reading` this means that am file doesn't exist.

**Comment by joazoa** [comment]
Are you sure your model is ok ? I have seen the same error with corrupted models.

**Comment by tlikhomanenko** [comment]
Feel free to reopen if you need more assistance on the issue!
