### ISSUE TITLE
maxDevicePerNode is hardcoded

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#536]
It looks like wav2letter only allows training with 8 GPUs per node. When I tried training with two 1-GPU nodes, I got an arrayfire index error.

https://github.com/facebookresearch/wav2letter/blob/08945f8ea0a433e2d12785a939b3b1af7cddfc85/src/common/Defines.h#L103

https://github.com/facebookresearch/wav2letter/blob/7f26987159af7d211078746c2559a4244e17171d/src/runtime/Distributed.cpp#L25-L26

**Comment by jacobkahn** [comment]
@lunixbochs — I can try to make a change that fixes this in the next week or so. It may require a bit if reconfiguration of some flashlight internals, but I should be able to make it work.

If you want this change before then, feel free to submit a PR, and I'll take a look.

**Comment by lunixbochs** [comment]
I hacked in a wav2letter flag with my build -devices_per_node that replaces the define and it worked, I’d recommend something like that. It won’t work for someone who wants complex topologies, I don’t really know the answer to that. But it works for N cards per host. If you want the code I can extract it from the larger diff but it was pretty much the obvious answer (add an int64 flag, remove the define, pass the flag into initDistributed).

Anyway I have distributed training running now and it’s working great! I have a methodology for using GCP preemptible instances, along with a control script running against the GCP API that handles instances coming/going and checkpointing on every epoch. I’ll probably post the info sometime and talk about requested changes to w2l to better support it (e.g. I also added a -single_epoch flag as iters=1 didn’t really work)

**Comment by jacobkahn** [comment]
@lunixbochs - nice to know that works. We can make that configurable in flashlight and wav2letter I suppose. We're probably not going to add the ability to express more complex topologies at the moment.

That's really cool that you have multinode training working on GCP! Would you be interested in writing up a tutorial/instructions/sharing any wisdom there? Would be a great thing to add to our docs or a wiki on the repo.

**Comment by abdelhamidfares** [comment]
@lunixbochs please,are you writing tutorial to your work?. thank you.

**Comment by jacobkahn** [comment]
Fixed in those commits above. Closing.
