### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by kingdeewang** [facebookresearch/wav2letter#539]
thank for you great job, when i install the the wav2letter, in the last step(make j4),i get error, as the blow show, can help me to check the problem?

[  7%] No install step for 'fbgemm'
[  7%] Completed 'fbgemm'
[  7%] Built target fbgemm
[  7%] Linking CXX executable RuntimeTest
CMakeFiles/Decoder.dir/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o：在函数‘w2l::ConnectionistTemporalClassificationCriterion::viterbiPath(af::array const&, af::array const&)’中：
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x111f)：对‘w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::getWorkspaceSize(int, int, int, int)’未定义的引用
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x11e1)：对‘w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::viterbi(int, int, int, int, float const*, int const*, int const*, int*, void*)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/Decoder.dir/build.make:1838: recipe for target 'Decoder' failed
make[2]: *** [Decoder] Error 1
CMakeFiles/Makefile2:149: recipe for target 'CMakeFiles/Decoder.dir/all' failed
make[1]: *** [CMakeFiles/Decoder.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
CMakeFiles/Test.dir/src/criterion/ConnectionistTemporalClassificationCriterion.cpp.o：在函数‘w2l::ConnectionistTemporalClassificationCriterion::viterbiPath(af::array const&, af::array const&)’中：
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x111f)：对‘w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::getWorkspaceSize(int, int, int, int)’未定义的引用
ConnectionistTemporalClassificationCriterion.cpp:(.text+0x11e1)：对‘w2l::cpu::ConnectionistTemporalClassificationCriterion<float>::viterbi(int, int, int, int, float const*, int const*, int const*, int*, void*)’未定义的引用

**Comment by tlikhomanenko** [comment]
We sent recently a fix 490411679ae13546060a3f82fccca44e30194225, can you try git pull and cmake/make again?

**Comment by kingdeewang** [comment]
it is ok,thanks!
