### ISSUE TITLE
cannot reproduce WER for seq2seq_tds for librispeech using pre-trained models

### ISSUE THREAD

**Issue by yurtmete** [facebookresearch/wav2letter#541]
I cannot reproduce WER for seq2seq_tds model reported on the paper. 
I used convlm as language model. 

WER should have been 3.39% as mentioned here https://github.com/facebookresearch/wav2letter/issues/390#issuecomment-526404274 by @tlikhomanenko, however I got WER 6.51% on test-clean. 

Here is my decode configuration:

--am=/home/yurtmn/workspace/cpp/wav2letter/recipes/models/seq2seq_tds/librispeech/decoder/baseline_dev-clean.bin
--tokensdir=/home/yurtmn/workspace/cpp/wav2letter/recipes/models/seq2seq_tds/librispeech/am
--tokens=librispeech-train-all-unigram-10000.tokens
--lexicon=/home/yurtmn/workspace/cpp/wav2letter/recipes/models/seq2seq_tds/librispeech/am/librispeech-train+dev-unigram-10000-nbest10.lexicon
--lm=/home/yurtmn/workspace/cpp/wav2letter/recipes/models/seq2seq_tds/librispeech/decoder/lm_librispeech_convlm_14B.bin
--datadir=/home/yurtmn/workspace/cpp/wav2letter/recipes/data/librispeech/librispeech/lists
--test=test-clean.lst
--sclite=/home/yurtmn/workspace/cpp/wav2letter/recipes/models/seq2seq_tds/librispeech
--uselexicon=false
--decodertype=tkn
--lmweight=0.5
--wordscore=1.0
--beamsize=80
--beamthreshold=7
--hardselection=1.5
--softselection=10.0
--attentionthreshold=30
--nthread_decoder=1
--smearing=max
--show=true
--lmtype=convlm
--lm_memory=3000
--lm_vocab=/home/yurtmn/workspace/cpp/wav2letter/recipes/models/seq2seq_tds/librispeech/decoder/lm_librispeech_convlm_14B.vocab

**Comment by tlikhomanenko** [comment]
Hi @yurtmete,

which version/commit of wav2letter are you using to run decoder?

**Comment by yurtmete** [comment]
I am using "commit 63326c174a83155661415f3e059faf52a4373d5c"

**Comment by xuqiantong** [comment]
@yurtmete We recently update the implementation of decoder, flags like `softselection` and `hardselection` are deprecated. So in order to reproduce the old results, you may checkout an old commit dates back to last Nov, say 7258c1697bbcc30ca0c3e06718ee62203a2c33d4.

**Comment by tlikhomanenko** [comment]
@yurtmete, yep @xuqiantong pointed you correctly: we changed parameters and logic of decoder, so for the new version of it (which is in the latest commits) you need to rerun decoder parameters search again.

**Comment by yurtmete** [comment]
Thank you! I could get WER 3.39% with an older commit.
