### ISSUE TITLE
Streaming model convertion

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#542]
Hello there I follow the recipe from the lexicon free model, i wanted to know if is possible to serialize this model and use in a similar way to the Multithreaded Streaming ASR Example, thanks in advance.

**Comment by vineelpratap** [comment]
Hi, it is possible. However, we don't have any automated code to do this. See https://github.com/facebookresearch/wav2letter/issues/524#issuecomment-584729188 for a parallel discussion.
