### ISSUE TITLE
Question:Streaming conv nets , perfomance

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#543]
hi there i have been reading through the paper , and tutorial on streaming conv nets, very impressive I must say, just have some questions about this great work:
How is the perfomance of this approach compared to other approach for instance the original conv_glu arch of wav2letter, i mean is quite interesting that you have training on 32 gpus  I image the training cost increase because of the reduced future window

**Comment by vineelpratap** [comment]
> How is the performance of this approach compared to other approach for instance the original `conv_glu` arch of wav2letter

i think the performance of the streaming model should be faster as it strides more (original `conv_glu` model has stride 2 while streaming model has stride 8). Also, note that one should also reduce future window for conv_glu models using asymmetric padding and add more stride for a fair comparison. But, we haven't done this analysis.
