### ISSUE TITLE
running out of ram with librilight

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#544]
I haven't tracked down a root cause yet, but wav2letter is using >120gb of ram on an 8 gpu node when loading even a fraction of the librilight training lists for me. This is right around the loading/filtering step, e.g.

```
I0218 01:12:07.823933  5881 W2lListFilesDataset.cpp:141] 2798754 files found.                                                                                    
I0218 01:12:07.961205  5883 Utils.cpp:102] Filtered 0/9706053 samples                                                                                            
```

I see memory crawl up to about 80gb (10gb * 8 processes), then it jumps to 120gb during filtering and crashes (as that's all the memory on these nodes). I'm adding more memory but if there's a way to make this more efficient that would make these models easier to train.

Looks like the librilight large lst file is 2.6gb on its own for me, which probably isn't helping.

**Comment by tlikhomanenko** [comment]
Hi @lunixbochs,

The problem could be that the audios are very long. Do you use original audio or segmented ones?

**Comment by lunixbochs** [comment]
I segmented the audio. Oh, you used a sort of fixed length segmentation though, like 60s? I was doing proper alignment, so I have a lot of shorter files, which means I probably ended up with way more files than you. Maybe the wav2letter overhead per file is very large. This can’t be the actual audio data, that’s closer to 3TB which will never fit in ram. It’s just the file lists during the loading/filtering steps.

**Comment by tlikhomanenko** [comment]
I meant for the batch case. We are using segments no longer 36s. But, yep, agree, still seems to be very strange.

**Comment by xuqiantong** [comment]
@lunixbochs You are right, the wav2letter dataset loads the metadata of all training and validation data, and then perform sorting on them. So, the more samples you have or the longer transcriptions you attach to each sample, the more memory you will use. 

In all our experiments, we segmented LibriVox data into 36s chunks and the overall RAM usage during training is around 80GB to 100GB on a 8 GPU node.

**Comment by tlikhomanenko** [comment]
Feel free to reopen if it is needed.
