### ISSUE TITLE
Getting Error on cd /root/wav2letter/build && make test 

### ISSUE THREAD

**Issue by krish-sentientgeeks** [facebookresearch/wav2letter#547]
Hi on testing with `cd /root/wav2letter/build && make test` I am getting the following error

root@1d61c7574a80:~/wav2letter/build# cd /root/wav2letter/build && make test
Running tests...
Test project /root/wav2letter/build
      Start  1: W2lCommonTest
 1/31 Test  #1: W2lCommonTest ....................***Exception: SegFault  1.49 sec
      Start  2: DictionaryTest
 2/31 Test  #2: DictionaryTest ...................   Passed    0.03 sec
      Start  3: ProducerConsumerQueueTest
 3/31 Test  #3: ProducerConsumerQueueTest ........   Passed    0.03 sec
      Start  4: CriterionTest
 4/31 Test  #4: CriterionTest ....................***Exception: SegFault  0.73 sec
      Start  5: Seq2SeqTest
 5/31 Test  #5: Seq2SeqTest ......................***Exception: SegFault  0.71 sec
      Start  6: AttentionTest
 6/31 Test  #6: AttentionTest ....................***Exception: SegFault  0.93 sec
      Start  7: WindowTest
 7/31 Test  #7: WindowTest .......................***Exception: SegFault  0.69 sec
      Start  8: DataTest
 8/31 Test  #8: DataTest .........................***Failed    0.73 sec
      Start  9: ListFileDatasetTest
 9/31 Test  #9: ListFileDatasetTest ..............   Passed    0.61 sec
      Start 10: SoundTest
10/31 Test #10: SoundTest ........................   Passed    0.07 sec
      Start 11: DecoderTest
11/31 Test #11: DecoderTest ......................   Passed    1.08 sec
      Start 12: CeplifterTest
12/31 Test #12: CeplifterTest ....................   Passed    0.03 sec
      Start 13: DctTest
13/31 Test #13: DctTest ..........................   Passed    0.05 sec
      Start 14: DerivativesTest
14/31 Test #14: DerivativesTest ..................   Passed    0.03 sec
      Start 15: DitherTest
15/31 Test #15: DitherTest .......................   Passed    8.03 sec
      Start 16: MfccTest
16/31 Test #16: MfccTest .........................   Passed    0.23 sec
      Start 17: PreEmphasisTest
17/31 Test #17: PreEmphasisTest ..................   Passed    0.03 sec
      Start 18: SpeechUtilsTest
18/31 Test #18: SpeechUtilsTest ..................***Failed    0.89 sec
      Start 19: TriFilterbankTest
19/31 Test #19: TriFilterbankTest ................   Passed    0.04 sec
      Start 20: WindowingTest
20/31 Test #20: WindowingTest ....................   Passed    0.03 sec
      Start 21: W2lModuleTest
21/31 Test #21: W2lModuleTest ....................***Exception: SegFault  1.71 sec
      Start 22: RuntimeTest
22/31 Test #22: RuntimeTest ......................***Failed    8.59 sec
      Start 23: inference_Conv1dTest
23/31 Test #23: inference_Conv1dTest .............   Passed    0.03 sec
      Start 24: inference_IdentityTest
24/31 Test #24: inference_IdentityTest ...........   Passed    0.01 sec
      Start 25: inference_LayerNormTest
25/31 Test #25: inference_LayerNormTest ..........   Passed    0.01 sec
      Start 26: inference_LinearTest
26/31 Test #26: inference_LinearTest .............   Passed    0.01 sec
      Start 27: inference_LogMelFeatureTest
27/31 Test #27: inference_LogMelFeatureTest ......   Passed    0.04 sec
      Start 28: inference_MemoryManagerTest
28/31 Test #28: inference_MemoryManagerTest ......   Passed    0.01 sec
      Start 29: inference_ReluTest
29/31 Test #29: inference_ReluTest ...............   Passed    0.01 sec
      Start 30: inference_ResidualTest
30/31 Test #30: inference_ResidualTest ...........   Passed    0.01 sec
      Start 31: inference_TDSBlockTest
31/31 Test #31: inference_TDSBlockTest ...........   Passed    0.01 sec

71% tests passed, 9 tests failed out of 31

Total Test time (real) =  26.87 sec

The following tests FAILED:
	  1 - W2lCommonTest (SEGFAULT)
	  4 - CriterionTest (SEGFAULT)
	  5 - Seq2SeqTest (SEGFAULT)
	  6 - AttentionTest (SEGFAULT)
	  7 - WindowTest (SEGFAULT)
	  8 - DataTest (Failed)
	 18 - SpeechUtilsTest (Failed)
	 21 - W2lModuleTest (SEGFAULT)
	 22 - RuntimeTest (Failed)
Errors while running CTest
Makefile:104: recipe for target 'test' failed
make: *** [test] Error 8

I am also attaching the log that I got while make-ing 

here [log.txt](https://github.com/facebookresearch/wav2letter/files/4224479/log.txt)

I am not sure... 
it seems to me that it is something related to the RALocalAllocator::allocBranch 
can someone please help.

**Comment by tlikhomanenko** [comment]
Hi @krish-sentientgeeks,

which version of CUDA do you have? Could you run each test separately and post the log of them?
```
./wav2letter/build/src/tests/W2lCommonTest
./wav2letter/build/src/tests/CriterionTest
```

**Comment by krish-sentientgeeks** [comment]
We are using CUDA 9.2

**Comment by krish-sentientgeeks** [comment]
> Hi @krish-sentientgeeks,
> 
> which version of CUDA do you have? Could you run each test separately and post the log of them?
> 
> ```
> ./wav2letter/build/src/tests/W2lCommonTest
> ./wav2letter/build/src/tests/CriterionTest
> ```

When I run 
cd /root/wav2letter/build && ./src/tests/W2lCommonTest

I am getting the following

root@63055e5691d9:/# cd /root/wav2letter/build && ./src/tests/W2lCommonTest
[==========] Running 19 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 19 tests from W2lCommonTest
[ RUN      ] W2lCommonTest.StringTrim
[       OK ] W2lCommonTest.StringTrim (0 ms)
[ RUN      ] W2lCommonTest.ReplaceAll
[       OK ] W2lCommonTest.ReplaceAll (0 ms)
[ RUN      ] W2lCommonTest.StringSplit
[       OK ] W2lCommonTest.StringSplit (0 ms)
[ RUN      ] W2lCommonTest.StringJoin
[       OK ] W2lCommonTest.StringJoin (0 ms)
[ RUN      ] W2lCommonTest.StringFormat
[       OK ] W2lCommonTest.StringFormat (0 ms)
[ RUN      ] W2lCommonTest.PathsConcat
[       OK ] W2lCommonTest.PathsConcat (0 ms)
[ RUN      ] W2lCommonTest.RetryWithBackoff
[       OK ] W2lCommonTest.RetryWithBackoff (752 ms)
[ RUN      ] W2lCommonTest.PackReplabels
[       OK ] W2lCommonTest.PackReplabels (0 ms)
[ RUN      ] W2lCommonTest.Dictionary
[       OK ] W2lCommonTest.Dictionary (0 ms)
[ RUN      ] W2lCommonTest.UnpackReplabels
[       OK ] W2lCommonTest.UnpackReplabels (0 ms)
[ RUN      ] W2lCommonTest.UnpackReplabelsIgnoresInvalid
[       OK ] W2lCommonTest.UnpackReplabelsIgnoresInvalid (0 ms)
[ RUN      ] W2lCommonTest.Uniq
[       OK ] W2lCommonTest.Uniq (0 ms)
[ RUN      ] W2lCommonTest.Normalize
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:160
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION


In function af::array af::stdev(const af::array&, dim_t)
In file src/api/cpp/stdev.cpp:55" thrown in the test body.
[  FAILED  ] W2lCommonTest.Normalize (445 ms)
[ RUN      ] W2lCommonTest.Transpose
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:160
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION


In function af::array af::transpose(const af::array&, bool)
In file src/api/cpp/transpose.cpp:18" thrown in the test body.
[  FAILED  ] W2lCommonTest.Transpose (1 ms)
[ RUN      ] W2lCommonTest.localNormalize
Segmentation fault (core dumped)

Also When running 
cd /root/wav2letter/build && ./src/tests/CriterionTest

I am getting the following

root@63055e5691d9:~/wav2letter/build# cd /root/wav2letter/build && ./src/tests/CriterionTest
[==========] Running 22 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 22 tests from CriterionTest
[ RUN      ] CriterionTest.CTCEmptyTarget
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function cuda::Kernel cuda::buildKernel(int, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool)
In file src/backend/cuda/nvrtc/cache.cpp:160
NVRTC Error(5): NVRTC_ERROR_INVALID_OPTION

**Comment by tlikhomanenko** [comment]
This errors connected to the driver issue, docker image version is not compatible to your cuda on machine or your driver is old. Please have a look at issue https://github.com/facebookresearch/wav2letter/issues/335 and check your cuda version on machine itself.

**Comment by tlikhomanenko** [comment]
Feel free to reopen if it is needed.
