### ISSUE TITLE
Library iomp5: not found & make test error 

### ISSUE THREAD

**Issue by kingdeewang** [facebookresearch/wav2letter#548]
Hi,
   Can  help me to check the below problem.  i don't know how to solve it, thanks very much!

help for usage, or press the help button on the CMake GUI.
(voice) $  cmake .. -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CUDA -DArrayFire_DIR=/home/wel/wav2letter_install/arrayfire/share/ArrayFire/cmake/ -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda 
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_intel_thread: /opt/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /opt/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_intel_thread: /opt/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /opt/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_sequential: /opt/intel/mkl/lib/intel64/libmkl_sequential.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- ArrayFire found (include: /home/wel/wav2letter_install/arrayfire/include, library: ArrayFire::afcuda)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- OpenMP found
-- flashlight found (include:  lib: flashlight::flashlight )
-- flashlight built in distributed mode.
-- flashlight built with contrib features.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_sequential.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /home/wel/wav2letter_install/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/wel/wav2letter_install/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /home/wel/wav2letter_install/kenlm/lm/model.hh
-- Found kenlm (include: /home/wel/wav2letter_install/kenlm, library: /home/wel/wav2letter_install/kenlm/build/lib/libkenlm.a;/home/wel/wav2letter_install/kenlm/build/lib/libkenlm_util.a)
-- Adding warpctc:
-- warpctc: cuda found TRUE
-- warpctc: using CUDA 9.0 or above
-- warpctc: Building shared library with GPU support
-- Required SndFile dependency Ogg found.
-- Required SndFile dependency Vorbis found.
-- Required SndFile dependency VorbisEnc found.
-- Required SndFile dependency FLAC found.
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.a include: /usr/local/include
-- libsndfile found.
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- Looking for KenLM
-- Using kenlm library found in /home/wel/wav2letter_install/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/wel/wav2letter_install/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /home/wel/wav2letter_install/kenlm/lm/model.hh
-- Found kenlm (include: /home/wel/wav2letter_install/kenlm, library: /home/wel/wav2letter_install/kenlm/build/lib/libkenlm.a;/home/wel/wav2letter_install/kenlm/build/lib/libkenlm_util.a)
ExternalProject_Add(fbgemm) downloading ...
-- Examples: add executable simple_streaming_asr_example
-- Examples: add executable multithreaded_streaming_asr_example
-- Tests: add executable inference_Conv1dTest
-- Tests: add executable inference_IdentityTest
-- Tests: add executable inference_LayerNormTest
-- Tests: add executable inference_LinearTest
-- Tests: add executable inference_LogMelFeatureTest
-- Tests: add executable inference_MemoryManagerTest
-- Tests: add executable inference_ReluTest
-- Tests: add executable inference_ResidualTest
-- Tests: add executable inference_TDSBlockTest
-- Building recipes.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wel/wav2letter/build

(voice) $ make test
Running tests...
Test project /home/wel/wav2letter/build
      Start  1: W2lCommonTest
 1/31 Test  #1: W2lCommonTest ....................   Passed    2.59 sec
      Start  2: DictionaryTest
 2/31 Test  #2: DictionaryTest ...................   Passed    0.03 sec
      Start  3: ProducerConsumerQueueTest
 3/31 Test  #3: ProducerConsumerQueueTest ........   Passed    0.03 sec
      Start  4: CriterionTest
 4/31 Test  #4: CriterionTest ....................   Passed    8.24 sec
      Start  5: Seq2SeqTest
 5/31 Test  #5: Seq2SeqTest ......................   Passed    5.86 sec
      Start  6: AttentionTest
 6/31 Test  #6: AttentionTest ....................   Passed    2.54 sec
      Start  7: WindowTest
 7/31 Test  #7: WindowTest .......................   Passed    2.10 sec
      Start  8: DataTest
 8/31 Test  #8: DataTest .........................   Passed    0.77 sec
      Start  9: ListFileDatasetTest
 9/31 Test  #9: ListFileDatasetTest ..............   Passed    0.45 sec
      Start 10: SoundTest
10/31 Test #10: SoundTest ........................***Failed    0.05 sec
      Start 11: DecoderTest
11/31 Test #11: DecoderTest ......................   Passed    1.33 sec
      Start 12: CeplifterTest
12/31 Test #12: CeplifterTest ....................   Passed    0.03 sec
      Start 13: DctTest
13/31 Test #13: DctTest ..........................   Passed    0.03 sec
      Start 14: DerivativesTest
14/31 Test #14: DerivativesTest ..................   Passed    0.03 sec
      Start 15: DitherTest
15/31 Test #15: DitherTest .......................   Passed    8.04 sec
      Start 16: MfccTest
16/31 Test #16: MfccTest .........................   Passed    0.21 sec
      Start 17: PreEmphasisTest
17/31 Test #17: PreEmphasisTest ..................   Passed    0.02 sec
      Start 18: SpeechUtilsTest
18/31 Test #18: SpeechUtilsTest ..................   Passed    0.83 sec
      Start 19: TriFilterbankTest
19/31 Test #19: TriFilterbankTest ................   Passed    0.03 sec
      Start 20: WindowingTest
20/31 Test #20: WindowingTest ....................   Passed    0.03 sec
      Start 21: W2lModuleTest
21/31 Test #21: W2lModuleTest ....................   Passed    2.20 sec
      Start 22: RuntimeTest
22/31 Test #22: RuntimeTest ......................   Passed    1.24 sec
      Start 23: inference_Conv1dTest
23/31 Test #23: inference_Conv1dTest .............   Passed    0.03 sec
      Start 24: inference_IdentityTest
24/31 Test #24: inference_IdentityTest ...........   Passed    0.01 sec
      Start 25: inference_LayerNormTest
25/31 Test #25: inference_LayerNormTest ..........   Passed    0.02 sec
      Start 26: inference_LinearTest
26/31 Test #26: inference_LinearTest .............   Passed    0.01 sec
      Start 27: inference_LogMelFeatureTest
27/31 Test #27: inference_LogMelFeatureTest ......   Passed    0.03 sec
      Start 28: inference_MemoryManagerTest
28/31 Test #28: inference_MemoryManagerTest ......   Passed    0.01 sec
      Start 29: inference_ReluTest
29/31 Test #29: inference_ReluTest ...............   Passed    0.00 sec
      Start 30: inference_ResidualTest
30/31 Test #30: inference_ResidualTest ...........   Passed    0.01 sec
      Start 31: inference_TDSBlockTest
31/31 Test #31: inference_TDSBlockTest ...........   Passed    0.01 sec

97% tests passed, 1 tests failed out of 31

Total Test time (real) =  36.82 sec

The following tests FAILED:
	 10 - SoundTest (Failed)
Errors while running CTest
Makefile:118: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by tlikhomanenko** [comment]
Hi @kingdeewang,

Did you manage to solve the issue? What was the problem?
