### ISSUE TITLE
Inference example results in segmentation fault

### ISSUE THREAD

**Issue by LouisXiaoWANG** [facebookresearch/wav2letter#549]
I am following the tutorial of Simple Streaming ASR Example
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#simple-streaming-asr-example
I successfully made inference with docker image, but when I run the same command with locally compiled wave2letter inference, I have an error:
`~/src/wav2letter/build$ cat ~/data/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | inference/inference/examples/simple_streaming_asr_example --input_files_base_path ~/data/model
Started features model file loading ... 
Completed features model file loading elapsed time=100 milliseconds

Started acoustic model file loading ... 
Completed acoustic model file loading elapsed time=1025 milliseconds

Started tokens file loading ... 
Completed tokens file loading elapsed time=482 microseconds

Tokens loaded - 9998 tokens
Started decoder options file loading ... 
Completed decoder options file loading elapsed time=19 microseconds

Started create decoder ... 
[Letters] 9998 tokens loaded.
[Words] 200001 words loaded.
Segmentation fault (core dumped)
`

I have tried to:
 - recompile with commit head-1 on master
 - redownload the model and audio files following the tutorial https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-the-example-trained-models-from-aws-s3

but the error remains, would someone help please?

ps: I also followed the tutorial for a full build of wave2letter, but after successful build, I have no Train Test executables under build folder, any idea?
`~/src/wav2letter/build$ ls -lh

total 76K

-rw-r--r-- 1 louis louis  39K févr. 19 14:37 CMakeCache.txt

drwxr-xr-x 5 louis louis 4,0K févr. 19 14:52 CMakeFiles

-rw-r--r-- 1 louis louis 1,8K févr. 19 14:37 cmake_install.cmake

drwxr-xr-x 6 louis louis 4,0K févr. 19 14:52 inference

-rw-r--r-- 1 louis louis  19K févr. 19 14:52 Makefile

drwxr-xr-x 3 louis louis 4,0K févr. 18 22:25 src
`

**Comment by avidov** [comment]
> ps: I also followed the tutorial for a full build of wave2letter, but after successful build, I have no Train Test executables under build folder, any idea?
> `~/src/wav2letter/build$ ls -lh

Sounds like you tried to build with 2 diffrent sets of cmake flags.
Before changing cmake flag set please:
rm CMakeCache.txt

and run the cmake command again

**Comment by xuqiantong** [comment]
@LouisXiaoWANG We are not able to reproduce this seg fault with current master.

**Comment by LouisXiaoWANG** [comment]
Thanks for your quickly replies, I deleted completed the build folder and tried to rebuild but had no chance.
Never mind, I will stick with the docker version
