### ISSUE TITLE
incorrect dimensions when forking pretrained streaming_convnets model

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#550]
I want to try specializing the streaming_convnets model. `continue model/` failed, and I don't blame it, but fork also fails with this:
```
terminate called after throwing an instance of 'af::exception'
  what():  CTC: Incorrect dimensions for input. Expected dim4(N, T, B)
```

I'm using

```
Train fork model/000_model_last.bin --flagsfile flagsfile --rndv_filepath='' --rundir=''
```

flagsfile is:

```
--arch=arch
--tokens=tokens.txt
--lexicon=lexicon.txt
--datadir=/data/processed
--train=[...]
--valid=[...]

--criterion=ctc
--batchsize=8
--lr=0.4
--momentum=0.0
--maxgradnorm=0.5
--reportiters=1000
--nthread=6
--mfsc=true
--usewordpiece=true
--wordseparator=_
--filterbanks=80
--minisz=200
--mintsz=2
--maxisz=33000
--enable_distributed=true
--pcttraineval=1
--minloglevel=0
--logtostderr
--onorm=target
--sqnorm
--localnrmlleftctx=300
```

I'm using your tokens, and it happens both with yours and my own lexicon. Test works fine, I only get this issue on Train.

**Comment by vineelpratap** [comment]
Hi, could you share the complete output when you run the `Train` binary.

**Comment by lunixbochs** [comment]
Oh! Was the model you published run through the `streaming_tds_model_converter`?

Which drops a bunch of layers:
```
Skipping View module: V -1 NFEAT 1 0
Skipping SpecAugment module: SAUG 80 27 2 100 1.0 2
Skipping Dropout module: DO 0.1
Skipping Dropout module: DO 0.1
Skipping Dropout module: DO 0.1
Skipping Dropout module: DO 0.1
Skipping Reorder module: RO 2 1 0 3
Skipping View module: V 2160 -1 1 0
Skipping View module: V NLABEL 0 -1 1
```

**Comment by lunixbochs** [comment]
@vineelpratap here is most of the output. I’ve removed a bit of “missing word in lexicon” lines: https://bochs.info/p/n5kme9

**Comment by vineelpratap** [comment]
Hi, looks like you forgot to copy the last line of https://git.io/Jv2AS in your arch file.

**Comment by lunixbochs** [comment]
This is my arch file:

```
# streaming_tds_k10s_d8_p125m_do0.1_saug_mln_500ms.arch
V -1 NFEAT 1 0
SAUG 80 27 2 100 1.0 2
PD 0 5 3
C2 1 15 10 1 2 1 0 0
R
DO 0.1
LN 1 2
TDS 15 9 80 0.1 0 1 0
TDS 15 9 80 0.1 0 1 0
PD 0 7 1
C2 15 19 10 1 2 1 0 0
R
DO 0.1
LN 1 2
TDS 19 9 80 0.1 0 1 0
TDS 19 9 80 0.1 0 1 0
TDS 19 9 80 0.1 0 1 0
PD 0 9 1
C2 19 23 12 1 2 1 0 0
R
DO 0.1
LN 1 2
TDS 23 11 80 0.1 0 1 0
TDS 23 11 80 0.1 0 1 0
TDS 23 11 80 0.1 0 1 0
TDS 23 11 80 0.1 0 0 0
PD 0 10 0
C2 23 27 11 1 1 1 0 0
R
DO 0.1
LN 1 2
TDS 27 11 80 0.1 0 0 0
TDS 27 11 80 0.1 0 0 0
TDS 27 11 80 0.1 0 0 0
TDS 27 11 80 0.1 0 0 0
TDS 27 11 80 0.1 0 0 0
RO 2 1 0 3
V 2160 -1 1 0
L 2160 NLABEL
V NLABEL 0 -1 1
```

I'm forking the model you published, so it's not using my arch file. I'm using wav2letter master Train.cpp, not the changes proposed in a github issue to zero the linear layer and reload the arch. So the published model has the old/incorrect arch and can't be forked unless the model is patched?

**Comment by lunixbochs** [comment]
Thanks for the hint about the view.

Forking with this code fixed it: https://github.com/facebookresearch/wav2letter/issues/507#issuecomment-580809478

I vote you make an official flag for doing this, it's very useful.

**Comment by vineelpratap** [comment]
I have updated the model on S3. There shouldn’t be any issues when forking the model now.

**Comment by vineelpratap** [comment]
I have updated the model on S3. There shouldn’t be any issues when forking the model now.
