### ISSUE TITLE
[question] WSJ CER guidelines

### ISSUE THREAD

**Issue by sdrobert** [facebookresearch/wav2letter#552]
Hello,

I just have a question on how letter error rates/character error rates are calculated for WSJ. Is it as simple as treating each character in the reference/hypothesis transcriptions as tokens? Is there any pre-filtering going on? Are there any guidelines or previous implementations that were followed?

Thank you very much for your time,
Sean

**Comment by vineelpratap** [comment]
Hi, we try to follow the recipes from Kaldi for data preparation part to do it the standard way. You can look at our normalization and data preparation code here - https://github.com/facebookresearch/wav2letter/tree/master/recipes/data/wsj
