### ISSUE TITLE
Docker​ issues

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#553]
(1) on Windows PowerShell, I could execute

run hello-world

nicely, and it produced:

"Hello from Docker!​
This message shows that your installation appears to be working correctly.

…"

However, on Ubuntu,

I tried to run

Quickly run Streaming ASR Examples using Docker​
Simple Streaming ASR Example using Docker

sudo docker run --rm -v ~:/root/host/ -it --ipc=host --name w2l -a stdin -a stdout -a stderr wav2letter/wav2letter:inference-latest sh -c "/root/host/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | /root/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path /root/host/model"

from
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-and-build-wav2letter-inference

or  run 

(docker) run hello-world

It produced:

"docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'."

I have tried many ways available on the net and the problem could not be fixed. Any suggestions?.

(2) I have installed "Free 90-Day Microsoft Visual Studio Enterprise Trial" (Windows 10) (which works for Docker ) on my brand new laptop:

https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise

To install WSL 2, I also need "Windows 10 (insider) build 18917 or higher".

After I go to Settings > Update & Security > Windows Insider Program. It says: "It looks the version of the Windows you're using is not supported by the Insider Program at this time". And the button "Get Started" there is in Gray and it is unclickable. Do you have any ideas regarding how to have "Windows 10 build 18917 or higher" on "Free 90-Day Microsoft Visual Studio Enterprise Trial"? 

Do I need WSL 2 to run wav2letter programs such as converting a wav file to text? And the problem (1) above is because there is no WSL 2 installed?

Thank you very much!

**Comment by tlikhomanenko** [comment]
Hi @ML6634,

(1) Did you try solutions listed here https://stackoverflow.com/questions/44678725/cannot-connect-to-the-docker-daemon-at-unix-var-run-docker-sock-is-the-docker?
One another way I would try is to remove docker from machine and follow installation again.

(2) To check your build version of Windows 10 you can go to shell and run `ver`.  To have working version of w2l with inference pipeline you only need the docker for Windows.

**Comment by ML6634** [comment]
Thank Tatiana a lot for the helpful comments! 

(1) It sounds the newest version (or even some other newer versions?) of Docker could not get along with Ubuntu very well. Per the suggestion of the following link (in Chinese) I have installed an older version of Docker instead:
https://www.jianshu.com/p/7842b543e4ac
Then it works.

**Comment by tlikhomanenko** [comment]
@ML6634,

Yep, this could be. Nice catch of docker version!
