### ISSUE TITLE
not able to run decoder

### ISSUE THREAD

**Issue by vigneshmj1997** [facebookresearch/wav2letter#556]
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
*** Aborted at 1582644132 (unix time) try "date -d @1582644132" if you are using GNU date ***
PC: @     0x7f3ebab7a428 gsignal
*** SIGABRT (@0x65b7) received by PID 26039 (TID 0x7f3ec6163bc0) from PID 26039; stack trace: ***
    @     0x7f3ebb9f0390 (unknown)
    @     0x7f3ebab7a428 gsignal
    @     0x7f3ebab7c02a abort
    @     0x7f3ebb4bd84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f3ebb4bb6b6 (unknown)
    @     0x7f3ebb4bb701 std::terminate()
    @     0x7f3ebb4bb969 __cxa_rethrow
    @           0x488f9e _ZN3w2l16retryWithBackoffIRFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt13unordered_mapIS6_S6_St4hashIS6_ESt8equal_toIS6_ESaISt4pairIS7_S6_EEERSt10shared_ptrIN2fl6ModuleEERSJ_INS_17SequenceCriterionEEEJS8_SI_SN_SQ_EEENSt9result_ofIFT_DpT0_EE4typeENSt6chrono8durationIdSt5ratioILl1ELl1EEEEdlOSU_DpOSV_.constprop.6300
    @           0x4183da main
    @     0x7f3ebab65830 __libc_start_main
    @           0x487459 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by padentomasello** [comment]
Hi @vigneshmj1997, would you mind providing a bit more details to reproduce so I can better assist? It would be helpful to have the command you are running, as well as your build information.

**Comment by vigneshmj1997** [comment]
wav2letter/build/Test   --am /root/model/acoustic_model.bin   --maxload 10   --test /root/audio/LibriSpeech-dev-clean-wav-all.lst
 
this was the command i executed

**Comment by tlikhomanenko** [comment]
@vigneshmj1997,

your list file should be in the format (please have a look in https://github.com/facebookresearch/wav2letter/wiki/Data-Preparation)
```
id file_path size transcription
```

Also you cannot use the model from the inference pipeline because it is converted from w2l to the the format supported in the inference pipeline. That is why you have an error.

Feel free to reopen if further support is needed.
