### ISSUE TITLE
not able to create python bindings

### ISSUE THREAD

**Issue by vigneshmj1997** [facebookresearch/wav2letter#558]
i built the docker image as told in the documentation following that .I am not able to execute the instructions given in "python binding" i had installed packaging and torch 
the on executing command pip install -e . i get the following error

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/root/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /root/wav2letter/bindings/python/
    Complete output (36 lines):
    running develop
    running egg_info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    reading manifest file 'wav2letter.egg-info/SOURCES.txt'
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    running build_ext
    make: *** No targets specified and no makefile found.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/wav2letter/bindings/python/setup.py", line 109, in <module>
        zip_safe=False,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/wav2letter/bindings/python/setup.py", line 48, in run
        self.build_extensions()
      File "/root/wav2letter/bindings/python/setup.py", line 91, in build_extensions
        ["cmake", "--build", "."] + build_args, cwd=self.build_temp
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/root/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

i ignored the error and continued with importing wav2letter 
 wav2letter got imported but it was incomplete

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
these are the output when i executed dir(wav2letter)
python3 version 3.6.8
docker downloaded  is the docker given for cpu

**Comment by tlikhomanenko** [comment]
Hi @vigneshmj1997,

I have successfully installed for the CPU image `wav2letter/wav2letter:cpu-0142d39` by doing
```
pip install torch==1.2.0 packaging==19.1
# reinstall kenlm with additional flag, without it doesn't work
cd /root/kenlm/build && cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON && \
  make -j$(nproc) && make install && \
# set no cuda
export USE_CUDA=0
export KENLM_ROOT_DIR=/root/kenlm 
cd /root/wav2letter/bindings/python && pip install -e .
```

I will update the dockerfile for CPU to have this too a bit later.

Feel free to reopen if problem still persists.
