### ISSUE TITLE
error in fork flags

### ISSUE THREAD

**Issue by cri5Castro** [facebookresearch/wav2letter#559]
Hello i'm forking the tds-ctc model from 2019 sota, after redefining some flags such as batch size, itersave,gamma and stepsize i found that the flags are not redefined , is there a way to fix this?
my first attempt was to hard code the Train.cpp but i thing is not an  optimal solution

Note: i have already pull from master and recompile wav2letter with no errors

**Comment by tlikhomanenko** [comment]
@cri5Castro,

can you send the command how you redefine flags?

**Comment by cri5Castro** [comment]
my first version of the fork script was
`WAV2LETTER="$1"
MODEL_DST="$2"

mkdir -p $MODEL_DST/am/lexfreeTDS
"$WAV2LETTER/build/Train" fork $MODEL_DST/am/am_tds_ctc_librivox_dev_clean.bin --runname=lexfreeTDS \
--rundir=$MODEL_DST/am/lexfreeTDS \
--tokensdir=$MODEL_DST/am \
--tokens=char_train+dev.tokens \
--archdir=$MODEL_DST/am \
--arch=am_tds.arch \
--datadir="$MODEL_DST/" \
--train=lists/np_clean_train.lst \
--valid=lists/np_clean_dev.lst \
--lexicon=$MODEL_DST/am/char_train+dev.lexicon \
--criterion=ctc \
--onorm=target \
--lr=0.2 \
--lrcrit=0.006 \
--linseg=1 \
--momentum=0.6 \
--maxgradnorm=1 \
"--surround=|" \
--sqnorm=true \
--mfsc=true \
--nthread=8 \
--batchsize=4 \
--melfloor=1.0 \
--iter=50 \
--gamma=0.5 \
--stepsize=200 \
--seed=2 \
--labelsmooth=0.05 \
--filterbanks=80 \
--enable_distributed=true \`

then i manage to solve this issue  moving this flags to a flag file and indicate the path to the training bin , what ever i'm not sure about if this is supposed to happen

**Comment by tlikhomanenko** [comment]
@cri5Castro,

right do I understand that you solved the fork issue by putting flags into config file and running with it?

**Comment by cri5Castro** [comment]
Yep that solve the problem

**Comment by vineelpratap** [comment]
@cri5Castro - when using `--surround |` on command line, you should use as `--surround "|"`. Otherwise, we won't be ready any gflags passed after it.

**Comment by tlikhomanenko** [comment]
@cri5Castro,

feel free to reopen, but seems the problem is solved.
