### ISSUE TITLE
Rasbperry support

### ISSUE THREAD

**Issue by LouisXiaoWANG** [facebookresearch/wav2letter#561]
Hello,
I'd like to make inference on  a raspberry model 3B+， when trying to compile the simple_asr_model, I have the following error:
[ 29%] Building CXX object src/libraries/CMakeFiles/wav2letter-libraries.dir/feature/TriFilterbank.cpp.o
[ 29%] Building CXX object src/libraries/CMakeFiles/wav2letter-libraries.dir/feature/Windowing.cpp.o
[ 33%] Linking CXX static library libwav2letter-libraries.a
[ 33%] Built target wav2letter-libraries
make[1]: *** [CMakeFiles/Makefile2:1155: inference/inference/examples/CMakeFiles/simple_streaming_asr_example.dir/rule] Error 2
make: *** [Makefile:424: simple_streaming_asr_example] Error 2

So my question is, if the code has been tested on platforms like Raspberry?
Will you provide docker images for Raspbian?

Thanks!

**Comment by LouisXiaoWANG** [comment]
Redone a clean installation of Raspbian  Buster Lite, get the error below:
 `-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_AVX512
-- Performing Test COMPILER_SUPPORTS_AVX512 - Failed
CMake Error at CMakeLists.txt:60 (message):
  A compiler with AVX512 support is required.
`

**Comment by avidov** [comment]
Hi, 
We are planing support for Raspberry but it is not in the pipeline yet.

**Comment by jacobkahn** [comment]
@LouisXiaoWANG - down the road, we may add the ability to plug in different GEMM libraries (such as something that works on an R Pi (such as xnnpack).

**Comment by nijynot** [comment]
Any updates on Raspberry PI support?
Is it still on the roadmap?
