### ISSUE TITLE
chinese prepare data help 

### ISSUE THREAD

**Issue by kingdeewang** [facebookresearch/wav2letter#566]
hi, i want to train the thchs30 data for chinese recognize. how  should the word(一丁点) int   the lexicon.txt format like ?
一丁点 ii i4 d ing1 d ian3

or as the below:
一丁点 一 丁 点 |

can give me a suggestion,thanks a lot!

**Comment by tlikhomanenko** [comment]
We support any kind of tokens/letters for any language. So you can just simply use the latest version where you just separate each hieroglyph with the space.

**Comment by kenxiexiaolong** [comment]
> hi, i want to train the thchs30 data for chinese recognize. how  should the word(一丁点) int   the lexicon.txt format like ?
> 一丁点 ii i4 d ing1 d ian3
> or as the below:
> 一丁点 一 丁 点 |
> can give me a suggestion,thanks a lot!

hi，Is this problem solved? I have the same question.
