### ISSUE TITLE
Difference of `tokens.txt` in tutorial and recipe

### ISSUE THREAD

**Issue by hwidong-na** [facebookresearch/wav2letter#568]
Hi,

I'm trying to run baseline experiments using LibriSpeech. When I ran the data preparation in the [tutorial](https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean), the generated `tokens.txt` is different from [here](https://dl.fbaipublicfiles.com/wav2letter/sota/2019/librispeech/models/am/librispeech-train-all-unigram-10000.tokens).

`tokens.txt` in the tutorial
```
|
'
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z

```

`/path/to/model/am/librispeech-train-all-unigram-10000.tokens`
```_the
_and
_of
_to
_a
s
_in
_i
_he
_that
_was
_it
_his
_with
...
```

Is this intended? Where can I find the format of tokens?

**Comment by lunixbochs** [comment]
The tutorial is for the conv_glu model, which uses letter tokens. The sota 2019 is a "word piece" model, which uses more-than-one-letter tokens. This data preparation step should give you the same tokens as sota 2019: https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019#data-preparation

**Comment by tlikhomanenko** [comment]
@hwidong-na,

As @lunixbochs pointed (thanks!) you tokens set depends on what type of AM you want to train. We have several recipes which have either phonemes, letters outputs for each frame or word pieces (and also word pieces dictionary also could be different depending on the data on which you train word pieces mapping or number of word pieces). In the tutorial the simplest case when model outputs a letter  for each frame is provided.

If you need further help, feel free to reopen.

**Comment by Bernardo-Favoreto** [comment]
> @hwidong-na,
> 
> As @lunixbochs pointed (thanks!) you tokens set depends on what type of AM you want to train. We have several recipes which have either phonemes, letters outputs for each frame or word pieces (and also word pieces dictionary also could be different depending on the data on which you train word pieces mapping or number of word pieces). In the tutorial the simplest case when model outputs a letter for each frame is provided.
> 
> If you need further help, feel free to reopen.

Does this mean I cannot use letters for models that use wordpiece as default (even if I set usewordpiece=false and remove wordseparator)? For instance, all SOTA models **must** be trained with wordpiece or is this optional?
Thanks!

**Comment by tlikhomanenko** [comment]
You can use recipes of models with wp setting and change tokens set, lexicon in the config according to your tokens set you want to train. But you cannot apply trained model on wp to predict letters of course. You can train SOTA models with any tokens set you want, however for the letter based model you need to change a bit arch to have less stride (it is 8 stride, letters  prediction will probably work badly with this).

**Comment by Bernardo-Favoreto** [comment]
Thanks for the answer!

I was browsing through the architecture files/writing architecture files wiki but could not seem to understand where is stride defined. Specifically, I'm talking about these: https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019/am_arch.
According to the wiki, layers with stride are: Conv2D, Pool2D (M, A), and AsymmetricConv1D. In said files I've seen only C2 and Pool, but stride wasn't set to 8. 
Am I missing something here?

**Comment by tlikhomanenko** [comment]
It is total stride 8, you can see 3 pooling layers with stride 2, so total stride 8.
