### ISSUE TITLE
Train aishell problem

### ISSUE THREAD

**Issue by kingdeewang** [facebookresearch/wav2letter#572]
when i train the aishell recipt, i got the below problem.
 would you pls help me to check? thanks

*** Aborted at 1583984943 (unix time) try "date -d @1583984943" if you are using GNU date ***
PC: @     0x7f8a7f7587a9 cuda::evalNodes<>()
*** SIGFPE (@0x7f8a7f7587a9) received by PID 21046 (TID 0x7f8ab54588c0) from PID 2138408873; stack trace: ***
    @     0x7f8a619e8890 (unknown)
    @     0x7f8a7f7587a9 cuda::evalNodes<>()
    @     0x7f8a7f7593b8 cuda::evalNodes<>() 

    @     0x7f8a7f696c07 cuda::Array<>::eval()
    @     0x7f8a7e7c0c31 _ZN4cuda10reduce_allIL7af_op_t5EccEET1_RKNS_5ArrayIT0_EEbd
    @     0x7f8a7faebb13 af_any_true_all
    @     0x7f8a7fca8e24 af::anyTrue<>()
    @     0x560c6425493d _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S9_S9_ddbi
    @     0x560c641f036a main
    @     0x7f8a60459b97 __libc_start_main
    @     0x560c6424f6ea _start

[lexicon.txt](https://github.com/facebookresearch/wav2letter/files/4322205/lexicon.txt)

**Comment by kingdeewang** [comment]
the train.list format:

train/S0509/BAC009S0509W0228.wav	 /home/wel/audio/thchs30/train/S0509/BAC009S0509W0228.wav	3.6589375	经济 房 和 保障 房 的 区别
train/S0509/BAC009S0509W0439.wav	 /home/wel/audio/thchs30/train/S0509/BAC009S0509W0439.wav	5.73	北京 公交 第 二 客运 分 公司 工作 人员 证实 此事

**Comment by tlikhomanenko** [comment]
close due to inactivity.
