### ISSUE TITLE
Dataset idx out of bound while calling through get()

### ISSUE THREAD

**Issue by juunnn** [facebookresearch/wav2letter#576]
Hi, I made two dataset using `w2l::createDataset()` (the one that being used in Train.cpp) and I want to get one datum from each dataset in one iteration. But each time I use method `get(idx)` I always get `Dataset idx out of range` even when I check manually it is not out of bound (I try using idx = 0). 
This is the code I try
```cpp

auto labeled = createDataset( <params> )
auto unlabeled = createDataset( <params> )

for ( int64_t i =0 ; i < *labeled->size(); i++) {
        // meters
        auto& sample = *labeled->get(i);
        auto& unlabel = *unlabeled->get(i);
        // Other training stuff
}
```
This is the error that I got:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  Dataset idx out of range
*** Aborted at 1584613459 (unix time) try "date -d @1584613459" if you are using GNU date ***
PC: @     0x7f9c6f769428 gsignal
*** SIGABRT (@0x10e41) received by PID 69185 (TID 0x7f9cb99da600) from PID 69185; stack trace: ***
    @     0x7f9cb1ce0390 (unknown)
    @     0x7f9c6f769428 gsignal
    @     0x7f9c6f76b02a abort
    @     0x7f9c700ac84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f9c700aa6b6 (unknown)
    @     0x7f9c700aa701 std::terminate()
    @     0x7f9c700aa919 __cxa_throw
    @           0x7f4df9 fl::Dataset::checkIndexBounds()
    @           0x802c71 w2l::W2lDataset::get()
    @           0x42678f _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES7_S_INS0_19FirstOrderOptimizerEES9_ddbiE3_clES2_S5_S7_S7_S9_S9_ddbi
    @           0x42c299 main
    @     0x7f9c6f754830 __libc_start_main
    @           0x423fc9 _start
    @                0x0 (unknown)
Aborted (core dumped)
```

I did also try using iterator from W2lDataset like this:
```cpp
      auto l = labeled->begin();
      auto u = unlabeled->begin();

      while ( ( l != labeled->end() ) && ( u != unlabeled->end() ) ){
          auto sample = *l ; l++;
          auto ulabel = *u ; u++;
          // other stuff
      }
```
but it never goes inside the while scoop. 

Can anybody please help me with this.
I really appreciate your time. Thank you.

**Comment by vineelpratap** [comment]
Hi,
 Could you check the size of `labeled->size()` and `unlabeled ->size()` before going into the `for` loop. 

Also, could you let us know a bit more about the `<params>` used while calling `createDataset`

**Comment by juunnn** [comment]
it turns out that my unlabeled dataset is 0 but my labeled dataset is non zero as expected. I don't get it why this happend, this is my code for that.

```cpp
auto labeledds = createDataset(
      FLAGS_labeled, dicts, lexicon, FLAGS_batchsize, worldRank, worldSize);

  auto unlabeledds = createDataset(
      FLAGS_unlabeled, dicts, lexicon, FLAGS_batchsize, worldRank, worldSize);
```

**Comment by juunnn** [comment]
Oh it is because I use the forth column on the dataset with invalid token (i use blank target) so the process of building dataset is corrupted. So i overcome this problem with inserting some "unk" target for the unlabeled dataset. Thank you for the response. I am going to close this.

**Comment by vineelpratap** [comment]
Cool. I believe you can also pass `mintsz=-1` so that target sizes of length 0 are not filtered.
