### ISSUE TITLE
[PSA] Streaming Inference C API + New English Model + Web Demo

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#577]
I've trained a new English streaming convnets model:
- I forked the Facebook 500ms model from [here](https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/streaming_convnets/librispeech), replacing the final linear layer, and regenerating tokens/lexicon using the `wpiece` command from [wav2train](https://github.com/facebookresearch/wav2letter/issues/509)
- I trained with several datasets totaling 13k hours of speech, including librispeech, the latest 1.5k hour Common Voice release, and about 9k hours of librilight, taken from 28k hours of librilight I aligned with [wav2train](https://github.com/facebookresearch/wav2letter/issues/509)

Model download: https://talonvoice.com/research/e44-sconv-inference.tar.gz

~Web demo of my model (streaming recognition, running on CPU): https://stream.talonvoice.com~ streaming demo is offline for now

Note the streaming demo is a greedy decoder with no language model. It's expected to have some artifacts around frame boundaries right now (like `hello lo` is not a problem, as it wouldn't do that with a language model)

The wav2letter frontend used by the web demo is in this branch, based on the fbgemm inference frontend: https://github.com/talonvoice/wav2letter/tree/w2lstream

## Model comparisons:

**Talon** is the model from this post.
**FB SOTA** is the SOTA Transformer S2S Librivox model.
**FB Conv** is the Facebook Streaming Convnet model.

**WER** is Word Error Rate, or % of words incorrect
**LER** is Letter Error Rate, or % of letters incorrect

<table>
<thead>
<tr>
<th></th>
<th colspan=2>Talon</th>
<th colspan=2>FB SOTA</th>
<th colspan=2>FB Conv</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td><i>WER</i></td>
<td><i>LER</i></td>
<td><i>WER</i></td>
<td><i>LER</i></td>
<td><i>WER</i></td>
<td><i>LER</i></td>
</tr>
<tr>
<td>librispeech clean</td>
<td>&nbsp;3.18</td>
<td>&nbsp;1.20</td>
<td>&nbsp;2.33</td>
<td>&nbsp;0.83</td>
<td>&nbsp;3.28</td>
<td>&nbsp;1.32</td>
</tr>
<tr>
<td>librispeech other</td>
<td>&nbsp;8.08</td>
<td>&nbsp;3.78</td>
<td>&nbsp;5.20</td>
<td>&nbsp;2.21</td>
<td>&nbsp;8.25</td>
<td>&nbsp;3.96</td>
</tr>
<tr>
<td>speech commands</td>
<td>&nbsp;2.38</td>
<td>&nbsp;2.13</td>
<td>23.05</td>
<td>17.11</td>
<td>18.48</td>
<td>14.37</td>
</tr>
<tr>
<td>common voice 1500</td>
<td>18.82</td>
<td>10.50</td>
<td>24.25</td>
<td>13.45</td>
<td>34.40</td>
<td>20.39</td>
</tr>
<tr>
<td>talon speech</td>
<td>33.42</td>
<td>14.28</td>
<td>42.04</td>
<td>16.88</td>
<td>61.12</td>
<td>25.17</td>
</tr>
<tr>
<td>words</td>
<td>23.24</td>
<td>&nbsp;6.19</td>
<td>51.08</td>
<td>17.26</td>
<td>55.49</td>
<td>21.73</td>
</tr>
<tr>
<td>english</td>
<td>11.45</td>
<td>&nbsp;5.86</td>
<td>12.85</td>
<td>&nbsp;6.84</td>
<td>14.72</td>
<td>&nbsp;7.64</td>
</tr>
</tbody>
</table>

### Dataset Info:
`common_voice_1500` is the latest Common Voice release
`english` is a private "mixed quality english sentence" dataset
`talon-speech` is difficult english speech from the prompts at https://speech.talonvoice.com
`words` is a private "single english word" dataset, with most words from the english dictionary.

This talon model is trained on the train set for the `words` dataset, but has never seen any part of these `english` or `talon-speech` datasets.

**Comment by vineelpratap** [comment]
Very cool demo !

**Comment by cri5Castro** [comment]
very nice job, question the acoustic_model.bin is converted to be used in the inference api right?, have you shared the checkpoint generated by wav2letter?

**Comment by lunixbochs** [comment]
I have not shared the checkpoint yet as it’s not compatible with my libw2l code yet (because libw2l is on such an old wav2letter version). For transfer learning, use the Facebook streaming convnet model I forked from for now. It’s still a pretty good model!

**Comment by tu1258** [comment]
> Note the streaming demo is a greedy decoder with no language model. It's expected to have some artifacts around frame boundaries right now (like `hello lo` is not a problem, as it wouldn't do that with a language model)
> ## Model comparisons:
> **Talon** is the model from this post.
> **FB SOTA** is the SOTA Transformer S2S Librivox model.
> **FB Conv** is the Facebook Streaming Convnet model.
> 
> **WER** is Word Error Rate, or % of words incorrect
> **LER** is Letter Error Rate, or % of letters incorrect
> 
> Talon	FB SOTA	FB Conv
> WER	LER	WER	LER	WER	LER
> librispeech clean	 3.18	 1.20	 2.33	 0.83	 3.28	 1.32
> librispeech other	 8.08	 3.78	 5.20	 2.21	 8.25	 3.96
> speech commands	 2.38	 2.13	23.05	17.11	18.48	14.37
> common voice 1500	18.82	10.50	24.25	13.45	34.40	20.39
> talon speech	33.42	14.28	42.04	16.88	61.12	25.17
> words	23.24	 6.19	51.08	17.26	55.49	21.73
> english	11.45	 5.86	12.85	 6.84	14.72	 7.64

Is the WER in the table using greedy decoder? If not, the performance when actually running streaming inference won't be as good as that on the table. I wonder the performance gap between greedy search and beam search(without LM) among these models. If the gap is not that large, then it's not a big problem I guess.

**Comment by lunixbochs** [comment]
The table was greedy search without a lexicon, LM, or beam search.

**Comment by erksch** [comment]
Hey @lunixbochs! Your work is remarkable! It would really help if you would open your fork for issues: I have some questions about building the libw2l since your repo has so many different branches by now.

**Comment by lunixbochs** [comment]
Enabled issues.
