### ISSUE TITLE
Support for per-word confidence scores?

### ISSUE THREAD

**Issue by alexcannan** [facebookresearch/wav2letter#578]
Hi there, I'm interested in building a speech recognition model that returns per-word confidence scores. I'm wondering if anyone has a better idea if this is possible with the wav2letter framework, and if so, any advice as to where I could add this functionality would be appreciated.

My initial thoughts are it would involve some rework, since the decoder is already very optimized...

**Comment by tlikhomanenko** [comment]
Please have a look discussion here on probability for the sequence, you can do the same things for the words only to accumulate scores for tokens from that word https://github.com/facebookresearch/wav2letter/issues/609.

**Comment by hosjiu1702** [comment]
> Please have a look discussion here on probability for the sequence, you can do the same things for the words only to accumulate scores for tokens from that word #609.

Could you provide some references or example code on this issue? Thanks in advance

**Comment by tlikhomanenko** [comment]
Did you check the conversations and code snippets in the https://github.com/flashlight/wav2letter/issues/609?
