### ISSUE TITLE
LibriSpeech training folders not created

### ISSUE THREAD

**Issue by madhavajay** [facebookresearch/wav2letter#58]
I am on Mac OSX and when I run:
```
luajit ~/wav2letter/data/librispeech/create.lua ~/LibriSpeech ~/librispeech-proc
```
I get the following error:
```
luajit: ./wav2letter/data/librispeech/create.lua:54: cannot open /Users/madhavajay/LibriSpeech/train-clean-100: No such file or directory
```

Simply creating all the expected folders fixes this issue.
I assume the code should create the folders if they don't exist?

**Comment by madhavajay** [comment]
I have attached a commit which fixes the folder issue on my machine.

**Comment by vineelpratap** [comment]
Hi, we do this for destination folder here already - https://github.com/madhavajay/wav2letter/blob/1da54efc56742a8fb365f244b77ff205630eed32/data/librispeech/create.lua#L157

Also regarding #58, the error seems to be because input directory path doesn't doesn't exist.

**Comment by madhavajay** [comment]
I followed the guide and downloaded and extracted the dev-clean.tar.gz file, which creates the LibriSpeech folder. Is there a step im missing which creates the train-clean-100 and other folders before running the create.lua script?

**Comment by vineelpratap** [comment]
Can you make sure the path where it is downloaded is `~/LibriSpeech` or you might have to use appropriate path in `luajit ~/wav2letter/data/librispeech/create.lua ~/LibriSpeech ~/librispeech-proc`

**Comment by madhavajay** [comment]
This is what happens to if I do the following:
- wav2letter on master
- freshly extracted dev-clean.tar.gz in ~
- run command as per instructions:

```
➜  wav2letter git:(master) ✗ git branch
  create-path-fix
* master
➜  wav2letter git:(master) ✗ cd ..
➜  ~ ls ./LibriSpeech
BOOKS.TXT    CHAPTERS.TXT LICENSE.TXT  README.TXT   SPEAKERS.TXT dev-clean
➜  ~ luajit ~/wav2letter/data/librispeech/create.lua ~/LibriSpeech ~/librispeech-proc

| parsing SPEAKERS.TXT for gender...
| analyzing /Users/madhavajay/LibriSpeech/train-clean-100...
luajit: /Users/madhavajay/wav2letter/data/librispeech/create.lua:54: cannot open /Users/madhavajay/LibriSpeech/train-clean-100: No such file or directory
stack traceback:
	[C]: in function 'dir'
	/Users/madhavajay/wav2letter/data/librispeech/create.lua:54: in function 'fileapply'
	/Users/madhavajay/wav2letter/data/librispeech/create.lua:72: in function 'createidx'
	/Users/madhavajay/wav2letter/data/librispeech/create.lua:152: in main chunk
	[C]: at 0x01004d0330
```

**Comment by vineelpratap** [comment]
Oh okay. Looks like you haven't downloaded all the files as it is required in https://github.com/facebookresearch/wav2letter/blob/master/data/librispeech/create.lua#L146-L149. Please see #5 .
