### ISSUE TITLE
AssertionError: Id 4a8c0201 is absent in the subset si_tr_s of transcription for file

### ISSUE THREAD

**Issue by zqs01** [facebookresearch/wav2letter#580]
I run this command in `recipe/data/wsj` : `python prepare.py --wsj0 /disk3/qszhu/data/WSJ/CSRI_WSJ0_LDC93S6A --wsj1 /disk3/qszhu/data/WSJ/CSRII_WSJ1_LDC94S13A  --wsj1_type LDC94S13A `

but get this error, how can I solve this problem?

Traceback (most recent call last):
  File "prepare.py", line 98, in <module>
    wsj1_sep,
  File "/disk3/qszhu/Net/wav2letter/recipes/data/wsj/utils.py", line 98, in ndx_to_samples
    sample_id, subset, fname
AssertionError: Id 4a8c0201 is absent in the subset si_tr_s of transcription for file /disk3/qszhu/data/WSJ/CSRII_WSJ1_LDC94S13A/13-11.1/wsj1/si_tr_s/4a8/4a8c0201.wv1

**Comment by zqs01** [comment]
![image](https://user-images.githubusercontent.com/40491290/77280306-ed7b5f80-6cfe-11ea-94f0-f38d50e51703.png)

`4a8c0201.wv1` file is actually in this folder.

**Comment by tlikhomanenko** [comment]
Hi @zqs01,

Please check that you have the following file and transcription for the file you have an assertion
```
wsj/csr_2_comp$ cat 13-34.1/wsj1/trans/wsj1/si_tr_s/4a8/4a8c0200.dot | grep 4a8c0201
The spokeswoman declined to identify possible uses for the company\'s cash other than the stock buyback (4a8c0201)
```

or in you paths:
```
# check that dot file with transcriptions exists
ls /disk3/qszhu/data/WSJ/CSRII_WSJ1_LDC94S13A/13-34.1/wsj1/trans/wsj1/si_tr_s/4a8/4a8c0200.dot
# check that your file has transcription in the dot file
cat /disk3/qszhu/data/WSJ/CSRII_WSJ1_LDC94S13A/13-34.1/wsj1/trans/wsj1/si_tr_s/4a8/4a8c0200.dot | grep 4a8c0201
```

**Comment by zqs01** [comment]
@tlikhomanenko Thank you! It is the problem that you pointed out.
