### ISSUE TITLE
Question regarding --samplerate

### ISSUE THREAD

**Issue by davidbelle** [facebookresearch/wav2letter#583]
Hello

I have a need to transcribe audio that has an 8k sample rate. I saw the --samplerate flag, but I also noticed --noresample flag as well which has a default value of false.

Is my understand correct, that if I set the --samplerate flag to 8000 during training, wav2letter will automatically resample that audio to 8k unless --noresample is set to true?
On the same hand, is it also the case that if I download the dataset and resample all audio files to 8k before running the training, I don't need to set either of these two flags?  

Or on the contrary, does wav2letter just default to assuming the audio files are 16k? (In which case it's better to have wav2letter do the resampling)?

One final question, if my model was trained using 8k audio, and the audio I'm about to decode is also 8k, do I need to set the --samplerate option for decoding too? 

Thanks :)

**Comment by vineelpratap** [comment]
For audio at 8000Hz samplingrate audio, setting --samplerate=8000 should work. `--noresample` is related to shuffling of dataset and has nothing to do with sampling rate of audio. 

> if my model was trained using 8k audio, and the audio I'm about to decode is also 8k, do I need to set the --samplerate option for decoding too

No need to set it for decoding. It will use the value from training automatically.

**Comment by davidbelle** [comment]
Great! Thanks.
