### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by 4D1B** [facebookresearch/wav2letter#585]
I am quite new to command line and trying to set up wav2letter in my virtual Box(Ubuntu 18.4)

I am having these errors while trying to building wav2letter.

Having said that, I have had many issues but this one, I am not sure, where to search it anymore. Followed a previous thread on this issue but didn't work for me. 

I am attaching pictures of both of the build command in here. I would really appreciate any sort of help in this regard. 
![image](https://user-images.githubusercontent.com/48805976/77725003-88857980-701e-11ea-9b9f-c25bb252bfb4.png) 
![image](https://user-images.githubusercontent.com/48805976/77725045-a6eb7500-701e-11ea-898d-ea6150917b35.png)

**Comment by tlikhomanenko** [comment]
@4D1B,

could you attach full log of cmake for flashlight?

@jacobkahn, any idea what is going wrong?

**Comment by jacobkahn** [comment]
@4D1B — as the error message says, you have to link to a version of flashlight which is built with distributed training enabled. See the [flashlight build docs](https://fl.readthedocs.io/en/latest/installation.html#build-options) for more details, and make sure you build with `FL_BUILD_DISTRIBUTED=ON` (which it appears you've disabled).

**Comment by 4D1B** [comment]
I had solved that issue by rebuilding from scratch.
