### ISSUE TITLE
GLU fbgemm

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#586]
Do you have an implementation of the GLU module for the fbgemm inference backend already?

**Comment by vineelpratap** [comment]
Hi, 
  We currently don't have the GLU activation implemented.

**Comment by lunixbochs** [comment]
Have any tips for effectively using fbgemm for it if I wanted to do it?

**Comment by vineelpratap** [comment]
Hi, 
 I don't think we can make much use of FBGEMM for GLU. If you really want to optimize, you may be able to make use of some BLAS functions like vsExp, vsLinearFrac to perform the sigmoid operation required for GLU. But honestly, I would expect a simple `for` loop would be enough as it won't be the bottleneck in the network.  

You can check https://github.com/facebookresearch/wav2letter/blob/master/inference/inference/module/nn/Relu.h for an example that implements activation without depending on FBGEMM.

**Comment by lunixbochs** [comment]
Thanks, that's very helpful!
