### ISSUE TITLE
incorrect file link for SOTA2019 LibriSpeech TDS CTC Archfile

### ISSUE THREAD

**Issue by khu834** [facebookresearch/wav2letter#590]
The file link for SOTA 2019 LibriSpeech TDS CTC Archfile currently points to:
https://dl.fbaipublicfiles.com/wav2letter/sota/2019/am/am_resnet_ctc.arch

I'm assuming it should be at
https://dl.fbaipublicfiles.com/wav2letter/sota/2019/am/am_tds_ctc.arch
But the file path does not exist.

Can this link be updated to the correct file?

**Comment by vineelpratap** [comment]
Hi, 
 `am_resnet_ctc.arch` seems correct to me. Any reason you think it is incorrect ?

**Comment by khu834** [comment]
I'm not saying the `am_resnet_ctc.arch` file has problems.
I'm saying that it is listed under `TDS CTC`. I would assume that TDS CTC models are trained with TDS CTC architecture, in this case, it is pointed to a resnet architecture, which seems odd.

**Comment by vineelpratap** [comment]
Got it. Will fix soon.
