### ISSUE TITLE
Permission Denied for Simple Streaming ASR Example using Docker 

### ISSUE THREAD

**Issue by realbaker1967** [facebookresearch/wav2letter#595]
Hi, 

My system is Ubuntu 16.04, and I use docker version 19.03.8.
I am trying to follow the example [here](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#simple-streaming-asr-example-using-docker) with the following command:

`sudo docker run  --rm -v  /home/baker/workspace/cpp/wav2letter:/root/host/ -it --ipc=host --name w2l -a stdin -a stdout -a stderr wav2letter/wav2letter:inference-latest sh -c "/root/host/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | /root/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path /root/host/model"`

and I got a **permission denied** for the flac.wav file and could not really solve the issue:

```
sh: 1: /root/host/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav: Permission denied
Started features model file loading ... 
Completed features model file loading elapsed time=1140 microseconds

Started acoustic model file loading ... 
Completed acoustic model file loading elapsed time=2440 milliseconds

Started tokens file loading ... 
Completed tokens file loading elapsed time=776 microseconds

Tokens loaded - 9998 tokens
Started decoder options file loading ... 
Completed decoder options file loading elapsed time=38 microseconds

Started create decoder ... 
[Letters] 9998 tokens loaded.
[Words] 200001 words loaded.
Completed create decoder elapsed time=1137 milliseconds

Started converting audio input from stdin to text... ... 
Creating LexiconDecoder instance.
#start (msec), end(msec), transcription
0,0,
Completed converting audio input from stdin to text... elapsed time=116 milliseconds
```

There is no problem with mounting as the container successfully reads the model. Could you please help me with that?

Thank you!

**Comment by tlikhomanenko** [comment]
@realbaker1967,

Try to run `cat` for the audio file before sending it to the pipe:
```
sudo docker run --rm -v /home/baker/workspace/cpp/wav2letter:/root/host/ -it --ipc=host --name w2l -a stdin -a stdout -a stderr wav2letter/wav2letter:inference-latest sh -c "cat /root/host/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | /root/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path /root/host/model"
```

**Comment by realbaker1967** [comment]
Thanks, it works.
