### ISSUE TITLE
DecoderTest failing

### ISSUE THREAD

**Issue by adamchant** [facebookresearch/wav2letter#596]
Hey there,
   Can anyone help me out with this issue, the decoder binary has stopped working after I reran cmake and make in the build directory. And im unable to run any decoding script.
make test after build returned :
   11/31 Test #11: DecoderTest ......................***Exception: Child aborted  0.65 sec
97% tests passed, 1 tests failed out of 31
Total Test time (real) =  94.69 sec
The following tests FAILED:
	 11 - DecoderTest (Child aborted)
Errors while running CTest
Makefile:118: recipe for target 'test' failed
make: *** [test] Error 8

And when i run the DecoderTest binary in src/tests
I get the following log, 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DecoderTest
[ RUN      ] DecoderTest.run
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0403 16:30:10.350185 26661 DecoderTest.cpp:90] [Serialization] Loaded emissions [235 x 29]
I0403 16:30:10.420697 26661 DecoderTest.cpp:98] [Dictionary] Number of words: 26710
Loading the LM will be faster if you build a binary file.
Reading /home/dev/wav2letter/src/decoder/test/lm.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
I0403 16:30:10.480114 26661 DecoderTest.cpp:103] [Decoder] LM constructed.
corrupted size vs. prev_size
Aborted (core dumped)

I have read a few similar issues related to kenLM build, and i have built it max order=20 as shown in the install dependency wiki, but still facing this issue....
can someone help me with this issue, I'm unable to resolve it and it is a little urgent.
Thanks

**Comment by tlikhomanenko** [comment]
Hi @adamchant, could you provide your system info, commit of w2l at which you are running and the way you installed (docker image or locally on the machine)?

**Comment by adamchant** [comment]
Hi @tlikhomanenko , thanks for your reply...
I am currently running on cuda 10.2, cudnn 7.6.5, Tesla T4 GPU
I have built it on the latest commit,id: e7b8537c37465f44ca5ef4169764df06e35663cf
I have built it locally following the installation instructions in the wav2letter wiki.
I tried rebuilding in another machine, running on cuda 10.0, cudnn 7.6.5 and also Tesla T4, also on the same commit (e7b8537c37465f44ca5ef4169764df06e35663cf), and even there im getting the sane issue, all test cases are passing but the DecoderTest, and running the DecoderTest binary gives the same output.
Thanks

**Comment by tlikhomanenko** [comment]
which OS are you using and what are compiler and cmake versions?

**Comment by kksiddharth** [comment]
Im runnin ubuntu 18.04,
gcc compiler version:  gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 (on the cuda 10.0 machine)
and gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026 (on the cuda 10.2 machine)
, and cmake version : cmake version 3.10.2 (both have the same cmake version)

**Comment by adamchant** [comment]
I'm runnin ubuntu 18.04,
gcc compiler version: gcc (Ubuntu 7.5.0-3ubuntu118.04) 7.5.0 (on the cuda 10.0 machine)
and gcc (Ubuntu 6.5.0-2ubuntu118.04) 6.5.0 20181026 (on the cuda 10.2 machine)
, and cmake version : cmake version 3.10.2 (both have the same cmake version)

**Comment by adamchant** [comment]
Hey, i was able to solve this by remaking kenlm,
Instead of running cmake .. -DCMAKE_BUILD_TYPE=Release -DKENLM_MAX_ORDER=20 -DCMAKE_POSITION_INDEPENDENT_CODE=ON, as shown in the wiki,
i used cmake ..
and it seemed to work, thanks

**Comment by tlikhomanenko** [comment]
@adamchant, nice, thanks for finding solution!

I think this also should work https://github.com/facebookresearch/wav2letter/blob/master/Dockerfile-CUDA-Base#L87

FYI:
- `-DKENLM_MAX_ORDER=20` is needed if you want to train 7-gram and more grams model not specifying this flags allows only to train 1-6 grams language models)
- `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` is necessary if you want to build python bindings and use decoder from python.

Maybe `-DCMAKE_BUILD_TYPE=Release` breaks the correct build (which is strange) or above flags somehow. Your gcc and cmake version looks fine for me.

Anyway, glad that `cmake ..` works for you.
