### ISSUE TITLE
Train on chinese data.

### ISSUE THREAD

**Issue by jkkj1630** [facebookresearch/wav2letter#597]
I am using wav2letter to train Chinese data, but there may be many pronunciations of a letter in Chinese. Unfortunately, the pronunciation of each letter is not regular. The pronunciation of letters has different pronunciations according to different contexts. Is there any related support,thanks.

**Comment by lunixbochs** [comment]
If you train a wav2letter model it can learn context when determining pronunciation if you have enough examples. The streaming convnet and SOTA models should be even better at this than the original conv_glu model.

**Comment by jkkj1630** [comment]
My situation is like this:

lexicon.txt:
的 de0 |
的 di2 |
了 le0 |
了 liao3 |
和 he2 |
和 huo2 |
和 he4 |

one letter have mutil pronunciations, it pronunciations ，The pronunciation of a single word is relevant to the context。

好     |     的     |     那     |     就     |     这     |     样
hao3|     de0   |     na4   |    jiu4    |    zhe4  |   yang4

的     |    确     |    是     |    这     |    样
di2    |   qve4 |   shi4   |   zhe4  |   yang4

"的" has two pronunciations in different contexts

**Comment by jkkj1630** [comment]
I saw in WordUtils.cpp and WordUtils.h that the way lexicon.txt is read is LexiconMap, which is a std :: unordered_map <std :: string, std :: vector <std :: vector <std :: string> >>, a word to vector mapping, does this mean that multiple pronunciations of word can be stored in the vector? During training, will the pronunciation be adaptively selected according to various situations?

**Comment by lunixbochs** [comment]
Yes, multiple token representations can be provided for a word in the lexicon

**Comment by kenxiexiaolong** [comment]
嗨，哥们，中文训练的有进展没？

**Comment by lixinyu2001** [comment]
主要是找一个汉字转拼音的好软件
