### ISSUE TITLE
Checking nature of acousitc model

### ISSUE THREAD

**Issue by erksch** [facebookresearch/wav2letter#598]
Hey there!

Thank you for your great work here!

I am getting a little bit confused about all the different types of models and criterions wav2letter supports (TDS, CTC, ASG, Seq2Seq). I have a german model for wav2letter++ from [zamia speech](https://zamia.org/asr/) which is just a acoustic model binary with tokens and lexikon. How do I know which type of model & criterion this is, since this is important for converting it with streaming_tds_model_converter which only supports TDS + CTC models. 

Is there a script to get information more about a model binary?

**Comment by erksch** [comment]
Small followup regarding conversion: 
As of [the tools readme](https://github.com/facebookresearch/wav2letter/tree/master/tools), conversion with `streaming_tds_model_converter` looks simple by just passing the acoustic model to the script, but in reality, I have to pass criterion, architecture file (which I don't have from the model), a flagsfile (also missing) and many more. 

Maybe some more information in the tools readme about what is needed to be passed to the converter, and what files do you need to have at hand, would be very helpful!

**Comment by lunixbochs** [comment]
The zamia model is probably conv_glu, doubly so if it's around 1.6GB https://github.com/gooofy/zamia-speech/blob/master/data/src/speech/w2l_config_conv_glu_network.arch

**Comment by erksch** [comment]
Hey, @lunixbochs thanks for your reply and the clarification.
Yeah, I checked the files from Zamia and it seems to be a Conv Glu with ASG criterion (from the original wav2letter paper). Too bad, maybe I'll train my own streaming convnet for german with the data framework zamia already has available :)

**Comment by realbaker1967** [comment]
Hey @erksch, somewhat related question. 

Do you think that zamia speech people used greedy decoding as explained [here](https://github.com/facebookresearch/wav2letter/wiki/Beam-Search-Decoder#greedy-path) to get somewhat similar performance to the result [here](https://zamia.org/asr/)? 

I would like to do a benchmark using their pre-trained german acoustic model but don't know how to proceed. 

Best

**Comment by erksch** [comment]
@realbaker1967 Hmm, they state nowhere that they used a language model and beam search decoding. But I guess you have to use a language model to achieve that low WER. 

What do you mean you don't know how to proceed? Where are you stuck? 
Download the acoustic model from Zamia, run the decode executable (by building yourself or in docker) and check the results :D

**Comment by realbaker1967** [comment]
Thank you for the answer. 

I meant, if I want to use a language model, there are parameters to set for decoding, that is why I am confused about how to produce performance similar to the WER that they report.

**Comment by lagidigu** [comment]
It also seems like the [zamia decode template](https://github.com/gooofy/zamia-speech/blob/master/data/src/speech/w2l_run_decode.sh.template) does not yield the accuracy that is reported, probably due to an update of w2l. 

Did anyone manage to achieve the same WER with the current commit of w2l?
