### ISSUE TITLE
Running interactive_streaming_asr_example in a server-client fashion

### ISSUE THREAD

**Issue by realbaker1967** [facebookresearch/wav2letter#601]
Hi, 

I would like to use **interactive_streaming_asr_example** in a server-client fashion, where I need to run inference-latest image on a remote machine which should serve as a server, and I will send a wav file from client to the server in bytes using post request and the server returns corresponding transcriptions. 

In other words,  **interactive_streaming_asr_example** does not wait for paths for audio files, instead waits byte streams of audio files. 

Is this feature available right now, or should I build my own image? 

Thanks.

**Comment by avidov** [comment]
The multithreaded_streaming_asr_example is a good example of how to setup ASR service backend. You can use that to spawn ASR server. 
The interactive_streaming_asr_example is a good example for quick local experimentation shell. 
You can stitch them together but you'll need to:
- Set up a service using the multithreaded_streaming_asr_example.
- Create a client to that service.
- Hook the client as the back end of the interactive_streaming_asr_example.
