### ISSUE TITLE
[Question] how to limit GPU memory usage  during model training?

### ISSUE THREAD

**Issue by xiaotaw** [facebookresearch/wav2letter#603]
Wav2letter seems to use all the GPU memory during training as it could, even when cutting off network layers.

Once wav2letter started training on a card, there is no free  memory left for other programs. It's frustrating.

**Comment by jacobkahn** [comment]
@xiaotaw — this depends on the size of your model. When we want to increase model size, we make the models as large as they can be such that they fit in GPU memory, so we're not anticipating using other models that might not fit. I'd recommend looking in some of the TDS models; they're a bit smaller than the convolutional and resnet models.
