### ISSUE TITLE
Inference fails with SIGILL (Illegal instruction) on CPU without AVX2

### ISSUE THREAD

**Issue by daanzu** [facebookresearch/wav2letter#604]
It appears that it is using a AVX2 FBGEMM function, even though my CPU doesn't support AVX2 (or AVX for that matter). I don't know whether the cause of this lies in wav2letter or FBGEMM.

```
> gdb inference/inference/examples/simple_streaming_asr_example
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from inference/inference/examples/simple_streaming_asr_example...(no debugging symbols found)...done.
(gdb) run --input_files_base_path ~/decode_test/wav2letter/model < ~/decode_test/wav2letter/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav
Starting program: /home/daanzu/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path ~/decode_test/wav2letter/model < ~/decode_test/wav2letter/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Started features model file loading ...
Completed features model file loading elapsed time=71285 microseconds

Started acoustic model file loading ...
Completed acoustic model file loading elapsed time=3383 milliseconds

Started tokens file loading ...
Completed tokens file loading elapsed time=844 microseconds

Tokens loaded - 9998 tokens
Started decoder options file loading ...
Completed decoder options file loading elapsed time=49 microseconds

Started create decoder ...
[Letters] 9998 tokens loaded.
[Words] 200001 words loaded.
Completed create decoder elapsed time=1134 milliseconds

Started converting audio input from stdin to text... ...
Creating LexiconDecoder instance.
#start (msec), end(msec), transcription

Program received signal SIGILL, Illegal instruction.
0x000055555562f41c in fbgemm::gemmkernel_6x2_Avx2_fp16_fA0fB0fC0(fbgemm::GemmParams<unsigned short>*) ()
```

**Comment by bkkblue** [comment]
I had the same issue when I ran  simple_streaming_asr_example .
`~/work/w2l/cpu> cat /root/work/w2l/cpu/audio/LibriSpeech/dev-clean/6295/64301/6295-64301-0004.flac.wav | /root/work/w2l/cpu/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path ./model
Started features model file loading ... 
Completed features model file loading elapsed time=31110 microseconds

Started acoustic model file loading ... 
Completed acoustic model file loading elapsed time=11088 milliseconds

Started tokens file loading ... 
Completed tokens file loading elapsed time=1647 microseconds

Tokens loaded - 9998 tokens
Started decoder options file loading ... 
Completed decoder options file loading elapsed time=89 microseconds

Started create decoder ... 
[Letters] 9998 tokens loaded.
[Words] 200001 words loaded.
Completed create decoder elapsed time=2585 milliseconds

Started converting audio input from stdin to text... ... 
Creating LexiconDecoder instance.
#start (msec), end(msec), transcription
Illegal instruction (core dumped)

~/work/w2l/cpu> gdb /root/work/w2l/cpu/wav2letter/build/inference/inference/examples/simple_streaming_asr_example core
....
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00000000005b9a77 in fbgemm::gemmkernel_6x2_Avx2_fp16_fA0fB0fC0(fbgemm::GemmParams<unsigned short>*) ()`

**Comment by tlikhomanenko** [comment]
@avidov

**Comment by lunixbochs** [comment]
@daanzu run `x/i $rip` in gdb after the crash to see the faulting instruction

**Comment by bkkblue** [comment]
> My money's on this being an FBGEMM thing. 

-----Maybe It's time to upgrade my CPU and others, too. It only supports AVX, but not avx2 now.

**Comment by lunixbochs** [comment]
The MKL-DNN wav2letter backend works great still, and can target SSE4.

**Comment by daanzu** [comment]
@lunixbochs Oops, my quick search for info on FBGEMM & AVX somehow missed that, and I figured surely it must have some kind of fall back or at least a sensible error message for missing AVX.

Is the MKL-DNN wav2letter backend part of the inference backend, or something separate?

**Comment by bkkblue** [comment]
@daanzu I only found  fbgemm in the CMakeLists.txt, but I couldn't find the MKL-DNN in the CMakeLists or the inference backend dir. 
```
wav2letter# find . -name "*.*" | xargs grep  "AVAILABLE_INFERENCE_BACKENDS"
...
inference/CMakeLists.txt:set(AVAILABLE_INFERENCE_BACKENDS fbgemm)
...
inference/module/nn/backend# ls
fbgemm
inference/module/nn/backend#
```
How to switch to the MKL-DNN wav2letter backend? @lunixbochs

**Comment by lunixbochs** [comment]
A possibly awful solution is to fallback to the reference C implementation: https://github.com/pytorch/FBGEMM/blob/880ade142005368d62de356d0910788e36de7c5c/src/FbgemmFP16.cc#L358

**Comment by bkkblue** [comment]
@lunixbochs  Thanks . I released the annotation of the define code  and It can work now. But it will spend a lot of time waiting for the transcription result. 
```
Started converting audio input file=/w2l/cpu/audio/LibriSpeech/dev-clean/6295/64301/6295-64301-0013.flac.wav to text... ... 
Creating LexiconDecoder instance.
#start (msec), end(msec), transcription
0,1000,
1000,2000,but in his 
2000,3000,hands 
3000,4000,solitude and 
4000,5000,a violin were 
5000,6000,sure to marry in 
6000,6000,music 
Completed converting audio input file=w2l/cpu/audio/LibriSpeech/dev-clean/6295/64301/6295-64301-0013.flac.wav to text... 
elapsed time=1227 seconds
```

**Comment by lunixbochs** [comment]
Ok, you’re much better off building the non inference frontend for now. That’s just the Test or Decode binary, which will use mkldnn.

**Comment by vineelpratap** [comment]
@bkkblue - Currently, we expect users to pass the all the CPU requirements necessary for FBGEMM to be able to run streaming inference. 

Also, please close the talk if you have solved the issue.

**Comment by lunixbochs** [comment]
I think this should just be repurposed into a generic "please add support for non-AVX2 streaming" issue, as the workaround I posted is like 500x realtime factor so it's not really usable.

**Comment by daanzu** [comment]
I would agree with @lunixbochs, but I also think there should be a check during initialization or compilation to give a useful error message if AVX2 support is missing, rather than just bombing out during inference.

**Comment by bkkblue** [comment]
I ran the streaming inference on another computer which support AVX2 .It can work well. I think the issue have been fixed.It should be closed. @daanzu

**Comment by bkkblue** [comment]
> Ok, you’re much better off building the non inference frontend for now. That’s just the Test or Decode binary, which will use mkldnn.

------- @lunixbochs .Yes,Thanks for your advise.  I ran the mkldnn version on your acvice just for test. The mkldnn version will cost too many time to print the result. So, it's better to switch to the FBGEMM version. In fact, it can work on a device whitch support avx2.  Thanks for your help.
