### ISSUE TITLE
train using multiple GPU

### ISSUE THREAD

**Issue by dtchantao** [facebookresearch/wav2letter#605]
hi there

I am trying to use multiple GPU (on the same PC) to train AM.

For example, CUDA_VISIBLE_DEVICES=0,1,2,3 Train ...

However, when I check nvidia-smi, only GPU 3 has been used. How shall I use all my GPUs to train?

Thanks!

**Comment by tlikhomanenko** [comment]
Hi @dtchantao,

Here is the doc https://github.com/facebookresearch/wav2letter/wiki/Distributed-training how to run on several GPUs: you need run with mpirun. 

If you run like `./Train train ...` it will run only on one GPU.

**Comment by dtchantao** [comment]
> Hi @dtchantao,
> 
> Here is the doc https://github.com/facebookresearch/wav2letter/wiki/Distributed-training how to run on several GPUs: you need run with mpirun.
> 
> If you run like `./Train train ...` it will run only on one GPU.

Hi @tlikhomanenko 

Thanks for your reply. I tried this one, but what I need is divided the model into several GPU which means in current command , my gpu will out of memory. When I use mpirun, it doesn;t help. The command seems to run whole model on every GPU.

**Comment by tlikhomanenko** [comment]
@dtchantao,

We don't support the case when model itself is distributed on several GPUs. We support only distributed learning over the data, not over the model. And for now we have no plans to support this functionality. 

Are you trying to train very huge model or do you have small GPU memory? In the latest case you can try to use TDS model for inference which is 37M parameters with sgd with momentum as optimizer (which can save also the memory on optimizer) and use batchsize=1 during training but in distributed regime, so the total batch will be the number of GPUs you have.

**Comment by dtchantao** [comment]
> @dtchantao,
> 
> We don't support the case when model itself is distributed on several GPUs. We support only distributed learning over the data, not over the model. And for now we have no plans to support this functionality.
> 
> Are you trying to train very huge model or do you have small GPU memory? In the latest case you can try to use TDS model for inference which is 37M parameters with sgd with momentum as optimizer (which can save also the memory on optimizer) and use batchsize=1 during training but in distributed regime, so the total batch will be the number of GPUs you have.

@tlikhomanenko 

Thanks for your suggestion, does this work for multiple GPU on different pc?

**Comment by jacobkahn** [comment]
@dtchantao — take a look at the [flashlight distributed training tutorial](https://fl.readthedocs.io/en/latest/distributed.html#distributedinit-mpi). You need to use some way of running multiple `Train` processes. `mpirun` accomplishes this and will be available with your OpenMPI installation. You can run:
```
mpirun -n 4 ./Train ...
```
to run training on 4 GPUs.

**Comment by tlikhomanenko** [comment]
@dtchantao 

You can use our distributed learning for multiple GPUs on different PC. But running the processes depends on your settings. The idea behind is the same as @jacobkahn  and I mentioned above. Here are parameters for distributed learning which can help you to set running on several nodes/several GPUs https://github.com/facebookresearch/wav2letter/blob/master/src/common/Defines.cpp#L312.
