### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by hajix** [facebookresearch/wav2letter#608]
Hi

Currently wav2letter support spectrogram augmentation (SAUG) and dither noise. What if I want to apply more augmentation? What is the proposed way of doing some augmentation say adding modeled noise (pink, babble, etc.), adding tempo and gain perturbations?

I also read in `SpecAugment.h` that currently time warping is not supported. Is it a WIP or there is no plan to implement this source of noise?

Thank you in advance

**Comment by AVSuni** [comment]
Since my question is about the same topic, I will add it here. The architecture file for the streaming convs includes SpecAugment as suggested by the paper. However, the config-file does not have SAUG flags (`--use_saug` and `--saug_start_update`). Is either/both of these flags unnecessary if the architecture file already includes SAUG?

**Comment by tlikhomanenko** [comment]
@AVSuni 

In case of transformer AM model we need to have warmup stage during which we don't use augmentation. To support this for now we solved it by added flags `use_saug` and `saug_start_update`. So in case you want to train model with warmup (and no augmentation during warmup) you just operate with these flags and spec augment flags and don't include SAUG layer in the arch file. If you don't do warmup you can simply specify SAUG layer in the arch. 

Also now one can use more complicated combinations, like use augmentation at some specific period of time during training.

**Comment by hajix** [comment]
@tlikhomanenko 

Is time warping applied in SAUG or not? I'm a little bit confused with the documentation.

**Comment by tlikhomanenko** [comment]
@hajix, sorry for delay in answering.

About SpecAugment: 
- In SAUG there is no time warping
- in the original paper they didn't see huge gain with time warping. For now it is not top priority for us to add time warping, but any pull request is welcome. 

About other augmentations:
- If you need more augmentation you always can add them by yourself following the interface of SpecAugment. 
- We have plans to add more augmentations, but this won't happen in upcoming weeks.

And always pull requests are welcome and appreciated!
