### ISSUE TITLE
Sequence Probabilities

### ISSUE THREAD

**Issue by NatSp** [facebookresearch/wav2letter#609]
Hi, I was wondering if there is a way to get the sequence probability for each output of the decoder in order to know how confident was the model for the specific sequence.

**Comment by tlikhomanenko** [comment]
Hi @NatSp,

Yep. You can find example how we use this score here https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L632. Decoder result from `decoder->decode(...)` is defined in https://github.com/facebookresearch/wav2letter/blob/7a9696dc2f7518642a3f1908d6ed298901e108c0/src/libraries/decoder/Utils.h#L64 where score is a total decoder score, amScore is a score based on emissions (+transitions in case of ASG) only and lmScore is LM score.

**Comment by NatSp** [comment]
Hi @tlikhomanenko, firstly thanks for replying to my question. I was wondering about the meaning of the decoder score provided because it is not between 0 and 1, so it is not a probability. Is there a way to get from that score the probability of the sequence?

**Comment by tlikhomanenko** [comment]
During decoding we use unnormalized scores from the emission matrix (which means we don't apply softmax at the end). Mathematically for decoder optimization normalization constant doesn't matter here and operating with log probs is more numerically stable. So to have at the end normalized AM scores you can add call to the logSoftmax after this line https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L360 (because inside we do summation of scores, not multiplication of probs) and at the end your AM_score will be total log AM_prob of the transcription. Just apply exp here to get AM prob. 

LM scores are computed from the LM itself, and LM in our interface returns log probs which are summed up during decoding. So at the end LM score is total log prob of the transcription. Just exp it and you will get LM prob (be care for KenLM it is log10 prob, so you need to call 10^LM_score).

Now about decoder score. It is defined (simple variant) as AM_score + alpha * LM_score, which if you apply logSoftmax on emissions will be equal to log AM_prob + alpha * log LM_prob. And to convert decoder score to the prob you need to apply softmax, which is intractable because you need to compute decoder score for all possible transcriptions (within time T). Thus here you can only operates with ranking score, not probability itself. Or compute some approximated probability doing softmax over the transcriptions in the beam.

Hope this answers your questions and will help you!

**Comment by NatSp** [comment]
@tlikhomanenko thanks for replying. Is it possible to explain in more detail how to compute the approximated probability you mention?

**Comment by tlikhomanenko** [comment]
@NatSp 

You compute large beam. For each hyp you will have decoder score and you do softmax over decoder scores in the beam, so normalization will be done only along the beam. At least this makes sense: what is the probability to be ranked as top-1 hyp in the final beam - this what exactly you will have as estimated probability.

**Comment by NatSp** [comment]
@tlikhomanenko Sorry I am bothering you again! I am new to c++ and I can't understand how to do that in your code. Could you tell me what changes I have to do?

**Comment by tlikhomanenko** [comment]
try to add the following after line https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L560:
```
double normalization = 0;
double maxScore = std::max_element(results.begin(), results.end(), [](const DecodeResult& v1, const DecodeResult& v2){return v1.score > v2.score;});
for (int indHyp = 0; indHyp < results.size(); indHyp++) {
  normalization += std::exp( results[indHyp].score - maxScore);
}
double currentProb = std::exp(results[i].score - maxScore + std::log(normalization));
```
and then add after line https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L602
```
<< ", Probability: " << currentProb
```
add `#include <cmath> ` in the include section at the beginning.

**Comment by tranmanhdat** [comment]
> try to add the following after line https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L560:
> 
> ```
> double normalization = 0;
> double maxScore = std::max_element(results.begin(), results.end(), [](const DecodeResult& v1, const DecodeResult& v2){return v1.score > v2.score;});
> for (int indHyp = 0; indHyp < results.size(); indHyp++) {
>   normalization += std::exp( results[indHyp].score - maxScore);
> }
> double currentProb = std::exp(results[i].score - maxScore + std::log(normalization));
> ```
> 
> and then add after line https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L602
> 
> ```
> << ", Probability: " << currentProb
> ```
> 
> add `#include <cmath> ` in the include section at the beginning.

can you help, when i build it had a error:
/root/wav2letter/Decode.cpp:566:155: error: cannot convert '__gnu_cxx::__normal_iterator<const w2l::DecodeResult*, std::vector<w2l::DecodeResult> >' to 'double' in initialization
         double maxScore = std::max_element(results.begin(), results.end(), [](const DecodeResult& v1, const DecodeResult& v2){return v1.score > v2.score;});

**Comment by tlikhomanenko** [comment]
@tranmanhdat  Please change the line on max element to 
```
double maxScore = std::max_element(results.begin(), results.end(), [](const DecodeResult& v1, const DecodeResult& v2){return v1.score > v2.score;}).score;
```

**Comment by tranmanhdat** [comment]
> @tranmanhdat Please change the line on max element to
> 
> ```
> double maxScore = std::max_element(results.begin(), results.end(), [](const DecodeResult& v1, const DecodeResult& v2){return v1.score > v2.score;}).score;
> ```

it doesn't work, so i do a loop to get score:
```
double maxScore = 0 ;
          for (int indHyp = 0; indHyp < results.size(); indHyp++)
          {
            if (results[indHyp].score > maxScore) 
              maxScore = results[indHyp].score;
          }
```
Thanks

**Comment by tranmanhdat** [comment]
> During decoding we use unnormalized scores from the emission matrix (which means we don't apply softmax at the end). Mathematically for decoder optimization normalization constant doesn't matter here and operating with log probs is more numerically stable. So to have at the end normalized AM scores you can add call to the logSoftmax after this line https://github.com/facebookresearch/wav2letter/blob/master/Decode.cpp#L360 (because inside we do summation of scores, not multiplication of probs) and at the end your AM_score will be total log AM_prob of the transcription. Just apply exp here to get AM prob.
> 
> LM scores are computed from the LM itself, and LM in our interface returns log probs which are summed up during decoding. So at the end LM score is total log prob of the transcription. Just exp it and you will get LM prob (be care for KenLM it is log10 prob, so you need to call 10^LM_score).
> 
> Now about decoder score. It is defined (simple variant) as AM_score + alpha * LM_score, which if you apply logSoftmax on emissions will be equal to log AM_prob + alpha * log LM_prob. And to convert decoder score to the prob you need to apply softmax, which is intractable because you need to compute decoder score for all possible transcriptions (within time T). Thus here you can only operates with ranking score, not probability itself. Or compute some approximated probability doing softmax over the transcriptions in the beam.
> 
> Hope this answers your questions and will help you!

can you show what default value is _alpha_?

**Comment by tlikhomanenko** [comment]
By default it is zero (see `--lmweight`).
