### ISSUE TITLE
Language Modeling for Hindi/Devnagari | Seq2Seq  

### ISSUE THREAD

**Issue by mrinal-sourav** [facebookresearch/wav2letter#611]
Hi Team, 

I am trying to prepare an Acoustic Model (AM) + Language Model (LM) pair for Hindi Speech / Devnagari Transcript data with SequenceToSequence TDS architecture. Without LM we do get some satisfactory results but we want to do better.  So we prepared a LM with about 6.8GB of filtered hindi corpus to which we also add the training and dev transcripts. However, this is a word based 4-gram language model, which, when plugged with the AM, predicts blank sentences with WER=100%. 

[This issue](https://github.com/facebookresearch/wav2letter/issues/323) mentions that seq2seq models require LM to be token based instead of word based. 

I have two questions:
1. Why are we getting blank predictions from word based LM? Is there a work around? 
2. Is there some documentation on the creation of token based LM that fits my use case?

**Comment by tlikhomanenko** [comment]
Hi @mrinal-sourav,

Here is full documentation on the beam-search decoder https://github.com/facebookresearch/wav2letter/wiki/Beam-Search-Decoder. And we support now word-based and token-based LMs for seq2seq beam-search decoder. 

For the training token based LMs you can have a look at the recipe we did for English here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech.

Can you send your decoder command, so I can help with correct setting of flags to run it with 4gram word-based LM?

**Comment by mrinal-sourav** [comment]
decoder.cfg looks like this: 
--lmtype=kenlm
--lm=/home/devnagri_lm.binary
--am=/home/training/quiet_10lakh_model_1/005_model_#lists#dev.lst.bin
--test=lists/test.lst
--sclite=/home/test_results
--decodertype=tkn
--lmweight=1.0
--wordscore=2.0
--beamsize=70
--beamthreshold=7
#--silweight=-0.5
--hardselection=1.5
--softselection=10.0
--attentionthreshold=30
--nthread_decoder=4
--smearing=max
--show=true

**Comment by tlikhomanenko** [comment]
Try this configuration:
```
--lmtype=kenlm
--lm=/home/devnagri_lm.binary
--am=/home/training/quiet_10lakh_model_1/005_model_#lists#dev.lst.bin
--test=lists/test.lst
--sclite=/home/test_results
--decodertype=wrd
--uselexicon=true
--beamsize=50
--beamsizetoken=10
--lmweight=1.0
--wordscore=2.0
--beamthreshold=10
--attentionthreshold=30
--smoothingtemperature=1
--nthread_decoder=1
--show
--showletters
--lmweight=1.0
--eosscore=-5
```

Parameters to optimize here for you are `lmweight` and `eosscore` (try to use it in range [-10, 0]). `nthread_decoder` you can set 4 if you have 4 GPUs. This will run word-based LM decoding.

**Comment by mrinal-sourav** [comment]
That helped!
Only issue I see now is the the predictions are single characters separated by space like so: 
|T|: रहने दो क्या करना है हमने आजकल सब के अपने विचार हैं अपने
|P|: 
|t|: र ह न े _ द ो _ क ् य ा _ क र न ा _ ह ै _ ह म न े _ आ ज क ल _ स ब _ क े _ अ प न े _ व ि च ा र _ ह ै ं _ अ प न े
|p|: 
[sample: ce3d588a-524c-460f-a24f-1a138264e81f.wav, WER: 100%, LER: 100%, slice WER: 100%, slice LER: 100%, progress (slice 0): 0.00495123%]
|T|: प्रीवियस
|P|: 
|t|: प ् र ी व ि य स
|p|: 
[sample: ab45eb2e-b17c-4fe7-b4c7-8d9002c886ae.wav, WER: 100%, LER: 100%, slice WER: 100%, slice LER: 100%, progress (slice 0): 0.00990246%]
|T|: कहा अभी की है
|P|: 
|t|: क ह ा _ अ भ ी _ क ी _ ह ै
|p|: 
[sample: d0242a4d-b1c3-473f-b65d-80734605e0e6.wav, WER: 100%, LER: 100%, slice WER: 100%, slice LER: 100%, progress (slice 0): 0.0148537%]
|T|: सब ठीक होगा
|P|: 
|t|: स ब _ ठ ी क _ ह ो ग ा
|p|: 

So wer/cer reported here does not exactly reflect the difference from ground truths. Perhaps a simple post-processing script will amend that. 

Thanks a lot for the response.

**Comment by tlikhomanenko** [comment]
No, it still doesn't work for you.

|T| - means target in words
|P| - predictions with words
|t| - target in letters
|p| - prediction in letters

So the numbers are correct, and you still have empty output

**Comment by mrinal-sourav** [comment]
Wups, my bad. Interesting. 
So tweaking those parameters will help?

**Comment by tlikhomanenko** [comment]
Not sure, maybe problem somewhere else. Can you send the full log before first sample is written on the screen?

**Comment by mrinal-sourav** [comment]
So I ran a test with maxload=10. The resulting file is [here](https://drive.google.com/file/d/1AYtf1qWDitf2yPL80Jc_BP28_gJRod-H/view?usp=sharing). 

The train configuration is [here](https://drive.google.com/file/d/1_TUnlwi0vEm2MBkl4nhL45pvn_cDrilF/view?usp=sharing)

I also tried with lm_weight=0, and I do get outputs (probably only from am) for like 5% of the records. I switched to the .arpa with which I created the LM binary; same behaviour.

**Comment by tlikhomanenko** [comment]
In the log file it should be printed also the flags, I want to see them (all the settings what will be used).

Could you try to run with `attentionthreshold=10000000`?

**Comment by mrinal-sourav** [comment]
So, I ran with attentionthreshold=10,000,000. 
The results are [here](https://drive.google.com/file/d/1AYtf1qWDitf2yPL80Jc_BP28_gJRod-H/view?usp=sharing). 
The flags for the above results are [here](https://drive.google.com/file/d/19mIjuzUQx45Qp21Io1nrpfDXXvynFtkY/view?usp=sharing). 

For comparison, I tested using the test command **without language model** with [these](https://drive.google.com/file/d/1ajvgKVLlbv4z5vW12dJygTc54IsU669s/view?usp=sharing) flags. I get [these](https://drive.google.com/file/d/16H6dMeHw_ra2ToJeCcjR1gGDYfowjJEQ/view?usp=sharing) results.

**Comment by tlikhomanenko** [comment]
Ok, you need to tune now `attentionthreshold` and `lm_weight` and `eosscore`. In case of seq2seq training depending on how attention is leant inside a model `attentionthreshold` should be set during decoding. Seems in your case the attention is using more context for prediction and restricting its context during decoding by `attentionthreshold=30` is too hard. In our practice we noticed that for some models one should use very large `attentionthreshold` during decoding otherwise it is empty output.

**Comment by mrinal-sourav** [comment]
Thanks for all the help. 
I will check and probably use emissions to get the right parameters here.

**Comment by mrinal-sourav** [comment]
Just to give me some starting point, could you please give me a wide/approximate **range** of parameter values I should try for  attentionthreshold, lm_weight, and eosscore for my case? 
Since I am a complete noob here, it is hard for me to understand what effect these parameters have on LM performance. Alternatively, some documentation/guide on this would be really helpful. Thanks again.

**Comment by tlikhomanenko** [comment]
Try `lm_weight` in range (0, 3), `eosscore` in (-10, 0). But before find the `attentionthreshold` by setting `lm_weight=0` and `eosscore=0` so that it gives non-empty output: try 100, 10^3, 10^5. If only 10,000,000 is working just use it and search other two parameters with random search.

**Comment by tlikhomanenko** [comment]
Closing for now, feel free to reopen!
