### ISSUE TITLE
Audio file format for inference examples

### ISSUE THREAD

**Issue by realbaker1967** [facebookresearch/wav2letter#615]
Hi, 

I am  trying to use your pre-trained models for benchmarking using my own audio files. 

My question is that what should be the audio format (for instace 16bit PCM or 32bit Float), sampling rate (I guess sampling rate should be 16k) etc for running **simple_streaming_asr_example**? 

Should I assume that audio file format should be **wav** by looking at [here](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-librispeech-audio-samples-from-openslrorg)? 

I would like to know exact format so that I can convert my files as well. 

Thank you!

**Comment by ericruleman** [comment]
"Also make sure your audio is in the right format. 16-bit 16khz mono" from https://github.com/facebookresearch/wav2letter/issues/564#issuecomment-593134763

This should be added to the tutorial!

**Comment by realbaker1967** [comment]
So all in all, the input audio file should be: 16 bit PCM, mono, 16khz WAV file, is that right?

**Comment by ericruleman** [comment]
Yes.
