### ISSUE TITLE
Problems with streaming TDS model conversion

### ISSUE THREAD

**Issue by vuongvantinh** [facebookresearch/wav2letter#619]
After building `streaming_tds_model_converter`, I ran the binary to my own trained tds_ctc model:
`tools/streaming_tds_model_converter -am /home/001_model_last.bin --outdir /home/output/`

Unfortunately, I got an error: 
`train_am_tds_ctc.cfg: No such file or directory`

I don't know why `train_am_tds_ctc.cfg` is required here. Could you give me any suggestion?

**Comment by lunixbochs** [comment]
You need to put the arch file in your current directory, or otherwise specify the path to the arch file during tds conversion.
