### ISSUE TITLE
saving emissions - slow decoding

### ISSUE THREAD

**Issue by jojo05** [facebookresearch/wav2letter#62]
In #29, it was mentioned that transcribing on CPU should be 1sec per sentence but no ideas on how to debug when decoding is slow (minutes per sentence). Has anybody discovered the cause of slow decoding ?
 
From #29, 
"It can't be 6 days, something must be wrong with your system. In my experience transcribing on CPU should take 1s per sequence, not 3 mins."

[Viterbi: reallocating with T=2000 N=30]
<|mister|quilter|is|the|apostle|of|the|mid1le|clas1es|and|we|are|glad|to|welcome|his|gospel|>
<|mister|quilter|is|the|apostle|of|the|mid1le|clas1es|and|we|are|glad|to|welcome|his|gospel|>
[Sentence WER: 000.00%, dataset WER: 000.00%]
<|nor|is|mister|qulter's|man1er|les1|interesting|than|his|mat1er|>......................]  ETA: 0ms | Step: 0ms         
<|nor|is|mister|quilter's|man1er|les1|interesting|than|his|mat1er|>
[Sentence WER: 010.00%, dataset WER: 003.70%]
<|he|tel1s|us|that|at|this|festive|season|of|the|year|with|christmas|and|roast|be1f|loving|before|us|similes|drawn|from|eating|and|its|results|ocur|most|readily|to|the|mind|>
<|he|tel1s|us|that|at|this|festive|season|of|the|year|with|christmas|and|roast|be1f|lo1ming|before|us|similes|drawn|from|eating|and|its|results|oc1ur|most|readily|to|the|mind|>
[Sentence WER: 006.25%, dataset WER: 005.08%]
<|it|is|obviously|un1eces1ary|for|us|to|point|out|how|luminous|these|criticisms|are|how|delicate|in|expres1ion|>5s      
<|it|is|obviously|un1eces1ary|for|us|to|point|out|how|luminous|these|criticisms|are|how|delicate|in|expres1ion|>
[Sentence WER: 000.00%, dataset WER: 003.90%]
 [........................................ 4/2703 ......................................]  ETA: 6D11h | Step: 3m27s

**Comment by vineelpratap** [comment]
Can you let us know the command you are using

**Comment by jojo05** [comment]
thanks

below:
- command used
- details of model dir and  librispeech-proc dir (dictdir / datadir)
- initial output (slightly different from previous one)
 
D=/home/ml/asr/librispeech-proc/
luajit wav2letter/test.lua /home/ml/asr/librispeech-glu-highdropout-cpu.bin -progress -show -test dev-clean -save -dictdir $D -datadir $D -gfsai

---

[root@i asr]# ll /home/ml/asr
total 1631800
-rwxr--r--. 1 joe  joe         317 Mar  5 13:08 dl-model.sh
-rwxr--r--. 1 joe  joe         185 Mar  5 12:05 dl.sh
drwxr-xr-x. 9 root root       4096 Mar  5 13:39 LibriSpeech
-rw-r--r--. 1 root root 1670805187 Jan 11 06:59 librispeech-glu-highdropout-cpu.bin
drwxr-xr-x. 9 root root       4096 Mar  6 09:59 librispeech-proc
-rw-r--r--. 1 root root     126976 Mar  6 10:17 output-dev-clean.bin
-rw-r--r--. 1 root root       3725 Mar  6 10:13 transitions-dev-clean.bin

[root@i asr]# ll /home/ml/asr/librispeech-proc
total 157312
-rw-r--r--. 1 root root 38757477 Mar  5 16:16 3-gram.pruned.3e-7.arpa
-rw-r--r--. 1 root root 37458439 Mar  4 22:02 3-gram.pruned.3e-7.bin
drwxr-xr-x. 2 root root   765952 Mar  5 16:54 dev-clean
drwxr-xr-x. 2 root root   831488 Mar  5 16:54 dev-other
-rw-r--r--. 1 root root  3475117 Mar  5 16:16 dict.lst
-rw-r--r--. 1 root root       56 Mar  5 14:56 letters.lst
-rw-r--r--. 1 root root       60 Mar  5 16:13 letters-rep.lst
drwxr-xr-x. 2 root root   745472 Mar  5 16:54 test-clean
drwxr-xr-x. 2 root root   856064 Mar  5 16:55 test-other
drwxr-xr-x. 2 root root  7979008 Mar  5 16:28 train-clean-100
drwxr-xr-x. 2 root root 29356032 Mar  5 16:40 train-clean-360
drwxr-xr-x. 2 root root 40824832 Mar  5 16:54 train-other-500

---
[Viterbi: reallocating with T=2000 N=30]
<|nor|is|mister|qulter's|man1er|les1|interesting|than|his|mat1er|>
<|nor|is|mister|quilter's|man1er|les1|interesting|than|his|mat1er|>
[Sentence WER: 010.00%, dataset WER: 010.00%]
<|mister|quilter|is|the|apostle|of|the|mid1le|clas1es|and|we|are|glad|to|welcome|his|gospel|>A: 0ms | Step: 0ms         
<|mister|quilter|is|the|apostle|of|the|mid1le|clas1es|and|we|are|glad|to|welcome|his|gospel|>
[Sentence WER: 000.00%, dataset WER: 003.70%]
 [........................................ 2/2703 ......................................]  ETA: 4D12h | Step: 2m24s

**Comment by jojo05** [comment]
Is anybody running the CPU model with 1s decodings ?

**Comment by vineelpratap** [comment]
Hi,
  I tried to verify again and it takes around 1sec for me for each step (I made sure GPU is disabled for the process). 
<img width="839" alt="screen shot 2018-03-07 at 2 10 07 pm" src="https://user-images.githubusercontent.com/5282102/37122473-898b9ae8-2215-11e8-9b57-6f1b567dc878.png">

Can you remove `-save` option and see if there is a significant change in time. I wonder if it is disk reading/writing is taking the time. 
Otherwise, one would have to some benchmarking and see which step is taking most time in https://github.com/facebookresearch/wav2letter/blob/master/test.lua.

**Comment by jojo05** [comment]
If the code is doing random seeks to file, then the difference between SSD and disk would explain the slow decoding

**Comment by vineelpratap** [comment]
Hi, 
 While I'm using SSD, I'm not 100% sure if this could cause such a huge regression. We use [ParallelDatasetIterator](https://github.com/torchnet/torchnet/blob/master/dataset/paralleldatasetiterator.lua) which should make preprocessing time almost zero. 

It may be best to benchmark the code to see what's happening. I'm not able to repro this, can you follow these step to see which step is taking most time. 
1. Find where `sgdengine.lua ` file is in your machine. It comes with torchnet package.  
```find ~/usr/share/ -name '*sgdengine*'```
2. Find the time taken for each step in https://github.com/torchnet/torchnet/blob/master/engine/sgdengine.lua#L170-L185 . 
3. If none of the hooks take significant amount of time, then it is most likely file reading which is causing regression.

**Comment by vineelpratap** [comment]
Hi, I'm not able to repro this on my machine.
Are you using intel MKL - https://github.com/facebookresearch/wav2letter#mkl . It could also make a huge difference (esp. for running convolutions and matrix multiplications in the network) while doing inference.

**Comment by grahamimac** [comment]
Ah, it turns out MKL was not installed and it does not seem like there was any default BLAS like openBLAS as well, given it was a clean Ubuntu docker container. I have updated my setup code on the Github link above - given it takes a few hours to build then test, I'll aim to test sometime when I have a bit more time and report the results. Thanks!

**Comment by vineelpratap** [comment]
@grahamimac Good to know it worked for you !  I have used the same command you mentioned for my initial benchmark. As you mentioned the network forward time is the bottleneck, please make sure you are running latest version of torch nn package (if you are not using already).
