### ISSUE TITLE
conv_glu training too slow?

### ISSUE THREAD

**Issue by luweishuang** [facebookresearch/wav2letter#621]
I use the lastest commit in facebook/wav2letter and run conv_glu training in wsj, I run on tesla P40 and set --reportiters=1, it shows
 `I0426 16:01:36.220798 55324 Train.cpp:342] epoch:        1 | nupdates:            1 | lr: 0.000125 | lrcriterion: 0.000001 | runtime: 00:00:59 | bch(ms): 59827.42 | smp(ms): 255.37 | fwd(ms): 15297.56 | crit-fwd(ms): 13415.74 | bwd(ms): 39754.97 | optim(ms): 1085.46 | loss:   65.30235 | train-TER: 100.00 | train-WER: 100.00 | wav_lists/dev.lst-small-loss:   85.67764 | wav_lists/dev.lst-small-TER: 100.00 | wav_lists/dev.lst-small-WER: 100.00 | avg-isz: 393 | avg-tsz: 017 | max-tsz: 017 | hrs:    0.03 | thrpt(sec/sec): 2.10`,  
it's first epoch only has servel iter and the second iter has many many iters and last more than 24 hours , any wrong with it?
[network.arch.txt](https://github.com/facebookresearch/wav2letter/files/4534888/network.arch.txt)
[wav_train.cfg.txt](https://github.com/facebookresearch/wav2letter/files/4534891/wav_train.cfg.txt)

**Comment by luweishuang** [comment]
it's seems --criterion=asg   and  --linseg=1 lead to slow training

**Comment by vineelpratap** [comment]
Hi, what is the token set size for training ? Note that ASG scales O(N^2) where N is the size of token set. Also, batchsize of 32 on 200Mil param model is probably too high for Tesla P40. You can try reducing batch size or use P100s, V100s.
