### ISSUE TITLE
How can I load CUDA-trained model on a computer without it?

### ISSUE THREAD

**Issue by ivodopyanov** [facebookresearch/wav2letter#63]
Hello

I've trained model with option -gpu 1 and trying to test it on another computer without GPU, calling
`~/usr/bin/luajit ~/wav2letter/test.lua ~/wav2letter/experiments/sphinx/001_model_dev-clean.bin -progress -show -test <test_folder> -save -gpu 0 -datadir <new datadir> -dictdir <new dictdir>
`

But I get error 
`~/usr/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>`
whole error stack:
`~/usr/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	~/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	~/usr/share/lua/5.1/nn/Module.lua:192: in function 'read'
	~/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	~/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	~/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	~/usr/share/lua/5.1/nn/Module.lua:192: in function 'read'
	~/usr/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	~/usr/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	~/usr/share/lua/5.1/wav2letter/runtime/serial.lua:57: in function 'loadmodel'
	~/wav2letter/test.lua:102: in main chunk
`

even though I've specified '-gpu 0' flag.

What should I do to be able to load this model properly?

Thanks.

**Comment by vineelpratap** [comment]
Hi,
 You might have to write a small script to do this. Once you load the model on a GPU 
```
local model = serial.loadmodel{filename=reload, arch=true} --
 https://github.com/facebookresearch/wav2letter/blob/master/test.lua#L102
local network = model.arch.network
local transitions = model.arch.transitions
local config = model.config
```
`network` has the information about the GPU neural network. You would have to create a new object `cpunetwork` (which works on CPU) with the same architecture and weights. You can find many reference online about this. Once this is done, save the cpu model using syntax -  
```
serial.savemodel{
      filename = <outputfilename>.bin,
      config = config,
      arch = {
         network = <CPU network created>,
         transitions = transitions
      }
   }
```

Let me know if you if it works. Thanks !

**Comment by ivodopyanov** [comment]
I hoped for a way to solve it without editing saved model, but I guess that will do to. Thanks.
