### ISSUE TITLE
feature extraction python binding error

### ISSUE THREAD

**Issue by dtchantao** [facebookresearch/wav2letter#636]
Hi there

Error occurs when using example to load 'wav' file: 
with open("test.wav") as f:
    wavinput = [float(x) for x in it.chain.from_iterable(line.split() for line in f)]

Error message:
'utf-8' codec can't decode byte 0x80 in position24: invalid start byte

Anyone can help with it?

Thank you very much!

**Comment by davidbelle** [comment]
Try

`open("test.wav",rb")`

**Comment by tlikhomanenko** [comment]
@dtchantao feel free to reopen if error still exist.
