### ISSUE TITLE
"training finished" without early stopping flag?

### ISSUE THREAD

**Issue by AVSuni** [facebookresearch/wav2letter#637]
I'm trying to understand why my training finishes after 16 epochs. I can't see any early stopping flag (i.e. "iter") in my flags file (below). Any thoughts?

--runname=streaming_convs_swe_2019_pretrained
--rundir=/data_local/w2l_streaming_convs_swe
--tokensdir=/data_local/w2l_streaming_convs_swe/model/am
--archdir=/data_local/w2l_streaming_convs_swe
--train=/data_local/w2l_streaming_convs_swe/train.lst
--valid=dev-clean:/data_local/w2l_streaming_convs_swe/val.lst
--lexicon=model/am/swedish-train+dev-unigram-10000-nbest10.lexicon
--arch=am_500ms_future_context.arch
--tokens=swedish-train-all-unigram-10000.tokens
--criterion=ctc
--input=wav
--batchsize=6
--lr=0.03
--momentum=0.0
--maxgradnorm=0.5
--reportiters=1000
--nthread=6
--mfsc=true
--usewordpiece=true
--wordseparator=_
--filterbanks=80
--minisz=0
--mintsz=0
--maxisz=1000000000
--maxtsz=1000000000
--enable_distributed=true
--pcttraineval=1
--minloglevel=0
--logtostderr
--onorm=target
--sqnorm
--localnrmlleftctx=300
--stepsize=2000000
--gamma=0.5

**Comment by tlikhomanenko** [comment]
Hi @AVSuni,

Could you post here full your log? Do you have loss NaN at the end?

**Comment by AVSuni** [comment]
Thanks @tlikhomanenko. I'm afraid I overwrote the log file when forking the previous training. Another problem I encountered was that "continue" led to starting from a random epoch number (e.g. around half of where I left off) with a much high WER. Only forking starts from  the previous WER.

**Comment by tlikhomanenko** [comment]
The continue mode will take that last `00*_model_last.bin` model you have in the directory while fork will use exactly file you specified in the run command. Could you share how you run continue and fork and what is the model directory when you run this?

**Comment by tlikhomanenko** [comment]
Closing due inactivity. Feel free to reopen!
