### ISSUE TITLE
parallel run

### ISSUE THREAD

**Issue by KellyZhao960510** [facebookresearch/wav2letter#638]
when I try to parallel run model, should I set batch_size=4 or batch_size=4*number of gpu,
I experiment to set batch_size=16 when I use 4 gpus to train model, but got 'device out of memory' error

**Comment by tlikhomanenko** [comment]
Hey @KellyZhao960510,

Batch size parameter is the batch per GPU, so if you specify `batchsize=4` this means that each GPU will process 4 samples.
