### ISSUE TITLE
Module 'samplerate' not found

### ISSUE THREAD

**Issue by ivodopyanov** [facebookresearch/wav2letter#64]
Hello

Model training goes without errors but when I try to test it I get this error
`/usr/local/share/lua/5.1/wav2letter/readers.lua:26: module 'samplerate' not found`

How can I get that module?
Currently I'm solving that problem by commenting out lines 25-29 in readers.lua

Thanks.

**Comment by vineelpratap** [comment]
Hi,
 `samplerate` module is used for both train and test. Is the testing done on the same machine ? If it is a different machine, can you make sure you have followed all the installation steps (specifically https://github.com/facebookresearch/wav2letter#wav2letter-packages)

**Comment by ivodopyanov** [comment]
No, testing was conducted on the same machine. Error does not arise during training.


Whole error stack trace:

luajit: /usr/local/share/lua/5.1/threads/threads.lua:183: [thread 6 callback] /usr/local/share/lua/5.1/wav2letter/readers.lua:26: module 'samplerate' not found:
	no field package.preload['samplerate']
	no file './samplerate.lua'
	no file '/usr/local/share/luajit-2.0.4/samplerate.lua'
	no file '/usr/local/share/lua/5.1/samplerate.lua'
	no file '/usr/local/share/lua/5.1/samplerate/init.lua'
	no file './samplerate.so'
	no file '/usr/local/lib/lua/5.1/samplerate.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/wav2letter/readers.lua:26: in function 'reader'
	.../local/share/lua/5.1/wav2letter/numberedfilesdataset.lua:112: in function 'get'
	...ocal/share/lua/5.1/torchnet/dataset/transformdataset.lua:112: in function 'get'
	...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:110: in function <...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:109>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	/usr/local/share/lua/5.1/threads/queue.lua:65: in function </usr/local/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:181: in function '(for generator)'
	/usr/local/share/lua/5.1/torchnet/engine/sgdengine.lua:172: in function 'test'
	/home/ubuntu/wav2letter/test.lua:269: in function 'test'
	/home/ubuntu/wav2letter/test.lua:280: in main chunk
	[C]: at 0x00404ab0

**Comment by vineelpratap** [comment]
Hi, I have checked the code again. You shouldn't be needing `samplerate` package as you can from see [here](https://github.com/facebookresearch/wav2letter/blob/7491ec4a697e00dcc1db7f869568e9a58a9396a1/wav2letter/readers.lua#L25) it is conditioned in a `if` statement.  

1. Can you make sure, test and train set have the same sampling rate. 
2. If both your test and train set have a sampling rate which is not 16KHz, you can use this flag to change it - https://github.com/facebookresearch/wav2letter/blob/master/train.lua#L128

Since you mentioned that training goes on without any errors, I'm guessing it is mostly (1).

**Comment by ivodopyanov** [comment]
Yes, that's highly likely. I've tried testing model on completely different dataset. Thanks.
