### ISSUE TITLE
question about input audio file format

### ISSUE THREAD

**Issue by dtchantao** [facebookresearch/wav2letter#641]
Hi there 

I  noticed that most of the model in this repo are trained by FLAC audios. While for inference like python binding feature extraction use wav as input. Is there any misalignment between these two formats?

Thank you very much!

**Comment by deepspiking** [comment]
Both FLAC and WAV are lossless audio format, thus I belive there should be no difference or misalignment.

**Comment by vineelpratap** [comment]
Hi, for training and python feature extraction, we support both .wav and .flac formats.
