### ISSUE TITLE
Using pre-built Docker images Issues

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#642]
By https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker, 

(1) I did:

sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-latest

and got:

docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.

BTW, I just have 1 GPU. Does it bother?

(2) However,

sudo docker run --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cpu-latest

produces

2239212117f1860845c0cccee7af9cb95514c6e9b8c2fb2009fc23b7c0cd2079

Then, for

sudo docker exec -it w2l bash
cd /root/wav2letter/build && make test

I got all 22 tests failed:

root@17e15666b1ef:/# cd /root/wav2letter/build && make test
Running tests...
...

Errors while running CTest
Makefile:72: recipe for target 'test' failed
make: *** [test] Error 8

In addition, more info can be found at https://github.com/NVIDIA/nvidia-docker/issues/1264#issuecomment-626212131.

Any comments about these issues? Thank you!

**Comment by ML6634** [comment]
For

cd /root/wav2letter/build && ./src/tests/W2lCommonTest

it produces:

./src/tests/W2lCommonTest: error while loading shared libraries: libmkl_rt.so: cannot open shared object file: No such file or directory

**Comment by ML6634** [comment]
When I run

locate libmkl_rt.so

it has no output.

**Comment by ML6634** [comment]
For (2), before 

sudo docker exec -it w2l bash

do I need to run the following command?

sudo docker run --rm -itd –ipc=host \
    --volume original/path/on/your/machine:mounted/path/in/the/container 
    --name w2l wav2letter/wav2letter:cuda-latest

However, the above command produces:

docker: invalid reference format.
See 'docker run --help'.

**Comment by ML6634** [comment]
For (2), right before 

sudo docker exec -it w2l bash

do I need to run the following command?

sudo docker run --rm -itd --ipc=host \  
    --volume original/path/on/your/machine:mounted/path/in/the/container 
    --name w2l wav2letter/wav2letter:cuda-latest

However, the above command produces:

docker: invalid reference format.
See 'docker run --help'.

**Comment by ML6634** [comment]
I have installed Install Docker. For using CUDA backend, nvidia-docker has also been installed:

the output for

sudo docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

is:

![image](https://user-images.githubusercontent.com/61134984/81441538-8e9b6980-9137-11ea-9d50-3bb31386a12c.png)

However, to go with CPU backend, do I need to install any other packages? 

Could any experts look at these issues please? Thank you!

**Comment by ML6634** [comment]
@tlikhomanenko @vineelpratap 

I have installed Install Docker. For using CUDA backend, nvidia-docker has also been installed:

the output for

sudo docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

is:

![image](https://user-images.githubusercontent.com/61134984/81462939-8ebd5880-917b-11ea-8628-01fbdb269bd0.png)

However, to go with CPU backend, do I need to install any other packages?

Could any experts look at these issues, please? Thank you!

**Comment by tlikhomanenko** [comment]
Hi @ML6634,

Sorry for the delay.
1) It doesn't matter how maby GPUs you have (1 or 8) it will work with the number you have.
2) To have docker working with GPU you need to install nvidia-docker so that `--runtime=nvidia` option will be available and during container running devices will be available for the container. If you run without `--runtime=nvidia` you have no access to GPUs. (This info is provided on https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker as `Install Docker and, if using the CUDA backend, nvidia-docker` with the links of their installation steps)
3) About tests in the CPU docker: There is a note here https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker that you need to do export before running the tests and all your work (this is because of mkl):
```
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_IBRARY_PATH
```
4) To run docker CPU backend you need only docker, no need for nvidia-docker
5) `--volume original/path/on/your/machine:mounted/path/in/the/container` this params just doing the mounting of your directory to the docker container so that everything in it will be saved on your dick even when you kill the container (all docker container file system is separate and will be deleted as container stops/removed).

Hope, this answers all your questions. Feel free to check docker manual on additional parameters (this is just helps you to operate with container, like adding users, groups, mounting, etc.)

**Comment by ML6634** [comment]
@tlikhomanenko

Thank you very much for the helpful comment!! 

I did both 2. and 3. in your message but not 5. So, anybody has a clue regarding how to take of issues (1) and (2) in my posting at the top? 

For an issue similar to (1), at https://github.com/NVIDIA/nvidia-docker/issues/951, and https://github.com/NVIDIA/nvidia-docker/issues/686, reinstalling docker and nvidia-docker was suggested. However, my docker and nvidia-docker were just installed. Reinstalling might not make things different.

**Comment by ML6634** [comment]
I installed nvidia-docker2:

<pre>$ sudo apt-get install -y nvidia-docker2
</pre>

and it has taken care of (1) and (2) nicely:

<pre>sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-latest
Unable to find image &apos;wav2letter/wav2letter:cuda-latest&apos; locally
cuda-latest: Pulling from wav2letter/wav2letter
7ddbc47eeb70: Already exists 
c1bbdc448b72: Already exists 
8c3b70e39044: Already exists 
45d437916d57: Already exists 
d8f1569ddae6: Already exists 
de5a2c57c41d: Already exists 
ea6f04a00543: Already exists 
7b872974e97c: Pull complete 
ba8a751eb7d9: Pull complete 
c23d51d23979: Pull complete 
c13ab06c6a37: Pull complete 
105e06abd348: Pull complete 
429351dfb5bc: Pull complete 
f90527b184b3: Pull complete 
ce24bdb48845: Pull complete 
Digest: sha256:a0eb0ae78c857813034fbb369bd527997f6d624661f2e617075b5da1ab25fab4
Status: Downloaded newer image for wav2letter/wav2letter:cuda-latest
4f82a06f80480d14a5026c66712896fe0a2ac33a50d7afe32e857d263a037746
</pre>

<pre># cd /root/wav2letter/build &amp;&amp; make test
<font color="#06989A">Running tests...</font>
Test project /root/wav2letter/build
      Start  1: W2lCommonTest
 1/31 Test  #1: W2lCommonTest ....................   Passed    4.08 sec
      Start  2: DictionaryTest
 2/31 Test  #2: DictionaryTest ...................   Passed    0.13 sec
      Start  3: ProducerConsumerQueueTest
 3/31 Test  #3: ProducerConsumerQueueTest ........   Passed    0.14 sec
      Start  4: CriterionTest
 4/31 Test  #4: CriterionTest ....................   Passed   11.42 sec
      Start  5: Seq2SeqTest
 5/31 Test  #5: Seq2SeqTest ......................   Passed   10.02 sec
      Start  6: AttentionTest
 6/31 Test  #6: AttentionTest ....................   Passed    3.18 sec
      Start  7: WindowTest
 7/31 Test  #7: WindowTest .......................   Passed    3.21 sec
      Start  8: DataTest
 8/31 Test  #8: DataTest .........................   Passed    0.88 sec
      Start  9: ListFileDatasetTest
 9/31 Test  #9: ListFileDatasetTest ..............   Passed    0.36 sec
      Start 10: SoundTest
10/31 Test #10: SoundTest ........................   Passed    0.15 sec
      Start 11: DecoderTest
11/31 Test #11: DecoderTest ......................   Passed    1.16 sec
      Start 12: CeplifterTest
12/31 Test #12: CeplifterTest ....................   Passed    0.15 sec
      Start 13: DctTest
13/31 Test #13: DctTest ..........................   Passed    0.15 sec
      Start 14: DerivativesTest
14/31 Test #14: DerivativesTest ..................   Passed    0.12 sec
      Start 15: DitherTest
15/31 Test #15: DitherTest .......................   Passed    8.16 sec
      Start 16: MfccTest
16/31 Test #16: MfccTest .........................   Passed    0.58 sec
      Start 17: PreEmphasisTest
17/31 Test #17: PreEmphasisTest ..................   Passed    0.18 sec
      Start 18: SpeechUtilsTest
18/31 Test #18: SpeechUtilsTest ..................   Passed    0.73 sec
      Start 19: TriFilterbankTest
19/31 Test #19: TriFilterbankTest ................   Passed    0.11 sec
      Start 20: WindowingTest
20/31 Test #20: WindowingTest ....................   Passed    0.14 sec
      Start 21: W2lModuleTest
21/31 Test #21: W2lModuleTest ....................   Passed    2.70 sec
      Start 22: RuntimeTest
22/31 Test #22: RuntimeTest ......................   Passed    1.20 sec
      Start 23: inference_Conv1dTest
23/31 Test #23: inference_Conv1dTest .............   Passed    0.02 sec
      Start 24: inference_IdentityTest
24/31 Test #24: inference_IdentityTest ...........   Passed    0.01 sec
      Start 25: inference_LayerNormTest
25/31 Test #25: inference_LayerNormTest ..........   Passed    0.01 sec
      Start 26: inference_LinearTest
26/31 Test #26: inference_LinearTest .............   Passed    0.01 sec
      Start 27: inference_LogMelFeatureTest
27/31 Test #27: inference_LogMelFeatureTest ......   Passed    0.03 sec
      Start 28: inference_MemoryManagerTest
28/31 Test #28: inference_MemoryManagerTest ......   Passed    0.00 sec
      Start 29: inference_ReluTest
29/31 Test #29: inference_ReluTest ...............   Passed    0.00 sec
      Start 30: inference_ResidualTest
30/31 Test #30: inference_ResidualTest ...........   Passed    0.00 sec
      Start 31: inference_TDSBlockTest
31/31 Test #31: inference_TDSBlockTest ...........   Passed    0.00 sec

100% tests passed, 0 tests failed out of 31

Total Test time (real) =  49.06 sec
</pre>

Regarding  --volume original/path/on/your/machine:mounted/path/in/the/container, may I have more details regarding which path it is, or how to find it? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634,

Your (2) issue is not related to the nvidia-docker if you are running CPU docker.

About `--volume`: if say I have path `/home/antares/experiments` on my machine and want to see this path from the docker container then I do `--volume /home/antares/experiments:/root/experiments` which means that inside docker container I will have path `/root/experiments` where my original path is mounted (this is like disks mounting in linux). 

Docker docs on this https://docs.docker.com/storage/volumes/

**Comment by ML6634** [comment]
Yes, you are right! 

After (1) went through, commands: 

sudo docker exec -it w2l bash
cd /root/wav2letter/build && make test

in (2) also went through, with all 31 test passed, for CUDA backend. I did delete the container created for CPU backend, since I do not think that one can go with both backends at the same time. Thank you again for your help!
