### ISSUE TITLE
Online decoding with lexicon free setting

### ISSUE THREAD

**Issue by deepspiking** [facebookresearch/wav2letter#644]
I'm trying to mix up 
Pratap et al. (2020): **Scaling Online Speech Recognition Using ConvNets**
and 
Likhomanenko et al. (2019): Who Needs Words? **Lexicon-free Speech Recognition**

The problem is, in the lexicon-free manner, they are using the fairseq LM, and this is not suitable for online speech recognition manner.

Is there any way to use "simple_streaming_asr_example" with fairseq LM?

**Comment by tlikhomanenko** [comment]
Hi @deepspiking,

In lexicon-free we are using both fairseq models (for NN-based LMs, which are not very efficient for online setting if you need very good speed in decoding) and ngram. So ngram (20-gram char LMs)  model you can use with streaming ASR. Just remember your acoustic model should be char based too here (LM operates either on words or the same tokens on which ASR is trained).

**Comment by deepspiking** [comment]
Thanks for your reply! Though I was finding the way to utilize Conv LM trained on fairseq.
I think I should implement by myself. 
Thanks anyway!
