### ISSUE TITLE
streaming_tds_model_converter error  

### ISSUE THREAD

**Issue by bjl21012** [facebookresearch/wav2letter#646]
after Train model with network.arch and test，
 I try to General feature_extractor.bin by streaming_tds_model_converter , terminate called after throwing an instance of 'std::invalid_argument'
command :
 /root/wav2letter/build/tools/streaming_tds_model_converter  -am /home/bjl/data/data_aishell/aishelltrainlogs/001_model_last.bin  --outdir ./ 
output ：
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
*** Aborted at 1588934677 (unix time) try "date -d @1588934677" if you are using GNU date ***
PC: @     0x7fc2bd67ee97 gsignal
*** SIGABRT (@0x4498) received by PID 17560 (TID 0x7fc302b4e3c0) from PID 17560; stack trace: ***
    @     0x7fc2c537c890 (unknown)
    @     0x7fc2bd67ee97 gsignal
    @     0x7fc2bd680801 abort
    @     0x7fc2be073957 (unknown)
    @     0x7fc2be079ab6 (unknown)
    @     0x7fc2be079af1 std::terminate()
    @     0x7fc2be079d24 __cxa_throw
    @     0x7fc2be0757e3 (unknown)
    @     0x561416a36db3 _ZN9__gnu_cxx6__stoaIlicJiEEET0_PFT_PKT1_PPS3_DpT2_EPKcS5_PmS9_.constprop.24545
    @     0x5614169cc839 main
    @     0x7fc2bd661b97 __libc_start_main
    @     0x561416a364ba _start
Aborted (core dumped)
Is there problem with the command ？ Thank you!

**Comment by vineelpratap** [comment]
Hi, could you provide the arch file you are using. Also, if you can `gdb backtrace`, it would help us debug easily.

**Comment by bjl21012** [comment]
> Hi, could you provide the arch file you are using. Also, if you can `gdb backtrace`, it would help us debug easily.

i use network.arch 
# 8 Temporal Convolutions followed by 2 Linear layers with ReLU activations.
# First Conv layer has stride of 2. All Conv layers perform "SAME" padding.
V -1 1 NFEAT 0
C2 NFEAT 256 8 1 2 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
C2 256 256 8 1 1 1 -1 -1
R
RO 2 0 3 1
L 256 512
R
L 512 NLABEL

**Comment by vineelpratap** [comment]
Hi,
 We support only TDS based modules for streaming inference at the moment. See https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/streaming_convnets for an example.

**Comment by bjl21012** [comment]
> Hi,
> We support only TDS based modules for streaming inference at the moment. See https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/streaming_convnets for an example.

Thanks
