### ISSUE TITLE
test-one-file.lua broken

### ISSUE THREAD

**Issue by lukeinator42** [facebookresearch/wav2letter#65]
Hi,

I am able to run test.lua, but it appears the test-one-file.lua script is broken. Is there a simple way to transcribe a single wav file?

Thanks,

**Comment by vineelpratap** [comment]
Hi, as mentioned in #37 test-one-file.lua is outdated. Currently there is no script which tests on a single way. The best way to keep your test data in the same format as librispeech test data in the same folder and run preprocessing script on it and then test using `test.lua` file. Also make sure you have followed all the steps in README for using the pre-trained model, the audio file has the same  sampling rate as librispeech(16 KHz) and the audio has only one channel.

**Comment by thomasquintana** [comment]
@vineelpratap would you guys take a pull request to fix this issue?

**Comment by thomasquintana** [comment]
https://github.com/facebookresearch/wav2letter/pull/72
