### ISSUE TITLE
The error: ModuleNotFoundError: No module named 'sox'

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#652]
From 

E2E Speech Recognition on Librispeech-Clean Dataset
https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean

I did:

<pre>$ pip install sox
Collecting sox
  Using cached https://files.pythonhosted.org/packages/60/a0/5bee540554af8376e0313e462629d95bf2f2bc3c8cb60697aa01254e6cf5/sox-1.3.7-py2.py3-none-any.whl
Installing collected packages: sox
Successfully installed sox-1.3.7
</pre>

Then:

<pre>$ python3.7 wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
Traceback (most recent call last):
  File &quot;wav2letter/tutorials/1-librispeech_clean/prepare_data.py&quot;, line 30, in &lt;module&gt;
    import sox
ModuleNotFoundError: No module named &apos;sox&apos;
Error in sys.excepthook:
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/apport_python_hook.py&quot;, line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File &quot;/usr/lib/python3/dist-packages/apport/__init__.py&quot;, line 5, in &lt;module&gt;
    from apport.report import Report
  File &quot;/usr/lib/python3/dist-packages/apport/report.py&quot;, line 30, in &lt;module&gt;
    import apport.fileutils
  File &quot;/usr/lib/python3/dist-packages/apport/fileutils.py&quot;, line 23, in &lt;module&gt;
    from apport.packaging_impl import impl as packaging
  File &quot;/usr/lib/python3/dist-packages/apport/packaging_impl.py&quot;, line 24, in &lt;module&gt;
    import apt
  File &quot;/usr/lib/python3/dist-packages/apt/__init__.py&quot;, line 23, in &lt;module&gt;
    import apt_pkg
ModuleNotFoundError: No module named &apos;apt_pkg&apos;

Original exception was:
Traceback (most recent call last):
  File &quot;wav2letter/tutorials/1-librispeech_clean/prepare_data.py&quot;, line 30, in &lt;module&gt;
    import sox
ModuleNotFoundError: No module named &apos;sox&apos;
</pre>

If I run it without having "python3.7" in the command, it is:

<pre>$ wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
bash: wav2letter/tutorials/1-librispeech_clean/prepare_data.py: Permission denied
</pre>

If I did exactly the same as the tutorial, it is:

<pre>$ wav2letter/tutorials/librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
bash: wav2letter/tutorials/librispeech_clean/prepare_data.py: No such file or directory
</pre>

May I ask how to take care the above issue? 

I assume that those listed in

Building Running with Docker
https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker

are all dependencies we need.

In addition, might a model like this be good for transcribing a telephony audio? Thank you!

**Comment by padentomasello** [comment]
Hi @ML6634, I think you may be installing sox for python2, but then using python3.7 to run the code. Can you try `pip3 install sox` and then rerun? 

> wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR. 

This is occurring because you are trying to run a python file in bash. You may want to try `python wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR`. 

Are you trying to run this within docker? If so, everything should already be installed: https://github.com/facebookresearch/wav2letter/blob/7ef9db1cc8d387b91a33d5aa1cb488c4f04e63cd/Dockerfile-CPU-Base#L36. Otherwise, you can follow those steps in order to get everything installed correctly.

**Comment by ML6634** [comment]
@padentomasello

Do I need to run this on Ubuntu, or a Docker container:

<pre>~/wav2letter/tutorials/1-librispeech_clean# 
</pre>?

Thank you!

**Comment by ML6634** [comment]
Thank @padentomasello for the response! Per the suggestion, I did:

<pre>$ pip3 install sox
Collecting sox
  Using cached https://files.pythonhosted.org/packages/60/a0/5bee540554af8376e0313e462629d95bf2f2bc3c8cb60697aa01254e6cf5/sox-1.3.7-py2.py3-none-any.whl
Installing collected packages: sox
Successfully installed sox-1.3.7
</pre>

Then, 

<pre>$ python wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
usage: prepare_data.py [-h] [--src SRC] [--dst DST]
prepare_data.py: error: argument --dst: expected one argument
</pre>

If, in the above command, I use <pre>python3 </pre>  instead, it outputs the same error message as the case when <pre>python</pre> is used.

However, 

<pre>$ wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
bash: wav2letter/tutorials/1-librispeech_clean/prepare_data.py: Permission denied
</pre>

<pre>$ python3.7 wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
Traceback (most recent call last):
  File &quot;wav2letter/tutorials/1-librispeech_clean/prepare_data.py&quot;, line 30, in &lt;module&gt;
    import sox
ModuleNotFoundError: No module named &apos;sox&apos;
Error in sys.excepthook:
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/apport_python_hook.py&quot;, line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File &quot;/usr/lib/python3/dist-packages/apport/__init__.py&quot;, line 5, in &lt;module&gt;
    from apport.report import Report
  File &quot;/usr/lib/python3/dist-packages/apport/report.py&quot;, line 30, in &lt;module&gt;
    import apport.fileutils
  File &quot;/usr/lib/python3/dist-packages/apport/fileutils.py&quot;, line 23, in &lt;module&gt;
    from apport.packaging_impl import impl as packaging
  File &quot;/usr/lib/python3/dist-packages/apport/packaging_impl.py&quot;, line 24, in &lt;module&gt;
    import apt
  File &quot;/usr/lib/python3/dist-packages/apt/__init__.py&quot;, line 23, in &lt;module&gt;
    import apt_pkg
ModuleNotFoundError: No module named &apos;apt_pkg&apos;

Original exception was:
Traceback (most recent call last):
  File &quot;wav2letter/tutorials/1-librispeech_clean/prepare_data.py&quot;, line 30, in &lt;module&gt;
    import sox
ModuleNotFoundError: No module named &apos;sox&apos;</pre>

It sounds that things stay the same. However, it was a good way to try. Any further comments? Thank you!

**Comment by ML6634** [comment]
@padentomasello  @avidov @tlikhomanenko @YuanGongND
So, do any experts have any ideas about the above questions? I use Docker with CUDA backend. Thank you!

**Comment by padentomasello** [comment]
Hi @ML6634, if you running the commands in the Docker containe, everything should already be installed, and we symlink `python3 and `python` to `python3.6` (https://github.com/facebookresearch/wav2letter/blob/master/Dockerfile-CUDA-Base#L57)

So this is the right command:

> python wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
usage: prepare_data.py [-h] [--src SRC] [--dst DST]
prepare_data.py: error: argument --dst: expected one argument

Now, your getting an error that `--dst` is empty. Do you have $W2LDIR set? (try  `echo $W2LDIR`?).  Make sure you are following the first step of https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean#step-1-data-preparation correctly. 

```
> W2LDIR=/home/$USER/w2l # or any other path where you want to keep the data
> mkdir -p $W2LDIR
> wget -qO- http://www.openslr.org/resources/12/train-clean-100.tar.gz | tar xvz -C $W2LDIR
> wget -qO- http://www.openslr.org/resources/12/dev-clean.tar.gz | tar xvz -C $W2LDIR
> wget -qO- http://www.openslr.org/resources/12/test-clean.tar.gz | tar xvz -C $W2LDIR
```

```
> tree $W2LDIR --filelimit 20
# /home/vineelkpratap/w2l
# └── LibriSpeech
#     ├── BOOKS.TXT
#     ├── CHAPTERS.TXT
#     ├── dev-clean [40 entries exceeds filelimit, not opening dir]
#     ├── LICENSE.TXT
#     ├── README.TXT
#     ├── SPEAKERS.TXT
#     ├── test-clean [40 entries exceeds filelimit, not opening dir]
#     └── train-clean-100 [251 entries exceeds filelimit, not opening dir]
```

**Comment by ML6634** [comment]
Thank @padentomasello for the very helpful comments! I followed

E2E Speech Recognition on Librispeech-Clean Dataset
https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean

and reinstalled everything. I got:

<pre>$ python wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
Traceback (most recent call last):
  File &quot;wav2letter/tutorials/1-librispeech_clean/prepare_data.py&quot;, line 55, in &lt;module&gt;
    os.makedirs(args.dst, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument &apos;exist_ok&apos;
</pre>

However,

<pre>$ python3 wav2letter/tutorials/1-librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
</pre>

went through successfully!

Anybody has experience with the following error? Thank you!

<pre>root@e5810f1a1eef:/# cd root
root@e5810f1a1eef:~# wav2letter/build/Train train --flagsfile ./wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  Invalid dictionary filepath specified with --tokensdir and --tokens: &quot;[...]/am/tokens.txt&quot;
*** Aborted at 1590083185 (unix time) try &quot;date -d @1590083185&quot; if you are using GNU date ***
PC: @     0x7f915e280e97 gsignal
*** SIGABRT (@0x1dee) received by PID 7662 (TID 0x7f91a3b50380) from PID 7662; stack trace: ***
    @     0x7f919be66890 (unknown)
    @     0x7f915e280e97 gsignal
    @     0x7f915e282801 abort
    @     0x7f915ec75957 (unknown)
    @     0x7f915ec7bab6 (unknown)
    @     0x7f915ec7baf1 std::terminate()
    @     0x7f915ec7bd24 __cxa_throw
    @     0x560f8fa5dcc9 main
    @     0x7f915e263b97 __libc_start_main
    @     0x560f8fabb36a _start
Aborted (core dumped)
</pre>

In the file, train.cfg, I did replace `[...]` with my paths, for example:
--datadir=/home/ml/

**Comment by ML6634** [comment]
@padentomasello

My train.cfg with [...] replaced by appropriate paths:

![image](https://user-images.githubusercontent.com/61134984/82709294-dea12280-9c45-11ea-9dd2-d2c1e229dd22.png)

I added "--tokensdir=/home/ml/w2l" in. Any comments about these paths? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 
`tokensdir` and `tokens` are concatenated to form the full path. You should specify then `tokensdir=` to be empty if you put full path in `tokens.`

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the helpful comment! Your comment makes sense! Originally, there was no tokensdir in the file, it produced the error message showed above, which mentioned tokensdir. Other than removing tokensdir from the file, any other changes I need to make? Thank you!

**Comment by ML6634** [comment]
Paths of those files:

![image](https://user-images.githubusercontent.com/61134984/82737335-0c45a480-9cf6-11ea-9ef3-7f3313b356d3.png)

**Comment by ML6634** [comment]
I had "/" at the end of datadir:

--datadir=/home/ml/w2l/

it could not go through.

**Comment by tlikhomanenko** [comment]
What is the error now? For me your config (if you fix tokensdir) looks fine so far.

For tokensdir you can specify
```
--tokensdir=/home/ml/w2l/am
--tokens=tokens.txt
```

`datadir` is the prefix for files specified in the `--train` and `--valid`.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for further comments. Unfortunately, with the train.cfg:

![image](https://user-images.githubusercontent.com/61134984/82741537-c221ea80-9d18-11ea-812a-ff7df39b8141.png)

the error stays the same:

<pre>root@e5810f1a1eef:~# wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  Invalid dictionary filepath specified with --tokensdir and --tokens: &quot;[...]/am/tokens.txt&quot;
*** Aborted at 1590271900 (unix time) try &quot;date -d @1590271900&quot; if you are using GNU date ***
PC: @     0x7fefe371de97 gsignal
*** SIGABRT (@0x1e90) received by PID 7824 (TID 0x7ff028fed380) from PID 7824; stack trace: ***
    @     0x7ff021303890 (unknown)
    @     0x7fefe371de97 gsignal
    @     0x7fefe371f801 abort
    @     0x7fefe4112957 (unknown)
    @     0x7fefe4118ab6 (unknown)
    @     0x7fefe4118af1 std::terminate()
    @     0x7fefe4118d24 __cxa_throw
    @     0x5643ebfaacc9 main
    @     0x7fefe3700b97 __libc_start_main
    @     0x5643ec00836a _start
Aborted (core dumped)
</pre>

Might it be an issue other than the file path?

**Comment by tlikhomanenko** [comment]
Look at here https://github.com/facebookresearch/wav2letter/blob/2c9ffdd9699dcb2fc61f84e0a6f07aea59266f58/Train.cpp#L182 and the several rows before. This is exactly error in tokens path. 

Can you try to run with the absolute path for the flagsfile (starting from `/`)? Seems it reads some another config file where it is set `tokensdir=[...]`.

**Comment by ML6634** [comment]
@tlikhomanenko @padentomasello

Thank both of you very much for the help! I am not sure why it produced the above bug associated with the file path. 

<pre>$ locate train.cfg
/home/ml/wav2letter/recipes/models/conv_glu/librispeech/train.cfg
/home/ml/wav2letter/recipes/models/conv_glu/wsj/train.cfg
/home/ml/wav2letter/recipes/models/lexicon_free/librispeech/train.cfg
/home/ml/wav2letter/recipes/models/lexicon_free/wsj/train.cfg
/home/ml/wav2letter/recipes/models/seq2seq_tds/librispeech/train.cfg
/home/ml/wav2letter/tutorials/1-librispeech_clean/train.cfg
</pre>

However, recently I went back to:

Building Running with Docker
https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker

and reinstalled everything starting from: 

#with CUDA backend (for CUDA 10 and ubuntu 18.04), with latest master commits
sudo docker run --runtime=nvidia --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cuda-latest
//with old container "/w2l" removed first.
 
When I did: 

#for CUDA backend
sudo docker build --no-cache -f ./Dockerfile-CUDA -t wav2letter . 

I got:

CMake Error: The current CMakeCache.txt directory /root/wav2letter/build/CMakeCache.txt is different than the directory 
/home/ml/wav2letter/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txtCMake Error: The source "/root/wav2letter/CMakeLists.txt" does not match the source "/home/ml/wav2letter/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

The bug was fixed by removing the "build" in wav2letter by:

rm -r build     //I removed CMakeCache.txt 1st, but after that it still had some problem)

Then, I also reinstalled every things followed by:

E2E Speech Recognition on Librispeech-Clean Dataset
https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean

May I ask you a question?

In the above process I removed "build". May I ask whether "build" has been added back automatically, or I need to do something (do I need to re-run cmake?) to add it back? Right now in \home\ml\wav2letter, I do not have "build": 

![image](https://user-images.githubusercontent.com/61134984/82743181-50a06700-9d2d-11ea-90e0-c7c6e92dc58c.png)

and so I cannot run

$ wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg

on Ubuntu directly. Should \home\ml\wav2letter have a "build"?

However, I do have a "build" in "wav2letter" in the root directory. I run 

<pre>root@e5810f1a1eef:~# wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
</pre>

from there, and the train.cfg there with [...] replaced by appropriate paths is:

![image](https://user-images.githubusercontent.com/61134984/82744388-38d0df00-9d3d-11ea-92f1-e5f3043e88bd.png)

I have tried different ways to replace [...] in train.cfg, including removing tokensdir and put full path to tokens.txt and lexicon.txt:

![image](https://user-images.githubusercontent.com/61134984/82744700-b5fe5300-9d41-11ea-8db7-946a9365ff34.png)

Unfortunately, the bug message stays the same.

**Comment by ML6634** [comment]
@tlikhomanenko @padentomasello 

It reads the above cfg file, since whenever I change the path for tokens in the cfg file it effects the path echo-printed on the error message:

<pre>root@e5810f1a1eef:~# wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  Invalid dictionary filepath specified with --tokensdir and --tokens: &quot;/home/ml/w2l/am/tokens.txt&quot;
*** Aborted at 1590370843 (unix time) try &quot;date -d @1590370843&quot; if you are using GNU date ***
PC: @     0x7fa2a0e17e97 gsignal
*** SIGABRT (@0x1f10) received by PID 7952 (TID 0x7fa2e66e7380) from PID 7952; stack trace: ***
    @     0x7fa2de9fd890 (unknown)
    @     0x7fa2a0e17e97 gsignal
    @     0x7fa2a0e19801 abort
    @     0x7fa2a180c957 (unknown)
    @     0x7fa2a1812ab6 (unknown)
    @     0x7fa2a1812af1 std::terminate()
    @     0x7fa2a1812d24 __cxa_throw
    @     0x5561cca17cc9 main
    @     0x7fa2a0dfab97 __libc_start_main
    @     0x5561cca7536a _start
Aborted (core dumped)
</pre>

Anyone can find anything wrong with the path? Thanks.

The tokens.txt:

![image](https://user-images.githubusercontent.com/61134984/82770803-8150d100-9dff-11ea-8663-8ddc543d8c0c.png)

**Comment by ML6634** [comment]
@tlikhomanenko @padentomasello

By

How can I use a local file on container?
https://stackoverflow.com/questions/44876778/how-can-i-use-a-local-file-on-container/44876899

I run

<pre>$ sudo docker run -v /home/ml/w2l:/root/wav2letter wav2letter/wav2letter:cuda-latest</pre>

to mount the folder /home/ml/w2l of the home directory onto /root/wav2letter in the container. Unfortunately, after that, the error message for

<pre>root@fb4270322d7d:~# wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
</pre>

stays the same. Any comments on this? Thank you!

**Comment by padentomasello** [comment]
Hi @ML6634, when you run `docker run -v /home/ml/w2l:/root/wav2letter` it will mount ` /home/ml/w2l` to `/root/wav2letter` within the docker container, so you will need to change the filepaths within your config. (It's no longer `/home/ml/w2l/am/tokens.txt` but `/root/wav2letter/am/tokens.txt`.). 

You can check for these files by running `ls /root/wav2letter/am/tokens.txt` within the docker container.

**Comment by ML6634** [comment]
Thanks @padentomasello for the helpful comment! 

(1) When I ran

<pre>$ sudo docker run -v /home/ml/w2l:/root/wav2letter wav2letter/wav2letter:cuda-latest
</pre>

it went through but it did not produced any messages. Then I replaced all "/home/ml/w2l"s by "/root/wav2letter" in the config:

![image](https://user-images.githubusercontent.com/61134984/82932582-46a97e80-9f4e-11ea-8e85-c8f5c32c0da5.png)

When I ran train, the error stayed the same, with the updated path for tokens.txt:

<pre>~# wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  Invalid dictionary filepath specified with --tokensdir and --tokens: &quot;/root/wav2letter/am/tokens.txt&quot;
*** Aborted at 1590514957 (unix time) try &quot;date -d @1590514957&quot; if you are using GNU date ***
PC: @     0x7fa865226e97 gsignal
*** SIGABRT (@0x194) received by PID 404 (TID 0x7fa8aaaf6380) from PID 404; stack trace: ***
    @     0x7fa8a2e0c890 (unknown)
    @     0x7fa865226e97 gsignal
    @     0x7fa865228801 abort
    @     0x7fa865c1b957 (unknown)
    @     0x7fa865c21ab6 (unknown)
    @     0x7fa865c21af1 std::terminate()
    @     0x7fa865c21d24 __cxa_throw
    @     0x557cb39b9cc9 main
    @     0x7fa865209b97 __libc_start_main
    @     0x557cb3a1736a _start
Aborted (core dumped)
</pre>

And
<pre>/# ls /root/wav2letter/am/tokens.txt
ls: cannot access &apos;/root/wav2letter/am/tokens.txt&apos;: No such file or directory
</pre>

(2) Before I did the mounting command, all paths in the config seemed correct, but it did not go through either. See: https://github.com/facebookresearch/wav2letter/issues/652#issuecomment-633339657. So, something else is wrong? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634,

It is bad to mount your folder into `/root/wav2letter` because this folder exists and non-empty in the docker container. Could you mount to `-v /home/ml/w2l:/root/w2l`?

Then fix paths in the config with respect to this and check:
```
ls -lah /root/w2l
cat /root/w2l/am/tokens.txt
```

and put in the comments what the above commands output?

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the further help!

I did: 

<pre>$ sudo docker run -v /home/ml/w2l:/root/w2l wav2letter/wav2letter:cuda-latest
</pre>

Updated the config (with <pre>archdir</pre> changed to <pre>/root...</pre> or with <pre>archdir</pre> stayed  with <pre>/home/ml...</pre>):

![image](https://user-images.githubusercontent.com/61134984/83000758-700aee80-9fd0-11ea-961f-e84f0f835ed6.png)

<pre>train</pre> did not go through:

<pre>~# wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  Invalid dictionary filepath specified with --tokensdir and --tokens: &quot;/root/w2l/am/tokens.txt&quot;
*** Aborted at 1590572495 (unix time) try &quot;date -d @1590572495&quot; if you are using GNU date ***
PC: @     0x7ff727d8ce97 gsignal
*** SIGABRT (@0x1e1) received by PID 481 (TID 0x7ff76d65c380) from PID 481; stack trace: ***
    @     0x7ff765972890 (unknown)
    @     0x7ff727d8ce97 gsignal
    @     0x7ff727d8e801 abort
    @     0x7ff728781957 (unknown)
    @     0x7ff728787ab6 (unknown)
    @     0x7ff728787af1 std::terminate()
    @     0x7ff728787d24 __cxa_throw
    @     0x5593a16f8cc9 main
    @     0x7ff727d6fb97 __libc_start_main
    @     0x5593a175636a _start
Aborted (core dumped)
</pre>

In addition,

<pre>root@fb4270322d7d:/# ls -lah /root/w2l
ls: cannot access &apos;/root/w2l&apos;: No such file or directory
root@fb4270322d7d:/# cat /root/w2l/am/tokens.txt
cat: /root/w2l/am/tokens.txt: No such file or directory
root@fb4270322d7d:/# ls -l
total 76
drwxr-xr-x   1 root root 4096 Mar 31 23:35 <font color="#729FCF"><b>bin</b></font>
drwxr-xr-x   2 root root 4096 Apr 24  2018 <font color="#729FCF"><b>boot</b></font>
drwxr-xr-x   5 root root  440 May 25 22:02 <font color="#729FCF"><b>dev</b></font>
drwxr-xr-x   1 root root 4096 May 25 22:02 <font color="#729FCF"><b>etc</b></font>
drwxr-xr-x   2 root root 4096 Apr 24  2018 <font color="#729FCF"><b>home</b></font>
drwxr-xr-x   1 root root 4096 Nov 27 20:03 <font color="#729FCF"><b>lib</b></font>
drwxr-xr-x   2 root root 4096 Oct 29  2019 <font color="#729FCF"><b>lib64</b></font>
drwxr-xr-x   2 root root 4096 Oct 29  2019 <font color="#729FCF"><b>media</b></font>
drwxr-xr-x   2 root root 4096 Oct 29  2019 <font color="#729FCF"><b>mnt</b></font>
drwxr-xr-x   1 root root 4096 Mar 31 23:40 <font color="#729FCF"><b>opt</b></font>
dr-xr-xr-x 345 root root    0 May 25 22:02 <font color="#729FCF"><b>proc</b></font>
drwx------   1 root root 4096 May 26 02:02 <font color="#729FCF"><b>root</b></font>
drwxr-xr-x   1 root root 4096 May 25 22:02 <font color="#729FCF"><b>run</b></font>
drwxr-xr-x   1 root root 4096 Oct 31  2019 <font color="#729FCF"><b>sbin</b></font>
drwxr-xr-x   2 root root 4096 Oct 29  2019 <font color="#729FCF"><b>srv</b></font>
dr-xr-xr-x  13 root root    0 May 25 22:02 <font color="#729FCF"><b>sys</b></font>
drwxrwxrwt   1 root root 4096 May 27 09:36 <span style="background-color:#4E9A06"><font color="#2E3436">tmp</font></span>
drwxr-xr-x   1 root root 4096 Oct 29  2019 <font color="#729FCF"><b>usr</b></font>
drwxr-xr-x   1 root root 4096 Oct 29  2019 <font color="#729FCF"><b>var</b></font>
</pre>

**Comment by ML6634** [comment]
@tlikhomanenko @padentomasello

Back to: https://github.com/facebookresearch/wav2letter/issues/652#issuecomment-633172841. May I ask whether the folder \home\ml\wav2letter should have a "build" folder? If so, what's the best command to install "build" there? Or, we may just copy "build" in the \root\wav2letter to there?

If there is a 'build' folder there, we may run <pre>train</pre> on Ubuntu directly.

**Comment by tlikhomanenko** [comment]
You either use build directory inside docker container (which we prepared for you) /root/wav2letter/build and run inside the container (everything is build with respect to the libs and dependencies installed in the docker image, no any use of anything from your local machine) or you build locally installing before all dependencies on your local machine. You cannot mix build dir from local machine and use in the container or vise versa. 

About you mounting issue - your folder is not mounted into the container. Make sure that `/home/ml/w2l` is not a symlink and it is real folder and please report the issue and ask on docker forum (you can try at first place the folder somewhere else, not in /home and mount it again).

**Comment by ML6634** [comment]
@tlikhomanenko @padentomasello

Thank @tlikhomanenko for the helpful comment! I posted the issue on Docker Forum. Meanwhile, for those who build the model from a Docker container, may I ask you how you access files at home directory from the container, for example, if you do mounting, would you please describe how you do it? Thank you!

**Comment by ML6634** [comment]
Now, it sounds that the container, w2l, is gone:

<pre>$ sudo docker exec -it w2l bash
Error: No such container: w2l
</pre>

When I do:

<pre>$ sudo docker ps -a
</pre>

the container, w2l, is not on the list anymore. I did not remove it. Anyway to have it back? In the future, how may I avoid this happening again? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 

Could you try exactly to run
```
sudo docker run --runtime=nvidia --rm -itd --ipc=host \
    --volume /home/ml/w2l:/root/w2l
    --name w2l_test wav2letter/wav2letter:cuda-latest
sudo docker exec -it w2l_test bash
# you will be inside container after the above command
ls -lah /root/w2l
```

Could you also say what docker and nvidia-docker versions you have?

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the helpful comments! Versions of Docker etc. on my computer:

<pre>$ docker --version
Docker version 19.03.9, build 9d988398e7
</pre>

<pre>$ sudo nvidia-docker version
NVIDIA Docker: 2.3.0
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:18 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
</pre>

After putting the three line command into one line, it went through for me. When I ran train, I got

<pre># wav2letter/build/Train train --flagsfile wav2letter/tutorials/1-librispeech_clean/train.cfg
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  could not open file /home/ml/w2l/LibriSpeech/train-clean-100/2817/142371/2817-142371-0008.flac
*** Aborted at 1590821288 (unix time) try &quot;date -d @1590821288&quot; if you are using GNU date ***
PC: @     0x7fd1d0cd4e97 gsignal
*** SIGABRT (@0x28) received by PID 40 (TID 0x7fd2165a4380) from PID 40; stack trace: ***
    @     0x7fd20e8ba890 (unknown)
    @     0x7fd1d0cd4e97 gsignal
    @     0x7fd1d0cd6801 abort
    @     0x7fd1d16c9957 (unknown)
    @     0x7fd1d16cfab6 (unknown)
    @     0x7fd1d16cfaf1 std::terminate()
    @     0x7fd1d16cfd24 __cxa_throw
    @     0x56471ac10057 w2l::loadSound&lt;&gt;()
    @     0x56471ac26913 w2l::W2lListFilesDataset::getLoaderData()
    @     0x56471ac15a97 w2l::W2lDataset::getFeatureData()
    @     0x56471ac17276 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x56471ac177de w2l::W2lDataset::get()
    @     0x56471aa4a61e _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl
    @     0x56471a9e55f8 main
    @     0x7fd1d0cb7b97 __libc_start_main
    @     0x56471aa4536a _start
Aborted (core dumped)
</pre>

However, I do have the file <pre>2817-142371-0008.flac</pre> in that folder, and it is a very short speech. In addition, in the config, I do have:

<pre>--input=flac</pre>

Anybody has experience why it could not be opened? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 

Again, if you are running in the docker, all the paths should be paths related to docker not your local machine. You need to check the path existence inside the container. So here you need to fix the paths in the list file to the `/root/w2l/LibriSpeech/train-clean-100/2817/142371/2817-142371-0008.flac`

Please read standard doc on docker (what is it) to understand how to use it.

**Comment by ML6634** [comment]
Thank @tlikhomanenko and @padentomasello for the help!

My training and decoding went through. Sounds that this program transcribes many of short speeches into texts. Anyway for me to use it to transcribe a single telephony wav file to text?

Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 

yes, you can use to transcribe any wav file. One possible issue can be with Transformer because they have positional embedding which was restricted during training to 36s, other models should work anyway.

I am closing this issue, please open new ones if you need assistance on other things.
