### ISSUE TITLE
Network architecture and other training parameters

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#653]
Thank you for this open-source ASR toolkit. Would you please share the network architectures and other parameters for the train.cfg file that you used to get the state-of-the-art results shown on your papers?

**Comment by juunnn** [comment]
may be you can search from [here](https://github.com/facebookresearch/wav2letter/tree/master/recipes/models)

**Comment by tlikhomanenko** [comment]
@samin9796, 

@juunnn pointed correctly to all our models. In the readme https://github.com/facebookresearch/wav2letter/tree/master/recipes/models you can find details on which paper in which folder contains reproducible steps. We publish all configs we used (train and decoder), and models itself.
