### ISSUE TITLE
Streaming inference on microphone audio

### ISSUE THREAD

**Issue by abhinavkulkarni** [facebookresearch/wav2letter#654]
Hi,

I am able to pipe the WAV formatted mono-channel 16kHz microphone audio to streaming inference utility as follows:

    ffmpeg -hide_banner -loglevel error \
    -f pulse -i default \
    -acodec pcm_s16le \
    -ar 16000 -ac 1 -ab 256k \
    -f wav - \
    | docker run --rm -v ~:/root/host -i --ipc=host --name w2l wav2letter/wav2letter:inference-latest sh -c "/root/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path=/root/host/model/"

I know the above works because I see the successful output. 

I wanted to mimic a similar setup using Python `PyAduio` such that I could run the same setup as above as follows:

```python stream_audio.py | <docker cmd>```

I need to do this because my target host does not have FFmpeg installed.

```
import pyaudio
import pickle, sys

chunk = 1024  # Record in chunks of 1024 samples
sample_format = pyaudio.paInt16  # 16 bits per sample
channels = 1
fs = 16000  # Record at 16000 samples per second
seconds = 1000

p = pyaudio.PyAudio()  # Create an interface to PortAudio
stream = p.open(format=sample_format,
                channels=channels,
                rate=fs,
                frames_per_buffer=chunk,
                input=True)

for i in range(0, int(fs / chunk * seconds)):
    data = stream.read(chunk)
    pickle.dump(data, sys.stdout.buffer)

```

However, I am unable to mimic the setup. What could be missing?

Thanks

**Comment by lunixbochs** [comment]
Pickle won't dump raw 16-bit integers, you need `struct.pack('<I')` or something

**Comment by abhinavkulkarni** [comment]
@lunixbochs: The `type(data)` is already `bytes`.

I tried running the script with following snippet:

```
for i in range(0, int(fs / chunk * seconds)):
    data = stream.read(chunk)
    data = int.from_bytes(data, byteorder='little')
    pickle.dump(data, sys.stdout.buffer)
```

but no success.

**Comment by lunixbochs** [comment]
Again. Pickle. Will. Not. Dump. Raw. Integers.

Do not use pickle to write raw data to output.

```
>>> pickle.dumps([1])
b'\x80\x03]q\x00K\x01a.'
```

That's 9 bytes for an integer. That's the output format you're giving wav2letter. There's extra junk in there. Have you tried just writing the bytes data directly to stdout?

**Comment by abhinavkulkarni** [comment]
Thanks @lunixbochs,  `sys.stdout.buffer.write(data)` works.
