### ISSUE TITLE
wav2letter inference speech alignment?

### ISSUE THREAD

**Issue by JesseBerdowski** [facebookresearch/wav2letter#656]
Hi guys and gals,

first and foremost thank you for all the efforts and kind sharing of the code!
I just finished the first inference tutorial and wanted to quickly ask: is there any possibilty  of speech alignment in the wav2letter@anywhere?

Thank you all in advance!

**Comment by tlikhomanenko** [comment]
cc @padentomasello, @vineelpratap, @jacobkahn

**Comment by vineelpratap** [comment]
Hi @JesseBerdowski , are you looking for force alignment given an audio and its transcript or the ability to produce timestamps for the generated output from streaming inference.

**Comment by JesseBerdowski** [comment]
Hi there thank you so much for your response.
I am indeed looking for the ability to produce timestamps to single-word utterances for the generated output from streaming inferences.

**Comment by mpenagar** [comment]
Hi @vineelpratap is there any way to do the first thing you where talking about, that is, to force align given an audio and its transcript?

Thanks!

**Comment by mpenagar** [comment]
I am sorry, I should have found this earlier:

https://github.com/facebookresearch/wav2letter/tree/v0.2/tools/alignment

I will take a look at it.

Thanks
