### ISSUE TITLE
How to update an already trained model with new data

### ISSUE THREAD

**Issue by adryyandc** [facebookresearch/wav2letter#66]
Hi,

There is a way to update an already trained or a pre-trained model with new data?
Is --continue command used for this purpose?

Best regards,
Adrian

**Comment by vineelpratap** [comment]
Yes, ` --continue` option can be used to do it. You can follow these steps
- Save the pretrained model with name `001_model_last.bin`.  
- Run  `luajit ~/wav2letter/train.lua --continue  <MODEL_PATH> -nthread 6 -gpu 1 -linseg 0 `

Note that you might have to modify the code a little bit to suit your needs. Currently, it the same training/valid/test data as it is used for training.

**Comment by adryyandc** [comment]
I do not want to continue training with existing data-set. Instead, i want to add new data (words) to training set and update a previously trained network. Seems code changes are needed.
