### ISSUE TITLE
Issue with opening Flac file for librispeech training

### ISSUE THREAD

**Issue by omprakashsonie** [facebookresearch/wav2letter#660]
I am trying to run on librispeech train-clean-100 using docker:

It give error while opening file even if it is there:
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not open file LibriSpeech/dev-clean/3081/166546/3081-166546-0073.flac

it goes on in the lists file and gives error for file which is later in the list, then again comes back to point to files in beginning.

the file exists:
ls -l LibriSpeech/dev-clean/3081/166546/3081-166546-0073.flac
-rwxrwxr-x  32029 May 17 04:06 LibriSpeech/dev-clean/3081/166546/3081-166546-0073.flac

When I delete the entry from lists, it again points to other files.

Also, some input on container:
~/libri-w2l-100-15may/wav2letter$ docker container list
CONTAINER ID        IMAGE                               COMMAND             CREATED             STATUS              PORTS               NAMES
23e1b446be1c        wav2letter/wav2letter:cuda-latest   "/bin/bash"         4 hours ago         Up 4 hours                              w2l-960-local
adb4671aa848        wav2letter/wav2letter:cuda-latest   "/bin/bash"         8 hours ago         Up 8 hours                              w2l-960
9c1fd679a486        wav2letter/wav2letter:cuda-latest   "/bin/bash"         9 hours ago         Up 9 hours                              w2l-29

Using this to create container:
sudo docker run --runtime=nvidia --rm -itd --ipc=host -v /home/omprakash.s/libri-w2l-100-15may:/w2l-libri/ --name w2l-960-local wav2letter/wav2letter:cuda-latest

**Comment by tlikhomanenko** [comment]
Could you show the head of your list file? 
Could you try to set the full absolute path to the files in the list file? Like:
```
id /w2l-libri/LibriSpeech/dev-clean/3081/166546/3081-166546-0073.flac ...
```

**Comment by omprakashsonie** [comment]
Thanks for your reply. Here are the details:

head train-clean-100.lst

train-clean-100-103-1240-0000	/w2l-libri/LibriSpeech/train-clean-100/103/1240/103-1240-0000.flac	14.085	chapter one missus rachel lynde is surprised missus rachel lynde lived just where the avonlea main road dipped down into a little hollow fringed with alders and ladies eardrops and traversed by a brook
train-clean-100-103-1240-0001	/w2l-libri/LibriSpeech/train-clean-100/103/1240/103-1240-0001.flac	15.945	that had its source away back in the woods of the old cuthbert place it was reputed to be an intricate headlong brook in its earlier course through those woods with dark secrets of pool and cascade but by the time it reached lynde's hollow it was a quiet well conducted little stream

I suspected it to be latency with shared drive and hence moved ahead with loading data in docker. 

Looks like it is working.

Will set up absolute path next time when I try again.

Thank you for your help.
