### ISSUE TITLE
How to estimate/train a convlm language model.

### ISSUE THREAD

**Issue by gopesh97** [facebookresearch/wav2letter#665]
I have the corpus of Devanagari text with me. I have trained a Kenlm and used it on wav2letter decoding, now I want to train a convlm to see if I can get better results. I tried looking for documentation but couldn't find any to train a CONVLM.

**Comment by tlikhomanenko** [comment]
Hi @gopesh97 

Right now we are training ConvLM in fairseq library and then convert it to the w2l bin format. Here is an example how to train https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/lexicon_free/librispeech/README.md#reproduce-language-models-training--evaluation and then how to convert (at the end of section).

**Comment by egorsmkv** [comment]
A working link - https://github.com/flashlight/wav2letter/blob/main/recipes/lexicon_free/librispeech/README.md#reproduce-language-models-training--evaluation
