### ISSUE TITLE
May wav2letter get along with DeepSpeech and DeepSpeech2 etc.?

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#666]
I am working on wav2letter, with Docker, CUDA backend, on Ubuntu 18.04 which was installed on an external hard drive. 

I am downloading the dependencies for DeepSpeech:

https://www.tensorflow.org/install/gpu

NVIDIA® GPU drivers, CUDA, NVIDIA cuDNN, ...

which are quite similar but not quite the same as those for wav2letter. Since the dependencies were downloaded one piece each time instead of the whole set as a package, I am not quite sure whether dependencies of DeepSpeech and those for wav2letter could get along each other (for example, one new version may cover an old version required by another? Or, one big package may cover a smaller one required by another?).

DeepSpeech2 also uses Docker.

Any comments about this? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 

I don't understand where you install things:
- Are you using docker for w2l and not installing all dependencies directly on your local machine? (please make sure you understand what is docker image and how it works - it is like virtual machine)
- Are you trying to use docker for DeepSpeech2? or you installing everything on local machine?

If you install all on your local machine - this is bad, if different versions are required for DeepSpeech2 and w2l there will conflicts/not working code, possibly you need to link correct versions of libs during cmake/make which will solve the issue which version of libs to use.

If you are fine with docker images (this is the simplest solution if you want to start experiments and don't want to do fancy stuff with build, etc.) then just use each docker image (they are independent, again, please read docs on docker, what is it and how it works, but the main idea docker images are independent ubuntu systems so they don't share anything between local machine and images itself: exception if you mount something into docker container but it is just like mounting the disks).

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the helpful comments, which take cares my concern nicely!

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the helpful comments, which take cares of my concern nicely!

**Comment by ML6634** [comment]
Sorry that I missed questions of @tlikhomanenko.  I am using Docker for w2l, and plan to use Docker for other thing(s) only (if possible). Thanks again!
