### ISSUE TITLE
Architecture related issue

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#667]
I am trying to train a dataset of around 250 hours with different architectures such as resnet, TDS and transformer mentioned in the recipe section. But my computer automatically restarts when I use these architectures with the same number of layers and other parameters. If I try to reduce the number of layers or some parameters on my own, it shows Cudnn bad parameter or arrayfire exception(invalid size).  I have Nvidia GeForce gtx 1080ti card. It has 8 GPUs, each GPU 11 GB. If I use Nvidia-smi, I see there are 7 GPUs running ( I set # of gpu to 7 in the train.cfg), each taking only around 3500-4000 MB. Any solutions?

**Comment by tlikhomanenko** [comment]
@samin9796 

Your error "Cudnn bad parameter or arrayfire exception(invalid size)." is related to the sizes of parameter/inputs you use. Just removing layer will not work, you need to be sure sizes of inputs to the layers and layers parameters sizes are consistent. If you need help here, please post your arch which gives this error. One thing you can try also is to use batchsize=1.

About computer restarting - have no idea, better to ask on nvidia cite if this could happens in case of OOM. Possibly you have internal setting of computer itself on restarting (like temperature or something else).

**Comment by samin9796** [comment]
@tlikhomanenko 

This is the architecture I used last time but got no error. However,  after only two epochs, training was finished although it was supposed to be trained for 200 epochs. I found out that learning rate and lrcrit were decreasing pretty fast and eventually became zero. 

`V -1 NFEAT 1 0
C2 1 10 21 1 2 1 -1 -1
R
DO 0.2
LN 0 1 2
TDS 10 21 80 0.2
TDS 10 21 80 0.2
C2 10 14 21 1 2 1 -1 -1
R
DO 0.2
LN 0 1 2
TDS 14 21 80 0.2
TDS 14 21 80 0.2
TDS 14 21 80 0.2
C2 14 18 21 1 2 1 -1 -1
R
DO 0.2
LN 0 1 2
TDS 18 21 80 0.2
TDS 18 21 80 0.2
TDS 18 21 80 0.2
TDS 18 21 80 0.2
TDS 18 21 80 0.2
TDS 18 21 80 0.2
V 0 1440 1 0
RO 1 0 3 2
L 1440 1024`

This is the train.cfg. Criterion is seq2seq.
`--rundir=/data/ahnaf/wav2letter/dataset_prep/
--datadir=/data/ahnaf/wav2letter/dataset_prep/
--tokensdir=/data/ahnaf/wav2letter/dataset_prep/
--train=train.lst
--valid=validation.lst
--lexicon=/data/ahnaf/wav2letter/dataset_prep/lexicon.txt
--input=wav
--tokens=tokens.txt
--archdir=/data/ahnaf/wav2letter/dataset_prep/
--arch=network.arch
--batchsize=4
--lr=0.5
--lrcrit=0.05
--momentum=0.5
--maxgradnorm=15
--mfsc=true
--nthread=7
--criterion=seq2seq
--maxdecoderoutputlen=120
--labelsmooth=0.05
--dataorder=output_spiral
--inputbinsize=25
--attnWindow=softPretrain
--softwstd=4
--trainWithWindow=true
--pretrainWindow=3
--attention=keyvalue
--encoderdim=512
--memstepsize=8338608
--eostoken=true
--pcttraineval=1
--pctteacherforcing=99
--listdata=true
--usewordpiece=true
--wordseparator=_
--target=ltr
--filterbanks=80
--sampletarget=0.01
--enable_distributed=true
--iter=200
--framesizems=30
--framestridems=10
--decoderdropout=0.1
--decoderattnround=2
--decoderrnnlayer=3
--seed=2

`
Here is the log:
`epoch:        1 | nupdates:            4 | lr: 0.000023 | lrcriterion: 0.000023 | runtime: 00:00:13 | bch(ms): 3410.54 | smp(ms): 40.86 | fwd(ms): 1617.17 | crit-fwd(ms): 598.84 | bwd(ms): 1124.33 | optim(ms): 283.48 | loss:  693.69364 | train-LER:  0.00 | train-WER:  0.00 | validation.lst-loss:  733.39475 | validation.lst-LER: 107.13 | validation.lst-WER: 100.00 | avg-isz: 1761 | avg-tsz: 129 | max-tsz: 196 | hrs:    0.55 | thrpt(sec/sec): 144.62
epoch:        2 | nupdates:          201 | lr: 0.000000 | lrcriterion: 0.000000 | runtime: 00:00:45 | bch(ms): 227.74 | smp(ms): 1.56 | fwd(ms): 35.04 | crit-fwd(ms): 7.27 | bwd(ms): 175.15 | optim(ms): 11.27 | loss:  708.97445 | train-LER: 104.71 | train-WER: 100.00 | validation.lst-loss:  714.08817 | validation.lst-LER: 107.05 | validation.lst-WER: 100.00 | avg-isz: 1804 | avg-tsz: 134 | max-tsz: 259 | hrs:   27.79 | thrpt(sec/sec): 2218.63`

**Comment by tlikhomanenko** [comment]
This is because `--iter` is not the number of epochs, it is number of updates. You can see that in the log it stopped with `nupdates=201`. Also set `warmup=0` (it is 8k by default, however it is useful only for transformer arch).

Let me know if this solves the issue.

**Comment by samin9796** [comment]
@tlikhomanenko  
Thank you. Now it is training for much longer. However, model is not converging. WER is above 100 after 20 epochs although loss seems to be decreasing. Here is the log output:

> epoch:        1 | nupdates:            4 | lr: 0.050000 | lrcriterion: 0.050000 | runtime: 00:00:13 | bch(ms): 3355.77 | smp(ms): 44.58 | fwd(ms): 1613.06 | crit-fwd(ms): 627.92 | bwd(ms): 1120.72 | optim(ms): 286.27 | loss:  844.34770 | train-LER:  0.00 | train-WER:  0.00 | validation.lst-loss:  578.93092 | validation.lst-LER: 98.39 | validation.lst-WER: 100.00 | avg-isz: 1020 | avg-tsz: 141 | max-tsz: 169 | hrs:    0.36 | thrpt(sec/sec): 95.83
epoch:        2 | nupdates:         3074 | lr: 0.049772 | lrcriterion: 0.049772 | runtime: 00:09:03 | bch(ms): 176.82 | smp(ms): 0.45 | fwd(ms): 35.17 | crit-fwd(ms): 21.76 | bwd(ms): 126.57 | optim(ms): 10.72 | loss:  470.10974 | train-LER: 88.39 | train-WER: 116.15 | validation.lst-loss:  382.23168 | validation.lst-LER: 83.69 | validation.lst-WER: 186.14 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1973.97
epoch:        3 | nupdates:         6145 | lr: 0.049545 | lrcriterion: 0.049545 | runtime: 00:09:03 | bch(ms): 176.92 | smp(ms): 0.45 | fwd(ms): 35.11 | crit-fwd(ms): 21.70 | bwd(ms): 126.81 | optim(ms): 10.64 | loss:  379.61321 | train-LER: 82.87 | train-WER: 122.69 | validation.lst-loss:  295.78027 | validation.lst-LER: 86.23 | validation.lst-WER: 100.57 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1972.87
epoch:        4 | nupdates:         9216 | lr: 0.049319 | lrcriterion: 0.049319 | runtime: 00:09:03 | bch(ms): 176.86 | smp(ms): 0.45 | fwd(ms): 35.15 | crit-fwd(ms): 21.73 | bwd(ms): 126.84 | optim(ms): 10.63 | loss:  316.97520 | train-LER: 84.49 | train-WER: 117.76 | validation.lst-loss:  228.04079 | validation.lst-LER: 84.71 | validation.lst-WER: 122.55 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1973.50
epoch:        5 | nupdates:        12287 | lr: 0.049094 | lrcriterion: 0.049094 | runtime: 00:09:03 | bch(ms): 176.94 | smp(ms): 0.46 | fwd(ms): 35.15 | crit-fwd(ms): 21.71 | bwd(ms): 126.87 | optim(ms): 10.62 | loss:  275.74931 | train-LER: 84.15 | train-WER: 113.56 | validation.lst-loss:  188.62885 | validation.lst-LER: 86.05 | validation.lst-WER: 116.56 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1972.67
epoch:        6 | nupdates:        15358 | lr: 0.048870 | lrcriterion: 0.048870 | runtime: 00:09:03 | bch(ms): 177.08 | smp(ms): 0.43 | fwd(ms): 35.12 | crit-fwd(ms): 21.68 | bwd(ms): 127.05 | optim(ms): 10.61 | loss:  252.76600 | train-LER: 84.05 | train-WER: 109.78 | validation.lst-loss:  167.85221 | validation.lst-LER: 85.34 | validation.lst-WER: 101.32 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1971.04
epoch:        7 | nupdates:        18429 | lr: 0.048648 | lrcriterion: 0.048648 | runtime: 00:09:04 | bch(ms): 177.24 | smp(ms): 0.45 | fwd(ms): 35.15 | crit-fwd(ms): 21.70 | bwd(ms): 127.14 | optim(ms): 10.62 | loss:  237.17470 | train-LER: 84.48 | train-WER: 106.41 | validation.lst-loss:  139.57756 | validation.lst-LER: 84.48 | validation.lst-WER: 112.36 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1969.32
epoch:        8 | nupdates:        21500 | lr: 0.048426 | lrcriterion: 0.048426 | runtime: 00:09:04 | bch(ms): 177.19 | smp(ms): 0.45 | fwd(ms): 35.13 | crit-fwd(ms): 21.67 | bwd(ms): 127.10 | optim(ms): 10.61 | loss:  221.95621 | train-LER: 85.42 | train-WER: 107.38 | validation.lst-loss:  121.32067 | validation.lst-LER: 84.61 | validation.lst-WER: 105.50 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1969.90
epoch:        9 | nupdates:        24571 | lr: 0.048205 | lrcriterion: 0.048205 | runtime: 00:09:03 | bch(ms): 177.06 | smp(ms): 0.44 | fwd(ms): 35.21 | crit-fwd(ms): 21.75 | bwd(ms): 127.02 | optim(ms): 10.67 | loss:  214.64996 | train-LER: 82.72 | train-WER: 107.11 | validation.lst-loss:  108.93524 | validation.lst-LER: 85.69 | validation.lst-WER: 101.95 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1971.29
epoch:       10 | nupdates:        27642 | lr: 0.047985 | lrcriterion: 0.047985 | runtime: 00:09:03 | bch(ms): 177.04 | smp(ms): 0.49 | fwd(ms): 35.21 | crit-fwd(ms): 21.76 | bwd(ms): 126.98 | optim(ms): 10.65 | loss:  203.19442 | train-LER: 84.24 | train-WER: 105.78 | validation.lst-loss:  100.56053 | validation.lst-LER: 81.56 | validation.lst-WER: 107.82 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1971.49
epoch:       11 | nupdates:        30713 | lr: 0.047767 | lrcriterion: 0.047767 | runtime: 00:09:03 | bch(ms): 177.07 | smp(ms): 0.45 | fwd(ms): 35.16 | crit-fwd(ms): 21.70 | bwd(ms): 127.12 | optim(ms): 10.62 | loss:  203.17685 | train-LER: 85.31 | train-WER: 107.06 | validation.lst-loss:   94.19651 | validation.lst-LER: 84.91 | validation.lst-WER: 110.73 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1971.21
epoch:       12 | nupdates:        33784 | lr: 0.047549 | lrcriterion: 0.047549 | runtime: 00:09:03 | bch(ms): 176.95 | smp(ms): 0.49 | fwd(ms): 35.12 | crit-fwd(ms): 21.66 | bwd(ms): 126.99 | optim(ms): 10.63 | loss:  183.02544 | train-LER: 85.36 | train-WER: 106.21 | validation.lst-loss:   86.97901 | validation.lst-LER: 84.87 | validation.lst-WER: 112.29 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1972.58
epoch:       13 | nupdates:        36855 | lr: 0.047332 | lrcriterion: 0.047332 | runtime: 00:09:03 | bch(ms): 177.03 | smp(ms): 0.48 | fwd(ms): 35.12 | crit-fwd(ms): 21.66 | bwd(ms): 127.12 | optim(ms): 10.62 | loss:  183.16420 | train-LER: 84.77 | train-WER: 106.63 | validation.lst-loss:   82.17011 | validation.lst-LER: 85.70 | validation.lst-WER: 112.32 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1971.62
epoch:       14 | nupdates:        39926 | lr: 0.047116 | lrcriterion: 0.047116 | runtime: 00:09:03 | bch(ms): 177.07 | smp(ms): 0.50 | fwd(ms): 35.11 | crit-fwd(ms): 21.65 | bwd(ms): 127.05 | optim(ms): 10.61 | loss:  185.72854 | train-LER: 84.45 | train-WER: 108.54 | validation.lst-loss:   78.72603 | validation.lst-LER: 84.62 | validation.lst-WER: 109.84 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1971.22
epoch:       15 | nupdates:        42997 | lr: 0.046902 | lrcriterion: 0.046902 | runtime: 00:09:03 | bch(ms): 177.11 | smp(ms): 0.48 | fwd(ms): 35.18 | crit-fwd(ms): 21.71 | bwd(ms): 127.09 | optim(ms): 10.65 | loss:  176.71196 | train-LER: 85.23 | train-WER: 107.17 | validation.lst-loss:  110.26738 | validation.lst-LER: 85.45 | validation.lst-WER: 103.66 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1970.77
epoch:       16 | nupdates:        46068 | lr: 0.046688 | lrcriterion: 0.046688 | runtime: 00:09:03 | bch(ms): 176.98 | smp(ms): 0.46 | fwd(ms): 35.15 | crit-fwd(ms): 21.69 | bwd(ms): 127.07 | optim(ms): 10.61 | loss:  169.87589 | train-LER: 84.74 | train-WER: 107.42 | validation.lst-loss:  531.33527 | validation.lst-LER: 91.34 | validation.lst-WER: 100.01 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1972.22
epoch:       17 | nupdates:        49139 | lr: 0.046475 | lrcriterion: 0.046475 | runtime: 00:09:04 | bch(ms): 177.38 | smp(ms): 0.47 | fwd(ms): 35.16 | crit-fwd(ms): 21.69 | bwd(ms): 127.26 | optim(ms): 10.61 | loss:  175.18809 | train-LER: 84.37 | train-WER: 109.14 | validation.lst-loss:   71.69496 | validation.lst-LER: 84.75 | validation.lst-WER: 109.05 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1967.76
epoch:       18 | nupdates:        52210 | lr: 0.046263 | lrcriterion: 0.046263 | runtime: 00:09:04 | bch(ms): 177.26 | smp(ms): 0.48 | fwd(ms): 35.17 | crit-fwd(ms): 21.70 | bwd(ms): 127.22 | optim(ms): 10.63 | loss:  163.24543 | train-LER: 84.89 | train-WER: 108.49 | validation.lst-loss:   69.70462 | validation.lst-LER: 84.71 | validation.lst-WER: 108.71 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1969.10
epoch:       19 | nupdates:        55281 | lr: 0.046052 | lrcriterion: 0.046052 | runtime: 00:09:04 | bch(ms): 177.21 | smp(ms): 0.47 | fwd(ms): 35.18 | crit-fwd(ms): 21.72 | bwd(ms): 127.13 | optim(ms): 10.65 | loss:  166.36718 | train-LER: 84.06 | train-WER: 109.05 | validation.lst-loss:   95.06888 | validation.lst-LER: 83.46 | validation.lst-WER: 106.51 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1969.65
epoch:       20 | nupdates:        58352 | lr: 0.045842 | lrcriterion: 0.045842 | runtime: 00:09:03 | bch(ms): 176.94 | smp(ms): 0.46 | fwd(ms): 35.21 | crit-fwd(ms): 21.74 | bwd(ms): 127.13 | optim(ms): 10.65 | loss:  162.97865 | train-LER: 83.40 | train-WER: 104.94 | validation.lst-loss:   66.71311 | validation.lst-LER: 84.61 | validation.lst-WER: 108.90 | avg-isz: 1108 | avg-tsz: 132 | max-tsz: 267 | hrs:  297.75 | thrpt(sec/sec): 1972.68


Here is the train.cfg file:

> --runname=tds_latest_last
--rundir=/data/ahnaf/wav2letter/dataset_prep/
--datadir=/data/ahnaf/wav2letter/dataset_prep/
--tokensdir=/data/ahnaf/wav2letter/dataset_prep/
--train=train.lst
--valid=validation.lst
--lexicon=/data/ahnaf/wav2letter/dataset_prep/lexicon.txt
--input=wav
--tokens=tokens.txt
--archdir=/data/ahnaf/wav2letter/dataset_prep/
--arch=network_backup.arch
--batchsize=3
--lr=0.05
--lrcrit=0.05
--momentum=0.0
--maxgradnorm=15
--mfsc=true
--nthread=7
--criterion=seq2seq
--maxdecoderoutputlen=120
--labelsmooth=0.05
--dataorder=output_spiral
--inputbinsize=25
--attnWindow=softPretrain
--softwstd=4
--trainWithWindow=true
--pretrainWindow=3
--attention=keyvalue
--encoderdim=512
--memstepsize=8338608
--eostoken=true
--pcttraineval=1
--pctteacherforcing=99
--listdata=true
--target=ltr
--filterbanks=80
--sampletarget=0.01
--enable_distributed=true
--iter=200000
--framesizems=30
--framestridems=15
--decoderdropout=0.1
--decoderattnround=2
--decoderrnnlayer=3
--seed=2
--warmup=0
--reportiters=200
--stepsize=150000
--gamma=0.8

**Comment by samin9796** [comment]
@tlikhomanenko 
Thank you. I could train a model with seq2seq TDS architecture. Now I would like to train a transformer based model. If I train two models on 250 hrs and 400 hrs dataset, I am wondering if the following arch would be a good one or I need to reduce or increase the number of layers and other parameters. I am following the same training parameters mentioned in the recipe section.

> V -1 1 NFEAT 0
WN 3 C NFEAT 1024 3 1 -1
GLU 2
DO 0.2
M 1 1 2 1
WN 3 C 512 1024 3 1 -1
GLU 2
DO 0.2
M 1 1 2 1
WN 3 C 512 1536 3 1 -1
GLU 2
DO 0.2
M 1 1 2 1
RO 2 0 3 1
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
TR 768 3072 4 460 0.2 0.2
L 768 512

**Comment by tlikhomanenko** [comment]
@samin9796 

You could at first start with this arch and see how it goes, and if overfitting happens for you on train. If it overfits then reduce number of layers, try larger dropout. At least number of layers and dropout are the first thing you need to try for your data. Also learning rate and warmup are important, so you need to tune them too.

Some note: use instead of `M 1 1 2 1` this one `M 2 1 2 1`.

**Comment by samin9796** [comment]
@tlikhomanenko 

Could you please tell me what these parameters are after TR?  I can't find in the " writing arch file" doc?

> TR 768 3072 4 460 0.2 0.2

**Comment by tlikhomanenko** [comment]
The info of params is here https://github.com/facebookresearch/wav2letter/blob/master/src/module/W2lModule.cpp#L115
`TR  embeddingDim mlpDim nHeads maxPositions dropout layerDropout usePreNormLayer` (added to the arch wiki, let me know if more info on param you need).

About your loss and WER - loss is still very high. Which criterion and optimizer do you use? try the same init lr for both criterion and network.

**Comment by samin9796** [comment]
@tlikhomanenko 
I am using the train_am_transformer_s2s.cfg one from the recipes. Criterion is transformer,  netoptim and critoptim are both adagrad.

**Comment by tlikhomanenko** [comment]
First - try latest master, we recently fixed some issue with lr setting for s2s models, then try to have the same lr and lrcrit. And you need to tune lr and warmup. 

cc @syhw maybe you know what else can be done here.

**Comment by samin9796** [comment]
@tlikhomanenko 
My audio files are between 11 sec to 15 sec. Here in the arch maxposition is set to 460. Does maxposition value need to be increased for that?

**Comment by tlikhomanenko** [comment]
We used this 460 for 36s audio, so it should be fine for you too. If you have longer input then it will crash so you will see this for sure.

**Comment by tlikhomanenko** [comment]
I just noticed that you have `--maxgradnorm=15`, possibly too large, try to set to 1 or even further 0.1.

**Comment by Bernardo-Favoreto** [comment]
> You could at first start with this arch and see how it goes, and if overfitting happens for you on train. If it overfits then reduce number of layers, try larger dropout. At least number of layers and dropout are the first thing you need to try for your data. Also learning rate and warmup are important, so you need to tune them too.
@tlikhomanenko 
Is there a recommended way to tune it? For instance, I have around 100h of audio on my language and would like to use transformers. Should I reduce number of layers (because of less data)? Increase or decrease warmup/learning rate? And also, does batch size plays a major role in tuning these too?
Thanks!

**Comment by tlikhomanenko** [comment]
You can decrease layers / increase dropout / increase specaug - you need to see if there is a huge overfitting with less data, this depends not only on the data size but also complexity of your audio. Warmup / lr you can try the same at first and then for sure tune lr. Warmup - depending if you see blowing up of the model. Batchsize could influence here on the lr values.

**Comment by Bernardo-Favoreto** [comment]
Thanks, Tatiana!

When you say increase specaug you mean the number of steps or its options (fmask, fmaskn, etc...)?

Also, "blowing up of the model" is the loss skyrocketing? It is a bit unclear to me how metrics behave during training. For instance, my models seem to get stuck in a loss value (lowest I got was ~16) while WER for both dev and train are also stuck in 100+ after 50+ epochs. 
My guess is I am not tuning parameters/architectures accordingly, but I am unsure since I don't know what to expect during training.

**Comment by tlikhomanenko** [comment]
> When you say increase specaug you mean the number of steps or its options (fmask, fmaskn, etc...)?

more augmentation, so change saug parameters fmask, etc.

At first you can disable specaug and tune parameters that on the train you get ~0 WER and ~0 loss. During training WER for some time on train stays 100+ while loss is going down, then loss continue to go down and wer goes down too. Blowing up could happens after warmup - loss is going up or not decreasing.

**Comment by Bernardo-Favoreto** [comment]
Would you say given that I have less data and a smaller model (currently using 16 transformer layers) with the same batch size as you guys (128) learning rate should be smaller? Also, regarding warmup and specaug I'm starting it at 24k steps.

**Comment by tlikhomanenko** [comment]
Learning rate depends on the data and model size too, you cannot say that for the same batch learning rate will be the same. Just monitor the training WER and dev WER, how it behaves. Also you can increase dropout in your model to avoid overfitting (if I forgot to mention it).

**Comment by Bernardo-Favoreto** [comment]
Right, thanks. I'll present to you some of the things I've encountered. 

I've tried the Transformer architecture trained with CTC (**am_transformer_ctc.arch**) with both 7 and 16 layers of transformer (vs. the original 24). I have around 100h of Portuguese speech data and trained both models until they (at least is what it seemed) stopped learning. Here are their logs (I've uploaded them to avoid spamming here):
**Transformer 7 layers, batch size=8*8GPUs, warmup/specaug=16k steps, lr=0.4**: https://justpaste.it/259op
**Transformer 16 layers, batch size =16*8GPUs, warmup/specaug=24k steps, lr=0.4**: https://justpaste.it/53ko5
Some things that caught my attention: Even though the latter model is larger, its metrics got stuck on slightly worse values than the former (~50 vs. ~60 train-WER) but both of them seem like they reached their limits before I stopped training (the last epochs we can see the model is clearly stuck). Another comment is regarding the fact that dev-WER was always lower than train-WER, is this expected?
I was wondering if you have any thoughts on the presented behavior, as I'm not sure what would be my best direction right now and I also don't know the expected behavior from training these models. Should I try the exact same architecture with the exact same hyper-parameters? But would this be appropriate as I have 1/10 of the librispeech data? It also seems a bit counterintuitive since my smaller model performed slightly better. 
Anyway, I'd be happy to hear any thoughts/comments regarding the presented behavior.

Thank you ever so much, Tatiana.

**Comment by tlikhomanenko** [comment]
dev-WER is lower because you have specaug, so train loss and WER is computed on the augmented data. Also to be sure that model is trained you need to look at dev WER, not on train.

About model capacity to prevent overfitting:
- use smaller one, less number of parameters or
- set larger dropout there (and layer drop)

I would suggest to have at first baseline which you train without spec aug and make sure on the training you can easily overfit.

Then if on train you can reach less than 50% WER, activate saug only then. Probably your warmup is also very short, or you need to reduce learning rate.

For larger model try to increase dropout.

Looks they converge, here you can start to reduce learning rate, as we did for our SOTA results, use lr_decay and lr_decay_step.

**Comment by Bernardo-Favoreto** [comment]
Thanks, Tatiana!

I was happy to see even though metrics weren't as good as I expected, the model still performs reasonably well. I find a bit weird that I can't get better metrics since I have ~100h of data and I've seen great results with WSJ dataset. What comes into mind is data quality or maybe difficulties of the language itself (Brazilian Portuguese)?

I resumed the 7 layer transformer model but with 0.4 LR for a while and then started to halve it. Indeed, the model improved a bit on dev-WER/loss, I will resume once again now with 0.1 LR and keep halving every 40 epochs.

Regarding LR decay: for both models, they were set exactly as the recipe came, but it didn't seem to work properly, maybe I need to adapt this schedule for less data? 

Finally, regarding train-WER/loss I should not worry if they are stuck, as long as dev metrics are decreasing?

Thank you once again!

**Comment by tlikhomanenko** [comment]
@Bernardo-Favoreto always welcome!

> I was happy to see even though metrics weren't as good as I expected, the model still performs reasonably well. I find a bit weird that I can't get better metrics since I have ~100h of data and I've seen great results with WSJ dataset. What comes into mind is data quality or maybe difficulties of the language itself (Brazilian Portuguese)?

Yep, this depends on a lot of factors, like language, audio quality (noisy conditions, reading or conversational speech), speakers, accents, lexicon.

> I resumed the 7 layer transformer model but with 0.4 LR for a while and then started to halve it. Indeed, the model improved a bit on dev-WER/loss, I will resume once again now with 0.1 LR and keep halving every 40 epochs.

Nice

> Regarding LR decay: for both models, they were set exactly as the recipe came, but it didn't seem to work properly, maybe I need to adapt this schedule for less data?

Our SOTA recipes is good start but it is optimized for specific dataset, so at least some training params, like start lr and warmup/augmentation start can be different. Also depends on how hard / less your data you need to have more regularization (like increasing dropout, reducing number of layers).

> Finally, regarding train-WER/loss I should not worry if they are stuck, as long as dev metrics are decreasing?

Yep.
