### ISSUE TITLE
The source url in beamer-scm-1.rockspec doesn't exist

### ISSUE THREAD

**Issue by lijinfeng0713** [facebookresearch/wav2letter#67]
> package = "beamer"
> version = "scm-1"
> 
> source = {
>    url = "git://github.com/torch/beamer.git"
> }
> 
> description = {
>    summary = "Large Vocabulary Beam Search",
>    detailed = [[
>    Large Vocabulary Beam Search
>    ]],
>    homepage = "https://github.com/torch/beamer",
>    license = "BSD"
> }
> 
> dependencies = {
>    "lua >= 5.1",
>    "torch >= 7.0",
> }
> 
> build = {
>    type = "cmake",
>    variables = {
>       CMAKE_BUILD_TYPE="Release",
>       CMAKE_PREFIX_PATH="$(LUA_BINDIR)/..",
>       CMAKE_INSTALL_PREFIX="$(PREFIX)"
>    }
> }

The source url doesn't exist

**Comment by vineelpratap** [comment]
Hi,
 As you can see in the wiki, we use [`luarocks make`] to install. So, it assumes everything is in local directory and does make + install - https://github.com/luarocks/luarocks/wiki/make .
