### ISSUE TITLE
how to use model trained with w2l_docker_CUDA in   w2l_docker_CPU

### ISSUE THREAD

**Issue by lixinyu2001** [facebookresearch/wav2letter#670]
I have trained a model use wav2letter docker(CUDA),  and I used it to decode ,it worked fine ;
When I used the model file in a wav2letter docker(CPU),  it  doesn't  work fine. 
Is there anything should I do before I use the model in  wav2letter docker(CPU)？

**Comment by tlikhomanenko** [comment]
@lixinyu2001 

There is known issue with CPU backend, see https://github.com/facebookresearch/wav2letter/issues/503. Also there is mismatch of operations for CPU and CUDA and it could have expected deviation if you use CUDA backend trained models in CPU backed later (at least for transformers).

Solution for now: retrain on CPU backed the same recipe or use CUDA backend for CUDA trained models.

Closing this issue, please comment in the https://github.com/facebookresearch/wav2letter/issues/503 directly (and please put details what model and what is the mismatch of decoding output between CPU and CUDA backends).

**Comment by lixinyu2001** [comment]
Thanks , I make a mistake ,only check the open issue.
