### ISSUE TITLE
Re: Acoustic models training and beam-search decoding on Librispeech

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#676]
@tlikhomanenko

(1) By https://github.com/facebookresearch/wav2letter/issues/599#issuecomment-611349844, it sounds that the model, https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/librispeech/README.md, might be good for me to try for transcribing telephony audio. Right?

(2) To run that model, I started with Data preparation from https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019. I did:

<pre>$ pip install sentencepiece
Collecting sentencepiece
  Downloading https://files.pythonhosted.org/packages/7d/d2/46040cf958200c40382b4a3528f007841cedba14f41acead5cb9c6dc787c/sentencepiece-0.1.91-cp27-cp27mu-manylinux1_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.1MB/s 
Installing collected packages: sentencepiece
Successfully installed sentencepiece-0.1.91
</pre>

Then

<pre>$ python3 /home/ml/wav2letter/recipes/models/utilities/prepare_librispeech_wp_and_official_lexicon.py --data_dst /home/ml/My_W2L/Data --model_dst /home/ml/My_W2L/Models --nbest 10 --wp 10000
Traceback (most recent call last):
  File &quot;/home/ml/wav2letter/recipes/models/utilities/prepare_librispeech_wp_and_official_lexicon.py&quot;, line 24, in &lt;module&gt;
    import sentencepiece as spm
ModuleNotFoundError: No module named &apos;sentencepiece&apos;
</pre>

I did run:

<pre>$ pip install sentencepiece==0.1.82
</pre>

first, then I got the same bug as above.

Any comment about this bug? Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 

if you are not familiar with python env and python2 python3, please read about this (ask this looking back at all your questions =) ). So here I guess you install into python2 env not in python3, call `pip3 install sentencepiece==0.1.82`.

**Comment by ML6634** [comment]
From the commands in the link of (2) above:

pip install sentencepiece==0.1.82
python3 ../../utilities/prepare_librispeech_wp_and_official_lexicon.py --data_dst [...] --model_dst [...] --nbest 10 --wp 10000

with data downloaded and prepared, and pip replaced by pip3, it goes through. Thank @tlikhomanenko for the helpful comment!
