### ISSUE TITLE
error: ‘afSetMemStepSize’ is not a member of ‘fl’

### ISSUE THREAD

**Issue by luweishuang** [facebookresearch/wav2letter#677]
I install wav2letter as introduce in wiki from source. I encounted   `error: ‘afSetMemStepSize’ is not a member of ‘fl’` . I found commit cfcf21c5c9dde9dd068e4c7ea80077881c70e69a do some midification in this , I refered commit cfcf21c5c9dde9dd068e4c7ea80077881c70e69a and set back fl to af.  then i reported error `error: ‘afGetMemStepSize’ is not a member of ‘af’`

**Comment by vineelpratap** [comment]
Hi,
 You  can use the latest version of wav2letter and flashlight to avoid this error.

**Comment by luweishuang** [comment]
I build the latest flashlight again and it do solved this problem
