### ISSUE TITLE
Resnet - Total Batches zero during training

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#679]
I am using the same Resnet architecture from the SOTA recipe. 
This is what I am getting:

> I0606 00:52:02.980521  1392 Train.cpp:253] [Network Params: 283635715]
I0606 00:52:02.980557  1392 Train.cpp:254] [Criterion] ConnectionistTemporalClassificationCriterion
I0606 00:52:03.228327  1392 Train.cpp:262] [Network Optimizer] SGD (momentum=0.6)
I0606 00:52:03.228358  1392 Train.cpp:263] [Criterion Optimizer] SGD
[8a7bc292062a:01387] 6 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[8a7bc292062a:01387] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
I0606 00:52:04.425510  1398 W2lListFilesDataset.cpp:141] 64491 files found. 
I0606 00:52:04.426525  1398 Utils.cpp:102] Filtered 64491/64491 samples
I0606 00:52:04.426554  1398 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 0
I0606 00:52:04.436514  1397 W2lListFilesDataset.cpp:141] 64491 files found. 
I0606 00:52:04.437537  1397 Utils.cpp:102] Filtered 64491/64491 samples
I0606 00:52:04.437567  1397 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 0
I0606 00:52:04.443989  1393 W2lListFilesDataset.cpp:141] 64491 files found. 
I0606 00:52:04.445011  1393 Utils.cpp:102] Filtered 64491/64491 samples
I0606 00:52:04.445053  1393 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 0

This is the log file:

> epoch:        1 | nupdates:            0 | lr: 0.040000 | lrcriterion: 0.006000 | runtime: 00:00:00 | bch(ms): 0.00 | smp(ms): 0.00 | fwd(ms): 0.00 | crit-fwd(ms): 0.00 | bwd(ms): 0.00 | optim(ms): 0.00 | loss:    0.00000 | train-TER:  0.00 | train-WER:  0.00 | validation.lst-loss:    0.00000 | validation.lst-TER:  0.00 | validation.lst-WER:  0.00 | avg-isz: 000 | avg-tsz: 000 | max-tsz: 000 | hrs:    0.00 | thrpt(sec/sec): n/a
epoch:        2 | nupdates:            0 | lr: 0.040000 | lrcriterion: 0.006000 | runtime: 00:00:00 | bch(ms): 0.00 | smp(ms): 0.00 | fwd(ms): 0.00 | crit-fwd(ms): 0.00 | bwd(ms): 0.00 | optim(ms): 0.00 | loss:    0.00000 | train-TER:  0.00 | train-WER:  0.00 | validation.lst-loss:    0.00000 | validation.lst-TER:  0.00 | validation.lst-WER:  0.00 | avg-isz: 000 | avg-tsz: 000 | max-tsz: 000 | hrs:    0.00 | thrpt(sec/sec): n/a
epoch:        3 | nupdates:            0 | lr: 0.040000 | lrcriterion: 0.006000 | runtime: 00:00:00 | bch(ms): 0.00 | smp(ms): 0.00 | fwd(ms): 0.00 | crit-fwd(ms): 0.00 | bwd(ms): 0.00 | optim(ms): 0.00 | loss:    0.00000 | train-TER:  0.00 | train-WER:  0.00 | validation.lst-loss:    0.00000 | validation.lst-TER:  0.00 | validation.lst-WER:  0.00 | avg-isz: 000 | avg-tsz: 000 | max-tsz: 000 | hrs:    0.00 | thrpt(sec/sec): n/a

This is the train.cfg file:

> --runname=resnet_1
--rundir=/data/ahnaf/wav2letter/dataset_prep/all_models/
--datadir=/data/ahnaf/wav2letter/dataset_prep/
--tokensdir=/data/ahnaf/wav2letter/dataset_prep/
--train=train.lst
--valid=validation.lst
--lexicon=/data/ahnaf/wav2letter/dataset_prep/lexicon.txt
--input=wav
--tokens=tokens_normal.txt
--archdir=/data/ahnaf/wav2letter/dataset_prep/
--arch=network_backup.arch
--criterion=ctc
--mfsc
--labelsmooth=0.05
--sampletarget=0.01
--lr=0.4
--lrcrit=0.006
--linseg=0
--momentum=0.6
--maxgradnorm=1
--onorm=target
--sqnorm
--nthread=6
--batchsize=4
--filterbanks=80
--lrcosine
--iter=500
--minloglevel=0
--mintsz=2
--minisz=200
--reportiters=0
--logtostderr
--enable_distributed

**Comment by tlikhomanenko** [comment]
All the samples are filtered, the params which influence the filtering are `--mintsz=2
--minisz=200`, either you have targets with 1-2 words or very short audio, or you specified wrongly the duration (which should be in ms, not is seconds) in the list file. 

First recheck you list file, what duration (min, max, mean) do you have and what is min/max/mean of the target transcription length.

**Comment by samin9796** [comment]
I specified the duration in sec. Thank you.
