### ISSUE TITLE
require 'samplerate' in "readers.lua" in the reader.audio

### ISSUE THREAD

**Issue by gauenk** [facebookresearch/wav2letter#68]
The 'samplerate' library seems to be required to standardize the sampling rate of an audio file. I can't find the 'samplerate' package online. I do not think it is made available through this github repo install. In fact, it seems to have caused someone else an issue, to which the solution was to avoid calling this code  (see #64).

I think this information should be included in this repo or an alternative to transformating the sampling rate should be provided. Any thoughts? 

Thank you.

**Comment by vineelpratap** [comment]
Hi, 
Thanks for the feedback. We plan to  open source `samplerate` package soon.

**Comment by mgoldey** [comment]
@gauenk 
Just sox it. `sox inputfile outputfile rate 16k`
Fixed it for me

**Comment by gauenk** [comment]
@mgoldey thank you for that info. I ended up using ffmpeg but “tomayto, tomahto”
