### ISSUE TITLE
Test binary WER incorrect

### ISSUE THREAD

**Issue by TijsRozenbroek** [facebookresearch/wav2letter#682]
Hi again!

I have a question about the Test binary.
I have trained a seq2seq AM, which achieves low WERs during training.
However when I run the command
```
wav2letter/build/Test test --am atc/run/seq2seq_tds_atc_network1/001_model_last.bin --test atc/lists/test.lst --show
```
it gives an unexpected WER for all the transcriptions.
For example see the following output:
```
|T|: s p e e d b i r d | _ t w o | _ t w o | _ t h r e e | _ r a d a r | _ c o n t a c t
|P|: s p e e d b i r d | _ t w o | _ t w o | _ t h r e e | _ r a d a r | _ c o n t a c t
[sample: sm3_04_134, WER: 83.3333%, LER: 0%, total WER: 97.7383%, total LER: 12.7725%, progress (thread 0): 99.8763%]
```
In this case the LER is correct, but the WER seems to be wildly off, as does the total WER.

Would like to hear your thoughts about what the problem might be, thanks in advance!

**Comment by lunixbochs** [comment]
https://github.com/facebookresearch/wav2letter/issues/574

**Comment by TijsRozenbroek** [comment]
That solved the problem, thanks.
