### ISSUE TITLE
Re: Error: ArrayFire Exception (Device out of memory:101)

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#683]
From https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/librispeech/README.md, I ran Resnet CTC training:

<pre>root@3580592f301c:~# wav2letter/build/Train train --flagsfile wav2letter/recipes/models/sota/2019/librispeech/train_am_resnet_ctc.cfg --minloglevel=0 --logtostderr=1
</pre>

and got:

<pre>
...
Falling back to using letters as targets for the unknown word: bui
Falling back to using letters as targets for the unknown word: d&apos;avrigny
Falling back to using letters as targets for the unknown word: d&apos;avrigny
Falling back to using letters as targets for the unknown word: d&apos;avrigny
Falling back to using letters as targets for the unknown word: wildering
Falling back to using letters as targets for the unknown word: quinci
Falling back to using letters as targets for the unknown word: impara
I0607 21:13:24.300433   299 W2lListFilesDataset.cpp:141] 2703 files found. 
I0607 21:13:24.300465   299 Utils.cpp:102] Filtered 2703/2703 samples
I0607 21:13:24.300472   299 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 0
I0607 21:13:24.489915   299 W2lListFilesDataset.cpp:141] 2864 files found. 
I0607 21:13:24.489969   299 Utils.cpp:102] Filtered 4/2864 samples
I0607 21:13:24.490177   299 W2lListFilesDataset.cpp:62] Total batches (i.e. iters): 715
I0607 21:13:24.497853   299 Train.cpp:566] Shuffling trainset
I0607 21:13:24.502732   299 Train.cpp:573] Epoch 1 started!
Unable to allocate memory with native alloc for size 50331648 bytes with error &apos;ArrayFire Exception (Device out of memory:101):
ArrayFire error: 
In function fl::MemoryManagerInstaller::MemoryManagerInstaller(std::shared_ptr&lt;fl::MemoryManagerAdapter&gt;)::&lt;lambda(size_t)&gt;
In file /root/flashlight/flashlight/memory/MemoryManagerInstaller.cpp:178&apos;terminate called after throwing an instance of &apos;af::exception&apos;
  what():  ArrayFire Exception (Unknown error:999):

In function T* af::array::device() const [with T = void]
In file src/api/cpp/array.cpp:1024
*** Aborted at 1591564406 (unix time) try &quot;date -d @1591564406&quot; if you are using GNU date ***
PC: @     0x7f07ea4b5e97 gsignal
*** SIGABRT (@0x12b) received by PID 299 (TID 0x7f082fd85380) from PID 299; stack trace: ***
    @     0x7f082809b890 (unknown)
    @     0x7f07ea4b5e97 gsignal
    @     0x7f07ea4b7801 abort
    @     0x7f07eaeaa957 (unknown)
    @     0x7f07eaeb0ab6 (unknown)
    @     0x7f07eaeb0af1 std::terminate()
    @     0x7f07eaeb0d24 __cxa_throw
    @     0x7f080b105728 af::array::device&lt;&gt;()
    @     0x55d52ae5390c fl::DevicePtr::DevicePtr()
    @     0x55d52aecdd6d fl::conv2d()
    @     0x55d52ae7ce31 fl::Conv2D::forward()
    @     0x55d52ae8e7de fl::UnaryModule::forward()
    @     0x55d52aec17e1 fl::Residual::forward()
    @     0x55d52aec193d fl::Residual::forward()
    @     0x55d52ae7bd7a fl::Sequential::forward()
    @     0x55d52abbeaf3 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl
    @     0x55d52ab595f8 main
    @     0x7f07ea498b97 __libc_start_main
    @     0x55d52abb936a _start
Aborted (core dumped)
</pre>

I noticed that @kfmn, @vineelpratap, @sanjaykasturia and @jacobkahn etc. have talked about
similar issues at https://github.com/facebookresearch/wav2letter/issues/133, and https://github.com/facebookresearch/wav2letter/issues/248. May I ask whether there is a way to take care of this? For example, any wav2letter models (other than E2E Speech Recognition on Librispeech-Clean Dataset https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean), which might be good to transcribe a telephony audio, are smaller than this? BTW, I just have 1 GPU, and

![image](https://user-images.githubusercontent.com/61134984/83980698-63926a00-a8dd-11ea-8257-de7febc02f79.png)

Thank you!

**Comment by lunixbochs** [comment]
Reduce your batch size. 4GB is very small amount of GPU RAM.

**Comment by ML6634** [comment]
Thank @lunixbochs for the quick response! The batchsize was 4, I reduced it to 3, 2, and even 1, I still got the same error. Anybody has any further comments? Thank you!

**Comment by lunixbochs** [comment]
4GB of ram might not be enough to train that model. Try a smaller model, like the wsjarch model, or streaming convnets.

**Comment by ML6634** [comment]
Is the wsjarch model a wav2letter model or not? Any link for that?
For streaming_convnets model, https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/streaming_convnets, any restrictions to use it for transcribing a telephony audio? Thank you!

**Comment by ML6634** [comment]
I found wsj:

https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/wsj

**Comment by ML6634** [comment]
By https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/streaming_convnets/librispeech, it sounds that a streaming_convnets acoustic model is trained on 32 GPUs. Unfortunately, I only have 1 GPU. However, it seems that a wsj acoustic model is trained on 1 GPU. Does anybody know any other wav2letter models which are small, only need one GPU, and might be good for transcribing a telephony audio? Thank you!

**Comment by ML6634** [comment]
Or, does @tlikhomanenko or any other experts have any comment about this? Thank you!

**Comment by jacobkahn** [comment]
@ML6634 — you can train any of the models in our recipes with fewer GPUs, but training will take longer (you'll have less parallelism and will have to use a smaller batch size) - convergence may also be slightly different.

The steps listed in that recipe are for exact reproduction of our results - you should be able to get pretty close in your setup. Make sure to change the batch size as @lunixbochs mentioned such that you don't get out of memory issues. Outside of that, everything should work relatively well.

**Comment by ML6634** [comment]
I appreciate the helpful comments from @jacobkahn! May I ask you whether there is still a way for me to use Resnet CTC training? As I mentioned in the top, I reduced the batchsize from 4 to 3, 2, and even 1, each time it still produced the same error.

I am also trying some other models.

**Comment by tlikhomanenko** [comment]
@ML6634 

If you are trying to use the arch for your dataset (not reproducing Librispeech results) then just try to reduce number of layers in the CTC resnet arch to make it fit the memory. However, you will need to tune other params, like optimizer, lr, etc. 

So first thing to try: use the same params as we have in the recipe, just reduce number of layers or reduce conv feature map values, then tune other params to improve the quality.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the further help! So far, I have not reached the step to use my data set yet. Now I would like to first run the model using the data downloaded by the instructions of the FB link. I need to take care of the bug: "Device out of memory".

May I ask how to use arch? In addition, I found lr in train_am_resnet_ctc.cfg. Where are params:  number of layers, conv feature map values, and optimizer? I am new to this model.

Thank you!

**Comment by tlikhomanenko** [comment]
The doc on arch file is here https://github.com/facebookresearch/wav2letter/wiki/Writing-architecture-files, in the config we specify `--archdir` and `--arch` which defines the network architecture. Examples of archs for sota models are here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019/am_arch.

Default optimizer is sgd defined by flag `netoptim` and there is also the `critoptim` in case of seq2seq models (default sgd). Other parameters of optimizers can be found in https://github.com/facebookresearch/wav2letter/blob/master/src/common/Defines.cpp where all cmd flags are defined here for more details.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the continuous help! The --archdir has been specified by the appropriate path in my config. So, the arch is used. Thank you for the info about the arch!

I found netoptim in Defines.cpp in the link you gave. How can I change its value? You suggested that I need to first reduce number of layers or reduce conv feature map values. Is am_decoder_tr_layers in the same cpp file the number of layers which you mentioned? May I ask how to change its value? I still could not find conv feature map.

Right now I have around 177 GB available:

![image](https://user-images.githubusercontent.com/61134984/84479752-1144a680-ac59-11ea-81f7-165ee252ec78.png)

I hope that this much space left would not cause the Error: ArrayFire Exception (Device out of memory:101). Thank you!

**Comment by ML6634** [comment]
Or, any other way for me to run the Resnet CTC model? I run this on Ubuntu installed on an external hard drive with 500 GB. Thank you!

**Comment by tlikhomanenko** [comment]
@ML6634 
To change optimizer the possible names are here https://github.com/facebookresearch/wav2letter/blob/master/src/common/Defines.h#L92 like `--netoptim=sgd`.

Reduce at first number of layers. 

`am_decoder_tr_layers` is related to `decoder`-network of seq2seq model while you are trying to train CTC model, so this is parameter is not related to CTC training. You need to go to arch file and reduce number of layers there (arch file describes the network structure). Please read this https://github.com/facebookresearch/wav2letter/wiki/Writing-architecture-files.

About you disk capacity - it doesn't matter. What are you interesting is GPU memory and RAM memory.

**Comment by tlikhomanenko** [comment]
Closing as we solved the main issue here. Feel free to ask further if some support is needed

**Comment by xiaosdawn** [comment]
Hi, @tlikhomanenko I ran CTC training https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean, and got 
```
Unable to allocate memory with native alloc for size 2097152 bytes with error 'ArrayFire Exception (Driver not available or incompatible:102):
ArrayFire error:
In function fl::MemoryManagerInstaller::MemoryManagerInstaller(std::shared_ptr<fl::MemoryManagerAdapter>)::<lambda(size_t)>
In file /data/Dawn/wav2letter/flashlight/flashlight/memory/MemoryManagerInstaller.cpp:191'terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Driver not available or incompatible:102):
In function virtual void* MemoryManagerFunctionWrapper::alloc(bool, unsigned int, dim_t*, unsigned int)
In file src/api/c/memory.cpp:738


 0# 0x00007F65E2B5B091 in /usr/local/lib/libafcuda.so.3
 1# 0x00007F65E23DF2A6 in /usr/local/lib/libafcuda.so.3
 2# 0x00007F65E1E7F4AD in /usr/local/lib/libafcuda.so.3
 3# 0x00007F65E1E7F579 in /usr/local/lib/libafcuda.so.3
 4# 0x00007F65E4509CED in /usr/local/lib/libafcuda.so.3
 5# 0x00007F65E2BB0B2B in /usr/local/lib/libafcuda.so.3
 6# af_randu in /usr/local/lib/libafcuda.so.3
 7# af::randu(af::dim4 const&, af_dtype) in /usr/local/lib/libafcuda.so.3
 8# 0x0000564187D5821D in /data/Dawn/wav2letter/build/Train
 9# 0x0000564187D68EAB in /data/Dawn/wav2letter/build/Train
10# 0x0000564187D690E4 in /data/Dawn/wav2letter/build/Train
11# 0x0000564187C992EB in /data/Dawn/wav2letter/build/Train
12# 0x0000564187C9B015 in /data/Dawn/wav2letter/build/Train
13# 0x0000564187A3894C in /data/Dawn/wav2letter/build/Train
14#
*** Aborted at 1594954117 (unix time) try "date -d @1594954117" if you are using GNU date ***
PC: @     0x7f65bcf04f47 gsignal
*** SIGABRT (@0x3e000009b57) received by PID 39767 (TID 0x7f66009538c0) from PID 39767; stack trace: ***
    @     0x7f65be4cf8a0 (unknown)
    @     0x7f65bcf04f47 gsignal
    @     0x7f65bcf068b1 abort
    @     0x7f65bdb46257 (unknown)
    @     0x7f65bdb51606 (unknown)
    @     0x7f65bdb51671 std::terminate()
    @     0x7f65bdb51905 __cxa_throw
    @     0x7f65e2da26ac af::randu()
    @     0x564187d5821d fl::kaimingUniform()
    @     0x564187d68eab fl::Conv2D::initialize()
    @     0x564187d690e4 fl::Conv2D::Conv2D()
    @     0x564187c992eb (anonymous namespace)::parseLines()
    @     0x564187c9b015 w2l::createW2lSeqModule()
    @     0x564187a3894c main
    @     0x7f65bcee7b97 __libc_start_main
    @     0x564187a9ce9a _start
Aborted (core dumped)
```
It sames like @ML6634 asked above. But some difference : "Driver not available or incompatible:102". I had checked the _arrayfire_ , and tested it works well. 
BTW, I have 8*V100, and:
![image](https://user-images.githubusercontent.com/26700262/87743595-de736c80-c81b-11ea-8fdd-41e4998f90cc.png)
I reduced the batchsize from 4 to 3, 2, and even 1. It had the same error. The _Train.cfg_ as:
![image](https://user-images.githubusercontent.com/26700262/87743920-b0daf300-c81c-11ea-8f1e-c56b16d25ec1.png)
Then_ I reduced number of layers. It had the same error. The _network.arch_ as:
![image](https://user-images.githubusercontent.com/26700262/87743993-dc5ddd80-c81c-11ea-9399-8a64dbcee2a9.png)
Can anyone help me or some suggestions? THX.

**Comment by tlikhomanenko** [comment]
@xiaosdawn can you confirm that you are using latest flashilght and wav2letter commits? and what is your arrayfire verison?

cc @jacobkahn @avidov any idea on this?

**Comment by xiaosdawn** [comment]
@tlikhomanenko Hi, thank you for the qucikly reply. 
I installed ArrayFire-v3.7.1-1_Linux_x86_64 on ubuntu 18.04, and  commit commit 18a1dfe4b22e875e5fd1f875f7bf9ec88a5616cd for wav2letter.

**Comment by tlikhomanenko** [comment]
Nope, we don't have any restrictions. Could you check that you can train other things on 0-GPU (that you don't have problem with the 0-card itself, so that it is not broken)?

**Comment by xiaosdawn** [comment]
0-GPU card is fine when training other things. My first comment showed an image, where a python script was running. 
When the first error disappeared, I ran the Train, and got 
![image](https://user-images.githubusercontent.com/26700262/88002079-3b309900-cb34-11ea-8d9b-67bfbe022806.png)
So is this a version problem?  I installed ArrayFire-v3.7.1-1_Linux_x86_64 on ubuntu 18.04, and commit 18a1dfe for wav2letter. If the version is not appropriate, please let me know. THX.

**Comment by xiaosdawn** [comment]
BTW, I tried Building Running with Docker. [https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker](url) and got:
![image](https://user-images.githubusercontent.com/26700262/88020566-8e1f4600-cb5e-11ea-8fad-de5a42522d6c.png)
The same as above phenomenon. @tlikhomanenko

**Comment by tlikhomanenko** [comment]
@xiaosdawn 

Memory manager is just information what is happening with your memory during training. This is normal - we recently added new default memory manager and printing the stats. Could you try to run training on 1 GPU only on 0-th? Does it crash as you reported before with `  what():  ArrayFire Exception (Driver not available or incompatible:102):
In function virtual void* MemoryManagerFunctionWrapper::alloc(bool, unsigned int, dim_t*, unsigned int)
In file src/api/c/memory.cpp:738`?

**Comment by xiaosdawn** [comment]
Thanks for your continue help. The memory information is normal. and there is no other information directly ending the training. Then I checked logs and found logs only contained information about the first epoch :
![image](https://user-images.githubusercontent.com/26700262/88145882-b4f87d80-cc2d-11ea-9def-d6301c9481be.png)
![image](https://user-images.githubusercontent.com/26700262/88145990-d9545a00-cc2d-11ea-8c37-0781ab17d86e.png)
BTW,  `--iter=2`.
I don't know how to run training on a specific GPU for now. Is there any instruction?
Forgive me for having so many questions. Thanks a lot.

**Comment by tlikhomanenko** [comment]
`--iter=2` means to run only 2 updates (not epochs), so set this var to be something large to have longer training. To run on specific GPUs you should use `export CUDA_VISIBLE_DEVICES=0`, in this case if you run training on 1 gpu it will be running on 0-th GPU. If you want to train for example on 4 from 5-th to 8-th, then use `export CUDA_VISIBLE_DEVICES=5,6,7,8`.

**Comment by xiaosdawn** [comment]
@tlikhomanenko Thank you so much. I used `export CUDA_VISIBLE_DEVICES=7` running on 8-th GPU. It's OK. 
![image](https://user-images.githubusercontent.com/26700262/88254341-9d7dcb00-cce7-11ea-88f6-23623b03aef7.png)
Then, I used `export CUDA_VISIBLE_DEVICES=0` running on 1-th GPU. It crashed as my reported before with what(): ArrayFire Exception (Driver not available or incompatible:102): In function virtual void* MemoryManagerFunctionWrapper::alloc(bool, unsigned int, dim_t*, unsigned int) In file src/api/c/memory.cpp:738?

BTW, how can I set `epochs`?  Thanks a lot.

**Comment by xiaosdawn** [comment]
Hi, @tlikhomanenko I used debug mode to run training, and got:
![image](https://user-images.githubusercontent.com/26700262/88273492-d9775700-cd0c-11ea-947a-2c10a75d84c0.png)
I built runing with docker. BTW, I synchronized the lastest version for wav2letter, then used `export CUDA_VISIBLE_DEVICES=0`  and `export CUDA_VISIBLE_DEVICES=7` respectively.  The error as my reported before just gone. 
From debug details, training ended normally. But `epochs` still 1. How can I set this? Looking forward to your replay. THX.

**Comment by tlikhomanenko** [comment]
just set `--iter=100000000`, we don't have flags for number of epochs anymore, only number of updates. But you can check how many samples you have in the train list, what is your total batch size and then calculate how many updates in the epoch you will have. So you need to multiply this value to the number of epochs you want to run and set it to `--iter` param.

Glad to here that with latest version the error didn't occur.

**Comment by xiaosdawn** [comment]
Thank you so much. @tlikhomanenko  I got it.

**Comment by ML6634** [comment]
Anybody has ideas about the following bug? Thanks.
<pre>wav2letter/build/Train train --flagsfile wav2letter/recipes/models/sota/2019/librispeech/train_am_resnet_ctc.cfg --minloglevel=0 --logtostderr=1
terminate called after throwing an instance of &apos;af::exception&apos;
  what():  ArrayFire Exception (Runtime error :103):
ArrayFire error: 
In function void fl::MemoryManagerInstaller::setAsMemoryManager()
In file /root/flashlight/flashlight/memory/MemoryManagerInstaller.cpp:218
Aborted (core dumped)
</pre>

**Comment by tlikhomanenko** [comment]
this is the only log you see on the screen? @ML6634

**Comment by ML6634** [comment]
Yes.

**Comment by tlikhomanenko** [comment]
cc @avidov

**Comment by ML6634** [comment]
Thank @tlikhomanenko. I did not get this bug when I trained it before. Recently, I downloaded CUDA and cuDNN etc. for Deepspeech2. I am not sure whether it might bother. However, I run both wav2letter and Deepspecch2 via Docker.

**Comment by ML6634** [comment]
For TDS CTC training, I got the same error.  However, it went though about two weeks ago. The only change I made is that I downloaded things (such as CUDA, cuDNN etc.) for Deepspeech2.
@tlikhomanenko @avidov

**Comment by tlikhomanenko** [comment]
could you test trained model with test.cpp in your updated env if it gives the same error?

**Comment by gauravgund** [comment]
@tlikhomanenko: Are there any light-weight models to do fine-tuning with 1 gpu? I tried reducing the batch-size but still the error is persistant! Arrayfire version: ArrayFire-v3.7.1-1_Linux_x86_64.sh

**Comment by tlikhomanenko** [comment]
Please have a look at the latest models we released (you need latest version of flashlight for it to use) https://github.com/facebookresearch/wav2letter/tree/master/recipes/rasr and recipe to ft https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr/tutorial (see finetuning)
