### ISSUE TITLE
Error while loading: ArrayFire Exception (Internal error:998)

### ISSUE THREAD

**Issue by GowthamS07** [facebookresearch/wav2letter#684]
I ran the following code to run beam search decoding
`root@a81f3d7ac263:/home# mpirun --allow-run-as-root -n 4 /root/wav2letter/build/Test --flagsfile /home/decoder.cfg`
I also tried using `/root/wav2letter/build/Test --flagsfile /home/decoder.cfg` without `mpirun` but I get the following error:
```
E0609 06:56:09.337702   174 Serial.h:74] Error while loading: ArrayFire Exception (Internal error:998):
In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/array.cpp:127

In function void {anonymous}::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:95
E0609 06:56:09.337707   172 Serial.h:74] Error while loading: ArrayFire Exception (Internal error:998):
In function af_err af_create_handle(void**, unsigned int, const dim_t*, af_dtype)
In file src/api/c/array.cpp:127
```
Can anyone please point out what kind of internal error is occuring here ??

**Comment by tlikhomanenko** [comment]
@GowthamS07 

could you post the full log you see on the screen? Do the test work for you from flashlight and wav2letter?

**Comment by lunixbochs** [comment]
https://github.com/arrayfire/arrayfire/issues/1258

Is this a GPU build of wav2letter? Do you have a GPU? Does nvidia-smi show it?

**Comment by GowthamS07** [comment]
@tlikhomanenko thank you for the response, @lunixbochs yes it is a GPU build, nvidia-smi shows it, the problem is solved, It was due to lack of free space on GPU, thank you for the support and apologize for the late reply.

**Comment by tlikhomanenko** [comment]
@GowthamS07 

Thanks for your comments on the source of the error!
