### ISSUE TITLE
Difference between "acoustic model dev-clean" and "acoustic model dev-other"

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#685]
Hello,

I wanted to understand please the difference between "acoustic model dev-clean" and "acoustic model dev-other" in your pretrained models.

Are these models from the same training process and only optimal model was selected according to different validation sets?

Thanks,
Alexander.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

Both models are trained in the same training process: during training we evaluate current checkpoint separately on dev-other and dev-clean and overwrite the best of each if current checkpoint improves WER the particular dev set. So dev-clean and dev-other models could be the same snapshots or different snapshots of the same training run.


> Are these models from the same training process and only optimal model was selected according to different validation sets?

Thus this is correct.
