### ISSUE TITLE
problem in docker inference 

### ISSUE THREAD

**Issue by vigneshmj1997** [facebookresearch/wav2letter#686]
cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_BUILD_LIBRARIES_ONLY=ON -DW2L_LIBRARIES_USE_CUDA=OFF -DW2L_BUILD_INFERENCE=ON 
after running of the command 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Checking for [openblas]
-- Checking for [cblas]
-- Checking for [blas]
CMake Error at cmake/FindCBLAS.cmake:334 (MESSAGE):
  CBLAS library not found.  Please specify library location
Call Stack (most recent call first):
  src/libraries/feature/CMakeLists.txt:10 (find_package)
 i am getting this error

**Comment by tlikhomanenko** [comment]
are you running this in the docker container? everything should be pre-built there.

**Comment by vigneshmj1997** [comment]
yes i am running a this in a docker container , as said in documentation

**Comment by tlikhomanenko** [comment]
@avidov can you check what is the problem? On the github action everything works, so build looks fine.

**Comment by vigneshmj1997** [comment]
i tries it multiples times not i created docker image my self and its working , any way thanks for u time :)

**Comment by avidov** [comment]
Please try to remove the build directory and follow:
https://github.com/facebookresearch/wav2letter/blob/739e7f9a81fe0caaca45af52680ce474d5ea59f8/Dockerfile-Inference#L18
