### ISSUE TITLE
shape of emission set seem not right?

### ISSUE THREAD

**Issue by trangtv57** [facebookresearch/wav2letter#688]
I train model streaming conv and using ./Test for get emission set. I have used python code for loading output of emission sample:
`T, N = numpy.frombuffer(raw_data[-8:], dtype=numpy.int32)`
this code for get T, and N
and my output T=30, and N=1286 for my emission of file audio test1.bin

`emissions = numpy.frombuffer(raw_data[:T * (N + 1) * 4], dtype=numpy.float32)`
and output shape of emisssions is (38601,).

With my knowledge emission is output of AM with shape T*N (time step and each probability of N token in each time step) before feed to criterion like CTC. So I don't know why output shape of emission: 38601 != 30 *1286, and I try test in another audio emission and have the same result, all of this need add 21 to equal length of emission?
Pls correct me if i am wrong. thank you!

**Comment by avidov** [comment]
cc @vineelpratap @tlikhomanenko

**Comment by tlikhomanenko** [comment]
@trangtv57,
I guess your shape is `38610` not `38601`. 
Here should be `emissions = numpy.frombuffer(raw_data[:T * N * 4], dtype=numpy.float32)`, thanks for pointing, will leave comment here https://github.com/facebookresearch/wav2letter/issues/614 on this fix too.
