### ISSUE TITLE
 kenlmutillib not found

### ISSUE THREAD

**Issue by minhson3012** [facebookresearch/wav2letter#69]
Hello when I try to make rocks/beamer-scm-1.rockspec using the command
`cd beamer && KENLM_INC=$HOME/kenlm luarocks make rocks/beamer-scm-1.rockspec && cd ..`
I get this error:

> -- Using kenlm library /home/tung/usr/lib/libkenlm.a
> -- Using kenlm include path /home/tung/kenlm
> -- Found Torch7 in /home/tung/torch/install
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> kenlmutillib
>     linked by target "beamer" in directory /home/tung/wav2letter/beamer
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/tung/wav2letter/beamer/build.luarocks/CMakeFiles/CMakeOutput.log".
> 
> Error: Build error: Failed cmake.

**Comment by bolt163** [comment]
you  need to export the  kenlm releated lib path to the LD_LIBRARY_PATH etc.   env  variables, and source it
