### ISSUE TITLE
lmweight and eosscore

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#691]
Hello,

Could you please explain how lmweight and eosscore parameters are trained.

Thanks,
AlexG.

**Comment by avidov** [comment]
cc @tlikhomanenko

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski,

When your AM model is trained we do optimization of beam-search decoder. We take the dev set and with random search (randomly sample lmweight and eosscore) for each generated set of params we run decoder and pick up parameters for which WER is minimal. Check on section A.1 (appendix) in the https://arxiv.org/pdf/1911.08460.pdf.
