### ISSUE TITLE
Comparison of letter ans word-pieces approaches

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#694]
Hello,

I would like to understand how better word-pieces approach is better than letter approach. Is there some article describing this improvement?

Thanks,
AlexG.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

I didn't see the extensive comparison of models trained with letters and word-pieces. So far you can conclude that word-pieces possibly better from recent papers on SOTA where people use word-pieces. Maybe we just need to have better tunning for letter based models. And this also depends on the language itself (there are Thai, etc. for example where you can use only letter based systems).
