### ISSUE TITLE
Using of decoder lexicon in word-pieces system

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#695]
Hello,

It is not clear why do we used decoder lexicon. Once we have word-pieces system, I understand that we can work without lexicon. Am I wrong?

Thanks,
Alexander.

**Comment by AlexandderGorodetski** [comment]
I see that in my decoder configuration file --uselexicon=false. Does it mean that decoder lexicon is not used. Is this correct?

**Comment by tlikhomanenko** [comment]
Hi @AlexandderGorodetski,

We support both cases lexicon and lexicon free, correct `uselexicon` flag is for this purpose (`uselexicon=false` will not use lexicon for decoding). In case of lexicon the lm model should be word-based, in case of lexicon-free the lm model should be token-based (the same tokens as for AM). Lexicon-free is good in the sense that it is able to infer out-of-vocabulary (OOV) words, in lexicon-based we will never infer OOV. In our previous study we compare lexicon-based and lexicon free for letter-based AM (they are close, but lexicon-free is able to recognize OOV, https://arxiv.org/abs/1904.04479). 

Often we use lexicon free decoding if we have s2s model trained on word-pieces.
