### ISSUE TITLE
TED evaluations

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#696]
When I am evaluating TEDLium using LibriSpeech+LirbriVox transformer model without LM I got WER=11.2%.

I see following problems:

|T|: after it's been overcooked
|P|: after it's been over cooked

|T|: the plant biomass 
|P|: the plant bio mass

|T|: monocultures chemicals to soil chicken to fish
|P|: mono cultures chemicals to soil chicken to fish

Do you think that LM will solve some of these problems. What LM do you recommend to train, word-based or wp-based?

Thanks,
Alexander.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

Yep, definitely this type of errors can be solved with LM. Does this s2s model or CTC? For CTC it is better to train word-based, for s2s - word-pieces. You can start with training n-gram LM on TEDLium lm data (they provide lm corpus for this purpose).
