### ISSUE TITLE
LibriSpeech and LibriVox training times

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#697]
Hello,

I have a question about LibriSpeech and LibriVox training times.

In one of your previous answers you wrote to me that training time of LibriSpeech (1K hours) is about 3days. And training time of LibriVox (50K hours) is about 14 days. 

Because LibriVox is 50 times larger than LibriSpeech I would expect that LibriVox training would take ~150 days.

Am I missing something?

Maybe you started your LibriVox training from existing LibriSpeech model? 

Thank you so much,
Alexander.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 
LibriVox models trained from scratch (so no training continue from Librispeech pre-training). 

Yes, we have 50 times more data but there is no rule like N times more data N times more training. You train to full convergence (this depends mainly on model capacity/complexity). You can simpler consider one-layer MLP, whose capacity is very small and starting from some amount of data you will not see any gain during training with more updates. 

For LibriVox models it didn't fully converge for resnet and TDS models (for CTC), while for Transformer it converged. So we still can have gain for resnet and TDS for longer training, but we didn't train further.
