### ISSUE TITLE
word-piece n_gram LM

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#699]
Hello,

Could you please guide me how to train word-piece N-gram LM.

Could you please explain the idea behind the algorithm. Do you select randomly one of ten word-piece representations of a word and in this way you can create a sentence at word-piece level?

I looked into file train_ngram_lms.sh and I did not find there this staff.

Thanks a lot,
AlexG

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

Example of training for 10k word-pieces you can find here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019/lm in README.md. There is script which converts input text into word-pieces sequences: here we use the same word-piece model which is constructed on train transcriptions and then take only best split on word-pieces for each word https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/lm/prepare_wp_data.py#L46.

In the same README also you can find details on how to run kenlm training.
