### ISSUE TITLE
Using of TransformerSeq2Seq word-piece model word-based arpabo

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#701]
Hello,

I am trying to use TransformerSeq2Seq word-piece acoustic model (pretrained LibriSpeech+LibriVox model) with my aprabo file which is word based.

It seems that something is going wrong, because decoding results are completely wrong.

Moreover I receive following message 

I0617 15:26:22.573542   236 Decode.cpp:480] [Decoder] LexiconSeq2Seq decoder with token-LM loaded in thread: 0

It seems that the decoder assumes that I supplied word-piece based arpabo. Is there some flag where I can say that the arpabo is word based.

I use --uselexicon=true as was recommended before, and I have created updated lexicon file as was recommended before.

Thanks,
Alexander.

**Comment by AlexandderGorodetski** [comment]
To solve upper mentioned problem

--decodertype=tkn 

should be replaced with

--decodertype=wrd

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

Yep, you found correct flag to change. FYI here is full doc https://github.com/facebookresearch/wav2letter/wiki/Beam-Search-Decoder on decoder side with all use-cases and flags description. Let me know if this doc can be improved.
