### ISSUE TITLE
DecoderState comparison

### ISSUE THREAD

**Issue by Kuronogard** [facebookresearch/wav2letter#705]
Hi, thank you for the great job that you are doing with this project and thank you for making it available for the public.

I was studying the code for the _LexiconDecoder_ and run into the function _compareNoScoreStates()_, that compares two _decoderState_ objects.

I don't quite understand, by reading this function, what it means that a state is _more_ (or _less_) than other state... For example, the first comparison performed inside the function is between both lmState attributes, but this function (as defined in _lm/LM.h_) compares the pointers, which is _unspecified_ (for < or >) in standard C++ (as far as I know). I could not find any definition of _operator<_ or _operator>_ for these classes in the code, so I am kind of stuck here...

Please, can you explain how decoder states are compared and what it means that a state is more (or less) than another?

**Comment by tlikhomanenko** [comment]
Purpose of states comparison is to establish if we have exactly the same state (you can think in simple case that you have the same transcription prefix). If they are the same we merge these states to one (= setting score to the max of them or logadd and staying this final state in the beam, so thus the search is effective, especially in CTC case).

We use this comparison function in the sort algorithm and for it we need to have proper comparison. For us only matters if pointers are the same or not, comparison </> we do only for the proper function in sorting, for us it doesn't matter. Comparison </> on pointers is just comparison of addresses numbers.

**Comment by Kuronogard** [comment]
Ok, thank you, it's totally clear now.
