### ISSUE TITLE
Is it possible to run the training on AMD Radeon Graphics Cards ?

### ISSUE THREAD

**Issue by therahulprasad** [facebookresearch/wav2letter#708]
Hi, I have a AMD Radeon VII Graphics Card. Is it possible to run training on it ?

**Comment by tlikhomanenko** [comment]
cc @jacobkahn @avidov

**Comment by therahulprasad** [comment]
Please help.

**Comment by jacobkahn** [comment]
@therahulprasad — we unfortunately don't have an OpenCL backend just yet, but we're actually pretty close to having this working, although it might be a month or two until. If your model doesn't have Convolutions or RNN layers, everything should work as is.

That aside, would you be interested in contributing to the remaining primitives we need for AMD support? We have these partially implemented but need someone to see them through.

**Comment by therahulprasad** [comment]
Sure, Please let me know the branch name.

**Comment by tlikhomanenko** [comment]
@therahulprasad please check recent flashlight https://github.com/facebookresearch/flashlight where we improved CPU backend with onednn and there are developments on opencl https://github.com/facebookresearch/flashlight/pulls?q=opencl
