### ISSUE TITLE
Using of points in the training data and in the dictionary

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#713]
Hello,

In my training data there are many acronyms, e.g. AAPI, AAPL, AAR, etc. During my text normalization process I convert every acronym to the following format a.a.p.i, a.a.p.l, a.a.r., etc. So that the acoustic model will able to learn that points inside a word actually represents spelling of them.

I wanted to check if "." is not reserved symbol and if I can use it in the training data and in the dictionary or should I replace it to some another UTF-8 symbol like you did it with "_" symbol.

Thanks,
Alexander.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

It is fine to use "." as a token, we did the same for example for WSJ dataset. Feel free just to add to the tokens set.
