### ISSUE TITLE
last step decode outputs

### ISSUE THREAD

**Issue by innarid** [facebookresearch/wav2letter#714]
Hi!
I'm using python bindings and LexiconDecoder. I need to get N best results from last step of decoding. Increasing of beam threshold influences all steps and makes decoding slower. Is there any way to change beam threshold only at last step of decoding or to get all predictions from last step?

**Comment by tlikhomanenko** [comment]
Beam threshold is more about pruning and restricting the search. You need to increase the `beamsize` if you want to have more hypothesis at each step and at the end. Result of decoding contains all hypotheses at the end, not just the best one. Check on the example here https://github.com/facebookresearch/wav2letter/blob/master/bindings/python/examples/decoder_example.py#L190, and we print top-5 https://github.com/facebookresearch/wav2letter/blob/master/bindings/python/examples/decoder_example.py#L192 but you can print all of them.
