### ISSUE TITLE
Arpbabo building using kenlm

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#715]
Hello,

I have just built 6-gram word-piece arpabo file using kenlm. To convert my text data to word-pieces I used librispeech model which should contain 10,000 tokens. I got following n-grams.

ngram 1=33520
ngram 2=7920930
ngram 3=71510723
ngram 4=190283731
ngram 5=54897127
ngram 6=13476834

My question is how I got ngram1=33520 when it is supposed that ngram1 will be 10000.

Thanks,
Alexander.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

Yep, number of ngrams should be 10k if you have the same letters in your data as we have in the Librispeech (a-z, '). If for example you have in the data "Hello" (uppercase letter), then sentencepiece model will convert it to "_ H el lo" for example, so thus all unknown letters will be just separate tokens.  Check what letters you have in the data, possibly some other letters from other languages, numbers, uppercase letters, etc.
