### ISSUE TITLE
issue while running test

### ISSUE THREAD

**Issue by vigneshmj1997** [facebookresearch/wav2letter#717]
./Test: error while loading shared libraries: libmkl_rt.so: cannot open shared object file: No such file or directory

i happed to delete wav2letter folder by mistake so i donlowaded wav2letter from git and ran cmake , now when in run test i am getting following error

**Comment by tlikhomanenko** [comment]
@vigneshmj1997 did you successfully build the w2l? What about w2l tests? What backend are you using?

**Comment by vigneshmj1997** [comment]
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_IBRARY_PATH

i for got to run this sry its my mistake @tlikhomanenko

**Comment by tlikhomanenko** [comment]
Sure, no problem! Happy that you solved it.
