### ISSUE TITLE
portable model serialization format

### ISSUE THREAD

**Issue by lunixbochs** [facebookresearch/wav2letter#718]
I'm working on a minimal binary format for serializing wav2letter models designed to be more portable than the current Cereal format and intended to work with a very minimal parser (Cereal isn't really usable outside of C++ afaik and doesn't package stuff like tokens).

Basically, I want to:
- Ship only one kind of self-contained model file on https://talonvoice.com/research/
- Package stuff like sentencepiece models and tokens.txt inside the model instead of shipping tarballs
- Make it easy to load the same model from both e.g. a Pytorch or wav2letter inference frontend

Goals:
- Can be directly loaded by both wav2letter++ and the Inference frontend
- Can be converted to/from a "real" wav2letter model
- A single file can be used for anything you might need to do with an acoustic model - that means tokens.txt and sentencepiece model files should also be stored in here
- Extremely minimal code required to read/write the format
- An importer can be easily written for something like Pytorch or Tensorflow
- `Model` command in wav2letter repo for converting to/from or editing this format

Basically looking for any feedback, and curious if this is worth standardizing and upstreaming.

This is my current draft:

```
# binary wav2letter model file format
# all numbers are stored as little endian
# floats are stored as IEEE754

short string:
    u8 length
    utf8 value = <length> utf8 bytes

long string:
    u64 length
    utf8 value = <length> utf8 bytes

file start:
    magic = "BW2L"
    u8 version = 1
    short string name
    u64 section_count = number of sections
    for (1 ... <section_count>)
        short string name = name of section (see "common sections")
        short string type = type of section (see "section types")
        long string desc  = section description
        u64 data_length
        bytes data = <data_length> bytes

common sections:
    name="arch"        type="utf8"   - wav2letter arch file
    name="tokens"      type="utf8"   - wav2letter tokens file
    name="flags"       type="keyval" - wav2letter flagsfile
    name="config"      type="keyval" - model config e.g. {name: "streaming convnets",
                                                          description: "example model",
                                                          quantization: "",             # ("", "dynamic", "fp16", "i8", "8x16")
                                                          criterion: "ctc",             # ("", "ctc", "asg", "seq2seq", "transformer")
                                                          feature: "mfsc"}
    name="layers"      type="layers" - model layers
    name="spm"         type="data"   - sentencepiece model data
    name="transitions" type="array"  - ASG transition matrix

section types:
    "utf8"   - section data is interpreted as utf8 text
    "keyval" - section is filled with {short string key, long string val}
    "data"   - section is byte data
    "array":
        short string type ("fp64", "fp32", "fp16", "i64", "i32", "i16", "i8")
        u64 array_len
        data[] = dense array of <type> values, length <array_len>
    "layers":
        u64 layer_count = number of layers
        for (1 ... <layer_count>)
            long_string arch # line defining this layer from wav2letter architecture file
            float scale
            i64 offset
            u64 param_count
            for (1 ... <param_count>)
                array
```

An example model would look something like this:

```
magic = "BW2L"
version = 1
name = "example-asg-conv-glu-small"
sections = [
    [type="arch", data="C2 ..."],
    [type="keyval", name="config", data={criterion = "asg"}],
    [type="tokens", data="a\nb\nc\nd\n..."],
    [type="transitions", data=[0., 0., 0., 0.1, ...]],
    [type="params", data=[
        [type="fp32", data=[0., 0., 0., 0., ...]],
        [type="fp32", data=[0., 0., 0., 0., ...]],
        [type="fp32", data=[0., 0., 0., 0., ...]],
    ],
]
```

**Comment by lunixbochs** [comment]
It's implemented and working for C++ here:
- https://github.com/talonvoice/wav2letter/blob/b2l/w2l/b2l.h
- https://github.com/talonvoice/wav2letter/blob/b2l/w2l/b2l_test.cpp
- https://github.com/talonvoice/wav2letter/blob/b2l/w2l/w2l_forward.cpp#L139
- A more up to date spec is here: https://github.com/talonvoice/wav2letter/blob/b2l/w2l/b2l.txt

I have pytorch importing for this file format working for conv_glu. I'm working on the streaming convnets layers in #744

**Comment by galv** [comment]
@lunixbochs is the pytorch code you have in a state where you feel comfortable sharing it?

**Comment by lunixbochs** [comment]
@galv I'm not sure yet, mind reaching out on the talon slack?

**Comment by lunixbochs** [comment]
As there's been no movement on this I'll just keep doing what I'm doing
