### ISSUE TITLE
question about lrcrit?

### ISSUE THREAD

**Issue by trangtv57** [facebookresearch/wav2letter#721]
I am trying to train model conv_streaming with my dataset, and i have some unclear knowledge about learning rate for criterion?
With some recipes in recipes/models sometime lrcrit=lr, sometime lrcrit less small then lr, and with conv streaming model, lrcrit=0 (with default  in Defines.cpp). 
And can you tell me the impact of each setting, and what is best practice for tuning this parameter?.
Thank you.

**Comment by lunixbochs** [comment]
lrcrit is for criterions like ASG, where it needs to learn bigram probabilities

**Comment by trangtv57** [comment]
so if lrcrit=0, mean CTC no learn and just mean for remove duplicate and get greedy path? And if lrcirt !=0 mean CTC has parameter to learn weighted of each phoneme for get better predict of AM. Does it right? correct me if i'm wrong. Thank you

**Comment by lunixbochs** [comment]
CTC does not use lrcrit afaik

**Comment by vineelpratap** [comment]
CTC doesn't have any learnable parameters. So, `lrcrit` would have no effect.

**Comment by trangtv57** [comment]
thanks you @vineelpratap 
lrcrit would have no effect if i use criterion = CTC, so why this configure 
[transformer_ctc](https://github.com/facebookresearch/wav2letter/blob/7e6189fe65742fbf99f2b6313d57bf7003877377/recipes/models/sota/2019/librispeech/train_am_transformer_ctc.cfg) has setting criterion=CTC and lrcrit=0.4. Sorry if i'm wrong.

**Comment by vineelpratap** [comment]
It could be removed as well. Won't change anything. We will fix it.

**Comment by trangtv57** [comment]
thanks you @vineelpratap
