### ISSUE TITLE
Unknown words in transcription

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#723]
Hello,

In my training data I have many examples of unclear words which are manually transcribed as <unk>.

Can I use this information in train.lst or such utterances should be deleted from the training data?

Same question about <cough>, <lipsmack>, etc.

Thanks,
Alexander.

**Comment by AlexandderGorodetski** [comment]
There were problems in question text processing. I will re-write this question in another thread. Sorry.

**Comment by AlexandderGorodetski** [comment]
Thanks

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

If you are have "." and "," in the token set then on this positions AM will try to learn set "." and ",". If there are symbols in your target transcriptions for which you haven't mapping in the lexicon file they will be mapped to empty - so just skipped. For example if I have "hello he llo" in the lexicon and don't have "world" then original transcription "hello world" will be mapped to "he llo" during training.

Possibly better solution here is to use some token as unk word and add to the lexicon mapping of "," and "." to this unk token.
