### ISSUE TITLE
its just a quesion can we use decoder as a stand alone code or package

### ISSUE THREAD

**Issue by vigneshmj1997** [facebookresearch/wav2letter#725]
i have a already a build a asr model , i have been using parlance ctc decoder [ctcdecoder](https://github.com/parlance/ctcdecode)
which works as a stand alone .Can i used decoder provided here similarly

**Comment by tlikhomanenko** [comment]
There is the doc on decoder and on the python binding of w2l decoder https://github.com/facebookresearch/wav2letter/wiki/Beam-Search-Decoder, https://github.com/facebookresearch/wav2letter/wiki/Python-bindings.
