### ISSUE TITLE
unknown data in training/validation

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#727]
Hello,

In my training data I have many examples of unclear words which are manually transcribed as UNKNOWN

Can I use this information in train.lst or such utterances should be deleted from the training data?

Same question about  COUGH, LIPSMACK , etc.

Thanks,
Alexander.

**Comment by tlikhomanenko** [comment]
Depending on if you want to have in transcription unknown words generation. see also comment https://github.com/facebookresearch/wav2letter/issues/723. 

Possibly it is good to replace all strange words to unk and train with them.
