### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#729]
Hello,

I have prepared environment similar to libri-100 which uses my inhouse data.

During the training I got following error

root@49ff990a1ccc:/media_alex/common/projects/wav2letter/sh/ted_100# ./main.sh
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: compute_ctc_loss, stat = label length >639 is not supported

Does it mean that every training/validation utterance should include less than 639 characters?

Thanks,
Alexander.

**Comment by AlexandderGorodetski** [comment]
Indeed when I've deleted utterances longer than 639 characters, it solved this problem.
In my inhouse data 10% of data is longer than 639 characters. Is it possible to fix this issue, to let's say 2000 characters?

**Comment by tlikhomanenko** [comment]
cc @awni @vineelpratap

**Comment by vineelpratap** [comment]
Hi, it is a limitation of warp-ctc - https://github.com/baidu-research/warp-ctc#known-issues---limitations . 

Strictly speaking, one can modify its code a bit to make it work for longer targets, but we are not looking into it at the moment.
