### ISSUE TITLE
Is there anything wrong with "node->children[idx] = std::make_shared<TrieNode>(idx);" in Trie.cpp ?

### ISSUE THREAD

**Issue by luweishuang** [facebookresearch/wav2letter#732]
I debug ASR with setting "decodeType==tkn and use_lexicon==true". I found with the `node->children[idx] = std::make_shared<TrieNode>(idx);` in src/libraries/decoder/Trie.cpp, the node->labels.size() almost always little than var TrieMaxLabel even I had set kTrieMaxLabel==1. 

       I found with `std::make_shared<TrieNode>(idx)`, it actually created a new TrieNodePtr insteads of using exist one which maybe has been created before. So node->labels in the next several line almost always equal to 1. 
The only situation which `node->labels.size() >= kTrieMaxLabel` is the exactly same indices exists more than once in lexicon.txt which I think is unreasonable.

**Comment by tlikhomanenko** [comment]
This situation occurs when in the lexicon you have words which have the same spelling with tokens, and this situation for real use cases can be often (also appears in the WSJ dataset too). Also this could be for the abbreviations, like you have normal word and then word with all capital letters. We set just some constant on kTrieMaxLabel. kTrieMaxLabel controls max size of words with the same spelling, so if you have more, the rest will be ignored.

Right now I would say the best way is to have only one word for each spelling and resolve the problem on other levels.

**Comment by trangtv57** [comment]
hi @tlikhomanenko,
I think it's my problem, i mention it on #905 , any solution for this, you can give me some suggest, and i can adding code by myself.
