### ISSUE TITLE
error: ‘afSetMemStepSize’ is not a member of ‘fl’

### ISSUE THREAD

**Issue by tumusudheer** [facebookresearch/wav2letter#733]
Hi,

I just checked out and trying to build wave2letter. But getting this error:

```
/home/facebook/wav2letter/wav2letter/recipes/models/local_prior_match/Decode_length_lpm.cpp: In function ‘int main(int, char**)’:
/home/facebook/wav2letter/wav2letter/recipes/models/local_prior_match/Decode_length_lpm.cpp:66:7: error: ‘afSetMemStepSize’ is not a member of ‘fl’
   fl::afSetMemStepSize(FLAGS_memstepsize);

```

This is the latest commit for wave2letter from `git log` 

```
commit 18a1dfe4b22e875e5fd1f875f7bf9ec88a5616cd (HEAD -> master, origin/master, origin/HEAD)
Author: Shai Szulanski <iahs@fb.com>
Date:   Tue Jun 30 19:11:24 2020 -0700

```
And for Flashlight, This is the latest commit 

```
commit c6355207fd91a78026b16cd815c6c49740e8fecf (HEAD -> master, origin/master, origin/HEAD)
Author: Qiantong Xu <qiantong@fb.com>
Date:   Wed Jul 1 15:28:14 2020 -0700
```

`cmake for flashlight: cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA -DCMAKE_INSTALL_PREFIX=flashlight_dist/ -DBUILD_SHARED_LIBS=ON`

Similarly, for wave2letter, cmake command is : `cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CUDA`

There was a similar issue posted [here](https://github.com/facebookresearch/wav2letter/issues/677) But I couldn't resolve the issue by taking latest flashlight,

Thank you

**Comment by tumusudheer** [comment]
If I change

```
-  fl::afSetMemStepSize(FLAGS_memstepsize);
+  af::setMemStepSize(FLAGS_memstepsize);
```

in recipes/models/local_prior_match/Decode_length_lpm.cpp

and 

```
-  fl::afSetMemStepSize(FLAGS_memstepsize);
+  af::setMemStepSize(FLAGS_memstepsize);
```

in recipes/models/local_prior_match/Train_lpm.cpp

Then the build became successful. Not sure if this is the right change? Please let me know. Thank you

**Comment by tlikhomanenko** [comment]
@tumusudheer,

yep this change is fine. However for the recipes we didn't update them for new versions of flashlight and wav2letter, so use new versions for your own risk. 

@an918tw could you provide commits with which one can reproduce the recipe on local prior match?

**Comment by tumusudheer** [comment]
@tlikhomanenko ,

Thank you very much. Do you recommend any particular commit or version of flashlight and wav2letter for the current recipes ?

Thank you

**Comment by an918tw** [comment]
@tumusudheer please try out w2l commit 9e2c69f1962900c5e9ef723ab14047962b4458e2 and fl commit 16d0bf0bf1dfb930b7bb0415260f9e7914f7818c and let us know if there's any other problem. Thanks!
