### ISSUE TITLE
UNK, COUGH and LIPSMACK words

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#735]
Hello,

In my training data I have following non-speech tokens UNK, COUGH, LIPSMACK, etc. How can I inform lexicon creator that this words are atomic and should not be split to word pieces? Can I write these words in CAPITAL and maybe this trick will solve the issue?

Thanks a lot,
Alexander.

**Comment by tlikhomanenko** [comment]
@AlexandderGorodetski 

You need to add them to the tokens set anyway, so just add them to the tokens set and in the lexicon add `UNK UNK` so that it is one token in spelling. You can use capital letters to prevent some intersection with the normal words.
