### ISSUE TITLE
where  to find asg criterion result?

### ISSUE THREAD

**Issue by qzfnihao** [facebookresearch/wav2letter#738]
when i learn asg, i found it can reach better result than ctc.(https://towardsdatascience.com/better-faster-speech-recognition-with-wav2letters-auto-segmentation-criterion-765efd55449)
But in recipes, i cant get any result in asg criterion. 
especially  in sota/2019,  it list ctc/seq2seq with resnet, tds and transformer, but why no asg result? 
Are asg results worse than ctc?

**Comment by vineelpratap** [comment]
Hi, 
 Recently we have been using 10000 sentence piece tokens as modelling units. ASG will be super slow to run for such large vocabulary sizes. So, we have been using CTC and seq2seq for our experiments.

**Comment by tlikhomanenko** [comment]
We used ASG for Lexicon-free paper, recipe is here https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free
