### ISSUE TITLE
Can't get the master branch built

### ISSUE THREAD

**Issue by zhouyong64** [facebookresearch/wav2letter#740]
Having installing all of the dependencies, I just can't get the master branch of wav2letter built in my environment. The error seems like coming from an incompatible c++ compiler. I've tried g++ 4.8.5, 5.4, 7.3.1, all resulting in different kinds of "grammar" like errors. The following is the error when using g++ 7.3.1:

[  5%] Building CXX object CMakeFiles/wav2letter++.dir/src/module/TDSBlock.cpp.o
[  5%] Building CXX object CMakeFiles/wav2letter++.dir/src/module/W2lModule.cpp.o
/root/sw/wav2letter-master/src/module/W2lModule.cpp: In function ‘std::shared_ptr<fl::Module> {anonymous}::parseLines(const std::vector<std::basic_string<char> >&, int, int&)’:
/root/sw/wav2letter-master/src/module/W2lModule.cpp:321:29: error: ‘Swish’ was not declared in this scope
     return std::make_shared<Swish>(beta);
                             ^~~~~
/root/sw/wav2letter-master/src/module/W2lModule.cpp:321:40: error: no matching function for call to ‘make_shared<<expression error> >(double&)’
     return std::make_shared<Swish>(beta);
                                        ^
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/memory:81:0,
                 from /usr/local/include/flashlight/nn/DistributedUtils.h:11,
                 from /usr/local/include/flashlight/nn/nn.h:19,
                 from /usr/local/include/flashlight/contrib/modules/AsymmetricConv1D.h:10,
                 from /usr/local/include/flashlight/contrib/modules/modules.h:11,
                 from /usr/local/include/flashlight/contrib/contrib.h:11,
                 from /root/sw/wav2letter-master/src/module/W2lModule.h:11,
                 from /root/sw/wav2letter-master/src/module/W2lModule.cpp:13:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr.h:703:5: note: candidate: template<class _Tp, class ... _Args> std::shared_ptr<_Tp> std::make_shared(_Args&& ...)
     make_shared(_Args&&... __args)
     ^~~~~~~~~~~
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr.h:703:5: note:   template argument deduction/substitution failed:
/root/sw/wav2letter-master/src/module/W2lModule.cpp:321:40: error: template argument 1 is invalid
     return std::make_shared<Swish>(beta);
                                        ^
[  5%] Building CXX object CMakeFiles/wav2letter++.dir/src/runtime/Data.cpp.o
make[2]: *** [CMakeFiles/wav2letter++.dir/src/module/W2lModule.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/wav2letter++.dir/all] Error 2
make: *** [all] Error 2
 
My questions is, could you give me, for example, a specific branch or tag of wav2letter that's known to be working with a specific version of gcc/g++?

**Comment by zhouyong64** [comment]
The current master branch is bound to fail when compiling since "Swish" is not defined anywhere.

**Comment by tlikhomanenko** [comment]
When you compile latest master of wav2letter make sure you have latest master of flashlight too!
