### ISSUE TITLE
What is the training data used for the pretrained model in the inference framework tutorial?

### ISSUE THREAD

**Issue by unilight** [facebookresearch/wav2letter#743]
Hi, thank you for all the amazing work!
I have been looking into the wav2letter@anywhere tutorial, and I was wondering that for the pretrained model here,
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#download-the-example-trained-models-from-aws-s3
what training data was used to train it? Is it the same as described in Section 4.1 of https://research.fb.com/wp-content/uploads/2020/01/Scaling-up-online-speech-recognition-using-ConvNets.pdf, "1 million utterances (∼13.7K hours) of in-house English videos publicly shared by users"?
Thanks!

**Comment by tlikhomanenko** [comment]
cc @avidov @vineelpratap

**Comment by vineelpratap** [comment]
For the model we have open sourced -  we use LibriSpeech and additional unlabeled datafrom LibriVox through pseudo-labeling as training data.
