### ISSUE TITLE
docker: Error response from daemon: create ~: volume name is too short, names should be at least two alphanumeric characters.

### ISSUE THREAD

**Issue by MyJumperBroke23** [facebookresearch/wav2letter#745]
Hi, I'm trying to run the inference example, but when I run the command 

`sudo docker run --rm -v ~:/root/host/ -it --ipc=host --name w2l -a stdin -a stdout -a stderr wav2letter/wav2letter:inference-latest sh -c "cat /root/host/audio/LibriSpeech/dev-clean/777/126732/777-126732-0070.flac.wav | /root/wav2letter/build/inference/inference/examples/simple_streaming_asr_example --input_files_base_path /root/host/model"`

I get the error

docker: Error response from daemon: create ~: volume name is too short, names should be at least two alphanumeric characters.

running docker -v gives me 

`Docker version 19.03.8, build afacb8b`

**Comment by tlikhomanenko** [comment]
@MyJumperBroke23 

could you try specify here  `~:/root/host/` the full path to your home dir instead of `~`?

**Comment by MyJumperBroke23** [comment]
@tlikhomanenko that fixed it. Thanks!
