### ISSUE TITLE
Wrong Character Prediction in starting of transcription during Decoding

### ISSUE THREAD

**Issue by rajeevbaalwan** [facebookresearch/wav2letter#747]
I trained wav2letter model successfully on 100 hour subset of librispeech.
and decoded using the below decoder.cfg file 

--lexicon=/hdd1/nfshare_hulk/wav2vec/libri_exp/am/lexicon.txt
--lm=/hdd1/nfshare_hulk/wav2vec/libri_exp/lm/4-gram.binary
--am=/hdd1/nfshare_hulk/wav2vec/wav2vec_exp/librispeech_clean_asg_12Conv_prelu_lowreg_512kernel_trainlogs/001_model_#hdd1#nfshare_hulk#wav2vec#libri_exp#lists#test.trans.h5.tsv.bin
--test=/hdd1/nfshare_hulk/wav2vec/libri_exp/lists/test.trans.h5.tsv
--sclite=/hdd1/nfshare_hulk/wav2vec/wav2vec_exp/librispeech_clean_asg_12Conv_prelu_lowreg_512kernel_trainlogs/sclite
--lmweight=2
--wordscore=0.5
--beamsize=500
--beamthreshold=25
--silweight=-0.5
--nthread_decoder=1
--smearing=max
--show=true

but during decoding i am always getting some character in the starting of each sample which is effecting the overall results.

|T|: they pointedly drew back from john jago as he approached the empty chair next to me and moved round to the opposite side of the table
|P|: d they pointedly drew back from john jago as he approach the him to chair next me and move round to the opposite side of the table
[sample: test1544, WER: 23.0769%, LER: 9.02256%, slice WER: 23.0769%, slice LER: 9.02256%, decoded samples (thread 0): 1]

|T|: the ingenious hawkeye who recalled the hasty manner in which the other had abandoned his post at the bedside of the sick woman was not without his suspicions concerning the subject of so much solemn deliberation
|P|: d the ingenious hawk eye who recalled the hasty manner in which the other had abandon his post at the bedside of the sick woman was not without his suspicions concerning the subject of so much solemn deliberation
[sample: test296, WER: 11.1111%, LER: 2.36967%, slice WER: 16.129%, slice LER: 4.94186%, decoded samples (thread 0): 2]

|T|: john taylor who had supported her through college was interested in cotton
|P|: e john tailor who had supported her few college was interested in cotton
[sample: test441, WER: 25%, LER: 13.5135%, slice WER: 17.5676%, slice LER: 6.45933%, decoded samples (thread 0): 3]

|T|: please forgive me for this underhanded way of admitting i had turned forty
|P|: d please forgive me for this underhanded way of admitting at i had turned forty
[sample: test2474, WER: 15.3846%, LER: 6.75676%, slice WER: 20.8791%, slice LER: 7.58755%, decoded samples (thread 0): 5]

For Example For below output:
|T|: yes dead these four years an a good job for her too
|P|: d yes dead these four years and a good job for her too
[sample: test1365, WER: 16.6667%, LER: 5.88235%, slice WER: 22.3022%, slice LER: 7.56972%, decoded samples (thread 0): 8]

WER is 16.667%  but if i remove the starting character 'd' WER will be 8.3%

Any reasons why is this happening ?

**Comment by lunixbochs** [comment]
What does your Test output look like?

**Comment by rajeevbaalwan** [comment]
> What does your Test output look like?

Hi @lunixbochs 
I have not found any details on how to run test.cpp with what flags.

**Comment by lunixbochs** [comment]
try setting lmweight=1.3 and silweight=0

generally, you should do a random hyperparameter search to figure out which parameters are best for your LM and model combo

**Comment by rajeevbaalwan** [comment]
> try setting lmweight=1.3 and silweight=0
> 
> generally, you should do a random hyperparameter search to figure out which parameters are best for your LM and model combo

still getting the first character in prediction at lmweight=1.3 and silweight=0

**Comment by tlikhomanenko** [comment]
What are your tokens set? Letters? And as I see you trained ASG criterion, is this correct?

In decoder optimization it is a lot of time could be the case that decoder is worse than Viterbi, you just need to find appropriate params. Also optimal (near optimal) params can be different for lexicon and lexicon free, token and word-based decoders.

One more comment: if you are using token-based decoder, your lm should be trained on tokens, not on the words. So it will not work properly otherwise, it will just predict unk mostly all the time.

**Comment by rajeevbaalwan** [comment]
> What are your tokens set? Letters? And as I see you trained ASG criterion, is this correct?
> 
> In decoder optimization it is a lot of time could be the case that decoder is worse than Viterbi, you just need to find appropriate params. Also optimal (near optimal) params can be different for lexicon and lexicon free, token and word-based decoders.
> 
> One more comment: if you are using token-based decoder, your lm should be trained on tokens, not on the words. So it will not work properly otherwise, it will just predict unk mostly all the time.

@tlikhomanenko 
Yes I have trained using ASG and these are the tokens i am using 
|
'
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z

But when i trained tutorial model by following the instructions provided there is issue of wrong character prediction in some of samples for which WER drops from 52% to 20%. But when i trained another model by changing the architecture this is happening in almost all samples during decoding. surely this issue has nothing to do with AM. 

So you are suggesting to find the better parmas for decoder ? 

Also the Language model is constructed using KenLM , downloaded from http://www.openslr.org/resources/11/4-gram.arpa.gz. but i don't is it character based or word based LM ?

**Comment by tlikhomanenko** [comment]
> Also the Language model is constructed using KenLM , downloaded from http://www.openslr.org/resources/11/4-gram.arpa.gz. but i don't know is it character based or word based LM ?

Here the model is word-based, you can check this by doing head on the arpa file, you will see stats and then 1-grams (which will be just normal words). If you want to run with letter based ngram you can check this recipe https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech.

Yep, you Viterbi transcirptions looks fine, so the problem in the decoder itself. I would suggest to increase the beamthreshold to be 100 (less than 50 in my practice for ASG letters can be very bad and cut a lot of good hypothesis). Also try then to increase the beam to 1000 at least. `silweight` should be used in ASG, it should give better results.

**Comment by tlikhomanenko** [comment]
Did you set surround during training?

**Comment by TIFOSI528** [comment]
> try setting lmweight=1.3 and silweight=0
> 
> generally, you should do a random hyperparameter search to figure out which parameters are best for your LM and model combo

Hi, what is the reasonable range to do random search for _**lmweight, silweight & wordscore**_?
Thanks.

**Comment by tlikhomanenko** [comment]
@TIFOSI528 what kind of am model you are using? you can have a look at https://arxiv.org/pdf/1911.08460.pdf in the appendix on the decoder parameters and https://arxiv.org/abs/1904.04479 in the decoding section, how we did for our models.

**Comment by TIFOSI528** [comment]
> @TIFOSI528 what kind of am model you are using? you can have a look at https://arxiv.org/pdf/1911.08460.pdf in the appendix on the decoder parameters and https://arxiv.org/abs/1904.04479 in the decoding section, how we did for our models.

@tlikhomanenko ,
I try to use this  am model **baseline_nov93dev** with the following config
https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/lexicon_free/wsj/decoder_word_4gram.cfg,
but I met the same question as @rajeevbaalwan ,
in the head of each decoded sentence, I got an "a" or "i", with a total WER of ~12%.
I will check the papers then. Thank you.

**Comment by tlikhomanenko** [comment]
for this particular model please see my recent comment https://github.com/facebookresearch/wav2letter/issues/804

**Comment by xuqiantong** [comment]
@rajeevbaalwan Three questions:
- What is your lexicon? 
- What's the criterion you used in model training?
- Did you specify --surround?

I didn't see any obvious issue here. One possible reason is you have an item `d    d |` in the lexicon, and given the parameters you used, it tends to generate a word `d` at the beginning. Try sweep the decoder parameters.

**Comment by mpenagar** [comment]
Hi, I am geting this excat behavior on spanish Commonvoice data: almost perfect output for the greedy path (Test):
```
# /root/wav2letter/build/Test --am 002/001_model_.#manifest#dev.tsv.bin --test manifest/train_micro.tsv --show=true --input=wav
|T|: a s i m i s m o | c u e n t a | c o n | t a l l e r e s | d e | s e r v i c i o s | g a s o l i n e r a s | a l m a c e n e s | y | m e r c a d o
|P|: a s i m i s m o | c u e n t a | c o n | t a l l e r e s | d e | s e r v i c i o s | g a s o l i n e r a s | a l m a c e n e s | y | m e r c a d o
[sample: 19341400, WER: 0%, LER: 0%, total WER: 0%, total LER: 0%, progress (thread 0): 16.6667%]
|T|: p e r o | l a | t a r e a | n o | s e r i a | f a c i l
|P|: p e r o | l a | t a r e a | n o | s e r i a | f a c i l
[sample: 20022683, WER: 0%, LER: 0%, total WER: 0%, total LER: 0%, progress (thread 0): 33.3333%]
|T|: e n | o c a s i o n e s | a c t u a b a | c o m o | j u e z | s u p r e m o | d e | l a | p r o v i n c i a | e n | l u g a r | d e l | c a d i
|P|: e n | o c a s i o n e s | a c t u a b a | c o m o | j u e z | s u p r e m o | d e | l a | p r o v i n c i a | e n | l u g a r | d e l | c a d i
[sample: 20160024, WER: 0%, LER: 0%, total WER: 0%, total LER: 0%, progress (thread 0): 50%]
|T|: c o n | e l | d i s c o | d e m o s t r a r o n | s o n i d o s | m a s | f u n k | y | e l e c t r o n i c o s | q u e | e n | s u s | t r a b a j o s | a n t e r i o r e s
|P|: c o n | e l | d i s c o | d e m o s t r a r o n | s o n i d o s | m a s | f u n k | y | e l e c t r o n i c o s | q u e | e n | s u s | t r a b a j o s | a n t e r i o r e s
[sample: 19646836, WER: 0%, LER: 0%, total WER: 0%, total LER: 0%, progress (thread 0): 66.6667%]
|T|: a l a n | c e l o s o | e m p u j o | a | g r e g | a f u e r a | d e | s u | c o c h e | y | c o n d u j o | a l e j a n d o s e | d e l | l u g a r
|P|: a l a n c e l o s o | e m p u j o | a | g r e g | a f u e r a | d e | s u | c o c h e | y | c o n d u j o | a l e j a n d o s e | d e | l u g a r
[sample: 20157832, WER: 21.4286%, LER: 2.66667%, total WER: 5.26316%, total LER: 0.597015%, progress (thread 0): 83.3333%]
|T|: p e r t e n e c i a | a | l a | o r d e n | m i l i t a r | d e | s a n | j o r g e | d e | a l f a m a
|P|: p e r t e n e c i a | a | l a | o r d e n | m i l i t a r | d e | s a n | j o r g e | d e | a l f a m a
[sample: 20022692, WER: 0%, LER: 0%, total WER: 4.47761%, total LER: 0.516796%, progress (thread 0): 100%]

```
 but single character inserted word at the begining of every decoded sentence:

```
# /root/wav2letter/build/Decoder --am=/home/data/ASR/wav2letter/CommonVoice-5.1.es/002/001_model_.#manifest#dev.tsv.bin -tokensdir=/home/data/ASR/wav2letter/CommonVoice-5.1.es/manifest --tokens=tokens.txt --lexicon=/home/data/ASR/LM/wikipedia.mini/lexicon.100000.w2l.txt --lm=/home/data/ASR/LM/wikipedia.mini/lm.binary --datadir=/home/data/ASR/wav2letter/CommonVoice-5.1.es --test=manifest/train_micro.tsv --sclite=/home/data/ASR/wav2letter/CommonVoice-5.1.es/002 --lmweight=2.5 --wordscore=1 --beamsize=2500 --beamthreshold=100 --smearing=max --show=true --nthread_decoder=28 --input=wav
|T|: asimismo cuenta con talleres de servicios gasolineras almacenes y mercado
|P|: s asimismo cuenta con talleres de servicios gasolineras almacenes y mercado
[sample: 19341400, WER: 10%, LER: 2.73973%, slice WER: 10%, slice LER: 2.73973%, decoded samples (thread 1): 1]
|T|: pertenecia a la orden militar de san jorge de alfama
|P|: s pertenecia a la orden militar de san jorge de alfama
[sample: 20022692, WER: 10%, LER: 3.84615%, slice WER: 10%, slice LER: 3.84615%, decoded samples (thread 4): 1]
|T|: en ocasiones actuaba como juez supremo de la provincia en lugar del cadi
|P|: s en ocasiones actuaba como juez supremo de la provincia en lugar del cadi
[sample: 20160024, WER: 7.69231%, LER: 2.77778%, slice WER: 7.69231%, slice LER: 2.77778%, decoded samples (thread 14): 1]
|T|: alan celoso empujo a greg afuera de su coche y condujo alejandose del lugar
|P|: a alan celoso empujo a greg fuera de su coche y condujo alejandose de lugar
[sample: 20157832, WER: 21.4286%, LER: 5.33333%, slice WER: 21.4286%, slice LER: 5.33333%, decoded samples (thread 5): 1]
|T|: pero la tarea no seria facil
|P|: s pero la tarea no seria facil
[sample: 20022683, WER: 16.6667%, LER: 7.14286%, slice WER: 16.6667%, slice LER: 7.14286%, decoded samples (thread 3): 1]
|T|: con el disco demostraron sonidos mas funk y electronicos que en sus trabajos anteriores
|P|: s con el disco demostraron sonidos mas funk y electronicos que en sus trabajos anteriores
[sample: 19646836, WER: 7.14286%, LER: 2.29885%, slice WER: 7.14286%, slice LER: 2.29885%, decoded samples (thread 6): 1]
```
I tried to set the silweight argument, but there is no such an argument:

```
# /root/wav2letter/build/Decoder --am=/home/data/ASR/wav2letter/CommonVoice-5.1.es/002/001_model_.#manifest#dev.tsv.bin -tokensdir=/home/data/ASR/wav2letter/CommonVoice-5.1.es/manifest --tokens=tokens.txt --lexicon=/home/data/ASR/LM/wikipedia.mini/lexicon.100000.w2l.txt --lm=/home/data/ASR/LM/wikipedia.mini/lm.binary --datadir=/home/data/ASR/wav2letter/CommonVoice-5.1.es --test=manifest/train_micro.tsv --sclite=/home/data/ASR/wav2letter/CommonVoice-5.1.es/002 --lmweight=2.5 --wordscore=1 --beamsize=2500 --beamthreshold=100 --smearing=max --show=true --nthread_decoder=28 --input=wav --silweight=-1
ERROR: unknown command line flag 'silweight'
```

**Comment by mpenagar** [comment]
I noticed too that adding the argument `--input=wav` (I am using wav files) doesn't change anything (default is flac, but seting to `--input=flac` or `--input=wav` does the same). Does it autodetect the audio format, or maybe `Decoder` is not correctly detecting the input argument?

**Comment by tlikhomanenko** [comment]
@mpenagar do you use surround flag to be set to word separator?

**Comment by mpenagar** [comment]
I used the `conv_glu/librispeech` recipe.  I trained using `--surround=|` and the train/decode lexicon  is as:

```
abanico a b a n i c o |
abanicos a b a n i c o s |
abanilla a b a n i l l a |
abanto a b a n t o |
abaratamiento a b a r a t a m i e n t o |
abarca a b a r c a |
```

**Comment by mpenagar** [comment]
I tried ZeroLM decode with `--lm=''` and `--wordscore=0` and get exactly the same output:

```
/root/wav2letter/build/Decoder --am=/home/data/ASR/wav2letter/CommonVoice-5.1.es/002/001_model_.#manifest#dev.tsv.bin -tokensdir=/home/data/ASR/wav2letter/CommonVoice-5.1.es/manifest --tokens=tokens.txt --datadir=/home/data/ASR/wav2letter/CommonVoice-5.1.es --test=manifest/train_micro.tsv --sclite=/home/data/ASR/wav2letter/CommonVoice-5.1.es/002 --beamsize=2500 --beamthreshold=100 --smearing=max --show=true --nthread_decoder=28 --input=wav --lm='' --wordscore=0
|T|: asimismo cuenta con talleres de servicios gasolineras almacenes y mercado
|P|: s asimismo cuenta con talleres de servicios gasolineras almacenes y mercado
[sample: 19341400, WER: 10%, LER: 2.73973%, slice WER: 10%, slice LER: 2.73973%, decoded samples (thread 2): 1]
|T|: en ocasiones actuaba como juez supremo de la provincia en lugar del cadi
|P|: s en ocasiones actuaba como juez supremo de la provincia en lugar del cadi
[sample: 20160024, WER: 7.69231%, LER: 2.77778%, slice WER: 7.69231%, slice LER: 2.77778%, decoded samples (thread 1): 1]
|T|: alan celoso empujo a greg afuera de su coche y condujo alejandose del lugar
|P|: s alan celoso empujo a greg afuera de su coche y condujo alejandose de lugar
[sample: 20157832, WER: 14.2857%, LER: 4%, slice WER: 14.2857%, slice LER: 4%, decoded samples (thread 11): 1]
|T|: pero la tarea no seria facil
|P|: s pero la tarea no seria facil
[sample: 20022683, WER: 16.6667%, LER: 7.14286%, slice WER: 16.6667%, slice LER: 7.14286%, decoded samples (thread 3): 1]
|T|: pertenecia a la orden militar de san jorge de alfama
|P|: s pertenecia a la orden militar de san jorge de alfama
[sample: 20022692, WER: 10%, LER: 3.84615%, slice WER: 10%, slice LER: 3.84615%, decoded samples (thread 24): 1]
|T|: con el disco demostraron sonidos mas funk y electronicos que en sus trabajos anteriores
|P|: s con el disco demostraron sonidos mas funk y electronicos que en sus trabajos anteriores
[sample: 19646836, WER: 7.14286%, LER: 2.29885%, slice WER: 7.14286%, slice LER: 2.29885%, decoded samples (thread 8): 1]
```
It is like the Decoder would be seeing some data (wav header?) at the begining...

**Comment by mpenagar** [comment]
I've been playing with the lexicon and added a _silence_ word:
```
SIL     |
```

And now I am geting just silences at the begining of each sentence:

```
|T|: asimismo cuenta con talleres de servicios gasolineras almacenes y mercado
|P|: SIL asimismo cuenta con talleres de servicios gasolineras almacenes y mercado
[sample: 19341400, WER: 10%, LER: 0%, slice WER: 10%, slice LER: 0%, decoded samples (thread 0): 1]
|T|: en ocasiones actuaba como juez supremo de la provincia en lugar del cadi
|P|: SIL en ocasiones actuaba como juez supremo de la provincia en lugar del cadi
[sample: 20160024, WER: 7.69231%, LER: 0%, slice WER: 7.69231%, slice LER: 0%, decoded samples (thread 12): 1]
|T|: alan celoso empujo a greg afuera de su coche y condujo alejandose del lugar
|P|: SIL alan celoso empujo a greg afuera de su coche y condujo alejandose de lugar
[sample: 20157832, WER: 14.2857%, LER: 1.33333%, slice WER: 14.2857%, slice LER: 1.33333%, decoded samples (thread 7): 1]
|T|: pertenecia a la orden militar de san jorge de alfama
|P|: SIL pertenecia a la orden militar de san jorge de alfama
```
Now I see something is going wrong with the silences,  but not sure where. How are initial silences treated? Maybe the audio files have very long initial silences?

**Comment by tlikhomanenko** [comment]
We have the fix, it is on the way, will update as we push it.

**Comment by tlikhomanenko** [comment]
@mpenagar @rajeevbaalwan 

Ok, fix is added in the v0.2 branch for current usage, the diff is here https://github.com/facebookresearch/wav2letter/commit/b1d1f89f586120a978a4666cffd45c55f0a2e564, feel free to try and let me know if this fixes your problem (for me it is working well)!

**Comment by mpenagar** [comment]
Works perfectly, Thanks!

**Comment by tlikhomanenko** [comment]
Nice! @rajeevbaalwan @TIFOSI528 @lunixbochs feel free to try the fix too, it should work for you too. Closing the issue, but feel free to reopen if this fix would not solve the issues for you.
