### ISSUE TITLE
GLU dimension is incorrect 

### ISSUE THREAD

**Issue by pankajkumar** [facebookresearch/wav2letter#75]
https://github.com/facebookresearch/wav2letter/blob/153ac12304a51199249d797d365c25f13b5426ed/wav2letter/runtime/netutils.lua#L131

It should be : 
`return nn.GatedLinearUnit(2):cuda()`

Otherwise it returns the error:- 

> SpatialConvolution.lua:102: input has to contain: 200 feature maps, but received input of size: 2 x 40 1 x 1844

**Comment by vineelpratap** [comment]
@pankajkumar Can you let me know what data you are training on, the sampling frequency of audio files and the command you have used to run the training

**Comment by pankajkumar** [comment]
I am training on LibriSpeech ASR corpus, here is the command:- 


`luajit train.lua --train -rundir ~/experiments -runname hello_librispeech -archdir ~/pb/wav2letter/wav2letter/arch/ -arch librispeech-glu-highdropout -lr 0.1 -lrcrit 0.0005 -gpu 1 -linseg 1 -linlr 0 -linlrcrit 0.005 -onorm target -nthread 0 -dictdir downloads/librispeech-proc  -datadir downloads/librispeech-proc -train dev-clean -valid test-clean -sqnorm -mfsc -melfloor 1 -surround "|" -replabel 2 -progress -wnorm -normclamp 0.2 -momentum 0.9 -weightdecay 1e-05`

**Comment by vineelpratap** [comment]
Fixed
