### ISSUE TITLE
does it means down sample or error?

### ISSUE THREAD

**Issue by qzfnihao** [facebookresearch/wav2letter#754]
In recipes/models/sota/2019/am_arch/am_transformer_ctc.arch, the arch has 1 layer: 
....
M 1 1 2 1
...

in src/module/W2lModule.cpp: 
M means Pool2D layer with PoolimingModel::MAX, 
but the parameters confuse me. 
from the code:  it means wx = 1, wy=1, dx=2, dy=1. 
In flashlight,  in construction of Pool2D, dx=2 means stride_x = 2, and wx = 1 means window_x = 1. 
Does it mean that we choose 1 data from window size 1 with stride 2? it means we just down sample every 2 data?
why not choose 1 data from window size 2 with stride 2 ?

Am i wrong?

**Comment by tlikhomanenko** [comment]
@qzfnihao 

Original it was by mistake, so if you switch to M 2 1 2 1 it will give similar final model. 

For the M 1 2 1 1 it means that for example for input [1, 2, 3, 4] it will consider [1] and then [3] and take max in each array which is [1, 3]. (So we don't do max and just skip all even positions.
