### ISSUE TITLE
File https://github.com/facebookresearch/wav2letter/blob/master/tutorials/1-librispeech_clean/README.md should be updated

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#760]
In file 

https://github.com/facebookresearch/wav2letter/blob/master/tutorials/1-librispeech_clean/README.md

In following lines "1-" should be added before "librispeech_clean"

wav2letter/tutorials/librispeech_clean/prepare_data.py --src $W2LDIR/LibriSpeech/ --dst $W2LDIR
wav2letter/tutorials/librispeech_clean/prepare_lm.py --dst $W2LDIR

Thanks,
AlexG.

**Comment by vineelpratap** [comment]
Thanks ! Could you send a PR for the fix.

**Comment by AlexandderGorodetski** [comment]
Hi. I am sorry. I am relatively new to wav2letter++. Could you please explain me how can I send PR request.

**Comment by tlikhomanenko** [comment]
As usual as people do it for any other repository. For example instructions here https://gist.github.com/Chaser324/ce0505fbed06b947d962 (you can do part of the command in the browser, like create clone of the project and sending pull request from you clone into wav2letter).
