### ISSUE TITLE
Audio and text data preparing

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#764]
### Question

On my new hard drive, I ran first:

<pre>$ pip3 install sox
Collecting sox
  Using cached https://files.pythonhosted.org/packages/60/a0/5bee540554af8376e0313e462629d95bf2f2bc3c8cb60697aa01254e6cf5/sox-1.3.7-py2.py3-none-any.whl
Installing collected packages: sox
Successfully installed sox-1.3.7
</pre>

Then when I ran:

<pre>$ python3 wav2letter/recipes/data/librispeech/prepare.py --dst /home/lm/w2l</pre>

I got:

<pre>
...

test-other.tar.gz                100%[=========================================================&gt;] 313.53M   356KB/s    in 15m 26s 

2020-07-25 04:45:15 (347 KB/s) - ‘/home/lm/w2l/audio/test-other.tar.gz’ saved [328757843/328757843]

Downloading and unpacking text data...
--2020-07-25 04:45:18--  http://www.openslr.org/resources/11/librispeech-lm-norm.txt.gz
Resolving www.openslr.org (www.openslr.org)... 46.101.158.64
Connecting to www.openslr.org (www.openslr.org)|46.101.158.64|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1507274412 (1.4G) [application/x-gzip]
Saving to: ‘/home/lm/w2l/text/librispeech-lm-norm.txt.gz’

librispeech-lm-norm.txt.gz       100%[=========================================================&gt;]   1.40G   357KB/s    in 72m 27s 

2020-07-25 05:57:46 (339 KB/s) - ‘/home/lm/w2l/text/librispeech-lm-norm.txt.gz’ saved [1507274412/1507274412]

Converting audio data into necessary format.
Path /home/lm/w2l/lists/train-clean-100.lst exists, skip its generation. To regenerate this file, please, remove it.
Analyzing /home/lm/w2l/audio/LibriSpeech/train-clean-360...
Writing to /home/lm/w2l/lists/train-clean-360.lst...
This install of SoX cannot process .flac files.
  0%|                                                                                                     | 0/2097 [00:00&lt;?, ?it/s]This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
  0%|                                                                                                     | 0/2097 [00:00&lt;?, ?it/s]
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
This install of SoX cannot process .flac files.
multiprocessing.pool.RemoteTraceback: 
&quot;&quot;&quot;
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/multiprocessing/pool.py&quot;, line 119, in worker
    result = (True, func(*args, **kwds))
  File &quot;/home/lm/wav2letter/recipes/data/librispeech/utils.py&quot;, line 43, in transcript_to_list
    duration = sox.file_info.duration(audio_file) * 1000  # miliseconds
  File &quot;/home/lm/.local/lib/python3.6/site-packages/sox/file_info.py&quot;, line 89, in duration
    output = soxi(input_filepath, &apos;D&apos;)
  File &quot;/home/lm/.local/lib/python3.6/site-packages/sox/core.py&quot;, line 118, in soxi
    stderr=subprocess.PIPE
  File &quot;/usr/lib/python3.6/subprocess.py&quot;, line 356, in check_output
    **kwargs).stdout
  File &quot;/usr/lib/python3.6/subprocess.py&quot;, line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File &quot;/usr/lib/python3.6/subprocess.py&quot;, line 729, in __init__
    restore_signals, start_new_session)
  File &quot;/usr/lib/python3.6/subprocess.py&quot;, line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: &apos;sox&apos;: &apos;sox&apos;
&quot;&quot;&quot;

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;wav2letter/recipes/data/librispeech/prepare.py&quot;, line 113, in &lt;module&gt;
    total=len(transcript_files),
  File &quot;/home/lm/.local/lib/python3.6/site-packages/tqdm/std.py&quot;, line 1130, in __iter__
    for obj in iterable:
  File &quot;/usr/lib/python3.6/multiprocessing/pool.py&quot;, line 735, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: &apos;sox&apos;: &apos;sox&apos;
</pre>

I have: <pre>$ locate sox
/home/lm/.local/lib/python3.6/site-packages/sox
...
</pre>

Questions: (1) How may I fix the above error? (2) When I ran <pre>$ python3 wav2letter/recipes/data/librispeech/prepare.py --dst /home/lm/w2l</pre>
data was downloaded and unpacked successfully:
 
![image](https://user-images.githubusercontent.com/61134984/88457941-ccaf4c00-ce4f-11ea-887e-12e81c250c2f.png)

it sounds that I only need to do "Converting audio data into necessary format, and generate train-clean-100.lst, train-clean-360.lst...". Any command which just does this without downloading the data again?  Downloading data took me several days.

Thank you!!

#### Additional Context
[Add any additional information here]

**Comment by ML6634** [comment]
I copied the folder, lists, from another drive to here. So, I could move on now. However, if somebody knows answers to questions (1) and (2) above, it would be appreciated if you would let me know. Thank you!

**Comment by tlikhomanenko** [comment]
(1) `apt-get install sox` you need binary, not only python sox wrapper.
(2) The script was not finished, so part of the data, like text data for lm training are not prepared.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the helpful comments!!
