### ISSUE TITLE
Question about <unk> word

### ISSUE THREAD

**Issue by AlexandderGorodetski** [facebookresearch/wav2letter#765]
Hello,

I have a question about libri-clean recipe. The arpabo of this recipe includes <unk> word. But tokens file does not include any information about <unk>. I guess somewhere in the code you ignore everything related to <unk> word in the arpabo. Is that correct?

Thanks,
Alexander.

**Comment by tlikhomanenko** [comment]
Tokens set of acoustic model can be any: phonemes, letters, word-pieces, words. Arpa file of language model is word-based, which means that we add lm score only when we form a word during beam-search decoding. (Maybe I didn't understand your question correctly).

**Comment by AlexandderGorodetski** [comment]
I am sorry it was my mistake. I had word with illegal characters in lm/lexicon.txt. In this case the Decoder crashes. It was not issue of the arpabo. lm/lexicon.txt should include only valid characters (tokens).
