### ISSUE TITLE
lpm training convlm tokens

### ISSUE THREAD

**Issue by MohitTare** [facebookresearch/wav2letter#768]
### Question
We are trying to use the LPM recipe and trying to reproduce it for hindi(devngari). We already have an initial and proposal model trained using word pieces as tokens. We plan to use the same tokens for lpm training. 

For training a convlm, we first tried a word based lm using recipe mentioned below
https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech

but due to token mismatch the lpm training is crashing.

 For training lpm is it necessary to have the lm dictionary(tokens) same as the tokens used for training the model ?

**Comment by tlikhomanenko** [comment]
@an918tw could you provide details here?

**Comment by an918tw** [comment]
@MohitTare yes in the current setup it is required that the LM and the acoustic models share the same token set.

**Comment by MohitTare** [comment]
@an918tw Thanks for the reply. If possible can you provide the details of the lm recipe you using word piece tokens. I can try to reproduce similar recipe for hindi then. Currently i am trying with the lm training recipe mentioned below

https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech

**Comment by an918tw** [comment]
@MohitTare we were using the same recipe for training the convLM.
