### ISSUE TITLE
Streaming TDS model conversion Error for TDS seq2seq model in docker GPU

### ISSUE THREAD

**Issue by itsmemuthu** [facebookresearch/wav2letter#769]
I'm able to make the streaming_tds_model_converter inside the docker wav2letter/wav2letter:cuda-latest. But while converting the TDS seq2seq acoustic model inside recipes/sota/2019, I am getting this error.

> ./streaming_tds_model_converter --am /root/wav2letter/sota_2019_models/am_tds_s2s_librivox_dev_other.bin --outdir /root/wav2letter/streamable_am/

**push_numbers/200M/500M/101.cfg: No such file or directory**

**Comment by jacobkahn** [comment]
cc @tlikhomanenko @gilad @xuqiantong - this looks like an issue with deserialization and an old config being present?

**Comment by itsmemuthu** [comment]
Also while serializing the latest TDS seq2seq model (**am_tds_s2s_librivox_dev_other_icml.bin**), I am getting similar issue with the config path. But with streaming_convnets model, there is no such issue.
**/private/home/qiantong/push_numbers/200M/ICML/301.cfg: No such file or directory**

Is the path information also being captured in the model?

**Comment by tlikhomanenko** [comment]
Inside converter script the flagsfile from the saved model is reading https://github.com/facebookresearch/wav2letter/blob/master/tools/StreamingTDSModelConverter.cpp#L171, so to avoid this error just run the converter script with argument `--flagsfile=` (empty input).

**Comment by vineelpratap** [comment]
Hi,
 Note that we don't support running TDS seq2seq in streaming manner at the moment. You should train models using a recipe similar to https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/streaming_convnets .

A pretrained model in LibriSpeech+Librivox is also available there.

**Comment by itsmemuthu** [comment]
@tlikhomanenko Adding --flagsfile= (empty input) solved the path issue
@vineelpratap Thanks for your input. I tried out the pretrained model. It works perfectly.
