### ISSUE TITLE
[Argument to train CONVLM]

### ISSUE THREAD

**Issue by gopesh97** [facebookresearch/wav2letter#777]
### Bug Description
Refer to this.
https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/lexicon_free/librispeech#reproduce-language-models-training--evaluation

This is the command given to train a convlm from fairseq. 
When you run it, throws an error stating one the argument is wrong, i.e., `keep-interval-update`
```
python3 [FAIRSEQ]/train.py [MODEL_DST]/decoder/fairseq_word_data \
--save-dir [MODEL_DST]/decoder/convlm_models/word_14B \
--task=language_modeling \
--arch=fconv_lm --fp16 --max-epoch=48 --optimizer=nag \
--lr=0.5 --lr-scheduler=fixed --decoder-embed-dim=128 --clip-norm=0.1 \
--decoder-layers='[(512, 5)] + [(128, 1, 0), (128, 5, 0), (512, 1, 3)] * 3 + [(512, 1, 0), (512, 5, 0), (1024, 1, 3)] * 3 + [(1024, 1, 0), (1024, 5, 0), (2048, 1, 3)] * 6 + [(1024, 1, 0), (1024, 5, 0), (4096, 1, 3)]' \
--dropout=0.1 --weight-decay=1e-07 \
--max-tokens=1024 --tokens-per-sample=1024 --sample-break-mode=none \
--criterion=adaptive_loss --adaptive-softmax-cutoff='10000,50000,200000' --seed=42 \
--log-format=json --log-interval=100 \
--save-interval-updates=10000 --keep-interval-update=10 \
--ddp-backend="no_c10d" --distributed-world-size=8 > [MODEL_DST]/decoder/convlm_models/word_14B/train.log

```

Upon searching the valid arguments from fairseq, turns out this argument is `keep-interval-updates`. 
So this change needs to be done so that anyone else won't face this issue.

### Platform and Hardware
I am using the `wav2letter/wav2letter:cuda-latest` docker.

**Comment by tlikhomanenko** [comment]
Thanks for the pointing to this!

Will fix this typo in the README.
