### ISSUE TITLE
Training stopped - what():  loadSound: read error 

### ISSUE THREAD

**Issue by Dr-AyanDebnath** [facebookresearch/wav2letter#779]
Thanks to Facebook for making such a good ASR. 
I would like to train librispeech data using tutorial (https://github.com/facebookresearch/wav2letter/tree/master/tutorials/1-librispeech_clean) with CTC criterion. Initially, my training didn't start due to the following error 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  loadSound: read error
```

I changed batchsize from 16 to 4 and increased iter from 25 to 25000, Suddenly training started but again stopped after epoch1. Now again I am getting same error.
The train.cfg is [train.cfg.txt](https://github.com/facebookresearch/wav2letter/files/5054445/train.cfg.txt)
The network architecture is the simplest one as shown in tutorial and is also attached here [network.arch.txt](https://github.com/facebookresearch/wav2letter/files/5054420/network.arch.txt)
In this case, number of traning sample is 93,905 (train-clean-100.lst, train-clean-360.lst).
I am using wav2letter cuda latest docker on ML server where I already trained different models for Hindi data (Indian language) using seq2seq criterion. The docker passed all the test (make test), so there shouldn't be an issue with docker itself which surely cannot be the reason to provide loadSound error.
even I tried to re-build libsndfile using the follwoing steps:
```
    cd /tmp && git clone https://github.com/erikd/libsndfile.git && \
    cd libsndfile && git checkout 4bdd7414602946a18799b514001b0570e8693a47 && \
    ./autogen.sh && ./configure --enable-werror && \
    make -j$(nproc) && make check && make install 
```
I am also providing the log file for epoch1
`epoch:        1 | nupdates:         2501 | lr: 0.100000 | lrcriterion: 0.000000 | runtime: 00:03:33 | bch(ms): 85.25 | smp(ms): 4.52 | fwd(ms): 32.57 | crit-fwd(ms): 27.54 | bwd(ms): 41.92 | optim(ms): 3.28 | loss:   36.36931 | train-TER: 85.97 | train-WER: 100.26 | /lists/dev-clean.lst-loss:   21.17431 | /lists/dev-clean.lst-TER: 67.94 | /lists/dev-clean.lst-WER: 99.22 | avg-isz: 1227 | avg-tsz: 208 | max-tsz: 345 | hrs:  136.44 | thrpt(sec/sec): 2303.82`

Here is the details of the error [error.txt](https://github.com/facebookresearch/wav2letter/files/5054468/error.txt)
`
I used the following training command to continue my training
mpirun --allow-run-as-root -n 4 /root/wav2letter/build/Train continue /home/librispeech_clean_trainlogs/ -enable_distributed true --flagsfile /home/train.cfg --minloglevel=0 --logtostderr=1

Kindly let me know how to solve the issue and continue my training.

I have a general question too, which is as follows:
I am utterly confused with batchsize, niter (number of iteration which I calculated as number of traning samples divided by batch size). Often, I found out that training got stopped after epoch2 or epoch3, but again get started due to increasing niter. So to keep on training, I put higher value for niter, but still stopped due to some error. Kindly explain the concept behind batchsize, niter and what to assign their value.

**Comment by avidov** [comment]
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  loadSound: read error

Looks like sound file loading issue, where the number of loaded frames is different than expected one.

https://github.com/facebookresearch/wav2letter/blob/d313e6a394cac4c8cf157aee9f853c6778afc7e9/src/data/Sound.cpp#L266

Please ensure that your input sound files are accessible for the running training process.
I'd check first that you can access the files from command line.
If that work you can log the failing file name by printing it here:
https://github.com/facebookresearch/wav2letter/blob/d313e6a394cac4c8cf157aee9f853c6778afc7e9/src/data/Sound.cpp#L223

**Comment by tlikhomanenko** [comment]
Batchsize is number of sample per GPU to be used for 1 optimization step. `iter` is number of updates of the training. So in case of say batch=10 and 2 GPUs 1 update will process 20 samples. In terms of epochs then 1 epoch consists of Nsamples / batchsize / nGPUs updates.
