### ISSUE TITLE
Transcriptions

### ISSUE THREAD

**Issue by ambigus9** [facebookresearch/wav2letter#78]
I would Like to know if I run the test.lua with a transcription.txt file with a simple word for all audios will affect the model?

For example, I modify a trans.txt file and the content is this:

1272-128104-0000 HI
1272-128104-0001 HI
1272-128104-0002 HI

When I run the test.lua I'm getting a WER for each sentence, for me doesn't matter WER scoring, which is really important to me are the transriptions of each audio. So, It's just a question about the workflow of this Framework.

**Comment by vineelpratap** [comment]
Hi it shouldn’t matter. Also, I’m testing the PR https://github.com/facebookresearch/wav2letter/pull/73 to see if it produces the same results as expected on a sample dataset.
Once it is committed, there shouldn’t be any need to do all the hacks I have mentioned. You just specify audio file and it should return the transcript

**Comment by ambigus9** [comment]
@vineelpratap Thanks. I achived to run decode and this is part of the result:

```
002167 |P| following the tingle of relief came a sharp sickening pinch of jealousy and mortification these inspired her
002167 |T| following the tingle of relief came a sharp sickening pinch of jealousy and mortification these inspired her {progress=099% iWER=000.00% sliceWER=006.77%}
002168 |P| i don't wonder you were afraid to tell me she began you don't love me you've never loved me i was an idiot to believe you did
002168 |T| i don't wonder you were afraid to tell me she began you don't love me you've never loved me i was an idiot to believe you did {progress=100% iWER=000.00% sliceWER=006.74%}
[Memory usage: 97.58 Mb]
[Decoded 2703 sequences in 1503.26 s (actual: 12330.21 s)]
[WER on dev-clean = 5.89%, LER = 2.44%]
```

I would like to know where is saved the decode results?

**Comment by xuqiantong** [comment]
@ambigus9 currently, the decoding results only print out on stdout. You may save the log by yourself.

**Comment by ambigus9** [comment]
@xuqiantong Could you  please give me some clue to save the log? May be with `tee` command?

**Comment by xuqiantong** [comment]
Yeah, `tee` seems like a simple to save log.
e.g. `<run_decoder_script> | tee <log_file_path>`
