### ISSUE TITLE
Decoder command specified incorrectly in Beam search decoding tutorial

### ISSUE THREAD

**Issue by Dr-AyanDebnath** [facebookresearch/wav2letter#781]
### Bug Description
Kindly check https://github.com/facebookresearch/wav2letter/wiki/Beam-Search-Decoder for the decoding command, it is mentioned as
wav2letter/build/Decode \
  --am path/to/train/am.bin \
  --test path/to/test/list/file \  
  --maxload 10 \
  --nthread_decoder 2 \

I believe the command should be wav2letter/build/Decoder  i.e. Decoder in place of Decode

If I am wrong, kindly rectify me.

**Comment by tlikhomanenko** [comment]
Thanks for pointing, I have fixed it.
