### ISSUE TITLE
After build wav2letter through docker ，but cmake test failed.

### ISSUE THREAD

**Issue by zira-wang** [facebookresearch/wav2letter#782]
HELLO:
### Question
1、I have downloaded the latest image of wav2letter:cpu-latest
`sudo docker run --rm -itd --ipc=host --name w2l wav2letter/wav2letter:cpu-latest`
2、When running the make test within the docker the tests fails.
`cd /root/wav2letter/build && make test`
Seq2SeqTest && W2lModuleTest ***Failed

How should i solve this problem？？

**Comment by tlikhomanenko** [comment]
Please have a look on this thread https://github.com/facebookresearch/wav2letter/issues/706 - closing as this issue some sort duplication of https://github.com/facebookresearch/wav2letter/issues/706
