### ISSUE TITLE
How to compute future context in streaming conv

### ISSUE THREAD

**Issue by uqyxx** [facebookresearch/wav2letter#783]
In the paper(SCALING UP ONLINE SPEECH RECOGNITION USING CONVNETS), it said 'The features are extracted with a stride of 10ms so the model has a receptive field of ~10 seconds per frame and a future context of 250ms.' So I compute the receptive field according to the model architecture, I can get 1000*10ms=10seconds. But I don't know how to get 250ms from the architecture.  Can anyone help? Thanks.

**Comment by nguyenhuy1209** [comment]
> In the paper(SCALING UP ONLINE SPEECH RECOGNITION USING CONVNETS), it said 'The features are extracted with a stride of 10ms so the model has a receptive field of ~10 seconds per frame and a future context of 250ms.' So I compute the receptive field according to the model architecture, I can get 1000*10ms=10seconds. But I don't know how to get 250ms from the architecture. Can anyone help? Thanks.

Sorry for the inconvenience, I know this is an old and closed issue, but can you tell me how did you calculate the 10 seconds receptive field? I'm currently researching the paper and still cannot get my head around it. Thank you in advance.
