### ISSUE TITLE
Problem when install in ubuntu 18.04+

### ISSUE THREAD

**Issue by aidenpearce001** [facebookresearch/wav2letter#794]
After git clone Wav2letter from https://github.com/facebookresearch/wav2letter and cant see CMakeLists.txt so i clone from this https://github.com/maltium/wav2letter at build step i got this error even when i set -DFLASHLIGHT_DIR and -DArrayFire_DIRpoint to where i build it ! help me 
![image](https://user-images.githubusercontent.com/56188293/91068110-f9789e00-e65d-11ea-9c8a-5d9b1c05fa2f.png)
even

**Comment by tlikhomanenko** [comment]
Hi @aidenpearce001,

We are restructuring and moving things to the flashlight, so please use for now stable version at https://github.com/facebookresearch/wav2letter/tree/v0.2 along with the flashlight version https://github.com/facebookresearch/flashlight/tree/v0.2. Let me know if with them you have the same problem during installation.

**Comment by aidenpearce001** [comment]
> Hi @aidenpearce001,
> 
> We are restructuring and moving things to the flashlight, so please use for now stable version at https://github.com/facebookresearch/wav2letter/tree/v0.2 along with the flashlight version https://github.com/facebookresearch/flashlight/tree/v0.2. Let me know if with them you have the same problem during installation.
> 
> Can you also make sure that you followed flashlight instructions on installation in distributed mode?

Tks , its work
