### ISSUE TITLE
Fork for pretrained model 

### ISSUE THREAD

**Issue by akhaled89** [facebookresearch/wav2letter#795]
### Question
I'm using this model for transcript some audio and I need to finetune it , I got it from this tutorial https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples ,from 'http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model' I'm wondering if there a way to get the train.cfg that used to train the model. 
#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
cc @avidov

**Comment by vineelpratap** [comment]
Hi, here is the config used for that model - https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/streaming_convnets/librispeech/train_am_500ms_future_context.cfg.  
 
You can use it to fork the model. Note that you would have to remove blank token '#' from the tokens file while running the experiment. Also, I would play around with lr, momentum to find the best setting for the fine-tuning.

**Comment by ngocanh99124** [comment]
> Hi, here is the config used for that model - https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/streaming_convnets/librispeech/train_am_500ms_future_context.cfg.
> 
> You can use it to fork the model. Note that you would have to remove blank token '#' from the tokens file while running the experiment. Also, I would play around with lr, momentum to find the best setting for the fine-tuning.

I findout in my vocabs and tokens file have blank tokens, does it affect to model trainning?
Shoul i remove it?
![Screenshot from 2020-10-06 09-00-33](https://user-images.githubusercontent.com/49809347/95150531-8dd43580-07b2-11eb-870c-a2d04a073597.png)

**Comment by tlikhomanenko** [comment]
what do you mean as blank tokens? having "_" is ok.

**Comment by ngocanh99124** [comment]
> what do you mean as blank tokens? having "_" is ok.

oh, it's my confuse
