### ISSUE TITLE
Run CPU version Decoder got an error result

### ISSUE THREAD

**Issue by sdkdzq2020** [facebookresearch/wav2letter#798]
### Question decoder
Path is recipes/models/sota/2019. Run "/root/wav2letter/build/Decoder --flagsfile decode_transformer_ctc_ngram_clean.cfg --minloglevel=0 --logtostderr=1"  on GPU docker and CPU docker, I got the fellow different result. Model and cfg is same, Is the CPU docker's inference has some problem?

I print the log with

const float* ess = emission.data();
LOG(INFO)
<< "[Decoder] emission is "
<< ess[2*10+11];

get result:

GPU：I0826 08:00:35.457897  2161 Decode.cpp:552] [Decoder] emission is -8653.43
CPU：I0826 07:54:15.805691 22352 Decode.cpp:555] [Decoder] emission is -1200.53

#### Additional Context
GPU result：

|T|: all the furniture belonged to other times

|P|: all the furniture belonged to other times

|t|: a l l _ t h e _ f u r n i t u r e _ b e l o n g e d _ t o _ o t h e r _ t i m e s

|p|: _ a l l _ t h e _ f u r n i t u r e _ b e l o n g e d _ t o _ o t h e r _ t i m e s

[sample: test-clean-5683-32866-0023, WER: 0%, LER: 2.43902%, slice WER: 0%, slice LER: 2.43902%, decoded samples (thread 0): 1]

CPU result：

|T|: all the furniture belonged to other times

|P|: one sees one sees one

|t|: a l l _ t h e _ f u r n i t u r e _ b e l o n g e d _ t o _ o t h e r _ t i m e s

|p|: o n e _ s e e s _ o n e _ s e e s _ o n e

[sample: test-clean-5683-32866-0023, WER: 100%, LER: 75.6098%, slice WER: 100%, slice LER: 75.6098%, decoded samples (thread 0): 1]

**Comment by tlikhomanenko** [comment]
Did you solve the issue @sdkdzq2020?

**Comment by sdkdzq2020** [comment]
No. I try the latest CPU version, the question is still have.

**Comment by tlikhomanenko** [comment]
Please have a look at this thread too https://github.com/facebookresearch/wav2letter/issues/503.

The operations implementations is different (even libraries are totally different, so computations are different) in CPU and CUDA backends, so one can see the difference when do inference on CPU with model trained on GPU. So far for transformer models we saw huge difference between inference in CPU and CUDA backends.

Solutions for now:
1) use only CUDA backend for model trained on GPU
2) re-train model on CPU backend
