### ISSUE TITLE
unknown issue on installation

### ISSUE THREAD

**Issue by Terry1504** [facebookresearch/wav2letter#8]
pls ignore if here it's not good place to raise question.

----------------------------------------

bash-3.2$ cd speech/
bash-3.2$ luarocks make rocks/speech-scm-1.rockspec

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FFTW (missing: FFTW_INCLUDES FFTW_LIBRARIES)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFTW.cmake:94 (find_package_handle_standard_args)
  CMakeLists.txt:8 (find_package)

**Comment by jaeho-kang** [comment]
in my case 
i install fftw package with under 2 command 

sudo apt-get install libfftw3-3
sudo apt-get install libfftw3-dev

after that problem was solved

**Comment by VitaliyLi** [comment]
@Terry1504 , has @jaeho-kang solution worked for you?

**Comment by DenisPeskov** [comment]
I ran into this exact issue while installing on MacOS.  I followed the FFTW package installation instructions to no avail, but then a "bnew install fftw" (and a couple of manual fixes) worked.

**Comment by Terry1504** [comment]
thank you all. 
Original issue was resolved after ""brew install fftw". 
Later need to do "brew install libsndfile"  to fix error "Could not find libsndfile" at step "cd wav2letter && luarocks make rocks/wav2letter-scm-1.rockspec".
