### ISSUE TITLE
Cannot build wav2letter on non-ubuntu systems 

### ISSUE THREAD

**Issue by picheny-nyu** [facebookresearch/wav2letter#800]
Build does not work on non-Ubuntu Linux systems, at least as fast as I can tell, because we do not have the apt and apt-get package managers on RHEL, and also we run on a distributed system where we do not ourselves have access to /usr/local (so we need a way to install software via local directories).

For example, the fftw package will not install.

**Comment by tlikhomanenko** [comment]
Could you clarify: you cannot install dependencies, is it slow installation or what? You can specify also `-DCMAKE_INSTALL_PREFIX` where you want to install. All dependencies should be installed on each node. One of the solutions for you could be usage of docker images.

**Comment by picheny-nyu** [comment]
I work in a slum environment where I cannot install to /usr/local/. Either I need to figure out how to install to my own directories and somehow point to them or ask you say run docker, but I am not sure that is possible under slurm. These extra dependencies (like opus and fftw) are therefore causing me a lot of trouble. Any suggestions appreciated. Note that speech packages like kaldi and espnet do not seem to have such issues.....or at least less of them, for me....

**Comment by itzsimpl** [comment]
Typically in a SLURM environment you have a package manager (e.g. MODULES) and the admins install your dependancies upon request. That is, when you wish to run on bare metal. The typical workflow when running your code is then to load the desired packages via MODULES. 

On the other hand, if you are comfortable with containers, your best bet in SLURM is to use singularity or enroot/pixys; see https://slurm.schedmd.com/containers.html.

**Comment by tlikhomanenko** [comment]
@itzsimpl good point about MODULES!

**Comment by picheny-nyu** [comment]
I am somewhat clueless about containers but it looks like I finally found the needed modules on my system (in. non-standard places), and just put them on my PATH which seemed to get the. build going (though now I seem to have new problems :-( )
