### ISSUE TITLE
ASG criterion - failing to allocate memory

### ISSUE THREAD

**Issue by omprakashsonie** [facebookresearch/wav2letter#802]
### Bug Description
With CTC the system is able to allocate 14+GB GPU memory. But by just changing to ASG criterion it is failing to allocate 12+GB memory.

#### Reproduction Steps
Getting following msg:
I0827 09:38:22.176551  2038 Train.cpp:571] Epoch 1 started!
Unable to allocate memory with native alloc for size 12832473088 bytes with error 'ArrayFire Exception (Device out of memory:101):
ArrayFire error:
In function fl::MemoryManagerInstaller::MemoryManagerInstaller(std::shared_ptr<fl::MemoryManagerAdapter>)::<lambda(size_t)>
In file /root/flashlight/flashlight/memory/MemoryManagerInstaller.cpp:188'terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function virtual void* MemoryManagerFunctionWrapper::alloc(bool, unsigned int, dim_t*, unsigned int)
In file src/api/c/memory.cpp:684

 0# 0x00007FD7BDFE6D11 in /usr/local/lib/libafcuda.so.3
 1# 0x00007FD7BD7EF5C6 in /usr/local/lib/libafcuda.so.3
 2# 0x00007FD7BD26BF3D in /usr/local/lib/libafcuda.so.3
 3# 0x00007FD7BD26C02F in /usr/local/lib/libafcuda.so.3
 4# 0x00007FD7BDE13531 in /usr/local/lib/libafcuda.so.3
 5# af_create_handle in /usr/local/lib/libafcuda.so.3
 6# 0x00007FD7BE1641DE in /usr/local/lib/libafcuda.so.3
 7# af::array::array(long long, af_dtype) in /usr/local/lib/libafcuda.so.3
 8# 0x0000559AD1E2ED97 in /root/wav2letter/build/Train
 9# 0x0000559AD1CE2ECC in /root/wav2letter/build/Train
10# 0x0000559AD1CC9E50 in /root/wav2letter/build/Train
11# 0x0000559AD1C636A8 in /root/wav2letter/build/Train
12# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
13# 0x0000559AD1CC451A in /root/wav2letter/build/Train

In function void* {anonymous}::initEm
*** Aborted at 1598521107 (unix time) try "date -d @1598521107" if you are using GNU date ***
PC: @     0x7fd79d591e97 gsignal
*** SIGABRT (@0x7f8) received by PID 2040 (TID 0x7fd7e2e61380) from PID 2040; stack trace: ***
    @     0x7fd7e1d39890 (unknown)
    @     0x7fd79d591e97 gsignal
    @     0x7fd79d593801 abort
    @     0x7fd79df86957 (unknown)
    @     0x7fd79df8cab6 (unknown)
    @     0x7fd79df8caf1 std::terminate()
    @     0x7fd79df8cd24 __cxa_throw
    @     0x7fd7be16432c (anonymous namespace)::initEmptyArray()
    @     0x7fd7be16557b af::array::array()
    @     0x559ad1e2ed97 w2l::FullConnectionCriterion::forward()
    @     0x559ad1ce2ecc w2l::AutoSegmentationCriterion::forward()
    @     0x559ad1cc9e50 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl
    @     0x559ad1c636a8 main
    @     0x7fd79d574b97 __libc_start_main
    @     0x559ad1cc451a _start
Unable to allocate memory with native alloc for size 12832473088 bytes with error 'ArrayFire Exception (Device out of memory:101):
ArrayFire error:

### Platform and Hardware
v100-4gpu machine

#### Additional Context
In config file only changing ctc -> asg

#--criterion=ctc
--criterion=asg
--mfsc
--usewordpiece=true
--wordseparator=_
--labelsmooth=0.05
--dataorder=output_spiral
--inputbinsize=25
--softwstd=4
--memstepsize=5000000
--pcttraineval=1
--pctteacherforcing=99
--sampletarget=0.01
--netoptim=adadelta
--critoptim=adadelta
--lr=0.4
--lrcrit=0.4
--linseg=0
--momentum=0.0
--maxgradnorm=1.0
--onorm=target
--sqnorm
--nthread=6
--batchsize=8
#--filterbanks=80
--filterbanks=120
--minisz=200
--mintsz=2
--minloglevel=0
--logtostderr
--enable_distributed

**Comment by lunixbochs** [comment]
What's your arch?
Also, why oh why are you using 120 filterbanks?

**Comment by lunixbochs** [comment]
Actually I can answer this already. This is not a bug. I bet you're e.g. 10,000 word pieces via `--usewordpiece=true`. ASG has additional memory use based on your token size.

That means the ASG "transitions" matrix is roughly `10,000 x 10,000`, or 400MB per operation. With your batchsize of 8, this means probably at least 3GB of extra memory used? This doesn't make a lot of sense, it will be pretty inefficient and hard to train. If you're using a model like streaming convnets, most of the transitions will also be 0, because the model stride is 8.

Probably just don't use ASG with large vocab high stride models. CTC makes way more sense here.

**Comment by tlikhomanenko** [comment]
@lunixbochs thanks for the nice comment! It should be really the case of additional memory on transition matrix. Also ASG will be very slow in training if number of tokens is very huge, like 10k is (because of graph normalization term which we need to compute here).

**Comment by omprakashsonie** [comment]
Thank you everyone for your inputs.
