### ISSUE TITLE
Failed to reproduce the results on the WSJ dataset 

### ISSUE THREAD

**Issue by cyl250** [facebookresearch/wav2letter#804]
Thank you for sharing your code~

### Question
When reproducing the lexicon-free models on WSJ dataset,  I found the shared pre-trained models (including acoustic and 4-gram language models) had a 12.42 WER and 4.22 LER.  

Then I trained a new acoustic model following the same parameters in "train.cfg" , failed again to get 5.5 WER and 2.2 LER as shown in paper. 

I wonder whether I could reproduce the results shown in paper or I need to train a new 4-gram language models?

#### Additional Context
When I use the downloaded "lexicon.txt" there are many "oovs". 
When I use the cmudict.0.7.a, every predicted sentence starts with word "a" or "i".

**Comment by tlikhomanenko** [comment]
First, can you specify which version of wav2letter you are using to repro results?

Right I understand that you got 12.42 wer while in the paper we got 5.5 wer on nov92 with pretrained published models and running the decoder configs?

**Comment by cyl250** [comment]
Thank you for the help.

Based on this image, “https://github.com/facebookresearch/wav2letter/blob/v0.2/Dockerfile-CUDA” , I prepared my experimental environment.

yes, it's.  following this decoder configs "recipes/models/lexicon_free/wsj/decoder_word_4gram.cfg", I got 12.42 WER on nov92 with pretrained published models.

**Comment by tlikhomanenko** [comment]
From the published version of the paper we modified a bunch of things in the decoder, even some flags renaming. Either you can try to track changes or do the decoding search again, or use this image (where all research was done) `sudo docker run --runtime=nvidia --rm -itd --ipc=host --name lexfree wav2letter/wav2letter:lexfree`

**Comment by cyl250** [comment]
Thanks for help, it works very well.
When I use the right image, I could get the same results in 4-gram language model. 

However, when I use "lm_wsj_convlm_word_14B",  I could get 3.8 WER. Do I need a grid search to get better results?

And When I use "lm_wsj_convlm_char_20B", I met this Error:
I0901  07:07:29.580243 1565 Decode.cpp:292 [ConLM]: loading LM from `pwd`/lm_wsj_convlm_char_20B.bin
E0901 07:07:29.580243 1565 Seial.h:74]  Error while loading: Failed to read 41943040 bytes from input stream! Read 4181150.

**Comment by tlikhomanenko** [comment]
Didn't have time to look at it. Let me try to repro this error. One thing is to use the fairseq model which I published to and run converting by yourself as I pointed in the recipe. Could you try it? Here is fairseq model https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/lm/lm_librispeech_convlm_char_20B.pt and here is how one can convert https://github.com/facebookresearch/wav2letter/blob/v0.2/recipes/models/lexicon_free/librispeech/convert_convlm.sh

**Comment by cyl250** [comment]
Thanks for your advice~.
It works well when I used "convert_convlm.sh" to convert "lm_wsj_convlm_char_20B.pt " (downloaded)  to "lm_wsj_convlm_char_20B.bin".

**Comment by cyl250** [comment]
Thanks for your advice~.
It works well when I used "convert_convlm.sh" to convert "lm_wsj_convlm_char_20B.pt " (downloaded)  to "lm_wsj_convlm_char_20B.bin".
