### ISSUE TITLE
[How can I use mel-spectrogram as features?]

### ISSUE THREAD

**Issue by mlexplore1122** [facebookresearch/wav2letter#805]
### Question
I have checked in Defines.cpp file, and just see wav2letter using mfsc, or mfcc feature, and don't have option for using mel-spectrogram as feature? I need use mel-spectrograms as feature?
And I wanna ask how can i use mel-spectrogram as feature in wav2letter, thanks you.

**Comment by lunixbochs** [comment]
mfsc and mfcc are both variants of mel spec. mfcc is mfsc with a DCT. mfsc works fine.

**Comment by mlexplore1122** [comment]
Thanks lunixbochs
I know mfsc and mfcc are both variants of mel spec, but I don't deep understand the difference of each feature. My language has tone, so pitch feature is important. I have train my dataset with nemo(quartznet network) and transformer with espnet and both have fast converge and good result. But all feature they use is mel spectrogram, and I am not sure, problem when i train model with streaming convnet is feature or about difference about architecture of network. 
Do you have any suggest?

**Comment by tlikhomanenko** [comment]
Probably the issue with the architecture and its hyperparameters for your data. So you need to tweak model size, optimization to make it work with your data.
