### ISSUE TITLE
pre-trained model | Train | Fork | Decoder

### ISSUE THREAD

**Issue by Dr-AyanDebnath** [facebookresearch/wav2letter#806]
### Question#1
I have my own English dataset. I wished to use "fork" for training (TDS using seq2seq criterion) on my dataset using a pre-trained English model (am_TDS_s2s_clean) https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019
I have used train.cfg (train_am_tds_s2s.cfg) [train_am_tds_s2s.cfg.txt](https://github.com/facebookresearch/wav2letter/files/5141821/train_am_tds_s2s.cfg.txt) as shown in the link(https://github.com/facebookresearch/wav2letter/files/5141796/train_am_tds_s2s.cfg.txt)
and network.arch [network_am_tds_s2s.arch.txt](https://github.com/facebookresearch/wav2letter/files/5141809/network_am_tds_s2s.arch.txt) as shown in link https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/am_arch/am_tds_s2s.arch

I used the command  mpirun --allow-run-as-root -n 4 /root/wav2letter/build/Train fork [path to pre-trained model.bin] -enable_distributed true --flagsfile [path to train.cfg]  --minloglevel=0 --logtostderr=1

It is providing following error
```
I0828 07:27:01.567111  2358 Train.cpp:114] Parsing command line flags
I0828 07:27:01.567134  2358 Train.cpp:115] Overriding flags should be mutable when using `fork`
I0828 07:27:01.567153  2358 Train.cpp:120] Reading flags from file/home/pre_trained_model/train_am_tds_s2s.cfg
terminate called after throwing an instance of 'std::runtime_error'
  what():  FileStore set: file create failed: /checkpoint/qiantong/ls_200M/do0.15_l5.6.10_mid3.0_incDO/4_rndv/.10210577316483720853
terminate called after throwing an instance of 'std::runtime_error'
```

The full error is [error.txt](https://github.com/facebookresearch/wav2letter/files/5141838/error.txt)

**Question** is which flags should I remove from train.cfg? how to know which are the overriding flags while using fork.

### Question#2
Since fork was not working, I also tried using the Train command to do training from scratch using the above-mentioned network.arch and train.cfg. It started training for epoch#1 and stopped at epoch#2.

I0828 06:34:19.184639  2182 Train.cpp:564] Shuffling trainset
I0828 06:34:19.775981  2182 Train.cpp:571] Epoch 1 started!
I0828 06:40:40.005527  2182 Train.cpp:345] epoch:        1 | nupdates:            4 | lr: 0.058901 | lrcriterion: 0.058901 | runtime: 00:00:12 | bch(ms): 3082.95 | smp(ms): 85.55 | fwd(ms): 1240.59 | crit-fwd(ms): 401.26 | bwd(ms): 1233.52 | optim(ms): 362.15 | loss:  232.60042 | train-LER:  0.00 | train-WER:  0.00 | /home/english_data/lists1/dev1.lst-loss:  112.75320 | /home/english_data/lists1/dev1.lst-LER: 538.68 | /home/english_data/lists1/dev1.lst-WER: 1054.08 | avg-isz: 1180 | avg-tsz: 023 | max-tsz: 048 | hrs:    0.21 | thrpt(sec/sec): 61.26
Memory Manager Stats
MemoryManager type: CachingMemoryManager
Number of allocated blocks:455
Size of free block pool (small):56
Size of free block pool (large):185
Total native mallocs:234
Total native frees:0
I0828 06:40:42.630482  2182 Train.cpp:728] Finished window pretraining.
I0828 06:40:42.639550  2182 Train.cpp:564] Shuffling trainset
I0828 06:40:43.156523  2182 Train.cpp:571] Epoch 2 started!
```
Unable to allocate memory with native alloc for size 12582912 bytes with error 'ArrayFire Exception (Device out of memory:101):
ArrayFire error:
In function fl::MemoryManagerInstaller::MemoryManagerInstaller(std::shared_ptr<fl::MemoryManagerAdapter>)::<lambda(size_t)>
In file /root/flashlight/flashlight/memory/MemoryManagerInstaller.cpp:188'Unable to allocate memory with native alloc for size 44040192 bytes with error 'ArrayFire Exception (Device out of memory:101):
ArrayFire error:
In function fl::MemoryManagerInstaller::MemoryManagerInstaller(std::shared_ptr<fl::MemoryManagerAdapter>)::<lambda(size_t)>
In file /root/flashlight/flashlight/memory/MemoryManagerInstaller.cpp:188'terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Device out of memory:101):
In function virtual void* MemoryManagerFunctionWrapper::alloc(bool, unsigned int, dim_t*, unsigned int)
In file src/api/c/memory.cpp:684

```
The full error is [error_training.txt](https://github.com/facebookresearch/wav2letter/files/5141864/error_training.txt)

**Question** is how to solve this issue? It is very strange that I faced this issue every time I start training from scratch using various other training criteria.

### Question#3
while decoding on my test.lst with pre-trained model using [deoder.cfg.txt](https://github.com/facebookresearch/wav2letter/files/5141946/deoder.cfg.txt) https://github.com/facebookresearch/wav2letter/blob/master/recipes/models/sota/2019/librispeech/decode_tds_s2s_ngram_clean.cfg 
The error is 
```
failed to open file for reading: /home/pre_trained_model_librispeech/am_tds_s2s_librispeech_dev_clean.bin
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open file for reading: /home/pre_trained_model_librispeech/am_tds_s2s_librispeech_dev_clean.bin
*** Aborted at 1598616307 (unix time) try "date -d @1598616307" if you are using GNU date ***
```
**Question** is how to oslve the issue though I have pre-trained am model (am_tds_s2s_librispeech_dev_clean.bin) in the path mentioned.

**Comment by tlikhomanenko** [comment]
> Question#1

You need to set reset the flag `--rndv_filepath=` to empty, this one we used to do sync of GPUs, while you are running with MPI and you don't need it, but it still tries to read its filepath. The flags in config will overwrite those in the saved model.

> Question#2

Please debug what is happening with your GPU memory (like watching nvidia-smi). It could be too large batch / model / input audio. First try to reduce batch, check what is the longest audio in your data and try to restrict used samples with max input/target length with flags `maxisz` and `maxtsz`.

> Question#3

The error definitely about opening the file itself. Could you copy paste the file path from the error log and do ls on it, just to be sure file exists (and no typo in the filename)?

**Comment by Dr-AyanDebnath** [comment]
Thanks, @tlikhomanenko for your suggestion.

###Question#1
I set--rndv_filepath= to empty, maxisz=2000 , maxtsz=150 and started training using fork. But it is throwing error in 2nd epoch after running for almost 8 hours.

I0901 14:26:06.072155  3627 Train.cpp:728] Finished window pretraining.
I0901 14:26:06.594415  3627 Train.cpp:571] Epoch 2 started!
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDNN_STATUS_EXECUTION_FAILED
*** Aborted at 1599002290 (unix time) try "date -d @1599002290" if you are using GNU date ***
PC: @     0x7f10433d9e97 gsignal
*** SIGABRT (@0xe2e) received by PID 3630 (TID 0x7f1088ca9380) from PID 3630; stack trace: **


I would like to ask:
1. What is window pre-training (it always appear in epoch#1 ?
2. How to solve CUDNN_STATUS_EXECUTION_FAILED error. I am using docker (wav2letter/wav2letter:cuda-latest) on 4 GPUS (GeForce RTX).
This is watch nvidia-smi when training was going on
![nvidia-smi](https://user-images.githubusercontent.com/57833226/92029167-c67f8a00-ed82-11ea-825f-a82d8ccb922c.jpg)

This is watch nvidia-smi when training stopped
![nvidia-smi_o](https://user-images.githubusercontent.com/57833226/92029213-dc8d4a80-ed82-11ea-8efb-742f58f52332.jpg)


###Question#2,3
Thanks for the solution. The path I mentioned was wrong (typo).

**Comment by tlikhomanenko** [comment]
In case of s2s we are learning attention, and at the beginning it is hard to learn, that is why for first updates we have forced like diagonal attention matrix. After it finished that epoch start normally without this additional diagonal matrix. If you set pretraining say 10 updates, then 10 batches will be used for this pretraining step. Then all the data will be prepared for new epoch. 

About your error - this could be anything, do you have full stack of the error printed on the screen? You can try at first take 100 random samples from the data and just run to be sure everything is fine.
