### ISSUE TITLE
Python bindings instillation issue

### ISSUE THREAD

**Issue by amant555** [facebookresearch/wav2letter#810]
I am trying to install python bindings in linux environment(Ubuntu). Already done with ArrayFire and Kenlm and rest of dependencies required for python bindings mentioned in doc. 
When I call the pip install -e . it exits with status code 1. 
Do I need to install flashlight too?
It's not given in the requirements but the setup.py call cmake in wav2letter root folder where it return error for flashlight after that for MKL. 

Don't know if doing something wrong but really need some help with installing the python bindings.

Once again,
I have tried with building wav2letter first.
All the dependencies are installed. 
Followed the steps written for python bindings exactly.

Still it fails

**Comment by tlikhomanenko** [comment]
Hey @amant555 

Several things:
- you don't need to install flashlight and arrayfire
- it still calling Cmake, yes, but calling building only necessary parts which doesn't depend on the flashlight and arrayfire.
- could you remove build folder from the `bindings/python`, run inside `pip install -e .` and send me all log which appears on your screen after this command?

**Comment by amant555** [comment]
Hi @tlikhomanenko,
These are the logs that I get when I run `pip install -e .` I run this after I install KenLM using:
```
sudo apt-get install liblzma-dev libbz2-dev libzstd-dev
git clone https://github.com/kpu/kenlm.git
cd kenlm
mkdir -p build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DKENLM_MAX_ORDER=20 -DCMAKE_POSITION_INDEPENDENT_CODE=ON
make -j16
# don't forget to export KENLM_ROOT_DIR
```
**Logs:**
Obtaining file:///content/wav2letter/bindings/python
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/content/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by amant555** [comment]
Hi @tlikhomanenko 
I handled it just some minor error and confusion from Arrayfire and flashlight. 

Thanks for the quick reply and help.
