### ISSUE TITLE
Question about group conv in TDS block use in streaming conv?

### ISSUE THREAD

**Issue by trangtv57** [facebookresearch/wav2letter#811]
last week, I want to understand detail about streaming conv architecture and i read more about TDSBlock.cpp, and I read in paper that TDSBlock using group conv for small parameter, but in file code I just see your config in conv2D group = 1, not like you using group conv. So I don't know it's my wrong understand or missing something. 
[Detail]
I just print dimension of input array is input of network has shape (76, 80, 1, 8) (76 is time step, 80: feature, 1: expand dimension for conv2d, and 8 is batch size)
and I see config in file [am_500ms_future_context.arch ](https://github.com/facebookresearch/wav2letter/blob/v0.2/recipes/models/streaming_convnets/librispeech/am_500ms_future_context.arch) that using first conv2d(1, 15, 10, 1, 2, 1, 0, 0) mean: 1: input feature, 15: output feature, 10: kernel size x, 1, kernel size y, 2: stride x, 1 stride y, and no mention about groups so default groups=1. 
And same in setting of TDSBlock(15, 9, 80, 0.1, 0, 1, 0) 15: channel, 9: kernel size, 80 width, 0.1: dropout, ...) and first conv2d in TDSblock is: conv2d(15, 15, 9, 1, 1, 1, padding, 0); and no mention about groups too. 
So pls correct me if i'm wrong. 
Thank you very much.

**Comment by vineelpratap** [comment]
Hi, 
 TDS uses **1D** group convolutions. This can be expressed using 2D conv block without any `groups` option specified.

**Comment by trangtv57** [comment]
thank you @vineelpratap 
I try to understand what you said? But I can't figured out what is?
Can you explain more detail about how to use 2D conv as 1D group conv withoutt groups option specified?
I have an example:
tensor_1 has shape: (76, 64, 1, 8) 
tensor_2 has shape: (76, 1, 64, 8)
conv2d_1 (1, 1, 33, 1, 1, 1, ,16, 0, 1, 1, false, 1) // group 1
conv2d_2(64, 64, 33, 1, 1, 1, 16, 0, 1, 1, false, 64) // group 64
output result when using conv2d_1 with tensor_1 is equal as output result when using conv2d_2. But I don't think the logic of math is same. 
Thanks again

**Comment by hellomotor** [comment]
I have the same question, can you explain more detail please? @vineelpratap
