### ISSUE TITLE
difficult to reproduce "wav2vec features" as input

### ISSUE THREAD

**Issue by cyl250** [facebookresearch/wav2letter#816]
### Question
Hi, Thanks for sharing your code.
I  found that I had difficulty to reproduce the "wav2vec" results when using h5data as input?
Is there any advice for me?
Thank you~

**Comment by tlikhomanenko** [comment]
We don't support wav2vec inside current codebase, possibly someone from the community is working/trying it.

**Comment by padentomasello** [comment]
Hi @cyl250, wanted to share https://github.com/facebookresearch/wav2letter/issues/832 with you. It appears @phamvandan is trying to use wav2vec features as input.
