### ISSUE TITLE
zcat on macOS always appends a .Z to the filename (better use gunzip -c)

### ISSUE THREAD

**Issue by juancq** [facebookresearch/wav2letter#82]
I ran convert-arpa.lua on macOS 10.13.5 and got the following error:
```bash
zcat: can't stat: 3-gram.pruned.3e-7.arpa.gz (3-gram.pruned.3e-7.arpa.gz.Z): No such file or directory. 
```
I found the solution in another [github thread](https://github.com/dalibo/pgbadger/issues/70). It seems that zcat on macOS always appends .Z to all filenames. The proposed solution is to use gunzip -c. 

Changing line 67 in convert-arpa.lua to the following fixed the issue: 
```ruby
ifarpa = io.popen(string.format('gunzip -c %s', opt.arpasrc))
```

**Comment by andresy** [comment]
Closing as we do not support the lua version of wav2letter anymore.

**Comment by unacceptable** [comment]
@juancq `gunzip -c` worked like a champ for me.  You're a gentleman and a scholar. 🙂

**Comment by sarnobat** [comment]
I have this issue with log4j RollingFile too. If anyone's wondering, `gunzip -c` is a drop-in replacement:
```
     -c, --stdout, --to-stdout
                       This option specifies that output will go to the standard output stream, leaving files intact.
```
You don't have to unzip, and then perform cat as my initial reaction feared.

Other commands like `zless` continue to work.
