### ISSUE TITLE
Must long utterances be physically segmented before processing?

### ISSUE THREAD

**Issue by picheny-nyu** [facebookresearch/wav2letter#824]
### Question
Many speech corpora (e.g. Broadcast News and Switchboard) are provided as long utterances with time marks that indicate the beginning and ends of segments. Packages such as Kaldi allow one to provide the segmentation marks so that the long utterances do not need to physically segmented before processing. Does wav2letter have this capability? The documentation suggests that all audio must be physically segmented....

Thanks
Michael

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
Hi @picheny-nyu,

currently we don't support this option. Also it is the question of efficiency: doing reading of the full file and then cutting it on fly each time - could be not so efficient than pre-segmented audio. If you want I can point to the code, where you could add this support.

**Comment by picheny-nyu** [comment]
The way this is often implemented is to cache the file and replace it with the next one. If you jump around a lot it is obviously more problematical, of course :-). Yes, it would be useful if you could point me to the code. Thanks!

**Comment by tlikhomanenko** [comment]
Here you could extend the reading info from the file https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/W2lListFilesDataset.cpp#L101 and add storing the start and end time stamps. Here you need to propagate that info https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/W2lListFilesDataset.cpp#L80 along with sample id and audio file. Result of this function is used then in featurization called in the https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/W2lDataset.cpp#L75. So finally you need to fix featurization logic here https://github.com/facebookresearch/wav2letter/blob/v0.2/src/data/Featurize.cpp#L78 before this row you can cut the data in a necessary way using propagated info about segment you need.

**Comment by picheny-nyu** [comment]
Thanks!  Will have a look, though in the short term I may just segment the corpus of interest myself to get going as I am a bit rusty programming-wise, but I think this is a very useful feature to have - many speech corpora are like this. Also note that if you are processing the file sequentially it is often better to grab a big file at once than a lot of small files especially if the data is not local....I guess I could implement a cache of some sort with multiple files up to some memory limit.

**Comment by tlikhomanenko** [comment]
We have prefetching for the dataset.

@vineelpratap probably you can give some comments on this.

**Comment by vineelpratap** [comment]
Hi, 
 Yes, this is currently not supported at the moment from master. We would like to support it at some point but currently it is not in our priority. 
 Manually segmenting the dataset might be the best way to do it for now. If this is something not feasible for your use case, I could give you some code pointers on how to modify the wav2letter code to achieve the behavior you want.
