### ISSUE TITLE
Maybe sota/2019/raw_lm_corpus/get_titles.py has a bug

### ISSUE THREAD

**Issue by xiaosdawn** [facebookresearch/wav2letter#825]
Hi, I found that the parameter `CACHE_PATH` did not work when passed to the subfuction `def get_one_title(book_id)` https://github.com/facebookresearch/wav2letter/blob/v0.2/recipes/models/sota/2019/raw_lm_corpus/get_titles.py#L49
Maybe adding `global CACHE_PATH` to https://github.com/facebookresearch/wav2letter/blob/v0.2/recipes/models/sota/2019/raw_lm_corpus/get_titles.py#L48 can make the parameter `CACHE_PATH` work.
Maybe it was because of my inconsistent operation that I found the problem. If this is not a bug, please ignore it. THX.

**Comment by tlikhomanenko** [comment]
did you specify the python running script with flag `--cachepath`? if no, then it will be empty.

**Comment by xiaosdawn** [comment]
Yes, I had given specific `--cachepath` when running script. But it did not work (It was empty). Then I added `global CACHE_PATH` before `CACHE_PATH = args.cachepath`. It worked.

**Comment by tlikhomanenko** [comment]
I see now. Correct, this is python behaviour on global var change. Thanks for reporting this, will send a quick fix for this.
