### ISSUE TITLE
How to install on Jetson Nano?

### ISSUE THREAD

**Issue by laohur** [facebookresearch/wav2letter#827]
### Question
How to install on Jetson Nano?
on cuda ?
on cpu ?

#### Additional Context
OpenBLAS ok!
cereal ok!
kenlm ok!
arrayfire binary ok!  (ArrayFire-v3.5.1_Linux_aarch64.sh  not compatible)
arrayfire compile failed for no nccl (on cuda)
flashlight failed! 
wav2letter 

## solution
cmake Only compile CUDA, not cpu/opencl
compile others: gtest ...

**Comment by tlikhomanenko** [comment]
You need to install all dependancies, please create issues in arrayfire directly if you have trouble to install it. If you succesfully installed all dependencies and have trouble with flashlight, please post full log of cmake and make errors which you have.

Other options install only docker and use docker images.
