### ISSUE TITLE
How to use parameters in the pretrained model except the last layer?

### ISSUE THREAD

**Issue by DongChanS** [facebookresearch/wav2letter#829]
### Question
I want to use pretrained model in the `recipes` folder.

But, since my language is not english, the number of tokens is different to that model.

So, to conduct transfer learning, i should copy the parameters except the last layer.   

How to use parameters in the pretrained model except the last layer??

**Comment by padentomasello** [comment]
Hi @DongChanS, thanks for the question. One way I think you can do this would be to:

First, load pretrained model as we do when we use the Fork mode: 

https://github.com/facebookresearch/flashlight/blob/4584567aaca14aebc0cf317e3d1c512bf21108bc/app/asr/Train.cpp#L252

Second, create a new model with all the same layers except for the last. (You can do this using a similar archfile a initial model, and `buildSequentialModel` as in https://github.com/facebookresearch/flashlight/blob/4584567aaca14aebc0cf317e3d1c512bf21108bc/app/asr/Train.cpp#L229

Third, iterate through all the parameters of the pretrained model, except for the last, using the method https://fl.readthedocs.io/en/latest/modules.html#_CPPv4NK2fl6Module5paramEi, 
and set them in the new model using the method https://fl.readthedocs.io/en/latest/modules.html#_CPPv4N2fl6Module9setParamsERK8Variablei

**Comment by DongChanS** [comment]
Thanks you!!
I modify `train.cpp` as you told, it worked fine!

```c++
  } else if (runStatus == kForkMode) {
  //   std::unordered_map<std::string, std::string> cfg; // unused
  //   W2lSerializer::load(reloadPath, cfg, network, criterion);

    // refer https://github.com/facebookresearch/wav2letter/issues/829
    // fork pretrained model
    std::shared_ptr<fl::Module> PretrainedNetwork;
    std::unordered_map<std::string, std::string> cfg; // unused
    W2lSerializer::load(reloadPath, cfg, PretrainedNetwork, criterion);

    // load surrogate model
    auto archfile = pathsConcat(FLAGS_archdir, FLAGS_arch);
    LOG_MASTER(INFO) << "Loading architecture file from " << archfile;
    auto numFeatures = getSpeechFeatureSize();
    network = createW2lSeqModule(archfile, numFeatures, numClasses);

    // copy parameters to surrogate model
    int SquashedNetworkParamSize = network->params().size();
    for (int position=0; position < SquashedNetworkParamSize; position++){
      fl::Variable PretrainedParamGivenPosition = PretrainedNetwork->param(position);
      fl::Variable ParamGivenPosition = network->param(position);
      // Validate paramater attributes
      // 1. parameter type
      if (ParamGivenPosition.type() != PretrainedParamGivenPosition.type()){
        LOG_MASTER(INFO) << "[Warning] Types of two variables are different.";
        break;
      } 
      // 2. parameter dimension
      if (ParamGivenPosition.dims() != PretrainedParamGivenPosition.dims()){
        LOG_MASTER(INFO) << "[Warning] dimensions of two variables are different.";
        break;
      }
      // setParams
      network->setParams(PretrainedParamGivenPosition, position);
    }
```

**Comment by DongChanS** [comment]
Thanks!!
it works well.

**Comment by padentomasello** [comment]
Glad to hear! Will close this issue.
