### ISSUE TITLE
Missing newline in README under subsection "Running the decoder (inference)" 

### ISSUE THREAD

**Issue by juancq** [facebookresearch/wav2letter#83]
In the README, under subsection **"Running the decoder (inference)"**, the wget command should have a newline before luajit. 

Currently it reads as follows:
<pre>
wget http://www.openslr.org/resources/11/3-gram.pruned.3e-7.arpa.gz <b>luajit</b>
~/wav2letter/data/utils/convert-arpa.lua ~/3-gram.pruned.3e-7.arpa.gz ...
</pre>

Should be changed to: 
<pre>
wget http://www.openslr.org/resources/11/3-gram.pruned.3e-7.arpa.gz 
<b>luajit</b> ~/wav2letter/data/utils/convert-arpa.lua ~/3-gram.pruned.3e-7.arpa.gz ...
</pre>

For those of us who tend to follow blindly and copy/paste from the documentation.

**Comment by vineelpratap** [comment]
Hey thanks! I have fixed it.
