### ISSUE TITLE
Low thrpt(sec/sec) when training conv_glu with asg

### ISSUE THREAD

**Issue by tetiana-myronivska** [facebookresearch/wav2letter#835]
### Question
I am getting low thrpt(sec/sec) when training conv_glu with ASG criterion, and one epoch takes 18 hours to run. Could you please let me know if this kind of thing is expected and how to increase the thrpt (if it's possible to increase it)?

```
epoch:        1 | lr: 0.050000 | lrcriterion: 0.006000 | runtime: 18:15:07 | bch(ms): 3119.73 | smp(ms): 0.56 | fwd(ms): 777.44 | crit-fwd(ms): 6.66 | bwd(ms): 2276.63 | optim(ms): 40.44 | loss:   14.90907 | train-TER: 96.05 | train-WER: 99.70 | dev.tsv-loss:   13.02363 | dev.tsv-TER: 93.04 | dev.tsv-WER: 99.83 | avg-isz: 440 | avg-tsz: 099 | max-tsz: 269 | hrs: 1237.23 | thrpt(sec/sec): 67.79
```

#### Additional Context
Running ~1000 hours of audio on four Tesla T4 GPUs, forking from conv_glu pretrained librispeech model
config
```
--tokensdir=/root/data/w2v/
--tokens=tokens.txt
--lexicon=/root/data/w2v/lexicon.txt
--arch=conv_glu/network.arch
--criterion=asg
--lr=0.6
--lrcrit=0.006
--onorm=target
--sqnorm=true
--mfsc=true
--nthread=32
--batchsize=12
--transdiag=4
--iter=80
--maxgradnorm=0.2
--replabel=2
--surround=|
--minloglevel=0
--linseg=1
--momentum=0.8
--logtostderr=1
```

**Comment by vineelpratap** [comment]
Hi, 
 The training is slow because of the following reasons - 

1. the model for librispeech is quite large with 200M params. You might have to use our more recent architeccture using TDS that can be faster - https://github.com/facebookresearch/wav2letter/blob/master/recipes/seq2seq_tds/librispeech/network.arch .  Note that it uses `--mfsc 80` instead of 40 log mel features that  `conv_glu` recipe uses. 
2. Tesla T4 GPUs are slow compared to Tesla V100 GPUs that we typically use to train. See ` fwd(ms)` in the logs.
3. Networking communication seems to be slow. See ` bwd(ms) vs  fwd(ms)` in the logs.

**Comment by tetiana-myronivska** [comment]
hi @vineelpratap. Thank you for your answer, greatly appreciate it. I will try out TDS and switch to Tesla V100 GPUs.

**Comment by tetiana-myronivska** [comment]
@vineelpratap for finetuning the TDS model, would you recommend using the most recent binary https://github.com/facebookresearch/wav2letter/tree/master/recipes/seq2seq_tds/librispeech#acoustic-models or the SOTA one https://github.com/facebookresearch/wav2letter/tree/master/recipes/sota/2019#pre-trained-acoustic-models? I can see that their sizes differ considerably (185 MB for the recent one and 1.5GB for SOTA).

**Comment by vineelpratap** [comment]
Hi, 
 I would start with the model in the first link `seq2seq_tds` to access what the throughput looks like for your setup. The ones in `sota/2019` have relatively larger number of parameters and will be a bit slower compared to the above. However, in terms of performance, the models in `sota/2019` should give better performance. 

You can also play around with the architectures in  `sota/2019` and reduce #layers or #channels to find the best throughput/WER trade-off for your system.

**Comment by tetiana-myronivska** [comment]
@vineelpratap that makes a lot of sense, thank you. I am aiming for performance, so decided to go with the sota ones. It already got to a decent WER 8.57 on the dev set.
Now I want to compare the librispeech word piece tokens set with ours. Is there a script in the repo that generates the word piece tokens set from the custom dataset?  I can see that this script https://github.com/facebookresearch/wav2letter/blob/master/recipes/utilities/prepare_librispeech_wp_and_official_lexicon.py does it for librispeech.

**Comment by tlikhomanenko** [comment]
here is the preparation of word-pieces happens https://github.com/facebookresearch/wav2letter/blob/master/recipes/utilities/prepare_librispeech_wp_and_official_lexicon.py#L89. We are using https://github.com/google/sentencepiece, so you can simply adapt code from our librispeech script or directly use https://github.com/google/sentencepiece to do so.

**Comment by tetiana-myronivska** [comment]
@tlikhomanenko thank you for the info! It was quite easy to adapt the script to build custom tokens vocab.
Closing the issue now.
