### ISSUE TITLE
python bindings - error.

### ISSUE THREAD

**Issue by SvPolina** [facebookresearch/wav2letter#850]
### Question
I'm trying to build python bindings for the fairseq model.

While running 
pip install  -e . ,  
I'm getting the following error:

#### Additional Context
Created temporary directory: /tmp/pip-ephem-wheel-cache-mzc0hlse
Created temporary directory: /tmp/pip-req-tracker-9odjyc2t
Created requirements tracker '/tmp/pip-req-tracker-9odjyc2t'
Created temporary directory: /tmp/pip-install-nhtlu5w_
Obtaining file:///content/gdrive/My%20Drive/gdrive/wav2letter/bindings/python
  Added file:///content/gdrive/My%20Drive/gdrive/wav2letter/bindings/python to build tracker '/tmp/pip-req-tracker-9odjyc2t'
    Running setup.py (path:/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py) egg_info for package from file:///content/gdrive/My%20Drive/gdrive/wav2letter/bindings/python
    Running command python setup.py egg_info
    running egg_info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
  Source in /content/gdrive/My Drive/gdrive/wav2letter/bindings/python has version 0.0.2, which satisfies requirement wav2letter==0.0.2 from file:///content/gdrive/My%20Drive/gdrive/wav2letter/bindings/python
  Removed wav2letter==0.0.2 from file:///content/gdrive/My%20Drive/gdrive/wav2letter/bindings/python from build tracker '/tmp/pip-req-tracker-9odjyc2t'
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
    Running command /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
    -- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Checking for [Accelerate]
    -- Checking for [vecLib]
    -- Checking for [cblas - atlas]
    -- Includes found
    -- Looking for cblas_dgemm
    -- Looking for cblas_dgemm - found
    -- CBLAS Symbols FOUND
    -- CBLAS library found
    -- CBLAS found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libcblas.so;/usr/lib/x86_64-linux-gnu/libatlas.so)
    -- Found FFTW: /usr/include
    -- FFTW found
    -- Looking for KenLM
    -- Using kenlm library found in /content/gdrive/My Drive/gdrive/kenlm
    -- Using kenlm utils library found in /content/gdrive/My Drive/gdrive/kenlm
    -- kenlm lm/model.hh found in /content/gdrive/My Drive/gdrive/kenlm/lm/model.hh
    -- Found kenlm: /content/gdrive/My Drive/gdrive/kenlm
    -- Found kenlm (include: /content/gdrive/My Drive/gdrive/kenlm, library: /content/gdrive/My Drive/gdrive/kenlm;/content/gdrive/My Drive/gdrive/kenlm/util)
    -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Found LibLZMA: /usr/include (found version "5.2.2")
    -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
    -- Looking for BZ2_bzCompressInit
    -- Looking for BZ2_bzCompressInit - found
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    WARNING: Target "wav2letter-libraries" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "wav2letter-libraries" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_feature" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_feature" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_decoder" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_decoder" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_criterion" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_criterion" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_common" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "_common" requests linking to directory "/content/gdrive/My Drive/gdrive/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
    -- Generating done
    -- Build files have been written to: /content/gdrive/My Drive/gdrive/wav2letter/bindings/python/build/temp.linux-x86_64-3.6
    Scanning dependencies of target pybind11
    Scanning dependencies of target CUB
    [ -1%] Creating directories for 'pybind11'
    [ -1%] Creating directories for 'CUB'
    [ -1%] Performing download step (git clone) for 'pybind11'
    [  0%] Performing download step (git clone) for 'CUB'
    Cloning into 'pybind11'...
    Cloning into 'CUB'...
    Checking out files: 100% (214/214), done.
    error: Your local changes to the following files would be overwritten by checkout:
    	tools/check-style.sh
    Please commit your changes or stash them before you switch branches.
    Aborting
    CMake Error at /content/gdrive/My Drive/gdrive/wav2letter/bindings/python/build/temp.linux-x86_64-3.6/bindings/python/pybind11/tmp/pybind11-gitclone.cmake:75 (message):
      Failed to checkout tag: '9a19306fbf30642ca331d0ec88e7da54a96860f9'

    bindings/python/CMakeFiles/pybind11.dir/build.make:89: recipe for target 'bindings/python/pybind11/src/pybind11-stamp/pybind11-download' failed
    make[2]: *** [bindings/python/pybind11/src/pybind11-stamp/pybind11-download] Error 1
    CMakeFiles/Makefile2:489: recipe for target 'bindings/python/CMakeFiles/pybind11.dir/all' failed
    make[1]: *** [bindings/python/CMakeFiles/pybind11.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    Checking out files: 100% (176/176), done.
    Note: checking out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at c3cceac1 update readme to 1.8.0
    M	experimental/spmv_script.sh
    [  0%] Performing update step for 'CUB'
    [  1%] No patch step for 'CUB'
    [  2%] No configure step for 'CUB'
    [  2%] No build step for 'CUB'
    [  3%] No install step for 'CUB'
    [  3%] Completed 'CUB'
    [  3%] Built target CUB
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py", line 113, in <module>
        zip_safe=False,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py", line 48, in run
        self.build_extensions()
      File "/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py", line 95, in build_extensions
        ["cmake", "--build", "."] + build_args, cwd=self.build_temp
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-9odjyc2t'
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 851, in install
    install_options, global_options, prefix=prefix,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 700, in install_editable
    cwd=self.unpacked_source_directory,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py'"'"'; __file__='"'"'/content/gdrive/My Drive/gdrive/wav2letter/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

Could anyone please clarify the source of it and what can be done? 

Thanks in advance.

**Comment by tlikhomanenko** [comment]
Please, have a look here https://github.com/facebookresearch/wav2letter/issues/847. You have the same error.

**Comment by SvPolina** [comment]
Hi @tlikhomanenko,

Thanks for answering.
I performed exactly all the mentioned steps.

- cloned the kenlm repo
- cd kenlm
- mkdir build
- cd build
- cmake ..
- make -j 4
- cloned the wav2letter to the root dir.
- export  KENLM_ROOT_DIR=/path/kenlm . 
echo $KENLM_ROOT_DIR does give path/kenlm 
- cd path/wav2letter/bindings/python
- pip install -e .
- The structure of my directory : some_path ->kenlm,wav2letter, fairseq

and the error remains the same.....

**Comment by tlikhomanenko** [comment]
Ok, you have problem on checkouting the pybind version here https://github.com/facebookresearch/wav2letter/blob/v0.2/cmake/Buildpybind11.cmake#L4. Could you say what version of cmake do you have?

**Comment by SvPolina** [comment]
Hi,  
cmake version : 3.12.0
I also tried 3.10.2 .
Got the same error with both.

**Comment by jinggaizi** [comment]
i got the similar error, just with mkl
cmake .. -DCMAKE_BUILD_TYPE=Release -DMKL_LIBRARIES=/opt/intel/mkl/lib/intel64/ -DKENLM_ROOT=/root/kenlm -DMKL_INCLUDE_DIR=/opt/intel/mkl/include/


WARNING: Target "fl_imageNetResnet34" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "flashlight-app-imgclass" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "fl_asr_decode" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "flashlight-app-asr" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "flashlight-app-asr" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "fl-libraries" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "flashlight" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "fl_asr_test" requests linking to directory "/opt/intel/mkl/lib/intel64/".  Targets may link only to libraries.  CMake is dropping the item.
...
i try set MKLROOT=/opt/intel/mkl and the warning still occurred
when i ignore the warning and make, An error will occur:

[ 53%] Building CXX object CMakeFiles/fl_asr_decode.dir/flashlight/app/asr/Decode.cpp.o
[ 54%] Linking CUDA device code CMakeFiles/fl_asr_decode.dir/cmake_device_link.o
[ 54%] Linking CXX executable bin/asr/fl_asr_decode
libflashlight-app-asr.a(ctc_entrypoint.cu.o)：在函数‘compute_ctc_loss’中：
tmpxft_0004a2c5_00000000-5_ctc_entrypoint.cudafe1.cpp:(.text+0x260)：对‘omp_set_num_threads’未定义的引用
tmpxft_0004a2c5_00000000-5_ctc_entrypoint.cudafe1.cpp:(.text+0x361)：对‘omp_get_max_threads’未定义的引用
libfl-libraries.a(PowerSpectrum.cpp.o)：在函数‘fl::lib::audio::PowerSpectrum::batchApply(std::vector<float, std::allocator<float> > const&, int) [clone ._omp_fn.0]’中：
PowerSpectrum.cpp:(.text+0xcd8)：对‘omp_get_num_threads’未定义的引用
PowerSpectrum.cpp:(.text+0xcdf)：对‘omp_get_thread_num’未定义的引用
libfl-libraries.a(PowerSpectrum.cpp.o)：在函数‘fl::lib::audio::PowerSpectrum::batchApply(std::vector<float, std::allocator<float> > const&, int)’中：
PowerSpectrum.cpp:(.text+0x1289)：对‘GOMP_parallel’未定义的引用
libfl-libraries.a(SpeechUtils.cpp.o)：在函数‘fl::lib::audio::cblasGemm(std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> > const&, int, int)’中：
SpeechUtils.cpp:(.text+0x51c)：对‘MKL_Get_Max_Threads’未定义的引用
SpeechUtils.cpp:(.text+0x529)：对‘MKL_Set_Num_Threads_Local’未定义的引用
SpeechUtils.cpp:(.text+0x562)：对‘cblas_sgemm’未定义的引用
SpeechUtils.cpp:(.text+0x56e)：对‘MKL_Set_Num_Threads_Local’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/fl_asr_decode.dir/build.make:157: recipe for target 'bin/asr/fl_asr_decode' failed
make[2]: *** [bin/asr/fl_asr_decode] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/fl_asr_decode.dir/all' failed
make[1]: *** [CMakeFiles/fl_asr_decode.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jinggaizi** [comment]
I check CMakeCache.txt in build directory ,then find some question, just 2 lib is found, maybe the FindMKL.cmake has some question.
//Path to a library.
MKL_CDFT_LIBRARIES:FILEPATH=/opt/intel/mkl/lib/intel64/libmkl_cdft_core.so

//Path to a file.
MKL_INCLUDE_DIR:PATH=/opt/intel/mkl/include

//Path to a library.
MKL_KERNEL_libirc:FILEPATH=MKL_KERNEL_libirc-NOTFOUND

//Path to a library.
MKL_LAPACK_LIBRARIES:FILEPATH=MKL_LAPACK_LIBRARIES-NOTFOUND

//No help, variable specified on the command line.
MKL_LIBRARIES:UNINITIALIZED=/opt/intel/mkl/lib/intel64/

//Path to a library.
MKL_LIBRARIES_mkl_LIBRARY:FILEPATH=MKL_LIBRARIES_mkl_LIBRARY-NOTFOUND

//Path to a library.
MKL_LIBRARIES_mkl_gf_LIBRARY:FILEPATH=MKL_LIBRARIES_mkl_gf_LIBRARY-NOTFOUND

//Path to a library.
MKL_LIBRARIES_mkl_gf_lp64_LIBRARY:FILEPATH=MKL_LIBRARIES_mkl_gf_lp64_LIBRARY-NOTFOUND

//Path to a library.
MKL_LIBRARIES_mkl_intel_LIBRARY:FILEPATH=MKL_LIBRARIES_mkl_intel_LIBRARY-NOTFOUND

//Path to a library.
MKL_LIBRARIES_mkl_intel_lp64_LIBRARY:FILEPATH=MKL_LIBRARIES_mkl_intel_lp64_LIBRARY-NOTFOUND

//Path to a library.
MKL_SCALAPACK_LIBRARIES:FILEPATH=/opt/intel/mkl/lib/intel64/libmkl_scalapack_lp64.so

//Path to a library.
MKL_SOLVER_LIBRARIES:FILEPATH=MKL_SOLVER_LIBRARIES-NOTFOUND

**Comment by jinggaizi** [comment]
i didn't find MKL_KERNEL_libirc and MKL_SOLVER_LIBRARIES, is my MKL outdated

**Comment by Logicbloke** [comment]
First, could you try to remove build folder inside wav2letter/bindings/python do export of kenlm path as you are doing now and run pip install -e . again? Does the error still occur?

_Originally posted by @tlikhomanenko in https://github.com/facebookresearch/wav2letter/issues/847#issuecomment-703370130_

**Comment by tlikhomanenko** [comment]
@jinggaizi could you try once more with latest flashlight master (we have improved installation and fixed a bunch of bugs)? I am closing issue here, please create now issues in flashlight directly if there are troubles with current master.
