### ISSUE TITLE
Count not find Glog issue when building Flashlight. 

### ISSUE THREAD

**Issue by manojmsrit** [facebookresearch/wav2letter#857]
I am facing below issue while trying to build flash light. I installed all the necessary dependencies. Please help me regarding the same. Thank you.

```
-- Could NOT find Glog (missing: GLOG_INCLUDE_DIR GLOG_LIBRARY) 
CMake Error at app/asr/CMakeLists.txt:27 (message):
  GLOG not found
Call Stack (most recent call first):
  app/CMakeLists.txt:10 (include)
  CMakeLists.txt:250 (include)

```

**Comment by tlikhomanenko** [comment]
could you post this issue in the flashlight directly and specify all repro steps? Closing here.
