### ISSUE TITLE
Bindings folder not available

### ISSUE THREAD

**Issue by ngoel17** [facebookresearch/wav2letter#859]
https://github.com/facebookresearch/wav2letter/wiki/Building-Python-bindings. this documentation implies that the git repository should have the bindings/python folder. However I don't find that folder in the repository. Please guide.

**Comment by tetiana-myronivska** [comment]
Hi @ngoel17. You can find bindings on the branch v0.2 https://github.com/facebookresearch/wav2letter/tree/v0.2.

If you decide to go the way of running wav2letter in docker https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker, their prebuilt docker image is pulled from this branch and has the folder you are looking for.

**Comment by tlikhomanenko** [comment]
otherwise welcome on new releases where we merged flashlight and wav2letter together, python bindings now in the https://github.com/facebookresearch/flashlight, feel free to use in the new version too!
