### ISSUE TITLE
Suggestion on modifying the network architecture

### ISSUE THREAD

**Issue by sinhnn** [facebookresearch/wav2letter#86]
Dear Sir,
    I am planning using the wav2letter for vietnamese. I have read the network architecture `arch/librispeech-glu-highdropout`, it has many layers. I would like to change the architecture.
   Could you give me any suggestions?
Thank you so much.

**Comment by vineelpratap** [comment]
Hi,
 You can use the same building blocks as in the librispeech architecture (Conv layers followed by GLUs).  If your dataset is small, try to reduce the width of each layer and the total number of layers to avoid overfitting.

**Comment by sinhnn** [comment]
Dear Sir,
Thank you, I will try as your comments.
