### ISSUE TITLE
more time training after 1 epoch coredump at w2l::W2lDataset::getFeatureDataAndPrefetch()?

### ISSUE THREAD

**Issue by trangtv57** [facebookresearch/wav2letter#861]
I have training normal with small dataset 2k2 hour, and then I want to fine tune my model with some noise data augment (generate by kaldi wav-reverb..). My dataset now  approximately 5k hour. And My training seem normal at epoch 1, but at epoch 2 time for training so long, it's take 3 times more when compare with epoch 1. I recognize time forward is same as epoch 1, but backward time so long, and I don't have any idea why it's happen. It's my log:
`epoch:       29 | nupdates:       813285 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 01:07:51 | bch(ms): 265.33 | smp(ms): 3.66 | fwd(ms): 33.03 | crit-fwd(ms): 0.93 | bwd(ms): 208.90 | optim(ms): 19.74 | loss:    1.40718 | 
epoch:       29 | nupdates:       828630 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 01:12:06 | bch(ms): 281.94 | smp(ms): 1.11 | fwd(ms): 41.26 | crit-fwd(ms): 1.40 | bwd(ms): 219.14 | optim(ms): 20.19 | loss:    2.86765 | 
epoch:       29 | nupdates:       843975 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 01:21:43 | bch(ms): 319.57 | smp(ms): 3.06 | fwd(ms): 55.02 | crit-fwd(ms): 2.38 | bwd(ms): 240.66 | optim(ms): 20.56 | loss:    4.49728 | 
epoch:       29 | nupdates:       859320 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 02:19:14 | bch(ms): 544.42 | smp(ms): 42.41 | fwd(ms): 87.74 | crit-fwd(ms): 4.92 | bwd(ms): 388.86 | optim(ms): 20.63 | loss:    3.59611 |
epoch:       30 | nupdates:       874665 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 01:21:58 | bch(ms): 320.51 | smp(ms): 18.78 | fwd(ms): 32.54 | crit-fwd(ms): 0.93 | bwd(ms): 248.94 | optim(ms): 19.69 | loss:    1.72786 |
epoch:       30 | nupdates:       890010 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 02:18:53 | bch(ms): 543.10 | smp(ms): 72.61 | fwd(ms): 41.16 | crit-fwd(ms): 1.38 | bwd(ms): 400.95 | optim(ms): 19.91 | loss:    3.03516 |
epoch:       30 | nupdates:       905355 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 04:49:14 | bch(ms): 1130.98 | smp(ms): 222.97 | fwd(ms): 54.86 | crit-fwd(ms): 2.32 | bwd(ms): 804.60 | optim(ms): 19.78 | loss:    4.46928 |
epoch:       30 | nupdates:       920700 | lr: 0.400000 | lrcriterion: 0.000000 | runtime: 06:20:46 | bch(ms): 1488.86 | smp(ms): 282.84 | fwd(ms): 87.22 | crit-fwd(ms): 4.85 | bwd(ms): 1033.89 | optim(ms): 19.94 | loss:    3.5718 |`

some time, It's can broken with coredump and error message i get is: 
`ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl.cons`
Thanks you.

**Comment by trangtv57** [comment]
I think my issue is same as #277 , and I don't know how to figure out with this problem?, can you give me some idea?

**Comment by tlikhomanenko** [comment]
Could you post here the configs with which you run and also the full log of training?

**Comment by trangtv57** [comment]
sorry, I have debug with a few day, and figure out reason of killing process not relation to code or dataset itself. 
My server dataset (networking remote) has congestion because we have other access server in same time. So I will close issue, thank you
