### ISSUE TITLE
Train/Decode Model for Telephony Data

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#862]
On an Alienwaren desktop with one GPU (11GB), TDS CTC Training (I set iter=10000 for now), and Decoding went through (with lm_memory=500):

<pre>...
|T|: with these and some reenforcements of the &lt;unk&gt; and macdonalds whom he had recalled montrose fell suddenly upon argyle&apos;s country and let loose upon it all the rage of war carrying off the cattle burning the houses and putting the inhabitants to the sword
|P|: with these and some reinforcements of the ethel men and macdonalds whom he had recalled montrose fell suddenly upon argyle&apos;s country and let loose upon it all the rage of war carrying off the cattle burning the houses and putting the inhabitants to the sword
|t|: w i t h _ t h e s e _ a n d _ s o m e _ r e e n f o r c e m e n t s _ o f _ t h e _ a t h o l e m e n _ a n d _ m a c d o n a l d s _ w h o m _ h e _ h a d _ r e c a l l e d _ m o n t r o s e _ f e l l _ s u d d e n l y _ u p o n _ a r g y l e &apos; s _ c o u n t r y _ a n d _ l e t _ l o o s e _ u p o n _ i t _ a l l _ t h e _ r a g e _ o f _ w a r _ c a r r y i n g _ o f f _ t h e _ c a t t l e _ b u r n i n g _ t h e _ h o u s e s _ a n d _ p u t t i n g _ t h e _ i n h a b i t a n t s _ t o _ t h e _ s w o r d
|p|: w i t h _ t h e s e _ a n d _ s o m e _ r e i n f o r c e m e n t s _ o f _ t h e _ e t h e l _ m e n _ a n d _ m a c d o n a l d s _ w h o m _ h e _ h a d _ r e c a l l e d _ m o n t r o s e _ f e l l _ s u d d e n l y _ u p o n _ a r g y l e &apos; s _ c o u n t r y _ a n d _ l e t _ l o o s e _ u p o n _ i t _ a l l _ t h e _ r a g e _ o f _ w a r _ c a r r y i n g _ o f f _ t h e _ c a t t l e _ b u r n i n g _ t h e _ h o u s e s _ a n d _ p u t t i n g _ t h e _ i n h a b i t a n t s _ t o _ t h e _ s w o r d
[sample: test-clean-8224-274381-0008, WER: 6.81818%, LER: 1.55039%, slice WER: 3.4046%, slice LER: 1.63428%, decoded samples (thread 0): 2620]
I1007 10:16:46.345358   188 Decode.cpp:721] ------
[Decode test-clean.lst (2620 samples) in 17201.1s (actual decoding time 6.55s/sample) -- WER: 3.4046, LER: 1.63428]
</pre>

May I ask what |T|, |P|, |t|, and |p| mean? |T| is the text produced by the model when the audio is transcribed?
In addition, may I ask how to transcribe a telephony wav file (8 kHz) using this model which was trained by the default data set by wav2letter? May I also ask how to train a wav2letter model using user's data (telephony 8 kHz wav files), and transcribe a telephony wav file (8 kHz)? Thank you!

**Comment by tlikhomanenko** [comment]
see my comment here https://github.com/facebookresearch/wav2letter/issues/711.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the helpful comments! For each sample in test-clean.lst, there is a number followed the name of the audio file, for example,  it is 10435.0 for the first sample. May I ask what that number is? To transcribe wav audio files, other than the filenames for samples in test-clean.lst have .wav as their filename extension, do I need add something like --input=wav in the config? Thanks.

**Comment by ML6634** [comment]
I added --input=wav in since by default it is --input=flac. However, either way went through, at least for my case.

**Comment by ML6634** [comment]
I added --input=wav in since by default it was --input=flac. However, either way went through, at least for my case.

**Comment by tlikhomanenko** [comment]
the format of list is id for sample, its full path, duration of audio, transcription itself. 

Yep, please specify that input is wav, and make sure that `--samlerate` is 16kHz otherwise set it to correct value from you data.
