### ISSUE TITLE
python bindings error [Question title here]

### ISSUE THREAD

**Issue by insub789** [facebookresearch/wav2letter#863]
### Question

I try bindings of wav2letter in ubuntu environment, but I get the following error.

Any advice is good, so let me know how to fix this.

Obtaining file:///home/ubuntu/wav2letter/bindings/python
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/ubuntu/wav2letter/bindings/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    running develop
    running egg_info
    writing wav2letter.egg-info/PKG-INFO
    writing dependency_links to wav2letter.egg-info/dependency_links.txt
    writing top-level names to wav2letter.egg-info/top_level.txt
    reading manifest file 'wav2letter.egg-info/SOURCES.txt'
    writing manifest file 'wav2letter.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
    -- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'cblas'
    --   No package 'cblas' found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Checking for [Accelerate]
    -- Checking for [vecLib]
    -- Checking for [cblas - atlas]
    -- Includes found
    -- Looking for cblas_dgemm
    -- Looking for cblas_dgemm - found
    -- CBLAS Symbols FOUND
    -- CBLAS library found
    -- CBLAS found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libcblas.so;/usr/lib/x86_64-linux-gnu/libatlas.so)
    -- Found FFTW: /usr/include
    -- FFTW found
    -- Looking for KenLM
    -- Using kenlm library found in /home/ubuntu/kenlm/build/lib/libkenlm.a
    -- Using kenlm utils library found in /home/ubuntu/kenlm/build/lib/libkenlm.a
    -- kenlm lm/model.hh found in /home/ubuntu/kenlm/lm/model.hh
    -- Found kenlm: /home/ubuntu/kenlm
    -- Found kenlm (include: /home/ubuntu/kenlm, library: /home/ubuntu/kenlm/build/lib/libkenlm.a;/home/ubuntu/kenlm/build/lib/libkenlm_util.a)
    -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
    -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
    -- Found LibLZMA: /usr/include (found version "5.2.2")
    -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
    -- Looking for BZ2_bzCompressInit
    -- Looking for BZ2_bzCompressInit - found
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/ubuntu/wav2letter/bindings/python/build/temp.linux-x86_64-3.6
    Scanning dependencies of target pybind11
    Scanning dependencies of target CUB
    [  0%] Creating directories for 'CUB'
    [  1%] Creating directories for 'pybind11'
    [  1%] Performing download step (git clone) for 'pybind11'
    [  2%] Performing download step (git clone) for 'CUB'
    Cloning into 'pybind11'...
    Cloning into 'CUB'...
    Note: checking out '9a19306fbf30642ca331d0ec88e7da54a96860f9'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at 9a19306 bump version to 2.2.4
    Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
    Cloning into '/home/ubuntu/wav2letter/bindings/python/build/temp.linux-x86_64-3.6/bindings/python/pybind11/src/pybind11/tools/clang'...
    Note: checking out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b <new-branch-name>

    HEAD is now at c3cceac1 update readme to 1.8.0
    [  2%] Performing update step for 'CUB'
    [  3%] No patch step for 'CUB'
    [  4%] No configure step for 'CUB'
    [  4%] No build step for 'CUB'
    [  5%] No install step for 'CUB'
    [  5%] Completed 'CUB'
    [  5%] Built target CUB
    [  6%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ViterbiPath.cu.o
    [  6%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_CriterionUtils.cu.o
    [  7%] Building NVCC (Device) object src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o
    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    CMake Error at w2l-criterion-library-cuda_generated_ViterbiPath.cu.o.Release.cmake:219 (message):
      Error generating
      /home/ubuntu/wav2letter/bindings/python/build/temp.linux-x86_64-3.6/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_ViterbiPath.cu.o

    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:84: recipe for target 'src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ViterbiPath.cu.o' failed
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ViterbiPath.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMake Error at w2l-criterion-library-cuda_generated_CriterionUtils.cu.o.Release.cmake:219 (message):
      Error generating
      /home/ubuntu/wav2letter/bindings/python/build/temp.linux-x86_64-3.6/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_CriterionUtils.cu.o

    nvcc fatal   : Unsupported gpu architecture 'compute_30'
    src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:63: recipe for target 'src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_CriterionUtils.cu.o' failed
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_CriterionUtils.cu.o] Error 1
    CMake Error at w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o.Release.cmake:219 (message):
      Error generating
      /home/ubuntu/wav2letter/bindings/python/build/temp.linux-x86_64-3.6/src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/./w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o

    src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/build.make:70: recipe for target 'src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o' failed
    make[2]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/cuda/w2l-criterion-library-cuda_generated_ForceAlignmentCriterion.cu.o] Error 1
    CMakeFiles/Makefile2:174: recipe for target 'src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/all' failed
    make[1]: *** [src/libraries/criterion/CMakeFiles/w2l-criterion-library-cuda.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
    [  8%] No patch step for 'pybind11'
    [  8%] Performing update step for 'pybind11'
    [  9%] No configure step for 'pybind11'
    [ 10%] No build step for 'pybind11'
    [ 11%] No install step for 'pybind11'
    [ 11%] Completed 'pybind11'
    [ 11%] Built target pybind11
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/wav2letter/bindings/python/setup.py", line 109, in <module>
        zip_safe=False,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ubuntu/wav2letter/bindings/python/setup.py", line 48, in run
        self.build_extensions()
      File "/home/ubuntu/wav2letter/bindings/python/setup.py", line 91, in build_extensions
        ["cmake", "--build", "."] + build_args, cwd=self.build_temp
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/ubuntu/wav2letter/bindings/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/ubuntu/wav2letter/bindings/python/

#### Additional Context
[Add any additional information here]

**Comment by tetiana-myronivska** [comment]
Hi @insub789! It says "Unsupported gpu architecture 'compute_30'" in the error log you posted. What is the GPU that you have on your machine?

**Comment by insub789** [comment]
Hi @tetiana-myronivska !!

I used to aws p3.2xlarge tesla v100 !!

**Comment by tetiana-myronivska** [comment]
Hmm I see. I was also using Tesla V100 (provided by google cloud), and it worked.

What is your CUDA version then? One thing I noticed is that it only worked on CUDA10.0 for me, but never on CUDA11.0.

**Comment by insub789** [comment]
Oh... I use CUDA11.0...

I will remove CUDA11.0 and reinstall CUDA10.0 !!

Thank you!

**Comment by insub789** [comment]
@tetiana-myronivska 

!! I have solved this problem and I can use wav2letter, fairseq 

Thanks a lot :)

**Comment by tetiana-myronivska** [comment]
@tetiana-myronivska no problem! glad it worked!

**Comment by tlikhomanenko** [comment]
We didn't switch to CUDA 11 yet and didn't test for it, so please use old version as you do and wait more updates in future! Thanks for reporting!

**Comment by LamyaMohamed** [comment]
> We didn't switch to CUDA 11 yet and didn't test for it, so please use old version as you do and wait more updates in future! Thanks for reporting!

how can I install wav2letter on CUDA11.1? what do I need to change in cmake file? I want to try and see if it works..
