### ISSUE TITLE
which model architectures could be used for streaming inference ASR purposes and which layers should be avoided

### ISSUE THREAD

**Issue by kerolos** [facebookresearch/wav2letter#864]
#### In the recipes there are many model architectures can be train but i would like to know, which one i should use:

a) local_prior_match 
c) sota/2019 End-to-end ASR
d) self_training 
c) seq2seq_tds 
d) learnable_frontend 
e) lexicon_free
f) conv_glu

for the purpose of creating a customized model, which layers should be avoid to  use in streaming ASR  such as  LayerNorm , bach normalization and what else?

**Comment by vineelpratap** [comment]
Hi,
 We support only `streaming_convnets` style architectures only at the moment. However, it is indeed possible to make other networks like `conv_glu`. But one would to do extra work to write the corresponding code for the specific module. 

Also, note that layernorm can be made streamable by not making it dependent on time axis while computing mean/var stats. Please check section 3.1.2 in https://arxiv.org/abs/2001.09727 for details.

**Comment by abhinavkulkarni** [comment]
Thanks @vineelpratap and @tlikhomanenko.

I was looking for architecture files for the AM model (`acoustic_model.bin`) provided [here](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples). I was looking under `recipes` directory of branch `v0.2` ([link](https://github.com/facebookresearch/wav2letter/tree/v0.2/recipes)) and could not find an `.arch` file for this model.

For e.g., the last layer for this model is 

```json
        {
            "name": "Linear",
            "inFeatures": 2160,
            "outFeatures": 9998
        }
```

however, when I recursively `grep` for `1200`, not a single `.arch` file shows up.

Can you please provide the recipe for the this model as I would like to find tune it on some additional data I have.

Thanks.

**Comment by tlikhomanenko** [comment]
@avidov could give more info about inference model from the examples?

**Comment by abhinavkulkarni** [comment]
Thanks @tlikhomanenko I found the arch file. Feel free to close the issue.
