### ISSUE TITLE
[Python bindings for inference]

### ISSUE THREAD

**Issue by tetiana-myronivska** [facebookresearch/wav2letter#865]
### Question
I can see that there are python bindings for training and decoding. I couldn't find python bindings for inference, so I decided to write my own and call the functions from [the streaming example](https://github.com/facebookresearch/wav2letter/blob/v0.2/inference/inference/examples/SimpleStreamingASRExample.cpp) in python. Running into multiple issues now and reconsidering my approach.
 So I guess my question is two-fold:
1. Are there any python bindings for inference available that anyone knows about?
This is in case I am trying to re-invent the wheel here.

2. I wrote a simple script for the binding with pybind11 and I am running into the error described below. Does anyone have any insights as to how to fix it?
```
bind.cc

#include <pybind11/pybind11.h>
#include "SimpleStreamingASRExample.cpp"

PYBIND11_MODULE(SimpleStreamingASRExample, m)
{
    // optional module docstring
    m.doc() = "SimpleStreamingASRExample awesome module";
    m.def("main", &main, "A function which adds two numbers");
}
```

and the compile script
```
compile.sh

clang++ -O3 -Wall -shared -std=c++11 -fPIC     \
  -undefined dynamic_lookup                    \
  -o SimpleStreamingASRExample`python3-config --extension-suffix` \
  `python3 -m pybind11 --includes`             \
  bind.cc

```

When I run `compile.sh` from the folder where the SimpleStreamingASRExample.cpp is located, I am getting the following error:
```
root@b02e17a2f462:~/wav2letter/build/inference/inference/examples# ./compile.sh
clang: warning: argument unused during compilation: '-undefined dynamic_lookup' [-Wunused-command-line-argument]
In file included from bind.cc:2:
./SimpleStreamingASRExample.cpp:73:10: fatal error: 'cereal/archives/binary.hpp' file not found
#include <cereal/archives/binary.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I understand that the `cereal/archives/binary.hpp` is missing, but I don't know how to get it.

Any help is greatly appreciated. Thank you!

**Comment by tetiana-myronivska** [comment]
Figured it was an external dependency with the `cereal` library that needed to be installed. Figuring out how to make the internal imports work now.

**Comment by tlikhomanenko** [comment]
Hi @tetiana-myronivska,

we have python binding only for the beam search decoder, featurization and ASG criterion. We don't have binding for the training and inference pipeline.

However, for the inference here is an example how can you call it from python https://github.com/facebookresearch/wav2letter/issues/865#event-3884119482. Maybe you need more advance thing with direct c++ functions communication, and then you need to write python bindings. But we don't have plans for it.

**Comment by tetiana-myronivska** [comment]
Hi @tlikhomanenko,

Thank you for clearing things up. I will give it a try to build a direct c++ functions communication with python, as you suggested.

Greatly appreciate your support and general responsiveness in this repo.
