### ISSUE TITLE
how to show batch Dimension 

### ISSUE THREAD

**Issue by yuseungwoo** [facebookresearch/wav2letter#867]
### Question
[A clear, concise description of your setup and question]
![스크린샷 2020-10-20 오후 5 57 31](https://user-images.githubusercontent.com/42972413/96564264-e4d32200-12fd-11eb-9d87-6b1d476aa99f.png).

In here, https://github.com/facebookresearch/wav2letter/wiki/Writing-architecture-files

INPUT SIZE  is like (Time, 1, NFEAT, Batch) 

I want to see input size but don't know it

please let you teach me it?

Best Regard

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
`fl::Variable` and `af::array` has the option `dims()` which return you dimentions of the tensor. So you need to add (before if condition in your screenshot:
```
std::cout << "Input tensor sizes " << input.dims() << std::endl;
```

**Comment by yuseungwoo** [comment]
Appreciate your consideration!

**Comment by yuseungwoo** [comment]
> `fl::Variable` and `af::array` has the option `dims()` which return you dimentions of the tensor. So you need to add (before if condition in your screenshot:
> 
> ```
> std::cout << "Input tensor sizes " << input.dims() << std::endl;
> ```

Appreciate your consideration!!
