### ISSUE TITLE
Unable to run streaming convnet recipe model in streaming fashion

### ISSUE THREAD

**Issue by abhinavkulkarni** [facebookresearch/wav2letter#869]
### Bug Description
Hi,

I am unable to run [streaming convnet recipe models](https://github.com/facebookresearch/wav2letter/tree/v0.2/recipes/models/streaming_convnets/librispeech) using example binaries (streaming or interactive ASR examples).

#### Reproduction Steps
I have all the requisite files present:

```bash
$ ls -1
3-gram.pruned.3e-7.bin.qt
am_500ms_future_context_dev_other.bin
decoder-unigram-10000-nbest10.lexicon
feature_extractor.bin
librispeech-train-all-unigram-10000.tokens
```

I'm running the command as follows:

```bash
$ ~/Projects/wav2letter/cmake-build-debug/inference/inference/examples/simple_streaming_asr_example \
  -acoustic_module_file am_500ms_future_context_dev_other.bin \
  -feature_module_file feature_extractor.bin \
  -language_model_file 3-gram.pruned.3e-7.bin.qt \
  -lexicon_file decoder-unigram-10000-nbest10.lexicon \
  -tokens_file librispeech-train-all-unigram-10000.tokens 
```

I get the following error:

```bash
Started features model file loading ... 
Completed features model file loading elapsed time=111 milliseconds

Started acoustic model file loading ... 
terminate called after throwing an instance of 'cereal::Exception'
  what():  Error while trying to deserialize a polymorphic pointer. Could not find type id 3
Aborted (core dumped)
```

Please note that I am able to **_successfully_** run the models provided on the [inference wiki](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples):

```bash
$ ~/Projects/wav2letter/cmake-build-debug/inference/inference/examples/simple_streaming_asr_example \
  -acoustic_module_file acoustic_model.bin \
  -feature_module_file feature_extractor.bin \
  -language_model_file language_model.bin \
  -lexicon_file lexicon.txt \
  -tokens_file tokens.txt 
```
### Platform and Hardware
Ubuntu 20.04, CPU

Thanks!

**Comment by tlikhomanenko** [comment]
cc @vineelpratap @avidov

**Comment by vineelpratap** [comment]
Hi,
 Models which are serialized using wav2letter can't be run directly with inference pipeline. Please use this tool to convert the model to a format which inference pipeline can load -  https://github.com/facebookresearch/wav2letter/blob/v0.2/Train.cpp#L436 . 

Note that it only works with `streaming_convnets` recipe.

**Comment by abhinavkulkarni** [comment]
Thanks, @vineelpratap. 

I have asked a [follow-up question ](https://github.com/facebookresearch/wav2letter/issues/888)regarding converting the sota/2019/am_tds_ctc model to an FBGEMM streaming convnets, you may want to take a look at it.

Thanks again!
