### ISSUE TITLE
Bad transcription output from Streaming_ASR

### ISSUE THREAD

**Issue by MrityunjoyS** [facebookresearch/wav2letter#870]
Trying to used [https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019] for **simple_streaming_asr_example** and **interactive_streaming_asr_example** .

Using below command :- 

```
cat /path/tmp2.wav | \
 /path/wav2letter/build/inference/inference/examples/simple_streaming_asr_example \
 acoustic_module_file /path/sota/am_resnet_ctc_librivox_dev_clean_icml.bin \
 feature_module_file /path/sota/feature_extractor.bin \
 language_model_file /path/sota/lm_librispeech_kenlm_word_4g_200kvocab.bin \
 lexicon_file /path/sota/librispeech-train+dev-unigram-10000-nbest10.lexicon \
 tokens_file /path/sota/librispeech-train-all-unigram-10000.tokens \
 decoder_options_file /path/wav2letter/decoder_options.json
```
decoder.json file ->
```
{
  "beamSize" : 100,
  "beamSizeToken" : 100,
  "beamThreshold" : 100,
  "lmWeight" : 0.674,
  "wordScore" : 0.628,
  "unkScore" : -Infinity,
  "silScore" : 0.0,
  "eosScore" : 0.0,
  "logAdd" : false,
  "criterionType" : "CTC"
}

```

But the transcription output is very poor as in, the audio not getting recognised properly. Any suggestion on how to improve the recognision quality please.
Thanks in advance.

**Comment by tetiana-myronivska** [comment]
@MrityunjoyS I am facing a similar issue with the streaming ASR quality. At the same time, the accuracy of the same model in the decoding mode is much higher.
Did you figure out the reason/solution for it?

**Comment by tlikhomanenko** [comment]
Could you send more details on repro? cc @avidov

**Comment by tetiana-myronivska** [comment]
Hi @tlikhomanenko. When running the same audios with `/root/wav2letter/build/Decoder` and `simple_streaming_asr_eample`, I would get different transcripts, the one run in the streaming having wrong words and missing words. Apparently, it was caused by pruning in the inference mode. Got an answer [here](https://github.com/facebookresearch/wav2letter/issues/885).
