### ISSUE TITLE
How to get CER of each letter?

### ISSUE THREAD

**Issue by samin9796** [facebookresearch/wav2letter#871]
I have more than 70 letters. I want to get the error rates of each of these letters (total number of times a letter is incorrectly predicted while testing). Where is the code for calculating CER in wav2letter? Is there any easy way/suggestion I can follow?

Thank you!

**Comment by vineelpratap** [comment]
Hi, this is the place where we add tokens array to an `EditDistanceMeter` for calculating CER https://github.com/facebookresearch/wav2letter/blob/v0.2/Train.cpp#L436 . 

You will have to modify the code here appropriately.
