### ISSUE TITLE
How to use streaming_asr in real time and using streaming_asr for audio files other than .wav

### ISSUE THREAD

**Issue by MrityunjoyS** [facebookresearch/wav2letter#872]
Trying to use [https://github.com/facebookresearch/wav2letter/tree/master/recipes/models/sota/2019] for **simple_streaming_asr_example** and **interactive_streaming_asr_example** . 

- Is there way I can integrate the[simple_streaming_asr_example]( https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#simple-streaming-asr-example) to receive audio in live stream and give transcription.

- And one more thing is that the **streaming_asr** is working good enough for **.wav** but giving bad transcription or not transcription for any other format, is there any way to rectify it.

For example -->
1. with .wav file ::-

```
cat /path/tmp2.wav | \
 /path/wav2letter/build/inference/inference/examples/simple_streaming_asr_example \
 acoustic_module_file /path/sota/am_resnet_ctc_librivox_dev_clean_icml.bin \
 feature_module_file /path/sota/feature_extractor.bin \
 language_model_file /path/sota/lm_librispeech_kenlm_word_4g_200kvocab.bin \
 lexicon_file /path/sota/librispeech-train+dev-unigram-10000-nbest10.lexicon \
 tokens_file /path/sota/librispeech-train-all-unigram-10000.tokens \
 decoder_options_file /path/wav2letter/decoder_options.json
```

Output ::

> #start (msec), end(msec), transcription
> 0,1000,
> 1000,2000,he tells 
> 2000,3000,us that at this 
> 3000,4000,festive season 
> 4000,5000,of the year 
> 5000,6000,with christmas 
> 6000,7000,and roast beef 
> 7000,8000,looming before us 
> 8000,9000,
> 9000,10000,similes drawn from eating 
> 10000,11000,and its results 
> 11000,12000,occur most readily readily 
> 12000,12485,readily to the mind

2. with .flac file ::-

```
cat /path/tmp2.flac | \
 /path/wav2letter/build/inference/inference/examples/simple_streaming_asr_example \
 acoustic_module_file /path/sota/am_resnet_ctc_librivox_dev_clean_icml.bin \
 feature_module_file /path/sota/feature_extractor.bin \
 language_model_file /path/sota/lm_librispeech_kenlm_word_4g_200kvocab.bin \
 lexicon_file /path/sota/librispeech-train+dev-unigram-10000-nbest10.lexicon \
 tokens_file /path/sota/librispeech-train-all-unigram-10000.tokens \
 decoder_options_file /path/wav2letter/decoder_options.json
```
Output ::

> #start (msec), end(msec), transcription
> 0,1000,
> 1000,2000,h h h h 
> 2000,3000,h h 
> readTransformIntoBuffer(buffer=IOBuffer:{name_= offsetInBytes_=0 buf_.size()=65536 sizeInBytes_=1280} ,sizeInBufferType=8000) read 23997 bytes that is not devisible by 2
> 3000,3749,
> 3749,3749,
> Completed converting audio input from stdin to text... elapsed time=1789 milliseconds

**Can you please provide some insights on above two issues. Thanks in advance.**

**Comment by vineelpratap** [comment]
Hi, 
  To keep it simple, it might be better to convert the `.flac` to `.wav` using `sox` and use it.
   If you want to use `.flac` files, you would have to use a C++ `.flac` loader and modify the code [here](https://git.io/JT18n) such that the `istream` object corresponds to PCM16 array.

**Comment by MrityunjoyS** [comment]
Hi @vineelpratap , thanks for the suggestion. But I'm trying to use this for real time audio stream, in which I'll not be receiving a complete audio file that can be loaded in any required format. The input will be coming as raw audio that needs to be recognised by the streaming_asr and give output in the go

**Comment by vineelpratap** [comment]
Hi, you can take a look at the example here - https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#interactive-streaming-asr-example and adapt the code for your use case. 

The example mentioned about also takes `.wav` audio as a stream.

**Comment by light42** [comment]
Hi @vineelpratap, I intent to create a live-streaming service from this. For now, my goal is to make it so that it could handle running 1000 live-streams at the same time.

But I must admit that this is outside of my wisdom as a junior developer, so if you don't mind I want to discuss about what tech stack I could use so that I could achieve that goal.

P.S: I've already create my custom docker container for simple streaming asr api, and boy did it go sooo fast, I'm really impressed.
