### ISSUE TITLE
Using wav2vec2.0 model for ASR

### ISSUE THREAD

**Issue by MrityunjoyS** [facebookresearch/wav2letter#873]
I'm sorry if I'm missing something or this feature is already there or if it's not possible. 
I'm trying to get a streaming_asr for a particular domain. I've adequate audio files to train my own model and finetune it. I'm using wav2vec2.0 model for it. 
Is there any streaming_asr in wav2letter that I can integrate with my trained wav2vec2.0 model to use in real time ?

Thanks in advance for your response.

**Comment by tlikhomanenko** [comment]
did you train your wav2vec2.0 model in fairseq?

**Comment by MrityunjoyS** [comment]
@tlikhomanenko , yes mam

**Comment by tlikhomanenko** [comment]
You will need to convert them into conv layers of streaming asr by hand and then can use (like saving pytorch params vectors into txt file and then load in c++ and store in a proper way for conv operations).

**Comment by MrityunjoyS** [comment]
ok mam, thanks
