### ISSUE TITLE
How to prepare data for decoding in python?

### ISSUE THREAD

**Issue by light42** [facebookresearch/wav2letter#876]
~~I'm following the instructions for creating python decoder in python api section in the wiki.~~

~~The part that got me confused is in the wiki the file path that I must provide are only file paths for lexicon, token, and kenlm model.~~

~~Is this the bare minimum needed for running the decoder in python, or am I missing something?~~

**Comment by light42** [comment]
I want to make my own test data for python decoder like in `[/src/decoder/test](https://github.com/facebookresearch/wav2letter/tree/v0.2/src/decoder/test)`. But it seems like the steps to do it is missing from the wiki.

**Comment by tlikhomanenko** [comment]
Hi @light42, thanks for your question, later I will add to the wiki too, but for now you can have a look at discussion with the same question here https://github.com/facebookresearch/wav2letter/issues/614.

Closing, but feel free to reopen if any other assistant is needed.

**Comment by light42** [comment]
It's not related to the question but I have quite large lexicon/token files, and this code in Wiki:

```
from wav2letter.decoder import Trie, SmearingMode


trie = Trie(token_dict.index_size(), sil_idx)
start_state = lm.start(False)

for word, spellings in lexicon.items():
    usr_idx = word_dict.get_index(word)
    _, score = lm.score(start_state, usr_idx)
    for spelling in spellings:
        spelling_idxs = tkn_to_idx(spelling, token_dict, 1) # convert spelling string into vector of indices
        trie.insert(spelling_idxs, usr_idx, score)

    trie.smear(SmearingMode.MAX) # propagate word score to each spelling node to have some lm proxy score in each node.
```
took around 3 hours to run.

Is there a way to optimize this, or at least make the wav2letter._decoder.trie object persistent? It's making it really frustrating to debug.

Or is the only choice I have is to keep the session running via Ipython/Jupyter?

**Comment by tlikhomanenko** [comment]
> I want to make my own test data for python decoder like in [/src/decoder/test](https://github.com/facebookresearch/wav2letter/tree/v0.2/src/decoder/test). But it seems like the steps to do it is missing from the wiki.

The data there are your lexicon, tokens, lm and saved emissions. So I sent solution how to store emissions, the rest is just your files depending on the task.

> It's not related to the question but I have quite large lexicon/token files, and this code in Wiki:

What is number of rows in your tokens and lexicon file? You can precompute lm scores and save them and then load in trie construction. To save precomputed trie - not sure if this is doable.

Often 200k words in lexicon is enough to for good decoding, and it should be fast.

**Comment by light42** [comment]
Yeah, I could already run the code without any crash, the output is still wrong, but it's probably the fault of my configuration, I could fixed this, no worries.

The number of rows is 10000, I want to say there's something wrong with the lexicon/tokens file, but it worked perfectly when I run decoder without bindings, so I really have no clue what's going on.

Closing this, since I already have the answers I need.

**Comment by kaleko** [comment]
@light42 Out of curiosity, were you able to solve the issue of creating the trie w/ python bindings taking 3 hours? I am encountering the same issue.

**Comment by kaleko** [comment]
For those interested, I've identified the issue with trie creation for large lexicon (100k+ lines) taking a long time with the python implementation as shown in the readme here: https://github.com/flashlight/flashlight/blob/main/bindings/python/README.md

The issue is that the line `trie.smear(SmearingMode.MAX)` is incorrectly indented, causing smearing to be applied each time a word is inserted into the trie. In reality, it should be smeared only once after all words are inserted (e.g. matching the pytorch implementation here: https://pytorch.org/audio/main/_modules/torchaudio/models/decoder/_ctc_decoder.html#ctc_decoder).

Unindenting this line causes the ~3 hours trie creation to drop down to a few seconds. I recommend the README be corrected.
