### ISSUE TITLE
[Inference Run by python call]

### ISSUE THREAD

**Issue by tranmanhdat** [facebookresearch/wav2letter#878]
### Bug Description
i try to run inference with call from python but it leads to an error : AttributeError: 'bytes' object has no attribute 'format'
![Screenshot from 2020-11-05 09-37-46](https://user-images.githubusercontent.com/30494878/98190917-a7e86b80-1f4a-11eb-91c4-cedfe222654c.png)

#### Reproduction Steps

I follow instruction here [Inference Run Example](https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples#interactive-streaming-asr-example)

### Platform and Hardware
[Ubuntu 18.04, Nvidia 1050ti 4gb, python 3.6.9, docker nvidia 2]

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
What python version are you using? so you need to pass binary string with content "input=/path/to/file".

**Comment by tranmanhdat** [comment]
it need a sleep after calling process, i think it need time to load model
