### ISSUE TITLE
Unable to reproduce the result of paper

### ISSUE THREAD

**Issue by keshawnhsieh** [facebookresearch/wav2letter#88]
Using pre-trained model named librispeech-glu-highdropout.bin provied in repo, I can only reach WER 5.15% on test-clean with a 4-gram language model (one provided in this repo too). However it should be 4.8% as promised in paper.

**Comment by andresy** [comment]
Closing as we do not support the lua version of wav2letter anymore - latest recipes of the C++ version should make it easier to reproduce our numbers.
