### ISSUE TITLE
I counldn't find wav2letter/build/Train train 

### ISSUE THREAD

**Issue by AghilasSini** [facebookresearch/wav2letter#881]
Hi,

After installing wav2letter

![wav2letter_install](https://user-images.githubusercontent.com/16865777/98391610-25010700-2057-11eb-8dba-a810a52eb5f2.png)

I am trying to reproduce the recipe **learnable_frontend**,

After passing the stage of data preparation, I am actually facing issues related to the training stage because I couldn't find  **wav2letter/build/Train**? Is this related to the installation process or the Train script doesn't exist anymore?

Thank you so much for your help.

Best regards,

**Comment by ML6634** [comment]
It would be much easier if you use Docker instead:

Building Running with Docker
https://github.com/facebookresearch/wav2letter/wiki/Building-Running-with-Docker

**Comment by tlikhomanenko** [comment]
@AghilasSini 

We moved the codebase into flashlight, where we do restructure and a lot of improvements and new releases. Either use wav2letter with branch v0.2 (right before we moved the codebase) or please have a look at latest state of flashlight repo.

**Comment by AghilasSini** [comment]
Hi @tlikhomanenko,

Thank you so much for your quick answer and for your help. the problem is solved.

Best regards,
