### ISSUE TITLE
Kill the running Decoding inside Docker container 

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#883]
May I ask how to kill the running Decoding inside a Docker container? I would like to keep the Training I have done, so I do not like to remove the container.

I closed the Window on which the Decoding was running. However, it sounds that it did not kill the running Decoding command. Thanks.

**Comment by tlikhomanenko** [comment]
it is the same process as in standard Linux, so htop, find the process and kill it. You can do it in your terminal without attaching to container or run `docker exec .. bash` and their htop/top and kill the process.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for helping it out! It works!
