### ISSUE TITLE
Example links are broken for inference framework in wiki 

### ISSUE THREAD

**Issue by nihiluis** [facebookresearch/wav2letter#889]
https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples

i.e.
https://github.com/facebookresearch/wav2letter/blob/master/inference/inference/examples/SimpleStreamingASRExample.cpp

**Comment by nihiluis** [comment]
I don't know how to change the label, sorry.

**Comment by tlikhomanenko** [comment]
We are moving all codebase into flashlight, still in progress. Please in all link just use instead of master the branch v0.2 like https://github.com/facebookresearch/wav2letter/blob/v0.2/inference/inference/examples/SimpleStreamingASRExample.cpp
