### ISSUE TITLE
Is wav2vec 2.0 supported by wav2letter inference framework in streaming mode?

### ISSUE THREAD

**Issue by akademi4eg** [facebookresearch/wav2letter#892]
### Question
Can I run a model trained using Wav2Vec 2.0 approach in a streaming fashion using wav2letter-inference?

#### Additional Context
I guess it is a double question:
1. Is online ASR possible with Wav2Vec 2.0?
2. If yes, is it supported by wav2letter-inference?

**Comment by tlikhomanenko** [comment]
cc @vineelpratap

**Comment by abhinavkulkarni** [comment]
@akademi4eg: Only streaming convnets can be run in streaming fashion with `FBGEMM` backend. The [recipe link for those](https://github.com/facebookresearch/wav2letter/tree/v0.2/recipes/models/streaming_convnets) produces a `Flashlight` model that needs to be converted to an `FBGEMM` model using a convertor tool.

The [wav2vec 2.0 models](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md?fbclid=IwAR0qtyOMrK8Vf10LQip85YGCcgYv4pXcfnPYSvEb_pE-dfzAqGVrxz83TK4) are in `fairseq`, a seq2seq library that uses PyTorch. You will have to write the conversation tool to convert `fairseq` models to `FBGEMM` one. I don't think it's that trivial.

**Comment by vineelpratap** [comment]
Hi, 
 Yes, as mentioned above it is doable but it is not supported natively. So, one has to do the extra work to write the specific code for the necessary modules.
