### ISSUE TITLE
Cmake Error while building wav2letter

### ISSUE THREAD

**Issue by ishan-modi** [facebookresearch/wav2letter#895]
Hi Facebook team, I have encountered the following error while building wav2letter

-- flashlight found (include:  lib: flashlight::flashlight )
CMake Error at CMakeLists.txt:103 (message):
  flashlight must be build in distributed mode for wav2letter++

-- Configuring incomplete, errors occurred!
See also "/home/ishan/Vscode/wav2letter/build/CMakeFiles/CMakeOutput.log".

This is same error mentioned in following link,

_https://github.com/facebookresearch/wav2letter/issues/227#issue-416527092_

but the solution is not available please help 

I have built Flashlight with the following command:
**cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU -DFL_BUILD_DISTRIBUTED=ON**

and building wav2letter with following command.
**cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_CRITERION_BACKEND=CPU**

**Comment by abhinavkulkarni** [comment]
@ishan-modi: Can you retry by exactly replicating steps in the [Dockerfile](https://github.com/facebookresearch/wav2letter/blob/v0.2/Dockerfile-CUDA)?

**Comment by ishan-modi** [comment]
Thank you for the response. I figured out that flashlight v0.2 was missing in my case
