### ISSUE TITLE
A default value needs to be assigned to iter for Resnet CTC training

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#898]
For Resnet CTC training,  I think <pre>--iter=500</pre> used to be there in the config file. However, now it is not there anymore:

https://github.com/facebookresearch/wav2letter/blob/master/recipes/sota/2019/librispeech/train_am_resnet_ctc.cfg

And it sounds that there is no built-in assignment for <pre>iter</pre> either. So, when one runs the training, he will get:

<pre>--iter=9223372036854775807</pre>

which is maximum value for a 64-bit signed integer. My understanding is that

<pre>500</pre>

might not be quite correct value for  <pre>iter</pre> It sounds that another default value needs to be assigned to it instead.

**Comment by abhinavkulkarni** [comment]
@ML6634: If `iter` flag is not provided, max int value is assigned as defined in `Defines.cpp`:

```bash
DEFINE_int64(iter, std::numeric_limits<int64_t>::max(), "number of updates");
```

Idea is to let the training run loop forever and monitor the loss on dev datasets and use early stopping when the loss starts plateauing.

**Comment by ML6634** [comment]
Thank @abhinavkulkarni for the helpful comment!
