### ISSUE TITLE
wav2letter compile error 

### ISSUE THREAD

**Issue by jaeho-kang** [facebookresearch/wav2letter#9]
hello 

i download codes from git 

git clone https://github.com/facebookresearch/wav2letter.git
cd wav2letter
cd gtn && luarocks make rocks/gtn-scm-1.rockspec && cd ..   -> OK
cd speech && luarocks make rocks/speech-scm-1.rockspec && cd .. --> OK
cd torchnet-optim && luarocks make rocks/torchnet-optim-scm-1.rockspec && cd .. --> OK

cd wav2letter && luarocks make rocks/wav2letter-scm-1.rockspec && cd .. --> error

error message is following sentences 

wav2letter git:(master) ✗ cd wav2letter && luarocks make rocks/wav2letter-scm-1.rockspec && cd ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Compiling with OpenMP support
-- Found Torch7 in /home/nuri/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nuri/git/wav2letter/wav2letter/build.luarocks
Scanning dependencies of target waveval
[ 12%] Building C object CMakeFiles/waveval.dir/libwaveval/waveval.c.o
make[2]: *** No rule to make target '/home/nuri/torch/install/lib/libluajit.so', needed by 'libwaveval.so'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/waveval.dir/all' failed
make[1]: *** [CMakeFiles/waveval.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jaeho-kang** [comment]
i solve it ^^

**Comment by huynguyentn** [comment]
Hi jaeho-kang
I got the same. How did you solved it?
