### ISSUE TITLE
How to build wav2letter so that it can generate "Train" "Test" and "Decode" binary files?

### ISSUE THREAD

**Issue by yyan7223** [facebookresearch/wav2letter#906]
### Question
Hi facebook team,
I am currently trying to reproduce the experiment results of [[NEW SOTA] Synnaeve et al. (2020): End-to-end ASR: from Supervised to Semi-Supervised Learning with Modern Architectures](https://github.com/facebookresearch/wav2letter/blob/master/recipes/sota/2019)
but I cannot find three binary files after building, please help me.

Following is the command I used to build flashlight and wav2letter++

**flashlight**
```
git clone --recursive https://github.com/facebookresearch/flashlight.git 
cd flashlight 
mkdir -p build && cd build 
cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA -DArrayFire_DIR=/opt/arrayfire/share/ArrayFire/cmake/ 
make -j8
make install
```

**wav2letter++**
```
git clone --recursive https://github.com/facebookresearch/wav2letter.git
cd wav2letter 
mkdir -p build && cd build 
cmake -DCMAKE_BUILD_TYPE=Debug -DW2L_BUILD_TESTS=OFF -DW2L_INFERENCE_BUILD_TESTS=OFF -DW2L_BUILD_TOOLS=ON -DW2L_BUILD_INFERENCE=ON -DW2L_INFERENCE_BACKEND=fbgemm -G "CodeBlocks - Unix Makefiles" /content/wav2letter
make -j8
```
They can both be successfully built.

**Comment by yyan7223** [comment]
**This is the building log for wav2letter, seems that it doesn't have any relationship with flashlight**

Cloning into 'wav2letter'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 6258 (delta 4), reused 14 (delta 3), pack-reused 6225
Receiving objects: 100% (6258/6258), 5.98 MiB | 25.51 MiB/s, done.
Resolving deltas: 100% (4019/4019), done.
/content/wav2letter
/content/wav2letter/build
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=/usr/lib/x86_64-linux-gnu/libfftw3.so
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- Found FFTW3: /usr/include  
-- Could NOT find Ogg (missing: Ogg_DIR)
-- Found Ogg: /usr/lib/x86_64-linux-gnu/libogg.so (found version "1.3.2") 
-- Could NOT find Vorbis (missing: Vorbis_DIR)
-- Could NOT find Ogg (missing: Ogg_DIR)
-- Found Vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so (found version "1.3.5") 
-- Found VorbisEnc: /usr/lib/x86_64-linux-gnu/libvorbisenc.so (found version "1.3.5") 
-- Could NOT find Ogg (missing: Ogg_DIR)
-- Found FLAC: /usr/lib/x86_64-linux-gnu/libFLAC.so (found version "1.3.2") 
-- Could NOT find SndFile (missing: SndFile_DIR)
-- Found SndFile: /usr/include  
-- Found libsndfile: (lib: /usr/lib/x86_64-linux-gnu/libsndfile.so include: /usr/include
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /content/wav2letter/build
Scanning dependencies of target analyze_pseudo_label_dataset
Scanning dependencies of target SerializeConvLM
[ 14%] Building CXX object recipes/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/Utils.cpp.o
[ 28%] Building CXX object recipes/self_training/pseudo_labeling/CMakeFiles/analyze_pseudo_label_dataset.dir/AnalyzeDataset.cpp.o
[ 42%] Building CXX object recipes/utilities/convlm_serializer/CMakeFiles/SerializeConvLM.dir/Serialize.cpp.o
[ 57%] Linking CUDA device code CMakeFiles/analyze_pseudo_label_dataset.dir/cmake_device_link.o
[ 71%] Linking CXX executable analyze_pseudo_label_dataset
[ 71%] Built target analyze_pseudo_label_dataset
[ 85%] Linking CUDA device code CMakeFiles/SerializeConvLM.dir/cmake_device_link.o
[100%] Linking CXX executable SerializeConvLM
[100%] Built target SerializeConvLM

**Comment by yyan7223** [comment]
@jacobkahn Hi, can you help me?

**Comment by tlikhomanenko** [comment]
Right now we have moved all wav2letter code base into flashlight, so either follow instructions in the flashlight master or use branch v0.2 both in flashlight and wav2letter
