### ISSUE TITLE
can wav2letter train model for Mandarin

### ISSUE THREAD

**Issue by wujsy** [facebookresearch/wav2letter#91]
Hi, can wav2letter train model for Mandarin?

**Comment by vineelpratap** [comment]
Hi, 
  We have currently worked only on English and haven't tried Mandarin yet. However, e2e systems have been shown to work on Mandarin. So, I believe one can make Wav2letter work on Mandarin with some modifications to architecture and scaling the system to handle large alphabet size in Mandarin.
