### ISSUE TITLE
Resnet CTC training using telephone data

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#910]
(1) When I did Resnet CTC training using telephone data, I got:

<pre>I1208 23:26:41.493108    31 Train.cpp:568] Shuffling trainset
I1208 23:26:41.493173    31 Train.cpp:575] Epoch 1 started!
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  could not open file /root/w2l/audios/PhDt/CHm4Train/A/1038_A_10.wav
*** Aborted at 1607470001 (unix time) try &quot;date -d @1607470001&quot; if you are using GNU date ***
PC: @     0x7fd1adc17e97 gsignal
*** SIGABRT (@0x1f) received by PID 31 (TID 0x7fd1f34e9380) from PID 31; stack trace: ***
    @     0x7fd1eb7fd890 (unknown)
    @     0x7fd1adc17e97 gsignal
    @     0x7fd1adc19801 abort
    @     0x7fd1ae60c957 (unknown)
    @     0x7fd1ae612ab6 (unknown)
    @     0x7fd1ae612af1 std::terminate()
    @     0x7fd1ae612d24 __cxa_throw
    @     0x564d00a21fd7 w2l::loadSound&lt;&gt;()
    @     0x564d00a38c13 w2l::W2lListFilesDataset::getLoaderData()
    @     0x564d00a27a17 w2l::W2lDataset::getFeatureData()
    @     0x564d00a291f6 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x564d00a2975e w2l::W2lDataset::get()
    @     0x564d0084e68e _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl
    @     0x564d007e24d8 main
    @     0x7fd1adbfab97 __libc_start_main
    @     0x564d00848e4a _start
Aborted (core dumped)
</pre>

I could open that wav file myself. Any comments about this issue?

(2) In the target transcripts in the list file, there are some statements such as: [[there are background noises throughout this conversation but they in no way interfere with the speakers]], {laugh}, [squeak], ((Well)), [click], and [static] etc. I need to take them off before the training, won't I? What about those "words" in transcripts such as %mm, uh-huh, and %um etc.? My understanding is that before the training I need to convert all letters in transcripts to lowercase, and remove all punctuation marks. Right?

Thank you!

**Comment by ML6634** [comment]
I have taken care of (1).

**Comment by ML6634** [comment]
My training audios are wav files while those audios listed in --valid flag are flac files. Any way to run the training other than making both kinds of audios to the same format?

**Comment by tlikhomanenko** [comment]
My understanding - it doesn't matter what file you are reading, it will define automatically how to read. Do you see any errors if you have different formats for train and valid?

Regarding you question on target - you should do preprocessing whatever you need or define everything with lexicon file which defines mapping of words into sequence of tokens. If some word is not presented in the lexicon if will be considered as sequence of letters. Then for each sequence of tokens every token which is not presented in the tokens set will be skipped. This is the way how target transcription is constructed from the transcription in the list file.

**Comment by ML6634** [comment]
Right now for --valid flag I keep the default lists. I have got:

<pre>...
Skipping unknown token &apos;&amp;&apos; when falling back to letter target for the unknown word: &amp;Nettie
Skipping unknown token &apos;N&apos; when falling back to letter target for the unknown word: &amp;Nettie
Falling back to using letters as targets for the unknown word: ((
Skipping unknown token &apos;(&apos; when falling back to letter target for the unknown word: ((
Skipping unknown token &apos;(&apos; when falling back to letter target for the unknown word: ((
Falling back to using letters as targets for the unknown word: ))
Skipping unknown token &apos;)&apos; when falling back to letter target for the unknown word: ))
Skipping unknown token &apos;)&apos; when falling back to letter target for the unknown word: ))
Falling back to using letters as targets for the unknown word: &amp;Girard.
Skipping unknown token &apos;&amp;&apos; when falling back to letter target for the unknown word: &amp;Girard.
Skipping unknown token &apos;G&apos; when falling back to letter target for the unknown word: &amp;Girard.
Skipping unknown token &apos;.&apos; when falling back to letter target for the unknown word: &amp;Girard.
Falling back to using letters as targets for the unknown word: You
Skipping unknown token &apos;Y&apos; when falling back to letter target for the unknown word: You
Falling back to using letters as targets for the unknown word: h-
Skipping unknown token &apos;-&apos; when falling back to letter target for the unknown word: h-
Falling back to using letters as targets for the unknown word: house.
Skipping unknown token &apos;.&apos; when falling back to letter target for the unknown word: house.
Falling back to using letters as targets for the unknown word: And
Skipping unknown token &apos;A&apos; when falling back to letter target for the unknown word: And
Falling back to using letters as targets for the unknown word: %um
Skipping unknown token &apos;%&apos; when falling back to letter target for the unknown word: %um
Falling back to using letters as targets for the unknown word: &amp;Jefferson
Skipping unknown token &apos;&amp;&apos; when falling back to letter target for the unknown word: &amp;Jefferson
Skipping unknown token &apos;J&apos; when falling back to letter target for the unknown word: &amp;Jefferson
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  could not open file /root/w2l/audio/LibriSpeech/dev-clean/777/126732/777-126732-0081.flac
*** Aborted at 1607634594 (unix time) try &quot;date -d @1607634594&quot; if you are using GNU date ***
PC: @     0x7f4156f22e97 gsignal
*** SIGABRT (@0x1d) received by PID 29 (TID 0x7f419c7f4380) from PID 29; stack trace: ***
    @     0x7f4194b08890 (unknown)
    @     0x7f4156f22e97 gsignal
    @     0x7f4156f24801 abort
    @     0x7f4157917957 (unknown)
    @     0x7f415791dab6 (unknown)
    @     0x7f415791daf1 std::terminate()
    @     0x7f415791dd24 __cxa_throw
    @     0x55830a8adfd7 w2l::loadSound&lt;&gt;()
    @     0x55830a8c4c13 w2l::W2lListFilesDataset::getLoaderData()
    @     0x55830a8b3a17 w2l::W2lDataset::getFeatureData()
    @     0x55830a8b51f6 w2l::W2lDataset::getFeatureDataAndPrefetch()
    @     0x55830a8b575e w2l::W2lDataset::get()
    @     0x55830a6d8af8 _ZZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddblENKUlllddE0_clElldd
    @     0x55830a6db6af _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_IN3w2l17SequenceCriterionEES_INS3_10W2lDatasetEES_INS0_19FirstOrderOptimizerEES9_ddblE3_clES2_S5_S7_S9_S9_ddbl
    @     0x55830a66e4d8 main
    @     0x7f4156f05b97 __libc_start_main
    @     0x55830a6d4e4a _start
Aborted (core dumped)
</pre>

Thank you!

**Comment by tlikhomanenko** [comment]
can you run the same thing but
1) set train as wav list file, valid set the same as train
2) set train as flac list file, valid set the same as train

and report back if both cases worked for you?

**Comment by ML6634** [comment]
Thanks for the suggestion! Since I am going to transcribe phone audios, would it be better if I use phone wav files to replace those built-in audios listed in --valid flag? If so, any requirements for phone audios to be used for --valid flag?  What is the valid set for? Thanks again.

**Comment by ML6634** [comment]
I used phone audio wav files for the lists of both train and valid. The training went through successfully. So, it seems that we need to keep consistance for the format of files for train and valid. Any requirements for phone audios to be used for --valid flag? For example, how many  audios (each around 36s long) do we need to have? Thank you!

**Comment by ML6634** [comment]
I found the reason. Since I placed my audio folders into the folder, w2l/audio, I changed its name to w2l/audio**s**. I have changed it back. 
My phone audios are of 8kHz while those librispeech audios listed in --valid flag are of 16kHz. Do I need to add
--samplerate=8000 or not in the config file for training? I need to transcribe phone audios which just has speaking of one side (e.g. the caller), so audios have a lot of silence when the other spoke. Would it be better if replace those built-in audios listed in --valid flag by phone audios? Thank you!

**Comment by tlikhomanenko** [comment]
valid is to run validation, so it is like the same as train, no any specific meaning, that only it is not used to train a model. What do you mean by phone audio?

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the comments! A phone audio is a telephone audio, which is the recording when somebody is speaking on the phone. Our audios just have speeches of one side (either the caller or the callee). So, to transcribe a phone audio, would it be better if, when I train the model, I replace those built-in audios listed in both --train flag and --valid flag by my phone audios? And, I need to add --samplerate=8000 in the config file for training. Right? All phone audios which I will use are 8 kHz audios. Thank you!!

**Comment by tlikhomanenko** [comment]
yep, you need to set proper samplerate depending on your data. About what to use for training/valid - you can train on all data together, probably this can benefit that each dataset alone training. You can probably can be interested to look at our recent paper on domain transfer https://arxiv.org/abs/2010.11745

**Comment by ML6634** [comment]
Having replacing those built-in audios listed in both --train flag and --valid flag in the train config file by our phone audios, both Training and Decoding went through. Thank @tlikhomanenko for the nice help! 

Now I need to improve the accuracy for transcribing phone audios. In transcriptions in my list files, there are a lot of words/phrases/statements describing the status of the speaker or surroundings such as: [[there are background noises throughout this conversation but they in no way interfere with the speakers]], {laugh}, [squeak], ((Well)), {breath}, [clicking sound], and [static] etc. I think that I need to remove them. Or, if we would like to keep them, any possibility for a wav2letter model to recognize a status like that, and transcribe it out? What about those "words", in transcriptions in the list files, such as %mm, uh-huh, and %um etc.? Just add those words in the vocab set or so? Transcriptions in all list files need to be in lowercase letters only, and all punctuation marks need to be removed except apostrophes, dashes, and percent signs. Right? Right now I just use the default sets for vocab, lexicon, and tokens. How may I modify them, or even make my own sets, so that the model works better for phone audios? Thank you!

**Comment by tlikhomanenko** [comment]
You define your tokens set by yourself, so you can add even punctuation. As some special things like [laugh], [noise] etc. you can extend token set also with them to have special token for each of them and do proper pre-processing on transcription in the list file. So there is no restriction what you can have as token set and mapping between words and tokens sequence. You can have both lower case and upper case. The question only what will be simpler to learn, and maybe just post-processing with another model like punctuation can work better.

**Comment by tlikhomanenko** [comment]
I am closing this issue as we solved your main concern. Let's create another issue if you need it.

**Comment by ML6634** [comment]
Thank @tlikhomanenko for the comments, which really helps!
