### ISSUE TITLE
[Failing to upgrade flashlight and wav2letter in Docker Image on Ubuntu 20.04]

### ISSUE THREAD

**Issue by csikasote** [facebookresearch/wav2letter#912]
### Question
Hello, updating flashlight and wav2letter commands are giving me an error. Kindly help. NOTE: I dont have any GPU ..just CPU.

root@53054f6f3bc2:~/flashlight/build# cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:63 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/root/flashlight/build/CMakeFiles/CMakeOutput.log".
See also "/root/flashlight/build/CMakeFiles/CMakeError.log".

#### Additional Context
This was after a git pull command

root@53054f6f3bc2:~/flashlight# git pull
remote: Enumerating objects: 1695, done.
remote: Counting objects: 100% (1695/1695), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 13894 (delta 1563), reused 1615 (delta 1522), pack-reused 12199
Receiving objects: 100% (13894/13894), 6.95 MiB | 121.00 KiB/s, done.
Resolving deltas: 100% (9893/9893), completed with 299 local objects.
From https://github.com/facebookresearch/flashlight
   e62eb7ea..e95ad705 master                  -> origin/master
 * [new branch]      antares_conformer       -> origin/antares_conformer
 * [new branch]      antares_conformer2      -> origin/antares_conformer2
 * [new branch]      antares_dev             -> origin/antares_dev
 * [new branch]      antares_dev_d_s2s_oom   -> origin/antares_dev_d_s2s_oom
 * [new branch]      antares_dev_d_snapshot  -> origin/antares_dev_d_snapshot
 * [new branch]      antares_dev_d_thread    -> origin/antares_dev_d_thread
 * [new branch]      antares_dev_decoder_fix -> origin/antares_dev_decoder_fix
 * [new branch]      antares_dev_flags       -> origin/antares_dev_flags
 * [new branch]      antares_dev_raww_aug    -> origin/antares_dev_raww_aug
 * [new branch]      antares_dev_sinpos      -> origin/antares_dev_sinpos
 * [new branch]      antares_dev_tokenizer   -> origin/antares_dev_tokenizer
 * [new branch]      antares_dev_wnorm       -> origin/antares_dev_wnorm
 * [new branch]      antares_fix_trans       -> origin/antares_fix_trans
 * [new branch]      history_move            -> origin/history_move
 * [new branch]      release                 -> origin/release
 * [new branch]      release_consolidation   -> origin/release_consolidation
 * [new branch]      v0.2                    -> origin/v0.2
 * [new branch]      vineelpratap-patch-1    -> origin/vineelpratap-patch-1

**Comment by tlikhomanenko** [comment]
We have moved w2l codebase into flashlight and preparing huge refactor of the code. So please use branches v0.2 both for flashlight and wav2letter for now. Or switch to latest flashlight - for this check https://github.com/facebookresearch/flashlight how to install now fast with vcpkg or use another docker images from there.
