### ISSUE TITLE
[Question title here] I can't find bindings/python. 

### ISSUE THREAD

**Issue by raehyuk-yhat** [facebookresearch/wav2letter#917]
### Question
[A clear, concise description of your setup and question]
I would like to install python bindings for wav2letter.
I have installed all the dependencies as wiki: https://github.com/facebookresearch/wav2letter/wiki/Building-Python-bindings says.
I also git cloned the repository but I can't find bindings/python directory nor setup.py.

#### Additional Context
[Add any additional information here]

**Comment by abhinavkulkarni** [comment]
They are under [v0.2 branch](https://github.com/facebookresearch/wav2letter/tree/v0.2).

**Comment by tlikhomanenko** [comment]
or please visit latest version of flashlight where we moved all the codebase including python bindings.
