### ISSUE TITLE
Using pre-trained models with simple_streaming_asr_example

### ISSUE THREAD

**Issue by pletessier** [facebookresearch/wav2letter#920]
I have successfully followed the tutorial to run `simple_streaming_asr_example` with the models dowloaded from http://dl.fbaipublicfiles.com/wav2letter/inference/examples/model/

I am now trying to use the pre-trained models presented in https://github.com/facebookresearch/wav2letter/blob/master/recipes/mls/README.md.

Is that compatible ?

I have replaced : 
- `tokens.txt` with https://dl.fbaipublicfiles.com/wav2letter/mls/french/tokens.txt
- `acoustic_model.bin` with https://dl.fbaipublicfiles.com/wav2letter/mls/french/am.bin
- `lexicon.txt` with https://dl.fbaipublicfiles.com/wav2letter/mls/french/joint_lexicon.txt
- `language_model.bin` with `5-gram_lm.arpa` from https://dl.fbaipublicfiles.com/mls/mls_lm_french.tar.gz  (converted with `build_binary`)

I have an error when running `simple_streaming_asr_example` :

```
Started acoustic model file loading ... 
terminate called after throwing an instance of 'cereal::Exception'
  what():  Error while trying to deserialize a polymorphic pointer. Could not find type id 3
Aborted (core dumped)
```

`acoustic_model.bin` and https://dl.fbaipublicfiles.com/wav2letter/mls/french/am.bin are obviously not serialized in the same format.

**Comment by vineelpratap** [comment]
Hi, they are not compatible. It only supports models trianed with this recipe https://github.com/facebookresearch/wav2letter/tree/master/recipes/streaming_convnets/librispeech as of now...?


You can however, follow the commands in https://github.com/facebookresearch/wav2letter/blob/master/recipes/mls/README.md#decoding to do inference (but it won't be streaming) ....
