### ISSUE TITLE
Beam Search Decoder

### ISSUE THREAD

**Issue by bmblr497** [facebookresearch/wav2letter#921]
### Question
I was trying to run Beam search decoder on a model and came across the below error. Although the path of the model is fine its not able to load the model.

root@83530b864faf:/# /root/wav2letter/build/Decoder --am /model/acoustic_model.bin --test /model/audio --maxload 10 --nthread_decoder 2 --show --showletters --lexicon /model/lexicon.txt --uselexicon true --lm /model/language_model.bin --lmtype kenlm --decodertype wrd --beamsize 100 --beamsizetoken 100 --beamthreshold 20 --lmweight 1 --wordscore 0 --eosscore 0 --silscore 0 --unkscore 0 --smearing max
E1219 02:23:19.497965    41 Serial.h:77] Error while loading "/model/acoustic_model.bin": basic_string::_M_replace_aux
E1219 02:23:20.499104    41 Serial.h:77] Error while loading "/model/acoustic_model.bin": basic_string::_M_replace_aux
E1219 02:23:22.499753    41 Serial.h:77] Error while loading "/model/acoustic_model.bin": basic_string::_M_replace_aux
E1219 02:23:26.500145    41 Serial.h:77] Error while loading "/model/acoustic_model.bin": basic_string::_M_replace_aux
E1219 02:23:34.501024    41 Serial.h:77] Error while loading "/model/acoustic_model.bin": basic_string::_M_replace_aux
E1219 02:23:50.501910    41 Serial.h:77] Error while loading "/model/acoustic_model.bin": basic_string::_M_replace_aux
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
*** Aborted at 1608344630 (unix time) try "date -d @1608344630" if you are using GNU date ***
PC: @     0x7f1b668a9e97 gsignal
*** SIGABRT (@0x29) received by PID 41 (TID 0x7f1b720e0800) from PID 41; stack trace: ***
    @     0x7f1b677de890 (unknown)
    @     0x7f1b668a9e97 gsignal
    @     0x7f1b668ab801 abort
    @     0x7f1b6729e957 (unknown)
    @     0x7f1b672a4ae6 (unknown)
    @     0x7f1b672a4b21 std::terminate()
    @     0x7f1b672a4da9 __cxa_rethrow
    @     0x55689a864197 (unknown)
    @     0x55689a7fbf71 (unknown)
    @     0x7f1b6688cb97 __libc_start_main
    @     0x55689a860a9a (unknown)
Aborted (core dumped)

#### Additional Context
Ran using dockers.

**Comment by abhinavkulkarni** [comment]
@bmblr497: What recipe models are you using?

**Comment by bmblr497** [comment]
> @bmblr497: Which recipe models are you using?

In sota/2019, tried transformer model.

**Comment by abhinavkulkarni** [comment]
Hey @bmblr497,

The models should run as is if downloaded properly.

Did you rename the models? They should bear names such as `am_transformer_s2s_librispeech_dev_other.bin` (from this [link](https://github.com/facebookresearch/wav2letter/blob/v0.2/recipes/models/sota/2019/README.md)).
