### ISSUE TITLE
Preparing Data.

### ISSUE THREAD

**Issue by bmblr497** [facebookresearch/wav2letter#922]
### Question
I want to do decoding on  models present in '.../sota/2019'  but i am getting stuck in first step of data preparation as I am getting the errors below.

root@d8096c5ba82c:~# python3  /root/wav2letter/recipes/models/utilities/prepare_librispeech_wp_and_official_lexicon.py --data_dst /model/audio --model_dst  /model --nbest 10 --wp 10000
python3: can't open file '/root/wav2letter/recipes/models/utilities/../../../data/librispeech/prepare.py': [Errno 2] No such file or directory
Preparing tokens and lexicon for acoustic model...

Traceback (most recent call last):
  File "/root/wav2letter/recipes/models/utilities/prepare_librispeech_wp_and_official_lexicon.py", line 80, in <module>
    with open(os.path.join(lists_path, name + ".lst"), "r") as flist:
FileNotFoundError: [Errno 2] No such file or directory: '/model/audio/lists/train-clean-100.lst'

#### Additional Context
[Add any additional information here]

**Comment by abhinavkulkarni** [comment]
@bmblr497: Please change [lines 49-50](https://github.com/facebookresearch/wav2letter/blob/v0.2/recipes/models/utilities/prepare_librispeech_wp_and_official_lexicon.py#L49-L50) from

```python
        "python3 {}/../../../data/librispeech/prepare.py --dst {} -p {}".format(
            os.path.dirname(os.path.abspath(__file__)), args.data_dst, args.process
```
to 
```python
        "python3 {}/../../data/librispeech/prepare.py --dst {} -p {}".format(
            os.path.dirname(os.path.abspath(__file__)), args.data_dst, args.process
```

**Comment by tlikhomanenko** [comment]
Also please use for all code base with these pre-trained models branches v0.2 in both flashlight and wav2letter. Current master will not work with them as we changed namespacing.
