### ISSUE TITLE
i installed flashlight with vcpkg, how can i install wav2lettter

### ISSUE THREAD

**Issue by jinggaizi** [facebookresearch/wav2letter#925]
### Question
[A clear, concise description of your setup and question]

#### Additional Context
[Add any additional information here]
i installed flashlight with vcpkg, how can i set Dflashlight_DIR to install wav2letter?

**Comment by jacobkahn** [comment]
wav2letter is now contained inside of [Flashlight](https://github.com/facebookresearch/flashlight) in the [ASR Application](https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr).

To install with `vcpkg`, use `./vcpkg install flashlight[asr]`. That will install the ASR application.
