### ISSUE TITLE
Pre-trained models for conv_glu

### ISSUE THREAD

**Issue by tumusudheer** [facebookresearch/wav2letter#934]
### Question
Where can I find pre-trained models for conv_glu. I don't find them [here](https://github.com/facebookresearch/wav2letter/tree/master/recipes/conv_glu/librispeech)

Is the file [baseline_dev-clean+other](https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/am/baseline_dev-clean%2Bother.bin) the pre-trained model for conv-glu ?

Also is the lexicon-free models and conv-lm models are the same ?

Thank you

**Comment by tlikhomanenko** [comment]
Yep, lexicon-free exactly uses conv_glu models, and they are published under lexicon_free recipe. Please use them https://github.com/facebookresearch/wav2letter/tree/master/recipes/lexicon_free/librispeech
