### ISSUE TITLE
Does score in beam dump not show all score for select best hypothesis ?

### ISSUE THREAD

**Issue by trangtv57** [facebookresearch/wav2letter#936]
### Question
Hi,
I have an utterance where i have oov "titan" it's can be same as speaking 2 word in dictionary {"ti" , "tan" }. In lexicon:
titan    _ti _tan
I am using beam dump for get score of each beamsearch, as sample below. Score of AM is same in 3 beam,  although score of LM beam third is biggest, but combine LM and AM score final score of third is lowest. So I wonder the score show in beam dump is full or not, how it's happen?

Sample beam dump:
id1 | 1705.429154 | 1721.264524 | -43.264816 | 18.750000 | rồi ốc titan a nói chung ốc ti tan rồi nè rồi nói chung là đồng hồ
id2 | 1705.412166 | 1721.264524 | -44.503370 | 31.250000 | rồi ốc ti tan a nói chung ốc ti tan rồi nè rồi nói chung là đồng hồ
id3 | 1705.152164 | 1721.264524 | -42.446229 | 6.250000 | rồi ốc titan a nói chung ốc titan rồi nè rồi nói chung là đồng hồ

thanks you.

**Comment by tlikhomanenko** [comment]
The first score is total score which is equal to AM score + LM score + silscore * #silences + wordscore * #words. Do you have silscore/wordscore non-zero?

**Comment by trangtv57** [comment]
hi @tlikhomanenko ,
I miss understand about silsscore, and word score. Then i can figure out how its happen
thank you.
