### ISSUE TITLE
OOM when training stream convnet on custom data

### ISSUE THREAD

**Issue by tranmanhdat** [facebookresearch/wav2letter#937]
### Bug Description
Memory does not release when training model
in buff/cache of memory increase when start train and lead to OOM

#### Reproduction Steps
Follow [tutorials](https://github.com/facebookresearch/wav2letter/tree/master/recipes/streaming_convnets/librispeech), train on custom data( approximate 500 hours~ 150gb

### Platform and Hardware
Ubuntu 18.04.5 LTS
Intel(R) Xeon(R) CPU E5-2690 v4@ 2.60GHz
2 GPUs Tesla V100
64 GB RAM

#### Additional Context
Run with docker image cuda lastest, architect same tutorial
my flagsfile
![Screenshot from 2021-01-14 22-06-28](https://user-images.githubusercontent.com/30494878/104608805-ea4dc780-56b4-11eb-954c-c193db1bb1b8.png)
memory when run training
![Screenshot from 2021-01-14 22-02-37](https://user-images.githubusercontent.com/30494878/104608852-fa65a700-56b4-11eb-91e9-98e7f0fb98cf.png)
my Gpus
![Screenshot from 2021-01-14 22-01-42](https://user-images.githubusercontent.com/30494878/104608909-09e4f000-56b5-11eb-8307-a762df723f81.png)
train process
![Screenshot from 2021-01-14 22-09-13](https://user-images.githubusercontent.com/30494878/104609037-2b45dc00-56b5-11eb-8d5a-45ac705004a4.png)

**Comment by tlikhomanenko** [comment]
What is your longest audio?

**Comment by tranmanhdat** [comment]
> What is your longest audio?

approximate 24s, i find out after i release cached then restart docker, bug had gone, maybe docker container didn't release all cache!
