### ISSUE TITLE
[Question] Can I integrate it with my college website to transcribe the lecture videos online?

### ISSUE THREAD

**Issue by souravverma94** [facebookresearch/wav2letter#939]
I am new to ASR (Automatic Speech Recognition), I am working on a college website where professors can upload their lectures. I want to integrate an automatic speech transcript generator so that users can turn on the captions while streaming. While searching for open source options, I came across wav2letter. Could anyone please tell me whether it is possible to do that and if Yes, could you please guide me?

**Comment by tlikhomanenko** [comment]
Hi @souravverma94,

Please have a look in the flashlight repo directly as we moved wav2letter codebase into it and prepared recent tutorial on inference and voice activity detection with released model trained on several public benchmarks https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr/tutorial, colab direct link https://colab.research.google.com/github/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb. If you have any questions regarding this please create issues directly in the flashlight repo https://github.com/facebookresearch/flashlight.

Also if you need streaming inference, please have a look at the streaming model https://github.com/facebookresearch/wav2letter/tree/master/recipes/streaming_convnets and wiki on the inference code https://github.com/facebookresearch/wav2letter/wiki/Inference-Framework and tutorial on it here https://github.com/facebookresearch/wav2letter/wiki/Inference-Run-Examples
