### ISSUE TITLE
build wav2letter in Windows 10 x64 by cmake or visual studio 2017

### ISSUE THREAD

**Issue by doctorwho-123** [facebookresearch/wav2letter#942]
I try to build wav2letter in Windows 10 x64, but I can not to build flashlight
May be you know where I can download prebuilded, or may be you know where I can download wav2letter prebuilded for Windows x64
Thanks

**Comment by tlikhomanenko** [comment]
We don't support Windows build yet. Please use docker image on Windows for now.
