### ISSUE TITLE
cmake not finishing

### ISSUE THREAD

**Issue by sciai-ai** [facebookresearch/wav2letter#946]
When using cmake to compile I get these errors, I have made sure that the symbolic link cuda points to the cuda 11 but that does not help mitigate this.

cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BUILD_TESTS=OFF -DFL_BUILD_EXAMPLES=OFF -DFL_BUILD_APP_IMGCLASS=OFF -DFL_BUILD_APP_LM=OFF && make -j$(nproc)

I get this warning and then error

[ 90%] Linking CXX executable bin/asr/fl_asr_sfx_apply
[ 90%] Linking CXX executable bin/asr/fl_asr_tutorial_inference_ctc
[ 91%] Linking CXX executable bin/asr/fl_asr_tutorial_finetune_ctc
[ 91%] Linking CXX executable bin/asr/fl_asr_decode
/usr/bin/ld: warning: libnvrtc.so.10.0, needed by /opt/arrayfire/lib64/libafcuda.so.3.7.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcublas.so.10.0, needed by /opt/arrayfire/lib64/libafcuda.so.3.7.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcufft.so.10.0, needed by /opt/arrayfire/lib64/libafcuda.so.3.7.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcusolver.so.10.0, needed by /opt/arrayfire/lib64/libafcuda.so.3.7.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcusparse.so.10.0, needed by /opt/arrayfire/lib64/libafcuda.so.3.7.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /opt/arrayfire/lib64/libafcuda.so.3.7.1: undefined reference to `nvrtcGetErrorString@libnvrtc.so.10.0'

collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fl_asr_sfx_apply.dir/build.make:159: bin/asr/fl_asr_sfx_apply] Error 1
make[1]: *** [CMakeFiles/Makefile2:1244: CMakeFiles/fl_asr_sfx_apply.dir/all] Error 2

/usr/bin/ld: /opt/arrayfire/lib64/libafcuda.so.3.7.1: undefined reference to `cusolverDnSgesvd_bufferSize@libcusolver.so.10.0'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fl_asr_decode.dir/build.make:159: bin/asr/fl_asr_decode] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/fl_asr_decode.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by jacobkahn** [comment]
@sciai-ai — my this is an issue with ArrayFire prebuilt installer binary I suspect you're using, which is symlinked to CUDA 10 rather than CUDA 11. The shared objects that ArrayFire has in the pre-built package expect shared objects with CUDA 10 (`so.10.0`). Please create an issue in the ArrayFire repo and see if you can get pre-built binaries for CUDA 11.
