### ISSUE TITLE
arrayfire install hard

### ISSUE THREAD

**Issue by wbgxx333** [facebookresearch/wav2letter#95]
hi,
  when i install wav2letter,and find arrayfire is too hard to install.can you help me?

-- GTest found (library: /usr/local/lib64/libgtest.a include: /usr/local/include)
CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "FindArrayFire.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ArrayFire", but CMake did not find one.

  Could not find a package configuration file provided by "ArrayFire"
  (requested version 3.6.1) with any of the following names:

    ArrayFireConfig.cmake
    arrayfire-config.cmake

  Add the installation prefix of "ArrayFire" to CMAKE_PREFIX_PATH or set
  "ArrayFire_DIR" to a directory containing one of the above files.  If
  "ArrayFire" provides a separate development package or SDK, be sure it has
  been installed

best wishes
ben

**Comment by WilliamTambellini** [comment]
Hi, 
Well I guess you dont have installed AF 3.6.1 or you did nt specify the path to it : 
- To download/install 3.6.1 : 
http://arrayfire.s3.amazonaws.com/index.html#!/3.6.1%2F
- To cmake specifying the path : 
cmake -DArrayFire_DIR=/path/where/you/installed/AF

**Comment by benam2** [comment]
@WilliamTambellini After successfully installing Array fire, I got this error to specify the path:
` does not appear to contain CMakeLists.txt.` any idea where could be wrong? (installed through sh file)
Thanks~

**Comment by benam2** [comment]
The ArrayFire is installed in the root of my machine however, the flashlight is in another directory. Im not sure how can I set the path since Im keep getting error.

Array file is is `/home/ai-machine/arrayfire-no-gl/share/ArrayFire/cmake/ArrayFireConfig.cmake`

And Flashlight is in `/home/ai-machine/Desktop/flashlight`

I appreciate your help~ @WilliamTambellini

**Comment by benam2** [comment]
When I ran the flashlight using this command:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BUILD_ARRAYFIRE=ON -DArrayFire_DIR=../../arrayfire-no-gl/share/ArrayFire/cmake/ArrayFireConfig.cmake`

it raises this error:

`CMake Error: The source directory "/home/ai-mymachine/Desktop" does not appear to contain CMakeLists.txt.`
Any help would be really appreciate.

**Comment by benam2** [comment]
Still stuck on this error. any help I appreciated!

**Comment by Ch3nYe** [comment]
> Still stuck on this error. any help I appreciated!

Hi, Bro, I think the installation of this project is just shit!!!

**Comment by Ch3nYe** [comment]
> Still stuck on this error. any help I appreciated!

Hi Bro, well, it's rude, but I think the installation of this project is just shit !!! Sry contributors, you should make it more easy to install, or just stop this project. It's very disappointing.
