### ISSUE TITLE
How to convert W2L model to Pytorch?

### ISSUE THREAD

**Issue by DongChanS** [facebookresearch/wav2letter#956]
### Question

There is a method that convert Pytorch (fairseq) model to W2L.
(https://github.com/facebookresearch/wav2letter/tree/master/recipes/utilities/convlm_serializer)
 
Conversely, I want to convert W2L model parameter that pytorch supported.
(ex, `Transformer seq2seq` in https://github.com/facebookresearch/wav2letter/tree/master/recipes/sota/2019)

Is there any convenient way?

**Comment by tlikhomanenko** [comment]
Nope, we don't provide such functionality, you need to convert by yourself (you can use example of convlm converting). You can find in other issue converting TDS model (somebody successfully tried that and published in the issue the code). 

As there is no standard format (as some time ago ONNX was supposed to be) we don't support general format to convert models into other frameworks.
