### ISSUE TITLE
Run Decoder binary with mutiple GPUs

### ISSUE THREAD

**Issue by tranmanhdat** [facebookresearch/wav2letter#958]
i cant run Decoder binary with 4 GPUs, i trained with 4 gpus but cant with decode
command run decoder binary:
_./build/Decoder --am <path_to_model>/006_model_last.bin --test <path_to_lst>/train.lst --nthread_decoder 12 --lexicon  <path_to_lexicon>/unigram-7211-nbest10.lexicon --uselexicon true --decodertype wrd --beamsize 100 --beamsize 100 --beamthreshold 20  --lmweight 0.6 --wordscore 0.6 --eosscore 0 --silscore 0 --unkscore 0  --smearing max -sclite <path_to_log>/decode_log/_

**Comment by tlikhomanenko** [comment]
You need to specify `--nthread_decoder_am_forward=4` which will use 4 gpus to run forward pass on your test data. `--nthread_decoder` is used for dddecoding itself which happens on cpu in your case for zero lm or kenlm language models.

**Comment by tranmanhdat** [comment]
yeah it's really help, thanks
