### ISSUE TITLE
Inference, No results

### ISSUE THREAD

**Issue by MHumza3656** [facebookresearch/wav2letter#962]
### Question
Hello everyone,
The issue is that the inference does work but for some audios, it works so well, for some it returns nothing. Could anyone help me understand what this problem is?

#### Additional Context
I'm using the example of colab given in the link below: https://colab.research.google.com/github/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb#scrollTo=w-LBEbd_zbg7

**Comment by tlikhomanenko** [comment]
Closing this issue here, please create directly in Flashlight repo. Also please add info on repro, for example give an audio file for which you see empty output.
