### ISSUE TITLE
Building with Ubuntu 18.04 completely broken

### ISSUE THREAD

**Issue by syb0rg** [facebookresearch/wav2letter#97]
As stated in the title, building with Ubuntu 18.04 is a pain.  There are many issues I've had with compiling, too many to put in this issue.  I'll try and give you all my relevant build properties so you can attempt to replicate yourselves.

```
~/Downloads/wav2letter/build$  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

~/Downloads/wav2letter/build$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

~/Downloads/wav2letter/build$ cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 2

~/Downloads/wav2letter/build$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/Downloads/wav2letter/build$ g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

~/Downloads/wav2letter/build$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

As mentioned in a previous issue, all dependencies were successfully built and installed beforehand.  Let me know if you need any more information.

**Comment by jacobkahn** [comment]
Thanks for flagging/providing this info @syb0rg — looking into it now.

**Comment by jacobkahn** [comment]
@syb0rg - I wasn't able to reproduce any issues on Ubuntu 18.04 with g++ 7.3. We recently [stopped disabling GNU compiler extensions](https://github.com/facebookresearch/flashlight/commit/b0a15636bbcbc2e1f6db9ba54066009b49ace3e4) in flashlight and wav2letter, which was causing issues — can you try rebuilding/installing [flashlight](https://github.com/facebookresearch/flashlight) from master, then rebuilding wav2letter from master?

**Comment by syb0rg** [comment]
@jacobkahn Sure, I pulled down the recent commits for wav2letter before I created this issue, I'll try rebuilding flashlight from master and see if I'm able to resolve.

**Comment by syb0rg** [comment]
@jacobkahn Looks like rebuilding the updated flashlight code fixed it, I'm now able to successfully build it.  Thanks!
