### ISSUE TITLE
Just curious, is ArrayFire faster than PyTorch's C++? Otherwise, why don't you guys use PyTorch's C++?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/wav2letter#98]

**Comment by jacobkahn** [comment]
A few comments here.
- flashlight was started as a project before the PyTorch C++ API existed.
- flashlight (and many of the tensor operations in wav2letter) are built on ArrayFire, whereas PyTorch is built on ATen. If you're curious as to some reasons for choosing ArrayFire, take a look at [this issue](https://github.com/facebookresearch/flashlight/issues/1).
- In general, ArrayFire provides several performance and usability benefits including a fully-featured JIT and multiple-backend support out of the box. ArrayFire is still under development and has an active community.
